const rb2020PPRRedraftADP = [
  [
    {
      '"RB"': '"1"',
      '"Overall"': '"1"',
      '"Player"': '"Christian McCaffrey"',
      '"Team"': '"SF"',
      '"Bye"': '"11"',
      '"CBS"': '"1"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"1.0"',
    },
    {
      '"RB"': '"2"',
      '"Overall"': '"2"',
      '"Player"': '"Saquon Barkley"',
      '"Team"': '"PHI"',
      '"Bye"': '"9 "',
      '"CBS"': '"2"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"2.3"',
    },
    {
      '"RB"': '"3"',
      '"Overall"': '"3"',
      '"Player"': '"Ezekiel Elliott"',
      '"Team"': '"NE"',
      '"Bye"': '"5"',
      '"CBS"': '"3"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"2.8"',
    },
    {
      '"RB"': '"4"',
      '"Overall"': '"4"',
      '"Player"': '"Derrick Henry"',
      '"Team"': '"BAL"',
      '"Bye"': '"7"',
      '"CBS"': '"6"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"4.8"',
    },
    {
      '"RB"': '"5"',
      '"Overall"': '"5"',
      '"Player"': '"Dalvin Cook"',
      '"Team"': '"BAL"',
      '"Bye"': '"7"',
      '"CBS"': '"5"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"5.3"',
    },
    {
      '"RB"': '"6"',
      '"Overall"': '"7"',
      '"Player"': '"Alvin Kamara"',
      '"Team"': '"NO"',
      '"Bye"': '"6"',
      '"CBS"': '"4"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"5.5"',
    },
    {
      '"RB"': '"7"',
      '"Overall"': '"9"',
      '"Player"': '"Clyde Edwards-Helaire"',
      '"Team"': '"KC"',
      '"Bye"': '"10"',
      '"CBS"': '"7"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"7.8"',
    },
    {
      '"RB"': '"8"',
      '"Overall"': '"12"',
      '"Player"': '"Josh Jacobs"',
      '"Team"': '"GB"',
      '"Bye"': '"5"',
      '"CBS"': '"8"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"8.8"',
    },
    {
      '"RB"': '"9"',
      '"Overall"': '"8"',
      '"Player"': '"Nick Chubb"',
      '"Team"': '"CLE"',
      '"Bye"': '"9"',
      '"CBS"': '"10"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"9.0"',
    },
    {
      '"RB"': '"10"',
      '"Overall"': '"10"',
      '"Player"': '"Joe Mixon"',
      '"Team"': '"HOU"',
      '"Bye"': '"8"',
      '"CBS"': '"11"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"9.8"',
    },
    {
      '"RB"': '"11"',
      '"Overall"': '"15"',
      '"Player"': '"Aaron Jones"',
      '"Team"': '"MIN"',
      '"Bye"': '"7"',
      '"CBS"': '"12"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"11.0"',
    },
    {
      '"RB"': '"12"',
      '"Overall"': '"22"',
      '"Player"': '"Austin Ekeler"',
      '"Team"': '"WAS"',
      '"Bye"': '"8"',
      '"CBS"': '"9"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"12.3"',
    },
    {
      '"RB"': '"13"',
      '"Overall"': '"18"',
      '"Player"': '"Kenyan Drake"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"14"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"12.5"',
    },
    {
      '"RB"': '"14"',
      '"Overall"': '"19"',
      '"Player"': '"Miles Sanders"',
      '"Team"': '"CAR"',
      '"Bye"': '"13"',
      '"CBS"': '"13"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"12.5"',
    },
    {
      '"RB"': '"15"',
      '"Overall"': '"27"',
      '"Player"': '"Todd Gurley II"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"16"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"16.0"',
    },
    {
      '"RB"': '"16"',
      '"Overall"': '"28"',
      '"Player"': '"Chris Carson"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"17"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"16.8"',
    },
    {
      '"RB"': '"17"',
      '"Overall"': '"35"',
      '"Player"': '"James Conner"',
      '"Team"': '"ARI"',
      '"Bye"': '"8"',
      '"CBS"': '"15"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"17.3"',
    },
    {
      '"RB"': '"18"',
      '"Overall"': '"31"',
      '"Player"': '"David Johnson"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"19"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"18.5"',
    },
    {
      '"RB"': '"19"',
      '"Overall"': '"32"',
      '"Player"': '"Jonathan Taylor"',
      '"Team"': '"IND"',
      '"Bye"': '"7"',
      '"CBS"': '"22"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"19.8"',
    },
    {
      '"RB"': '"20"',
      '"Overall"': '"44"',
      '"Player"': '"Le\'Veon Bell"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"18"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"21.0"',
    },
    {
      '"RB"': '"21"',
      '"Overall"': '"41"',
      '"Player"': '"Melvin Gordon III"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"20"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"21.0"',
    },
    {
      '"RB"': '"22"',
      '"Overall"': '"43"',
      '"Player"': '"Mark Ingram II"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"21"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"21.5"',
    },
    {
      '"RB"': '"23"',
      '"Overall"': '"46"',
      '"Player"': '"Raheem Mostert"',
      '"Team"': '"MIA"',
      '"Bye"': '"7 "',
      '"CBS"': '"23"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"22.0"',
    },
    {
      '"RB"': '"24"',
      '"Overall"': '"40"',
      '"Player"': '"Leonard Fournette"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"25"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"22.0"',
    },
    {
      '"RB"': '"25"',
      '"Overall"': '"54"',
      '"Player"': '"Devin Singletary"',
      '"Team"': '"NYG"',
      '"Bye"': '"11"',
      '"CBS"': '"26"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"25.5"',
    },
    {
      '"RB"': '"26"',
      '"Overall"': '"60"',
      '"Player"': '"Cam Akers"',
      '"Team"': '"MIN"',
      '"Bye"': '"7"',
      '"CBS"': '"24"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"26.5"',
    },
    {
      '"RB"': '"27"',
      '"Overall"': '"64"',
      '"Player"': '"David Montgomery"',
      '"Team"': '"DET"',
      '"Bye"': '"5"',
      '"CBS"': '"31"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"27.3"',
    },
    {
      '"RB"': '"28"',
      '"Overall"': '"66"',
      '"Player"': '"Kareem Hunt"',
      '"Team"': '"CLE"',
      '"Bye"': '"9"',
      '"CBS"': '"27"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"27.8"',
    },
    {
      '"RB"': '"29"',
      '"Overall"': '"68"',
      '"Player"': '"D\'Andre Swift"',
      '"Team"': '"CHI"',
      '"Bye"': '"11"',
      '"CBS"': '"30"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"29.0"',
    },
    {
      '"RB"': '"30"',
      '"Overall"': '"84"',
      '"Player"': '"J.K. Dobbins"',
      '"Team"': '"BAL"',
      '"Bye"': '"7"',
      '"CBS"': '"28"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"31.8"',
    },
    {
      '"RB"': '"31"',
      '"Overall"': '"79"',
      '"Player"': '"Ronald Jones II"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"34"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"33.0"',
    },
    {
      '"RB"': '"32"',
      '"Overall"': '"85"',
      '"Player"': '"Jordan Howard"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"37"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"33.0"',
    },
    {
      '"RB"': '"33"',
      '"Overall"': '"88"',
      '"Player"': '"Marlon Mack"',
      '"Team"': '"ARI"',
      '"Bye"': '"8 "',
      '"CBS"': '"35"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"34.0"',
    },
    {
      '"RB"': '"34"',
      '"Overall"': '"89"',
      '"Player"': '"Kerryon Johnson"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"40"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"35.0"',
    },
    {
      '"RB"': '"35"',
      '"Overall"': '"93"',
      '"Player"': '"Phillip Lindsay"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"33"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"35.3"',
    },
    {
      '"RB"': '"36"',
      '"Overall"': '"90"',
      '"Player"': '"Sony Michel"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"43"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"36.8"',
    },
    {
      '"RB"': '"37"',
      '"Overall"': '"95"',
      '"Player"': '"James White"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"39"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"38.3"',
    },
    {
      '"RB"': '"38"',
      '"Overall"': '"109"',
      '"Player"': '"Tarik Cohen"',
      '"Team"': '"CAR"',
      '"Bye"': '"13 "',
      '"CBS"': '"29"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"39.3"',
    },
    {
      '"RB"': '"39"',
      '"Overall"': '"105"',
      '"Player"': '"Zack Moss"',
      '"Team"': '"CIN"',
      '"Bye"': '"9 "',
      '"CBS"': '"36"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"39.3"',
    },
    {
      '"RB"': '"40"',
      '"Overall"': '"101"',
      '"Player"': '"Matt Breida"',
      '"Team"': '"NYG"',
      '"Bye"': '"11"',
      '"CBS"': '"38"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"39.5"',
    },
    {
      '"RB"': '"41"',
      '"Overall"': '"103"',
      '"Player"': '"Tevin Coleman"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"42"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"40.8"',
    },
    {
      '"RB"': '"42"',
      '"Overall"': '"104"',
      '"Player"': '"Latavius Murray"',
      '"Team"': '"BUF"',
      '"Bye"': '"11"',
      '"CBS"': '"41"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"41.0"',
    },
    {
      '"RB"': '"43"',
      '"Overall"': '"124"',
      '"Player"': '"Antonio Gibson"',
      '"Team"': '"NE"',
      '"Bye"': '"5"',
      '"CBS"': '"32"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"41.3"',
    },
    {
      '"RB"': '"44"',
      '"Overall"': '"118"',
      '"Player"': '"Alexander Mattison"',
      '"Team"': '"LV"',
      '"Bye"': '"6"',
      '"CBS"': '"44"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"44.3"',
    },
    {
      '"RB"': '"45"',
      '"Overall"': '"135"',
      '"Player"': '"Chase Edmonds"',
      '"Team"': '"TB"',
      '"Bye"': '"13"',
      '"CBS"': '"48"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"48.0"',
    },
    {
      '"RB"': '"46"',
      '"Overall"': '"140"',
      '"Player"': '"Duke Johnson Jr."',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"45"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"49.0"',
    },
    {
      '"RB"': '"47"',
      '"Overall"': '"127"',
      '"Player"': '"Adrian Peterson"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"58"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"49.8"',
    },
    {
      '"RB"': '"48"',
      '"Overall"': '"147"',
      '"Player"': '"Boston Scott"',
      '"Team"': '"PHI"',
      '"Bye"': '"9"',
      '"CBS"': '"47"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"49.8"',
    },
    {
      '"RB"': '"49"',
      '"Overall"': '"136"',
      '"Player"': '"Darrell Henderson Jr."',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"53"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"46.3"',
    },
    {
      '"RB"': '"50"',
      '"Overall"': '"151"',
      '"Player"': '"AJ Dillon"',
      '"Team"': '"GB"',
      '"Bye"': '"5"',
      '"CBS"': '"54"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"52.0"',
    },
    {
      '"RB"': '"51"',
      '"Overall"': '"152"',
      '"Player"': '"Chris Thompson"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"50"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"52.3"',
    },
    {
      '"RB"': '"52"',
      '"Overall"': '"156"',
      '"Player"': '"Tony Pollard"',
      '"Team"': '"TEN"',
      '"Bye"': '"4"',
      '"CBS"': '"46"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"47.3"',
    },
    {
      '"RB"': '"53"',
      '"Overall"': '"153"',
      '"Player"': '"Justin Jackson"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"51.3"',
    },
    {
      '"RB"': '"54"',
      '"Overall"': '"139"',
      '"Player"': '"Ke\'Shawn Vaughn"',
      '"Team"': '"NE"',
      '"Bye"': '"5"',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"43.5"',
    },
    {
      '"RB"': '"55"',
      '"Overall"': '"170"',
      '"Player"': '"Nyheim Hines"',
      '"Team"': '"CLE"',
      '"Bye"': '"9"',
      '"CBS"': '"56"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"56.3"',
    },
    {
      '"RB"': '"56"',
      '"Overall"': '"171"',
      '"Player"': '"Damien Harris"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"55"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"58.0"',
    },
    {
      '"RB"': '"57"',
      '"Overall"': '"184"',
      '"Player"': '"Ryquell Armstead "',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"51"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"56.0"',
    },
    {
      '"RB"': '"58"',
      '"Overall"': '"179"',
      '"Player"': '"Darrel Williams"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"57"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"58.0"',
    },
    {
      '"RB"': '"59"',
      '"Overall"': '"186"',
      '"Player"': '"Bryce Love"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"60"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"67.3"',
    },
    {
      '"RB"': '"60"',
      '"Overall"': '"177"',
      '"Player"': '"Rashaad Penny"',
      '"Team"': '"PHI"',
      '"Bye"': '"9"',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"58.0"',
    },
    {
      '"RB"': '"61"',
      '"Overall"': '"332"',
      '"Player"': '"James Robinson"',
      '"Team"': '"NO"',
      '"Bye"': '"6"',
      '"CBS"': '"49"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"70.0"',
    },
    {
      '"RB"': '"62"',
      '"Overall"': '"213"',
      '"Player"': '"Jerick McKinnon"',
      '"Team"': '"KC"',
      '"Bye"': '"10"',
      '"CBS"': '"52"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"67.7"',
    },
    {
      '"RB"': '"63"',
      '"Overall"': '"183"',
      '"Player"': '"Jamaal Williams"',
      '"Team"': '"NO"',
      '"Bye"': '"6"',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"59.5"',
    },
    {
      '"RB"': '"64"',
      '"Overall"': '"192"',
      '"Player"': '"LeSean McCoy"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"59.5"',
    },
    {
      '"RB"': '"65"',
      '"Overall"': '"211"',
      '"Player"': '"Lamar Miller"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"57.0"',
    },
    {
      '"RB"': '"66"',
      '"Overall"': '"219"',
      '"Player"': '"Joshua Kelley"',
      '"Team"': '"LAC"',
      '"Bye"': '"6"',
      '"CBS"': '"59"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"65.3"',
    },
    {
      '"RB"': '"67"',
      '"Overall"': '"194"',
      '"Player"': '"Carlos Hyde"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"68.0"',
    },
    {
      '"RB"': '"68"',
      '"Overall"': '"235"',
      '"Player"': '"Frank Gore"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"60.0"',
    },
    {
      '"RB"': '"69"',
      '"Overall"': '"325"',
      '"Player"': '"Devine Ozigbo"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"61"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"75.0"',
    },
    {
      '"RB"': '"70"',
      '"Overall"': '"237"',
      '"Player"': '"Malcolm Brown"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"62.0"',
    },
    {
      '"RB"': '"71"',
      '"Overall"': '"275"',
      '"Player"': '"Jalen Richard"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"62"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"71.0"',
    },
    {
      '"RB"': '"72"',
      '"Overall"': '"274"',
      '"Player"': '"Ito Smith"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"63"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"71.0"',
    },
    {
      '"RB"': '"73"',
      '"Overall"': '"238"',
      '"Player"': '"Lynn Bowden Jr."',
      '"Team"': '"NO"',
      '"Bye"': '"6"',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"64.0"',
    },
    {
      '"RB"': '"74"',
      '"Overall"': '"210"',
      '"Player"': '"Benny Snell Jr."',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"70.0"',
    },
    {
      '"RB"': '"75"',
      '"Overall"': '"262"',
      '"Player"': '"Giovani Bernard"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '"64"',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"70.5"',
    },
    {
      '"RB"': '"76"',
      '"Overall"': '"240"',
      '"Player"': '"Justice Hill"',
      '"Team"': '"BAL"',
      '"Bye"': '"7"',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"65.0"',
    },
    {
      '"RB"': '"77"',
      '"Overall"': '"241"',
      '"Player"': '"Brian Hill"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"66.0"',
    },
    {
      '"RB"': '"78"',
      '"Overall"': '"245"',
      '"Player"': '"Eno Benjamin"',
      '"Team"': '"NO"',
      '"Bye"': '"6"',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"67.0"',
    },
    {
      '"RB"': '"79"',
      '"Overall"': '"248"',
      '"Player"': '"Darrynton Evans"',
      '"Team"': '"BUF"',
      '"Bye"': '"11"',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"68.0"',
    },
    {
      '"RB"': '"80"',
      '"Overall"': '"249"',
      '"Player"': '"Anthony McFarland Jr."',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"69.0"',
    },
    {
      '"RB"': '"81"',
      '"Overall"': '"251"',
      '"Player"': '"Devonta Freeman"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"71.0"',
    },
    {
      '"RB"': '"82"',
      '"Overall"': '"252"',
      '"Player"': '"Royce Freeman"',
      '"Team"': '"LAR"',
      '"Bye"': '"9"',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"72.0"',
    },
    {
      '"RB"': '"83"',
      '"Overall"': '"254"',
      '"Player"': '"La\'Mical Perine"',
      '"Team"': '"KC"',
      '"Bye"': '"10"',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"73.0"',
    },
    {
      '"RB"': '"84"',
      '"Overall"': '"259"',
      '"Player"': '"Gus Edwards"',
      '"Team"': '"LAC"',
      '"Bye"': '"6"',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"74.0"',
    },
    {
      '"RB"': '"85"',
      '"Overall"': '"278"',
      '"Player"': '"Jaylen Samuels"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"81.0"',
    },
    {
      '"RB"': '"86"',
      '"Overall"': '"281"',
      '"Player"': '"Dion Lewis"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"82.0"',
    },
    {
      '"RB"': '"87"',
      '"Overall"': '"286"',
      '"Player"': '"Rex Burkhead "',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"83.0"',
    },
    {
      '"RB"': '"88"',
      '"Overall"': '"290"',
      '"Player"': '"Darwin Thompson"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"84.0"',
    },
    {
      '"RB"': '"89"',
      '"Overall"': '"299"',
      '"Player"': '"Peyton Barber"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"86.0"',
    },
    {
      '"RB"': '"90"',
      '"Overall"': '"316"',
      '"Player"': '"Mike Boone"',
      '"Team"': '"CAR"',
      '"Bye"': '"13"',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"88.0"',
    },
    {
      '"RB"': '"91"',
      '"Overall"': '"330"',
      '"Player"': '"J.D. McKissic"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"90.0"',
    },
    {
      '"RB"': '"92"',
      '"Overall"': '"337"',
      '"Player"': '"Ty Montgomery II"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"92.0"',
    },
    {
      '"RB"': '"93"',
      '"Overall"': '"338"',
      '"Player"': '"Kalen Ballage"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"93.0"',
    },
    {
      '"RB"': '"94"',
      '"Overall"': '"341"',
      '"Player"': '"DeeJay Dallas"',
      '"Team"': '"ARI"',
      '"Bye"': '"8"',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"94.0"',
    },
    {
      '"RB"': '"95"',
      '"Overall"': '"345"',
      '"Player"': '"J.J. Taylor"',
      '"Team"': '"HOU"',
      '"Bye"': '"8"',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"95.0"',
    },
    {
      '"RB"': '"96"',
      '"Overall"': '"348"',
      '"Player"': '"Derrius Guice"',
      '"Team"': '""',
      '"Bye"': '""',
      '"CBS"': '""',
      '"Sleeper"': '""',
      '"RTSports"': '""',
      '"AVG"': '"97.0"',
    },
  ],
];

module.exports = rb2020PPRRedraftADP;
