const wr2022PPRRedraftADP = [
  {
    '"WR"': '"1"',
    '"Overall"': '"4"',
    '"Player"': '"Cooper Kupp"',
    '"Team"': '"LAR"',
    '"Bye"': '"7 "',
    '"ESPN"': '"1"',
    '"Sleeper"': '"1"',
    '"NFL"': '"1"',
    '"RTSports"': '"2"',
    '"FFC"': '""',
    '"AVG"': '"1.3"',
  },
  {
    '"WR"': '"2"',
    '"Overall"': '"6"',
    '"Player"': '"Justin Jefferson"',
    '"Team"': '"MIN"',
    '"Bye"': '"7"',
    '"ESPN"': '"2"',
    '"Sleeper"': '"2"',
    '"NFL"': '"2"',
    '"RTSports"': '"1"',
    '"FFC"': '""',
    '"AVG"': '"1.7"',
  },
  {
    '"WR"': '"3"',
    '"Overall"': '"9"',
    '"Player"': '"Ja\'Marr Chase"',
    '"Team"': '"CIN"',
    '"Bye"': '"10"',
    '"ESPN"': '"3"',
    '"Sleeper"': '"3"',
    '"NFL"': '"3"',
    '"RTSports"': '"3"',
    '"FFC"': '""',
    '"AVG"': '"3.0"',
  },
  {
    '"WR"': '"4"',
    '"Overall"': '"11"',
    '"Player"': '"Davante Adams"',
    '"Team"': '"LV"',
    '"Bye"': '"6"',
    '"ESPN"': '"4"',
    '"Sleeper"': '"5"',
    '"NFL"': '"4"',
    '"RTSports"': '"5"',
    '"FFC"': '""',
    '"AVG"': '"4.3"',
  },
  {
    '"WR"': '"5"',
    '"Overall"': '"12"',
    '"Player"': '"Stefon Diggs"',
    '"Team"': '"BUF"',
    '"Bye"': '"7"',
    '"ESPN"': '"5"',
    '"Sleeper"': '"4"',
    '"NFL"': '"5"',
    '"RTSports"': '"4"',
    '"FFC"': '""',
    '"AVG"': '"4.7"',
  },
  {
    '"WR"': '"6"',
    '"Overall"': '"16"',
    '"Player"': '"Deebo Samuel"',
    '"Team"': '"SF"',
    '"Bye"': '"9"',
    '"ESPN"': '"6"',
    '"Sleeper"': '"8"',
    '"NFL"': '"6"',
    '"RTSports"': '"6"',
    '"FFC"': '""',
    '"AVG"': '"6.0"',
  },
  {
    '"WR"': '"7"',
    '"Overall"': '"19"',
    '"Player"': '"Tyreek Hill"',
    '"Team"': '"MIA"',
    '"Bye"': '"11"',
    '"ESPN"': '"7"',
    '"Sleeper"': '"7"',
    '"NFL"': '"7"',
    '"RTSports"': '"8"',
    '"FFC"': '""',
    '"AVG"': '"7.3"',
  },
  {
    '"WR"': '"8"',
    '"Overall"': '"18"',
    '"Player"': '"CeeDee Lamb"',
    '"Team"': '"DAL"',
    '"Bye"': '"9"',
    '"ESPN"': '"8"',
    '"Sleeper"': '"6"',
    '"NFL"': '"8"',
    '"RTSports"': '"7"',
    '"FFC"': '""',
    '"AVG"': '"7.7"',
  },
  {
    '"WR"': '"9"',
    '"Overall"': '"26"',
    '"Player"': '"Mike Evans"',
    '"Team"': '"TB"',
    '"Bye"': '"11"',
    '"ESPN"': '"10"',
    '"Sleeper"': '"9"',
    '"NFL"': '"9"',
    '"RTSports"': '"9"',
    '"FFC"': '""',
    '"AVG"': '"9.3"',
  },
  {
    '"WR"': '"10"',
    '"Overall"': '"27"',
    '"Player"': '"Keenan Allen"',
    '"Team"': '"LAC"',
    '"Bye"': '"8"',
    '"ESPN"': '"9"',
    '"Sleeper"': '"10"',
    '"NFL"': '"10"',
    '"RTSports"': '"12"',
    '"FFC"': '""',
    '"AVG"': '"10.3"',
  },
  {
    '"WR"': '"11"',
    '"Overall"': '"31"',
    '"Player"': '"A.J. Brown"',
    '"Team"': '"PHI"',
    '"Bye"': '"7"',
    '"ESPN"': '"14"',
    '"Sleeper"': '"11"',
    '"NFL"': '"11"',
    '"RTSports"': '"10"',
    '"FFC"': '""',
    '"AVG"': '"11.7"',
  },
  {
    '"WR"': '"12"',
    '"Overall"': '"34"',
    '"Player"': '"Tee Higgins"',
    '"Team"': '"CIN"',
    '"Bye"': '"10"',
    '"ESPN"': '"11"',
    '"Sleeper"': '"12"',
    '"NFL"': '"12"',
    '"RTSports"': '"13"',
    '"FFC"': '""',
    '"AVG"': '"12.0"',
  },
  {
    '"WR"': '"13"',
    '"Overall"': '"33"',
    '"Player"': '"Michael Pittman Jr."',
    '"Team"': '"IND"',
    '"Bye"': '"14"',
    '"ESPN"': '"12"',
    '"Sleeper"': '"13"',
    '"NFL"': '"13"',
    '"RTSports"': '"11"',
    '"FFC"': '""',
    '"AVG"': '"12.0"',
  },
  {
    '"WR"': '"14"',
    '"Overall"': '"42"',
    '"Player"': '"DJ Moore"',
    '"Team"': '"CHI"',
    '"Bye"': '"14"',
    '"ESPN"': '"13"',
    '"Sleeper"': '"15"',
    '"NFL"': '"21"',
    '"RTSports"': '"14"',
    '"FFC"': '""',
    '"AVG"': '"16.0"',
  },
  {
    '"WR"': '"15"',
    '"Overall"': '"40"',
    '"Player"': '"Terry McLaurin"',
    '"Team"': '"WAS"',
    '"Bye"': '"14"',
    '"ESPN"': '"15"',
    '"Sleeper"': '"14"',
    '"NFL"': '"16"',
    '"RTSports"': '"18"',
    '"FFC"': '""',
    '"AVG"': '"16.3"',
  },
  {
    '"WR"': '"16"',
    '"Overall"': '"43"',
    '"Player"': '"Diontae Johnson"',
    '"Team"': '"PIT"',
    '"Bye"': '"9"',
    '"ESPN"': '"17"',
    '"Sleeper"': '"17"',
    '"NFL"': '"15"',
    '"RTSports"': '"17"',
    '"FFC"': '""',
    '"AVG"': '"16.3"',
  },
  {
    '"WR"': '"17"',
    '"Overall"': '"45"',
    '"Player"': '"Mike Williams"',
    '"Team"': '"LAC"',
    '"Bye"': '"8"',
    '"ESPN"': '"16"',
    '"Sleeper"': '"20"',
    '"NFL"': '"18"',
    '"RTSports"': '"16"',
    '"FFC"': '""',
    '"AVG"': '"16.7"',
  },
  {
    '"WR"': '"18"',
    '"Overall"': '"46"',
    '"Player"': '"Jaylen Waddle"',
    '"Team"': '"MIA"',
    '"Bye"': '"11"',
    '"ESPN"': '"18"',
    '"Sleeper"': '"16"',
    '"NFL"': '"17"',
    '"RTSports"': '"21"',
    '"FFC"': '""',
    '"AVG"': '"18.7"',
  },
  {
    '"WR"': '"19"',
    '"Overall"': '"47"',
    '"Player"': '"DK Metcalf"',
    '"Team"': '"SEA"',
    '"Bye"': '"11"',
    '"ESPN"': '"19"',
    '"Sleeper"': '"19"',
    '"NFL"': '"14"',
    '"RTSports"': '"24"',
    '"FFC"': '""',
    '"AVG"': '"19.0"',
  },
  {
    '"WR"': '"20"',
    '"Overall"': '"54"',
    '"Player"': '"Brandin Cooks"',
    '"Team"': '"DAL"',
    '"Bye"': '"9"',
    '"ESPN"': '"20"',
    '"Sleeper"': '"25"',
    '"NFL"': '"19"',
    '"RTSports"': '"23"',
    '"FFC"': '""',
    '"AVG"': '"20.7"',
  },
  {
    '"WR"': '"21"',
    '"Overall"': '"61"',
    '"Player"': '"Amon-Ra St. Brown"',
    '"Team"': '"DET"',
    '"Bye"': '"6"',
    '"ESPN"': '"24"',
    '"Sleeper"': '"28"',
    '"NFL"': '"26"',
    '"RTSports"': '"19"',
    '"FFC"': '""',
    '"AVG"': '"23.0"',
  },
  {
    '"WR"': '"22"',
    '"Overall"': '"56"',
    '"Player"': '"Courtland Sutton"',
    '"Team"': '"DEN"',
    '"Bye"': '"9"',
    '"ESPN"': '"22"',
    '"Sleeper"': '"18"',
    '"NFL"': '"34"',
    '"RTSports"': '"15"',
    '"FFC"': '""',
    '"AVG"': '"23.7"',
  },
  {
    '"WR"': '"23"',
    '"Overall"': '"59"',
    '"Player"': '"Chris Godwin"',
    '"Team"': '"TB"',
    '"Bye"': '"11"',
    '"ESPN"': '"25"',
    '"Sleeper"': '"26"',
    '"NFL"': '"20"',
    '"RTSports"': '"27"',
    '"FFC"': '""',
    '"AVG"': '"24.0"',
  },
  {
    '"WR"': '"24"',
    '"Overall"': '"66"',
    '"Player"': '"Gabe Davis"',
    '"Team"': '"BUF"',
    '"Bye"': '"7"',
    '"ESPN"': '"26"',
    '"Sleeper"': '"32"',
    '"NFL"': '"27"',
    '"RTSports"': '"20"',
    '"FFC"': '""',
    '"AVG"': '"24.3"',
  },
  {
    '"WR"': '"25"',
    '"Overall"': '"58"',
    '"Player"': '"Marquise Brown"',
    '"Team"': '"ARI"',
    '"Bye"': '"13"',
    '"ESPN"': '"23"',
    '"Sleeper"': '"24"',
    '"NFL"': '"24"',
    '"RTSports"': '"26"',
    '"FFC"': '""',
    '"AVG"': '"24.3"',
  },
  {
    '"WR"': '"26"',
    '"Overall"': '"60"',
    '"Player"': '"Allen Robinson II"',
    '"Team"': '"PIT"',
    '"Bye"': '"9 "',
    '"ESPN"': '"29"',
    '"Sleeper"': '"22"',
    '"NFL"': '"22"',
    '"RTSports"': '"25"',
    '"FFC"': '""',
    '"AVG"': '"25.3"',
  },
  {
    '"WR"': '"27"',
    '"Overall"': '"64"',
    '"Player"': '"Jerry Jeudy"',
    '"Team"': '"DEN"',
    '"Bye"': '"9"',
    '"ESPN"': '"21"',
    '"Sleeper"': '"21"',
    '"NFL"': '"29"',
    '"RTSports"': '"33"',
    '"FFC"': '""',
    '"AVG"': '"27.7"',
  },
  {
    '"WR"': '"28"',
    '"Overall"': '"68"',
    '"Player"': '"Amari Cooper"',
    '"Team"': '"CLE"',
    '"Bye"': '"9"',
    '"ESPN"': '"30"',
    '"Sleeper"': '"23"',
    '"NFL"': '"23"',
    '"RTSports"': '"31"',
    '"FFC"': '""',
    '"AVG"': '"28.0"',
  },
  {
    '"WR"': '"29"',
    '"Overall"': '"72"',
    '"Player"': '"Darnell Mooney"',
    '"Team"': '"CHI"',
    '"Bye"': '"14 "',
    '"ESPN"': '"27"',
    '"Sleeper"': '"31"',
    '"NFL"': '"38"',
    '"RTSports"': '"22"',
    '"FFC"': '""',
    '"AVG"': '"29.0"',
  },
  {
    '"WR"': '"30"',
    '"Overall"': '"71"',
    '"Player"': '"Adam Thielen"',
    '"Team"': '"CAR"',
    '"Bye"': '"13"',
    '"ESPN"': '"33"',
    '"Sleeper"': '"30"',
    '"NFL"': '"28"',
    '"RTSports"': '"28"',
    '"FFC"': '""',
    '"AVG"': '"29.7"',
  },
  {
    '"WR"': '"31"',
    '"Overall"': '"73"',
    '"Player"': '"JuJu Smith-Schuster"',
    '"Team"': '"NE"',
    '"Bye"': '"10"',
    '"ESPN"': '"28"',
    '"Sleeper"': '"29"',
    '"NFL"': '"32"',
    '"RTSports"': '"30"',
    '"FFC"': '""',
    '"AVG"': '"30.0"',
  },
  {
    '"WR"': '"32"',
    '"Overall"': '"80"',
    '"Player"': '"DeAndre Hopkins"',
    '"Team"': '"TEN"',
    '"Bye"': '"6"',
    '"ESPN"': '"40"',
    '"Sleeper"': '"34"',
    '"NFL"': '"25"',
    '"RTSports"': '"34"',
    '"FFC"': '""',
    '"AVG"': '"33.0"',
  },
  {
    '"WR"': '"33"',
    '"Overall"': '"75"',
    '"Player"': '"Michael Thomas"',
    '"Team"': '"N"',
    '"Bye"': '"14 O"',
    '"ESPN"': '"31"',
    '"Sleeper"': '"27"',
    '"NFL"': '"39"',
    '"RTSports"': '"29"',
    '"FFC"': '""',
    '"AVG"': '"33.0"',
  },
  {
    '"WR"': '"34"',
    '"Overall"': '"79"',
    '"Player"': '"Hunter Renfrow"',
    '"Team"': '"LV"',
    '"Bye"': '"6"',
    '"ESPN"': '"32"',
    '"Sleeper"': '"35"',
    '"NFL"': '"31"',
    '"RTSports"': '"41"',
    '"FFC"': '""',
    '"AVG"': '"34.7"',
  },
  {
    '"WR"': '"35"',
    '"Overall"': '"92"',
    '"Player"': '"Elijah Moore"',
    '"Team"': '"CLE"',
    '"Bye"': '"9"',
    '"ESPN"': '"38"',
    '"Sleeper"': '"38"',
    '"NFL"': '"33"',
    '"RTSports"': '"35"',
    '"FFC"': '""',
    '"AVG"': '"35.3"',
  },
  {
    '"WR"': '"36"',
    '"Overall"': '"89"',
    '"Player"': '"Rashod Bateman"',
    '"Team"': '"BAL"',
    '"Bye"': '"10 "',
    '"ESPN"': '"35"',
    '"Sleeper"': '"33"',
    '"NFL"': '"41"',
    '"RTSports"': '"32"',
    '"FFC"': '""',
    '"AVG"': '"36.0"',
  },
  {
    '"WR"': '"37"',
    '"Overall"': '"93"',
    '"Player"': '"DeVonta Smith"',
    '"Team"': '"PHI"',
    '"Bye"': '"7"',
    '"ESPN"': '"36"',
    '"Sleeper"': '"36"',
    '"NFL"': '"36"',
    '"RTSports"': '"38"',
    '"FFC"': '""',
    '"AVG"': '"36.7"',
  },
  {
    '"WR"': '"38"',
    '"Overall"': '"96"',
    '"Player"': '"Tyler Lockett"',
    '"Team"': '"SEA"',
    '"Bye"': '"11"',
    '"ESPN"': '"37"',
    '"Sleeper"': '"41"',
    '"NFL"': '"30"',
    '"RTSports"': '"45"',
    '"FFC"': '""',
    '"AVG"': '"37.3"',
  },
  {
    '"WR"': '"39"',
    '"Overall"': '"100"',
    '"Player"': '"Christian Kirk"',
    '"Team"': '"JAC"',
    '"Bye"': '"11"',
    '"ESPN"': '"34"',
    '"Sleeper"': '"43"',
    '"NFL"': '"43"',
    '"RTSports"': '"36"',
    '"FFC"': '""',
    '"AVG"': '"37.7"',
  },
  {
    '"WR"': '"40"',
    '"Overall"': '"97"',
    '"Player"': '"Brandon Aiyuk"',
    '"Team"': '"SF"',
    '"Bye"': '"9"',
    '"ESPN"': '"42"',
    '"Sleeper"': '"40"',
    '"NFL"': '"35"',
    '"RTSports"': '"40"',
    '"FFC"': '""',
    '"AVG"': '"39.0"',
  },
  {
    '"WR"': '"41"',
    '"Overall"': '"102"',
    '"Player"': '"Robert Woods"',
    '"Team"': '"HOU"',
    '"Bye"': '"6"',
    '"ESPN"': '"44"',
    '"Sleeper"': '"45"',
    '"NFL"': '"37"',
    '"RTSports"': '"39"',
    '"FFC"': '""',
    '"AVG"': '"40.0"',
  },
  {
    '"WR"': '"42"',
    '"Overall"': '"98"',
    '"Player"': '"Drake London"',
    '"Team"': '"ATL"',
    '"Bye"': '"14"',
    '"ESPN"': '"39"',
    '"Sleeper"': '"37"',
    '"NFL"': '"40"',
    '"RTSports"': '"42"',
    '"FFC"': '""',
    '"AVG"': '"40.3"',
  },
  {
    '"WR"': '"43"',
    '"Overall"': '"103"',
    '"Player"': '"Allen Lazard"',
    '"Team"': '"NYJ"',
    '"Bye"': '"10"',
    '"ESPN"': '"41"',
    '"Sleeper"': '"39"',
    '"NFL"': '"47"',
    '"RTSports"': '"37"',
    '"FFC"': '""',
    '"AVG"': '"41.7"',
  },
  {
    '"WR"': '"44"',
    '"Overall"': '"107"',
    '"Player"': '"Chris Olave"',
    '"Team"': '"NO"',
    '"Bye"': '"14"',
    '"ESPN"': '"43"',
    '"Sleeper"': '"42"',
    '"NFL"': '"44"',
    '"RTSports"': '"43"',
    '"FFC"': '""',
    '"AVG"': '"43.3"',
  },
  {
    '"WR"': '"45"',
    '"Overall"': '"111"',
    '"Player"': '"Chase Claypool"',
    '"Team"': '"MIA"',
    '"Bye"': '"11"',
    '"ESPN"': '"45"',
    '"Sleeper"': '"47"',
    '"NFL"': '"42"',
    '"RTSports"': '"48"',
    '"FFC"': '""',
    '"AVG"': '"45.0"',
  },
  {
    '"WR"': '"46"',
    '"Overall"': '"115"',
    '"Player"': '"Kadarius Toney"',
    '"Team"': '"KC"',
    '"Bye"': '"8"',
    '"ESPN"': '"46"',
    '"Sleeper"': '"48"',
    '"NFL"': '"45"',
    '"RTSports"': '"47"',
    '"FFC"': '""',
    '"AVG"': '"46.0"',
  },
  {
    '"WR"': '"47"',
    '"Overall"': '"120"',
    '"Player"': '"George Pickens"',
    '"Team"': '"PIT"',
    '"Bye"': '"9"',
    '"ESPN"': '"56"',
    '"Sleeper"': '"46"',
    '"NFL"': '"50"',
    '"RTSports"': '"44"',
    '"FFC"': '""',
    '"AVG"': '"50.0"',
  },
  {
    '"WR"': '"48"',
    '"Overall"': '"143"',
    '"Player"': '"Russell Gage"',
    '"Team"': '"TB"',
    '"Bye"': '"11"',
    '"ESPN"': '"52"',
    '"Sleeper"': '"60"',
    '"NFL"': '"46"',
    '"RTSports"': '"55"',
    '"FFC"': '""',
    '"AVG"': '"51.0"',
  },
  {
    '"WR"': '"49"',
    '"Overall"': '"136"',
    '"Player"': '"Michael Gallup"',
    '"Team"': '"DAL"',
    '"Bye"': '"9"',
    '"ESPN"': '"53"',
    '"Sleeper"': '"55"',
    '"NFL"': '"51"',
    '"RTSports"': '"49"',
    '"FFC"': '""',
    '"AVG"': '"51.0"',
  },
  {
    '"WR"': '"50"',
    '"Overall"': '"126"',
    '"Player"': '"Treylon Burks"',
    '"Team"': '"TEN"',
    '"Bye"': '"6"',
    '"ESPN"': '"54"',
    '"Sleeper"': '"44"',
    '"NFL"': '"55"',
    '"RTSports"': '"46"',
    '"FFC"': '""',
    '"AVG"': '"51.7"',
  },
  {
    '"WR"': '"51"',
    '"Overall"': '"145"',
    '"Player"': '"DJ Chark Jr."',
    '"Team"': '"CAR"',
    '"Bye"': '"13"',
    '"ESPN"': '"55"',
    '"Sleeper"': '"61"',
    '"NFL"': '"49"',
    '"RTSports"': '"52"',
    '"FFC"': '""',
    '"AVG"': '"52.0"',
  },
  {
    '"WR"': '"52"',
    '"Overall"': '"133"',
    '"Player"': '"Tyler Boyd"',
    '"Team"': '"CIN"',
    '"Bye"': '"10"',
    '"ESPN"': '"49"',
    '"Sleeper"': '"52"',
    '"NFL"': '"57"',
    '"RTSports"': '"51"',
    '"FFC"': '""',
    '"AVG"': '"52.3"',
  },
  {
    '"WR"': '"53"',
    '"Overall"': '"134"',
    '"Player"': '"Garrett Wilson"',
    '"Team"': '"NYJ"',
    '"Bye"': '"10"',
    '"ESPN"': '"47"',
    '"Sleeper"': '"50"',
    '"NFL"': '"54"',
    '"RTSports"': '"58"',
    '"FFC"': '""',
    '"AVG"': '"53.0"',
  },
  {
    '"WR"': '"54"',
    '"Overall"': '"140"',
    '"Player"': '"Skyy Moore"',
    '"Team"': '"KC"',
    '"Bye"': '"8"',
    '"ESPN"': '"51"',
    '"Sleeper"': '"51"',
    '"NFL"': '"60"',
    '"RTSports"': '"50"',
    '"FFC"': '""',
    '"AVG"': '"53.7"',
  },
  {
    '"WR"': '"55"',
    '"Overall"': '"148"',
    '"Player"': '"Marquez Valdes-Scantling"',
    '"Team"': '"KC"',
    '"Bye"': '"8"',
    '"ESPN"': '"48"',
    '"Sleeper"': '"53"',
    '"NFL"': '"58"',
    '"RTSports"': '"61"',
    '"FFC"': '""',
    '"AVG"': '"55.7"',
  },
  {
    '"WR"': '"56"',
    '"Overall"': '"157"',
    '"Player"': '"Jakobi Meyers"',
    '"Team"': '"LV"',
    '"Bye"': '"6"',
    '"ESPN"': '"50"',
    '"Sleeper"': '"62"',
    '"NFL"': '"64"',
    '"RTSports"': '"53"',
    '"FFC"': '""',
    '"AVG"': '"55.7"',
  },
  {
    '"WR"': '"57"',
    '"Overall"': '"141"',
    '"Player"': '"Julio Jones"',
    '"Team"': '"PHI"',
    '"Bye"': '"7"',
    '"ESPN"': '"60"',
    '"Sleeper"': '"49"',
    '"NFL"': '"53"',
    '"RTSports"': '"54"',
    '"FFC"': '""',
    '"AVG"': '"55.7"',
  },
  {
    '"WR"': '"58"',
    '"Overall"': '"153"',
    '"Player"': '"Jarvis Landry "',
    '"Team"': '""',
    '"Bye"': '""',
    '"ESPN"': '"57"',
    '"Sleeper"': '"54"',
    '"NFL"': '"62"',
    '"RTSports"': '"56"',
    '"FFC"': '""',
    '"AVG"': '"58.3"',
  },
  {
    '"WR"': '"59"',
    '"Overall"': '"163"',
    '"Player"': '"Mecole Hardman Jr."',
    '"Team"': '"KC"',
    '"Bye"': '"8"',
    '"ESPN"': '"65"',
    '"Sleeper"': '"66"',
    '"NFL"': '"48"',
    '"RTSports"': '"64"',
    '"FFC"': '""',
    '"AVG"': '"59.0"',
  },
  {
    '"WR"': '"60"',
    '"Overall"': '"155"',
    '"Player"': '"DeVante Parker"',
    '"Team"': '"NE"',
    '"Bye"': '"10"',
    '"ESPN"': '"62"',
    '"Sleeper"': '"56"',
    '"NFL"': '"56"',
    '"RTSports"': '"63"',
    '"FFC"': '""',
    '"AVG"': '"60.3"',
  },
  {
    '"WR"': '"61"',
    '"Overall"': '"175"',
    '"Player"': '"Isaiah McKenzie"',
    '"Team"': '"IND"',
    '"Bye"': '"14"',
    '"ESPN"': '"67"',
    '"Sleeper"': '"63"',
    '"NFL"': '"59"',
    '"RTSports"': '"59"',
    '"FFC"': '""',
    '"AVG"': '"61.7"',
  },
  {
    '"WR"': '"62"',
    '"Overall"': '"171"',
    '"Player"': '"Jahan Dotson"',
    '"Team"': '"WAS"',
    '"Bye"': '"14"',
    '"ESPN"': '"58"',
    '"Sleeper"': '"58"',
    '"NFL"': '"74"',
    '"RTSports"': '"57"',
    '"FFC"': '""',
    '"AVG"': '"63.0"',
  },
  {
    '"WR"': '"63"',
    '"Overall"': '"174"',
    '"Player"': '"Romeo Doubs"',
    '"Team"': '"GB"',
    '"Bye"': '"14"',
    '"ESPN"': '"64"',
    '"Sleeper"': '"57"',
    '"NFL"': '"66"',
    '"RTSports"': '"60"',
    '"FFC"': '""',
    '"AVG"': '"63.3"',
  },
  {
    '"WR"': '"64"',
    '"Overall"': '"182"',
    '"Player"': '"Rondale Moore"',
    '"Team"': '"ARI"',
    '"Bye"': '"13 "',
    '"ESPN"': '"68"',
    '"Sleeper"': '"59"',
    '"NFL"': '"68"',
    '"RTSports"': '"62"',
    '"FFC"': '""',
    '"AVG"': '"66.0"',
  },
  {
    '"WR"': '"65"',
    '"Overall"': '"194"',
    '"Player"': '"Joshua Palmer"',
    '"Team"': '"LAC"',
    '"Bye"': '"8"',
    '"ESPN"': '"61"',
    '"Sleeper"': '"72"',
    '"NFL"': '""',
    '"RTSports"': '"67"',
    '"FFC"': '""',
    '"AVG"': '"64.0"',
  },
  {
    '"WR"': '"66"',
    '"Overall"': '"225"',
    '"Player"': '"Van Jefferson"',
    '"Team"': '"ATL"',
    '"Bye"': '"14"',
    '"ESPN"': '""',
    '"Sleeper"': '"81"',
    '"NFL"': '"52"',
    '"RTSports"': '"87"',
    '"FFC"': '""',
    '"AVG"': '"69.5"',
  },
  {
    '"WR"': '"67"',
    '"Overall"': '"193"',
    '"Player"': '"Odell Beckham Jr."',
    '"Team"': '"BAL"',
    '"Bye"': '"10"',
    '"ESPN"': '"71"',
    '"Sleeper"': '"69"',
    '"NFL"': '"67"',
    '"RTSports"': '"70"',
    '"FFC"': '""',
    '"AVG"': '"69.3"',
  },
  {
    '"WR"': '"68"',
    '"Overall"': '"202"',
    '"Player"': '"Christian Watson"',
    '"Team"': '"GB"',
    '"Bye"': '"14"',
    '"ESPN"': '""',
    '"Sleeper"': '"64"',
    '"NFL"': '"63"',
    '"RTSports"': '"71"',
    '"FFC"': '""',
    '"AVG"': '"67.0"',
  },
  {
    '"WR"': '"69"',
    '"Overall"': '"203"',
    '"Player"': '"Marvin Jones Jr."',
    '"Team"': '""',
    '"Bye"': '""',
    '"ESPN"': '"59"',
    '"Sleeper"': '"80"',
    '"NFL"': '""',
    '"RTSports"': '"76"',
    '"FFC"': '""',
    '"AVG"': '"67.5"',
  },
  {
    '"WR"': '"70"',
    '"Overall"': '"206"',
    '"Player"': '"Nico Collins"',
    '"Team"': '"HU"',
    '"Bye"': '"6 O"',
    '"ESPN"': '"70"',
    '"Sleeper"': '"73"',
    '"NFL"': '""',
    '"RTSports"': '"65"',
    '"FFC"': '""',
    '"AVG"': '"67.5"',
  },
  {
    '"WR"': '"71"',
    '"Overall"': '"198"',
    '"Player"': '"Robbie Chosen"',
    '"Team"': '"MIA"',
    '"Bye"': '"11"',
    '"ESPN"': '"63"',
    '"Sleeper"': '"78"',
    '"NFL"': '""',
    '"RTSports"': '"74"',
    '"FFC"': '""',
    '"AVG"': '"68.5"',
  },
  {
    '"WR"': '"72"',
    '"Overall"': '"241"',
    '"Player"': '"Corey Davis"',
    '"Team"': '""',
    '"Bye"': '""',
    '"ESPN"': '""',
    '"Sleeper"': '""',
    '"NFL"': '"61"',
    '"RTSports"': '"78"',
    '"FFC"': '""',
    '"AVG"': '"69.5"',
  },
  {
    '"WR"': '"73"',
    '"Overall"': '"201"',
    '"Player"': '"Kenny Golladay"',
    '"Team"': '""',
    '"Bye"': '""',
    '"ESPN"': '"66"',
    '"Sleeper"': '"70"',
    '"NFL"': '"73"',
    '"RTSports"': '"79"',
    '"FFC"': '""',
    '"AVG"': '"72.7"',
  },
  {
    '"WR"': '"74"',
    '"Overall"': '"244"',
    '"Player"': '"A.J. Green"',
    '"Team"': '""',
    '"Bye"': '""',
    '"ESPN"': '""',
    '"Sleeper"': '"77"',
    '"NFL"': '"65"',
    '"RTSports"': '""',
    '"FFC"': '""',
    '"AVG"': '"65.0"',
  },
  {
    '"WR"': '"75"',
    '"Overall"': '"218"',
    '"Player"': '"Jameson Williams"',
    '"Team"': '"DET"',
    '"Bye"': '"6"',
    '"ESPN"': '""',
    '"Sleeper"': '"67"',
    '"NFL"': '"69"',
    '"RTSports"': '"72"',
    '"FFC"': '""',
    '"AVG"': '"70.5"',
  },
  {
    '"WR"': '"76"',
    '"Overall"': '"200"',
    '"Player"': '"Jalen Tolbert"',
    '"Team"': '"DAL"',
    '"Bye"': '"9"',
    '"ESPN"': '"69"',
    '"Sleeper"': '"68"',
    '"NFL"': '"75"',
    '"RTSports"': '"73"',
    '"FFC"': '""',
    '"AVG"': '"72.3"',
  },
  {
    '"WR"': '"77"',
    '"Overall"': '"223"',
    '"Player"': '"Alec Pierce"',
    '"Team"': '"IND"',
    '"Bye"': '"14"',
    '"ESPN"': '""',
    '"Sleeper"': '"71"',
    '"NFL"': '""',
    '"RTSports"': '"66"',
    '"FFC"': '""',
    '"AVG"': '"66.0"',
  },
  {
    '"WR"': '"78"',
    '"Overall"': '"213"',
    '"Player"': '"Sammy Watkins"',
    '"Team"': '""',
    '"Bye"': '""',
    '"ESPN"': '"72"',
    '"Sleeper"': '"65"',
    '"NFL"': '"71"',
    '"RTSports"': '"77"',
    '"FFC"': '""',
    '"AVG"': '"73.3"',
  },
  {
    '"WR"': '"79"',
    '"Overall"': '"243"',
    '"Player"': '"Parris Campbell"',
    '"Team"': '"NYG"',
    '"Bye"': '"9"',
    '"ESPN"': '""',
    '"Sleeper"': '"84"',
    '"NFL"': '""',
    '"RTSports"': '"68"',
    '"FFC"': '""',
    '"AVG"': '"68.0"',
  },
  {
    '"WR"': '"80"',
    '"Overall"': '"234"',
    '"Player"': '"Wan\'Dale Robinson"',
    '"Team"': '"NYG"',
    '"Bye"': '"9 "',
    '"ESPN"': '""',
    '"Sleeper"': '"74"',
    '"NFL"': '""',
    '"RTSports"': '"69"',
    '"FFC"': '""',
    '"AVG"': '"69.0"',
  },
  {
    '"WR"': '"81"',
    '"Overall"': '"250"',
    '"Player"': '"Randall Cobb"',
    '"Team"': '"NYJ"',
    '"Bye"': '"10"',
    '"ESPN"': '""',
    '"Sleeper"': '"79"',
    '"NFL"': '"70"',
    '"RTSports"': '""',
    '"FFC"': '""',
    '"AVG"': '"70.0"',
  },
  {
    '"WR"': '"82"',
    '"Overall"': '"257"',
    '"Player"': '"Kendrick Bourne"',
    '"Team"': '"NE"',
    '"Bye"': '"10"',
    '"ESPN"': '""',
    '"Sleeper"': '""',
    '"NFL"': '"72"',
    '"RTSports"': '"80"',
    '"FFC"': '""',
    '"AVG"': '"76.0"',
  },
  {
    '"WR"': '"83"',
    '"Overall"': '"236"',
    '"Player"': '"K.J. Osborn"',
    '"Team"': '"MIN"',
    '"Bye"': '"7"',
    '"ESPN"': '""',
    '"Sleeper"': '"75"',
    '"NFL"': '""',
    '"RTSports"': '"75"',
    '"FFC"': '""',
    '"AVG"': '"75.0"',
  },
  {
    '"WR"': '"84"',
    '"Overall"': '"263"',
    '"Player"': '"David Bell"',
    '"Team"': '"CLE"',
    '"Bye"': '"9"',
    '"ESPN"': '""',
    '"Sleeper"': '"83"',
    '"NFL"': '""',
    '"RTSports"': '"81"',
    '"FFC"': '""',
    '"AVG"': '"81.0"',
  },
  {
    '"WR"': '"85"',
    '"Overall"': '"255"',
    '"Player"': '"KJ Hamler"',
    '"Team"': '"BUF"',
    '"Bye"': '"7 "',
    '"ESPN"': '""',
    '"Sleeper"': '"76"',
    '"NFL"': '""',
    '"RTSports"': '"82"',
    '"FFC"': '""',
    '"AVG"': '"82.0"',
  },
  {
    '"WR"': '"86"',
    '"Overall"': '"296"',
    '"Player"': '"Braxton Berrios"',
    '"Team"': '"MIA"',
    '"Bye"': '"11"',
    '"ESPN"': '""',
    '"Sleeper"': '""',
    '"NFL"': '""',
    '"RTSports"': '"83"',
    '"FFC"': '""',
    '"AVG"': '"83.0"',
  },
  {
    '"WR"': '"87"',
    '"Overall"': '"299"',
    '"Player"': '"Zay Jones"',
    '"Team"': '"JAC"',
    '"Bye"': '"11"',
    '"ESPN"': '""',
    '"Sleeper"': '""',
    '"NFL"': '""',
    '"RTSports"': '"84"',
    '"FFC"': '""',
    '"AVG"': '"84.0"',
  },
  {
    '"WR"': '"88"',
    '"Overall"': '"260"',
    '"Player"': '"Donovan Peoples-Jones"',
    '"Team"': '"DET"',
    '"Bye"': '"6"',
    '"ESPN"': '""',
    '"Sleeper"': '"82"',
    '"NFL"': '""',
    '"RTSports"': '"85"',
    '"FFC"': '""',
    '"AVG"': '"85.0"',
  },
  {
    '"WR"': '"89"',
    '"Overall"': '"317"',
    '"Player"': '"Sterling Shepard"',
    '"Team"': '"NYG"',
    '"Bye"': '"9 "',
    '"ESPN"': '""',
    '"Sleeper"': '""',
    '"NFL"': '""',
    '"RTSports"': '"86"',
    '"FFC"': '""',
    '"AVG"': '"86.0"',
  },
  {
    '"WR"': '"90"',
    '"Overall"': '"277"',
    '"Player"': '"Curtis Samuel"',
    '"Team"': '"WAS"',
    '"Bye"': '"14"',
    '"ESPN"': '""',
    '"Sleeper"': '"85"',
    '"NFL"': '""',
    '"RTSports"': '"88"',
    '"FFC"': '""',
    '"AVG"': '"88.0"',
  },
  {
    '"WR"': '"91"',
    '"Overall"': '"329"',
    '"Player"': '"Laviska Shenault Jr."',
    '"Team"': '"CAR"',
    '"Bye"': '"13"',
    '"ESPN"': '""',
    '"Sleeper"': '""',
    '"NFL"': '""',
    '"RTSports"': '"89"',
    '"FFC"': '""',
    '"AVG"': '"89.0"',
  },
  {
    '"WR"': '"92"',
    '"Overall"': '"302"',
    '"Player"': '"Marquez Callaway"',
    '"Team"': '"PIT"',
    '"Bye"': '"9"',
    '"ESPN"': '""',
    '"Sleeper"': '""',
    '"NFL"': '""',
    '"RTSports"': '"90"',
    '"FFC"': '""',
    '"AVG"': '"90.0"',
  },
];

module.exports = wr2022PPRRedraftADP;
