const before2024seasonRVRedraftRankings = [
  {
    '""': '"1"',
    '"Rank"': '1',
    '"Player"': '"Christian McCaffrey"',
    '"POS"': '"RB"',
    '"Team"': '"SF"',
    '"PosRank"': '1',
    '"AVGRank"': '1',
    '"AVGTier"': '1',
    '"Siegele8.25"': '1',
  },
  {
    '""': '"2"',
    '"Rank"': '2',
    '"Player"': '"Tyreek Hill"',
    '"POS"': '"WR"',
    '"Team"': '"MIA"',
    '"PosRank"': '1',
    '"AVGRank"': '2',
    '"AVGTier"': '1',
    '"Siegele8.25"': '2',
  },
  {
    '""': '"3"',
    '"Rank"': '3',
    '"Player"': '"CeeDee Lamb"',
    '"POS"': '"WR"',
    '"Team"': '"DAL"',
    '"PosRank"': '2',
    '"AVGRank"': '3',
    '"AVGTier"': '1',
    '"Siegele8.25"': '3',
  },
  {
    '""': '"4"',
    '"Rank"': '4',
    '"Player"': '"Bijan Robinson"',
    '"POS"': '"RB"',
    '"Team"': '"ATL"',
    '"PosRank"': '2',
    '"AVGRank"': '4',
    '"AVGTier"': '1',
    '"Siegele8.25"': '4',
  },
  {
    '""': '"5"',
    '"Rank"': '5',
    '"Player"': '"Breece Hall"',
    '"POS"': '"RB"',
    '"Team"': '"NYJ"',
    '"PosRank"': '3',
    '"AVGRank"': '5',
    '"AVGTier"': '1',
    '"Siegele8.25"': '5',
  },
  {
    '""': '"6"',
    '"Rank"': '6',
    '"Player"': '"Justin Jefferson"',
    '"POS"': '"WR"',
    '"Team"': '"MIN"',
    '"PosRank"': '3',
    '"AVGRank"': '6',
    '"AVGTier"': '1',
    '"Siegele8.25"': '6',
  },
  {
    '""': '"7"',
    '"Rank"': '7',
    '"Player"': '"Ja\'Marr Chase"',
    '"POS"': '"WR"',
    '"Team"': '"CIN"',
    '"PosRank"': '4',
    '"AVGRank"': '7',
    '"AVGTier"': '1',
    '"Siegele8.25"': '7',
  },
  {
    '""': '"8"',
    '"Rank"': '8',
    '"Player"': '"Amon-Ra St. Brown"',
    '"POS"': '"WR"',
    '"Team"': '"DET"',
    '"PosRank"': '5',
    '"AVGRank"': '8',
    '"AVGTier"': '1',
    '"Siegele8.25"': '8',
  },
  {
    '""': '"9"',
    '"Rank"': '9',
    '"Player"': '"Garrett Wilson"',
    '"POS"': '"WR"',
    '"Team"': '"NYJ"',
    '"PosRank"': '6',
    '"AVGRank"': '9',
    '"AVGTier"': '1',
    '"Siegele8.25"': '9',
  },
  {
    '""': '"10"',
    '"Rank"': '10',
    '"Player"': '"Jahmyr Gibbs"',
    '"POS"': '"RB"',
    '"Team"': '"DET"',
    '"PosRank"': '4',
    '"AVGRank"': '10',
    '"AVGTier"': '2',
    '"Siegele8.25"': '10',
  },
  {
    '""': '"11"',
    '"Rank"': '11',
    '"Player"': '"Trey McBride"',
    '"POS"': '"TE"',
    '"Team"': '"ARI"',
    '"PosRank"': '1',
    '"AVGRank"': '11',
    '"AVGTier"': '2',
    '"Siegele8.25"': '11',
  },
  {
    '""': '"12"',
    '"Rank"': '12',
    '"Player"': '"Sam LaPorta"',
    '"POS"': '"TE"',
    '"Team"': '"DET"',
    '"PosRank"': '2',
    '"AVGRank"': '12',
    '"AVGTier"': '2',
    '"Siegele8.25"': '12',
  },
  {
    '""': '"13"',
    '"Rank"': '13',
    '"Player"': '"Chris Olave"',
    '"POS"': '"WR"',
    '"Team"': '"NO"',
    '"PosRank"': '7',
    '"AVGRank"': '13',
    '"AVGTier"': '2',
    '"Siegele8.25"': '13',
  },
  {
    '""': '"14"',
    '"Rank"': '14',
    '"Player"': '"Deebo Samuel"',
    '"POS"': '"WR"',
    '"Team"': '"SF"',
    '"PosRank"': '8',
    '"AVGRank"': '14',
    '"AVGTier"': '2',
    '"Siegele8.25"': '14',
  },
  {
    '""': '"15"',
    '"Rank"': '15',
    '"Player"': '"Drake London"',
    '"POS"': '"WR"',
    '"Team"': '"ATL"',
    '"PosRank"': '9',
    '"AVGRank"': '15',
    '"AVGTier"': '2',
    '"Siegele8.25"': '15',
  },
  {
    '""': '"16"',
    '"Rank"': '16',
    '"Player"': '"Jonathan Taylor"',
    '"POS"': '"RB"',
    '"Team"': '"IND"',
    '"PosRank"': '5',
    '"AVGRank"': '16',
    '"AVGTier"': '2',
    '"Siegele8.25"': '16',
  },
  {
    '""': '"17"',
    '"Rank"': '17',
    '"Player"': '"A.J. Brown"',
    '"POS"': '"WR"',
    '"Team"': '"PHI"',
    '"PosRank"': '10',
    '"AVGRank"': '17',
    '"AVGTier"': '2',
    '"Siegele8.25"': '17',
  },
  {
    '""': '"18"',
    '"Rank"': '18',
    '"Player"': '"Cooper Kupp"',
    '"POS"': '"WR"',
    '"Team"': '"LAR"',
    '"PosRank"': '11',
    '"AVGRank"': '18',
    '"AVGTier"': '2',
    '"Siegele8.25"': '18',
  },
  {
    '""': '"19"',
    '"Rank"': '19',
    '"Player"': '"Marvin Harrison"',
    '"POS"': '"WR"',
    '"Team"': '"ARI"',
    '"PosRank"': '12',
    '"AVGRank"': '19',
    '"AVGTier"': '2',
    '"Siegele8.25"': '19',
  },
  {
    '""': '"20"',
    '"Rank"': '20',
    '"Player"': '"Malik Nabers"',
    '"POS"': '"WR"',
    '"Team"': '"NYG"',
    '"PosRank"': '13',
    '"AVGRank"': '20',
    '"AVGTier"': '2',
    '"Siegele8.25"': '20',
  },
  {
    '""': '"21"',
    '"Rank"': '21',
    '"Player"': '"Jaylen Waddle"',
    '"POS"': '"WR"',
    '"Team"': '"MIA"',
    '"PosRank"': '14',
    '"AVGRank"': '22',
    '"AVGTier"': '2',
    '"Siegele8.25"': '22',
  },
  {
    '""': '"22"',
    '"Rank"': '22',
    '"Player"': '"Puka Nacua"',
    '"POS"': '"WR"',
    '"Team"': '"LAR"',
    '"PosRank"': '15',
    '"AVGRank"': '21',
    '"AVGTier"': '2',
    '"Siegele8.25"': '21',
  },
  {
    '""': '"23"',
    '"Rank"': '23',
    '"Player"': '"Kyren Williams"',
    '"POS"': '"RB"',
    '"Team"': '"LAR"',
    '"PosRank"': '6',
    '"AVGRank"': '23',
    '"AVGTier"': '2',
    '"Siegele8.25"': '23',
  },
  {
    '""': '"24"',
    '"Rank"': '24',
    '"Player"': '"Nico Collins"',
    '"POS"': '"WR"',
    '"Team"': '"HOU"',
    '"PosRank"': '16',
    '"AVGRank"': '24',
    '"AVGTier"': '2',
    '"Siegele8.25"': '24',
  },
  {
    '""': '"25"',
    '"Rank"': '25',
    '"Player"': '"Dalton Kincaid"',
    '"POS"': '"TE"',
    '"Team"': '"BUF"',
    '"PosRank"': '3',
    '"AVGRank"': '25',
    '"AVGTier"': '2',
    '"Siegele8.25"': '25',
  },
  {
    '""': '"26"',
    '"Rank"': '26',
    '"Player"': '"Devon Achane"',
    '"POS"': '"RB"',
    '"Team"': '"MIA"',
    '"PosRank"': '7',
    '"AVGRank"': '26',
    '"AVGTier"': '2',
    '"Siegele8.25"': '26',
  },
  {
    '""': '"27"',
    '"Rank"': '27',
    '"Player"': '"DeVonta Smith"',
    '"POS"': '"WR"',
    '"Team"': '"PHI"',
    '"PosRank"': '17',
    '"AVGRank"': '27',
    '"AVGTier"': '2',
    '"Siegele8.25"': '27',
  },
  {
    '""': '"28"',
    '"Rank"': '28',
    '"Player"': '"Stefon Diggs"',
    '"POS"': '"WR"',
    '"Team"': '"HOU"',
    '"PosRank"': '18',
    '"AVGRank"': '28',
    '"AVGTier"': '2',
    '"Siegele8.25"': '28',
  },
  {
    '""': '"29"',
    '"Rank"': '29',
    '"Player"': '"Tee Higgins"',
    '"POS"': '"WR"',
    '"Team"': '"CIN"',
    '"PosRank"': '19',
    '"AVGRank"': '29',
    '"AVGTier"': '3',
    '"Siegele8.25"': '29',
  },
  {
    '""': '"30"',
    '"Rank"': '30',
    '"Player"': '"DJ Moore"',
    '"POS"': '"WR"',
    '"Team"': '"CHI"',
    '"PosRank"': '20',
    '"AVGRank"': '30',
    '"AVGTier"': '3',
    '"Siegele8.25"': '30',
  },
  {
    '""': '"31"',
    '"Rank"': '31',
    '"Player"': '"Rashee Rice"',
    '"POS"': '"WR"',
    '"Team"': '"KC"',
    '"PosRank"': '21',
    '"AVGRank"': '31',
    '"AVGTier"': '3',
    '"Siegele8.25"': '31',
  },
  {
    '""': '"32"',
    '"Rank"': '32',
    '"Player"': '"Brandon Aiyuk"',
    '"POS"': '"WR"',
    '"Team"': '"SF"',
    '"PosRank"': '22',
    '"AVGRank"': '32',
    '"AVGTier"': '3',
    '"Siegele8.25"': '32',
  },
  {
    '""': '"33"',
    '"Rank"': '33',
    '"Player"': '"Travis Kelce"',
    '"POS"': '"TE"',
    '"Team"': '"KC"',
    '"PosRank"': '4',
    '"AVGRank"': '33',
    '"AVGTier"': '3',
    '"Siegele8.25"': '33',
  },
  {
    '""': '"34"',
    '"Rank"': '34',
    '"Player"': '"Derrick Henry"',
    '"POS"': '"RB"',
    '"Team"': '"BAL"',
    '"PosRank"': '8',
    '"AVGRank"': '34',
    '"AVGTier"': '3',
    '"Siegele8.25"': '34',
  },
  {
    '""': '"35"',
    '"Rank"': '35',
    '"Player"': '"Zay Flowers"',
    '"POS"': '"WR"',
    '"Team"': '"BAL"',
    '"PosRank"': '23',
    '"AVGRank"': '35',
    '"AVGTier"': '3',
    '"Siegele8.25"': '35',
  },
  {
    '""': '"36"',
    '"Rank"': '36',
    '"Player"': '"DK Metcalf"',
    '"POS"': '"WR"',
    '"Team"': '"SEA"',
    '"PosRank"': '24',
    '"AVGRank"': '36',
    '"AVGTier"': '3',
    '"Siegele8.25"': '36',
  },
  {
    '""': '"37"',
    '"Rank"': '37',
    '"Player"': '"Davante Adams"',
    '"POS"': '"WR"',
    '"Team"': '"LV"',
    '"PosRank"': '25',
    '"AVGRank"': '37',
    '"AVGTier"': '3',
    '"Siegele8.25"': '37',
  },
  {
    '""': '"38"',
    '"Rank"': '38',
    '"Player"': '"Kyle Pitts"',
    '"POS"': '"TE"',
    '"Team"': '"ATL"',
    '"PosRank"': '5',
    '"AVGRank"': '38',
    '"AVGTier"': '3',
    '"Siegele8.25"': '38',
  },
  {
    '""': '"39"',
    '"Rank"': '39',
    '"Player"': '"Mark Andrews"',
    '"POS"': '"TE"',
    '"Team"': '"BAL"',
    '"PosRank"': '6',
    '"AVGRank"': '39',
    '"AVGTier"': '3',
    '"Siegele8.25"': '39',
  },
  {
    '""': '"40"',
    '"Rank"': '40',
    '"Player"': '"Tank Dell"',
    '"POS"': '"WR"',
    '"Team"': '"HOU"',
    '"PosRank"': '26',
    '"AVGRank"': '40',
    '"AVGTier"': '3',
    '"Siegele8.25"': '40',
  },
  {
    '""': '"41"',
    '"Rank"': '41',
    '"Player"': '"Mike Evans"',
    '"POS"': '"WR"',
    '"Team"': '"TB"',
    '"PosRank"': '27',
    '"AVGRank"': '41',
    '"AVGTier"': '3',
    '"Siegele8.25"': '41',
  },
  {
    '""': '"42"',
    '"Rank"': '42',
    '"Player"': '"George Kittle"',
    '"POS"': '"TE"',
    '"Team"': '"SF"',
    '"PosRank"': '7',
    '"AVGRank"': '42',
    '"AVGTier"': '3',
    '"Siegele8.25"': '42',
  },
  {
    '""': '"43"',
    '"Rank"': '43',
    '"Player"': '"Josh Allen"',
    '"POS"': '"QB"',
    '"Team"': '"BUF"',
    '"PosRank"': '1',
    '"AVGRank"': '43',
    '"AVGTier"': '3',
    '"Siegele8.25"': '43',
  },
  {
    '""': '"44"',
    '"Rank"': '44',
    '"Player"': '"Travis Etienne"',
    '"POS"': '"RB"',
    '"Team"': '"JAC"',
    '"PosRank"': '9',
    '"AVGRank"': '44',
    '"AVGTier"': '3',
    '"Siegele8.25"': '44',
  },
  {
    '""': '"45"',
    '"Rank"': '45',
    '"Player"': '"Kenneth Walker"',
    '"POS"': '"RB"',
    '"Team"': '"SEA"',
    '"PosRank"': '10',
    '"AVGRank"': '45',
    '"AVGTier"': '3',
    '"Siegele8.25"': '45',
  },
  {
    '""': '"46"',
    '"Rank"': '46',
    '"Player"': '"Amari Cooper"',
    '"POS"': '"WR"',
    '"Team"': '"CLE"',
    '"PosRank"': '28',
    '"AVGRank"': '46',
    '"AVGTier"': '3',
    '"Siegele8.25"': '46',
  },
  {
    '""': '"47"',
    '"Rank"': '47',
    '"Player"': '"Isiah Pacheco"',
    '"POS"': '"RB"',
    '"Team"': '"KC"',
    '"PosRank"': '11',
    '"AVGRank"': '48',
    '"AVGTier"': '4',
    '"Siegele8.25"': '48',
  },
  {
    '""': '"48"',
    '"Rank"': '48',
    '"Player"': '"Xavier Worthy"',
    '"POS"': '"WR"',
    '"Team"': '"KC"',
    '"PosRank"': '29',
    '"AVGRank"': '47',
    '"AVGTier"': '3',
    '"Siegele8.25"': '47',
  },
  {
    '""': '"49"',
    '"Rank"': '49',
    '"Player"': '"Keenan Allen"',
    '"POS"': '"WR"',
    '"Team"': '"CHI"',
    '"PosRank"': '30',
    '"AVGRank"': '49',
    '"AVGTier"': '4',
    '"Siegele8.25"': '49',
  },
  {
    '""': '"50"',
    '"Rank"': '50',
    '"Player"': '"Saquon Barkley"',
    '"POS"': '"RB"',
    '"Team"': '"PHI"',
    '"PosRank"': '12',
    '"AVGRank"': '50',
    '"AVGTier"': '4',
    '"Siegele8.25"': '50',
  },
  {
    '""': '"51"',
    '"Rank"': '51',
    '"Player"': '"James Cook"',
    '"POS"': '"RB"',
    '"Team"': '"BUF"',
    '"PosRank"': '13',
    '"AVGRank"': '51',
    '"AVGTier"': '4',
    '"Siegele8.25"': '51',
  },
  {
    '""': '"52"',
    '"Rank"': '52',
    '"Player"': '"Michael Pittman"',
    '"POS"': '"WR"',
    '"Team"': '"IND"',
    '"PosRank"': '31',
    '"AVGRank"': '52',
    '"AVGTier"': '4',
    '"Siegele8.25"': '52',
  },
  {
    '""': '"53"',
    '"Rank"': '53',
    '"Player"': '"Evan Engram"',
    '"POS"': '"TE"',
    '"Team"': '"JAC"',
    '"PosRank"': '8',
    '"AVGRank"': '53',
    '"AVGTier"': '4',
    '"Siegele8.25"': '53',
  },
  {
    '""': '"54"',
    '"Rank"': '54',
    '"Player"': '"Lamar Jackson"',
    '"POS"': '"QB"',
    '"Team"': '"BAL"',
    '"PosRank"': '2',
    '"AVGRank"': '54',
    '"AVGTier"': '4',
    '"Siegele8.25"': '54',
  },
  {
    '""': '"55"',
    '"Rank"': '55',
    '"Player"': '"Josh Jacobs"',
    '"POS"': '"RB"',
    '"Team"': '"GB"',
    '"PosRank"': '14',
    '"AVGRank"': '55',
    '"AVGTier"': '4',
    '"Siegele8.25"': '55',
  },
  {
    '""': '"56"',
    '"Rank"': '56',
    '"Player"': '"Diontae Johnson"',
    '"POS"': '"WR"',
    '"Team"': '"CAR"',
    '"PosRank"': '32',
    '"AVGRank"': '57',
    '"AVGTier"': '4',
    '"Siegele8.25"': '57',
  },
  {
    '""': '"57"',
    '"Rank"': '57',
    '"Player"': '"Jayden Reed"',
    '"POS"': '"WR"',
    '"Team"': '"GB"',
    '"PosRank"': '33',
    '"AVGRank"': '56',
    '"AVGTier"': '4',
    '"Siegele8.25"': '56',
  },
  {
    '""': '"58"',
    '"Rank"': '58',
    '"Player"': '"Jaxon Smith-Njigba"',
    '"POS"': '"WR"',
    '"Team"': '"SEA"',
    '"PosRank"': '34',
    '"AVGRank"': '58',
    '"AVGTier"': '4',
    '"Siegele8.25"': '58',
  },
  {
    '""': '"59"',
    '"Rank"': '59',
    '"Player"': '"Terry McLaurin"',
    '"POS"': '"WR"',
    '"Team"': '"WAS"',
    '"PosRank"': '35',
    '"AVGRank"': '59',
    '"AVGTier"': '4',
    '"Siegele8.25"': '59',
  },
  {
    '""': '"60"',
    '"Rank"': '60',
    '"Player"': '"George Pickens"',
    '"POS"': '"WR"',
    '"Team"': '"PIT"',
    '"PosRank"': '36',
    '"AVGRank"': '60',
    '"AVGTier"': '4',
    '"Siegele8.25"': '60',
  },
  {
    '""': '"61"',
    '"Rank"': '61',
    '"Player"': '"Patrick Mahomes"',
    '"POS"': '"QB"',
    '"Team"': '"KC"',
    '"PosRank"': '3',
    '"AVGRank"': '62',
    '"AVGTier"': '4',
    '"Siegele8.25"': '62',
  },
  {
    '""': '"62"',
    '"Rank"': '62',
    '"Player"': '"Brock Bowers"',
    '"POS"': '"TE"',
    '"Team"': '"LV"',
    '"PosRank"': '9',
    '"AVGRank"': '61',
    '"AVGTier"': '4',
    '"Siegele8.25"': '61',
  },
  {
    '""': '"63"',
    '"Rank"': '63',
    '"Player"': '"Christian Kirk"',
    '"POS"': '"WR"',
    '"Team"': '"JAC"',
    '"PosRank"': '37',
    '"AVGRank"': '63',
    '"AVGTier"': '4',
    '"Siegele8.25"': '63',
  },
  {
    '""': '"64"',
    '"Rank"': '64',
    '"Player"': '"Aaron Jones"',
    '"POS"': '"RB"',
    '"Team"': '"MIN"',
    '"PosRank"': '15',
    '"AVGRank"': '64',
    '"AVGTier"': '4',
    '"Siegele8.25"': '64',
  },
  {
    '""': '"65"',
    '"Rank"': '65',
    '"Player"': '"Jalen Hurts"',
    '"POS"': '"QB"',
    '"Team"': '"PHI"',
    '"PosRank"': '4',
    '"AVGRank"': '65',
    '"AVGTier"': '4',
    '"Siegele8.25"': '65',
  },
  {
    '""': '"66"',
    '"Rank"': '66',
    '"Player"': '"James Conner"',
    '"POS"': '"RB"',
    '"Team"': '"ARI"',
    '"PosRank"': '16',
    '"AVGRank"': '67',
    '"AVGTier"': '4',
    '"Siegele8.25"': '67',
  },
  {
    '""': '"67"',
    '"Rank"': '67',
    '"Player"': '"Rome Odunze"',
    '"POS"': '"WR"',
    '"Team"': '"CHI"',
    '"PosRank"': '38',
    '"AVGRank"': '66',
    '"AVGTier"': '4',
    '"Siegele8.25"': '66',
  },
  {
    '""': '"68"',
    '"Rank"': '68',
    '"Player"': '"Jameson Williams"',
    '"POS"': '"WR"',
    '"Team"': '"DET"',
    '"PosRank"': '39',
    '"AVGRank"': '68',
    '"AVGTier"': '4',
    '"Siegele8.25"': '68',
  },
  {
    '""': '"69"',
    '"Rank"': '69',
    '"Player"': '"C.J. Stroud"',
    '"POS"': '"QB"',
    '"Team"': '"HOU"',
    '"PosRank"': '5',
    '"AVGRank"': '69',
    '"AVGTier"': '4',
    '"Siegele8.25"': '69',
  },
  {
    '""': '"70"',
    '"Rank"': '70',
    '"Player"': '"Jake Ferguson"',
    '"POS"': '"TE"',
    '"Team"': '"DAL"',
    '"PosRank"': '10',
    '"AVGRank"': '70',
    '"AVGTier"': '4',
    '"Siegele8.25"': '70',
  },
  {
    '""': '"71"',
    '"Rank"': '71',
    '"Player"': '"Joe Mixon"',
    '"POS"': '"RB"',
    '"Team"': '"HOU"',
    '"PosRank"': '17',
    '"AVGRank"': '71',
    '"AVGTier"': '4',
    '"Siegele8.25"': '71',
  },
  {
    '""': '"72"',
    '"Rank"': '72',
    '"Player"': '"Calvin Ridley"',
    '"POS"': '"WR"',
    '"Team"': '"TEN"',
    '"PosRank"': '40',
    '"AVGRank"': '72',
    '"AVGTier"': '5',
    '"Siegele8.25"': '72',
  },
  {
    '""': '"73"',
    '"Rank"': '73',
    '"Player"': '"Anthony Richardson"',
    '"POS"': '"QB"',
    '"Team"': '"IND"',
    '"PosRank"': '6',
    '"AVGRank"': '73',
    '"AVGTier"': '5',
    '"Siegele8.25"': '73',
  },
  {
    '""': '"74"',
    '"Rank"': '74',
    '"Player"': '"David Njoku"',
    '"POS"': '"TE"',
    '"Team"': '"CLE"',
    '"PosRank"': '11',
    '"AVGRank"': '74',
    '"AVGTier"': '5',
    '"Siegele8.25"': '74',
  },
  {
    '""': '"75"',
    '"Rank"': '75',
    '"Player"': '"Rhamondre Stevenson"',
    '"POS"': '"RB"',
    '"Team"': '"NE"',
    '"PosRank"': '18',
    '"AVGRank"': '76',
    '"AVGTier"': '5',
    '"Siegele8.25"': '76',
  },
  {
    '""': '"76"',
    '"Rank"': '76',
    '"Player"': '"Brian Thomas"',
    '"POS"': '"WR"',
    '"Team"': '"JAC"',
    '"PosRank"': '41',
    '"AVGRank"': '75',
    '"AVGTier"': '5',
    '"Siegele8.25"': '75',
  },
  {
    '""': '"77"',
    '"Rank"': '77',
    '"Player"': '"Christian Watson"',
    '"POS"': '"WR"',
    '"Team"': '"GB"',
    '"PosRank"': '42',
    '"AVGRank"': '77',
    '"AVGTier"': '5',
    '"Siegele8.25"': '77',
  },
  {
    '""': '"78"',
    '"Rank"': '78',
    '"Player"': '"Jordan Addison"',
    '"POS"': '"WR"',
    '"Team"': '"MIN"',
    '"PosRank"': '43',
    '"AVGRank"': '78',
    '"AVGTier"': '5',
    '"Siegele8.25"': '78',
  },
  {
    '""': '"79"',
    '"Rank"': '79',
    '"Player"': '"Jordan Love"',
    '"POS"': '"QB"',
    '"Team"': '"GB"',
    '"PosRank"': '7',
    '"AVGRank"': '79',
    '"AVGTier"': '5',
    '"Siegele8.25"': '79',
  },
  {
    '""': '"80"',
    '"Rank"': '80',
    '"Player"': '"Kyler Murray"',
    '"POS"': '"QB"',
    '"Team"': '"ARI"',
    '"PosRank"': '8',
    '"AVGRank"': '80',
    '"AVGTier"': '5',
    '"Siegele8.25"': '80',
  },
  {
    '""': '"81"',
    '"Rank"': '81',
    '"Player"': '"Javonte Williams"',
    '"POS"': '"RB"',
    '"Team"': '"DEN"',
    '"PosRank"': '19',
    '"AVGRank"': '81',
    '"AVGTier"': '5',
    '"Siegele8.25"': '81',
  },
  {
    '""': '"82"',
    '"Rank"': '82',
    '"Player"': '"Najee Harris"',
    '"POS"': '"RB"',
    '"Team"': '"PIT"',
    '"PosRank"': '20',
    '"AVGRank"': '82',
    '"AVGTier"': '5',
    '"Siegele8.25"': '82',
  },
  {
    '""': '"83"',
    '"Rank"': '83',
    '"Player"': '"DeAndre Hopkins"',
    '"POS"': '"WR"',
    '"Team"': '"TEN"',
    '"PosRank"': '44',
    '"AVGRank"': '83',
    '"AVGTier"': '5',
    '"Siegele8.25"': '83',
  },
  {
    '""': '"84"',
    '"Rank"': '84',
    '"Player"': '"David Montgomery"',
    '"POS"': '"RB"',
    '"Team"': '"DET"',
    '"PosRank"': '21',
    '"AVGRank"': '84',
    '"AVGTier"': '5',
    '"Siegele8.25"': '84',
  },
  {
    '""': '"85"',
    '"Rank"': '85',
    '"Player"': '"Alvin Kamara"',
    '"POS"': '"RB"',
    '"Team"': '"NO"',
    '"PosRank"': '22',
    '"AVGRank"': '85',
    '"AVGTier"': '5',
    '"Siegele8.25"': '85',
  },
  {
    '""': '"86"',
    '"Rank"': '86',
    '"Player"': '"Chase Brown"',
    '"POS"': '"RB"',
    '"Team"': '"CIN"',
    '"PosRank"': '23',
    '"AVGRank"': '87',
    '"AVGTier"': '5',
    '"Siegele8.25"': '87',
  },
  {
    '""': '"87"',
    '"Rank"': '87',
    '"Player"': '"Jayden Daniels"',
    '"POS"': '"QB"',
    '"Team"': '"WAS"',
    '"PosRank"': '9',
    '"AVGRank"': '86',
    '"AVGTier"': '5',
    '"Siegele8.25"': '86',
  },
  {
    '""': '"88"',
    '"Rank"': '88',
    '"Player"': '"Raheem Mostert"',
    '"POS"': '"RB"',
    '"Team"': '"MIA"',
    '"PosRank"': '24',
    '"AVGRank"': '89',
    '"AVGTier"': '5',
    '"Siegele8.25"': '89',
  },
  {
    '""': '"89"',
    '"Rank"': '89',
    '"Player"': '"Ladd McConkey"',
    '"POS"': '"WR"',
    '"Team"': '"LAC"',
    '"PosRank"': '45',
    '"AVGRank"': '88',
    '"AVGTier"': '5',
    '"Siegele8.25"': '88',
  },
  {
    '""': '"90"',
    '"Rank"': '90',
    '"Player"': '"Joe Burrow"',
    '"POS"': '"QB"',
    '"Team"': '"CIN"',
    '"PosRank"': '10',
    '"AVGRank"': '90',
    '"AVGTier"': '5',
    '"Siegele8.25"': '90',
  },
  {
    '""': '"91"',
    '"Rank"': '91',
    '"Player"': '"Tyjae Spears"',
    '"POS"': '"RB"',
    '"Team"': '"TEN"',
    '"PosRank"': '25',
    '"AVGRank"': '92',
    '"AVGTier"': '5',
    '"Siegele8.25"': '92',
  },
  {
    '""': '"92"',
    '"Rank"': '92',
    '"Player"': '"Jonathon Brooks"',
    '"POS"': '"RB"',
    '"Team"': '"CAR"',
    '"PosRank"': '26',
    '"AVGRank"': '91',
    '"AVGTier"': '5',
    '"Siegele8.25"': '91',
  },
  {
    '""': '"93"',
    '"Rank"': '93',
    '"Player"': '"D\'Andre Swift"',
    '"POS"': '"RB"',
    '"Team"': '"CHI"',
    '"PosRank"': '27',
    '"AVGRank"': '93',
    '"AVGTier"': '5',
    '"Siegele8.25"': '93',
  },
  {
    '""': '"94"',
    '"Rank"': '94',
    '"Player"': '"Tony Pollard"',
    '"POS"': '"RB"',
    '"Team"': '"TEN"',
    '"PosRank"': '28',
    '"AVGRank"': '94',
    '"AVGTier"': '5',
    '"Siegele8.25"': '94',
  },
  {
    '""': '"95"',
    '"Rank"': '95',
    '"Player"': '"Marquise Brown"',
    '"POS"': '"WR"',
    '"Team"': '"KC"',
    '"PosRank"': '46',
    '"AVGRank"': '95',
    '"AVGTier"': '5',
    '"Siegele8.25"': '95',
  },
  {
    '""': '"96"',
    '"Rank"': '96',
    '"Player"': '"Rachaad White"',
    '"POS"': '"RB"',
    '"Team"': '"TB"',
    '"PosRank"': '29',
    '"AVGRank"': '96',
    '"AVGTier"': '5',
    '"Siegele8.25"': '96',
  },
  {
    '""': '"97"',
    '"Rank"': '97',
    '"Player"': '"Jaylen Warren"',
    '"POS"': '"RB"',
    '"Team"': '"PIT"',
    '"PosRank"': '30',
    '"AVGRank"': '98',
    '"AVGTier"': '6',
    '"Siegele8.25"': '98',
  },
  {
    '""': '"98"',
    '"Rank"': '98',
    '"Player"': '"Keon Coleman"',
    '"POS"': '"WR"',
    '"Team"': '"BUF"',
    '"PosRank"': '47',
    '"AVGRank"': '97',
    '"AVGTier"': '5',
    '"Siegele8.25"': '97',
  },
  {
    '""': '"99"',
    '"Rank"': '99',
    '"Player"': '"Dak Prescott"',
    '"POS"': '"QB"',
    '"Team"': '"DAL"',
    '"PosRank"': '11',
    '"AVGRank"': '99',
    '"AVGTier"': '6',
    '"Siegele8.25"': '99',
  },
  {
    '""': '"100"',
    '"Rank"': '100',
    '"Player"': '"Courtland Sutton"',
    '"POS"': '"WR"',
    '"Team"': '"DEN"',
    '"PosRank"': '48',
    '"AVGRank"': '100',
    '"AVGTier"': '6',
    '"Siegele8.25"': '100',
  },
  {
    '""': '"101"',
    '"Rank"': '101',
    '"Player"': '"Zack Moss"',
    '"POS"': '"RB"',
    '"Team"': '"CIN"',
    '"PosRank"': '31',
    '"AVGRank"': '101',
    '"AVGTier"': '6',
    '"Siegele8.25"': '101',
  },
  {
    '""': '"102"',
    '"Rank"': '102',
    '"Player"': '"Chris Godwin"',
    '"POS"': '"WR"',
    '"Team"': '"TB"',
    '"PosRank"': '49',
    '"AVGRank"': '102',
    '"AVGTier"': '6',
    '"Siegele8.25"': '102',
  },
  {
    '""': '"103"',
    '"Rank"': '103',
    '"Player"': '"Zamir White"',
    '"POS"': '"RB"',
    '"Team"': '"LV"',
    '"PosRank"': '32',
    '"AVGRank"': '104',
    '"AVGTier"': '6',
    '"Siegele8.25"': '104',
  },
  {
    '""': '"104"',
    '"Rank"': '104',
    '"Player"': '"Caleb Williams"',
    '"POS"': '"QB"',
    '"Team"': '"CHI"',
    '"PosRank"': '12',
    '"AVGRank"': '103',
    '"AVGTier"': '6',
    '"Siegele8.25"': '103',
  },
  {
    '""': '"105"',
    '"Rank"': '105',
    '"Player"': '"Nick Chubb"',
    '"POS"': '"RB"',
    '"Team"': '"CLE"',
    '"PosRank"': '33',
    '"AVGRank"': '105',
    '"AVGTier"': '6',
    '"Siegele8.25"': '105',
  },
  {
    '""': '"106"',
    '"Rank"': '106',
    '"Player"': '"Brian Robinson"',
    '"POS"': '"RB"',
    '"Team"': '"WAS"',
    '"PosRank"': '34',
    '"AVGRank"': '106',
    '"AVGTier"': '6',
    '"Siegele8.25"': '106',
  },
  {
    '""': '"107"',
    '"Rank"': '107',
    '"Player"': '"Trevor Lawrence"',
    '"POS"': '"QB"',
    '"Team"': '"JAC"',
    '"PosRank"': '13',
    '"AVGRank"': '107',
    '"AVGTier"': '6',
    '"Siegele8.25"': '107',
  },
  {
    '""': '"108"',
    '"Rank"': '108',
    '"Player"': '"J.K. Dobbins"',
    '"POS"': '"RB"',
    '"Team"': '"LAC"',
    '"PosRank"': '35',
    '"AVGRank"': '108',
    '"AVGTier"': '6',
    '"Siegele8.25"': '108',
  },
  {
    '""': '"109"',
    '"Rank"': '109',
    '"Player"': '"Curtis Samuel"',
    '"POS"': '"WR"',
    '"Team"': '"BUF"',
    '"PosRank"': '50',
    '"AVGRank"': '109',
    '"AVGTier"': '6',
    '"Siegele8.25"': '109',
  },
  {
    '""': '"110"',
    '"Rank"': '110',
    '"Player"': '"Brock Purdy"',
    '"POS"': '"QB"',
    '"Team"': '"SF"',
    '"PosRank"': '14',
    '"AVGRank"': '110',
    '"AVGTier"': '6',
    '"Siegele8.25"': '110',
  },
  {
    '""': '"111"',
    '"Rank"': '111',
    '"Player"': '"T.J. Hockenson"',
    '"POS"': '"TE"',
    '"Team"': '"MIN"',
    '"PosRank"': '12',
    '"AVGRank"': '111',
    '"AVGTier"': '6',
    '"Siegele8.25"': '111',
  },
  {
    '""': '"112"',
    '"Rank"': '112',
    '"Player"': '"Devin Singletary"',
    '"POS"': '"RB"',
    '"Team"': '"NYG"',
    '"PosRank"': '36',
    '"AVGRank"': '112',
    '"AVGTier"': '6',
    '"Siegele8.25"': '112',
  },
  {
    '""': '"113"',
    '"Rank"': '113',
    '"Player"': '"Dontayvion Wicks"',
    '"POS"': '"WR"',
    '"Team"': '"GB"',
    '"PosRank"': '51',
    '"AVGRank"': '113',
    '"AVGTier"': '6',
    '"Siegele8.25"': '113',
  },
  {
    '""': '"114"',
    '"Rank"': '114',
    '"Player"': '"Rico Dowdle"',
    '"POS"': '"RB"',
    '"Team"': '"DAL"',
    '"PosRank"': '37',
    '"AVGRank"': '114',
    '"AVGTier"': '6',
    '"Siegele8.25"': '114',
  },
  {
    '""': '"115"',
    '"Rank"': '115',
    '"Player"': '"Jared Goff"',
    '"POS"': '"QB"',
    '"Team"': '"DET"',
    '"PosRank"': '15',
    '"AVGRank"': '115',
    '"AVGTier"': '6',
    '"Siegele8.25"': '115',
  },
  {
    '""': '"116"',
    '"Rank"': '116',
    '"Player"': '"Trey Benson"',
    '"POS"': '"RB"',
    '"Team"': '"ARI"',
    '"PosRank"': '38',
    '"AVGRank"': '116',
    '"AVGTier"': '6',
    '"Siegele8.25"': '116',
  },
  {
    '""': '"117"',
    '"Rank"': '117',
    '"Player"': '"Blake Corum"',
    '"POS"': '"RB"',
    '"Team"': '"LAR"',
    '"PosRank"': '39',
    '"AVGRank"': '117',
    '"AVGTier"': '6',
    '"Siegele8.25"': '117',
  },
  {
    '""': '"118"',
    '"Rank"': '118',
    '"Player"': '"Tyler Lockett"',
    '"POS"': '"WR"',
    '"Team"': '"SEA"',
    '"PosRank"': '52',
    '"AVGRank"': '119',
    '"AVGTier"': '6',
    '"Siegele8.25"': '119',
  },
  {
    '""': '"119"',
    '"Rank"': '119',
    '"Player"': '"Ja\'Lynn Polk"',
    '"POS"': '"WR"',
    '"Team"': '"NE"',
    '"PosRank"': '53',
    '"AVGRank"': '118',
    '"AVGTier"': '6',
    '"Siegele8.25"': '118',
  },
  {
    '""': '"120"',
    '"Rank"': '120',
    '"Player"': '"Jaleel McLaughlin"',
    '"POS"': '"RB"',
    '"Team"': '"DEN"',
    '"PosRank"': '40',
    '"AVGRank"': '120',
    '"AVGTier"': '6',
    '"Siegele8.25"': '120',
  },
  {
    '""': '"121"',
    '"Rank"': '121',
    '"Player"': '"Kirk Cousins"',
    '"POS"': '"QB"',
    '"Team"': '"ATL"',
    '"PosRank"': '16',
    '"AVGRank"': '122',
    '"AVGTier"': '6',
    '"Siegele8.25"': '122',
  },
  {
    '""': '"122"',
    '"Rank"': '122',
    '"Player"': '"Jaylen Wright"',
    '"POS"': '"RB"',
    '"Team"': '"MIA"',
    '"PosRank"': '41',
    '"AVGRank"': '121',
    '"AVGTier"': '6',
    '"Siegele8.25"': '121',
  },
  {
    '""': '"123"',
    '"Rank"': '123',
    '"Player"': '"Dallas Goedert"',
    '"POS"': '"TE"',
    '"Team"': '"PHI"',
    '"PosRank"': '13',
    '"AVGRank"': '123',
    '"AVGTier"': '6',
    '"Siegele8.25"': '123',
  },
  {
    '""': '"124"',
    '"Rank"': '124',
    '"Player"': '"Tua Tagovailoa"',
    '"POS"': '"QB"',
    '"Team"': '"MIA"',
    '"PosRank"': '17',
    '"AVGRank"': '125',
    '"AVGTier"': '6',
    '"Siegele8.25"': '125',
  },
  {
    '""': '"125"',
    '"Rank"': '125',
    '"Player"': '"Braelon Allen"',
    '"POS"': '"RB"',
    '"Team"': '"NYJ"',
    '"PosRank"': '42',
    '"AVGRank"': '124',
    '"AVGTier"': '6',
    '"Siegele8.25"': '124',
  },
  {
    '""': '"126"',
    '"Rank"': '126',
    '"Player"': '"Pat Freiermuth"',
    '"POS"': '"TE"',
    '"Team"': '"PIT"',
    '"PosRank"': '14',
    '"AVGRank"': '126',
    '"AVGTier"': '6',
    '"Siegele8.25"': '126',
  },
  {
    '""': '"127"',
    '"Rank"': '127',
    '"Player"': '"Zach Charbonnet"',
    '"POS"': '"RB"',
    '"Team"': '"SEA"',
    '"PosRank"': '43',
    '"AVGRank"': '127',
    '"AVGTier"': '6',
    '"Siegele8.25"': '127',
  },
  {
    '""': '"128"',
    '"Rank"': '128',
    '"Player"': '"Romeo Doubs"',
    '"POS"': '"WR"',
    '"Team"': '"GB"',
    '"PosRank"': '54',
    '"AVGRank"': '128',
    '"AVGTier"': '6',
    '"Siegele8.25"': '128',
  },
  {
    '""': '"129"',
    '"Rank"': '129',
    '"Player"': '"Jerry Jeudy"',
    '"POS"': '"WR"',
    '"Team"': '"CLE"',
    '"PosRank"': '55',
    '"AVGRank"': '129',
    '"AVGTier"': '6',
    '"Siegele8.25"': '129',
  },
  {
    '""': '"130"',
    '"Rank"': '130',
    '"Player"': '"Luke Musgrave"',
    '"POS"': '"TE"',
    '"Team"': '"GB"',
    '"PosRank"': '15',
    '"AVGRank"': '130',
    '"AVGTier"': '6',
    '"Siegele8.25"': '130',
  },
  {
    '""': '"131"',
    '"Rank"': '131',
    '"Player"': '"Cole Kmet"',
    '"POS"': '"TE"',
    '"Team"': '"CHI"',
    '"PosRank"': '16',
    '"AVGRank"': '132',
    '"AVGTier"': '7',
    '"Siegele8.25"': '132',
  },
  {
    '""': '"132"',
    '"Rank"': '132',
    '"Player"': '"Bucky Irving"',
    '"POS"': '"RB"',
    '"Team"': '"TB"',
    '"PosRank"': '44',
    '"AVGRank"': '131',
    '"AVGTier"': '7',
    '"Siegele8.25"': '131',
  },
  {
    '""': '"133"',
    '"Rank"': '133',
    '"Player"': '"Tyler Allgeier"',
    '"POS"': '"RB"',
    '"Team"': '"ATL"',
    '"PosRank"': '45',
    '"AVGRank"': '133',
    '"AVGTier"': '7',
    '"Siegele8.25"': '133',
  },
  {
    '""': '"134"',
    '"Rank"': '134',
    '"Player"': '"Khalil Shakir"',
    '"POS"': '"WR"',
    '"Team"': '"BUF"',
    '"PosRank"': '56',
    '"AVGRank"': '134',
    '"AVGTier"': '7',
    '"Siegele8.25"': '134',
  },
  {
    '""': '"135"',
    '"Rank"': '135',
    '"Player"': '"Josh Downs"',
    '"POS"': '"WR"',
    '"Team"': '"IND"',
    '"PosRank"': '57',
    '"AVGRank"': '135',
    '"AVGTier"': '7',
    '"Siegele8.25"': '135',
  },
  {
    '""': '"136"',
    '"Rank"': '136',
    '"Player"': '"Ty Chandler"',
    '"POS"': '"RB"',
    '"Team"': '"MIN"',
    '"PosRank"': '46',
    '"AVGRank"': '136',
    '"AVGTier"': '7',
    '"Siegele8.25"': '136',
  },
  {
    '""': '"137"',
    '"Rank"': '137',
    '"Player"': '"Austin Ekeler"',
    '"POS"': '"RB"',
    '"Team"': '"WAS"',
    '"PosRank"': '47',
    '"AVGRank"': '137',
    '"AVGTier"': '7',
    '"Siegele8.25"': '137',
  },
  {
    '""': '"138"',
    '"Rank"': '138',
    '"Player"': '"Joshua Palmer"',
    '"POS"': '"WR"',
    '"Team"': '"LAC"',
    '"PosRank"': '58',
    '"AVGRank"': '138',
    '"AVGTier"': '7',
    '"Siegele8.25"': '138',
  },
  {
    '""': '"139"',
    '"Rank"': '139',
    '"Player"': '"Gus Edwards"',
    '"POS"': '"RB"',
    '"Team"': '"LAC"',
    '"PosRank"': '48',
    '"AVGRank"': '139',
    '"AVGTier"': '7',
    '"Siegele8.25"': '139',
  },
  {
    '""': '"140"',
    '"Rank"': '140',
    '"Player"': '"Jakobi Meyers"',
    '"POS"': '"WR"',
    '"Team"': '"LV"',
    '"PosRank"': '59',
    '"AVGRank"': '140',
    '"AVGTier"': '7',
    '"Siegele8.25"': '140',
  },
  {
    '""': '"141"',
    '"Rank"': '141',
    '"Player"': '"Gabe Davis"',
    '"POS"': '"WR"',
    '"Team"': '"JAC"',
    '"PosRank"': '60',
    '"AVGRank"': '141',
    '"AVGTier"': '7',
    '"Siegele8.25"': '141',
  },
  {
    '""': '"142"',
    '"Rank"': '142',
    '"Player"': '"Justin Herbert"',
    '"POS"': '"QB"',
    '"Team"': '"LAC"',
    '"PosRank"': '18',
    '"AVGRank"': '142',
    '"AVGTier"': '7',
    '"Siegele8.25"': '142',
  },
  {
    '""': '"143"',
    '"Rank"': '143',
    '"Player"': '"Jerome Ford"',
    '"POS"': '"RB"',
    '"Team"': '"CLE"',
    '"PosRank"': '49',
    '"AVGRank"': '143',
    '"AVGTier"': '7',
    '"Siegele8.25"': '143',
  },
  {
    '""': '"144"',
    '"Rank"': '144',
    '"Player"': '"Ezekiel Elliott"',
    '"POS"': '"RB"',
    '"Team"': '"DAL"',
    '"PosRank"': '50',
    '"AVGRank"': '144',
    '"AVGTier"': '7',
    '"Siegele8.25"': '144',
  },
  {
    '""': '"145"',
    '"Rank"': '145',
    '"Player"': '"Rashid Shaheed"',
    '"POS"': '"WR"',
    '"Team"': '"NO"',
    '"PosRank"': '61',
    '"AVGRank"': '145',
    '"AVGTier"': '7',
    '"Siegele8.25"': '145',
  },
  {
    '""': '"146"',
    '"Rank"': '146',
    '"Player"': '"Chuba Hubbard"',
    '"POS"': '"RB"',
    '"Team"': '"CAR"',
    '"PosRank"': '51',
    '"AVGRank"': '147',
    '"AVGTier"': '7',
    '"Siegele8.25"': '147',
  },
  {
    '""': '"147"',
    '"Rank"': '147',
    '"Player"': '"Adonai Mitchell"',
    '"POS"': '"WR"',
    '"Team"': '"IND"',
    '"PosRank"': '62',
    '"AVGRank"': '146',
    '"AVGTier"': '7',
    '"Siegele8.25"': '146',
  },
  {
    '""': '"148"',
    '"Rank"': '148',
    '"Player"': '"Jalen Tolbert"',
    '"POS"': '"WR"',
    '"Team"': '"DAL"',
    '"PosRank"': '63',
    '"AVGRank"': '148',
    '"AVGTier"': '7',
    '"Siegele8.25"': '148',
  },
  {
    '""': '"149"',
    '"Rank"': '149',
    '"Player"': '"Khalil Herbert"',
    '"POS"': '"RB"',
    '"Team"': '"CHI"',
    '"PosRank"': '52',
    '"AVGRank"': '149',
    '"AVGTier"': '7',
    '"Siegele8.25"': '149',
  },
  {
    '""': '"150"',
    '"Rank"': '150',
    '"Player"': '"Ricky Pearsall"',
    '"POS"': '"WR"',
    '"Team"': '"SF"',
    '"PosRank"': '64',
    '"AVGRank"': '150',
    '"AVGTier"': '7',
    '"Siegele8.25"': '150',
  },
  {
    '""': '"151"',
    '"Rank"': '151',
    '"Player"': '"Matthew Stafford"',
    '"POS"': '"QB"',
    '"Team"': '"LAR"',
    '"PosRank"': '19',
    '"AVGRank"': '152',
    '"AVGTier"': '7',
    '"Siegele8.25"': '152',
  },
  {
    '""': '"152"',
    '"Rank"': '152',
    '"Player"': '"Tyrone Tracy"',
    '"POS"': '"RB"',
    '"Team"': '"NYG"',
    '"PosRank"': '53',
    '"AVGRank"': '151',
    '"AVGTier"': '7',
    '"Siegele8.25"': '151',
  },
  {
    '""': '"153"',
    '"Rank"': '153',
    '"Player"': '"Ray Davis"',
    '"POS"': '"RB"',
    '"Team"': '"BUF"',
    '"PosRank"': '54',
    '"AVGRank"': '153',
    '"AVGTier"': '7',
    '"Siegele8.25"': '153',
  },
  {
    '""': '"154"',
    '"Rank"': '154',
    '"Player"': '"Jalen McMillan"',
    '"POS"': '"WR"',
    '"Team"': '"TB"',
    '"PosRank"': '65',
    '"AVGRank"': '154',
    '"AVGTier"': '7',
    '"Siegele8.25"': '154',
  },
  {
    '""': '"155"',
    '"Rank"': '155',
    '"Player"': '"MarShawn Lloyd"',
    '"POS"': '"RB"',
    '"Team"': '"GB"',
    '"PosRank"': '55',
    '"AVGRank"': '155',
    '"AVGTier"': '7',
    '"Siegele8.25"': '155',
  },
  {
    '""': '"156"',
    '"Rank"': '156',
    '"Player"': '"Geno Smith"',
    '"POS"': '"QB"',
    '"Team"': '"SEA"',
    '"PosRank"': '20',
    '"AVGRank"': '157',
    '"AVGTier"': '7',
    '"Siegele8.25"': '157',
  },
  {
    '""': '"157"',
    '"Rank"': '157',
    '"Player"': '"Kimani Vidal"',
    '"POS"': '"RB"',
    '"Team"': '"LAC"',
    '"PosRank"': '56',
    '"AVGRank"': '156',
    '"AVGTier"': '7',
    '"Siegele8.25"': '156',
  },
  {
    '""': '"158"',
    '"Rank"': '158',
    '"Player"': '"Aaron Rodgers"',
    '"POS"': '"QB"',
    '"Team"': '"NYJ"',
    '"PosRank"': '21',
    '"AVGRank"': '159',
    '"AVGTier"': '7',
    '"Siegele8.25"': '159',
  },
  {
    '""': '"159"',
    '"Rank"': '159',
    '"Player"': '"Xavier Legette"',
    '"POS"': '"WR"',
    '"Team"': '"CAR"',
    '"PosRank"': '66',
    '"AVGRank"': '158',
    '"AVGTier"': '7',
    '"Siegele8.25"': '158',
  },
  {
    '""': '"160"',
    '"Rank"': '160',
    '"Player"': '"Tyler Conklin"',
    '"POS"': '"TE"',
    '"Team"': '"NYJ"',
    '"PosRank"': '17',
    '"AVGRank"': '160',
    '"AVGTier"': '8',
    '"Siegele8.25"': '160',
  },
  {
    '""': '"161"',
    '"Rank"': '161',
    '"Player"': '"Dalton Schultz"',
    '"POS"': '"TE"',
    '"Team"': '"HOU"',
    '"PosRank"': '18',
    '"AVGRank"': '161',
    '"AVGTier"': '8',
    '"Siegele8.25"': '161',
  },
  {
    '""': '"162"',
    '"Rank"': '162',
    '"Player"': '"Will Shipley"',
    '"POS"': '"RB"',
    '"Team"': '"PHI"',
    '"PosRank"': '57',
    '"AVGRank"': '162',
    '"AVGTier"': '8',
    '"Siegele8.25"': '162',
  },
  {
    '""': '"163"',
    '"Rank"': '163',
    '"Player"': '"Audric Estime"',
    '"POS"': '"RB"',
    '"Team"': '"DEN"',
    '"PosRank"': '58',
    '"AVGRank"': '163',
    '"AVGTier"': '8',
    '"Siegele8.25"': '163',
  },
  {
    '""': '"164"',
    '"Rank"': '164',
    '"Player"': '"Demario Douglas"',
    '"POS"': '"WR"',
    '"Team"': '"NE"',
    '"PosRank"': '67',
    '"AVGRank"': '165',
    '"AVGTier"': '8',
    '"Siegele8.25"': '165',
  },
  {
    '""': '"165"',
    '"Rank"': '165',
    '"Player"': '"Ben Sinnott"',
    '"POS"': '"TE"',
    '"Team"': '"WAS"',
    '"PosRank"': '19',
    '"AVGRank"': '164',
    '"AVGTier"': '8',
    '"Siegele8.25"': '164',
  },
  {
    '""': '"166"',
    '"Rank"': '166',
    '"Player"': '"Justin Fields"',
    '"POS"': '"QB"',
    '"Team"': '"PIT"',
    '"PosRank"': '22',
    '"AVGRank"': '166',
    '"AVGTier"': '8',
    '"Siegele8.25"': '166',
  },
  {
    '""': '"167"',
    '"Rank"': '167',
    '"Player"': '"Darnell Mooney"',
    '"POS"': '"WR"',
    '"Team"': '"ATL"',
    '"PosRank"': '68',
    '"AVGRank"': '167',
    '"AVGTier"': '8',
    '"Siegele8.25"': '167',
  },
  {
    '""': '"168"',
    '"Rank"': '168',
    '"Player"': '"Juwan Johnson"',
    '"POS"': '"TE"',
    '"Team"': '"NO"',
    '"PosRank"': '20',
    '"AVGRank"': '168',
    '"AVGTier"': '8',
    '"Siegele8.25"': '168',
  },
  {
    '""': '"169"',
    '"Rank"': '169',
    '"Player"': '"Mike Williams"',
    '"POS"': '"WR"',
    '"Team"': '"NYJ"',
    '"PosRank"': '69',
    '"AVGRank"': '169',
    '"AVGTier"': '8',
    '"Siegele8.25"': '169',
  },
  {
    '""': '"170"',
    '"Rank"': '170',
    '"Player"': '"Noah Fant"',
    '"POS"': '"TE"',
    '"Team"': '"SEA"',
    '"PosRank"': '21',
    '"AVGRank"': '170',
    '"AVGTier"': '8',
    '"Siegele8.25"': '170',
  },
  {
    '""': '"171"',
    '"Rank"': '171',
    '"Player"': '"Wan\'Dale Robinson"',
    '"POS"': '"WR"',
    '"Team"': '"NYG"',
    '"PosRank"': '70',
    '"AVGRank"': '171',
    '"AVGTier"': '8',
    '"Siegele8.25"': '171',
  },
  {
    '""': '"172"',
    '"Rank"': '172',
    '"Player"': '"Antonio Gibson"',
    '"POS"': '"RB"',
    '"Team"': '"NE"',
    '"PosRank"': '59',
    '"AVGRank"': '172',
    '"AVGTier"': '8',
    '"Siegele8.25"': '172',
  },
  {
    '""': '"173"',
    '"Rank"': '173',
    '"Player"': '"Tank Bigsby"',
    '"POS"': '"RB"',
    '"Team"': '"JAC"',
    '"PosRank"': '60',
    '"AVGRank"': '173',
    '"AVGTier"': '8',
    '"Siegele8.25"': '173',
  },
  {
    '""': '"174"',
    '"Rank"': '174',
    '"Player"': '"Miles Sanders"',
    '"POS"': '"RB"',
    '"Team"': '"CAR"',
    '"PosRank"': '61',
    '"AVGRank"': '175',
    '"AVGTier"': '8',
    '"Siegele8.25"': '175',
  },
  {
    '""': '"175"',
    '"Rank"': '175',
    '"Player"': '"Bo Nix"',
    '"POS"': '"QB"',
    '"Team"': '"DEN"',
    '"PosRank"': '23',
    '"AVGRank"': '174',
    '"AVGTier"': '8',
    '"Siegele8.25"': '174',
  },
  {
    '""': '"176"',
    '"Rank"': '176',
    '"Player"': '"Kendre Miller"',
    '"POS"': '"RB"',
    '"Team"': '"NO"',
    '"PosRank"': '62',
    '"AVGRank"': '177',
    '"AVGTier"': '8',
    '"Siegele8.25"': '177',
  },
  {
    '""': '"177"',
    '"Rank"': '177',
    '"Player"': '"Drake Maye"',
    '"POS"': '"QB"',
    '"Team"': '"NE"',
    '"PosRank"': '24',
    '"AVGRank"': '176',
    '"AVGTier"': '8',
    '"Siegele8.25"': '176',
  },
  {
    '""': '"178"',
    '"Rank"': '178',
    '"Player"': '"Marvin Mims"',
    '"POS"': '"WR"',
    '"Team"': '"DEN"',
    '"PosRank"': '71',
    '"AVGRank"': '178',
    '"AVGTier"': '8',
    '"Siegele8.25"': '178',
  },
  {
    '""': '"179"',
    '"Rank"': '179',
    '"Player"': '"Baker Mayfield"',
    '"POS"': '"QB"',
    '"Team"': '"TB"',
    '"PosRank"': '25',
    '"AVGRank"': '179',
    '"AVGTier"': '8',
    '"Siegele8.25"': '179',
  },
  {
    '""': '"180"',
    '"Rank"': '180',
    '"Player"': '"Isaiah Likely"',
    '"POS"': '"TE"',
    '"Team"': '"BAL"',
    '"PosRank"': '22',
    '"AVGRank"': '180',
    '"AVGTier"': '8',
    '"Siegele8.25"': '180',
  },
  {
    '""': '"181"',
    '"Rank"': '181',
    '"Player"': '"Deshaun Watson"',
    '"POS"': '"QB"',
    '"Team"': '"CLE"',
    '"PosRank"': '26',
    '"AVGRank"': '181',
    '"AVGTier"': '9',
    '"Siegele8.25"': '181',
  },
  {
    '""': '"182"',
    '"Rank"': '182',
    '"Player"': '"Rashod Bateman"',
    '"POS"': '"WR"',
    '"Team"': '"BAL"',
    '"PosRank"': '72',
    '"AVGRank"': '182',
    '"AVGTier"': '9',
    '"Siegele8.25"': '182',
  },
  {
    '""': '"183"',
    '"Rank"': '183',
    '"Player"': '"Mike Gesicki"',
    '"POS"': '"TE"',
    '"Team"': '"CIN"',
    '"PosRank"': '23',
    '"AVGRank"': '183',
    '"AVGTier"': '9',
    '"Siegele8.25"': '183',
  },
  {
    '""': '"184"',
    '"Rank"': '184',
    '"Player"': '"Bryce Young"',
    '"POS"': '"QB"',
    '"Team"': '"CAR"',
    '"PosRank"': '27',
    '"AVGRank"': '184',
    '"AVGTier"': '9',
    '"Siegele8.25"': '184',
  },
  {
    '""': '"185"',
    '"Rank"': '185',
    '"Player"': '"Tucker Kraft"',
    '"POS"': '"TE"',
    '"Team"': '"GB"',
    '"PosRank"': '24',
    '"AVGRank"': '186',
    '"AVGTier"': '9',
    '"Siegele8.25"': '186',
  },
  {
    '""': '"186"',
    '"Rank"': '186',
    '"Player"': '"Jermaine Burton"',
    '"POS"': '"WR"',
    '"Team"': '"CIN"',
    '"PosRank"': '73',
    '"AVGRank"': '185',
    '"AVGTier"': '9',
    '"Siegele8.25"': '185',
  },
  {
    '""': '"187"',
    '"Rank"': '187',
    '"Player"': '"Will Levis"',
    '"POS"': '"QB"',
    '"Team"': '"TEN"',
    '"PosRank"': '28',
    '"AVGRank"': '187',
    '"AVGTier"': '9',
    '"Siegele8.25"': '187',
  },
  {
    '""': '"188"',
    '"Rank"': '188',
    '"Player"': '"Hunter Henry"',
    '"POS"': '"TE"',
    '"Team"': '"NE"',
    '"PosRank"': '25',
    '"AVGRank"': '189',
    '"AVGTier"': '9',
    '"Siegele8.25"': '189',
  },
  {
    '""': '"189"',
    '"Rank"': '189',
    '"Player"': '"Andrei Iosivas"',
    '"POS"': '"WR"',
    '"Team"': '"CIN"',
    '"PosRank"': '74',
    '"AVGRank"': '188',
    '"AVGTier"': '9',
    '"Siegele8.25"': '188',
  },
  {
    '""': '"190"',
    '"Rank"': '190',
    '"Player"': '"Justice Hill"',
    '"POS"': '"RB"',
    '"Team"': '"BAL"',
    '"PosRank"': '63',
    '"AVGRank"': '190',
    '"AVGTier"': '9',
    '"Siegele8.25"': '190',
  },
  {
    '""': '"191"',
    '"Rank"': '191',
    '"Player"': '"Michael Wilson"',
    '"POS"': '"WR"',
    '"Team"': '"ARI"',
    '"PosRank"': '75',
    '"AVGRank"': '191',
    '"AVGTier"': '9',
    '"Siegele8.25"': '191',
  },
  {
    '""': '"192"',
    '"Rank"': '192',
    '"Player"': '"Derek Carr"',
    '"POS"': '"QB"',
    '"Team"': '"NO"',
    '"PosRank"': '29',
    '"AVGRank"': '193',
    '"AVGTier"': '9',
    '"Siegele8.25"': '193',
  },
  {
    '""': '"193"',
    '"Rank"': '193',
    '"Player"': '"Ja\'Tavion Sanders"',
    '"POS"': '"TE"',
    '"Team"': '"CAR"',
    '"PosRank"': '26',
    '"AVGRank"': '192',
    '"AVGTier"': '9',
    '"Siegele8.25"': '192',
  },
  {
    '""': '"194"',
    '"Rank"': '194',
    '"Player"': '"Brandin Cooks"',
    '"POS"': '"WR"',
    '"Team"': '"DAL"',
    '"PosRank"': '76',
    '"AVGRank"': '194',
    '"AVGTier"': '9',
    '"Siegele8.25"': '194',
  },
  {
    '""': '"195"',
    '"Rank"': '195',
    '"Player"': '"Quentin Johnston"',
    '"POS"': '"WR"',
    '"Team"': '"LAC"',
    '"PosRank"': '77',
    '"AVGRank"': '195',
    '"AVGTier"': '9',
    '"Siegele8.25"': '195',
  },
  {
    '""': '"196"',
    '"Rank"': '196',
    '"Player"': '"Daniel Jones"',
    '"POS"': '"QB"',
    '"Team"': '"NYG"',
    '"PosRank"': '30',
    '"AVGRank"': '196',
    '"AVGTier"': '9',
    '"Siegele8.25"': '196',
  },
  {
    '""': '"197"',
    '"Rank"': '197',
    '"Player"': '"Adam Thielen"',
    '"POS"': '"WR"',
    '"Team"': '"CAR"',
    '"PosRank"': '78',
    '"AVGRank"': '197',
    '"AVGTier"': '9',
    '"Siegele8.25"': '197',
  },
  {
    '""': '"198"',
    '"Rank"': '198',
    '"Player"': '"DJ Chark"',
    '"POS"': '"WR"',
    '"Team"': '"LAC"',
    '"PosRank"': '79',
    '"AVGRank"': '198',
    '"AVGTier"': '9',
    '"Siegele8.25"': '198',
  },
  {
    '""': '"199"',
    '"Rank"': '199',
    '"Player"': '"Greg Dulcich"',
    '"POS"': '"TE"',
    '"Team"': '"DEN"',
    '"PosRank"': '27',
    '"AVGRank"': '200',
    '"AVGTier"': '9',
    '"Siegele8.25"': '200',
  },
  {
    '""': '"200"',
    '"Rank"': '200',
    '"Player"': '"Jonnu Smith"',
    '"POS"': '"TE"',
    '"Team"': '"MIA"',
    '"PosRank"': '28',
    '"AVGRank"': '199',
    '"AVGTier"': '9',
    '"Siegele8.25"': '199',
  },
  {
    '""': '"201"',
    '"Rank"': '201',
    '"Player"': '"Samaje Perine"',
    '"POS"': '"RB"',
    '"Team"': '"DEN"',
    '"PosRank"': '64',
    '"AVGRank"': '201',
    '"AVGTier"': '9',
    '"Siegele8.25"': '201',
  },
  {
    '""': '"202"',
    '"Rank"': '202',
    '"Player"': '"Dameon Pierce"',
    '"POS"': '"RB"',
    '"Team"': '"HOU"',
    '"PosRank"': '65',
    '"AVGRank"': '202',
    '"AVGTier"': '9',
    '"Siegele8.25"': '202',
  },
  {
    '""': '"203"',
    '"Rank"': '203',
    '"Player"': '"Roschon Johnson"',
    '"POS"': '"RB"',
    '"Team"': '"CHI"',
    '"PosRank"': '66',
    '"AVGRank"': '203',
    '"AVGTier"': '9',
    '"Siegele8.25"': '203',
  },
  {
    '""': '"204"',
    '"Rank"': '204',
    '"Player"': '"Dylan Laube"',
    '"POS"': '"RB"',
    '"Team"': '"LV"',
    '"PosRank"': '67',
    '"AVGRank"': '204',
    '"AVGTier"': '9',
    '"Siegele8.25"': '204',
  },
  {
    '""': '"205"',
    '"Rank"': '205',
    '"Player"': '"Jalin Hyatt"',
    '"POS"': '"WR"',
    '"Team"': '"NYG"',
    '"PosRank"': '80',
    '"AVGRank"': '206',
    '"AVGTier"': '9',
    '"Siegele8.25"': '206',
  },
  {
    '""': '"206"',
    '"Rank"': '206',
    '"Player"': '"Theo Johnson"',
    '"POS"': '"TE"',
    '"Team"': '"NYG"',
    '"PosRank"': '29',
    '"AVGRank"': '205',
    '"AVGTier"': '9',
    '"Siegele8.25"': '205',
  },
  {
    '""': '"207"',
    '"Rank"': '207',
    '"Player"': '"Greg Dortch"',
    '"POS"': '"WR"',
    '"Team"': '"ARI"',
    '"PosRank"': '81',
    '"AVGRank"': '207',
    '"AVGTier"': '9',
    '"Siegele8.25"': '207',
  },
  {
    '""': '"208"',
    '"Rank"': '208',
    '"Player"': '"Pierre Strong"',
    '"POS"': '"RB"',
    '"Team"': '"CLE"',
    '"PosRank"': '68',
    '"AVGRank"': '208',
    '"AVGTier"': '9',
    '"Siegele8.25"': '208',
  },
  {
    '""': '"209"',
    '"Rank"': '209',
    '"Player"': '"Jahan Dotson"',
    '"POS"': '"WR"',
    '"Team"': '"WAS"',
    '"PosRank"': '82',
    '"AVGRank"': '210',
    '"AVGTier"': '9',
    '"Siegele8.25"': '210',
  },
  {
    '""': '"210"',
    '"Rank"': '210',
    '"Player"': '"Demarcus Robinson"',
    '"POS"': '"WR"',
    '"Team"': '"LAR"',
    '"PosRank"': '83',
    '"AVGRank"': '209',
    '"AVGTier"': '9',
    '"Siegele8.25"': '209',
  },
  {
    '""': '"211"',
    '"Rank"': '211',
    '"Player"': '"Chigoziem Okonkwo"',
    '"POS"': '"TE"',
    '"Team"': '"TEN"',
    '"PosRank"': '30',
    '"AVGRank"': '211',
    '"AVGTier"': '9',
    '"Siegele8.25"': '211',
  },
  {
    '""': '"212"',
    '"Rank"': '212',
    '"Player"': '"Michael Mayer"',
    '"POS"': '"TE"',
    '"Team"': '"LV"',
    '"PosRank"': '31',
    '"AVGRank"': '212',
    '"AVGTier"': '9',
    '"Siegele8.25"': '212',
  },
  {
    '""': '"213"',
    '"Rank"': '213',
    '"Player"': '"Malachi Corley"',
    '"POS"': '"WR"',
    '"Team"': '"NYJ"',
    '"PosRank"': '84',
    '"AVGRank"': '213',
    '"AVGTier"': '9',
    '"Siegele8.25"': '213',
  },
  {
    '""': '"214"',
    '"Rank"': '214',
    '"Player"': '"Dawson Knox"',
    '"POS"': '"TE"',
    '"Team"': '"BUF"',
    '"PosRank"': '32',
    '"AVGRank"': '215',
    '"AVGTier"': '10',
    '"Siegele8.25"': '215',
  },
  {
    '""': '"215"',
    '"Rank"': '215',
    '"Player"': '"Isaac Guerendo"',
    '"POS"': '"RB"',
    '"Team"': '"SF"',
    '"PosRank"': '69',
    '"AVGRank"': '214',
    '"AVGTier"': '9',
    '"Siegele8.25"': '214',
  },
  {
    '""': '"216"',
    '"Rank"': '216',
    '"Player"': '"Cade Otton"',
    '"POS"': '"TE"',
    '"Team"': '"TB"',
    '"PosRank"': '33',
    '"AVGRank"': '217',
    '"AVGTier"': '10',
    '"Siegele8.25"': '217',
  },
  {
    '""': '"217"',
    '"Rank"': '217',
    '"Player"': '"Luke McCaffrey"',
    '"POS"': '"WR"',
    '"Team"': '"WAS"',
    '"PosRank"': '85',
    '"AVGRank"': '216',
    '"AVGTier"': '10',
    '"Siegele8.25"': '216',
  },
  {
    '""': '"218"',
    '"Rank"': '218',
    '"Player"': '"Keaton Mitchell"',
    '"POS"': '"RB"',
    '"Team"': '"BAL"',
    '"PosRank"': '70',
    '"AVGRank"': '219',
    '"AVGTier"': '10',
    '"Siegele8.25"': '219',
  },
  {
    '""': '"219"',
    '"Rank"': '219',
    '"Player"': '"Malik Washington"',
    '"POS"': '"WR"',
    '"Team"': '"MIA"',
    '"PosRank"': '86',
    '"AVGRank"': '218',
    '"AVGTier"': '10',
    '"Siegele8.25"': '218',
  },
  {
    '""': '"220"',
    '"Rank"': '220',
    '"Player"': '"Dalvin Cook"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '71',
    '"AVGRank"': '220',
    '"AVGTier"': '10',
    '"Siegele8.25"': '220',
  },
  {
    '""': '"221"',
    '"Rank"': '221',
    '"Player"': '"Alexander Mattison"',
    '"POS"': '"RB"',
    '"Team"': '"LV"',
    '"PosRank"': '72',
    '"AVGRank"': '221',
    '"AVGTier"': '10',
    '"Siegele8.25"': '221',
  },
  {
    '""': '"222"',
    '"Rank"': '222',
    '"Player"': '"Javon Baker"',
    '"POS"': '"WR"',
    '"Team"': '"NE"',
    '"PosRank"': '87',
    '"AVGRank"': '222',
    '"AVGTier"': '10',
    '"Siegele8.25"': '222',
  },
  {
    '""': '"223"',
    '"Rank"': '223',
    '"Player"': '"Roman Wilson"',
    '"POS"': '"WR"',
    '"Team"': '"PIT"',
    '"PosRank"': '88',
    '"AVGRank"': '223',
    '"AVGTier"': '10',
    '"Siegele8.25"': '223',
  },
  {
    '""': '"224"',
    '"Rank"': '224',
    '"Player"': '"Troy Franklin"',
    '"POS"': '"WR"',
    '"Team"': '"DEN"',
    '"PosRank"': '89',
    '"AVGRank"': '224',
    '"AVGTier"': '10',
    '"Siegele8.25"': '224',
  },
  {
    '""': '"225"',
    '"Rank"': '225',
    '"Player"': '"Zach Ertz"',
    '"POS"': '"TE"',
    '"Team"': '"WAS"',
    '"PosRank"': '34',
    '"AVGRank"': '226',
    '"AVGTier"': '10',
    '"Siegele8.25"': '226',
  },
  {
    '""': '"226"',
    '"Rank"': '226',
    '"Player"': '"Devontez Walker"',
    '"POS"': '"WR"',
    '"Team"': '"BAL"',
    '"PosRank"': '90',
    '"AVGRank"': '225',
    '"AVGTier"': '10',
    '"Siegele8.25"': '225',
  },
  {
    '""': '"227"',
    '"Rank"': '227',
    '"Player"': '"Colby Parkinson"',
    '"POS"': '"TE"',
    '"Team"': '"LAR"',
    '"PosRank"': '35',
    '"AVGRank"': '227',
    '"AVGTier"': '10',
    '"Siegele8.25"': '227',
  },
  {
    '""': '"228"',
    '"Rank"': '228',
    '"Player"': '"Russell Wilson"',
    '"POS"': '"QB"',
    '"Team"': '"PIT"',
    '"PosRank"': '31',
    '"AVGRank"': '229',
    '"AVGTier"': '10',
    '"Siegele8.25"': '229',
  },
  {
    '""': '"229"',
    '"Rank"': '229',
    '"Player"': '"Cody Schrader"',
    '"POS"': '"RB"',
    '"Team"': '"SF"',
    '"PosRank"': '73',
    '"AVGRank"': '228',
    '"AVGTier"': '10',
    '"Siegele8.25"': '228',
  },
  {
    '""': '"230"',
    '"Rank"': '230',
    '"Player"': '"Gardner Minshew"',
    '"POS"': '"QB"',
    '"Team"': '"LV"',
    '"PosRank"': '32',
    '"AVGRank"': '230',
    '"AVGTier"': '10',
    '"Siegele8.25"': '230',
  },
  {
    '""': '"231"',
    '"Rank"': '231',
    '"Player"': '"Tyler Boyd"',
    '"POS"': '"WR"',
    '"Team"': '"TEN"',
    '"PosRank"': '91',
    '"AVGRank"': '231',
    '"AVGTier"': '11',
    '"Siegele8.25"': '231',
  },
  {
    '""': '"232"',
    '"Rank"': '232',
    '"Player"': '"Jonathan Mingo"',
    '"POS"': '"WR"',
    '"Team"': '"CAR"',
    '"PosRank"': '92',
    '"AVGRank"': '232',
    '"AVGTier"': '11',
    '"Siegele8.25"': '232',
  },
  {
    '""': '"233"',
    '"Rank"': '233',
    '"Player"': '"Kendrick Bourne"',
    '"POS"': '"WR"',
    '"Team"': '"NE"',
    '"PosRank"': '93',
    '"AVGRank"': '233',
    '"AVGTier"': '11',
    '"Siegele8.25"': '233',
  },
  {
    '""': '"234"',
    '"Rank"': '234',
    '"Player"': '"Kenneth Gainwell"',
    '"POS"': '"RB"',
    '"Team"': '"PHI"',
    '"PosRank"': '74',
    '"AVGRank"': '234',
    '"AVGTier"': '11',
    '"Siegele8.25"': '234',
  },
  {
    '""': '"235"',
    '"Rank"': '235',
    '"Player"': '"Deneric Prince"',
    '"POS"': '"RB"',
    '"Team"': '"KC"',
    '"PosRank"': '75',
    '"AVGRank"': '235',
    '"AVGTier"': '11',
    '"Siegele8.25"': '235',
  },
  {
    '""': '"236"',
    '"Rank"': '236',
    '"Player"': '"Zay Jones"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '94',
    '"AVGRank"': '237',
    '"AVGTier"': '11',
    '"Siegele8.25"': '237',
  },
  {
    '""': '"237"',
    '"Rank"': '237',
    '"Player"': '"Johnny Wilson"',
    '"POS"': '"WR"',
    '"Team"': '"PHI"',
    '"PosRank"': '95',
    '"AVGRank"': '236',
    '"AVGTier"': '11',
    '"Siegele8.25"': '236',
  },
  {
    '""': '"238"',
    '"Rank"': '238',
    '"Player"': '"D\'Onta Foreman"',
    '"POS"': '"RB"',
    '"Team"': '"CLE"',
    '"PosRank"': '76',
    '"AVGRank"': '239',
    '"AVGTier"': '11',
    '"Siegele8.25"': '239',
  },
  {
    '""': '"239"',
    '"Rank"': '239',
    '"Player"': '"Jacob Cowing"',
    '"POS"': '"WR"',
    '"Team"': '"SF"',
    '"PosRank"': '96',
    '"AVGRank"': '238',
    '"AVGTier"': '11',
    '"Siegele8.25"': '238',
  },
  {
    '""': '"240"',
    '"Rank"': '240',
    '"Player"': '"Eric Gray"',
    '"POS"': '"RB"',
    '"Team"': '"NYG"',
    '"PosRank"': '77',
    '"AVGRank"': '240',
    '"AVGTier"': '11',
    '"Siegele8.25"': '240',
  },
  {
    '""': '"241"',
    '"Rank"': '241',
    '"Player"': '"Blake Watson"',
    '"POS"': '"RB"',
    '"Team"': '"DEN"',
    '"PosRank"': '78',
    '"AVGRank"': '241',
    '"AVGTier"': '11',
    '"Siegele8.25"': '241',
  },
  {
    '""': '"242"',
    '"Rank"': '242',
    '"Player"': '"Jaret Patterson"',
    '"POS"': '"RB"',
    '"Team"': '"LAC"',
    '"PosRank"': '79',
    '"AVGRank"': '242',
    '"AVGTier"': '11',
    '"Siegele8.25"': '242',
  },
  {
    '""': '"243"',
    '"Rank"': '243',
    '"Player"': '"Treylon Burks"',
    '"POS"': '"WR"',
    '"Team"': '"TEN"',
    '"PosRank"': '97',
    '"AVGRank"': '243',
    '"AVGTier"': '11',
    '"Siegele8.25"': '243',
  },
  {
    '""': '"244"',
    '"Rank"': '244',
    '"Player"': '"Darius Slayton"',
    '"POS"': '"WR"',
    '"Team"': '"NYG"',
    '"PosRank"': '98',
    '"AVGRank"': '245',
    '"AVGTier"': '11',
    '"Siegele8.25"': '245',
  },
  {
    '""': '"245"',
    '"Rank"': '245',
    '"Player"': '"Jaheim Bell"',
    '"POS"': '"TE"',
    '"Team"': '"NE"',
    '"PosRank"': '36',
    '"AVGRank"': '244',
    '"AVGTier"': '11',
    '"Siegele8.25"': '244',
  },
  {
    '""': '"246"',
    '"Rank"': '246',
    '"Player"': '"Tre Tucker"',
    '"POS"': '"WR"',
    '"Team"': '"LV"',
    '"PosRank"': '99',
    '"AVGRank"': '246',
    '"AVGTier"': '11',
    '"Siegele8.25"': '246',
  },
  {
    '""': '"247"',
    '"Rank"': '247',
    '"Player"': '"Daniel Bellinger"',
    '"POS"': '"TE"',
    '"Team"': '"NYG"',
    '"PosRank"': '37',
    '"AVGRank"': '247',
    '"AVGTier"': '11',
    '"Siegele8.25"': '247',
  },
  {
    '""': '"248"',
    '"Rank"': '248',
    '"Player"': '"A.T. Perry"',
    '"POS"': '"WR"',
    '"Team"': '"NO"',
    '"PosRank"': '100',
    '"AVGRank"': '248',
    '"AVGTier"': '11',
    '"Siegele8.25"': '248',
  },
  {
    '""': '"249"',
    '"Rank"': '249',
    '"Player"': '"Trey Palmer"',
    '"POS"': '"WR"',
    '"Team"': '"TB"',
    '"PosRank"': '101',
    '"AVGRank"': '249',
    '"AVGTier"': '11',
    '"Siegele8.25"': '249',
  },
  {
    '""': '"250"',
    '"Rank"': '250',
    '"Player"': '"Kadarius Toney"',
    '"POS"': '"WR"',
    '"Team"': '"KC"',
    '"PosRank"': '102',
    '"AVGRank"': '250',
    '"AVGTier"': '11',
    '"Siegele8.25"': '250',
  },
];
module.exports = before2024seasonRVRedraftRankings;
