const allNFLTeamPace = [
	{
		"\"Home\"": "\"CHI\"",
		"\"Away\"": "\"CAR\"",
		"\"Time\"": "\"THU 8:15 PM\"",
		"\"Sec_ALL_nt_h\"": "28.4",
		"\"Sec_ALL_nt_v\"": "27.6",
		"\"Sec_ALL_nt_avg\"": "28",
		"\"Plays_ALL_nt_h\"": "64",
		"\"Plays_ALL_nt_v\"": "62",
		"\"Plays_ALL_nt_avg\"": "63",
		"\"Sec_ALL_h\"": "25.3",
		"\"Sec_ALL_v\"": "23.1",
		"\"Sec_ALL_avg\"": "24.2",
		"\"Plays_ALL_h\"": "70",
		"\"Plays_ALL_v\"": "79",
		"\"PLays_ALL_avg\"": "74.5"
	},
	{
		"\"Home\"": "\"NE\"",
		"\"Away\"": "\"IND\"",
		"\"Time\"": "\"SUN 9:30 AM\"",
		"\"Sec_ALL_nt_h\"": "22.2",
		"\"Sec_ALL_nt_v\"": "25.6",
		"\"Sec_ALL_nt_avg\"": "23.9",
		"\"Plays_ALL_nt_h\"": "65",
		"\"Plays_ALL_nt_v\"": "69",
		"\"Plays_ALL_nt_avg\"": "67",
		"\"Sec_ALL_h\"": "21.1",
		"\"Sec_ALL_v\"": "22.3",
		"\"Sec_ALL_avg\"": "21.7",
		"\"Plays_ALL_h\"": "73",
		"\"Plays_ALL_v\"": "74",
		"\"PLays_ALL_avg\"": "73.5"
	},
	{
		"\"Home\"": "\"BAL\"",
		"\"Away\"": "\"CLE\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "28",
		"\"Sec_ALL_nt_v\"": "23.5",
		"\"Sec_ALL_nt_avg\"": "25.8",
		"\"Plays_ALL_nt_h\"": "71",
		"\"Plays_ALL_nt_v\"": "83",
		"\"Plays_ALL_nt_avg\"": "77",
		"\"Sec_ALL_h\"": "26",
		"\"Sec_ALL_v\"": "23.7",
		"\"Sec_ALL_avg\"": "24.9",
		"\"Plays_ALL_h\"": "72",
		"\"Plays_ALL_v\"": "84",
		"\"PLays_ALL_avg\"": "78"
	},
	{
		"\"Home\"": "\"CIN\"",
		"\"Away\"": "\"HOU\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "28.4",
		"\"Sec_ALL_nt_v\"": "24.3",
		"\"Sec_ALL_nt_avg\"": "26.4",
		"\"Plays_ALL_nt_h\"": "67",
		"\"Plays_ALL_nt_v\"": "67",
		"\"Plays_ALL_nt_avg\"": "67",
		"\"Sec_ALL_h\"": "25.4",
		"\"Sec_ALL_v\"": "22.1",
		"\"Sec_ALL_avg\"": "23.8",
		"\"Plays_ALL_h\"": "70",
		"\"Plays_ALL_v\"": "78",
		"\"PLays_ALL_avg\"": "74"
	},
	{
		"\"Home\"": "\"JAC\"",
		"\"Away\"": "\"SF\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "27.1",
		"\"Sec_ALL_nt_v\"": "26.8",
		"\"Sec_ALL_nt_avg\"": "27",
		"\"Plays_ALL_nt_h\"": "77",
		"\"Plays_ALL_nt_v\"": "69",
		"\"Plays_ALL_nt_avg\"": "73",
		"\"Sec_ALL_h\"": "24.4",
		"\"Sec_ALL_v\"": "25.4",
		"\"Sec_ALL_avg\"": "24.9",
		"\"Plays_ALL_h\"": "75",
		"\"Plays_ALL_v\"": "72",
		"\"PLays_ALL_avg\"": "73.5"
	},
	{
		"\"Home\"": "\"MIN\"",
		"\"Away\"": "\"NO\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "24.8",
		"\"Sec_ALL_nt_v\"": "23.7",
		"\"Sec_ALL_nt_avg\"": "24.2",
		"\"Plays_ALL_nt_h\"": "68",
		"\"Plays_ALL_nt_v\"": "73",
		"\"Plays_ALL_nt_avg\"": "70.5",
		"\"Sec_ALL_h\"": "22.9",
		"\"Sec_ALL_v\"": "23.3",
		"\"Sec_ALL_avg\"": "23.1",
		"\"Plays_ALL_h\"": "74",
		"\"Plays_ALL_v\"": "79",
		"\"PLays_ALL_avg\"": "76.5"
	},
	{
		"\"Home\"": "\"PIT\"",
		"\"Away\"": "\"GB\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "24",
		"\"Sec_ALL_nt_v\"": "24.9",
		"\"Sec_ALL_nt_avg\"": "24.4",
		"\"Plays_ALL_nt_h\"": "65",
		"\"Plays_ALL_nt_v\"": "63",
		"\"Plays_ALL_nt_avg\"": "64",
		"\"Sec_ALL_h\"": "22.5",
		"\"Sec_ALL_v\"": "22.2",
		"\"Sec_ALL_avg\"": "22.4",
		"\"Plays_ALL_h\"": "70",
		"\"Plays_ALL_v\"": "74",
		"\"PLays_ALL_avg\"": "72"
	},
	{
		"\"Home\"": "\"TB\"",
		"\"Away\"": "\"TEN\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "25.1",
		"\"Sec_ALL_nt_v\"": "26.5",
		"\"Sec_ALL_nt_avg\"": "25.8",
		"\"Plays_ALL_nt_h\"": "70",
		"\"Plays_ALL_nt_v\"": "66",
		"\"Plays_ALL_nt_avg\"": "68",
		"\"Sec_ALL_h\"": "23.6",
		"\"Sec_ALL_v\"": "24.9",
		"\"Sec_ALL_avg\"": "24.2",
		"\"Plays_ALL_h\"": "71",
		"\"Plays_ALL_v\"": "69",
		"\"PLays_ALL_avg\"": "70"
	},
	{
		"\"Home\"": "\"ARI\"",
		"\"Away\"": "\"ATL\"",
		"\"Time\"": "\"SUN 4:05 PM\"",
		"\"Sec_ALL_nt_h\"": "26.2",
		"\"Sec_ALL_nt_v\"": "24.6",
		"\"Sec_ALL_nt_avg\"": "25.4",
		"\"Plays_ALL_nt_h\"": "61",
		"\"Plays_ALL_nt_v\"": "67",
		"\"Plays_ALL_nt_avg\"": "64",
		"\"Sec_ALL_h\"": "22.9",
		"\"Sec_ALL_v\"": "22.3",
		"\"Sec_ALL_avg\"": "22.6",
		"\"Plays_ALL_h\"": "71",
		"\"Plays_ALL_v\"": "79",
		"\"PLays_ALL_avg\"": "75"
	},
	{
		"\"Home\"": "\"LAC\"",
		"\"Away\"": "\"DET\"",
		"\"Time\"": "\"SUN 4:05 PM\"",
		"\"Sec_ALL_nt_h\"": "25.1",
		"\"Sec_ALL_nt_v\"": "28.6",
		"\"Sec_ALL_nt_avg\"": "26.9",
		"\"Plays_ALL_nt_h\"": "70",
		"\"Plays_ALL_nt_v\"": "68",
		"\"Plays_ALL_nt_avg\"": "69",
		"\"Sec_ALL_h\"": "23.4",
		"\"Sec_ALL_v\"": "26",
		"\"Sec_ALL_avg\"": "24.7",
		"\"Plays_ALL_h\"": "70",
		"\"Plays_ALL_v\"": "75",
		"\"PLays_ALL_avg\"": "72.5"
	},
	{
		"\"Home\"": "\"DAL\"",
		"\"Away\"": "\"NYG\"",
		"\"Time\"": "\"SUN 4:25 PM\"",
		"\"Sec_ALL_nt_h\"": "24.2",
		"\"Sec_ALL_nt_v\"": "26.6",
		"\"Sec_ALL_nt_avg\"": "25.4",
		"\"Plays_ALL_nt_h\"": "67",
		"\"Plays_ALL_nt_v\"": "66",
		"\"Plays_ALL_nt_avg\"": "66.5",
		"\"Sec_ALL_h\"": "24.4",
		"\"Sec_ALL_v\"": "24.4",
		"\"Sec_ALL_avg\"": "24.4",
		"\"Plays_ALL_h\"": "77",
		"\"Plays_ALL_v\"": "74",
		"\"PLays_ALL_avg\"": "75.5"
	},
	{
		"\"Home\"": "\"SEA\"",
		"\"Away\"": "\"WAS\"",
		"\"Time\"": "\"SUN 4:25 PM\"",
		"\"Sec_ALL_nt_h\"": "26.6",
		"\"Sec_ALL_nt_v\"": "26.2",
		"\"Sec_ALL_nt_avg\"": "26.4",
		"\"Plays_ALL_nt_h\"": "65",
		"\"Plays_ALL_nt_v\"": "73",
		"\"Plays_ALL_nt_avg\"": "69",
		"\"Sec_ALL_h\"": "23.3",
		"\"Sec_ALL_v\"": "23.4",
		"\"Sec_ALL_avg\"": "23.4",
		"\"Plays_ALL_h\"": "67",
		"\"Plays_ALL_v\"": "77",
		"\"PLays_ALL_avg\"": "72"
	},
	{
		"\"Home\"": "\"LV\"",
		"\"Away\"": "\"NYJ\"",
		"\"Time\"": "\"SUN 8:20 PM\"",
		"\"Sec_ALL_nt_h\"": "26.8",
		"\"Sec_ALL_nt_v\"": "24.3",
		"\"Sec_ALL_nt_avg\"": "25.6",
		"\"Plays_ALL_nt_h\"": "60",
		"\"Plays_ALL_nt_v\"": "55",
		"\"Plays_ALL_nt_avg\"": "57.5",
		"\"Sec_ALL_h\"": "24.7",
		"\"Sec_ALL_v\"": "23.4",
		"\"Sec_ALL_avg\"": "24",
		"\"Plays_ALL_h\"": "66",
		"\"Plays_ALL_v\"": "66",
		"\"PLays_ALL_avg\"": "66"
	},
	{
		"\"Home\"": "\"BUF\"",
		"\"Away\"": "\"DEN\"",
		"\"Time\"": "\"MON 8:15 PM\"",
		"\"Sec_ALL_nt_h\"": "26.1",
		"\"Sec_ALL_nt_v\"": "28.9",
		"\"Sec_ALL_nt_avg\"": "27.5",
		"\"Plays_ALL_nt_h\"": "61",
		"\"Plays_ALL_nt_v\"": "56",
		"\"Plays_ALL_nt_avg\"": "58.5",
		"\"Sec_ALL_h\"": "25.7",
		"\"Sec_ALL_v\"": "25.3",
		"\"Sec_ALL_avg\"": "25.5",
		"\"Plays_ALL_h\"": "69",
		"\"Plays_ALL_v\"": "64",
		"\"PLays_ALL_avg\"": "66.5"
	},
	
]

module.exports = allNFLTeamPace;