const allNFLTeamPace = [
	{
		"\"Home\"": "\"BUF\"",
		"\"Away\"": "\"TB\"",
		"\"Time\"": "\"THU 8:15 PM\"",
		"\"Sec_ALL_nt_h\"": "25.9",
		"\"Sec_ALL_nt_v\"": "26.2",
		"\"Sec_ALL_nt_avg\"": "26",
		"\"Plays_ALL_nt_h\"": "61",
		"\"Plays_ALL_nt_v\"": "69",
		"\"Plays_ALL_nt_avg\"": "65",
		"\"Sec_ALL_h\"": "26.4",
		"\"Sec_ALL_v\"": "24.4",
		"\"Sec_ALL_avg\"": "25.4",
		"\"Plays_ALL_h\"": "69",
		"\"Plays_ALL_v\"": "68",
		"\"PLays_ALL_avg\"": "68.5"
	},
	{
		"\"Home\"": "\"CAR\"",
		"\"Away\"": "\"HOU\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "27.8",
		"\"Sec_ALL_nt_v\"": "23.2",
		"\"Sec_ALL_nt_avg\"": "25.5",
		"\"Plays_ALL_nt_h\"": "64",
		"\"Plays_ALL_nt_v\"": "71",
		"\"Plays_ALL_nt_avg\"": "67.5",
		"\"Sec_ALL_h\"": "22.7",
		"\"Sec_ALL_v\"": "21.4",
		"\"Sec_ALL_avg\"": "22",
		"\"Plays_ALL_h\"": "81",
		"\"Plays_ALL_v\"": "81",
		"\"PLays_ALL_avg\"": "81"
	},
	{
		"\"Home\"": "\"DAL\"",
		"\"Away\"": "\"LAR\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "25",
		"\"Sec_ALL_nt_v\"": "28.8",
		"\"Sec_ALL_nt_avg\"": "26.9",
		"\"Plays_ALL_nt_h\"": "63",
		"\"Plays_ALL_nt_v\"": "62",
		"\"Plays_ALL_nt_avg\"": "62.5",
		"\"Sec_ALL_h\"": "24.1",
		"\"Sec_ALL_v\"": "25.6",
		"\"Sec_ALL_avg\"": "24.9",
		"\"Plays_ALL_h\"": "77",
		"\"Plays_ALL_v\"": "72",
		"\"PLays_ALL_avg\"": "74.5"
	},
	{
		"\"Home\"": "\"GB\"",
		"\"Away\"": "\"MIN\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "23.8",
		"\"Sec_ALL_nt_v\"": "24.5",
		"\"Sec_ALL_nt_avg\"": "24.1",
		"\"Plays_ALL_nt_h\"": "68",
		"\"Plays_ALL_nt_v\"": "66",
		"\"Plays_ALL_nt_avg\"": "67",
		"\"Sec_ALL_h\"": "22.2",
		"\"Sec_ALL_v\"": "22.4",
		"\"Sec_ALL_avg\"": "22.3",
		"\"Plays_ALL_h\"": "73",
		"\"Plays_ALL_v\"": "72",
		"\"PLays_ALL_avg\"": "72.5"
	},
	{
		"\"Home\"": "\"IND\"",
		"\"Away\"": "\"NO\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "25",
		"\"Sec_ALL_nt_v\"": "22.7",
		"\"Sec_ALL_nt_avg\"": "23.9",
		"\"Plays_ALL_nt_h\"": "66",
		"\"Plays_ALL_nt_v\"": "78",
		"\"Plays_ALL_nt_avg\"": "72",
		"\"Sec_ALL_h\"": "21.9",
		"\"Sec_ALL_v\"": "22.9",
		"\"Sec_ALL_avg\"": "22.4",
		"\"Plays_ALL_h\"": "75",
		"\"Plays_ALL_v\"": "81",
		"\"PLays_ALL_avg\"": "78"
	},
	{
		"\"Home\"": "\"MIA\"",
		"\"Away\"": "\"NE\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "27",
		"\"Sec_ALL_nt_v\"": "23",
		"\"Sec_ALL_nt_avg\"": "25",
		"\"Plays_ALL_nt_h\"": "62",
		"\"Plays_ALL_nt_v\"": "68",
		"\"Plays_ALL_nt_avg\"": "65",
		"\"Sec_ALL_h\"": "24.7",
		"\"Sec_ALL_v\"": "21.7",
		"\"Sec_ALL_avg\"": "23.2",
		"\"Plays_ALL_h\"": "67",
		"\"Plays_ALL_v\"": "73",
		"\"PLays_ALL_avg\"": "70"
	},
	{
		"\"Home\"": "\"NYG\"",
		"\"Away\"": "\"NYJ\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "25.7",
		"\"Sec_ALL_nt_v\"": "25.9",
		"\"Sec_ALL_nt_avg\"": "25.8",
		"\"Plays_ALL_nt_h\"": "67",
		"\"Plays_ALL_nt_v\"": "52",
		"\"Plays_ALL_nt_avg\"": "59.5",
		"\"Sec_ALL_h\"": "23.9",
		"\"Sec_ALL_v\"": "24.1",
		"\"Sec_ALL_avg\"": "24",
		"\"Plays_ALL_h\"": "75",
		"\"Plays_ALL_v\"": "64",
		"\"PLays_ALL_avg\"": "69.5"
	},
	{
		"\"Home\"": "\"PIT\"",
		"\"Away\"": "\"JAC\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "23.1",
		"\"Sec_ALL_nt_v\"": "26.6",
		"\"Sec_ALL_nt_avg\"": "24.9",
		"\"Plays_ALL_nt_h\"": "70",
		"\"Plays_ALL_nt_v\"": "76",
		"\"Plays_ALL_nt_avg\"": "73",
		"\"Sec_ALL_h\"": "22.1",
		"\"Sec_ALL_v\"": "24.3",
		"\"Sec_ALL_avg\"": "23.2",
		"\"Plays_ALL_h\"": "70",
		"\"Plays_ALL_v\"": "74",
		"\"PLays_ALL_avg\"": "72"
	},
	{
		"\"Home\"": "\"TEN\"",
		"\"Away\"": "\"ATL\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "28.4",
		"\"Sec_ALL_nt_v\"": "25.2",
		"\"Sec_ALL_nt_avg\"": "26.8",
		"\"Plays_ALL_nt_h\"": "58",
		"\"Plays_ALL_nt_v\"": "67",
		"\"Plays_ALL_nt_avg\"": "62.5",
		"\"Sec_ALL_h\"": "26.4",
		"\"Sec_ALL_v\"": "22.5",
		"\"Sec_ALL_avg\"": "24.4",
		"\"Plays_ALL_h\"": "64",
		"\"Plays_ALL_v\"": "81",
		"\"PLays_ALL_avg\"": "72.5"
	},
	{
		"\"Home\"": "\"WAS\"",
		"\"Away\"": "\"PHI\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "25.6",
		"\"Sec_ALL_nt_v\"": "27.4",
		"\"Sec_ALL_nt_avg\"": "26.5",
		"\"Plays_ALL_nt_h\"": "72",
		"\"Plays_ALL_nt_v\"": "74",
		"\"Plays_ALL_nt_avg\"": "73",
		"\"Sec_ALL_h\"": "22.8",
		"\"Sec_ALL_v\"": "26.1",
		"\"Sec_ALL_avg\"": "24.5",
		"\"Plays_ALL_h\"": "76",
		"\"Plays_ALL_v\"": "77",
		"\"PLays_ALL_avg\"": "76.5"
	},
	{
		"\"Home\"": "\"SEA\"",
		"\"Away\"": "\"CLE\"",
		"\"Time\"": "\"SUN 4:05 PM\"",
		"\"Sec_ALL_nt_h\"": "27",
		"\"Sec_ALL_nt_v\"": "23.3",
		"\"Sec_ALL_nt_avg\"": "25.1",
		"\"Plays_ALL_nt_h\"": "67",
		"\"Plays_ALL_nt_v\"": "82",
		"\"Plays_ALL_nt_avg\"": "74.5",
		"\"Sec_ALL_h\"": "24",
		"\"Sec_ALL_v\"": "23.6",
		"\"Sec_ALL_avg\"": "23.8",
		"\"Plays_ALL_h\"": "70",
		"\"Plays_ALL_v\"": "82",
		"\"PLays_ALL_avg\"": "76"
	},
	{
		"\"Home\"": "\"ARI\"",
		"\"Away\"": "\"BAL\"",
		"\"Time\"": "\"SUN 4:25 PM\"",
		"\"Sec_ALL_nt_h\"": "25.7",
		"\"Sec_ALL_nt_v\"": "27.9",
		"\"Sec_ALL_nt_avg\"": "26.8",
		"\"Plays_ALL_nt_h\"": "63",
		"\"Plays_ALL_nt_v\"": "73",
		"\"Plays_ALL_nt_avg\"": "68",
		"\"Sec_ALL_h\"": "22.9",
		"\"Sec_ALL_v\"": "25.7",
		"\"Sec_ALL_avg\"": "24.3",
		"\"Plays_ALL_h\"": "72",
		"\"Plays_ALL_v\"": "70",
		"\"PLays_ALL_avg\"": "71"
	},
	{
		"\"Home\"": "\"DEN\"",
		"\"Away\"": "\"KC\"",
		"\"Time\"": "\"SUN 4:25 PM\"",
		"\"Sec_ALL_nt_h\"": "28.4",
		"\"Sec_ALL_nt_v\"": "27.6",
		"\"Sec_ALL_nt_avg\"": "28",
		"\"Plays_ALL_nt_h\"": "54",
		"\"Plays_ALL_nt_v\"": "73",
		"\"Plays_ALL_nt_avg\"": "63.5",
		"\"Sec_ALL_h\"": "24.9",
		"\"Sec_ALL_v\"": "25.9",
		"\"Sec_ALL_avg\"": "25.4",
		"\"Plays_ALL_h\"": "63",
		"\"Plays_ALL_v\"": "74",
		"\"PLays_ALL_avg\"": "68.5"
	},
	{
		"\"Home\"": "\"SF\"",
		"\"Away\"": "\"CIN\"",
		"\"Time\"": "\"SUN 4:25 PM\"",
		"\"Sec_ALL_nt_h\"": "25.8",
		"\"Sec_ALL_nt_v\"": "27.7",
		"\"Sec_ALL_nt_avg\"": "26.8",
		"\"Plays_ALL_nt_h\"": "74",
		"\"Plays_ALL_nt_v\"": "64",
		"\"Plays_ALL_nt_avg\"": "69",
		"\"Sec_ALL_h\"": "25.1",
		"\"Sec_ALL_v\"": "24.8",
		"\"Sec_ALL_avg\"": "25",
		"\"Plays_ALL_h\"": "74",
		"\"Plays_ALL_v\"": "69",
		"\"PLays_ALL_avg\"": "71.5"
	},
	{
		"\"Home\"": "\"LAC\"",
		"\"Away\"": "\"CHI\"",
		"\"Time\"": "\"SUN 8:20 PM\"",
		"\"Sec_ALL_nt_h\"": "24.8",
		"\"Sec_ALL_nt_v\"": "29.6",
		"\"Sec_ALL_nt_avg\"": "27.2",
		"\"Plays_ALL_nt_h\"": "69",
		"\"Plays_ALL_nt_v\"": "63",
		"\"Plays_ALL_nt_avg\"": "66",
		"\"Sec_ALL_h\"": "23.1",
		"\"Sec_ALL_v\"": "25.8",
		"\"Sec_ALL_avg\"": "24.5",
		"\"Plays_ALL_h\"": "71",
		"\"Plays_ALL_v\"": "68",
		"\"PLays_ALL_avg\"": "69.5"
	},
	{
		"\"Home\"": "\"DET\"",
		"\"Away\"": "\"LV\"",
		"\"Time\"": "\"MON 8:15 PM\"",
		"\"Sec_ALL_nt_h\"": "28.7",
		"\"Sec_ALL_nt_v\"": "26.9",
		"\"Sec_ALL_nt_avg\"": "27.8",
		"\"Plays_ALL_nt_h\"": "64",
		"\"Plays_ALL_nt_v\"": "64",
		"\"Plays_ALL_nt_avg\"": "64",
		"\"Sec_ALL_h\"": "25.8",
		"\"Sec_ALL_v\"": "24.7",
		"\"Sec_ALL_avg\"": "25.2",
		"\"Plays_ALL_h\"": "73",
		"\"Plays_ALL_v\"": "68",
		"\"PLays_ALL_avg\"": "70.5"
	},
	
]

module.exports = allNFLTeamPace;