const allNFLTeamPace = [
	{
		"\"Home\"": "\"GB\"",
		"\"Away\"": "\"DET\"",
		"\"Time\"": "\"THU 8:15 PM\"",
		"\"Sec_ALL_nt_h\"": "25.5",
		"\"Sec_ALL_nt_v\"": "27.7",
		"\"Sec_ALL_nt_avg\"": "26.6",
		"\"Plays_ALL_nt_h\"": "69",
		"\"Plays_ALL_nt_v\"": "63",
		"\"Plays_ALL_nt_avg\"": "66",
		"\"Sec_ALL_h\"": "23.4",
		"\"Sec_ALL_v\"": "25.9",
		"\"Sec_ALL_avg\"": "24.6",
		"\"Plays_ALL_h\"": "71",
		"\"Plays_ALL_v\"": "69",
		"\"PLays_ALL_avg\"": "70"
	},
	{
		"\"Home\"": "\"JAC\"",
		"\"Away\"": "\"ATL\"",
		"\"Time\"": "\"SUN 9:30 AM\"",
		"\"Sec_ALL_nt_h\"": "27.7",
		"\"Sec_ALL_nt_v\"": "25.4",
		"\"Sec_ALL_nt_avg\"": "26.5",
		"\"Plays_ALL_nt_h\"": "65",
		"\"Plays_ALL_nt_v\"": "61",
		"\"Plays_ALL_nt_avg\"": "63",
		"\"Sec_ALL_h\"": "24.4",
		"\"Sec_ALL_v\"": "21.9",
		"\"Sec_ALL_avg\"": "23.1",
		"\"Plays_ALL_h\"": "74",
		"\"Plays_ALL_v\"": "78",
		"\"PLays_ALL_avg\"": "76"
	},
	{
		"\"Home\"": "\"BUF\"",
		"\"Away\"": "\"MIA\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "28.1",
		"\"Sec_ALL_nt_v\"": "27",
		"\"Sec_ALL_nt_avg\"": "27.6",
		"\"Plays_ALL_nt_h\"": "66",
		"\"Plays_ALL_nt_v\"": "76",
		"\"Plays_ALL_nt_avg\"": "71",
		"\"Sec_ALL_h\"": "27.4",
		"\"Sec_ALL_v\"": "24.8",
		"\"Sec_ALL_avg\"": "26.1",
		"\"Plays_ALL_h\"": "74",
		"\"Plays_ALL_v\"": "72",
		"\"PLays_ALL_avg\"": "73"
	},
	{
		"\"Home\"": "\"CAR\"",
		"\"Away\"": "\"MIN\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "27.8",
		"\"Sec_ALL_nt_v\"": "24.1",
		"\"Sec_ALL_nt_avg\"": "26",
		"\"Plays_ALL_nt_h\"": "60",
		"\"Plays_ALL_nt_v\"": "66",
		"\"Plays_ALL_nt_avg\"": "63",
		"\"Sec_ALL_h\"": "22.1",
		"\"Sec_ALL_v\"": "22.1",
		"\"Sec_ALL_avg\"": "22.1",
		"\"Plays_ALL_h\"": "80",
		"\"Plays_ALL_v\"": "74",
		"\"PLays_ALL_avg\"": "77"
	},
	{
		"\"Home\"": "\"CHI\"",
		"\"Away\"": "\"DEN\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "29",
		"\"Sec_ALL_nt_v\"": "29.6",
		"\"Sec_ALL_nt_avg\"": "29.3",
		"\"Plays_ALL_nt_h\"": "48",
		"\"Plays_ALL_nt_v\"": "49",
		"\"Plays_ALL_nt_avg\"": "48.5",
		"\"Sec_ALL_h\"": "23.7",
		"\"Sec_ALL_v\"": "24.8",
		"\"Sec_ALL_avg\"": "24.2",
		"\"Plays_ALL_h\"": "64",
		"\"Plays_ALL_v\"": "67",
		"\"PLays_ALL_avg\"": "65.5"
	},
	{
		"\"Home\"": "\"CLE\"",
		"\"Away\"": "\"BAL\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "26.6",
		"\"Sec_ALL_nt_v\"": "26.3",
		"\"Sec_ALL_nt_avg\"": "26.5",
		"\"Plays_ALL_nt_h\"": "79",
		"\"Plays_ALL_nt_v\"": "73",
		"\"Plays_ALL_nt_avg\"": "76",
		"\"Sec_ALL_h\"": "27.2",
		"\"Sec_ALL_v\"": "24.9",
		"\"Sec_ALL_avg\"": "26",
		"\"Plays_ALL_h\"": "79",
		"\"Plays_ALL_v\"": "71",
		"\"PLays_ALL_avg\"": "75"
	},
	{
		"\"Home\"": "\"HOU\"",
		"\"Away\"": "\"PIT\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "25.5",
		"\"Sec_ALL_nt_v\"": "22.8",
		"\"Sec_ALL_nt_avg\"": "24.1",
		"\"Plays_ALL_nt_h\"": "62",
		"\"Plays_ALL_nt_v\"": "73",
		"\"Plays_ALL_nt_avg\"": "67.5",
		"\"Sec_ALL_h\"": "20.8",
		"\"Sec_ALL_v\"": "20.9",
		"\"Sec_ALL_avg\"": "20.9",
		"\"Plays_ALL_h\"": "86",
		"\"Plays_ALL_v\"": "70",
		"\"PLays_ALL_avg\"": "78"
	},
	{
		"\"Home\"": "\"IND\"",
		"\"Away\"": "\"LAR\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "23.1",
		"\"Sec_ALL_nt_v\"": "28.5",
		"\"Sec_ALL_nt_avg\"": "25.8",
		"\"Plays_ALL_nt_h\"": "73",
		"\"Plays_ALL_nt_v\"": "63",
		"\"Plays_ALL_nt_avg\"": "68",
		"\"Sec_ALL_h\"": "21.4",
		"\"Sec_ALL_v\"": "23.4",
		"\"Sec_ALL_avg\"": "22.4",
		"\"Plays_ALL_h\"": "75",
		"\"Plays_ALL_v\"": "80",
		"\"PLays_ALL_avg\"": "77.5"
	},
	{
		"\"Home\"": "\"NO\"",
		"\"Away\"": "\"TB\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "24.2",
		"\"Sec_ALL_nt_v\"": "28.1",
		"\"Sec_ALL_nt_avg\"": "26.1",
		"\"Plays_ALL_nt_h\"": "73",
		"\"Plays_ALL_nt_v\"": "69",
		"\"Plays_ALL_nt_avg\"": "71",
		"\"Sec_ALL_h\"": "22.7",
		"\"Sec_ALL_v\"": "26.1",
		"\"Sec_ALL_avg\"": "24.4",
		"\"Plays_ALL_h\"": "75",
		"\"Plays_ALL_v\"": "65",
		"\"PLays_ALL_avg\"": "70"
	},
	{
		"\"Home\"": "\"PHI\"",
		"\"Away\"": "\"WAS\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "26.6",
		"\"Sec_ALL_nt_v\"": "29.8",
		"\"Sec_ALL_nt_avg\"": "28.2",
		"\"Plays_ALL_nt_h\"": "81",
		"\"Plays_ALL_nt_v\"": "65",
		"\"Plays_ALL_nt_avg\"": "73",
		"\"Sec_ALL_h\"": "26.5",
		"\"Sec_ALL_v\"": "25",
		"\"Sec_ALL_avg\"": "25.8",
		"\"Plays_ALL_h\"": "81",
		"\"Plays_ALL_v\"": "70",
		"\"PLays_ALL_avg\"": "75.5"
	},
	{
		"\"Home\"": "\"TEN\"",
		"\"Away\"": "\"CIN\"",
		"\"Time\"": "\"SUN 1:00 PM\"",
		"\"Sec_ALL_nt_h\"": "28.9",
		"\"Sec_ALL_nt_v\"": "26.6",
		"\"Sec_ALL_nt_avg\"": "27.8",
		"\"Plays_ALL_nt_h\"": "60",
		"\"Plays_ALL_nt_v\"": "61",
		"\"Plays_ALL_nt_avg\"": "60.5",
		"\"Sec_ALL_h\"": "26.3",
		"\"Sec_ALL_v\"": "24.8",
		"\"Sec_ALL_avg\"": "25.6",
		"\"Plays_ALL_h\"": "63",
		"\"Plays_ALL_v\"": "68",
		"\"PLays_ALL_avg\"": "65.5"
	},
	{
		"\"Home\"": "\"LAC\"",
		"\"Away\"": "\"LV\"",
		"\"Time\"": "\"SUN 4:05 PM\"",
		"\"Sec_ALL_nt_h\"": "23.9",
		"\"Sec_ALL_nt_v\"": "25.2",
		"\"Sec_ALL_nt_avg\"": "24.5",
		"\"Plays_ALL_nt_h\"": "69",
		"\"Plays_ALL_nt_v\"": "60",
		"\"Plays_ALL_nt_avg\"": "64.5",
		"\"Sec_ALL_h\"": "22.1",
		"\"Sec_ALL_v\"": "24",
		"\"Sec_ALL_avg\"": "23.1",
		"\"Plays_ALL_h\"": "73",
		"\"Plays_ALL_v\"": "63",
		"\"PLays_ALL_avg\"": "68"
	},
	{
		"\"Home\"": "\"DAL\"",
		"\"Away\"": "\"NE\"",
		"\"Time\"": "\"SUN 4:25 PM\"",
		"\"Sec_ALL_nt_h\"": "26",
		"\"Sec_ALL_nt_v\"": "22.1",
		"\"Sec_ALL_nt_avg\"": "24.1",
		"\"Plays_ALL_nt_h\"": "61",
		"\"Plays_ALL_nt_v\"": "75",
		"\"Plays_ALL_nt_avg\"": "68",
		"\"Sec_ALL_h\"": "25",
		"\"Sec_ALL_v\"": "21.7",
		"\"Sec_ALL_avg\"": "23.4",
		"\"Plays_ALL_h\"": "81",
		"\"Plays_ALL_v\"": "80",
		"\"PLays_ALL_avg\"": "80.5"
	},
	{
		"\"Home\"": "\"SF\"",
		"\"Away\"": "\"ARI\"",
		"\"Time\"": "\"SUN 4:25 PM\"",
		"\"Sec_ALL_nt_h\"": "29.2",
		"\"Sec_ALL_nt_v\"": "26.2",
		"\"Sec_ALL_nt_avg\"": "27.7",
		"\"Plays_ALL_nt_h\"": "72",
		"\"Plays_ALL_nt_v\"": "78",
		"\"Plays_ALL_nt_avg\"": "75",
		"\"Sec_ALL_h\"": "26.4",
		"\"Sec_ALL_v\"": "24.8",
		"\"Sec_ALL_avg\"": "25.6",
		"\"Plays_ALL_h\"": "77",
		"\"Plays_ALL_v\"": "66",
		"\"PLays_ALL_avg\"": "71.5"
	},
	{
		"\"Home\"": "\"NYJ\"",
		"\"Away\"": "\"KC\"",
		"\"Time\"": "\"SUN 8:20 PM\"",
		"\"Sec_ALL_nt_h\"": "26.3",
		"\"Sec_ALL_nt_v\"": "25.9",
		"\"Sec_ALL_nt_avg\"": "26.1",
		"\"Plays_ALL_nt_h\"": "43",
		"\"Plays_ALL_nt_v\"": "69",
		"\"Plays_ALL_nt_avg\"": "56",
		"\"Sec_ALL_h\"": "24.2",
		"\"Sec_ALL_v\"": "25.3",
		"\"Sec_ALL_avg\"": "24.8",
		"\"Plays_ALL_h\"": "55",
		"\"Plays_ALL_v\"": "74",
		"\"PLays_ALL_avg\"": "64.5"
	},
	{
		"\"Home\"": "\"NYG\"",
		"\"Away\"": "\"SEA\"",
		"\"Time\"": "\"MON 8:15 PM\"",
		"\"Sec_ALL_nt_h\"": "24.2",
		"\"Sec_ALL_nt_v\"": "28.4",
		"\"Sec_ALL_nt_avg\"": "26.3",
		"\"Plays_ALL_nt_h\"": "54",
		"\"Plays_ALL_nt_v\"": "64",
		"\"Plays_ALL_nt_avg\"": "59",
		"\"Sec_ALL_h\"": "23.2",
		"\"Sec_ALL_v\"": "25.3",
		"\"Sec_ALL_avg\"": "24.2",
		"\"Plays_ALL_h\"": "70",
		"\"Plays_ALL_v\"": "65",
		"\"PLays_ALL_avg\"": "67.5"
	},
	
]

module.exports = allNFLTeamPace;