const fantasyPointsBrowser4for4ForQBLastFiveWeeks = [
	{
		"Player": "\"Lamar Jackson\"",
		"Pos": "QB",
		"Team": "BAL",
		"G": "5",
		"W3": "26.0",
		"W4": "23.6",
		"W5": "33.4",
		"W6": "18.9",
		"W7": "34.4",
		"\"FF Pts\"": "136.4",
		"\"FF Pts/G\"": "27.3"
	},
	{
		"Player": "\"Baker Mayfield\"",
		"Pos": "QB",
		"Team": "TB",
		"G": "5",
		"W3": "8.5",
		"W4": "28.9",
		"W5": "23.4",
		"W6": "25.9",
		"W7": "27.0",
		"\"FF Pts\"": "113.7",
		"\"FF Pts/G\"": "22.7"
	},
	{
		"Player": "\"Joe Burrow\"",
		"Pos": "QB",
		"Team": "CIN",
		"G": "5",
		"W3": "25.4",
		"W4": "16.3",
		"W5": "33.8",
		"W6": "19.8",
		"W7": "14.9",
		"\"FF Pts\"": "110.2",
		"\"FF Pts/G\"": "22.0"
	},
	{
		"Player": "\"Josh Allen\"",
		"Pos": "QB",
		"Team": "BUF",
		"G": "5",
		"W3": "30.9",
		"W4": "7.3",
		"W5": "14.6",
		"W6": "24.4",
		"W7": "21.0",
		"\"FF Pts\"": "98.3",
		"\"FF Pts/G\"": "19.7"
	},
	{
		"Player": "\"Jayden Daniels\"",
		"Pos": "QB",
		"Team": "WAS",
		"G": "5",
		"W3": "28.1",
		"W4": "24.0",
		"W5": "19.7",
		"W6": "21.0",
		"W7": "5.2",
		"\"FF Pts\"": "98.0",
		"\"FF Pts/G\"": "19.6"
	},
	{
		"Player": "\"Brock Purdy\"",
		"Pos": "QB",
		"Team": "SF",
		"G": "5",
		"W3": "25.8",
		"W4": "14.6",
		"W5": "13.1",
		"W6": "24.1",
		"W7": "17.2",
		"\"FF Pts\"": "94.7",
		"\"FF Pts/G\"": "18.9"
	},
	{
		"Player": "\"Justin Fields\"",
		"Pos": "QB",
		"Team": "PIT",
		"G": "4",
		"W3": "18.4",
		"W4": "32.0",
		"W5": "15.9",
		"W6": "23.7",
		"W7": "-",
		"\"FF Pts\"": "90.0",
		"\"FF Pts/G\"": "22.5"
	},
	{
		"Player": "\"Jordan Love\"",
		"Pos": "QB",
		"Team": "GB",
		"G": "4",
		"W3": "-",
		"W4": "28.2",
		"W5": "16.0",
		"W6": "25.6",
		"W7": "16.8",
		"\"FF Pts\"": "86.5",
		"\"FF Pts/G\"": "21.6"
	},
	{
		"Player": "\"Geno Smith\"",
		"Pos": "QB",
		"Team": "SEA",
		"G": "5",
		"W3": "11.4",
		"W4": "21.6",
		"W5": "22.6",
		"W6": "12.5",
		"W7": "17.8",
		"\"FF Pts\"": "85.8",
		"\"FF Pts/G\"": "17.2"
	},
	{
		"Player": "\"Jared Goff\"",
		"Pos": "QB",
		"Team": "DET",
		"G": "4",
		"W3": "14.6",
		"W4": "26.2",
		"W5": "-",
		"W6": "25.1",
		"W7": "18.8",
		"\"FF Pts\"": "84.6",
		"\"FF Pts/G\"": "21.2"
	},
	{
		"Player": "\"Bo Nix\"",
		"Pos": "QB",
		"Team": "DEN",
		"G": "5",
		"W3": "19.3",
		"W4": "6.7",
		"W5": "23.1",
		"W6": "20.7",
		"W7": "14.1",
		"\"FF Pts\"": "84.0",
		"\"FF Pts/G\"": "16.8"
	},
	{
		"Player": "\"Kyler Murray\"",
		"Pos": "QB",
		"Team": "ARI",
		"G": "5",
		"W3": "14.8",
		"W4": "10.0",
		"W5": "24.1",
		"W6": "12.0",
		"W7": "20.2",
		"\"FF Pts\"": "81.0",
		"\"FF Pts/G\"": "16.2"
	},
	{
		"Player": "\"Caleb Williams\"",
		"Pos": "QB",
		"Team": "CHI",
		"G": "4",
		"W3": "17.3",
		"W4": "11.5",
		"W5": "23.6",
		"W6": "28.6",
		"W7": "-",
		"\"FF Pts\"": "81.0",
		"\"FF Pts/G\"": "20.3"
	},
	{
		"Player": "\"Trevor Lawrence\"",
		"Pos": "QB",
		"Team": "JAX",
		"G": "5",
		"W3": "9.4",
		"W4": "14.8",
		"W5": "21.2",
		"W6": "17.1",
		"W7": "15.0",
		"\"FF Pts\"": "77.5",
		"\"FF Pts/G\"": "15.5"
	},
	{
		"Player": "\"Aaron Rodgers\"",
		"Pos": "QB",
		"Team": "NYJ",
		"G": "5",
		"W3": "21.0",
		"W4": "11.6",
		"W5": "11.8",
		"W6": "17.8",
		"W7": "13.0",
		"\"FF Pts\"": "75.2",
		"\"FF Pts/G\"": "15.0"
	},
	{
		"Player": "\"C.J. Stroud\"",
		"Pos": "QB",
		"Team": "HOU",
		"G": "5",
		"W3": "9.8",
		"W4": "23.5",
		"W5": "15.9",
		"W6": "18.4",
		"W7": "5.3",
		"\"FF Pts\"": "73.0",
		"\"FF Pts/G\"": "14.6"
	},
	{
		"Player": "\"Kirk Cousins\"",
		"Pos": "QB",
		"Team": "ATL",
		"G": "5",
		"W3": "11.1",
		"W4": "7.5",
		"W5": "34.4",
		"W6": "12.5",
		"W7": "7.2",
		"\"FF Pts\"": "72.7",
		"\"FF Pts/G\"": "14.5"
	},
	{
		"Player": "\"Jalen Hurts\"",
		"Pos": "QB",
		"Team": "PHI",
		"G": "4",
		"W3": "10.9",
		"W4": "16.3",
		"W5": "-",
		"W6": "21.9",
		"W7": "22.8",
		"\"FF Pts\"": "71.9",
		"\"FF Pts/G\"": "18.0"
	},
	{
		"Player": "\"Daniel Jones\"",
		"Pos": "QB",
		"Team": "NYG",
		"G": "5",
		"W3": "19.4",
		"W4": "9.5",
		"W5": "22.1",
		"W6": "11.8",
		"W7": "6.0",
		"\"FF Pts\"": "68.8",
		"\"FF Pts/G\"": "13.8"
	},
	{
		"Player": "\"Dak Prescott\"",
		"Pos": "QB",
		"Team": "DAL",
		"G": "4",
		"W3": "29.9",
		"W4": "16.7",
		"W5": "16.4",
		"W6": "3.2",
		"W7": "-",
		"\"FF Pts\"": "66.2",
		"\"FF Pts/G\"": "16.6"
	},
	{
		"Player": "\"Sam Darnold\"",
		"Pos": "QB",
		"Team": "MIN",
		"G": "4",
		"W3": "23.2",
		"W4": "20.5",
		"W5": "4.3",
		"W6": "-",
		"W7": "16.3",
		"\"FF Pts\"": "64.3",
		"\"FF Pts/G\"": "16.1"
	},
	{
		"Player": "\"Andy Dalton\"",
		"Pos": "QB",
		"Team": "CAR",
		"G": "5",
		"W3": "24.6",
		"W4": "15.7",
		"W5": "3.7",
		"W6": "14.9",
		"W7": "0.0",
		"\"FF Pts\"": "59.0",
		"\"FF Pts/G\"": "11.8"
	},
	{
		"Player": "\"Joe Flacco\"",
		"Pos": "QB",
		"Team": "IND",
		"G": "3",
		"W3": "-",
		"W4": "15.0",
		"W5": "26.6",
		"W6": "13.7",
		"W7": "-",
		"\"FF Pts\"": "55.2",
		"\"FF Pts/G\"": "18.4"
	},
	{
		"Player": "\"Patrick Mahomes\"",
		"Pos": "QB",
		"Team": "KC",
		"G": "4",
		"W3": "16.4",
		"W4": "13.0",
		"W5": "13.4",
		"W6": "-",
		"W7": "12.1",
		"\"FF Pts\"": "54.9",
		"\"FF Pts/G\"": "13.7"
	},
	{
		"Player": "\"Deshaun Watson\"",
		"Pos": "QB",
		"Team": "CLE",
		"G": "5",
		"W3": "16.4",
		"W4": "12.2",
		"W5": "8.4",
		"W6": "8.4",
		"W7": "5.1",
		"\"FF Pts\"": "50.6",
		"\"FF Pts/G\"": "10.1"
	},
	{
		"Player": "\"Justin Herbert\"",
		"Pos": "QB",
		"Team": "LAC",
		"G": "4",
		"W3": "9.0",
		"W4": "11.2",
		"W5": "-",
		"W6": "13.7",
		"W7": "14.8",
		"\"FF Pts\"": "48.6",
		"\"FF Pts/G\"": "12.2"
	},
	{
		"Player": "\"Drake Maye\"",
		"Pos": "QB",
		"Team": "NE",
		"G": "3",
		"W3": "2.1",
		"W4": "-",
		"W5": "-",
		"W6": "19.5",
		"W7": "20.8",
		"\"FF Pts\"": "42.4",
		"\"FF Pts/G\"": "14.1"
	},
	{
		"Player": "\"Matthew Stafford\"",
		"Pos": "QB",
		"Team": "LAR",
		"G": "4",
		"W3": "12.8",
		"W4": "4.9",
		"W5": "12.4",
		"W6": "-",
		"W7": "4.0",
		"\"FF Pts\"": "34.1",
		"\"FF Pts/G\"": "8.5"
	},
	{
		"Player": "\"Derek Carr\"",
		"Pos": "QB",
		"Team": "NO",
		"G": "3",
		"W3": "8.0",
		"W4": "8.1",
		"W5": "12.6",
		"W6": "-",
		"W7": "-",
		"\"FF Pts\"": "28.6",
		"\"FF Pts/G\"": "9.5"
	},
	{
		"Player": "\"Tyler Huntley\"",
		"Pos": "QB",
		"Team": "MIA",
		"G": "3",
		"W3": "-",
		"W4": "11.8",
		"W5": "6.5",
		"W6": "-",
		"W7": "9.5",
		"\"FF Pts\"": "27.8",
		"\"FF Pts/G\"": "9.3"
	},
	{
		"Player": "\"Malik Willis\"",
		"Pos": "QB",
		"Team": "GB",
		"G": "1",
		"W3": "25.4",
		"W4": "-",
		"W5": "-",
		"W6": "-",
		"W7": "-",
		"\"FF Pts\"": "25.4",
		"\"FF Pts/G\"": "25.4"
	},
	{
		"Player": "\"Gardner Minshew\"",
		"Pos": "QB",
		"Team": "LV",
		"G": "4",
		"W3": "14.0",
		"W4": "5.0",
		"W5": "7.7",
		"W6": "-",
		"W7": "-1.6",
		"\"FF Pts\"": "25.0",
		"\"FF Pts/G\"": "6.3"
	},
	{
		"Player": "\"Russell Wilson\"",
		"Pos": "QB",
		"Team": "PIT",
		"G": "1",
		"W3": "-",
		"W4": "-",
		"W5": "-",
		"W6": "-",
		"W7": "24.9",
		"\"FF Pts\"": "24.9",
		"\"FF Pts/G\"": "24.9"
	},
	{
		"Player": "\"Aidan O'Connell\"",
		"Pos": "QB",
		"Team": "LV",
		"G": "4",
		"W3": "7.3",
		"W4": "-",
		"W5": "1.8",
		"W6": "11.1",
		"W7": "2.1",
		"\"FF Pts\"": "22.2",
		"\"FF Pts/G\"": "5.6"
	},
	{
		"Player": "\"Will Levis\"",
		"Pos": "QB",
		"Team": "TEN",
		"G": "3",
		"W3": "13.6",
		"W4": "-0.5",
		"W5": "-",
		"W6": "7.3",
		"W7": "-",
		"\"FF Pts\"": "20.4",
		"\"FF Pts/G\"": "6.8"
	},
	{
		"Player": "\"Marcus Mariota\"",
		"Pos": "QB",
		"Team": "WAS",
		"G": "2",
		"W3": "-",
		"W4": "-",
		"W5": "0.1",
		"W6": "-",
		"W7": "19.6",
		"\"FF Pts\"": "19.7",
		"\"FF Pts/G\"": "9.9"
	},
	{
		"Player": "\"Anthony Richardson\"",
		"Pos": "QB",
		"Team": "IND",
		"G": "3",
		"W3": "5.1",
		"W4": "5.2",
		"W5": "-",
		"W6": "-",
		"W7": "8.8",
		"\"FF Pts\"": "19.1",
		"\"FF Pts/G\"": "6.4"
	},
	{
		"Player": "\"Spencer Rattler\"",
		"Pos": "QB",
		"Team": "NO",
		"G": "2",
		"W3": "-",
		"W4": "-",
		"W5": "-",
		"W6": "12.4",
		"W7": "6.3",
		"\"FF Pts\"": "18.7",
		"\"FF Pts/G\"": "9.4"
	},
	{
		"Player": "\"Jacoby Brissett\"",
		"Pos": "QB",
		"Team": "NE",
		"G": "3",
		"W3": "3.9",
		"W4": "7.0",
		"W5": "7.4",
		"W6": "-",
		"W7": "-",
		"\"FF Pts\"": "18.3",
		"\"FF Pts/G\"": "6.1"
	},
	{
		"Player": "\"Mason Rudolph\"",
		"Pos": "QB",
		"Team": "TEN",
		"G": "2",
		"W3": "-",
		"W4": "3.4",
		"W5": "-",
		"W6": "-",
		"W7": "9.9",
		"\"FF Pts\"": "13.3",
		"\"FF Pts/G\"": "6.7"
	},
	{
		"Player": "\"Jameis Winston\"",
		"Pos": "QB",
		"Team": "CLE",
		"G": "4",
		"W3": "0.1",
		"W4": "-",
		"W5": "0.3",
		"W6": "0.0",
		"W7": "8.7",
		"\"FF Pts\"": "9.1",
		"\"FF Pts/G\"": "2.3"
	},
	{
		"Player": "\"Jake Haener\"",
		"Pos": "QB",
		"Team": "NO",
		"G": "2",
		"W3": "-",
		"W4": "-",
		"W5": "1.8",
		"W6": "-",
		"W7": "5.5",
		"\"FF Pts\"": "7.3",
		"\"FF Pts/G\"": "3.7"
	},
	{
		"Player": "\"Tim Boyle\"",
		"Pos": "QB",
		"Team": "MIA",
		"G": "2",
		"W3": "3.8",
		"W4": "-",
		"W5": "-",
		"W6": "-",
		"W7": "3.4",
		"\"FF Pts\"": "7.1",
		"\"FF Pts/G\"": "3.6"
	},
	{
		"Player": "\"Skylar Thompson\"",
		"Pos": "QB",
		"Team": "MIA",
		"G": "1",
		"W3": "4.3",
		"W4": "-",
		"W5": "-",
		"W6": "-",
		"W7": "-",
		"\"FF Pts\"": "4.3",
		"\"FF Pts/G\"": "4.3"
	},
	{
		"Player": "\"Dorian Thompson-Robinson\"",
		"Pos": "QB",
		"Team": "CLE",
		"G": "1",
		"W3": "-",
		"W4": "-",
		"W5": "-",
		"W6": "-",
		"W7": "3.7",
		"\"FF Pts\"": "3.7",
		"\"FF Pts/G\"": "3.7"
	},
	{
		"Player": "\"Davis Mills\"",
		"Pos": "QB",
		"Team": "HOU",
		"G": "2",
		"W3": "3.2",
		"W4": "-",
		"W5": "-",
		"W6": "0.0",
		"W7": "-",
		"\"FF Pts\"": "3.2",
		"\"FF Pts/G\"": "1.6"
	},
	{
		"Player": "\"Bryce Young\"",
		"Pos": "QB",
		"Team": "CAR",
		"G": "2",
		"W3": "-",
		"W4": "-",
		"W5": "3.1",
		"W6": "-",
		"W7": "-0.2",
		"\"FF Pts\"": "3.0",
		"\"FF Pts/G\"": "1.5"
	},
	{
		"Player": "\"Drew Lock\"",
		"Pos": "QB",
		"Team": "NYG",
		"G": "1",
		"W3": "-",
		"W4": "-",
		"W5": "-",
		"W6": "-",
		"W7": "1.5",
		"\"FF Pts\"": "1.5",
		"\"FF Pts/G\"": "1.5"
	},
	{
		"Player": "\"Taylor Heinicke\"",
		"Pos": "QB",
		"Team": "LAC",
		"G": "1",
		"W3": "1.0",
		"W4": "-",
		"W5": "-",
		"W6": "-",
		"W7": "-",
		"\"FF Pts\"": "1.0",
		"\"FF Pts/G\"": "1.0"
	},
	{
		"Player": "\"Nick Mullens\"",
		"Pos": "QB",
		"Team": "MIN",
		"G": "2",
		"W3": "0.0",
		"W4": "-",
		"W5": "1.0",
		"W6": "-",
		"W7": "-",
		"\"FF Pts\"": "1.0",
		"\"FF Pts/G\"": "0.5"
	},
	{
		"Player": "\"Kyle Allen\"",
		"Pos": "QB",
		"Team": "PIT",
		"G": "1",
		"W3": "-",
		"W4": "-",
		"W5": "0.8",
		"W6": "-",
		"W7": "-",
		"\"FF Pts\"": "0.8",
		"\"FF Pts/G\"": "0.8"
	},
	{
		"Player": "\"Hendon Hooker\"",
		"Pos": "QB",
		"Team": "DET",
		"G": "1",
		"W3": "-",
		"W4": "-",
		"W5": "-",
		"W6": "0.7",
		"W7": "-",
		"\"FF Pts\"": "0.7",
		"\"FF Pts/G\"": "0.7"
	},
	{
		"Player": "\"Michael Penix Jr.\"",
		"Pos": "QB",
		"Team": "ATL",
		"G": "1",
		"W3": "-",
		"W4": "-",
		"W5": "-",
		"W6": "-",
		"W7": "0.6",
		"\"FF Pts\"": "0.6",
		"\"FF Pts/G\"": "0.6"
	},
	{
		"Player": "\"Clayton Tune\"",
		"Pos": "QB",
		"Team": "ARI",
		"G": "1",
		"W3": "-",
		"W4": "-",
		"W5": "-",
		"W6": "-",
		"W7": "0.2",
		"\"FF Pts\"": "0.2",
		"\"FF Pts/G\"": "0.2"
	},
	{
		"Player": "\"Mitch Trubisky\"",
		"Pos": "QB",
		"Team": "BUF",
		"G": "3",
		"W3": "0.0",
		"W4": "0.1",
		"W5": "0.0",
		"W6": "-",
		"W7": "-",
		"\"FF Pts\"": "0.1",
		"\"FF Pts/G\"": "0.0"
	},
	{
		"Player": "\"Cooper Rush\"",
		"Pos": "QB",
		"Team": "DAL",
		"G": "1",
		"W3": "-",
		"W4": "-",
		"W5": "-",
		"W6": "0.0",
		"W7": "-",
		"\"FF Pts\"": "0.0",
		"\"FF Pts/G\"": "0.0"
	},
	{
		"Player": "\"Josh Johnson\"",
		"Pos": "QB",
		"Team": "BAL",
		"G": "2",
		"W3": "-",
		"W4": "0.0",
		"W5": "-",
		"W6": "-",
		"W7": "0.0",
		"\"FF Pts\"": "0.0",
		"\"FF Pts/G\"": "0.0"
	},

]

module.exports = fantasyPointsBrowser4for4ForQBLastFiveWeeks;