const fantasyPointsBrowser4for4ForQBLastFiveWeeks = [
  {
    Player: '"Baker Mayfield"',
    Pos: 'QB',
    Team: 'TB',
    G: '2',
    W1: '29.7',
    W2: '18.8',
    '"FF Pts"': '48.5',
    '"FF Pts/G"': '24.2',
  },
  {
    Player: '"Derek Carr"',
    Pos: 'QB',
    Team: 'NO',
    G: '2',
    W1: '21.3',
    W2: '21.8',
    '"FF Pts"': '43.1',
    '"FF Pts/G"': '21.6',
  },
  {
    Player: '"Kyler Murray"',
    Pos: 'QB',
    Team: 'ARI',
    G: '2',
    W1: '14.2',
    W2: '28.5',
    '"FF Pts"': '42.7',
    '"FF Pts/G"': '21.4',
  },
  {
    Player: '"Jayden Daniels"',
    Pos: 'QB',
    Team: 'WAS',
    G: '2',
    W1: '28.2',
    W2: '13.4',
    '"FF Pts"': '41.6',
    '"FF Pts/G"': '20.8',
  },
  {
    Player: '"Lamar Jackson"',
    Pos: 'QB',
    Team: 'BAL',
    G: '2',
    W1: '25.1',
    W2: '16.4',
    '"FF Pts"': '41.5',
    '"FF Pts/G"': '20.8',
  },
  {
    Player: '"Josh Allen"',
    Pos: 'QB',
    Team: 'BUF',
    G: '2',
    W1: '31.2',
    W2: '9.8',
    '"FF Pts"': '40.9',
    '"FF Pts/G"': '20.5',
  },
  {
    Player: '"Jalen Hurts"',
    Pos: 'QB',
    Team: 'PHI',
    G: '2',
    W1: '16.4',
    W2: '23.8',
    '"FF Pts"': '40.2',
    '"FF Pts/G"': '20.1',
  },
  {
    Player: '"Anthony Richardson"',
    Pos: 'QB',
    Team: 'IND',
    G: '2',
    W1: '26.1',
    W2: '9.9',
    '"FF Pts"': '35.9',
    '"FF Pts/G"': '18.0',
  },
  {
    Player: '"Geno Smith"',
    Pos: 'QB',
    Team: 'SEA',
    G: '2',
    W1: '17.8',
    W2: '17.9',
    '"FF Pts"': '35.7',
    '"FF Pts/G"': '17.9',
  },
  {
    Player: '"Sam Darnold"',
    Pos: 'QB',
    Team: 'MIN',
    G: '2',
    W1: '14.6',
    W2: '19.9',
    '"FF Pts"': '34.5',
    '"FF Pts/G"': '17.3',
  },
  {
    Player: '"C.J. Stroud"',
    Pos: 'QB',
    Team: 'HOU',
    G: '2',
    W1: '18.7',
    W2: '14.3',
    '"FF Pts"': '33.0',
    '"FF Pts/G"': '16.5',
  },
  {
    Player: '"Patrick Mahomes"',
    Pos: 'QB',
    Team: 'KC',
    G: '2',
    W1: '14.1',
    W2: '12.9',
    '"FF Pts"': '27.1',
    '"FF Pts/G"': '13.5',
  },
  {
    Player: '"Deshaun Watson"',
    Pos: 'QB',
    Team: 'CLE',
    G: '2',
    W1: '10.7',
    W2: '15.4',
    '"FF Pts"': '26.1',
    '"FF Pts/G"': '13.1',
  },
  {
    Player: '"Joe Burrow"',
    Pos: 'QB',
    Team: 'CIN',
    G: '2',
    W1: '8.1',
    W2: '17.2',
    '"FF Pts"': '25.3',
    '"FF Pts/G"': '12.6',
  },
  {
    Player: '"Trevor Lawrence"',
    Pos: 'QB',
    Team: 'JAX',
    G: '2',
    W1: '11.3',
    W2: '13.3',
    '"FF Pts"': '24.6',
    '"FF Pts/G"': '12.3',
  },
  {
    Player: '"Dak Prescott"',
    Pos: 'QB',
    Team: 'DAL',
    G: '2',
    W1: '11.5',
    W2: '12.9',
    '"FF Pts"': '24.4',
    '"FF Pts/G"': '12.2',
  },
  {
    Player: '"Brock Purdy"',
    Pos: 'QB',
    Team: 'SF',
    G: '2',
    W1: '10.3',
    W2: '14.0',
    '"FF Pts"': '24.3',
    '"FF Pts/G"': '12.2',
  },
  {
    Player: '"Tua Tagovailoa"',
    Pos: 'QB',
    Team: 'MIA',
    G: '2',
    W1: '18.6',
    W2: '5.5',
    '"FF Pts"': '24.1',
    '"FF Pts/G"': '12.1',
  },
  {
    Player: '"Kirk Cousins"',
    Pos: 'QB',
    Team: 'ATL',
    G: '2',
    W1: '6.2',
    W2: '17.5',
    '"FF Pts"': '23.7',
    '"FF Pts/G"': '11.9',
  },
  {
    Player: '"Gardner Minshew"',
    Pos: 'QB',
    Team: 'LV',
    G: '2',
    W1: '10.8',
    W2: '12.9',
    '"FF Pts"': '23.7',
    '"FF Pts/G"': '11.9',
  },
  {
    Player: '"Aaron Rodgers"',
    Pos: 'QB',
    Team: 'NYJ',
    G: '2',
    W1: '8.6',
    W2: '15.1',
    '"FF Pts"': '23.7',
    '"FF Pts/G"': '11.9',
  },
  {
    Player: '"Justin Fields"',
    Pos: 'QB',
    Team: 'PIT',
    G: '2',
    W1: '11.9',
    W2: '11.4',
    '"FF Pts"': '23.3',
    '"FF Pts/G"': '11.7',
  },
  {
    Player: '"Daniel Jones"',
    Pos: 'QB',
    Team: 'NYG',
    G: '2',
    W1: '4.9',
    W2: '18.3',
    '"FF Pts"': '23.3',
    '"FF Pts/G"': '11.6',
  },
  {
    Player: '"Justin Herbert"',
    Pos: 'QB',
    Team: 'LAC',
    G: '2',
    W1: '10.4',
    W2: '11.0',
    '"FF Pts"': '21.4',
    '"FF Pts/G"': '10.7',
  },
  {
    Player: '"Matthew Stafford"',
    Pos: 'QB',
    Team: 'LAR',
    G: '2',
    W1: '14.7',
    W2: '6.6',
    '"FF Pts"': '21.3',
    '"FF Pts/G"': '10.7',
  },
  {
    Player: '"Jared Goff"',
    Pos: 'QB',
    Team: 'DET',
    G: '2',
    W1: '11.4',
    W2: '8.8',
    '"FF Pts"': '20.2',
    '"FF Pts/G"': '10.1',
  },
  {
    Player: '"Bo Nix"',
    Pos: 'QB',
    Team: 'DEN',
    G: '2',
    W1: '11.0',
    W2: '8.3',
    '"FF Pts"': '19.4',
    '"FF Pts/G"': '9.7',
  },
  {
    Player: '"Jacoby Brissett"',
    Pos: 'QB',
    Team: 'NE',
    G: '2',
    W1: '8.0',
    W2: '10.6',
    '"FF Pts"': '18.6',
    '"FF Pts/G"': '9.3',
  },
  {
    Player: '"Will Levis"',
    Pos: 'QB',
    Team: 'TEN',
    G: '2',
    W1: '6.7',
    W2: '11.5',
    '"FF Pts"': '18.2',
    '"FF Pts/G"': '9.1',
  },
  {
    Player: '"Jordan Love"',
    Pos: 'QB',
    Team: 'GB',
    G: '1',
    W1: '16.4',
    W2: '-',
    '"FF Pts"': '16.4',
    '"FF Pts/G"': '16.4',
  },
  {
    Player: '"Caleb Williams"',
    Pos: 'QB',
    Team: 'CHI',
    G: '2',
    W1: '7.2',
    W2: '7.4',
    '"FF Pts"': '14.6',
    '"FF Pts/G"': '7.3',
  },
  {
    Player: '"Malik Willis"',
    Pos: 'QB',
    Team: 'GB',
    G: '2',
    W1: '0.0',
    W2: '13.0',
    '"FF Pts"': '13.0',
    '"FF Pts/G"': '6.5',
  },
  {
    Player: '"Bryce Young"',
    Pos: 'QB',
    Team: 'CAR',
    G: '2',
    W1: '9.6',
    W2: '2.0',
    '"FF Pts"': '11.6',
    '"FF Pts/G"': '5.8',
  },
  {
    Player: '"Tyrod Taylor"',
    Pos: 'QB',
    Team: 'NYJ',
    G: '1',
    W1: '6.1',
    W2: '-',
    '"FF Pts"': '6.1',
    '"FF Pts/G"': '6.1',
  },
  {
    Player: '"Skylar Thompson"',
    Pos: 'QB',
    Team: 'MIA',
    G: '1',
    W1: '-',
    W2: '3.6',
    '"FF Pts"': '3.6',
    '"FF Pts/G"': '3.6',
  },
  {
    Player: '"Jameis Winston"',
    Pos: 'QB',
    Team: 'CLE',
    G: '1',
    W1: '-',
    W2: '0.4',
    '"FF Pts"': '0.4',
    '"FF Pts/G"': '0.4',
  },
  {
    Player: '"Cooper Rush"',
    Pos: 'QB',
    Team: 'DAL',
    G: '2',
    W1: '-0.1',
    W2: '0.2',
    '"FF Pts"': '0.1',
    '"FF Pts/G"': '0.1',
  },
];

module.exports = fantasyPointsBrowser4for4ForQBLastFiveWeeks;
