const fantasyPointsBrowser4for4ForQBLastFiveWeeks = [
	{
		"Player": "\"Josh Allen\"",
		"Pos": "QB",
		"Team": "BUF",
		"G": "3",
		"W1": "31.2",
		"W2": "9.8",
		"W3": "30.9",
		"\"PPR Pts\"": "71.9",
		"\"PPR Pts/G\"": "24.0"
	},
	{
		"Player": "\"Jayden Daniels\"",
		"Pos": "QB",
		"Team": "WAS",
		"G": "3",
		"W1": "28.2",
		"W2": "13.4",
		"W3": "28.1",
		"\"PPR Pts\"": "69.7",
		"\"PPR Pts/G\"": "23.2"
	},
	{
		"Player": "\"Lamar Jackson\"",
		"Pos": "QB",
		"Team": "BAL",
		"G": "3",
		"W1": "25.1",
		"W2": "16.4",
		"W3": "26.0",
		"\"PPR Pts\"": "67.5",
		"\"PPR Pts/G\"": "22.5"
	},
	{
		"Player": "\"Sam Darnold\"",
		"Pos": "QB",
		"Team": "MIN",
		"G": "3",
		"W1": "14.6",
		"W2": "19.9",
		"W3": "23.2",
		"\"PPR Pts\"": "57.8",
		"\"PPR Pts/G\"": "19.3"
	},
	{
		"Player": "\"Kyler Murray\"",
		"Pos": "QB",
		"Team": "ARI",
		"G": "3",
		"W1": "14.2",
		"W2": "28.5",
		"W3": "14.8",
		"\"PPR Pts\"": "57.5",
		"\"PPR Pts/G\"": "19.2"
	},
	{
		"Player": "\"Baker Mayfield\"",
		"Pos": "QB",
		"Team": "TB",
		"G": "3",
		"W1": "29.7",
		"W2": "18.8",
		"W3": "8.5",
		"\"PPR Pts\"": "57.0",
		"\"PPR Pts/G\"": "19.0"
	},
	{
		"Player": "\"Dak Prescott\"",
		"Pos": "QB",
		"Team": "DAL",
		"G": "3",
		"W1": "11.5",
		"W2": "12.9",
		"W3": "29.9",
		"\"PPR Pts\"": "54.2",
		"\"PPR Pts/G\"": "18.1"
	},
	{
		"Player": "\"Jalen Hurts\"",
		"Pos": "QB",
		"Team": "PHI",
		"G": "3",
		"W1": "16.4",
		"W2": "23.8",
		"W3": "10.9",
		"\"PPR Pts\"": "51.2",
		"\"PPR Pts/G\"": "17.1"
	},
	{
		"Player": "\"Derek Carr\"",
		"Pos": "QB",
		"Team": "NO",
		"G": "3",
		"W1": "21.3",
		"W2": "21.8",
		"W3": "8.0",
		"\"PPR Pts\"": "51.1",
		"\"PPR Pts/G\"": "17.0"
	},
	{
		"Player": "\"Joe Burrow\"",
		"Pos": "QB",
		"Team": "CIN",
		"G": "3",
		"W1": "8.1",
		"W2": "17.2",
		"W3": "25.4",
		"\"PPR Pts\"": "50.6",
		"\"PPR Pts/G\"": "16.9"
	},
	{
		"Player": "\"Brock Purdy\"",
		"Pos": "QB",
		"Team": "SF",
		"G": "3",
		"W1": "10.3",
		"W2": "14.0",
		"W3": "25.8",
		"\"PPR Pts\"": "50.1",
		"\"PPR Pts/G\"": "16.7"
	},
	{
		"Player": "\"Geno Smith\"",
		"Pos": "QB",
		"Team": "SEA",
		"G": "3",
		"W1": "17.8",
		"W2": "17.9",
		"W3": "11.4",
		"\"PPR Pts\"": "47.1",
		"\"PPR Pts/G\"": "15.7"
	},
	{
		"Player": "\"Aaron Rodgers\"",
		"Pos": "QB",
		"Team": "NYJ",
		"G": "3",
		"W1": "8.6",
		"W2": "15.1",
		"W3": "21.0",
		"\"PPR Pts\"": "44.8",
		"\"PPR Pts/G\"": "14.9"
	},
	{
		"Player": "\"Patrick Mahomes\"",
		"Pos": "QB",
		"Team": "KC",
		"G": "3",
		"W1": "15.1",
		"W2": "12.9",
		"W3": "16.4",
		"\"PPR Pts\"": "44.5",
		"\"PPR Pts/G\"": "14.8"
	},
	{
		"Player": "\"C.J. Stroud\"",
		"Pos": "QB",
		"Team": "HOU",
		"G": "3",
		"W1": "18.7",
		"W2": "14.3",
		"W3": "9.8",
		"\"PPR Pts\"": "42.8",
		"\"PPR Pts/G\"": "14.3"
	},
	{
		"Player": "\"Daniel Jones\"",
		"Pos": "QB",
		"Team": "NYG",
		"G": "3",
		"W1": "4.9",
		"W2": "18.3",
		"W3": "19.4",
		"\"PPR Pts\"": "42.7",
		"\"PPR Pts/G\"": "14.2"
	},
	{
		"Player": "\"Deshaun Watson\"",
		"Pos": "QB",
		"Team": "CLE",
		"G": "3",
		"W1": "10.7",
		"W2": "15.4",
		"W3": "16.4",
		"\"PPR Pts\"": "42.5",
		"\"PPR Pts/G\"": "14.2"
	},
	{
		"Player": "\"Justin Fields\"",
		"Pos": "QB",
		"Team": "PIT",
		"G": "3",
		"W1": "11.9",
		"W2": "11.4",
		"W3": "18.4",
		"\"PPR Pts\"": "41.7",
		"\"PPR Pts/G\"": "13.9"
	},
	{
		"Player": "\"Anthony Richardson\"",
		"Pos": "QB",
		"Team": "IND",
		"G": "3",
		"W1": "26.1",
		"W2": "9.9",
		"W3": "5.1",
		"\"PPR Pts\"": "41.0",
		"\"PPR Pts/G\"": "13.7"
	},
	{
		"Player": "\"Bo Nix\"",
		"Pos": "QB",
		"Team": "DEN",
		"G": "3",
		"W1": "11.0",
		"W2": "8.3",
		"W3": "19.3",
		"\"PPR Pts\"": "38.7",
		"\"PPR Pts/G\"": "12.9"
	},
	{
		"Player": "\"Malik Willis\"",
		"Pos": "QB",
		"Team": "GB",
		"G": "3",
		"W1": "0.0",
		"W2": "13.0",
		"W3": "25.4",
		"\"PPR Pts\"": "38.4",
		"\"PPR Pts/G\"": "12.8"
	},
	{
		"Player": "\"Gardner Minshew\"",
		"Pos": "QB",
		"Team": "LV",
		"G": "3",
		"W1": "10.8",
		"W2": "12.9",
		"W3": "14.0",
		"\"PPR Pts\"": "37.7",
		"\"PPR Pts/G\"": "12.6"
	},
	{
		"Player": "\"Kirk Cousins\"",
		"Pos": "QB",
		"Team": "ATL",
		"G": "3",
		"W1": "6.2",
		"W2": "17.5",
		"W3": "11.1",
		"\"PPR Pts\"": "34.8",
		"\"PPR Pts/G\"": "11.6"
	},
	{
		"Player": "\"Jared Goff\"",
		"Pos": "QB",
		"Team": "DET",
		"G": "3",
		"W1": "11.4",
		"W2": "8.8",
		"W3": "14.6",
		"\"PPR Pts\"": "34.7",
		"\"PPR Pts/G\"": "11.6"
	},
	{
		"Player": "\"Matthew Stafford\"",
		"Pos": "QB",
		"Team": "LAR",
		"G": "3",
		"W1": "14.7",
		"W2": "6.6",
		"W3": "12.8",
		"\"PPR Pts\"": "34.2",
		"\"PPR Pts/G\"": "11.4"
	},
	{
		"Player": "\"Trevor Lawrence\"",
		"Pos": "QB",
		"Team": "JAX",
		"G": "3",
		"W1": "11.3",
		"W2": "13.3",
		"W3": "9.4",
		"\"PPR Pts\"": "34.0",
		"\"PPR Pts/G\"": "11.3"
	},
	{
		"Player": "\"Caleb Williams\"",
		"Pos": "QB",
		"Team": "CHI",
		"G": "3",
		"W1": "7.2",
		"W2": "7.4",
		"W3": "17.3",
		"\"PPR Pts\"": "31.9",
		"\"PPR Pts/G\"": "10.6"
	},
	{
		"Player": "\"Will Levis\"",
		"Pos": "QB",
		"Team": "TEN",
		"G": "3",
		"W1": "6.7",
		"W2": "11.5",
		"W3": "13.6",
		"\"PPR Pts\"": "31.8",
		"\"PPR Pts/G\"": "10.6"
	},
	{
		"Player": "\"Justin Herbert\"",
		"Pos": "QB",
		"Team": "LAC",
		"G": "3",
		"W1": "10.4",
		"W2": "11.0",
		"W3": "9.0",
		"\"PPR Pts\"": "30.4",
		"\"PPR Pts/G\"": "10.1"
	},
	{
		"Player": "\"Andy Dalton\"",
		"Pos": "QB",
		"Team": "CAR",
		"G": "2",
		"W1": "0.0",
		"W2": "-",
		"W3": "24.6",
		"\"PPR Pts\"": "24.6",
		"\"PPR Pts/G\"": "12.3"
	},
	{
		"Player": "\"Tua Tagovailoa\"",
		"Pos": "QB",
		"Team": "MIA",
		"G": "2",
		"W1": "18.6",
		"W2": "5.5",
		"W3": "-",
		"\"PPR Pts\"": "24.1",
		"\"PPR Pts/G\"": "12.1"
	},
	{
		"Player": "\"Jacoby Brissett\"",
		"Pos": "QB",
		"Team": "NE",
		"G": "3",
		"W1": "8.0",
		"W2": "10.6",
		"W3": "3.9",
		"\"PPR Pts\"": "22.5",
		"\"PPR Pts/G\"": "7.5"
	},
	{
		"Player": "\"Jordan Love\"",
		"Pos": "QB",
		"Team": "GB",
		"G": "1",
		"W1": "16.4",
		"W2": "-",
		"W3": "-",
		"\"PPR Pts\"": "16.4",
		"\"PPR Pts/G\"": "16.4"
	},
	{
		"Player": "\"Bryce Young\"",
		"Pos": "QB",
		"Team": "CAR",
		"G": "2",
		"W1": "9.6",
		"W2": "2.0",
		"W3": "-",
		"\"PPR Pts\"": "11.6",
		"\"PPR Pts/G\"": "5.8"
	},
	{
		"Player": "\"Skylar Thompson\"",
		"Pos": "QB",
		"Team": "MIA",
		"G": "2",
		"W1": "-",
		"W2": "3.6",
		"W3": "4.3",
		"\"PPR Pts\"": "7.9",
		"\"PPR Pts/G\"": "3.9"
	},
	{
		"Player": "\"Aidan O'Connell\"",
		"Pos": "QB",
		"Team": "LV",
		"G": "1",
		"W1": "-",
		"W2": "-",
		"W3": "7.3",
		"\"PPR Pts\"": "7.3",
		"\"PPR Pts/G\"": "7.3"
	},
	{
		"Player": "\"Tyrod Taylor\"",
		"Pos": "QB",
		"Team": "NYJ",
		"G": "1",
		"W1": "6.1",
		"W2": "-",
		"W3": "-",
		"\"PPR Pts\"": "6.1",
		"\"PPR Pts/G\"": "6.1"
	},
	{
		"Player": "\"Tim Boyle\"",
		"Pos": "QB",
		"Team": "MIA",
		"G": "1",
		"W1": "-",
		"W2": "-",
		"W3": "3.8",
		"\"PPR Pts\"": "3.8",
		"\"PPR Pts/G\"": "3.8"
	},
	{
		"Player": "\"Davis Mills\"",
		"Pos": "QB",
		"Team": "HOU",
		"G": "1",
		"W1": "-",
		"W2": "-",
		"W3": "3.2",
		"\"PPR Pts\"": "3.2",
		"\"PPR Pts/G\"": "3.2"
	},
	{
		"Player": "\"Drake Maye\"",
		"Pos": "QB",
		"Team": "NE",
		"G": "1",
		"W1": "-",
		"W2": "-",
		"W3": "2.1",
		"\"PPR Pts\"": "2.1",
		"\"PPR Pts/G\"": "2.1"
	},
	{
		"Player": "\"Taylor Heinicke\"",
		"Pos": "QB",
		"Team": "LAC",
		"G": "1",
		"W1": "-",
		"W2": "-",
		"W3": "1.0",
		"\"PPR Pts\"": "1.0",
		"\"PPR Pts/G\"": "1.0"
	},
	{
		"Player": "\"Jameis Winston\"",
		"Pos": "QB",
		"Team": "CLE",
		"G": "2",
		"W1": "-",
		"W2": "0.4",
		"W3": "0.1",
		"\"PPR Pts\"": "0.5",
		"\"PPR Pts/G\"": "0.3"
	},
	{
		"Player": "\"Cooper Rush\"",
		"Pos": "QB",
		"Team": "DAL",
		"G": "2",
		"W1": "-0.1",
		"W2": "0.2",
		"W3": "-",
		"\"PPR Pts\"": "0.1",
		"\"PPR Pts/G\"": "0.1"
	},
	
]

module.exports = fantasyPointsBrowser4for4ForQBLastFiveWeeks;