const qbRushingLastFiveGamesFromWeeklyStatExplorer = [
	{
		"\"Player\"": "\"Aidan O'Connell\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "3",
		"\"Yards\"": "6",
		"\"TD\"": "0",
		"\"YPC\"": "2",
		"\"% Tm Att\"": "\"3%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Bailey Zappe\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "4",
		"\"Yards\"": "16",
		"\"TD\"": "0",
		"\"YPC\"": "4",
		"\"% Tm Att\"": "\"4%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Baker Mayfield\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "15",
		"\"Yards\"": "33",
		"\"TD\"": "0",
		"\"YPC\"": "2.2",
		"\"% Tm Att\"": "\"12%\"",
		"\"FumL\"": "2"
	},
	{
		"\"Player\"": "\"Brett Rypien\"",
		"\"Team\"": "\"LAR\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "3",
		"\"Yards\"": "19",
		"\"TD\"": "0",
		"\"YPC\"": "6.3",
		"\"% Tm Att\"": "\"12%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Brock Purdy\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "9",
		"\"Yards\"": "24",
		"\"TD\"": "0",
		"\"YPC\"": "2.7",
		"\"% Tm Att\"": "\"7%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Bryce Young\"",
		"\"Team\"": "\"CAR\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "13",
		"\"Yards\"": "85",
		"\"TD\"": "0",
		"\"YPC\"": "6.5",
		"\"% Tm Att\"": "\"10%\"",
		"\"FumL\"": "2"
	},
	{
		"\"Player\"": "\"CJ Beathard\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "1",
		"\"Yards\"": "7",
		"\"TD\"": "0",
		"\"YPC\"": "7",
		"\"% Tm Att\"": "\"1%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"CJ Stroud\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "14",
		"\"Yards\"": "70",
		"\"TD\"": "2",
		"\"YPC\"": "5",
		"\"% Tm Att\"": "\"11%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Carson Wentz\"",
		"\"Team\"": "\"LAR\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Clayton Tune\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "6",
		"\"Yards\"": "29",
		"\"TD\"": "1",
		"\"YPC\"": "4.8",
		"\"% Tm Att\"": "\"10%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Cooper Rush\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "5",
		"\"Yards\"": "2",
		"\"TD\"": "0",
		"\"YPC\"": "0.4",
		"\"% Tm Att\"": "\"8%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Dak Prescott\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "18",
		"\"Yards\"": "70",
		"\"TD\"": "1",
		"\"YPC\"": "3.9",
		"\"% Tm Att\"": "\"14%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Daniel Jones\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "2",
		"\"Yards\"": "9",
		"\"TD\"": "0",
		"\"YPC\"": "4.5",
		"\"% Tm Att\"": "\"8%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Davis Mills\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Derek Carr\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "8",
		"\"Yards\"": "19",
		"\"TD\"": "0",
		"\"YPC\"": "2.4",
		"\"% Tm Att\"": "\"8%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Deshaun Watson\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "11",
		"\"Yards\"": "59",
		"\"TD\"": "0",
		"\"YPC\"": "5.4",
		"\"% Tm Att\"": "\"14%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Desmond Ridder\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "13",
		"\"Yards\"": "41",
		"\"TD\"": "1",
		"\"YPC\"": "3.2",
		"\"% Tm Att\"": "\"11%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Dorian Thompson-Robinson\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "8",
		"\"Yards\"": "41",
		"\"TD\"": "0",
		"\"YPC\"": "5.1",
		"\"% Tm Att\"": "\"15%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Drew Lock\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Gardner Minshew\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "13",
		"\"Yards\"": "12",
		"\"TD\"": "1",
		"\"YPC\"": "0.9",
		"\"% Tm Att\"": "\"12%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Geno Smith\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "10",
		"\"Yards\"": "43",
		"\"TD\"": "1",
		"\"YPC\"": "4.3",
		"\"% Tm Att\"": "\"10%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Jacoby Brissett\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Jake Browning\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "9",
		"\"Yards\"": "71",
		"\"TD\"": "1",
		"\"YPC\"": "7.9",
		"\"% Tm Att\"": "\"14%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Jalen Hurts\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "43",
		"\"Yards\"": "150",
		"\"TD\"": "6",
		"\"YPC\"": "3.5",
		"\"% Tm Att\"": "\"39%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Jameis Winston\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Jared Goff\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "10",
		"\"Yards\"": "8",
		"\"TD\"": "0",
		"\"YPC\"": "0.8",
		"\"% Tm Att\"": "\"9%\"",
		"\"FumL\"": "3"
	},
	{
		"\"Player\"": "\"Jaren Hall\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "2",
		"\"Yards\"": "11",
		"\"TD\"": "0",
		"\"YPC\"": "5.5",
		"\"% Tm Att\"": "\"6%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Joe Burrow\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "11",
		"\"Yards\"": "31",
		"\"TD\"": "0",
		"\"YPC\"": "2.8",
		"\"% Tm Att\"": "\"18%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Joe Flacco\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Jordan Love\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "14",
		"\"Yards\"": "67",
		"\"TD\"": "0",
		"\"YPC\"": "4.8",
		"\"% Tm Att\"": "\"10%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Josh Allen\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "26",
		"\"Yards\"": "153",
		"\"TD\"": "4",
		"\"YPC\"": "5.9",
		"\"% Tm Att\"": "\"22%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Joshua Dobbs\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "23",
		"\"Yards\"": "118",
		"\"TD\"": "3",
		"\"YPC\"": "5.1",
		"\"% Tm Att\"": "\"20%\"",
		"\"FumL\"": "3"
	},
	{
		"\"Player\"": "\"Justin Fields\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "30",
		"\"Yards\"": "163",
		"\"TD\"": "0",
		"\"YPC\"": "5.4",
		"\"% Tm Att\"": "\"39%\"",
		"\"FumL\"": "3"
	},
	{
		"\"Player\"": "\"Justin Herbert\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "23",
		"\"Yards\"": "147",
		"\"TD\"": "0",
		"\"YPC\"": "6.4",
		"\"% Tm Att\"": "\"20%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Kenny Pickett\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "17",
		"\"Yards\"": "32",
		"\"TD\"": "0",
		"\"YPC\"": "1.9",
		"\"% Tm Att\"": "\"11%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Kyle Allen\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "2",
		"\"Yards\"": "-2",
		"\"TD\"": "0",
		"\"YPC\"": "-1",
		"\"% Tm Att\"": "\"5%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Kyle Trask\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "1",
		"\"Yards\"": "-1",
		"\"TD\"": "0",
		"\"YPC\"": "-1",
		"\"% Tm Att\"": "\"2%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Kyler Murray\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "22",
		"\"Yards\"": "100",
		"\"TD\"": "3",
		"\"YPC\"": "4.5",
		"\"% Tm Att\"": "\"22%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Lamar Jackson\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "38",
		"\"Yards\"": "194",
		"\"TD\"": "0",
		"\"YPC\"": "5.1",
		"\"% Tm Att\"": "\"29%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Mac Jones\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "6",
		"\"Yards\"": "28",
		"\"TD\"": "0",
		"\"YPC\"": "4.7",
		"\"% Tm Att\"": "\"7%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Marcus Mariota\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "2",
		"\"Yards\"": "6",
		"\"TD\"": "0",
		"\"YPC\"": "3",
		"\"% Tm Att\"": "\"11%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Matthew Stafford\"",
		"\"Team\"": "\"LAR\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "4",
		"\"Yards\"": "1",
		"\"TD\"": "0",
		"\"YPC\"": "0.2",
		"\"% Tm Att\"": "\"5%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Mike White\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "1",
		"\"Yards\"": "-2",
		"\"TD\"": "0",
		"\"YPC\"": "-2",
		"\"% Tm Att\"": "\"1%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Mitch Trubisky\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "3",
		"\"Yards\"": "5",
		"\"TD\"": "0",
		"\"YPC\"": "1.7",
		"\"% Tm Att\"": "\"10%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"PJ Walker\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "1",
		"\"Yards\"": "-1",
		"\"TD\"": "0",
		"\"YPC\"": "-1",
		"\"% Tm Att\"": "\"1%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Patrick Mahomes\"",
		"\"Team\"": "\"KC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "21",
		"\"Yards\"": "97",
		"\"TD\"": "0",
		"\"YPC\"": "4.6",
		"\"% Tm Att\"": "\"21%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Russell Wilson\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "32",
		"\"Yards\"": "109",
		"\"TD\"": "2",
		"\"YPC\"": "3.4",
		"\"% Tm Att\"": "\"26%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Sam Darnold\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "4",
		"\"Yards\"": "-4",
		"\"TD\"": "0",
		"\"YPC\"": "-1",
		"\"% Tm Att\"": "\"7%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Sam Howell\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "16",
		"\"Yards\"": "113",
		"\"TD\"": "4",
		"\"YPC\"": "7.1",
		"\"% Tm Att\"": "\"13%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Taylor Heinicke\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "7",
		"\"Yards\"": "54",
		"\"TD\"": "0",
		"\"YPC\"": "7.7",
		"\"% Tm Att\"": "\"10%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Tim Boyle\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "4",
		"\"Yards\"": "5",
		"\"TD\"": "0",
		"\"YPC\"": "1.2",
		"\"% Tm Att\"": "\"8%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Tommy DeVito\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "17",
		"\"Yards\"": "71",
		"\"TD\"": "0",
		"\"YPC\"": "4.2",
		"\"% Tm Att\"": "\"20%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Trevor Lawrence\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "14",
		"\"Yards\"": "32",
		"\"TD\"": "4",
		"\"YPC\"": "2.3",
		"\"% Tm Att\"": "\"13%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Trevor Siemian\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "1",
		"\"Yards\"": "8",
		"\"TD\"": "0",
		"\"YPC\"": "8",
		"\"% Tm Att\"": "\"4%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Tua Tagovailoa\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "6",
		"\"Yards\"": "14",
		"\"TD\"": "0",
		"\"YPC\"": "2.3",
		"\"% Tm Att\"": "\"5%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Tyler Huntley\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "4",
		"\"Yards\"": "8",
		"\"TD\"": "0",
		"\"YPC\"": "2",
		"\"% Tm Att\"": "\"10%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Tyson Bagent\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "13",
		"\"Yards\"": "77",
		"\"TD\"": "0",
		"\"YPC\"": "5.9",
		"\"% Tm Att\"": "\"19%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Will Levis\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "10",
		"\"Yards\"": "6",
		"\"TD\"": "0",
		"\"YPC\"": "0.6",
		"\"% Tm Att\"": "\"8%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Zach Wilson\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "10",
		"\"Yards\"": "76",
		"\"TD\"": "0",
		"\"YPC\"": "7.6",
		"\"% Tm Att\"": "\"17%\"",
		"\"FumL\"": "2"
	},
	
]

module.exports = qbRushingLastFiveGamesFromWeeklyStatExplorer;