const qbRushingLastFiveGamesFromWeeklyStatExplorer = [
	{
		"\"Player\"": "\"AJ McCarron\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Aidan O'Connell\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "2",
		"\"Yards\"": "5",
		"\"TD\"": "0",
		"\"YPC\"": "2.5",
		"\"% Tm Att\"": "\"2%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Bailey Zappe\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "8",
		"\"Yards\"": "31",
		"\"TD\"": "0",
		"\"YPC\"": "3.9",
		"\"% Tm Att\"": "\"8%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Baker Mayfield\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "13",
		"\"Yards\"": "18",
		"\"TD\"": "1",
		"\"YPC\"": "1.4",
		"\"% Tm Att\"": "\"10%\"",
		"\"FumL\"": "3"
	},
	{
		"\"Player\"": "\"Brock Purdy\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "11",
		"\"Yards\"": "31",
		"\"TD\"": "0",
		"\"YPC\"": "2.8",
		"\"% Tm Att\"": "\"8%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Bryce Young\"",
		"\"Team\"": "\"CAR\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "12",
		"\"Yards\"": "75",
		"\"TD\"": "0",
		"\"YPC\"": "6.2",
		"\"% Tm Att\"": "\"7%\"",
		"\"FumL\"": "3"
	},
	{
		"\"Player\"": "\"CJ Beathard\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "1",
		"\"Yards\"": "7",
		"\"TD\"": "0",
		"\"YPC\"": "7",
		"\"% Tm Att\"": "\"2%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"CJ Stroud\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "12",
		"\"Yards\"": "52",
		"\"TD\"": "1",
		"\"YPC\"": "4.3",
		"\"% Tm Att\"": "\"13%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Carson Wentz\"",
		"\"Team\"": "\"LAR\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Case Keenum\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "2",
		"\"Yards\"": "1",
		"\"TD\"": "0",
		"\"YPC\"": "0.5",
		"\"% Tm Att\"": "\"6%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Clayton Tune\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "1",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "0",
		"\"% Tm Att\"": "\"2%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Cooper Rush\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "3",
		"\"Yards\"": "-3",
		"\"TD\"": "0",
		"\"YPC\"": "-1",
		"\"% Tm Att\"": "\"11%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Dak Prescott\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "17",
		"\"Yards\"": "77",
		"\"TD\"": "0",
		"\"YPC\"": "4.5",
		"\"% Tm Att\"": "\"13%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Davis Mills\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Derek Carr\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "7",
		"\"Yards\"": "2",
		"\"TD\"": "0",
		"\"YPC\"": "0.3",
		"\"% Tm Att\"": "\"6%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Desmond Ridder\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "19",
		"\"Yards\"": "43",
		"\"TD\"": "1",
		"\"YPC\"": "2.3",
		"\"% Tm Att\"": "\"14%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Dorian Thompson-Robinson\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "9",
		"\"Yards\"": "46",
		"\"TD\"": "0",
		"\"YPC\"": "5.1",
		"\"% Tm Att\"": "\"9%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Drew Lock\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "3",
		"\"Yards\"": "2",
		"\"TD\"": "0",
		"\"YPC\"": "0.7",
		"\"% Tm Att\"": "\"5%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Easton Stick\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "2",
		"\"Yards\"": "11",
		"\"TD\"": "0",
		"\"YPC\"": "5.5",
		"\"% Tm Att\"": "\"4%\"",
		"\"FumL\"": "3"
	},
	{
		"\"Player\"": "\"Gardner Minshew\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "10",
		"\"Yards\"": "13",
		"\"TD\"": "1",
		"\"YPC\"": "1.3",
		"\"% Tm Att\"": "\"10%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Geno Smith\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "7",
		"\"Yards\"": "26",
		"\"TD\"": "1",
		"\"YPC\"": "3.7",
		"\"% Tm Att\"": "\"11%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Jacoby Brissett\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "2",
		"\"Yards\"": "9",
		"\"TD\"": "0",
		"\"YPC\"": "4.5",
		"\"% Tm Att\"": "\"4%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Jake Browning\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "16",
		"\"Yards\"": "78",
		"\"TD\"": "2",
		"\"YPC\"": "4.9",
		"\"% Tm Att\"": "\"13%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Jalen Hurts\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "51",
		"\"Yards\"": "226",
		"\"TD\"": "7",
		"\"YPC\"": "4.4",
		"\"% Tm Att\"": "\"37%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Jameis Winston\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "2",
		"\"Yards\"": "-2",
		"\"TD\"": "0",
		"\"YPC\"": "-1",
		"\"% Tm Att\"": "\"3%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Jared Goff\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "8",
		"\"Yards\"": "10",
		"\"TD\"": "0",
		"\"YPC\"": "1.2",
		"\"% Tm Att\"": "\"6%\"",
		"\"FumL\"": "3"
	},
	{
		"\"Player\"": "\"Jarrett Stidham\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Joe Burrow\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "1",
		"\"Yards\"": "7",
		"\"TD\"": "0",
		"\"YPC\"": "7",
		"\"% Tm Att\"": "\"4%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Joe Flacco\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "5",
		"\"Yards\"": "-2",
		"\"TD\"": "0",
		"\"YPC\"": "-0.4",
		"\"% Tm Att\"": "\"7%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Jordan Love\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "12",
		"\"Yards\"": "52",
		"\"TD\"": "0",
		"\"YPC\"": "4.3",
		"\"% Tm Att\"": "\"10%\"",
		"\"FumL\"": "2"
	},
	{
		"\"Player\"": "\"Josh Allen\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "32",
		"\"Yards\"": "152",
		"\"TD\"": "4",
		"\"YPC\"": "4.8",
		"\"% Tm Att\"": "\"21%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Joshua Dobbs\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "15",
		"\"Yards\"": "53",
		"\"TD\"": "1",
		"\"YPC\"": "3.5",
		"\"% Tm Att\"": "\"18%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Justin Fields\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "48",
		"\"Yards\"": "232",
		"\"TD\"": "1",
		"\"YPC\"": "4.8",
		"\"% Tm Att\"": "\"36%\"",
		"\"FumL\"": "3"
	},
	{
		"\"Player\"": "\"Justin Herbert\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "16",
		"\"Yards\"": "115",
		"\"TD\"": "0",
		"\"YPC\"": "7.2",
		"\"% Tm Att\"": "\"19%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Kenny Pickett\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "12",
		"\"Yards\"": "17",
		"\"TD\"": "0",
		"\"YPC\"": "1.4",
		"\"% Tm Att\"": "\"13%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Kyle Allen\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "4",
		"\"Yards\"": "-4",
		"\"TD\"": "0",
		"\"YPC\"": "-1",
		"\"% Tm Att\"": "\"5%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Kyle Trask\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Kyler Murray\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "22",
		"\"Yards\"": "116",
		"\"TD\"": "2",
		"\"YPC\"": "5.3",
		"\"% Tm Att\"": "\"21%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Lamar Jackson\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "43",
		"\"Yards\"": "260",
		"\"TD\"": "0",
		"\"YPC\"": "6",
		"\"% Tm Att\"": "\"32%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Mac Jones\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Marcus Mariota\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "2",
		"\"Yards\"": "6",
		"\"TD\"": "0",
		"\"YPC\"": "3",
		"\"% Tm Att\"": "\"5%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Mason Rudolph\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Matthew Stafford\"",
		"\"Team\"": "\"LAR\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "6",
		"\"Yards\"": "2",
		"\"TD\"": "0",
		"\"YPC\"": "0.3",
		"\"% Tm Att\"": "\"4%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Mike White\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "3",
		"\"Yards\"": "-4",
		"\"TD\"": "0",
		"\"YPC\"": "-1.3",
		"\"% Tm Att\"": "\"3%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Mitch Trubisky\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "13",
		"\"Yards\"": "36",
		"\"TD\"": "2",
		"\"YPC\"": "2.8",
		"\"% Tm Att\"": "\"16%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Nick Mullens\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "6",
		"\"Yards\"": "10",
		"\"TD\"": "0",
		"\"YPC\"": "1.7",
		"\"% Tm Att\"": "\"10%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"PJ Walker\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "1",
		"\"Yards\"": "-1",
		"\"TD\"": "0",
		"\"YPC\"": "-1",
		"\"% Tm Att\"": "\"4%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Patrick Mahomes\"",
		"\"Team\"": "\"KC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "19",
		"\"Yards\"": "76",
		"\"TD\"": "0",
		"\"YPC\"": "4",
		"\"% Tm Att\"": "\"16%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Russell Wilson\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "36",
		"\"Yards\"": "90",
		"\"TD\"": "3",
		"\"YPC\"": "2.5",
		"\"% Tm Att\"": "\"26%\"",
		"\"FumL\"": "2"
	},
	{
		"\"Player\"": "\"Sam Darnold\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "3",
		"\"Yards\"": "-3",
		"\"TD\"": "0",
		"\"YPC\"": "-1",
		"\"% Tm Att\"": "\"6%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Sam Ehlinger\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Sam Howell\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "12",
		"\"Yards\"": "91",
		"\"TD\"": "4",
		"\"YPC\"": "7.6",
		"\"% Tm Att\"": "\"12%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Tim Boyle\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "4",
		"\"Yards\"": "5",
		"\"TD\"": "0",
		"\"YPC\"": "1.2",
		"\"% Tm Att\"": "\"8%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Tommy DeVito\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "20",
		"\"Yards\"": "120",
		"\"TD\"": "0",
		"\"YPC\"": "6",
		"\"% Tm Att\"": "\"23%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Trevor Lawrence\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "19",
		"\"Yards\"": "77",
		"\"TD\"": "4",
		"\"YPC\"": "4.1",
		"\"% Tm Att\"": "\"15%\"",
		"\"FumL\"": "2"
	},
	{
		"\"Player\"": "\"Trevor Siemian\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "1",
		"\"Yards\"": "8",
		"\"TD\"": "0",
		"\"YPC\"": "8",
		"\"% Tm Att\"": "\"3%\"",
		"\"FumL\"": "2"
	},
	{
		"\"Player\"": "\"Tua Tagovailoa\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "7",
		"\"Yards\"": "22",
		"\"TD\"": "0",
		"\"YPC\"": "3.1",
		"\"% Tm Att\"": "\"4%\"",
		"\"FumL\"": "2"
	},
	{
		"\"Player\"": "\"Tyrod Taylor\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Will Levis\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Att\"": "17",
		"\"Yards\"": "44",
		"\"TD\"": "1",
		"\"YPC\"": "2.6",
		"\"% Tm Att\"": "\"12%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Zach Wilson\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "7",
		"\"Yards\"": "27",
		"\"TD\"": "0",
		"\"YPC\"": "3.9",
		"\"% Tm Att\"": "\"13%\"",
		"\"FumL\"": "2"
	},
	
]

module.exports = qbRushingLastFiveGamesFromWeeklyStatExplorer;