const qbRushingLastFiveGamesFromWeeklyStatExplorer = [
	{
		"\"Player\"": "\"Aaron Rodgers\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "11",
		"\"Yards\"": "44",
		"\"TD\"": "0",
		"\"YPC\"": "4",
		"\"% Tm Att\"": "\"11%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Aidan O'Connell\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Andy Dalton\"",
		"\"Team\"": "\"CAR\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "5",
		"\"Yards\"": "7",
		"\"TD\"": "0",
		"\"YPC\"": "1.4",
		"\"% Tm Att\"": "\"6%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Anthony Richardson\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "21",
		"\"Yards\"": "141",
		"\"TD\"": "1",
		"\"YPC\"": "6.7",
		"\"% Tm Att\"": "\"20%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Baker Mayfield\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "12",
		"\"Yards\"": "65",
		"\"TD\"": "2",
		"\"YPC\"": "5.4",
		"\"% Tm Att\"": "\"13%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Bo Nix\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "23",
		"\"Yards\"": "110",
		"\"TD\"": "2",
		"\"YPC\"": "4.8",
		"\"% Tm Att\"": "\"22%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Brandon Allen\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "1",
		"\"Yards\"": "-1",
		"\"TD\"": "0",
		"\"YPC\"": "-1",
		"\"% Tm Att\"": "\"3%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Brock Purdy\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "18",
		"\"Yards\"": "75",
		"\"TD\"": "0",
		"\"YPC\"": "4.2",
		"\"% Tm Att\"": "\"14%\"",
		"\"FumL\"": "2"
	},
	{
		"\"Player\"": "\"Bryce Young\"",
		"\"Team\"": "\"CAR\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "5",
		"\"Yards\"": "18",
		"\"TD\"": "1",
		"\"YPC\"": "3.6",
		"\"% Tm Att\"": "\"13%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"CJ Stroud\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "11",
		"\"Yards\"": "41",
		"\"TD\"": "0",
		"\"YPC\"": "3.7",
		"\"% Tm Att\"": "\"11%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Caleb Williams\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "16",
		"\"Yards\"": "79",
		"\"TD\"": "0",
		"\"YPC\"": "4.9",
		"\"% Tm Att\"": "\"16%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Clayton Tune\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "1",
		"\"Yards\"": "-6",
		"\"TD\"": "0",
		"\"YPC\"": "-6",
		"\"% Tm Att\"": "\"2%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Cooper Rush\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "1",
		"\"Yards\"": "-1",
		"\"TD\"": "0",
		"\"YPC\"": "-1",
		"\"% Tm Att\"": "\"2%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Dak Prescott\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "7",
		"\"Yards\"": "21",
		"\"TD\"": "1",
		"\"YPC\"": "3",
		"\"% Tm Att\"": "\"8%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Daniel Jones\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "23",
		"\"Yards\"": "70",
		"\"TD\"": "0",
		"\"YPC\"": "3",
		"\"% Tm Att\"": "\"23%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Davis Mills\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Derek Carr\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "8",
		"\"Yards\"": "22",
		"\"TD\"": "1",
		"\"YPC\"": "2.8",
		"\"% Tm Att\"": "\"6%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Deshaun Watson\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "22",
		"\"Yards\"": "117",
		"\"TD\"": "1",
		"\"YPC\"": "5.3",
		"\"% Tm Att\"": "\"25%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Drake Maye\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "2",
		"\"Yards\"": "12",
		"\"TD\"": "0",
		"\"YPC\"": "6",
		"\"% Tm Att\"": "\"13%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Gardner Minshew\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "9",
		"\"Yards\"": "16",
		"\"TD\"": "0",
		"\"YPC\"": "1.8",
		"\"% Tm Att\"": "\"11%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Geno Smith\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "11",
		"\"Yards\"": "36",
		"\"TD\"": "1",
		"\"YPC\"": "3.3",
		"\"% Tm Att\"": "\"15%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Jacoby Brissett\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "11",
		"\"Yards\"": "41",
		"\"TD\"": "0",
		"\"YPC\"": "3.7",
		"\"% Tm Att\"": "\"10%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Jake Haener\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "3",
		"\"Yards\"": "-3",
		"\"TD\"": "0",
		"\"YPC\"": "-1",
		"\"% Tm Att\"": "\"4%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Jalen Hurts\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "42",
		"\"Yards\"": "163",
		"\"TD\"": "2",
		"\"YPC\"": "3.9",
		"\"% Tm Att\"": "\"35%\"",
		"\"FumL\"": "2"
	},
	{
		"\"Player\"": "\"Jameis Winston\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "4",
		"\"Yards\"": "5",
		"\"TD\"": "0",
		"\"YPC\"": "1.2",
		"\"% Tm Att\"": "\"9%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Jared Goff\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "6",
		"\"Yards\"": "18",
		"\"TD\"": "0",
		"\"YPC\"": "3",
		"\"% Tm Att\"": "\"6%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Jayden Daniels\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "45",
		"\"Yards\"": "216",
		"\"TD\"": "4",
		"\"YPC\"": "4.8",
		"\"% Tm Att\"": "\"34%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Jeff Driskel\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Joe Burrow\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "12",
		"\"Yards\"": "38",
		"\"TD\"": "0",
		"\"YPC\"": "3.2",
		"\"% Tm Att\"": "\"13%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Joe Flacco\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "2",
		"\"Yards\"": "3",
		"\"TD\"": "0",
		"\"YPC\"": "1.5",
		"\"% Tm Att\"": "\"6%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Jordan Love\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "1",
		"\"Yards\"": "6",
		"\"TD\"": "0",
		"\"YPC\"": "6",
		"\"% Tm Att\"": "\"2%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Josh Allen\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "22",
		"\"Yards\"": "106",
		"\"TD\"": "2",
		"\"YPC\"": "4.8",
		"\"% Tm Att\"": "\"20%\"",
		"\"FumL\"": "2"
	},
	{
		"\"Player\"": "\"Josh Johnson\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Justin Fields\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "38",
		"\"Yards\"": "145",
		"\"TD\"": "3",
		"\"YPC\"": "3.8",
		"\"% Tm Att\"": "\"28%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Justin Herbert\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "14",
		"\"Yards\"": "24",
		"\"TD\"": "0",
		"\"YPC\"": "1.7",
		"\"% Tm Att\"": "\"12%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Kirk Cousins\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "6",
		"\"Yards\"": "-2",
		"\"TD\"": "0",
		"\"YPC\"": "-0.3",
		"\"% Tm Att\"": "\"7%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Kyle Trask\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "2",
		"\"Yards\"": "-2",
		"\"TD\"": "0",
		"\"YPC\"": "-1",
		"\"% Tm Att\"": "\"7%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Kyler Murray\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "16",
		"\"Yards\"": "164",
		"\"TD\"": "0",
		"\"YPC\"": "10.2",
		"\"% Tm Att\"": "\"14%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Lamar Jackson\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "41",
		"\"Yards\"": "308",
		"\"TD\"": "2",
		"\"YPC\"": "7.5",
		"\"% Tm Att\"": "\"30%\"",
		"\"FumL\"": "2"
	},
	{
		"\"Player\"": "\"Mac Jones\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Malik Willis\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "12",
		"\"Yards\"": "114",
		"\"TD\"": "1",
		"\"YPC\"": "9.5",
		"\"% Tm Att\"": "\"11%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Matthew Stafford\"",
		"\"Team\"": "\"LAR\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "1",
		"\"Yards\"": "-1",
		"\"TD\"": "0",
		"\"YPC\"": "-1",
		"\"% Tm Att\"": "\"1%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Mitch Trubisky\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "3",
		"\"Yards\"": "-3",
		"\"TD\"": "0",
		"\"YPC\"": "-1",
		"\"% Tm Att\"": "\"4%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Nick Mullens\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "1",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "0",
		"\"% Tm Att\"": "\"4%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Patrick Mahomes\"",
		"\"Team\"": "\"KC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "17",
		"\"Yards\"": "61",
		"\"TD\"": "0",
		"\"YPC\"": "3.6",
		"\"% Tm Att\"": "\"15%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Sam Darnold\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "14",
		"\"Yards\"": "50",
		"\"TD\"": "0",
		"\"YPC\"": "3.6",
		"\"% Tm Att\"": "\"13%\"",
		"\"FumL\"": "1"
	},
	{
		"\"Player\"": "\"Skylar Thompson\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "1",
		"\"Yards\"": "4",
		"\"TD\"": "0",
		"\"YPC\"": "4",
		"\"% Tm Att\"": "\"2%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Taylor Heinicke\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPC\"": "NA",
		"\"% Tm Att\"": "\"0%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Tim Boyle\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "1",
		"\"Yards\"": "6",
		"\"TD\"": "0",
		"\"YPC\"": "6",
		"\"% Tm Att\"": "\"6%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Trevor Lawrence\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Att\"": "8",
		"\"Yards\"": "61",
		"\"TD\"": "0",
		"\"YPC\"": "7.6",
		"\"% Tm Att\"": "\"9%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Tua Tagovailoa\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Att\"": "3",
		"\"Yards\"": "28",
		"\"TD\"": "0",
		"\"YPC\"": "9.3",
		"\"% Tm Att\"": "\"5%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Tyrod Taylor\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Att\"": "1",
		"\"Yards\"": "7",
		"\"TD\"": "0",
		"\"YPC\"": "7",
		"\"% Tm Att\"": "\"5%\"",
		"\"FumL\"": "0"
	},
	{
		"\"Player\"": "\"Will Levis\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Att\"": "11",
		"\"Yards\"": "86",
		"\"TD\"": "0",
		"\"YPC\"": "7.8",
		"\"% Tm Att\"": "\"17%\"",
		"\"FumL\"": "3"
	},
	
]

module.exports = qbRushingLastFiveGamesFromWeeklyStatExplorer;