const QBWeeklyStatExplorerLastFiveWeeksCategoryPassing = [
  {
    '"Player"': '"Aaron Rodgers"',
    '"Team"': '"GB"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1157',
    '"Att"': '167',
    '"Comp"': '114',
    '"Comp%"': '"68%"',
    '"TD"': '8',
    '"Int"': '3',
    '"Yd/Att"': '6.9',
    '"Rating"': '96.3',
    '"Total"': '1149',
    '"Completed"': '437',
    '"Conv%"': '"38%"',
    '"AirYds/Att"': '6.9',
  },
  {
    '"Player"': '"Andy Dalton"',
    '"Team"': '"NO"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Yards"': '423',
    '"Att"': '51',
    '"Comp"': '36',
    '"Comp%"': '"71%"',
    '"TD"': '2',
    '"Int"': '1',
    '"Yd/Att"': '8.3',
    '"Rating"': '100.4',
    '"Total"': '490',
    '"Completed"': '256',
    '"Conv%"': '"52%"',
    '"AirYds/Att"': '9.6',
  },
  {
    '"Player"': '"Bailey Zappe"',
    '"Team"': '"NE"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Yards"': '287',
    '"Att"': '36',
    '"Comp"': '27',
    '"Comp%"': '"75%"',
    '"TD"': '2',
    '"Int"': '1',
    '"Yd/Att"': '8',
    '"Rating"': '104.7',
    '"Total"': '270',
    '"Completed"': '136',
    '"Conv%"': '"50%"',
    '"AirYds/Att"': '7.5',
  },
  {
    '"Player"': '"Baker Mayfield"',
    '"Team"': '"CAR"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '962',
    '"Att"': '152',
    '"Comp"': '84',
    '"Comp%"': '"55%"',
    '"TD"': '4',
    '"Int"': '4',
    '"Yd/Att"': '6.3',
    '"Rating"': '72.3',
    '"Total"': '1031',
    '"Completed"': '391',
    '"Conv%"': '"38%"',
    '"AirYds/Att"': '6.8',
  },
  {
    '"Player"': '"Brian Hoyer"',
    '"Team"': '"NE"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Yards"': '37',
    '"Att"': '6',
    '"Comp"': '5',
    '"Comp%"': '"83%"',
    '"TD"': '0',
    '"Int"': '0',
    '"Yd/Att"': '6.2',
    '"Rating"': '92.4',
    '"Total"': '28',
    '"Completed"': '15',
    '"Conv%"': '"54%"',
    '"AirYds/Att"': '4.7',
  },
  {
    '"Player"': '"Brock Purdy"',
    '"Team"': '"SF"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Yards"': '0',
    '"Att"': '0',
    '"Comp"': '0',
    '"Comp%"': 'NA',
    '"TD"': '0',
    '"Int"': '0',
    '"Yd/Att"': 'NA',
    '"Rating"': 'NA',
    '"Total"': '0',
    '"Completed"': '0',
    '"Conv%"': 'NA',
    '"AirYds/Att"': 'NA',
  },
  {
    '"Player"': '"CJ Beathard"',
    '"Team"': '"JAC"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Yards"': '0',
    '"Att"': '0',
    '"Comp"': '0',
    '"Comp%"': 'NA',
    '"TD"': '0',
    '"Int"': '0',
    '"Yd/Att"': 'NA',
    '"Rating"': 'NA',
    '"Total"': '0',
    '"Completed"': '0',
    '"Conv%"': 'NA',
    '"AirYds/Att"': 'NA',
  },
  {
    '"Player"': '"Carson Wentz"',
    '"Team"': '"WAS"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1390',
    '"Att"': '207',
    '"Comp"': '132',
    '"Comp%"': '"64%"',
    '"TD"': '10',
    '"Int"': '6',
    '"Yd/Att"': '6.7',
    '"Rating"': '87.2',
    '"Total"': '1692',
    '"Completed"': '752',
    '"Conv%"': '"44%"',
    '"AirYds/Att"': '8.2',
  },
  {
    '"Player"': '"Case Keenum"',
    '"Team"': '"BUF"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Yards"': '8',
    '"Att"': '7',
    '"Comp"': '2',
    '"Comp%"': '"29%"',
    '"TD"': '0',
    '"Int"': '0',
    '"Yd/Att"': '1.1',
    '"Rating"': '39.6',
    '"Total"': '57',
    '"Completed"': '3',
    '"Conv%"': '"5%"',
    '"AirYds/Att"': '8.1',
  },
  {
    '"Player"': '"Chad Henne"',
    '"Team"': '"KC"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Yards"': '0',
    '"Att"': '0',
    '"Comp"': '0',
    '"Comp%"': 'NA',
    '"TD"': '0',
    '"Int"': '0',
    '"Yd/Att"': 'NA',
    '"Rating"': 'NA',
    '"Total"': '0',
    '"Completed"': '0',
    '"Conv%"': 'NA',
    '"AirYds/Att"': 'NA',
  },
  {
    '"Player"': '"Chase Daniel"',
    '"Team"': '"LAC"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Yards"': '0',
    '"Att"': '0',
    '"Comp"': '0',
    '"Comp%"': 'NA',
    '"TD"': '0',
    '"Int"': '0',
    '"Yd/Att"': 'NA',
    '"Rating"': 'NA',
    '"Total"': '0',
    '"Completed"': '0',
    '"Conv%"': 'NA',
    '"AirYds/Att"': 'NA',
  },
  {
    '"Player"': '"Cooper Rush"',
    '"Team"': '"DAL"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '839',
    '"Att"': '116',
    '"Comp"': '72',
    '"Comp%"': '"62%"',
    '"TD"': '4',
    '"Int"': '0',
    '"Yd/Att"': '7.2',
    '"Rating"': '95.4',
    '"Total"': '916',
    '"Completed"': '492',
    '"Conv%"': '"54%"',
    '"AirYds/Att"': '7.9',
  },
  {
    '"Player"': '"Dak Prescott"',
    '"Team"': '"DAL"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Yards"': '134',
    '"Att"': '28',
    '"Comp"': '14',
    '"Comp%"': '"50%"',
    '"TD"': '0',
    '"Int"': '1',
    '"Yd/Att"': '4.8',
    '"Rating"': '48.8',
    '"Total"': '202',
    '"Completed"': '78',
    '"Conv%"': '"39%"',
    '"AirYds/Att"': '7.2',
  },
  {
    '"Player"': '"Daniel Jones"',
    '"Team"': '"NYG"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '848',
    '"Att"': '131',
    '"Comp"': '88',
    '"Comp%"': '"67%"',
    '"TD"': '3',
    '"Int"': '2',
    '"Yd/Att"': '6.5',
    '"Rating"': '86.3',
    '"Total"': '809',
    '"Completed"': '404',
    '"Conv%"': '"50%"',
    '"AirYds/Att"': '6.2',
  },
  {
    '"Player"': '"Davis Mills"',
    '"Team"': '"HOU"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1048',
    '"Att"': '166',
    '"Comp"': '104',
    '"Comp%"': '"63%"',
    '"TD"': '5',
    '"Int"': '4',
    '"Yd/Att"': '6.3',
    '"Rating"': '80.6',
    '"Total"': '1201',
    '"Completed"': '567',
    '"Conv%"': '"47%"',
    '"AirYds/Att"': '7.2',
  },
  {
    '"Player"': '"Derek Carr"',
    '"Team"': '"LV"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1279',
    '"Att"': '182',
    '"Comp"': '113',
    '"Comp%"': '"62%"',
    '"TD"': '8',
    '"Int"': '4',
    '"Yd/Att"': '7',
    '"Rating"': '88.6',
    '"Total"': '1561',
    '"Completed"': '735',
    '"Conv%"': '"47%"',
    '"AirYds/Att"': '8.6',
  },
  {
    '"Player"': '"Geno Smith"',
    '"Team"': '"SEA"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1305',
    '"Att"': '154',
    '"Comp"': '118',
    '"Comp%"': '"77%"',
    '"TD"': '9',
    '"Int"': '2',
    '"Yd/Att"': '8.5',
    '"Rating"': '115.3',
    '"Total"': '1332',
    '"Completed"': '840',
    '"Conv%"': '"63%"',
    '"AirYds/Att"': '8.6',
  },
  {
    '"Player"': '"Jacoby Brissett"',
    '"Team"': '"CLE"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1060',
    '"Att"': '160',
    '"Comp"': '103',
    '"Comp%"': '"64%"',
    '"TD"': '5',
    '"Int"': '3',
    '"Yd/Att"': '6.6',
    '"Rating"': '85.9',
    '"Total"': '1164',
    '"Completed"': '609',
    '"Conv%"': '"52%"',
    '"AirYds/Att"': '7.3',
  },
  {
    '"Player"': '"Jalen Hurts"',
    '"Team"': '"PHI"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1359',
    '"Att"': '158',
    '"Comp"': '108',
    '"Comp%"': '"68%"',
    '"TD"': '4',
    '"Int"': '2',
    '"Yd/Att"': '8.6',
    '"Rating"': '98',
    '"Total"': '1106',
    '"Completed"': '631',
    '"Conv%"': '"57%"',
    '"AirYds/Att"': '7',
  },
  {
    '"Player"': '"Jameis Winston"',
    '"Team"': '"NO"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Yards"': '858',
    '"Att"': '113',
    '"Comp"': '73',
    '"Comp%"': '"65%"',
    '"TD"': '4',
    '"Int"': '5',
    '"Yd/Att"': '7.6',
    '"Rating"': '80.9',
    '"Total"': '1320',
    '"Completed"': '656',
    '"Conv%"': '"50%"',
    '"AirYds/Att"': '11.7',
  },
  {
    '"Player"': '"Jared Goff"',
    '"Team"': '"DET"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1355',
    '"Att"': '180',
    '"Comp"': '111',
    '"Comp%"': '"62%"',
    '"TD"': '11',
    '"Int"': '4',
    '"Yd/Att"': '7.5',
    '"Rating"': '95.9',
    '"Total"': '1625',
    '"Completed"': '687',
    '"Conv%"': '"42%"',
    '"AirYds/Att"': '9',
  },
  {
    '"Player"': '"Jeff Driskel"',
    '"Team"': '"HOU"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Yards"': '0',
    '"Att"': '0',
    '"Comp"': '0',
    '"Comp%"': 'NA',
    '"TD"': '0',
    '"Int"': '0',
    '"Yd/Att"': 'NA',
    '"Rating"': 'NA',
    '"Total"': '0',
    '"Completed"': '0',
    '"Conv%"': 'NA',
    '"AirYds/Att"': 'NA',
  },
  {
    '"Player"': '"Jimmy Garoppolo"',
    '"Team"': '"SF"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Yards"': '857',
    '"Att"': '106',
    '"Comp"': '65',
    '"Comp%"': '"61%"',
    '"TD"': '5',
    '"Int"': '1',
    '"Yd/Att"': '8.1',
    '"Rating"': '98.7',
    '"Total"': '802',
    '"Completed"': '350',
    '"Conv%"': '"44%"',
    '"AirYds/Att"': '7.6',
  },
  {
    '"Player"': '"Joe Burrow"',
    '"Team"': '"CIN"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1316',
    '"Att"': '189',
    '"Comp"': '124',
    '"Comp%"': '"66%"',
    '"TD"': '9',
    '"Int"': '4',
    '"Yd/Att"': '7',
    '"Rating"': '92.8',
    '"Total"': '1261',
    '"Completed"': '579',
    '"Conv%"': '"46%"',
    '"AirYds/Att"': '6.7',
  },
  {
    '"Player"': '"Joe Flacco"',
    '"Team"': '"NYJ"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Yards"': '899',
    '"Att"': '154',
    '"Comp"': '91',
    '"Comp%"': '"59%"',
    '"TD"': '5',
    '"Int"': '3',
    '"Yd/Att"': '5.8',
    '"Rating"': '78.4',
    '"Total"': '1208',
    '"Completed"': '506',
    '"Conv%"': '"42%"',
    '"AirYds/Att"': '7.8',
  },
  {
    '"Player"': '"Jordan Love"',
    '"Team"': '"GB"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Yards"': '65',
    '"Att"': '5',
    '"Comp"': '4',
    '"Comp%"': '"80%"',
    '"TD"': '0',
    '"Int"': '0',
    '"Yd/Att"': '13',
    '"Rating"': '118.8',
    '"Total"': '29',
    '"Completed"': '29',
    '"Conv%"': '"100%"',
    '"AirYds/Att"': '5.8',
  },
  {
    '"Player"': '"Josh Allen"',
    '"Team"': '"BUF"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1651',
    '"Att"': '193',
    '"Comp"': '133',
    '"Comp%"': '"69%"',
    '"TD"': '14',
    '"Int"': '4',
    '"Yd/Att"': '8.6',
    '"Rating"': '110.7',
    '"Total"': '1572',
    '"Completed"': '935',
    '"Conv%"': '"59%"',
    '"AirYds/Att"': '8.1',
  },
  {
    '"Player"': '"Justin Fields"',
    '"Team"': '"CHI"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '676',
    '"Att"': '87',
    '"Comp"': '49',
    '"Comp%"': '"56%"',
    '"TD"': '3',
    '"Int"': '4',
    '"Yd/Att"': '7.8',
    '"Rating"': '73.7',
    '"Total"': '827',
    '"Completed"': '339',
    '"Conv%"': '"41%"',
    '"AirYds/Att"': '9.5',
  },
  {
    '"Player"': '"Justin Herbert"',
    '"Team"': '"LAC"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1478',
    '"Att"': '197',
    '"Comp"': '133',
    '"Comp%"': '"68%"',
    '"TD"': '10',
    '"Int"': '2',
    '"Yd/Att"': '7.5',
    '"Rating"': '102.3',
    '"Total"': '1309',
    '"Completed"': '701',
    '"Conv%"': '"54%"',
    '"AirYds/Att"': '6.6',
  },
  {
    '"Player"': '"Kenny Pickett"',
    '"Team"': '"PIT"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Yards"': '447',
    '"Att"': '64',
    '"Comp"': '44',
    '"Comp%"': '"69%"',
    '"TD"': '0',
    '"Int"': '4',
    '"Yd/Att"': '7',
    '"Rating"': '62.4',
    '"Total"': '530',
    '"Completed"': '270',
    '"Conv%"': '"51%"',
    '"AirYds/Att"': '8.3',
  },
  {
    '"Player"': '"Kirk Cousins"',
    '"Team"': '"MIN"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1327',
    '"Att"': '196',
    '"Comp"': '131',
    '"Comp%"': '"67%"',
    '"TD"': '7',
    '"Int"': '5',
    '"Yd/Att"': '6.8',
    '"Rating"': '87.3',
    '"Total"': '1208',
    '"Completed"': '693',
    '"Conv%"': '"57%"',
    '"AirYds/Att"': '6.2',
  },
  {
    '"Player"': '"Kyler Murray"',
    '"Team"': '"ARI"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1241',
    '"Att"': '214',
    '"Comp"': '141',
    '"Comp%"': '"66%"',
    '"TD"': '6',
    '"Int"': '3',
    '"Yd/Att"': '5.8',
    '"Rating"': '84.7',
    '"Total"': '1322',
    '"Completed"': '571',
    '"Conv%"': '"43%"',
    '"AirYds/Att"': '6.2',
  },
  {
    '"Player"': '"Lamar Jackson"',
    '"Team"': '"BAL"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1067',
    '"Att"': '148',
    '"Comp"': '95',
    '"Comp%"': '"64%"',
    '"TD"': '12',
    '"Int"': '5',
    '"Yd/Att"': '7.2',
    '"Rating"': '98.6',
    '"Total"': '1378',
    '"Completed"': '595',
    '"Conv%"': '"43%"',
    '"AirYds/Att"': '9.3',
  },
  {
    '"Player"': '"Mac Jones"',
    '"Team"': '"NE"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Yards"': '786',
    '"Att"': '95',
    '"Comp"': '64',
    '"Comp%"': '"67%"',
    '"TD"': '2',
    '"Int"': '5',
    '"Yd/Att"': '8.3',
    '"Rating"': '77.8',
    '"Total"': '992',
    '"Completed"': '502',
    '"Conv%"': '"51%"',
    '"AirYds/Att"': '10.4',
  },
  {
    '"Player"': '"Malik Willis"',
    '"Team"': '"TEN"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Yards"': '6',
    '"Att"': '4',
    '"Comp"': '1',
    '"Comp%"': '"25%"',
    '"TD"': '0',
    '"Int"': '0',
    '"Yd/Att"': '1.5',
    '"Rating"': '39.6',
    '"Total"': '29',
    '"Completed"': '6',
    '"Conv%"': '"21%"',
    '"AirYds/Att"': '7.2',
  },
  {
    '"Player"': '"Marcus Mariota"',
    '"Team"': '"ATL"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '926',
    '"Att"': '121',
    '"Comp"': '71',
    '"Comp%"': '"59%"',
    '"TD"': '4',
    '"Int"': '4',
    '"Yd/Att"': '7.7',
    '"Rating"': '80.1',
    '"Total"': '1289',
    '"Completed"': '558',
    '"Conv%"': '"43%"',
    '"AirYds/Att"': '10.7',
  },
  {
    '"Player"': '"Matt Ryan"',
    '"Team"': '"IND"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1376',
    '"Att"': '193',
    '"Comp"': '128',
    '"Comp%"': '"66%"',
    '"TD"': '5',
    '"Int"': '7',
    '"Yd/Att"': '7.1',
    '"Rating"': '80.6',
    '"Total"': '1234',
    '"Completed"': '760',
    '"Conv%"': '"62%"',
    '"AirYds/Att"': '6.4',
  },
  {
    '"Player"': '"Matthew Stafford"',
    '"Team"': '"LAR"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1323',
    '"Att"': '190',
    '"Comp"': '134',
    '"Comp%"': '"71%"',
    '"TD"': '5',
    '"Int"': '7',
    '"Yd/Att"': '7',
    '"Rating"': '83.3',
    '"Total"': '1274',
    '"Completed"': '586',
    '"Conv%"': '"46%"',
    '"AirYds/Att"': '6.7',
  },
  {
    '"Player"': '"Mitchell Trubisky"',
    '"Team"': '"PIT"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Yards"': '653',
    '"Att"': '115',
    '"Comp"': '69',
    '"Comp%"': '"60%"',
    '"TD"': '2',
    '"Int"': '2',
    '"Yd/Att"': '5.7',
    '"Rating"': '74.3',
    '"Total"': '1160',
    '"Completed"': '453',
    '"Conv%"': '"39%"',
    '"AirYds/Att"': '10.1',
  },
  {
    '"Player"': '"Nick Foles"',
    '"Team"': '"IND"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Yards"': '0',
    '"Att"': '0',
    '"Comp"': '0',
    '"Comp%"': 'NA',
    '"TD"': '0',
    '"Int"': '0',
    '"Yd/Att"': 'NA',
    '"Rating"': 'NA',
    '"Total"': '0',
    '"Completed"': '0',
    '"Conv%"': 'NA',
    '"AirYds/Att"': 'NA',
  },
  {
    '"Player"': '"Patrick Mahomes"',
    '"Team"': '"KC"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1398',
    '"Att"': '186',
    '"Comp"': '126',
    '"Comp%"': '"68%"',
    '"TD"': '15',
    '"Int"': '2',
    '"Yd/Att"': '7.5',
    '"Rating"': '112.3',
    '"Total"': '1381',
    '"Completed"': '668',
    '"Conv%"': '"48%"',
    '"AirYds/Att"': '7.4',
  },
  {
    '"Player"': '"Phillip Walker"',
    '"Team"': '"CAR"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Yards"': '60',
    '"Att"': '6',
    '"Comp"': '5',
    '"Comp%"': '"83%"',
    '"TD"': '0',
    '"Int"': '0',
    '"Yd/Att"': '10',
    '"Rating"': '108.3',
    '"Total"': '76',
    '"Completed"': '46',
    '"Conv%"': '"61%"',
    '"AirYds/Att"': '12.7',
  },
  {
    '"Player"': '"Russell Wilson"',
    '"Team"': '"DEN"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1254',
    '"Att"': '167',
    '"Comp"': '101',
    '"Comp%"': '"60%"',
    '"TD"': '4',
    '"Int"': '3',
    '"Yd/Att"': '7.5',
    '"Rating"': '84.3',
    '"Total"': '1447',
    '"Completed"': '620',
    '"Conv%"': '"43%"',
    '"AirYds/Att"': '8.7',
  },
  {
    '"Player"': '"Ryan Tannehill"',
    '"Team"': '"TEN"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '965',
    '"Att"': '125',
    '"Comp"': '82',
    '"Comp%"': '"66%"',
    '"TD"': '6',
    '"Int"': '3',
    '"Yd/Att"': '7.7',
    '"Rating"': '94.9',
    '"Total"': '986',
    '"Completed"': '530',
    '"Conv%"': '"54%"',
    '"AirYds/Att"': '7.9',
  },
  {
    '"Player"': '"Skylar Thompson"',
    '"Team"': '"MIA"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Yards"': '166',
    '"Att"': '33',
    '"Comp"': '19',
    '"Comp%"': '"58%"',
    '"TD"': '0',
    '"Int"': '1',
    '"Yd/Att"': '5',
    '"Rating"': '58.4',
    '"Total"': '227',
    '"Completed"': '94',
    '"Conv%"': '"41%"',
    '"AirYds/Att"': '6.9',
  },
  {
    '"Player"': '"Teddy Bridgewater"',
    '"Team"': '"MIA"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Yards"': '193',
    '"Att"': '25',
    '"Comp"': '14',
    '"Comp%"': '"56%"',
    '"TD"': '1',
    '"Int"': '1',
    '"Yd/Att"': '7.7',
    '"Rating"': '77.6',
    '"Total"': '219',
    '"Completed"': '123',
    '"Conv%"': '"56%"',
    '"AirYds/Att"': '8.8',
  },
  {
    '"Player"': '"Tom Brady"',
    '"Team"': '"TB"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1409',
    '"Att"': '207',
    '"Comp"': '141',
    '"Comp%"': '"68%"',
    '"TD"': '7',
    '"Int"': '1',
    '"Yd/Att"': '6.8',
    '"Rating"': '96.5',
    '"Total"': '1541',
    '"Completed"': '734',
    '"Conv%"': '"48%"',
    '"AirYds/Att"': '7.4',
  },
  {
    '"Player"': '"Trace McSorley"',
    '"Team"': '"ARI"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Yards"': '12',
    '"Att"': '4',
    '"Comp"': '2',
    '"Comp%"': '"50%"',
    '"TD"': '0',
    '"Int"': '0',
    '"Yd/Att"': '3',
    '"Rating"': '56.2',
    '"Total"': '17',
    '"Completed"': '8',
    '"Conv%"': '"47%"',
    '"AirYds/Att"': '4.2',
  },
  {
    '"Player"': '"Trevor Lawrence"',
    '"Team"': '"JAC"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Yards"': '1232',
    '"Att"': '178',
    '"Comp"': '113',
    '"Comp%"': '"63%"',
    '"TD"': '8',
    '"Int"': '4',
    '"Yd/Att"': '6.9',
    '"Rating"': '89.4',
    '"Total"': '1398',
    '"Completed"': '622',
    '"Conv%"': '"44%"',
    '"AirYds/Att"': '7.9',
  },
  {
    '"Player"': '"Trey Lance"',
    '"Team"': '"SF"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Yards"': '194',
    '"Att"': '31',
    '"Comp"': '15',
    '"Comp%"': '"48%"',
    '"TD"': '0',
    '"Int"': '1',
    '"Yd/Att"': '6.3',
    '"Rating"': '55',
    '"Total"': '207',
    '"Completed"': '114',
    '"Conv%"': '"55%"',
    '"AirYds/Att"': '6.7',
  },
  {
    '"Player"': '"Tua Tagovailoa"',
    '"Team"': '"MIA"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Yards"': '1035',
    '"Att"': '113',
    '"Comp"': '80',
    '"Comp%"': '"71%"',
    '"TD"': '8',
    '"Int"': '3',
    '"Yd/Att"': '9.2',
    '"Rating"': '111.8',
    '"Total"': '973',
    '"Completed"': '609',
    '"Conv%"': '"63%"',
    '"AirYds/Att"': '8.6',
  },
  {
    '"Player"': '"Tyrod Taylor"',
    '"Team"': '"NYG"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Yards"': '11',
    '"Att"': '3',
    '"Comp"': '1',
    '"Comp%"': '"33%"',
    '"TD"': '0',
    '"Int"': '1',
    '"Yd/Att"': '3.7',
    '"Rating"': '5.6',
    '"Total"': '72',
    '"Completed"': '5',
    '"Conv%"': '"7%"',
    '"AirYds/Att"': '24',
  },
  {
    '"Player"': '"Zach Wilson"',
    '"Team"': '"NYJ"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Yards"': '462',
    '"Att"': '57',
    '"Comp"': '32',
    '"Comp%"': '"56%"',
    '"TD"': '1',
    '"Int"': '2',
    '"Yd/Att"': '8.1',
    '"Rating"': '73.9',
    '"Total"': '528',
    '"Completed"': '231',
    '"Conv%"': '"44%"',
    '"AirYds/Att"': '9.3',
  },
];

module.exports = QBWeeklyStatExplorerLastFiveWeeksCategoryPassing;
