const QBWeeklyStatExplorerLastFiveWeeksCategoryPassing = [
	{
		"\"Player\"": "\"Aaron Rodgers\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "731",
		"\"Att\"": "135",
		"\"Comp\"": "87",
		"\"Comp%\"": "\"64%\"",
		"\"TD\"": "7",
		"\"Int\"": "1",
		"\"Yd/Att\"": "5.4",
		"\"Rating\"": "92.5",
		"\"Total\"": "834",
		"\"Completed\"": "292",
		"\"Conv%\"": "\"35%\"",
		"\"AirYds/Att\"": "6.2"
	},
	{
		"\"Player\"": "\"Aidan O'Connell\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "340",
		"\"Att\"": "35",
		"\"Comp\"": "23",
		"\"Comp%\"": "\"66%\"",
		"\"TD\"": "2",
		"\"Int\"": "0",
		"\"Yd/Att\"": "9.7",
		"\"Rating\"": "116.4",
		"\"Total\"": "265",
		"\"Completed\"": "186",
		"\"Conv%\"": "\"70%\"",
		"\"AirYds/Att\"": "7.6"
	},
	{
		"\"Player\"": "\"Anthony Richardson\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Yards\"": "553",
		"\"Att\"": "82",
		"\"Comp\"": "43",
		"\"Comp%\"": "\"52%\"",
		"\"TD\"": "3",
		"\"Int\"": "2",
		"\"Yd/Att\"": "6.7",
		"\"Rating\"": "75.9",
		"\"Total\"": "1076",
		"\"Completed\"": "340",
		"\"Conv%\"": "\"32%\"",
		"\"AirYds/Att\"": "13.1"
	},
	{
		"\"Player\"": "\"Baker Mayfield\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "845",
		"\"Att\"": "123",
		"\"Comp\"": "86",
		"\"Comp%\"": "\"70%\"",
		"\"TD\"": "4",
		"\"Int\"": "2",
		"\"Yd/Att\"": "6.9",
		"\"Rating\"": "93",
		"\"Total\"": "740",
		"\"Completed\"": "366",
		"\"Conv%\"": "\"49%\"",
		"\"AirYds/Att\"": "6"
	},
	{
		"\"Player\"": "\"Bo Nix\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "1018",
		"\"Att\"": "138",
		"\"Comp\"": "94",
		"\"Comp%\"": "\"68%\"",
		"\"TD\"": "8",
		"\"Int\"": "1",
		"\"Yd/Att\"": "7.4",
		"\"Rating\"": "105.9",
		"\"Total\"": "913",
		"\"Completed\"": "478",
		"\"Conv%\"": "\"52%\"",
		"\"AirYds/Att\"": "6.6"
	},
	{
		"\"Player\"": "\"Brandon Allen\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "199",
		"\"Att\"": "29",
		"\"Comp\"": "17",
		"\"Comp%\"": "\"59%\"",
		"\"TD\"": "1",
		"\"Int\"": "1",
		"\"Yd/Att\"": "6.9",
		"\"Rating\"": "76.7",
		"\"Total\"": "214",
		"\"Completed\"": "83",
		"\"Conv%\"": "\"39%\"",
		"\"AirYds/Att\"": "7.4"
	},
	{
		"\"Player\"": "\"Brock Purdy\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Yards\"": "606",
		"\"Att\"": "82",
		"\"Comp\"": "57",
		"\"Comp%\"": "\"70%\"",
		"\"TD\"": "3",
		"\"Int\"": "1",
		"\"Yd/Att\"": "7.4",
		"\"Rating\"": "97.9",
		"\"Total\"": "497",
		"\"Completed\"": "318",
		"\"Conv%\"": "\"64%\"",
		"\"AirYds/Att\"": "6.1"
	},
	{
		"\"Player\"": "\"Bryce Young\"",
		"\"Team\"": "\"CAR\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "858",
		"\"Att\"": "132",
		"\"Comp\"": "78",
		"\"Comp%\"": "\"59%\"",
		"\"TD\"": "4",
		"\"Int\"": "1",
		"\"Yd/Att\"": "6.5",
		"\"Rating\"": "85.4",
		"\"Total\"": "1103",
		"\"Completed\"": "494",
		"\"Conv%\"": "\"45%\"",
		"\"AirYds/Att\"": "8.4"
	},
	{
		"\"Player\"": "\"CJ Stroud\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1169",
		"\"Att\"": "164",
		"\"Comp\"": "95",
		"\"Comp%\"": "\"58%\"",
		"\"TD\"": "4",
		"\"Int\"": "5",
		"\"Yd/Att\"": "7.1",
		"\"Rating\"": "75.5",
		"\"Total\"": "1496",
		"\"Completed\"": "633",
		"\"Conv%\"": "\"42%\"",
		"\"AirYds/Att\"": "9.1"
	},
	{
		"\"Player\"": "\"Caleb Williams\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1164",
		"\"Att\"": "188",
		"\"Comp\"": "113",
		"\"Comp%\"": "\"60%\"",
		"\"TD\"": "5",
		"\"Int\"": "0",
		"\"Yd/Att\"": "6.2",
		"\"Rating\"": "86.8",
		"\"Total\"": "1621",
		"\"Completed\"": "625",
		"\"Conv%\"": "\"39%\"",
		"\"AirYds/Att\"": "8.6"
	},
	{
		"\"Player\"": "\"Clayton Tune\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "0",
		"\"Att\"": "0",
		"\"Comp\"": "0",
		"\"Comp%\"": "NA",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "NA",
		"\"Rating\"": "NA",
		"\"Total\"": "0",
		"\"Completed\"": "0",
		"\"Conv%\"": "NA",
		"\"AirYds/Att\"": "NA"
	},
	{
		"\"Player\"": "\"Cooper Rush\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "956",
		"\"Att\"": "171",
		"\"Comp\"": "103",
		"\"Comp%\"": "\"60%\"",
		"\"TD\"": "5",
		"\"Int\"": "1",
		"\"Yd/Att\"": "5.6",
		"\"Rating\"": "82.9",
		"\"Total\"": "1177",
		"\"Completed\"": "444",
		"\"Conv%\"": "\"38%\"",
		"\"AirYds/Att\"": "6.9"
	},
	{
		"\"Player\"": "\"Dak Prescott\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "133",
		"\"Att\"": "24",
		"\"Comp\"": "18",
		"\"Comp%\"": "\"75%\"",
		"\"TD\"": "1",
		"\"Int\"": "0",
		"\"Yd/Att\"": "5.5",
		"\"Rating\"": "101.6",
		"\"Total\"": "90",
		"\"Completed\"": "49",
		"\"Conv%\"": "\"54%\"",
		"\"AirYds/Att\"": "3.8"
	},
	{
		"\"Player\"": "\"Daniel Jones\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "364",
		"\"Att\"": "63",
		"\"Comp\"": "42",
		"\"Comp%\"": "\"67%\"",
		"\"TD\"": "2",
		"\"Int\"": "2",
		"\"Yd/Att\"": "5.8",
		"\"Rating\"": "79.1",
		"\"Total\"": "465",
		"\"Completed\"": "288",
		"\"Conv%\"": "\"62%\"",
		"\"AirYds/Att\"": "7.4"
	},
	{
		"\"Player\"": "\"Derek Carr\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "937",
		"\"Att\"": "120",
		"\"Comp\"": "79",
		"\"Comp%\"": "\"66%\"",
		"\"TD\"": "6",
		"\"Int\"": "0",
		"\"Yd/Att\"": "7.8",
		"\"Rating\"": "106.1",
		"\"Total\"": "808",
		"\"Completed\"": "381",
		"\"Conv%\"": "\"47%\"",
		"\"AirYds/Att\"": "6.7"
	},
	{
		"\"Player\"": "\"Desmond Ridder\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "138",
		"\"Att\"": "26",
		"\"Comp\"": "16",
		"\"Comp%\"": "\"62%\"",
		"\"TD\"": "1",
		"\"Int\"": "0",
		"\"Yd/Att\"": "5.3",
		"\"Rating\"": "88.3",
		"\"Total\"": "146",
		"\"Completed\"": "84",
		"\"Conv%\"": "\"58%\"",
		"\"AirYds/Att\"": "5.6"
	},
	{
		"\"Player\"": "\"Dorian Thompson-Robinson\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "0",
		"\"Att\"": "1",
		"\"Comp\"": "0",
		"\"Comp%\"": "\"0%\"",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "0",
		"\"Rating\"": "39.6",
		"\"Total\"": "4",
		"\"Completed\"": "0",
		"\"Conv%\"": "\"0%\"",
		"\"AirYds/Att\"": "4"
	},
	{
		"\"Player\"": "\"Drake Maye\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1132",
		"\"Att\"": "173",
		"\"Comp\"": "120",
		"\"Comp%\"": "\"69%\"",
		"\"TD\"": "6",
		"\"Int\"": "6",
		"\"Yd/Att\"": "6.5",
		"\"Rating\"": "84.3",
		"\"Total\"": "1249",
		"\"Completed\"": "529",
		"\"Conv%\"": "\"42%\"",
		"\"AirYds/Att\"": "7.2"
	},
	{
		"\"Player\"": "\"Drew Lock\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "181",
		"\"Att\"": "33",
		"\"Comp\"": "22",
		"\"Comp%\"": "\"67%\"",
		"\"TD\"": "0",
		"\"Int\"": "1",
		"\"Yd/Att\"": "5.5",
		"\"Rating\"": "67.9",
		"\"Total\"": "180",
		"\"Completed\"": "84",
		"\"Conv%\"": "\"47%\"",
		"\"AirYds/Att\"": "5.5"
	},
	{
		"\"Player\"": "\"Gardner Minshew\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Yards\"": "636",
		"\"Att\"": "102",
		"\"Comp\"": "65",
		"\"Comp%\"": "\"64%\"",
		"\"TD\"": "3",
		"\"Int\"": "2",
		"\"Yd/Att\"": "6.2",
		"\"Rating\"": "82.8",
		"\"Total\"": "566",
		"\"Completed\"": "290",
		"\"Conv%\"": "\"51%\"",
		"\"AirYds/Att\"": "5.5"
	},
	{
		"\"Player\"": "\"Geno Smith\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "1044",
		"\"Att\"": "128",
		"\"Comp\"": "88",
		"\"Comp%\"": "\"69%\"",
		"\"TD\"": "5",
		"\"Int\"": "5",
		"\"Yd/Att\"": "8.2",
		"\"Rating\"": "90.1",
		"\"Total\"": "1006",
		"\"Completed\"": "588",
		"\"Conv%\"": "\"58%\"",
		"\"AirYds/Att\"": "7.9"
	},
	{
		"\"Player\"": "\"Hendon Hooker\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "37",
		"\"Att\"": "4",
		"\"Comp\"": "3",
		"\"Comp%\"": "\"75%\"",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "9.2",
		"\"Rating\"": "103.1",
		"\"Total\"": "33",
		"\"Completed\"": "27",
		"\"Conv%\"": "\"82%\"",
		"\"AirYds/Att\"": "8.2"
	},
	{
		"\"Player\"": "\"Jake Browning\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "0",
		"\"Att\"": "0",
		"\"Comp\"": "0",
		"\"Comp%\"": "NA",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "NA",
		"\"Rating\"": "NA",
		"\"Total\"": "0",
		"\"Completed\"": "0",
		"\"Conv%\"": "NA",
		"\"AirYds/Att\"": "NA"
	},
	{
		"\"Player\"": "\"Jake Haener\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "0",
		"\"Att\"": "0",
		"\"Comp\"": "0",
		"\"Comp%\"": "NA",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "NA",
		"\"Rating\"": "NA",
		"\"Total\"": "0",
		"\"Completed\"": "0",
		"\"Conv%\"": "NA",
		"\"AirYds/Att\"": "NA"
	},
	{
		"\"Player\"": "\"Jalen Hurts\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "950",
		"\"Att\"": "113",
		"\"Comp\"": "76",
		"\"Comp%\"": "\"67%\"",
		"\"TD\"": "6",
		"\"Int\"": "1",
		"\"Yd/Att\"": "8.4",
		"\"Rating\"": "107.2",
		"\"Total\"": "938",
		"\"Completed\"": "515",
		"\"Conv%\"": "\"55%\"",
		"\"AirYds/Att\"": "8.3"
	},
	{
		"\"Player\"": "\"Jameis Winston\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Yards\"": "849",
		"\"Att\"": "119",
		"\"Comp\"": "74",
		"\"Comp%\"": "\"62%\"",
		"\"TD\"": "3",
		"\"Int\"": "4",
		"\"Yd/Att\"": "7.1",
		"\"Rating\"": "78",
		"\"Total\"": "1096",
		"\"Completed\"": "546",
		"\"Conv%\"": "\"50%\"",
		"\"AirYds/Att\"": "9.2"
	},
	{
		"\"Player\"": "\"Jared Goff\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1193",
		"\"Att\"": "151",
		"\"Comp\"": "104",
		"\"Comp%\"": "\"69%\"",
		"\"TD\"": "9",
		"\"Int\"": "5",
		"\"Yd/Att\"": "7.9",
		"\"Rating\"": "98.5",
		"\"Total\"": "1007",
		"\"Completed\"": "530",
		"\"Conv%\"": "\"53%\"",
		"\"AirYds/Att\"": "6.7"
	},
	{
		"\"Player\"": "\"Jarrett Stidham\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "0",
		"\"Att\"": "0",
		"\"Comp\"": "0",
		"\"Comp%\"": "NA",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "NA",
		"\"Rating\"": "NA",
		"\"Total\"": "0",
		"\"Completed\"": "0",
		"\"Conv%\"": "NA",
		"\"AirYds/Att\"": "NA"
	},
	{
		"\"Player\"": "\"Jayden Daniels\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1083",
		"\"Att\"": "156",
		"\"Comp\"": "104",
		"\"Comp%\"": "\"67%\"",
		"\"TD\"": "8",
		"\"Int\"": "4",
		"\"Yd/Att\"": "6.9",
		"\"Rating\"": "93",
		"\"Total\"": "974",
		"\"Completed\"": "500",
		"\"Conv%\"": "\"51%\"",
		"\"AirYds/Att\"": "6.2"
	},
	{
		"\"Player\"": "\"Joe Burrow\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "1344",
		"\"Att\"": "183",
		"\"Comp\"": "117",
		"\"Comp%\"": "\"64%\"",
		"\"TD\"": "15",
		"\"Int\"": "2",
		"\"Yd/Att\"": "7.3",
		"\"Rating\"": "108.7",
		"\"Total\"": "1432",
		"\"Completed\"": "722",
		"\"Conv%\"": "\"50%\"",
		"\"AirYds/Att\"": "7.8"
	},
	{
		"\"Player\"": "\"Joe Flacco\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "451",
		"\"Att\"": "62",
		"\"Comp\"": "42",
		"\"Comp%\"": "\"68%\"",
		"\"TD\"": "2",
		"\"Int\"": "4",
		"\"Yd/Att\"": "7.3",
		"\"Rating\"": "72.7",
		"\"Total\"": "485",
		"\"Completed\"": "320",
		"\"Conv%\"": "\"66%\"",
		"\"AirYds/Att\"": "7.8"
	},
	{
		"\"Player\"": "\"Jordan Love\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "971",
		"\"Att\"": "107",
		"\"Comp\"": "70",
		"\"Comp%\"": "\"65%\"",
		"\"TD\"": "5",
		"\"Int\"": "2",
		"\"Yd/Att\"": "9.1",
		"\"Rating\"": "102.2",
		"\"Total\"": "987",
		"\"Completed\"": "471",
		"\"Conv%\"": "\"48%\"",
		"\"AirYds/Att\"": "9.2"
	},
	{
		"\"Player\"": "\"Josh Allen\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "925",
		"\"Att\"": "133",
		"\"Comp\"": "87",
		"\"Comp%\"": "\"65%\"",
		"\"TD\"": "6",
		"\"Int\"": "4",
		"\"Yd/Att\"": "7",
		"\"Rating\"": "88.1",
		"\"Total\"": "787",
		"\"Completed\"": "384",
		"\"Conv%\"": "\"49%\"",
		"\"AirYds/Att\"": "5.9"
	},
	{
		"\"Player\"": "\"Josh Johnson\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "0",
		"\"Att\"": "0",
		"\"Comp\"": "0",
		"\"Comp%\"": "NA",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "NA",
		"\"Rating\"": "NA",
		"\"Total\"": "0",
		"\"Completed\"": "0",
		"\"Conv%\"": "NA",
		"\"AirYds/Att\"": "NA"
	},
	{
		"\"Player\"": "\"Justin Fields\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Yards\"": "0",
		"\"Att\"": "1",
		"\"Comp\"": "0",
		"\"Comp%\"": "\"0%\"",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "0",
		"\"Rating\"": "39.6",
		"\"Total\"": "35",
		"\"Completed\"": "0",
		"\"Conv%\"": "\"0%\"",
		"\"AirYds/Att\"": "35"
	},
	{
		"\"Player\"": "\"Justin Herbert\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1114",
		"\"Att\"": "140",
		"\"Comp\"": "86",
		"\"Comp%\"": "\"61%\"",
		"\"TD\"": "5",
		"\"Int\"": "0",
		"\"Yd/Att\"": "8",
		"\"Rating\"": "98.3",
		"\"Total\"": "1384",
		"\"Completed\"": "678",
		"\"Conv%\"": "\"49%\"",
		"\"AirYds/Att\"": "9.9"
	},
	{
		"\"Player\"": "\"Kenny Pickett\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "5",
		"\"Att\"": "2",
		"\"Comp\"": "1",
		"\"Comp%\"": "\"50%\"",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "2.5",
		"\"Rating\"": "56.2",
		"\"Total\"": "14",
		"\"Completed\"": "5",
		"\"Conv%\"": "\"36%\"",
		"\"AirYds/Att\"": "7"
	},
	{
		"\"Player\"": "\"Kirk Cousins\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "946",
		"\"Att\"": "128",
		"\"Comp\"": "84",
		"\"Comp%\"": "\"66%\"",
		"\"TD\"": "3",
		"\"Int\"": "6",
		"\"Yd/Att\"": "7.4",
		"\"Rating\"": "75.8",
		"\"Total\"": "1047",
		"\"Completed\"": "496",
		"\"Conv%\"": "\"47%\"",
		"\"AirYds/Att\"": "8.2"
	},
	{
		"\"Player\"": "\"Kyle Trask\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "5",
		"\"Att\"": "1",
		"\"Comp\"": "1",
		"\"Comp%\"": "\"100%\"",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "5",
		"\"Rating\"": "87.5",
		"\"Total\"": "-3",
		"\"Completed\"": "-3",
		"\"Conv%\"": "\"100%\"",
		"\"AirYds/Att\"": "-3"
	},
	{
		"\"Player\"": "\"Kyler Murray\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "965",
		"\"Att\"": "126",
		"\"Comp\"": "90",
		"\"Comp%\"": "\"71%\"",
		"\"TD\"": "2",
		"\"Int\"": "3",
		"\"Yd/Att\"": "7.7",
		"\"Rating\"": "88.9",
		"\"Total\"": "828",
		"\"Completed\"": "445",
		"\"Conv%\"": "\"54%\"",
		"\"AirYds/Att\"": "6.6"
	},
	{
		"\"Player\"": "\"Lamar Jackson\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1191",
		"\"Att\"": "143",
		"\"Comp\"": "96",
		"\"Comp%\"": "\"67%\"",
		"\"TD\"": "12",
		"\"Int\"": "1",
		"\"Yd/Att\"": "8.3",
		"\"Rating\"": "117.8",
		"\"Total\"": "1287",
		"\"Completed\"": "599",
		"\"Conv%\"": "\"47%\"",
		"\"AirYds/Att\"": "9"
	},
	{
		"\"Player\"": "\"Mac Jones\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Yards\"": "484",
		"\"Att\"": "83",
		"\"Comp\"": "51",
		"\"Comp%\"": "\"61%\"",
		"\"TD\"": "2",
		"\"Int\"": "3",
		"\"Yd/Att\"": "5.8",
		"\"Rating\"": "70.6",
		"\"Total\"": "840",
		"\"Completed\"": "217",
		"\"Conv%\"": "\"26%\"",
		"\"AirYds/Att\"": "10.1"
	},
	{
		"\"Player\"": "\"Malik Willis\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "0",
		"\"Att\"": "0",
		"\"Comp\"": "0",
		"\"Comp%\"": "NA",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "NA",
		"\"Rating\"": "NA",
		"\"Total\"": "0",
		"\"Completed\"": "0",
		"\"Conv%\"": "NA",
		"\"AirYds/Att\"": "NA"
	},
	{
		"\"Player\"": "\"Mason Rudolph\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "240",
		"\"Att\"": "33",
		"\"Comp\"": "20",
		"\"Comp%\"": "\"61%\"",
		"\"TD\"": "2",
		"\"Int\"": "1",
		"\"Yd/Att\"": "7.3",
		"\"Rating\"": "90.5",
		"\"Total\"": "309",
		"\"Completed\"": "159",
		"\"Conv%\"": "\"51%\"",
		"\"AirYds/Att\"": "9.4"
	},
	{
		"\"Player\"": "\"Matthew Stafford\"",
		"\"Team\"": "\"LAR\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1312",
		"\"Att\"": "177",
		"\"Comp\"": "113",
		"\"Comp%\"": "\"64%\"",
		"\"TD\"": "10",
		"\"Int\"": "2",
		"\"Yd/Att\"": "7.4",
		"\"Rating\"": "100.3",
		"\"Total\"": "1467",
		"\"Completed\"": "773",
		"\"Conv%\"": "\"53%\"",
		"\"AirYds/Att\"": "8.3"
	},
	{
		"\"Player\"": "\"Michael Penix Jr\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "24",
		"\"Att\"": "4",
		"\"Comp\"": "2",
		"\"Comp%\"": "\"50%\"",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "6",
		"\"Rating\"": "68.8",
		"\"Total\"": "0",
		"\"Completed\"": "0",
		"\"Conv%\"": "NA",
		"\"AirYds/Att\"": "0"
	},
	{
		"\"Player\"": "\"Mitch Trubisky\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "4",
		"\"Att\"": "1",
		"\"Comp\"": "1",
		"\"Comp%\"": "\"100%\"",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "4",
		"\"Rating\"": "83.3",
		"\"Total\"": "0",
		"\"Completed\"": "0",
		"\"Conv%\"": "NA",
		"\"AirYds/Att\"": "0"
	},
	{
		"\"Player\"": "\"Nick Mullens\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "14",
		"\"Att\"": "1",
		"\"Comp\"": "1",
		"\"Comp%\"": "\"100%\"",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "14",
		"\"Rating\"": "118.8",
		"\"Total\"": "3",
		"\"Completed\"": "3",
		"\"Conv%\"": "\"100%\"",
		"\"AirYds/Att\"": "3"
	},
	{
		"\"Player\"": "\"Patrick Mahomes\"",
		"\"Team\"": "\"KC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1328",
		"\"Att\"": "202",
		"\"Comp\"": "138",
		"\"Comp%\"": "\"68%\"",
		"\"TD\"": "11",
		"\"Int\"": "2",
		"\"Yd/Att\"": "6.6",
		"\"Rating\"": "100.4",
		"\"Total\"": "1330",
		"\"Completed\"": "616",
		"\"Conv%\"": "\"46%\"",
		"\"AirYds/Att\"": "6.6"
	},
	{
		"\"Player\"": "\"Russell Wilson\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "1084",
		"\"Att\"": "130",
		"\"Comp\"": "87",
		"\"Comp%\"": "\"67%\"",
		"\"TD\"": "7",
		"\"Int\"": "3",
		"\"Yd/Att\"": "8.3",
		"\"Rating\"": "100.9",
		"\"Total\"": "1067",
		"\"Completed\"": "526",
		"\"Conv%\"": "\"49%\"",
		"\"AirYds/Att\"": "8.2"
	},
	{
		"\"Player\"": "\"Sam Darnold\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1342",
		"\"Att\"": "169",
		"\"Comp\"": "115",
		"\"Comp%\"": "\"68%\"",
		"\"TD\"": "9",
		"\"Int\"": "5",
		"\"Yd/Att\"": "7.9",
		"\"Rating\"": "97.3",
		"\"Total\"": "1391",
		"\"Completed\"": "794",
		"\"Conv%\"": "\"57%\"",
		"\"AirYds/Att\"": "8.2"
	},
	{
		"\"Player\"": "\"Skylar Thompson\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "0",
		"\"Att\"": "0",
		"\"Comp\"": "0",
		"\"Comp%\"": "NA",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "NA",
		"\"Rating\"": "NA",
		"\"Total\"": "0",
		"\"Completed\"": "0",
		"\"Conv%\"": "NA",
		"\"AirYds/Att\"": "NA"
	},
	{
		"\"Player\"": "\"Tommy DeVito\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "189",
		"\"Att\"": "31",
		"\"Comp\"": "21",
		"\"Comp%\"": "\"68%\"",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "6.1",
		"\"Rating\"": "83.9",
		"\"Total\"": "204",
		"\"Completed\"": "106",
		"\"Conv%\"": "\"52%\"",
		"\"AirYds/Att\"": "6.6"
	},
	{
		"\"Player\"": "\"Trevor Lawrence\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "210",
		"\"Att\"": "41",
		"\"Comp\"": "20",
		"\"Comp%\"": "\"49%\"",
		"\"TD\"": "0",
		"\"Int\"": "3",
		"\"Yd/Att\"": "5.1",
		"\"Rating\"": "33.6",
		"\"Total\"": "453",
		"\"Completed\"": "134",
		"\"Conv%\"": "\"30%\"",
		"\"AirYds/Att\"": "11"
	},
	{
		"\"Player\"": "\"Trey Lance\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "21",
		"\"Att\"": "6",
		"\"Comp\"": "4",
		"\"Comp%\"": "\"67%\"",
		"\"TD\"": "0",
		"\"Int\"": "1",
		"\"Yd/Att\"": "3.5",
		"\"Rating\"": "32.6",
		"\"Total\"": "48",
		"\"Completed\"": "13",
		"\"Conv%\"": "\"27%\"",
		"\"AirYds/Att\"": "8"
	},
	{
		"\"Player\"": "\"Tua Tagovailoa\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1408",
		"\"Att\"": "178",
		"\"Comp\"": "139",
		"\"Comp%\"": "\"78%\"",
		"\"TD\"": "12",
		"\"Int\"": "1",
		"\"Yd/Att\"": "7.9",
		"\"Rating\"": "119.8",
		"\"Total\"": "1007",
		"\"Completed\"": "693",
		"\"Conv%\"": "\"69%\"",
		"\"AirYds/Att\"": "5.7"
	},
	{
		"\"Player\"": "\"Will Levis\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "960",
		"\"Att\"": "115",
		"\"Comp\"": "71",
		"\"Comp%\"": "\"62%\"",
		"\"TD\"": "7",
		"\"Int\"": "2",
		"\"Yd/Att\"": "8.3",
		"\"Rating\"": "101.4",
		"\"Total\"": "1106",
		"\"Completed\"": "547",
		"\"Conv%\"": "\"49%\"",
		"\"AirYds/Att\"": "9.6"
	},
	
]

module.exports = QBWeeklyStatExplorerLastFiveWeeksCategoryPassing;