const QBWeeklyStatExplorerLastFiveWeeksCategoryPassing = [
	{
		"\"Player\"": "\"Aidan O'Connell\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Yards\"": "437",
		"\"Att\"": "65",
		"\"Comp\"": "42",
		"\"Comp%\"": "\"65%\"",
		"\"TD\"": "2",
		"\"Int\"": "2",
		"\"Yd/Att\"": "6.7",
		"\"Rating\"": "81.4",
		"\"Total\"": "499",
		"\"Completed\"": "201",
		"\"Conv%\"": "\"40%\"",
		"\"AirYds/Att\"": "7.7"
	},
	{
		"\"Player\"": "\"Bailey Zappe\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "25",
		"\"Att\"": "7",
		"\"Comp\"": "3",
		"\"Comp%\"": "\"43%\"",
		"\"TD\"": "0",
		"\"Int\"": "1",
		"\"Yd/Att\"": "3.6",
		"\"Rating\"": "13.1",
		"\"Total\"": "53",
		"\"Completed\"": "13",
		"\"Conv%\"": "\"25%\"",
		"\"AirYds/Att\"": "7.6"
	},
	{
		"\"Player\"": "\"Baker Mayfield\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1264",
		"\"Att\"": "180",
		"\"Comp\"": "110",
		"\"Comp%\"": "\"61%\"",
		"\"TD\"": "7",
		"\"Int\"": "3",
		"\"Yd/Att\"": "7",
		"\"Rating\"": "88.3",
		"\"Total\"": "1680",
		"\"Completed\"": "680",
		"\"Conv%\"": "\"40%\"",
		"\"AirYds/Att\"": "9.3"
	},
	{
		"\"Player\"": "\"Brett Rypien\"",
		"\"Team\"": "\"LAR\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Yards\"": "214",
		"\"Att\"": "48",
		"\"Comp\"": "23",
		"\"Comp%\"": "\"48%\"",
		"\"TD\"": "0",
		"\"Int\"": "1",
		"\"Yd/Att\"": "4.5",
		"\"Rating\"": "51.9",
		"\"Total\"": "334",
		"\"Completed\"": "88",
		"\"Conv%\"": "\"26%\"",
		"\"AirYds/Att\"": "7"
	},
	{
		"\"Player\"": "\"Brian Hoyer\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "231",
		"\"Att\"": "42",
		"\"Comp\"": "23",
		"\"Comp%\"": "\"55%\"",
		"\"TD\"": "0",
		"\"Int\"": "2",
		"\"Yd/Att\"": "5.5",
		"\"Rating\"": "50.8",
		"\"Total\"": "344",
		"\"Completed\"": "151",
		"\"Conv%\"": "\"44%\"",
		"\"AirYds/Att\"": "8.2"
	},
	{
		"\"Player\"": "\"Brock Purdy\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "1058",
		"\"Att\"": "114",
		"\"Comp\"": "74",
		"\"Comp%\"": "\"65%\"",
		"\"TD\"": "6",
		"\"Int\"": "5",
		"\"Yd/Att\"": "9.3",
		"\"Rating\"": "94.1",
		"\"Total\"": "945",
		"\"Completed\"": "567",
		"\"Conv%\"": "\"60%\"",
		"\"AirYds/Att\"": "8.3"
	},
	{
		"\"Player\"": "\"Bryce Young\"",
		"\"Team\"": "\"CAR\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "810",
		"\"Att\"": "146",
		"\"Comp\"": "90",
		"\"Comp%\"": "\"62%\"",
		"\"TD\"": "3",
		"\"Int\"": "3",
		"\"Yd/Att\"": "5.5",
		"\"Rating\"": "74.9",
		"\"Total\"": "952",
		"\"Completed\"": "442",
		"\"Conv%\"": "\"46%\"",
		"\"AirYds/Att\"": "6.5"
	},
	{
		"\"Player\"": "\"CJ Beathard\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "5",
		"\"Att\"": "2",
		"\"Comp\"": "1",
		"\"Comp%\"": "\"50%\"",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "2.5",
		"\"Rating\"": "56.2",
		"\"Total\"": "11",
		"\"Completed\"": "5",
		"\"Conv%\"": "\"45%\"",
		"\"AirYds/Att\"": "5.5"
	},
	{
		"\"Player\"": "\"CJ Stroud\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "1165",
		"\"Att\"": "132",
		"\"Comp\"": "82",
		"\"Comp%\"": "\"62%\"",
		"\"TD\"": "8",
		"\"Int\"": "2",
		"\"Yd/Att\"": "8.8",
		"\"Rating\"": "104.5",
		"\"Total\"": "1344",
		"\"Completed\"": "715",
		"\"Conv%\"": "\"53%\"",
		"\"AirYds/Att\"": "10.2"
	},
	{
		"\"Player\"": "\"Clayton Tune\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Yards\"": "62",
		"\"Att\"": "21",
		"\"Comp\"": "12",
		"\"Comp%\"": "\"57%\"",
		"\"TD\"": "0",
		"\"Int\"": "2",
		"\"Yd/Att\"": "3",
		"\"Rating\"": "22.6",
		"\"Total\"": "53",
		"\"Completed\"": "19",
		"\"Conv%\"": "\"36%\"",
		"\"AirYds/Att\"": "2.5"
	},
	{
		"\"Player\"": "\"Cooper Rush\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "71",
		"\"Att\"": "12",
		"\"Comp\"": "9",
		"\"Comp%\"": "\"75%\"",
		"\"TD\"": "0",
		"\"Int\"": "1",
		"\"Yd/Att\"": "5.9",
		"\"Rating\"": "54.5",
		"\"Total\"": "100",
		"\"Completed\"": "27",
		"\"Conv%\"": "\"27%\"",
		"\"AirYds/Att\"": "8.3"
	},
	{
		"\"Player\"": "\"Dak Prescott\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "1354",
		"\"Att\"": "140",
		"\"Comp\"": "101",
		"\"Comp%\"": "\"72%\"",
		"\"TD\"": "12",
		"\"Int\"": "2",
		"\"Yd/Att\"": "9.7",
		"\"Rating\"": "125.1",
		"\"Total\"": "1337",
		"\"Completed\"": "860",
		"\"Conv%\"": "\"64%\"",
		"\"AirYds/Att\"": "9.6"
	},
	{
		"\"Player\"": "\"Daniel Jones\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "25",
		"\"Att\"": "9",
		"\"Comp\"": "4",
		"\"Comp%\"": "\"44%\"",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "2.8",
		"\"Rating\"": "51.6",
		"\"Total\"": "126",
		"\"Completed\"": "7",
		"\"Conv%\"": "\"6%\"",
		"\"AirYds/Att\"": "14"
	},
	{
		"\"Player\"": "\"Derek Carr\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1285",
		"\"Att\"": "184",
		"\"Comp\"": "122",
		"\"Comp%\"": "\"66%\"",
		"\"TD\"": "6",
		"\"Int\"": "2",
		"\"Yd/Att\"": "7",
		"\"Rating\"": "92.8",
		"\"Total\"": "1412",
		"\"Completed\"": "676",
		"\"Conv%\"": "\"48%\"",
		"\"AirYds/Att\"": "7.7"
	},
	{
		"\"Player\"": "\"Deshaun Watson\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Yards\"": "437",
		"\"Att\"": "69",
		"\"Comp\"": "40",
		"\"Comp%\"": "\"58%\"",
		"\"TD\"": "3",
		"\"Int\"": "2",
		"\"Yd/Att\"": "6.3",
		"\"Rating\"": "79.2",
		"\"Total\"": "595",
		"\"Completed\"": "203",
		"\"Conv%\"": "\"34%\"",
		"\"AirYds/Att\"": "8.6"
	},
	{
		"\"Player\"": "\"Desmond Ridder\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "667",
		"\"Att\"": "90",
		"\"Comp\"": "59",
		"\"Comp%\"": "\"66%\"",
		"\"TD\"": "2",
		"\"Int\"": "3",
		"\"Yd/Att\"": "7.4",
		"\"Rating\"": "81.1",
		"\"Total\"": "808",
		"\"Completed\"": "427",
		"\"Conv%\"": "\"53%\"",
		"\"AirYds/Att\"": "9"
	},
	{
		"\"Player\"": "\"Dorian Thompson-Robinson\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "9",
		"\"Att\"": "1",
		"\"Comp\"": "1",
		"\"Comp%\"": "\"100%\"",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "9",
		"\"Rating\"": "104.2",
		"\"Total\"": "0",
		"\"Completed\"": "0",
		"\"Conv%\"": "NA",
		"\"AirYds/Att\"": "0"
	},
	{
		"\"Player\"": "\"Gardner Minshew\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1168",
		"\"Att\"": "173",
		"\"Comp\"": "106",
		"\"Comp%\"": "\"61%\"",
		"\"TD\"": "6",
		"\"Int\"": "6",
		"\"Yd/Att\"": "6.8",
		"\"Rating\"": "78.4",
		"\"Total\"": "1268",
		"\"Completed\"": "610",
		"\"Conv%\"": "\"48%\"",
		"\"AirYds/Att\"": "7.3"
	},
	{
		"\"Player\"": "\"Geno Smith\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1322",
		"\"Att\"": "177",
		"\"Comp\"": "112",
		"\"Comp%\"": "\"63%\"",
		"\"TD\"": "6",
		"\"Int\"": "6",
		"\"Yd/Att\"": "7.5",
		"\"Rating\"": "83.1",
		"\"Total\"": "1355",
		"\"Completed\"": "694",
		"\"Conv%\"": "\"51%\"",
		"\"AirYds/Att\"": "7.7"
	},
	{
		"\"Player\"": "\"Jalen Hurts\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "1085",
		"\"Att\"": "137",
		"\"Comp\"": "97",
		"\"Comp%\"": "\"71%\"",
		"\"TD\"": "9",
		"\"Int\"": "4",
		"\"Yd/Att\"": "7.9",
		"\"Rating\"": "103.8",
		"\"Total\"": "1095",
		"\"Completed\"": "608",
		"\"Conv%\"": "\"56%\"",
		"\"AirYds/Att\"": "8"
	},
	{
		"\"Player\"": "\"Jameis Winston\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "122",
		"\"Att\"": "25",
		"\"Comp\"": "13",
		"\"Comp%\"": "\"52%\"",
		"\"TD\"": "2",
		"\"Int\"": "2",
		"\"Yd/Att\"": "4.9",
		"\"Rating\"": "59.1",
		"\"Total\"": "387",
		"\"Completed\"": "86",
		"\"Conv%\"": "\"22%\"",
		"\"AirYds/Att\"": "15.5"
	},
	{
		"\"Player\"": "\"Jared Goff\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "1242",
		"\"Att\"": "167",
		"\"Comp\"": "112",
		"\"Comp%\"": "\"67%\"",
		"\"TD\"": "5",
		"\"Int\"": "2",
		"\"Yd/Att\"": "7.4",
		"\"Rating\"": "93.9",
		"\"Total\"": "1027",
		"\"Completed\"": "579",
		"\"Conv%\"": "\"56%\"",
		"\"AirYds/Att\"": "6.1"
	},
	{
		"\"Player\"": "\"Jaren Hall\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "101",
		"\"Att\"": "10",
		"\"Comp\"": "8",
		"\"Comp%\"": "\"80%\"",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "10.1",
		"\"Rating\"": "108.8",
		"\"Total\"": "43",
		"\"Completed\"": "36",
		"\"Conv%\"": "\"84%\"",
		"\"AirYds/Att\"": "4.3"
	},
	{
		"\"Player\"": "\"Jimmy Garoppolo\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "288",
		"\"Att\"": "43",
		"\"Comp\"": "24",
		"\"Comp%\"": "\"56%\"",
		"\"TD\"": "1",
		"\"Int\"": "2",
		"\"Yd/Att\"": "6.7",
		"\"Rating\"": "64.9",
		"\"Total\"": "371",
		"\"Completed\"": "159",
		"\"Conv%\"": "\"43%\"",
		"\"AirYds/Att\"": "8.6"
	},
	{
		"\"Player\"": "\"Joe Burrow\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "1163",
		"\"Att\"": "151",
		"\"Comp\"": "110",
		"\"Comp%\"": "\"73%\"",
		"\"TD\"": "9",
		"\"Int\"": "3",
		"\"Yd/Att\"": "7.7",
		"\"Rating\"": "106.5",
		"\"Total\"": "1021",
		"\"Completed\"": "575",
		"\"Conv%\"": "\"56%\"",
		"\"AirYds/Att\"": "6.8"
	},
	{
		"\"Player\"": "\"Jordan Love\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "925",
		"\"Att\"": "138",
		"\"Comp\"": "86",
		"\"Comp%\"": "\"62%\"",
		"\"TD\"": "6",
		"\"Int\"": "4",
		"\"Yd/Att\"": "6.7",
		"\"Rating\"": "84.4",
		"\"Total\"": "1153",
		"\"Completed\"": "499",
		"\"Conv%\"": "\"43%\"",
		"\"AirYds/Att\"": "8.4"
	},
	{
		"\"Player\"": "\"Josh Allen\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1193",
		"\"Att\"": "175",
		"\"Comp\"": "118",
		"\"Comp%\"": "\"67%\"",
		"\"TD\"": "8",
		"\"Int\"": "6",
		"\"Yd/Att\"": "6.8",
		"\"Rating\"": "87.6",
		"\"Total\"": "1478",
		"\"Completed\"": "624",
		"\"Conv%\"": "\"42%\"",
		"\"AirYds/Att\"": "8.4"
	},
	{
		"\"Player\"": "\"Joshua Dobbs\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1015",
		"\"Att\"": "175",
		"\"Comp\"": "108",
		"\"Comp%\"": "\"62%\"",
		"\"TD\"": "5",
		"\"Int\"": "3",
		"\"Yd/Att\"": "5.8",
		"\"Rating\"": "80.1",
		"\"Total\"": "1386",
		"\"Completed\"": "607",
		"\"Conv%\"": "\"44%\"",
		"\"AirYds/Att\"": "7.9"
	},
	{
		"\"Player\"": "\"Justin Fields\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "58",
		"\"Att\"": "10",
		"\"Comp\"": "6",
		"\"Comp%\"": "\"60%\"",
		"\"TD\"": "0",
		"\"Int\"": "1",
		"\"Yd/Att\"": "5.8",
		"\"Rating\"": "36.7",
		"\"Total\"": "54",
		"\"Completed\"": "24",
		"\"Conv%\"": "\"44%\"",
		"\"AirYds/Att\"": "5.4"
	},
	{
		"\"Player\"": "\"Justin Herbert\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1243",
		"\"Att\"": "177",
		"\"Comp\"": "113",
		"\"Comp%\"": "\"64%\"",
		"\"TD\"": "10",
		"\"Int\"": "4",
		"\"Yd/Att\"": "7",
		"\"Rating\"": "94",
		"\"Total\"": "1187",
		"\"Completed\"": "579",
		"\"Conv%\"": "\"49%\"",
		"\"AirYds/Att\"": "6.7"
	},
	{
		"\"Player\"": "\"Kenny Pickett\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "589",
		"\"Att\"": "94",
		"\"Comp\"": "60",
		"\"Comp%\"": "\"64%\"",
		"\"TD\"": "1",
		"\"Int\"": "0",
		"\"Yd/Att\"": "6.3",
		"\"Rating\"": "84.9",
		"\"Total\"": "616",
		"\"Completed\"": "272",
		"\"Conv%\"": "\"44%\"",
		"\"AirYds/Att\"": "6.6"
	},
	{
		"\"Player\"": "\"Kirk Cousins\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Yards\"": "833",
		"\"Att\"": "107",
		"\"Comp\"": "79",
		"\"Comp%\"": "\"74%\"",
		"\"TD\"": "5",
		"\"Int\"": "1",
		"\"Yd/Att\"": "7.8",
		"\"Rating\"": "107.7",
		"\"Total\"": "635",
		"\"Completed\"": "470",
		"\"Conv%\"": "\"74%\"",
		"\"AirYds/Att\"": "5.9"
	},
	{
		"\"Player\"": "\"Kyle Allen\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "0",
		"\"Att\"": "0",
		"\"Comp\"": "0",
		"\"Comp%\"": "NA",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "NA",
		"\"Rating\"": "NA",
		"\"Total\"": "0",
		"\"Completed\"": "0",
		"\"Conv%\"": "NA",
		"\"AirYds/Att\"": "NA"
	},
	{
		"\"Player\"": "\"Kyle Trask\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "0",
		"\"Att\"": "0",
		"\"Comp\"": "0",
		"\"Comp%\"": "NA",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "NA",
		"\"Rating\"": "NA",
		"\"Total\"": "0",
		"\"Completed\"": "0",
		"\"Conv%\"": "NA",
		"\"AirYds/Att\"": "NA"
	},
	{
		"\"Player\"": "\"Kyler Murray\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "249",
		"\"Att\"": "32",
		"\"Comp\"": "19",
		"\"Comp%\"": "\"59%\"",
		"\"TD\"": "0",
		"\"Int\"": "1",
		"\"Yd/Att\"": "7.8",
		"\"Rating\"": "71",
		"\"Total\"": "333",
		"\"Completed\"": "135",
		"\"Conv%\"": "\"41%\"",
		"\"AirYds/Att\"": "10.4"
	},
	{
		"\"Player\"": "\"Lamar Jackson\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1147",
		"\"Att\"": "133",
		"\"Comp\"": "94",
		"\"Comp%\"": "\"71%\"",
		"\"TD\"": "6",
		"\"Int\"": "3",
		"\"Yd/Att\"": "8.6",
		"\"Rating\"": "102.6",
		"\"Total\"": "1082",
		"\"Completed\"": "559",
		"\"Conv%\"": "\"52%\"",
		"\"AirYds/Att\"": "8.1"
	},
	{
		"\"Player\"": "\"Mac Jones\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1023",
		"\"Att\"": "156",
		"\"Comp\"": "107",
		"\"Comp%\"": "\"69%\"",
		"\"TD\"": "5",
		"\"Int\"": "4",
		"\"Yd/Att\"": "6.6",
		"\"Rating\"": "86.6",
		"\"Total\"": "922",
		"\"Completed\"": "379",
		"\"Conv%\"": "\"41%\"",
		"\"AirYds/Att\"": "5.9"
	},
	{
		"\"Player\"": "\"Malik Cunningham\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "0",
		"\"Att\"": "0",
		"\"Comp\"": "0",
		"\"Comp%\"": "NA",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "NA",
		"\"Rating\"": "NA",
		"\"Total\"": "0",
		"\"Completed\"": "0",
		"\"Conv%\"": "NA",
		"\"AirYds/Att\"": "NA"
	},
	{
		"\"Player\"": "\"Malik Willis\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "74",
		"\"Att\"": "5",
		"\"Comp\"": "4",
		"\"Comp%\"": "\"80%\"",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "14.8",
		"\"Rating\"": "118.8",
		"\"Total\"": "39",
		"\"Completed\"": "19",
		"\"Conv%\"": "\"49%\"",
		"\"AirYds/Att\"": "7.8"
	},
	{
		"\"Player\"": "\"Matthew Stafford\"",
		"\"Team\"": "\"LAR\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Yards\"": "619",
		"\"Att\"": "75",
		"\"Comp\"": "42",
		"\"Comp%\"": "\"56%\"",
		"\"TD\"": "3",
		"\"Int\"": "2",
		"\"Yd/Att\"": "8.3",
		"\"Rating\"": "85.4",
		"\"Total\"": "606",
		"\"Completed\"": "330",
		"\"Conv%\"": "\"54%\"",
		"\"AirYds/Att\"": "8.1"
	},
	{
		"\"Player\"": "\"Mike White\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "0",
		"\"Att\"": "1",
		"\"Comp\"": "0",
		"\"Comp%\"": "\"0%\"",
		"\"TD\"": "0",
		"\"Int\"": "1",
		"\"Yd/Att\"": "0",
		"\"Rating\"": "0",
		"\"Total\"": "0",
		"\"Completed\"": "0",
		"\"Conv%\"": "NA",
		"\"AirYds/Att\"": "0"
	},
	{
		"\"Player\"": "\"Mitch Trubisky\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "138",
		"\"Att\"": "27",
		"\"Comp\"": "15",
		"\"Comp%\"": "\"56%\"",
		"\"TD\"": "1",
		"\"Int\"": "2",
		"\"Yd/Att\"": "5.1",
		"\"Rating\"": "51.2",
		"\"Total\"": "0",
		"\"Completed\"": "0",
		"\"Conv%\"": "NA",
		"\"AirYds/Att\"": "0"
	},
	{
		"\"Player\"": "\"Nathan Peterman\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "0",
		"\"Att\"": "0",
		"\"Comp\"": "0",
		"\"Comp%\"": "NA",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "NA",
		"\"Rating\"": "NA",
		"\"Total\"": "0",
		"\"Completed\"": "0",
		"\"Conv%\"": "NA",
		"\"AirYds/Att\"": "NA"
	},
	{
		"\"Player\"": "\"PJ Walker\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "618",
		"\"Att\"": "98",
		"\"Comp\"": "48",
		"\"Comp%\"": "\"49%\"",
		"\"TD\"": "1",
		"\"Int\"": "5",
		"\"Yd/Att\"": "6.3",
		"\"Rating\"": "51.3",
		"\"Total\"": "808",
		"\"Completed\"": "246",
		"\"Conv%\"": "\"30%\"",
		"\"AirYds/Att\"": "8.2"
	},
	{
		"\"Player\"": "\"Patrick Mahomes\"",
		"\"Team\"": "\"KC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "1156",
		"\"Att\"": "150",
		"\"Comp\"": "106",
		"\"Comp%\"": "\"71%\"",
		"\"TD\"": "7",
		"\"Int\"": "4",
		"\"Yd/Att\"": "7.7",
		"\"Rating\"": "97.5",
		"\"Total\"": "945",
		"\"Completed\"": "439",
		"\"Conv%\"": "\"46%\"",
		"\"AirYds/Att\"": "6.3"
	},
	{
		"\"Player\"": "\"Russell Wilson\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "596",
		"\"Att\"": "99",
		"\"Comp\"": "69",
		"\"Comp%\"": "\"70%\"",
		"\"TD\"": "7",
		"\"Int\"": "2",
		"\"Yd/Att\"": "6",
		"\"Rating\"": "100.4",
		"\"Total\"": "571",
		"\"Completed\"": "262",
		"\"Conv%\"": "\"46%\"",
		"\"AirYds/Att\"": "5.8"
	},
	{
		"\"Player\"": "\"Ryan Tannehill\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "76",
		"\"Att\"": "16",
		"\"Comp\"": "8",
		"\"Comp%\"": "\"50%\"",
		"\"TD\"": "0",
		"\"Int\"": "1",
		"\"Yd/Att\"": "4.8",
		"\"Rating\"": "37.5",
		"\"Total\"": "131",
		"\"Completed\"": "27",
		"\"Conv%\"": "\"21%\"",
		"\"AirYds/Att\"": "8.2"
	},
	{
		"\"Player\"": "\"Sam Darnold\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "1",
		"\"Yards\"": "6",
		"\"Att\"": "2",
		"\"Comp\"": "1",
		"\"Comp%\"": "\"50%\"",
		"\"TD\"": "0",
		"\"Int\"": "0",
		"\"Yd/Att\"": "3",
		"\"Rating\"": "56.2",
		"\"Total\"": "0",
		"\"Completed\"": "-4",
		"\"Conv%\"": "\"-Inf\"",
		"\"AirYds/Att\"": "0"
	},
	{
		"\"Player\"": "\"Sam Howell\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "1434",
		"\"Att\"": "206",
		"\"Comp\"": "133",
		"\"Comp%\"": "\"65%\"",
		"\"TD\"": "11",
		"\"Int\"": "3",
		"\"Yd/Att\"": "7",
		"\"Rating\"": "96.6",
		"\"Total\"": "1586",
		"\"Completed\"": "688",
		"\"Conv%\"": "\"43%\"",
		"\"AirYds/Att\"": "7.7"
	},
	{
		"\"Player\"": "\"Taylor Heinicke\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Yards\"": "498",
		"\"Att\"": "74",
		"\"Comp\"": "41",
		"\"Comp%\"": "\"55%\"",
		"\"TD\"": "3",
		"\"Int\"": "1",
		"\"Yd/Att\"": "6.7",
		"\"Rating\"": "84.2",
		"\"Total\"": "677",
		"\"Completed\"": "229",
		"\"Conv%\"": "\"34%\"",
		"\"AirYds/Att\"": "9.1"
	},
	{
		"\"Player\"": "\"Tommy DeVito\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Yards\"": "260",
		"\"Att\"": "54",
		"\"Comp\"": "31",
		"\"Comp%\"": "\"57%\"",
		"\"TD\"": "3",
		"\"Int\"": "3",
		"\"Yd/Att\"": "4.8",
		"\"Rating\"": "65.4",
		"\"Total\"": "316",
		"\"Completed\"": "85",
		"\"Conv%\"": "\"27%\"",
		"\"AirYds/Att\"": "5.9"
	},
	{
		"\"Player\"": "\"Trevor Lawrence\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "862",
		"\"Att\"": "120",
		"\"Comp\"": "81",
		"\"Comp%\"": "\"68%\"",
		"\"TD\"": "4",
		"\"Int\"": "4",
		"\"Yd/Att\"": "7.2",
		"\"Rating\"": "85.5",
		"\"Total\"": "811",
		"\"Completed\"": "389",
		"\"Conv%\"": "\"48%\"",
		"\"AirYds/Att\"": "6.8"
	},
	{
		"\"Player\"": "\"Tua Tagovailoa\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "995",
		"\"Att\"": "142",
		"\"Comp\"": "95",
		"\"Comp%\"": "\"67%\"",
		"\"TD\"": "8",
		"\"Int\"": "2",
		"\"Yd/Att\"": "7",
		"\"Rating\"": "99.9",
		"\"Total\"": "1119",
		"\"Completed\"": "601",
		"\"Conv%\"": "\"54%\"",
		"\"AirYds/Att\"": "7.9"
	},
	{
		"\"Player\"": "\"Tyler Huntley\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "2",
		"\"Yards\"": "38",
		"\"Att\"": "8",
		"\"Comp\"": "5",
		"\"Comp%\"": "\"62%\"",
		"\"TD\"": "1",
		"\"Int\"": "0",
		"\"Yd/Att\"": "4.8",
		"\"Rating\"": "113.5",
		"\"Total\"": "60",
		"\"Completed\"": "13",
		"\"Conv%\"": "\"22%\"",
		"\"AirYds/Att\"": "7.5"
	},
	{
		"\"Player\"": "\"Tyrod Taylor\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Yards\"": "487",
		"\"Att\"": "72",
		"\"Comp\"": "46",
		"\"Comp%\"": "\"64%\"",
		"\"TD\"": "2",
		"\"Int\"": "0",
		"\"Yd/Att\"": "6.8",
		"\"Rating\"": "92.8",
		"\"Total\"": "595",
		"\"Completed\"": "295",
		"\"Conv%\"": "\"50%\"",
		"\"AirYds/Att\"": "8.3"
	},
	{
		"\"Player\"": "\"Tyson Bagent\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "5",
		"\"Yards\"": "859",
		"\"Att\"": "143",
		"\"Comp\"": "94",
		"\"Comp%\"": "\"66%\"",
		"\"TD\"": "3",
		"\"Int\"": "6",
		"\"Yd/Att\"": "6",
		"\"Rating\"": "71.4",
		"\"Total\"": "824",
		"\"Completed\"": "361",
		"\"Conv%\"": "\"44%\"",
		"\"AirYds/Att\"": "5.8"
	},
	{
		"\"Player\"": "\"Will Levis\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "3",
		"\"Yards\"": "699",
		"\"Att\"": "107",
		"\"Comp\"": "60",
		"\"Comp%\"": "\"56%\"",
		"\"TD\"": "4",
		"\"Int\"": "2",
		"\"Yd/Att\"": "6.5",
		"\"Rating\"": "80.7",
		"\"Total\"": "1164",
		"\"Completed\"": "352",
		"\"Conv%\"": "\"30%\"",
		"\"AirYds/Att\"": "10.9"
	},
	{
		"\"Player\"": "\"Zach Wilson\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"QB\"",
		"\"GMs\"": "4",
		"\"Yards\"": "952",
		"\"Att\"": "157",
		"\"Comp\"": "92",
		"\"Comp%\"": "\"59%\"",
		"\"TD\"": "1",
		"\"Int\"": "1",
		"\"Yd/Att\"": "6.1",
		"\"Rating\"": "75.7",
		"\"Total\"": "1245",
		"\"Completed\"": "472",
		"\"Conv%\"": "\"38%\"",
		"\"AirYds/Att\"": "7.9"
	},
	
]

module.exports = QBWeeklyStatExplorerLastFiveWeeksCategoryPassing;