const rb4for4WeeklyStatExplorerHVTsLastFiveWeeks = [
  {
    '"full_name"': '"Austin Ekeler"',
    '"posteam"': '"LAC"',
    '"position"': '"RB"',
    '"Wk 12"': '11',
    '"Wk 13"': '5',
    '"Wk 14"': '11',
    '"Wk 15"': '3',
    '"Wk 16"': '10',
  },
  {
    '"full_name"': '"Rhamondre Stevenson"',
    '"posteam"': '"NE"',
    '"position"': '"RB"',
    '"Wk 12"': '10',
    '"Wk 13"': '6',
    '"Wk 14"': '2',
    '"Wk 15"': '3',
    '"Wk 16"': '7',
  },
  {
    '"full_name"': '"Rachaad White"',
    '"posteam"': '"TB"',
    '"position"': '"RB"',
    '"Wk 12"': '9',
    '"Wk 13"': '6',
    '"Wk 14"': '6',
    '"Wk 15"': '1',
    '"Wk 16"': '4',
  },
  {
    '"full_name"': '"JaMycal Hasty"',
    '"posteam"': '"JAX"',
    '"position"': '"RB"',
    '"Wk 12"': '8',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '1',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Isiah Pacheco"',
    '"posteam"': '"KC"',
    '"position"': '"RB"',
    '"Wk 12"': '8',
    '"Wk 13"': '4',
    '"Wk 14"': '3',
    '"Wk 15"': '2',
    '"Wk 16"': '3',
  },
  {
    '"full_name"': '"Dalvin Cook"',
    '"posteam"': '"MIN"',
    '"position"': '"RB"',
    '"Wk 12"': '7',
    '"Wk 13"': '3',
    '"Wk 14"': '2',
    '"Wk 15"': '7',
    '"Wk 16"': '3',
  },
  {
    '"full_name"': '"Alvin Kamara"',
    '"posteam"': '"NO"',
    '"position"': '"RB"',
    '"Wk 12"': '7',
    '"Wk 13"': '2',
    '"Wk 14"': '0',
    '"Wk 15"': '2',
    '"Wk 16"': '3',
  },
  {
    '"full_name"': '"Josh Jacobs"',
    '"posteam"': '"LV"',
    '"position"': '"RB"',
    '"Wk 12"': '7',
    '"Wk 13"': '2',
    '"Wk 14"': '5',
    '"Wk 15"': '2',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"DAndre Swift"',
    '"posteam"': '"DET"',
    '"position"': '"RB"',
    '"Wk 12"': '7',
    '"Wk 13"': '7',
    '"Wk 14"': '3',
    '"Wk 15"': '5',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Christian McCaffrey"',
    '"posteam"': '"SF"',
    '"position"': '"RB"',
    '"Wk 12"': '6',
    '"Wk 13"': '10',
    '"Wk 14"': '4',
    '"Wk 15"': '8',
    '"Wk 16"': '4',
  },
  {
    '"full_name"': '"Samaje Perine"',
    '"posteam"': '"CIN"',
    '"position"': '"RB"',
    '"Wk 12"': '6',
    '"Wk 13"': '7',
    '"Wk 14"': '2',
    '"Wk 15"': '2',
    '"Wk 16"': '4',
  },
  {
    '"full_name"': '"Jamaal Williams"',
    '"posteam"': '"DET"',
    '"position"': '"RB"',
    '"Wk 12"': '6',
    '"Wk 13"': '2',
    '"Wk 14"': '0',
    '"Wk 15"': '3',
    '"Wk 16"': '3',
  },
  {
    '"full_name"': '"David Montgomery"',
    '"posteam"': '"CHI"',
    '"position"': '"RB"',
    '"Wk 12"': '6',
    '"Wk 13"': '5',
    '"Wk 14"': '0',
    '"Wk 15"': '4',
    '"Wk 16"': '4',
  },
  {
    '"full_name"': '"Jonathan Taylor"',
    '"posteam"': '"IND"',
    '"position"': '"RB"',
    '"Wk 12"': '6',
    '"Wk 13"': '3',
    '"Wk 14"': '0',
    '"Wk 15"': '1',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Cordarrelle Patterson"',
    '"posteam"': '"ATL"',
    '"position"': '"RB"',
    '"Wk 12"': '5',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '3',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Jeff Wilson"',
    '"posteam"': '"MIA"',
    '"position"': '"RB"',
    '"Wk 12"': '5',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '3',
  },
  {
    '"full_name"': '"Saquon Barkley"',
    '"posteam"': '"NYG"',
    '"position"': '"RB"',
    '"Wk 12"': '5',
    '"Wk 13"': '6',
    '"Wk 14"': '5',
    '"Wk 15"': '6',
    '"Wk 16"': '8',
  },
  {
    '"full_name"': '"Ameer Abdullah"',
    '"posteam"': '"LV"',
    '"position"': '"RB"',
    '"Wk 12"': '4',
    '"Wk 13"': '0',
    '"Wk 14"': '2',
    '"Wk 15"': '2',
    '"Wk 16"': '2',
  },
  {
    '"full_name"': '"Derrick Henry"',
    '"posteam"': '"TEN"',
    '"position"': '"RB"',
    '"Wk 12"': '4',
    '"Wk 13"': '2',
    '"Wk 14"': '5',
    '"Wk 15"': '6',
    '"Wk 16"': '2',
  },
  {
    '"full_name"': '"Aaron Jones"',
    '"posteam"': '"GB"',
    '"position"': '"RB"',
    '"Wk 12"': '4',
    '"Wk 13"': '5',
    '"Wk 14"': '0',
    '"Wk 15"': '6',
    '"Wk 16"': '3',
  },
  {
    '"full_name"': '"James Conner"',
    '"posteam"': '"ARI"',
    '"position"': '"RB"',
    '"Wk 12"': '4',
    '"Wk 13"': '0',
    '"Wk 14"': '7',
    '"Wk 15"': '5',
    '"Wk 16"': '7',
  },
  {
    '"full_name"': '"Miles Sanders"',
    '"posteam"': '"PHI"',
    '"position"': '"RB"',
    '"Wk 12"': '4',
    '"Wk 13"': '4',
    '"Wk 14"': '2',
    '"Wk 15"': '3',
    '"Wk 16"': '3',
  },
  {
    '"full_name"': '"Kenneth Gainwell"',
    '"posteam"': '"PHI"',
    '"position"': '"RB"',
    '"Wk 12"': '4',
    '"Wk 13"': '3',
    '"Wk 14"': '1',
    '"Wk 15"': '3',
    '"Wk 16"': '7',
  },
  {
    '"full_name"': '"Zonovan Knight"',
    '"posteam"': '"NYJ"',
    '"position"': '"RB"',
    '"Wk 12"': '4',
    '"Wk 13"': '8',
    '"Wk 14"': '2',
    '"Wk 15"': '0',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Jerick McKinnon"',
    '"posteam"': '"KC"',
    '"position"': '"RB"',
    '"Wk 12"': '3',
    '"Wk 13"': '4',
    '"Wk 14"': '8',
    '"Wk 15"': '8',
    '"Wk 16"': '4',
  },
  {
    '"full_name"': '"Dare Ogunbowale"',
    '"posteam"': '"HOU"',
    '"position"': '"RB"',
    '"Wk 12"': '3',
    '"Wk 13"': '4',
    '"Wk 14"': '2',
    '"Wk 15"': '0',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"DOnta Foreman"',
    '"posteam"': '"CAR"',
    '"position"': '"RB"',
    '"Wk 12"': '3',
    '"Wk 13"': '0',
    '"Wk 14"': '5',
    '"Wk 15"': '3',
    '"Wk 16"': '2',
  },
  {
    '"full_name"': '"Gus Edwards"',
    '"posteam"': '"BAL"',
    '"position"': '"RB"',
    '"Wk 12"': '3',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '1',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Dontrell Hilliard"',
    '"posteam"': '"TEN"',
    '"position"': '"RB"',
    '"Wk 12"': '3',
    '"Wk 13"': '2',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Nick Chubb"',
    '"posteam"': '"CLE"',
    '"position"': '"RB"',
    '"Wk 12"': '3',
    '"Wk 13"': '0',
    '"Wk 14"': '3',
    '"Wk 15"': '3',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Devin Singletary"',
    '"posteam"': '"BUF"',
    '"position"': '"RB"',
    '"Wk 12"': '3',
    '"Wk 13"': '1',
    '"Wk 14"': '1',
    '"Wk 15"': '3',
    '"Wk 16"': '3',
  },
  {
    '"full_name"': '"AJ Dillon"',
    '"posteam"': '"GB"',
    '"position"': '"RB"',
    '"Wk 12"': '3',
    '"Wk 13"': '3',
    '"Wk 14"': '0',
    '"Wk 15"': '6',
    '"Wk 16"': '6',
  },
  {
    '"full_name"': '"Antonio Gibson"',
    '"posteam"': '"WAS"',
    '"position"': '"RB"',
    '"Wk 12"': '3',
    '"Wk 13"': '2',
    '"Wk 14"': '0',
    '"Wk 15"': '2',
    '"Wk 16"': '4',
  },
  {
    '"full_name"': '"Anthony McFarland"',
    '"posteam"': '"PIT"',
    '"position"': '"RB"',
    '"Wk 12"': '3',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Elijah Mitchell"',
    '"posteam"': '"SF"',
    '"position"': '"RB"',
    '"Wk 12"': '3',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Dameon Pierce"',
    '"posteam"': '"HOU"',
    '"position"': '"RB"',
    '"Wk 12"': '3',
    '"Wk 13"': '3',
    '"Wk 14"': '3',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Kyren Williams"',
    '"posteam"': '"LA"',
    '"position"': '"RB"',
    '"Wk 12"': '3',
    '"Wk 13"': '0',
    '"Wk 14"': '1',
    '"Wk 15"': '0',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Kyle Juszczyk"',
    '"posteam"': '"SF"',
    '"position"': '"RB"',
    '"Wk 12"': '2',
    '"Wk 13"': '3',
    '"Wk 14"': '2',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Latavius Murray"',
    '"posteam"': '"DEN"',
    '"position"': '"RB"',
    '"Wk 12"': '2',
    '"Wk 13"': '4',
    '"Wk 14"': '3',
    '"Wk 15"': '3',
    '"Wk 16"': '2',
  },
  {
    '"full_name"': '"Ezekiel Elliott"',
    '"posteam"': '"DAL"',
    '"position"': '"RB"',
    '"Wk 12"': '2',
    '"Wk 13"': '5',
    '"Wk 14"': '9',
    '"Wk 15"': '4',
    '"Wk 16"': '4',
  },
  {
    '"full_name"': '"Patrick Ricard"',
    '"posteam"': '"BAL"',
    '"position"': '"RB"',
    '"Wk 12"': '2',
    '"Wk 13"': '1',
    '"Wk 14"': '0',
    '"Wk 15"': '1',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Benny Snell"',
    '"posteam"': '"PIT"',
    '"position"': '"RB"',
    '"Wk 12"': '2',
    '"Wk 13"': '1',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Tony Pollard"',
    '"posteam"': '"DAL"',
    '"position"': '"RB"',
    '"Wk 12"': '2',
    '"Wk 13"': '3',
    '"Wk 14"': '6',
    '"Wk 15"': '5',
    '"Wk 16"': '7',
  },
  {
    '"full_name"': '"Travis Homer"',
    '"posteam"': '"SEA"',
    '"position"': '"RB"',
    '"Wk 12"': '2',
    '"Wk 13"': '0',
    '"Wk 14"': '4',
    '"Wk 15"': '4',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Joshua Kelley"',
    '"posteam"': '"LAC"',
    '"position"': '"RB"',
    '"Wk 12"': '2',
    '"Wk 13"': '0',
    '"Wk 14"': '1',
    '"Wk 15"': '5',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"DeeJay Dallas"',
    '"posteam"': '"SEA"',
    '"position"': '"RB"',
    '"Wk 12"': '2',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '6',
  },
  {
    '"full_name"': '"Gary Brightwell"',
    '"posteam"': '"NYG"',
    '"position"': '"RB"',
    '"Wk 12"': '2',
    '"Wk 13"': '0',
    '"Wk 14"': '3',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Najee Harris"',
    '"posteam"': '"PIT"',
    '"position"': '"RB"',
    '"Wk 12"': '2',
    '"Wk 13"': '1',
    '"Wk 14"': '3',
    '"Wk 15"': '2',
    '"Wk 16"': '6',
  },
  {
    '"full_name"': '"Michael Carter"',
    '"posteam"': '"NYJ"',
    '"position"': '"RB"',
    '"Wk 12"': '2',
    '"Wk 13"': '0',
    '"Wk 14"': '3',
    '"Wk 15"': '2',
    '"Wk 16"': '5',
  },
  {
    '"full_name"': '"James Cook"',
    '"posteam"': '"BUF"',
    '"position"': '"RB"',
    '"Wk 12"': '2',
    '"Wk 13"': '7',
    '"Wk 14"': '1',
    '"Wk 15"': '2',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Brian Robinson"',
    '"posteam"': '"WAS"',
    '"position"': '"RB"',
    '"Wk 12"': '2',
    '"Wk 13"': '3',
    '"Wk 14"': '0',
    '"Wk 15"': '1',
    '"Wk 16"': '4',
  },
  {
    '"full_name"': '"Rex Burkhead"',
    '"posteam"': '"HOU"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '0',
    '"Wk 14"': '3',
    '"Wk 15"': '2',
    '"Wk 16"': '2',
  },
  {
    '"full_name"': '"Derek Watt"',
    '"posteam"': '"PIT"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '1',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Matt Breida"',
    '"posteam"': '"NYG"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '1',
    '"Wk 14"': '2',
    '"Wk 15"': '1',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Corey Clement"',
    '"posteam"': '"ARI"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '0',
    '"Wk 14"': '1',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Kareem Hunt"',
    '"posteam"': '"CLE"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '2',
    '"Wk 14"': '3',
    '"Wk 15"': '1',
    '"Wk 16"': '3',
  },
  {
    '"full_name"': '"Marlon Mack"',
    '"posteam"': '"DEN"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '1',
    '"Wk 14"': '2',
    '"Wk 15"': '5',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Justin Jackson"',
    '"posteam"': '"DET"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '3',
    '"Wk 14"': '1',
    '"Wk 15"': '2',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Ronald Jones"',
    '"posteam"': '"KC"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Justice Hill"',
    '"posteam"': '"BAL"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '2',
    '"Wk 14"': '0',
    '"Wk 15"': '1',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Alec Ingold"',
    '"posteam"': '"MIA"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '3',
    '"Wk 14"': '0',
    '"Wk 15"': '1',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Devine Ozigbo"',
    '"posteam"': '"DEN"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Trayveon Williams"',
    '"posteam"': '"CIN"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '0',
    '"Wk 14"': '1',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Myles Gaskin"',
    '"posteam"': '"MIA"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Ty Johnson"',
    '"posteam"': '"NYJ"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '6',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Darrynton Evans"',
    '"posteam"': '"CHI"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Caleb Huntley"',
    '"posteam"': '"ATL"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Raheem Blackshear"',
    '"posteam"': '"CAR"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '0',
    '"Wk 14"': '2',
    '"Wk 15"': '0',
    '"Wk 16"': '2',
  },
  {
    '"full_name"': '"Isaiah Spiller"',
    '"posteam"': '"LAC"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Kenneth Walker"',
    '"posteam"': '"SEA"',
    '"position"': '"RB"',
    '"Wk 12"': '1',
    '"Wk 13"': '1',
    '"Wk 14"': '0',
    '"Wk 15"': '4',
    '"Wk 16"': '2',
  },
  {
    '"full_name"': '"Mark Ingram"',
    '"posteam"': '"NO"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '6',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Brandon Bolden"',
    '"posteam"': '"LV"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Giovani Bernard"',
    '"posteam"': '"TB"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Michael Burton"',
    '"posteam"': '"KC"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Raheem Mostert"',
    '"posteam"': '"MIA"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '1',
    '"Wk 15"': '2',
    '"Wk 16"': '2',
  },
  {
    '"full_name"': '"Malcolm Brown"',
    '"posteam"': '"LA"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '2',
    '"Wk 15"': '0',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"David Johnson"',
    '"posteam"': '"NO"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"CJ Ham"',
    '"posteam"': '"MIN"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '1',
    '"Wk 15"': '2',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Jonathan Williams"',
    '"posteam"': '"WAS"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '2',
  },
  {
    '"full_name"': '"Kenyan Drake"',
    '"posteam"': '"BAL"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '2',
    '"Wk 14"': '2',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Leonard Fournette"',
    '"posteam"': '"TB"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '7',
    '"Wk 14"': '6',
    '"Wk 15"': '6',
    '"Wk 16"': '9',
  },
  {
    '"full_name"': '"Joe Mixon"',
    '"posteam"': '"CIN"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '2',
    '"Wk 15"': '8',
    '"Wk 16"': '7',
  },
  {
    '"full_name"': '"Jason Cabinda"',
    '"posteam"': '"DET"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Mike Boone"',
    '"posteam"': '"DEN"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '1',
    '"Wk 14"': '2',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Nyheim Hines"',
    '"posteam"': '"BUF"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '3',
    '"Wk 14"': '1',
    '"Wk 15"': '1',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Jordan Wilkins"',
    '"posteam"': '"IND"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Boston Scott"',
    '"posteam"': '"PHI"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '1',
    '"Wk 14"': '2',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Chase Edmonds"',
    '"posteam"': '"DEN"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '2',
  },
  {
    '"full_name"': '"Royce Freeman"',
    '"posteam"': '"HOU"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '2',
    '"Wk 16"': '3',
  },
  {
    '"full_name"': '"Alexander Mattison"',
    '"posteam"': '"MIN"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '2',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Khari Blasingame"',
    '"posteam"': '"CHI"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Damien Harris"',
    '"posteam"': '"NE"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Jakob Johnson"',
    '"posteam"': '"LV"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '1',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"James Robinson"',
    '"posteam"': '"NYJ"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Tony Jones"',
    '"posteam"': '"SEA"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '2',
    '"Wk 14"': '1',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Patrick Taylor"',
    '"posteam"': '"GB"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Salvon Ahmed"',
    '"posteam"': '"MIA"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"JK Dobbins"',
    '"posteam"': '"BAL"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '1',
    '"Wk 15"': '1',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Reggie Gilliam"',
    '"posteam"': '"BUF"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Zack Moss"',
    '"posteam"': '"IND"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '3',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Eno Benjamin"',
    '"posteam"': '"HOU"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Cam Akers"',
    '"posteam"': '"LA"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '3',
    '"Wk 14"': '3',
    '"Wk 15"': '4',
    '"Wk 16"': '6',
  },
  {
    '"full_name"': '"KeShawn Vaughn"',
    '"posteam"': '"TB"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Deon Jackson"',
    '"posteam"': '"IND"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '1',
    '"Wk 16"': '3',
  },
  {
    '"full_name"': '"Chuba Hubbard"',
    '"posteam"': '"CAR"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '5',
    '"Wk 15"': '4',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Demetric Felton"',
    '"posteam"': '"CLE"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '1',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Adam Prentice"',
    '"posteam"': '"NO"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '1',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Chris Evans"',
    '"posteam"': '"CIN"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '1',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Khalil Herbert"',
    '"posteam"': '"CHI"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '2',
  },
  {
    '"full_name"': '"Avery Williams"',
    '"posteam"': '"ATL"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '2',
    '"Wk 16"': '2',
  },
  {
    '"full_name"': '"Travis Etienne"',
    '"posteam"': '"JAX"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '4',
    '"Wk 14"': '1',
    '"Wk 15"': '6',
    '"Wk 16"': '5',
  },
  {
    '"full_name"': '"Trestan Ebner"',
    '"posteam"': '"CHI"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Jaylen Warren"',
    '"posteam"': '"PIT"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '2',
    '"Wk 14"': '2',
    '"Wk 15"': '4',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Tyler Allgeier"',
    '"posteam"': '"ATL"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '3',
    '"Wk 16"': '7',
  },
  {
    '"full_name"': '"Snoop Conner"',
    '"posteam"': '"JAX"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Jerome Ford"',
    '"posteam"': '"CLE"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Kevin Harris"',
    '"posteam"': '"NE"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Keaontay Ingram"',
    '"posteam"': '"ARI"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Troy Hairston"',
    '"posteam"': '"HOU"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '1',
  },
  {
    '"full_name"': '"Jordan Mason"',
    '"posteam"': '"SF"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Malik Davis"',
    '"posteam"': '"DAL"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Julius Chestnut"',
    '"posteam"': '"TEN"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '2',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Hassan Haskins"',
    '"posteam"': '"TEN"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '2',
    '"Wk 16"': '2',
  },
  {
    '"full_name"': '"Tyrion Davis-Price"',
    '"posteam"': '"SF"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Zamir White"',
    '"posteam"': '"LV"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '0',
    '"Wk 15"': '0',
    '"Wk 16"': '0',
  },
  {
    '"full_name"': '"Pierre Strong"',
    '"posteam"': '"NE"',
    '"position"': '"RB"',
    '"Wk 12"': '0',
    '"Wk 13"': '0',
    '"Wk 14"': '3',
    '"Wk 15"': '3',
    '"Wk 16"': '2',
  },
];

module.exports = rb4for4WeeklyStatExplorerHVTsLastFiveWeeks;
