const rbRvWeeklyStatExplorerRecievingTabLastFiveWeeks = [
	{
		"\"Player\"": "\"Aaron Jones\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "12",
		"\"Rec\"": "11",
		"\"Yards\"": "91",
		"\"TD\"": "0",
		"\"YPR\"": "8.3",
		"\"Yd/Tgt\"": "7.6",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "32",
		"\"AY/Tgt\"": "2.7",
		"\"YAC\"": "82",
		"\"RACR\"": "2.84",
		"\"Team %\"": "\"3%\"",
		"\"WOPR\"": "0.17",
		"\"AirYAC (AY+YAC)\"": "114"
	},
	{
		"\"Player\"": "\"Aaron Shampklin\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Adam Prentice\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "2",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "0",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "4",
		"\"AY/Tgt\"": "2",
		"\"YAC\"": "0",
		"\"RACR\"": "0",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "4"
	},
	{
		"\"Player\"": "\"Alec Ingold\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "4",
		"\"Rec\"": "4",
		"\"Yards\"": "44",
		"\"TD\"": "0",
		"\"YPR\"": "11",
		"\"Yd/Tgt\"": "11",
		"\"Tgt Shr\"": "\"5%\"",
		"\"AirYards\"": "20",
		"\"AY/Tgt\"": "5",
		"\"YAC\"": "24",
		"\"RACR\"": "2.2",
		"\"Team %\"": "\"4%\"",
		"\"WOPR\"": "0.09",
		"\"AirYAC (AY+YAC)\"": "44"
	},
	{
		"\"Player\"": "\"Alexander Mattison\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "14",
		"\"Rec\"": "13",
		"\"Yards\"": "92",
		"\"TD\"": "0",
		"\"YPR\"": "7.1",
		"\"Yd/Tgt\"": "6.6",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "-2",
		"\"AY/Tgt\"": "-0.1",
		"\"YAC\"": "94",
		"\"RACR\"": "-46",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.15",
		"\"AirYAC (AY+YAC)\"": "92"
	},
	{
		"\"Player\"": "\"Alvin Kamara\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "41",
		"\"Rec\"": "28",
		"\"Yards\"": "207",
		"\"TD\"": "0",
		"\"YPR\"": "7.4",
		"\"Yd/Tgt\"": "5",
		"\"Tgt Shr\"": "\"25%\"",
		"\"AirYards\"": "11",
		"\"AY/Tgt\"": "0.3",
		"\"YAC\"": "240",
		"\"RACR\"": "18.82",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.38",
		"\"AirYAC (AY+YAC)\"": "251"
	},
	{
		"\"Player\"": "\"Ameer Abdullah\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "10",
		"\"Rec\"": "7",
		"\"Yards\"": "37",
		"\"TD\"": "0",
		"\"YPR\"": "5.3",
		"\"Yd/Tgt\"": "3.7",
		"\"Tgt Shr\"": "\"7%\"",
		"\"AirYards\"": "6",
		"\"AY/Tgt\"": "0.6",
		"\"YAC\"": "39",
		"\"RACR\"": "6.17",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.12",
		"\"AirYAC (AY+YAC)\"": "45"
	},
	{
		"\"Player\"": "\"Andrew Beck\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "1",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "0",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "-6",
		"\"AY/Tgt\"": "-6",
		"\"YAC\"": "0",
		"\"RACR\"": "0",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "-6"
	},
	{
		"\"Player\"": "\"Antonio Gibson\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "6",
		"\"Rec\"": "5",
		"\"Yards\"": "45",
		"\"TD\"": "0",
		"\"YPR\"": "9",
		"\"Yd/Tgt\"": "7.5",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "1",
		"\"AY/Tgt\"": "0.2",
		"\"YAC\"": "48",
		"\"RACR\"": "45",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "49"
	},
	{
		"\"Player\"": "\"Audric Estime\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Austin Ekeler\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "16",
		"\"Rec\"": "12",
		"\"Yards\"": "104",
		"\"TD\"": "0",
		"\"YPR\"": "8.7",
		"\"Yd/Tgt\"": "6.5",
		"\"Tgt Shr\"": "\"11%\"",
		"\"AirYards\"": "-16",
		"\"AY/Tgt\"": "-1",
		"\"YAC\"": "120",
		"\"RACR\"": "-6.5",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.16",
		"\"AirYAC (AY+YAC)\"": "104"
	},
	{
		"\"Player\"": "\"Avery Williams\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Bijan Robinson\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "27",
		"\"Rec\"": "23",
		"\"Yards\"": "180",
		"\"TD\"": "1",
		"\"YPR\"": "7.8",
		"\"Yd/Tgt\"": "6.7",
		"\"Tgt Shr\"": "\"18%\"",
		"\"AirYards\"": "-15",
		"\"AY/Tgt\"": "-0.6",
		"\"YAC\"": "203",
		"\"RACR\"": "-12",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.25",
		"\"AirYAC (AY+YAC)\"": "188"
	},
	{
		"\"Player\"": "\"Blake Corum\"",
		"\"Team\"": "\"LAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "9",
		"\"TD\"": "0",
		"\"YPR\"": "9",
		"\"Yd/Tgt\"": "9",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "-2",
		"\"AY/Tgt\"": "-2",
		"\"YAC\"": "11",
		"\"RACR\"": "-4.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "9"
	},
	{
		"\"Player\"": "\"Braelon Allen\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "5",
		"\"Rec\"": "2",
		"\"Yards\"": "9",
		"\"TD\"": "0",
		"\"YPR\"": "4.5",
		"\"Yd/Tgt\"": "1.8",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "2",
		"\"AY/Tgt\"": "0.4",
		"\"YAC\"": "17",
		"\"RACR\"": "4.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "19"
	},
	{
		"\"Player\"": "\"Breece Hall\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "26",
		"\"Rec\"": "18",
		"\"Yards\"": "210",
		"\"TD\"": "0",
		"\"YPR\"": "11.7",
		"\"Yd/Tgt\"": "8.1",
		"\"Tgt Shr\"": "\"16%\"",
		"\"AirYards\"": "7",
		"\"AY/Tgt\"": "0.3",
		"\"YAC\"": "199",
		"\"RACR\"": "30",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.24",
		"\"AirYAC (AY+YAC)\"": "206"
	},
	{
		"\"Player\"": "\"Brian Robinson Jr\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "11",
		"\"TD\"": "0",
		"\"YPR\"": "11",
		"\"Yd/Tgt\"": "11",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "-6",
		"\"AY/Tgt\"": "-6",
		"\"YAC\"": "17",
		"\"RACR\"": "-1.83",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "11"
	},
	{
		"\"Player\"": "\"Bucky Irving\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "18",
		"\"Rec\"": "18",
		"\"Yards\"": "142",
		"\"TD\"": "0",
		"\"YPR\"": "7.9",
		"\"Yd/Tgt\"": "7.9",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "-41",
		"\"AY/Tgt\"": "-2.3",
		"\"YAC\"": "183",
		"\"RACR\"": "-3.46",
		"\"Team %\"": "\"-3%\"",
		"\"WOPR\"": "0.12",
		"\"AirYAC (AY+YAC)\"": "142"
	},
	{
		"\"Player\"": "\"CJ Ham\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Cam Akers\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "3",
		"\"Rec\"": "3",
		"\"Yards\"": "16",
		"\"TD\"": "0",
		"\"YPR\"": "5.3",
		"\"Yd/Tgt\"": "5.3",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "-7",
		"\"AY/Tgt\"": "-2.3",
		"\"YAC\"": "23",
		"\"RACR\"": "-2.29",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "16"
	},
	{
		"\"Player\"": "\"Carson Steele\"",
		"\"Team\"": "\"KC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "8",
		"\"TD\"": "0",
		"\"YPR\"": "8",
		"\"Yd/Tgt\"": "8",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "8",
		"\"RACR\"": "Inf",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "8"
	},
	{
		"\"Player\"": "\"Chase Brown\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "25",
		"\"Rec\"": "20",
		"\"Yards\"": "111",
		"\"TD\"": "1",
		"\"YPR\"": "5.6",
		"\"Yd/Tgt\"": "4.4",
		"\"Tgt Shr\"": "\"14%\"",
		"\"AirYards\"": "-14",
		"\"AY/Tgt\"": "-0.6",
		"\"YAC\"": "120",
		"\"RACR\"": "-7.93",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.21",
		"\"AirYAC (AY+YAC)\"": "106"
	},
	{
		"\"Player\"": "\"Chris Brooks\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "5",
		"\"Rec\"": "4",
		"\"Yards\"": "29",
		"\"TD\"": "0",
		"\"YPR\"": "7.2",
		"\"Yd/Tgt\"": "5.8",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "4",
		"\"AY/Tgt\"": "0.8",
		"\"YAC\"": "30",
		"\"RACR\"": "7.25",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "34"
	},
	{
		"\"Player\"": "\"Chris Collier\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Chris Rodriguez Jr\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Christian McCaffrey\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "7",
		"\"Rec\"": "6",
		"\"Yards\"": "68",
		"\"TD\"": "0",
		"\"YPR\"": "11.3",
		"\"Yd/Tgt\"": "9.7",
		"\"Tgt Shr\"": "\"21%\"",
		"\"AirYards\"": "37",
		"\"AY/Tgt\"": "5.3",
		"\"YAC\"": "31",
		"\"RACR\"": "1.84",
		"\"Team %\"": "\"15%\"",
		"\"WOPR\"": "0.41",
		"\"AirYAC (AY+YAC)\"": "68"
	},
	{
		"\"Player\"": "\"Chuba Hubbard\"",
		"\"Team\"": "\"CAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "17",
		"\"Rec\"": "13",
		"\"Yards\"": "42",
		"\"TD\"": "0",
		"\"YPR\"": "3.2",
		"\"Yd/Tgt\"": "2.5",
		"\"Tgt Shr\"": "\"12%\"",
		"\"AirYards\"": "-25",
		"\"AY/Tgt\"": "-1.5",
		"\"YAC\"": "66",
		"\"RACR\"": "-1.68",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.17",
		"\"AirYAC (AY+YAC)\"": "41"
	},
	{
		"\"Player\"": "\"Cordarrelle Patterson\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Craig Reynolds\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"D'Andre Swift\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "11",
		"\"Rec\"": "11",
		"\"Yards\"": "65",
		"\"TD\"": "0",
		"\"YPR\"": "5.9",
		"\"Yd/Tgt\"": "5.9",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "-3",
		"\"AY/Tgt\"": "-0.3",
		"\"YAC\"": "68",
		"\"RACR\"": "-21.67",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.15",
		"\"AirYAC (AY+YAC)\"": "65"
	},
	{
		"\"Player\"": "\"D'Ernest Johnson\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "9",
		"\"Rec\"": "6",
		"\"Yards\"": "68",
		"\"TD\"": "0",
		"\"YPR\"": "11.3",
		"\"Yd/Tgt\"": "7.6",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "7",
		"\"AY/Tgt\"": "0.8",
		"\"YAC\"": "67",
		"\"RACR\"": "9.71",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.12",
		"\"AirYAC (AY+YAC)\"": "74"
	},
	{
		"\"Player\"": "\"D'Onta Foreman\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "16",
		"\"TD\"": "0",
		"\"YPR\"": "8",
		"\"Yd/Tgt\"": "8",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "5",
		"\"AY/Tgt\"": "2.5",
		"\"YAC\"": "11",
		"\"RACR\"": "3.2",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.03",
		"\"AirYAC (AY+YAC)\"": "16"
	},
	{
		"\"Player\"": "\"Dalvin Cook\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "10",
		"\"TD\"": "0",
		"\"YPR\"": "10",
		"\"Yd/Tgt\"": "10",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "3",
		"\"AY/Tgt\"": "3",
		"\"YAC\"": "7",
		"\"RACR\"": "3.33",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "10"
	},
	{
		"\"Player\"": "\"Dameon Pierce\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "1",
		"\"TD\"": "0",
		"\"YPR\"": "1",
		"\"Yd/Tgt\"": "1",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "-2",
		"\"AY/Tgt\"": "-2",
		"\"YAC\"": "3",
		"\"RACR\"": "-0.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "1"
	},
	{
		"\"Player\"": "\"Dare Ogunbowale\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "5",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "0",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "25",
		"\"AY/Tgt\"": "5",
		"\"YAC\"": "0",
		"\"RACR\"": "0",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "25"
	},
	{
		"\"Player\"": "\"David Montgomery\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "11",
		"\"Rec\"": "9",
		"\"Yards\"": "91",
		"\"TD\"": "0",
		"\"YPR\"": "10.1",
		"\"Yd/Tgt\"": "8.3",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "2",
		"\"AY/Tgt\"": "0.2",
		"\"YAC\"": "95",
		"\"RACR\"": "45.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.15",
		"\"AirYAC (AY+YAC)\"": "97"
	},
	{
		"\"Player\"": "\"De'Von Achane\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "19",
		"\"Rec\"": "16",
		"\"Yards\"": "116",
		"\"TD\"": "2",
		"\"YPR\"": "7.2",
		"\"Yd/Tgt\"": "6.1",
		"\"Tgt Shr\"": "\"22%\"",
		"\"AirYards\"": "-14",
		"\"AY/Tgt\"": "-0.7",
		"\"YAC\"": "125",
		"\"RACR\"": "-8.29",
		"\"Team %\"": "\"-3%\"",
		"\"WOPR\"": "0.31",
		"\"AirYAC (AY+YAC)\"": "111"
	},
	{
		"\"Player\"": "\"DeeJay Dallas\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Derrick Henry\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "4",
		"\"Rec\"": "4",
		"\"Yards\"": "47",
		"\"TD\"": "1",
		"\"YPR\"": "11.8",
		"\"Yd/Tgt\"": "11.8",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "-14",
		"\"AY/Tgt\"": "-3.5",
		"\"YAC\"": "61",
		"\"RACR\"": "-3.36",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "47"
	},
	{
		"\"Player\"": "\"Devin Singletary\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "6",
		"\"Rec\"": "4",
		"\"Yards\"": "20",
		"\"TD\"": "0",
		"\"YPR\"": "5",
		"\"Yd/Tgt\"": "3.3",
		"\"Tgt Shr\"": "\"5%\"",
		"\"AirYards\"": "3",
		"\"AY/Tgt\"": "0.5",
		"\"YAC\"": "23",
		"\"RACR\"": "6.67",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.08",
		"\"AirYAC (AY+YAC)\"": "26"
	},
	{
		"\"Player\"": "\"Dylan Laube\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Emanuel Wilson\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "5",
		"\"Rec\"": "4",
		"\"Yards\"": "18",
		"\"TD\"": "0",
		"\"YPR\"": "4.5",
		"\"Yd/Tgt\"": "3.6",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-20",
		"\"AY/Tgt\"": "-4",
		"\"YAC\"": "36",
		"\"RACR\"": "-0.9",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "16"
	},
	{
		"\"Player\"": "\"Emari Demercado\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "10",
		"\"Rec\"": "7",
		"\"Yards\"": "60",
		"\"TD\"": "0",
		"\"YPR\"": "8.6",
		"\"Yd/Tgt\"": "6",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "40",
		"\"AY/Tgt\"": "4",
		"\"YAC\"": "43",
		"\"RACR\"": "1.5",
		"\"Team %\"": "\"5%\"",
		"\"WOPR\"": "0.15",
		"\"AirYAC (AY+YAC)\"": "83"
	},
	{
		"\"Player\"": "\"Eric Gray\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "10",
		"\"TD\"": "0",
		"\"YPR\"": "5",
		"\"Yd/Tgt\"": "5",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "-8",
		"\"AY/Tgt\"": "-4",
		"\"YAC\"": "18",
		"\"RACR\"": "-1.25",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "10"
	},
	{
		"\"Player\"": "\"Evan Hull\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Ezekiel Elliott\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "4",
		"\"TD\"": "0",
		"\"YPR\"": "4",
		"\"Yd/Tgt\"": "4",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "-2",
		"\"AY/Tgt\"": "-2",
		"\"YAC\"": "6",
		"\"RACR\"": "-2",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "4"
	},
	{
		"\"Player\"": "\"Gus Edwards\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Hassan Haskins\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Hunter Luepke\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "3",
		"\"Rec\"": "2",
		"\"Yards\"": "4",
		"\"TD\"": "0",
		"\"YPR\"": "2",
		"\"Yd/Tgt\"": "1.3",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "3",
		"\"AY/Tgt\"": "1",
		"\"YAC\"": "4",
		"\"RACR\"": "1.33",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.03",
		"\"AirYAC (AY+YAC)\"": "7"
	},
	{
		"\"Player\"": "\"Isaac Guerendo\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "5",
		"\"Rec\"": "4",
		"\"Yards\"": "22",
		"\"TD\"": "0",
		"\"YPR\"": "5.5",
		"\"Yd/Tgt\"": "4.4",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "7",
		"\"AY/Tgt\"": "1.4",
		"\"YAC\"": "20",
		"\"RACR\"": "3.14",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "27"
	},
	{
		"\"Player\"": "\"Isaiah Davis\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "10",
		"\"TD\"": "0",
		"\"YPR\"": "10",
		"\"Yd/Tgt\"": "10",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "3",
		"\"AY/Tgt\"": "3",
		"\"YAC\"": "7",
		"\"RACR\"": "3.33",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.03",
		"\"AirYAC (AY+YAC)\"": "10"
	},
	{
		"\"Player\"": "\"JJ Taylor\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"JK Dobbins\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "17",
		"\"Rec\"": "14",
		"\"Yards\"": "68",
		"\"TD\"": "0",
		"\"YPR\"": "4.9",
		"\"Yd/Tgt\"": "4",
		"\"Tgt Shr\"": "\"12%\"",
		"\"AirYards\"": "-34",
		"\"AY/Tgt\"": "-2",
		"\"YAC\"": "81",
		"\"RACR\"": "-2",
		"\"Team %\"": "\"-3%\"",
		"\"WOPR\"": "0.16",
		"\"AirYAC (AY+YAC)\"": "47"
	},
	{
		"\"Player\"": "\"JaMycal Hasty\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "9",
		"\"Rec\"": "8",
		"\"Yards\"": "59",
		"\"TD\"": "1",
		"\"YPR\"": "7.4",
		"\"Yd/Tgt\"": "6.6",
		"\"Tgt Shr\"": "\"7%\"",
		"\"AirYards\"": "-8",
		"\"AY/Tgt\"": "-0.9",
		"\"YAC\"": "71",
		"\"RACR\"": "-7.38",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.1",
		"\"AirYAC (AY+YAC)\"": "63"
	},
	{
		"\"Player\"": "\"Jahmyr Gibbs\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "15",
		"\"Rec\"": "11",
		"\"Yards\"": "126",
		"\"TD\"": "0",
		"\"YPR\"": "11.5",
		"\"Yd/Tgt\"": "8.4",
		"\"Tgt Shr\"": "\"13%\"",
		"\"AirYards\"": "8",
		"\"AY/Tgt\"": "0.5",
		"\"YAC\"": "153",
		"\"RACR\"": "15.75",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.2",
		"\"AirYAC (AY+YAC)\"": "161"
	},
	{
		"\"Player\"": "\"Jaleel McLaughlin\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "6",
		"\"Rec\"": "6",
		"\"Yards\"": "36",
		"\"TD\"": "1",
		"\"YPR\"": "6",
		"\"Yd/Tgt\"": "6",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-9",
		"\"AY/Tgt\"": "-1.5",
		"\"YAC\"": "45",
		"\"RACR\"": "-4",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "36"
	},
	{
		"\"Player\"": "\"Jamaal Williams\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"James Conner\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "20",
		"\"Rec\"": "16",
		"\"Yards\"": "181",
		"\"TD\"": "0",
		"\"YPR\"": "11.3",
		"\"Yd/Tgt\"": "9.1",
		"\"Tgt Shr\"": "\"15%\"",
		"\"AirYards\"": "-43",
		"\"AY/Tgt\"": "-2.1",
		"\"YAC\"": "207",
		"\"RACR\"": "-4.21",
		"\"Team %\"": "\"-5%\"",
		"\"WOPR\"": "0.19",
		"\"AirYAC (AY+YAC)\"": "164"
	},
	{
		"\"Player\"": "\"James Cook\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "12",
		"\"Rec\"": "9",
		"\"Yards\"": "52",
		"\"TD\"": "0",
		"\"YPR\"": "5.8",
		"\"Yd/Tgt\"": "4.3",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "-4",
		"\"AY/Tgt\"": "-0.3",
		"\"YAC\"": "52",
		"\"RACR\"": "-13",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.11",
		"\"AirYAC (AY+YAC)\"": "48"
	},
	{
		"\"Player\"": "\"Jase McClellan\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Javonte Williams\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "19",
		"\"Rec\"": "14",
		"\"Yards\"": "92",
		"\"TD\"": "0",
		"\"YPR\"": "6.6",
		"\"Yd/Tgt\"": "4.8",
		"\"Tgt Shr\"": "\"12%\"",
		"\"AirYards\"": "19",
		"\"AY/Tgt\"": "1",
		"\"YAC\"": "93",
		"\"RACR\"": "4.84",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.19",
		"\"AirYAC (AY+YAC)\"": "112"
	},
	{
		"\"Player\"": "\"Jaylen Warren\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "11",
		"\"Rec\"": "9",
		"\"Yards\"": "68",
		"\"TD\"": "0",
		"\"YPR\"": "7.6",
		"\"Yd/Tgt\"": "6.2",
		"\"Tgt Shr\"": "\"11%\"",
		"\"AirYards\"": "17",
		"\"AY/Tgt\"": "1.5",
		"\"YAC\"": "66",
		"\"RACR\"": "4",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.17",
		"\"AirYAC (AY+YAC)\"": "83"
	},
	{
		"\"Player\"": "\"Jaylen Wright\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Jeremy McNichols\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "1",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "0",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "-2",
		"\"AY/Tgt\"": "-2",
		"\"YAC\"": "0",
		"\"RACR\"": "0",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "-2"
	},
	{
		"\"Player\"": "\"Jerome Ford\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "3",
		"\"Rec\"": "1",
		"\"Yards\"": "2",
		"\"TD\"": "0",
		"\"YPR\"": "2",
		"\"Yd/Tgt\"": "0.7",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "7",
		"\"AY/Tgt\"": "2.3",
		"\"YAC\"": "0",
		"\"RACR\"": "0.29",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "7"
	},
	{
		"\"Player\"": "\"Joe Mixon\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "16",
		"\"Rec\"": "10",
		"\"Yards\"": "115",
		"\"TD\"": "1",
		"\"YPR\"": "11.5",
		"\"Yd/Tgt\"": "7.2",
		"\"Tgt Shr\"": "\"11%\"",
		"\"AirYards\"": "-1",
		"\"AY/Tgt\"": "-0.1",
		"\"YAC\"": "128",
		"\"RACR\"": "-115",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.16",
		"\"AirYAC (AY+YAC)\"": "127"
	},
	{
		"\"Player\"": "\"Jonathan Taylor\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "10",
		"\"Rec\"": "6",
		"\"Yards\"": "31",
		"\"TD\"": "0",
		"\"YPR\"": "5.2",
		"\"Yd/Tgt\"": "3.1",
		"\"Tgt Shr\"": "\"11%\"",
		"\"AirYards\"": "-20",
		"\"AY/Tgt\"": "-2",
		"\"YAC\"": "45",
		"\"RACR\"": "-1.55",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.15",
		"\"AirYAC (AY+YAC)\"": "25"
	},
	{
		"\"Player\"": "\"Jonathan Ward\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Jordan Mason\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "4",
		"\"Rec\"": "3",
		"\"Yards\"": "20",
		"\"TD\"": "0",
		"\"YPR\"": "6.7",
		"\"Yd/Tgt\"": "5",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "4",
		"\"AY/Tgt\"": "1",
		"\"YAC\"": "20",
		"\"RACR\"": "5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "24"
	},
	{
		"\"Player\"": "\"Jordan Mims\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "7",
		"\"Rec\"": "4",
		"\"Yards\"": "42",
		"\"TD\"": "0",
		"\"YPR\"": "10.5",
		"\"Yd/Tgt\"": "6",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "-10",
		"\"AY/Tgt\"": "-1.4",
		"\"YAC\"": "44",
		"\"RACR\"": "-4.2",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.11",
		"\"AirYAC (AY+YAC)\"": "34"
	},
	{
		"\"Player\"": "\"Josh Jacobs\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "13",
		"\"Rec\"": "11",
		"\"Yards\"": "55",
		"\"TD\"": "1",
		"\"YPR\"": "5",
		"\"Yd/Tgt\"": "4.2",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "-15",
		"\"AY/Tgt\"": "-1.2",
		"\"YAC\"": "74",
		"\"RACR\"": "-3.67",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.14",
		"\"AirYAC (AY+YAC)\"": "59"
	},
	{
		"\"Player\"": "\"Julius Chestnut\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "9",
		"\"TD\"": "0",
		"\"YPR\"": "9",
		"\"Yd/Tgt\"": "9",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "-3",
		"\"AY/Tgt\"": "-3",
		"\"YAC\"": "12",
		"\"RACR\"": "-3",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "9"
	},
	{
		"\"Player\"": "\"Justice Hill\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "10",
		"\"Rec\"": "10",
		"\"Yards\"": "103",
		"\"TD\"": "1",
		"\"YPR\"": "10.3",
		"\"Yd/Tgt\"": "10.3",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "-16",
		"\"AY/Tgt\"": "-1.6",
		"\"YAC\"": "119",
		"\"RACR\"": "-6.44",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.1",
		"\"AirYAC (AY+YAC)\"": "103"
	},
	{
		"\"Player\"": "\"Kareem Hunt\"",
		"\"Team\"": "\"KC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "14",
		"\"Rec\"": "11",
		"\"Yards\"": "85",
		"\"TD\"": "0",
		"\"YPR\"": "7.7",
		"\"Yd/Tgt\"": "6.1",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "-26",
		"\"AY/Tgt\"": "-1.9",
		"\"YAC\"": "104",
		"\"RACR\"": "-3.27",
		"\"Team %\"": "\"-3%\"",
		"\"WOPR\"": "0.13",
		"\"AirYAC (AY+YAC)\"": "78"
	},
	{
		"\"Player\"": "\"Keaton Mitchell\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Kendall Milton\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Kendre Miller\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "3",
		"\"Rec\"": "2",
		"\"Yards\"": "1",
		"\"TD\"": "0",
		"\"YPR\"": "0.5",
		"\"Yd/Tgt\"": "0.3",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-1",
		"\"AY/Tgt\"": "-0.3",
		"\"YAC\"": "4",
		"\"RACR\"": "-1",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "3"
	},
	{
		"\"Player\"": "\"Kenneth Gainwell\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "5",
		"\"Rec\"": "3",
		"\"Yards\"": "21",
		"\"TD\"": "0",
		"\"YPR\"": "7",
		"\"Yd/Tgt\"": "4.2",
		"\"Tgt Shr\"": "\"5%\"",
		"\"AirYards\"": "-2",
		"\"AY/Tgt\"": "-0.4",
		"\"YAC\"": "15",
		"\"RACR\"": "-10.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "13"
	},
	{
		"\"Player\"": "\"Kenneth Walker III\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "18",
		"\"Rec\"": "17",
		"\"Yards\"": "118",
		"\"TD\"": "1",
		"\"YPR\"": "6.9",
		"\"Yd/Tgt\"": "6.6",
		"\"Tgt Shr\"": "\"13%\"",
		"\"AirYards\"": "-3",
		"\"AY/Tgt\"": "-0.2",
		"\"YAC\"": "117",
		"\"RACR\"": "-39.33",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.2",
		"\"AirYAC (AY+YAC)\"": "114"
	},
	{
		"\"Player\"": "\"Kenny McIntosh\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Khalil Herbert\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Khari Blasingame\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Kimani Vidal\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "3",
		"\"Rec\"": "3",
		"\"Yards\"": "49",
		"\"TD\"": "1",
		"\"YPR\"": "16.3",
		"\"Yd/Tgt\"": "16.3",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "23",
		"\"AY/Tgt\"": "7.7",
		"\"YAC\"": "26",
		"\"RACR\"": "2.13",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "49"
	},
	{
		"\"Player\"": "\"Kyle Juszczyk\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "8",
		"\"Rec\"": "4",
		"\"Yards\"": "16",
		"\"TD\"": "0",
		"\"YPR\"": "4",
		"\"Yd/Tgt\"": "2",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "25",
		"\"AY/Tgt\"": "3.1",
		"\"YAC\"": "12",
		"\"RACR\"": "0.64",
		"\"Team %\"": "\"4%\"",
		"\"WOPR\"": "0.17",
		"\"AirYAC (AY+YAC)\"": "37"
	},
	{
		"\"Player\"": "\"Kyren Williams\"",
		"\"Team\"": "\"LAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "10",
		"\"Rec\"": "6",
		"\"Yards\"": "45",
		"\"TD\"": "1",
		"\"YPR\"": "7.5",
		"\"Yd/Tgt\"": "4.5",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "-7",
		"\"AY/Tgt\"": "-0.7",
		"\"YAC\"": "47",
		"\"RACR\"": "-6.43",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.15",
		"\"AirYAC (AY+YAC)\"": "40"
	},
	{
		"\"Player\"": "\"Michael Burton\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "28",
		"\"TD\"": "0",
		"\"YPR\"": "28",
		"\"Yd/Tgt\"": "28",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "0",
		"\"RACR\"": "Inf",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Miles Sanders\"",
		"\"Team\"": "\"CAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "12",
		"\"Rec\"": "11",
		"\"Yards\"": "39",
		"\"TD\"": "0",
		"\"YPR\"": "3.5",
		"\"Yd/Tgt\"": "3.2",
		"\"Tgt Shr\"": "\"9%\"",
		"\"AirYards\"": "-42",
		"\"AY/Tgt\"": "-3.5",
		"\"YAC\"": "73",
		"\"RACR\"": "-0.93",
		"\"Team %\"": "\"-4%\"",
		"\"WOPR\"": "0.1",
		"\"AirYAC (AY+YAC)\"": "31"
	},
	{
		"\"Player\"": "\"Najee Harris\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "7",
		"\"Rec\"": "5",
		"\"Yards\"": "33",
		"\"TD\"": "0",
		"\"YPR\"": "6.6",
		"\"Yd/Tgt\"": "4.7",
		"\"Tgt Shr\"": "\"7%\"",
		"\"AirYards\"": "10",
		"\"AY/Tgt\"": "1.4",
		"\"YAC\"": "22",
		"\"RACR\"": "3.3",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.11",
		"\"AirYAC (AY+YAC)\"": "32"
	},
	{
		"\"Player\"": "\"Nick Chubb\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "6",
		"\"Rec\"": "2",
		"\"Yards\"": "6",
		"\"TD\"": "0",
		"\"YPR\"": "3",
		"\"Yd/Tgt\"": "1",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-5",
		"\"AY/Tgt\"": "-0.8",
		"\"YAC\"": "7",
		"\"RACR\"": "-1.2",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "2"
	},
	{
		"\"Player\"": "\"Patrick Ricard\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "2",
		"\"Rec\"": "1",
		"\"Yards\"": "3",
		"\"TD\"": "1",
		"\"YPR\"": "3",
		"\"Yd/Tgt\"": "1.5",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "8",
		"\"AY/Tgt\"": "4",
		"\"YAC\"": "2",
		"\"RACR\"": "0.38",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.03",
		"\"AirYAC (AY+YAC)\"": "10"
	},
	{
		"\"Player\"": "\"Patrick Taylor\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "12",
		"\"TD\"": "0",
		"\"YPR\"": "12",
		"\"Yd/Tgt\"": "12",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "3",
		"\"AY/Tgt\"": "3",
		"\"YAC\"": "9",
		"\"RACR\"": "4",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.03",
		"\"AirYAC (AY+YAC)\"": "12"
	},
	{
		"\"Player\"": "\"Pierre Strong Jr\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "7",
		"\"Rec\"": "4",
		"\"Yards\"": "47",
		"\"TD\"": "0",
		"\"YPR\"": "11.8",
		"\"Yd/Tgt\"": "6.7",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-18",
		"\"AY/Tgt\"": "-2.6",
		"\"YAC\"": "66",
		"\"RACR\"": "-2.61",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "48"
	},
	{
		"\"Player\"": "\"Rachaad White\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "22",
		"\"Rec\"": "20",
		"\"Yards\"": "164",
		"\"TD\"": "4",
		"\"YPR\"": "8.2",
		"\"Yd/Tgt\"": "7.5",
		"\"Tgt Shr\"": "\"14%\"",
		"\"AirYards\"": "-1",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "185",
		"\"RACR\"": "-164",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.22",
		"\"AirYAC (AY+YAC)\"": "184"
	},
	{
		"\"Player\"": "\"Raheem Blackshear\"",
		"\"Team\"": "\"CAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Raheem Mostert\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "4",
		"\"Rec\"": "3",
		"\"Yards\"": "43",
		"\"TD\"": "0",
		"\"YPR\"": "14.3",
		"\"Yd/Tgt\"": "10.8",
		"\"Tgt Shr\"": "\"5%\"",
		"\"AirYards\"": "1",
		"\"AY/Tgt\"": "0.2",
		"\"YAC\"": "35",
		"\"RACR\"": "43",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "36"
	},
	{
		"\"Player\"": "\"Ray Davis\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "6",
		"\"Rec\"": "6",
		"\"Yards\"": "131",
		"\"TD\"": "1",
		"\"YPR\"": "21.8",
		"\"Yd/Tgt\"": "21.8",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "38",
		"\"AY/Tgt\"": "6.3",
		"\"YAC\"": "93",
		"\"RACR\"": "3.45",
		"\"Team %\"": "\"3%\"",
		"\"WOPR\"": "0.08",
		"\"AirYAC (AY+YAC)\"": "131"
	},
	{
		"\"Player\"": "\"Reggie Gilliam\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Rhamondre Stevenson\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "12",
		"\"Rec\"": "11",
		"\"Yards\"": "65",
		"\"TD\"": "1",
		"\"YPR\"": "5.9",
		"\"Yd/Tgt\"": "5.4",
		"\"Tgt Shr\"": "\"9%\"",
		"\"AirYards\"": "-5",
		"\"AY/Tgt\"": "-0.4",
		"\"YAC\"": "78",
		"\"RACR\"": "-13",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.14",
		"\"AirYAC (AY+YAC)\"": "73"
	},
	{
		"\"Player\"": "\"Rico Dowdle\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "15",
		"\"Rec\"": "13",
		"\"Yards\"": "65",
		"\"TD\"": "1",
		"\"YPR\"": "5",
		"\"Yd/Tgt\"": "4.3",
		"\"Tgt Shr\"": "\"13%\"",
		"\"AirYards\"": "-4",
		"\"AY/Tgt\"": "-0.3",
		"\"YAC\"": "69",
		"\"RACR\"": "-16.25",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.19",
		"\"AirYAC (AY+YAC)\"": "65"
	},
	{
		"\"Player\"": "\"Roschon Johnson\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "8",
		"\"Rec\"": "5",
		"\"Yards\"": "38",
		"\"TD\"": "0",
		"\"YPR\"": "7.6",
		"\"Yd/Tgt\"": "4.8",
		"\"Tgt Shr\"": "\"7%\"",
		"\"AirYards\"": "4",
		"\"AY/Tgt\"": "0.5",
		"\"YAC\"": "38",
		"\"RACR\"": "9.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.11",
		"\"AirYAC (AY+YAC)\"": "42"
	},
	{
		"\"Player\"": "\"Samaje Perine\"",
		"\"Team\"": "\"KC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "10",
		"\"Rec\"": "9",
		"\"Yards\"": "114",
		"\"TD\"": "1",
		"\"YPR\"": "12.7",
		"\"Yd/Tgt\"": "11.4",
		"\"Tgt Shr\"": "\"7%\"",
		"\"AirYards\"": "18",
		"\"AY/Tgt\"": "1.8",
		"\"YAC\"": "92",
		"\"RACR\"": "6.33",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.12",
		"\"AirYAC (AY+YAC)\"": "110"
	},
	{
		"\"Player\"": "\"Saquon Barkley\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "11",
		"\"Rec\"": "9",
		"\"Yards\"": "73",
		"\"TD\"": "1",
		"\"YPR\"": "8.1",
		"\"Yd/Tgt\"": "6.6",
		"\"Tgt Shr\"": "\"11%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "68",
		"\"RACR\"": "Inf",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.17",
		"\"AirYAC (AY+YAC)\"": "68"
	},
	{
		"\"Player\"": "\"Scott Matlock\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "9",
		"\"TD\"": "0",
		"\"YPR\"": "9",
		"\"Yd/Tgt\"": "9",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "3",
		"\"AY/Tgt\"": "3",
		"\"YAC\"": "6",
		"\"RACR\"": "3",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "9"
	},
	{
		"\"Player\"": "\"Sean Tucker\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "7",
		"\"Rec\"": "6",
		"\"Yards\"": "83",
		"\"TD\"": "1",
		"\"YPR\"": "13.8",
		"\"Yd/Tgt\"": "11.9",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "6",
		"\"AY/Tgt\"": "0.9",
		"\"YAC\"": "87",
		"\"RACR\"": "13.83",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "93"
	},
	{
		"\"Player\"": "\"Sione Vaki\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Tank Bigsby\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "4",
		"\"Rec\"": "2",
		"\"Yards\"": "8",
		"\"TD\"": "0",
		"\"YPR\"": "4",
		"\"Yd/Tgt\"": "2",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "-10",
		"\"AY/Tgt\"": "-2.5",
		"\"YAC\"": "9",
		"\"RACR\"": "-0.8",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "-1"
	},
	{
		"\"Player\"": "\"Terrell Jennings\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Tony Pollard\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "21",
		"\"Rec\"": "15",
		"\"Yards\"": "67",
		"\"TD\"": "0",
		"\"YPR\"": "4.5",
		"\"Yd/Tgt\"": "3.2",
		"\"Tgt Shr\"": "\"13%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "67",
		"\"RACR\"": "Inf",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.2",
		"\"AirYAC (AY+YAC)\"": "67"
	},
	{
		"\"Player\"": "\"Travis Etienne\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "5",
		"\"Rec\"": "3",
		"\"Yards\"": "5",
		"\"TD\"": "0",
		"\"YPR\"": "1.7",
		"\"Yd/Tgt\"": "1",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "9",
		"\"AY/Tgt\"": "1.8",
		"\"YAC\"": "10",
		"\"RACR\"": "0.56",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.1",
		"\"AirYAC (AY+YAC)\"": "19"
	},
	{
		"\"Player\"": "\"Trayveon Williams\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Trey Benson\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "3",
		"\"Rec\"": "3",
		"\"Yards\"": "43",
		"\"TD\"": "0",
		"\"YPR\"": "14.3",
		"\"Yd/Tgt\"": "14.3",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "-4",
		"\"AY/Tgt\"": "-1.3",
		"\"YAC\"": "47",
		"\"RACR\"": "-10.75",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.03",
		"\"AirYAC (AY+YAC)\"": "43"
	},
	{
		"\"Player\"": "\"Trey Sermon\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "5",
		"\"Rec\"": "4",
		"\"Yards\"": "40",
		"\"TD\"": "0",
		"\"YPR\"": "10",
		"\"Yd/Tgt\"": "8",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "2",
		"\"AY/Tgt\"": "0.4",
		"\"YAC\"": "37",
		"\"RACR\"": "20",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "39"
	},
	{
		"\"Player\"": "\"Ty Chandler\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Ty Johnson\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "5",
		"\"Rec\"": "4",
		"\"Yards\"": "36",
		"\"TD\"": "1",
		"\"YPR\"": "9",
		"\"Yd/Tgt\"": "7.2",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "18",
		"\"AY/Tgt\"": "3.6",
		"\"YAC\"": "30",
		"\"RACR\"": "2",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "48"
	},
	{
		"\"Player\"": "\"Tyjae Spears\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "3",
		"\"Rec\"": "3",
		"\"Yards\"": "4",
		"\"TD\"": "0",
		"\"YPR\"": "1.3",
		"\"Yd/Tgt\"": "1.3",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "-3",
		"\"AY/Tgt\"": "-1",
		"\"YAC\"": "7",
		"\"RACR\"": "-1.33",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.09",
		"\"AirYAC (AY+YAC)\"": "4"
	},
	{
		"\"Player\"": "\"Tyler Allgeier\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "12",
		"\"TD\"": "0",
		"\"YPR\"": "6",
		"\"Yd/Tgt\"": "6",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "6",
		"\"AY/Tgt\"": "3",
		"\"YAC\"": "6",
		"\"RACR\"": "2",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "12"
	},
	{
		"\"Player\"": "\"Tyler Goodson\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "9",
		"\"Rec\"": "6",
		"\"Yards\"": "23",
		"\"TD\"": "1",
		"\"YPR\"": "3.8",
		"\"Yd/Tgt\"": "2.6",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "21",
		"\"AY/Tgt\"": "2.3",
		"\"YAC\"": "29",
		"\"RACR\"": "1.1",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.1",
		"\"AirYAC (AY+YAC)\"": "50"
	},
	{
		"\"Player\"": "\"Tyrone Tracy Jr\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "15",
		"\"Rec\"": "13",
		"\"Yards\"": "75",
		"\"TD\"": "0",
		"\"YPR\"": "5.8",
		"\"Yd/Tgt\"": "5",
		"\"Tgt Shr\"": "\"9%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "0",
		"\"RACR\"": "Inf",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.14",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Will Shipley\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Zach Charbonnet\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "9",
		"\"Rec\"": "7",
		"\"Yards\"": "55",
		"\"TD\"": "0",
		"\"YPR\"": "7.9",
		"\"Yd/Tgt\"": "6.1",
		"\"Tgt Shr\"": "\"7%\"",
		"\"AirYards\"": "-16",
		"\"AY/Tgt\"": "-1.8",
		"\"YAC\"": "69",
		"\"RACR\"": "-3.44",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.09",
		"\"AirYAC (AY+YAC)\"": "53"
	},
	{
		"\"Player\"": "\"Zack Moss\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "8",
		"\"Rec\"": "8",
		"\"Yards\"": "63",
		"\"TD\"": "0",
		"\"YPR\"": "7.9",
		"\"Yd/Tgt\"": "7.9",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "2",
		"\"AY/Tgt\"": "0.2",
		"\"YAC\"": "61",
		"\"RACR\"": "31.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.15",
		"\"AirYAC (AY+YAC)\"": "63"
	},
	{
		"\"Player\"": "\"Zamir White\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "14",
		"\"TD\"": "0",
		"\"YPR\"": "14",
		"\"Yd/Tgt\"": "14",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "-6",
		"\"AY/Tgt\"": "-6",
		"\"YAC\"": "20",
		"\"RACR\"": "-2.33",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "14"
	},
	
]

module.exports = rbRvWeeklyStatExplorerRecievingTabLastFiveWeeks;