const rbRvWeeklyStatExplorerRecievingTabLastFiveWeeks = [
	{
		"\"Player\"": "\"Aaron Jones\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "15",
		"\"Rec\"": "13",
		"\"Yards\"": "139",
		"\"TD\"": "1",
		"\"YPR\"": "10.7",
		"\"Yd/Tgt\"": "9.3",
		"\"Tgt Shr\"": "\"14%\"",
		"\"AirYards\"": "40",
		"\"AY/Tgt\"": "2.7",
		"\"YAC\"": "116",
		"\"RACR\"": "3.48",
		"\"Team %\"": "\"4%\"",
		"\"WOPR\"": "0.24",
		"\"AirYAC (AY+YAC)\"": "156"
	},
	{
		"\"Player\"": "\"Aaron Shampklin\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Adam Prentice\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Alec Ingold\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "4",
		"\"Rec\"": "4",
		"\"Yards\"": "41",
		"\"TD\"": "0",
		"\"YPR\"": "10.2",
		"\"Yd/Tgt\"": "10.2",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "17",
		"\"AY/Tgt\"": "4.2",
		"\"YAC\"": "24",
		"\"RACR\"": "2.41",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "41"
	},
	{
		"\"Player\"": "\"Alexander Mattison\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "16",
		"\"Rec\"": "13",
		"\"Yards\"": "123",
		"\"TD\"": "0",
		"\"YPR\"": "9.5",
		"\"Yd/Tgt\"": "7.7",
		"\"Tgt Shr\"": "\"9%\"",
		"\"AirYards\"": "5",
		"\"AY/Tgt\"": "0.3",
		"\"YAC\"": "124",
		"\"RACR\"": "24.6",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.14",
		"\"AirYAC (AY+YAC)\"": "129"
	},
	{
		"\"Player\"": "\"Alvin Kamara\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "36",
		"\"Rec\"": "27",
		"\"Yards\"": "160",
		"\"TD\"": "0",
		"\"YPR\"": "5.9",
		"\"Yd/Tgt\"": "4.4",
		"\"Tgt Shr\"": "\"21%\"",
		"\"AirYards\"": "46",
		"\"AY/Tgt\"": "1.3",
		"\"YAC\"": "123",
		"\"RACR\"": "3.48",
		"\"Team %\"": "\"3%\"",
		"\"WOPR\"": "0.35",
		"\"AirYAC (AY+YAC)\"": "169"
	},
	{
		"\"Player\"": "\"Ameer Abdullah\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "10",
		"\"Rec\"": "8",
		"\"Yards\"": "36",
		"\"TD\"": "0",
		"\"YPR\"": "4.5",
		"\"Yd/Tgt\"": "3.6",
		"\"Tgt Shr\"": "\"9%\"",
		"\"AirYards\"": "-22",
		"\"AY/Tgt\"": "-2.2",
		"\"YAC\"": "60",
		"\"RACR\"": "-1.64",
		"\"Team %\"": "\"-3%\"",
		"\"WOPR\"": "0.11",
		"\"AirYAC (AY+YAC)\"": "38"
	},
	{
		"\"Player\"": "\"Andrew Beck\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "1",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "0",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "-6",
		"\"AY/Tgt\"": "-6",
		"\"YAC\"": "0",
		"\"RACR\"": "0",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "-6"
	},
	{
		"\"Player\"": "\"Antonio Gibson\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "13",
		"\"Rec\"": "11",
		"\"Yards\"": "112",
		"\"TD\"": "0",
		"\"YPR\"": "10.2",
		"\"Yd/Tgt\"": "8.6",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "1",
		"\"AY/Tgt\"": "0.1",
		"\"YAC\"": "116",
		"\"RACR\"": "112",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.13",
		"\"AirYAC (AY+YAC)\"": "117"
	},
	{
		"\"Player\"": "\"Audric Estime\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Austin Ekeler\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "11",
		"\"Rec\"": "10",
		"\"Yards\"": "102",
		"\"TD\"": "0",
		"\"YPR\"": "10.2",
		"\"Yd/Tgt\"": "9.3",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "-24",
		"\"AY/Tgt\"": "-2.2",
		"\"YAC\"": "121",
		"\"RACR\"": "-4.25",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.14",
		"\"AirYAC (AY+YAC)\"": "97"
	},
	{
		"\"Player\"": "\"Avery Williams\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Bijan Robinson\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "18",
		"\"Rec\"": "15",
		"\"Yards\"": "133",
		"\"TD\"": "0",
		"\"YPR\"": "8.9",
		"\"Yd/Tgt\"": "7.4",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "-50",
		"\"AY/Tgt\"": "-2.8",
		"\"YAC\"": "187",
		"\"RACR\"": "-2.66",
		"\"Team %\"": "\"-4%\"",
		"\"WOPR\"": "0.12",
		"\"AirYAC (AY+YAC)\"": "137"
	},
	{
		"\"Player\"": "\"Blake Corum\"",
		"\"Team\"": "\"LAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "8",
		"\"TD\"": "0",
		"\"YPR\"": "8",
		"\"Yd/Tgt\"": "8",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "-6",
		"\"AY/Tgt\"": "-6",
		"\"YAC\"": "14",
		"\"RACR\"": "-1.33",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "8"
	},
	{
		"\"Player\"": "\"Blake Watson\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Braelon Allen\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "9",
		"\"Rec\"": "6",
		"\"Yards\"": "42",
		"\"TD\"": "0",
		"\"YPR\"": "7",
		"\"Yd/Tgt\"": "4.7",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "4",
		"\"AY/Tgt\"": "0.4",
		"\"YAC\"": "43",
		"\"RACR\"": "10.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "47"
	},
	{
		"\"Player\"": "\"Breece Hall\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "29",
		"\"Rec\"": "20",
		"\"Yards\"": "216",
		"\"TD\"": "0",
		"\"YPR\"": "10.8",
		"\"Yd/Tgt\"": "7.4",
		"\"Tgt Shr\"": "\"14%\"",
		"\"AirYards\"": "43",
		"\"AY/Tgt\"": "1.5",
		"\"YAC\"": "194",
		"\"RACR\"": "5.02",
		"\"Team %\"": "\"3%\"",
		"\"WOPR\"": "0.24",
		"\"AirYAC (AY+YAC)\"": "237"
	},
	{
		"\"Player\"": "\"Brian Robinson Jr\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "4",
		"\"Rec\"": "4",
		"\"Yards\"": "16",
		"\"TD\"": "0",
		"\"YPR\"": "4",
		"\"Yd/Tgt\"": "4",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-11",
		"\"AY/Tgt\"": "-2.8",
		"\"YAC\"": "27",
		"\"RACR\"": "-1.45",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "16"
	},
	{
		"\"Player\"": "\"British Brooks\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Bucky Irving\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "9",
		"\"Rec\"": "8",
		"\"Yards\"": "56",
		"\"TD\"": "0",
		"\"YPR\"": "7",
		"\"Yd/Tgt\"": "6.2",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "-30",
		"\"AY/Tgt\"": "-3.3",
		"\"YAC\"": "82",
		"\"RACR\"": "-1.87",
		"\"Team %\"": "\"-4%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "52"
	},
	{
		"\"Player\"": "\"CJ Ham\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Cam Akers\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "6",
		"\"Rec\"": "3",
		"\"Yards\"": "13",
		"\"TD\"": "1",
		"\"YPR\"": "4.3",
		"\"Yd/Tgt\"": "2.2",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-6",
		"\"AY/Tgt\"": "-1",
		"\"YAC\"": "10",
		"\"RACR\"": "-2.17",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "4"
	},
	{
		"\"Player\"": "\"Carson Steele\"",
		"\"Team\"": "\"KC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "5",
		"\"Rec\"": "2",
		"\"Yards\"": "2",
		"\"TD\"": "0",
		"\"YPR\"": "1",
		"\"Yd/Tgt\"": "0.4",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-6",
		"\"AY/Tgt\"": "-1.2",
		"\"YAC\"": "11",
		"\"RACR\"": "-0.33",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "5"
	},
	{
		"\"Player\"": "\"Chase Brown\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "14",
		"\"Rec\"": "11",
		"\"Yards\"": "47",
		"\"TD\"": "1",
		"\"YPR\"": "4.3",
		"\"Yd/Tgt\"": "3.4",
		"\"Tgt Shr\"": "\"9%\"",
		"\"AirYards\"": "-15",
		"\"AY/Tgt\"": "-1.1",
		"\"YAC\"": "61",
		"\"RACR\"": "-3.13",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.13",
		"\"AirYAC (AY+YAC)\"": "46"
	},
	{
		"\"Player\"": "\"Chris Brooks\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Chuba Hubbard\"",
		"\"Team\"": "\"CAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "19",
		"\"Rec\"": "18",
		"\"Yards\"": "81",
		"\"TD\"": "1",
		"\"YPR\"": "4.5",
		"\"Yd/Tgt\"": "4.3",
		"\"Tgt Shr\"": "\"12%\"",
		"\"AirYards\"": "-17",
		"\"AY/Tgt\"": "-0.9",
		"\"YAC\"": "98",
		"\"RACR\"": "-4.76",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.16",
		"\"AirYAC (AY+YAC)\"": "81"
	},
	{
		"\"Player\"": "\"Cordarrelle Patterson\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "7",
		"\"Rec\"": "5",
		"\"Yards\"": "34",
		"\"TD\"": "0",
		"\"YPR\"": "6.8",
		"\"Yd/Tgt\"": "4.9",
		"\"Tgt Shr\"": "\"11%\"",
		"\"AirYards\"": "27",
		"\"AY/Tgt\"": "3.9",
		"\"YAC\"": "25",
		"\"RACR\"": "1.26",
		"\"Team %\"": "\"6%\"",
		"\"WOPR\"": "0.21",
		"\"AirYAC (AY+YAC)\"": "52"
	},
	{
		"\"Player\"": "\"Craig Reynolds\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"D'Andre Swift\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "17",
		"\"Rec\"": "15",
		"\"Yards\"": "169",
		"\"TD\"": "0",
		"\"YPR\"": "11.3",
		"\"Yd/Tgt\"": "9.9",
		"\"Tgt Shr\"": "\"14%\"",
		"\"AirYards\"": "-15",
		"\"AY/Tgt\"": "-0.9",
		"\"YAC\"": "183",
		"\"RACR\"": "-11.27",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.2",
		"\"AirYAC (AY+YAC)\"": "168"
	},
	{
		"\"Player\"": "\"D'Ernest Johnson\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "10",
		"\"Rec\"": "7",
		"\"Yards\"": "57",
		"\"TD\"": "0",
		"\"YPR\"": "8.1",
		"\"Yd/Tgt\"": "5.7",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "-16",
		"\"AY/Tgt\"": "-1.6",
		"\"YAC\"": "67",
		"\"RACR\"": "-3.56",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.08",
		"\"AirYAC (AY+YAC)\"": "51"
	},
	{
		"\"Player\"": "\"D'Onta Foreman\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "4",
		"\"Rec\"": "4",
		"\"Yards\"": "37",
		"\"TD\"": "0",
		"\"YPR\"": "9.2",
		"\"Yd/Tgt\"": "9.2",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "-3",
		"\"AY/Tgt\"": "-0.8",
		"\"YAC\"": "40",
		"\"RACR\"": "-12.33",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.03",
		"\"AirYAC (AY+YAC)\"": "37"
	},
	{
		"\"Player\"": "\"Dameon Pierce\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "1",
		"\"TD\"": "0",
		"\"YPR\"": "1",
		"\"Yd/Tgt\"": "1",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "-2",
		"\"AY/Tgt\"": "-2",
		"\"YAC\"": "3",
		"\"RACR\"": "-0.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.03",
		"\"AirYAC (AY+YAC)\"": "1"
	},
	{
		"\"Player\"": "\"Dante Miller\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Dare Ogunbowale\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "14",
		"\"Rec\"": "12",
		"\"Yards\"": "132",
		"\"TD\"": "1",
		"\"YPR\"": "11",
		"\"Yd/Tgt\"": "9.4",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "8",
		"\"AY/Tgt\"": "0.6",
		"\"YAC\"": "124",
		"\"RACR\"": "16.5",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.13",
		"\"AirYAC (AY+YAC)\"": "132"
	},
	{
		"\"Player\"": "\"David Montgomery\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "9",
		"\"Rec\"": "8",
		"\"Yards\"": "96",
		"\"TD\"": "0",
		"\"YPR\"": "12",
		"\"Yd/Tgt\"": "10.7",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "-4",
		"\"AY/Tgt\"": "-0.4",
		"\"YAC\"": "103",
		"\"RACR\"": "-24",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.14",
		"\"AirYAC (AY+YAC)\"": "99"
	},
	{
		"\"Player\"": "\"De'Von Achane\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "12",
		"\"Rec\"": "9",
		"\"Yards\"": "49",
		"\"TD\"": "0",
		"\"YPR\"": "5.4",
		"\"Yd/Tgt\"": "4.1",
		"\"Tgt Shr\"": "\"11%\"",
		"\"AirYards\"": "5",
		"\"AY/Tgt\"": "0.4",
		"\"YAC\"": "46",
		"\"RACR\"": "9.8",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.18",
		"\"AirYAC (AY+YAC)\"": "51"
	},
	{
		"\"Player\"": "\"Derrick Henry\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "5",
		"\"Rec\"": "5",
		"\"Yards\"": "37",
		"\"TD\"": "1",
		"\"YPR\"": "7.4",
		"\"Yd/Tgt\"": "7.4",
		"\"Tgt Shr\"": "\"5%\"",
		"\"AirYards\"": "-9",
		"\"AY/Tgt\"": "-1.8",
		"\"YAC\"": "46",
		"\"RACR\"": "-4.11",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "37"
	},
	{
		"\"Player\"": "\"Deuce Vaughn\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "2",
		"\"Rec\"": "1",
		"\"Yards\"": "8",
		"\"TD\"": "0",
		"\"YPR\"": "8",
		"\"Yd/Tgt\"": "4",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "4",
		"\"AY/Tgt\"": "2",
		"\"YAC\"": "3",
		"\"RACR\"": "2",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "7"
	},
	{
		"\"Player\"": "\"Devin Singletary\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "6",
		"\"Rec\"": "6",
		"\"Yards\"": "60",
		"\"TD\"": "0",
		"\"YPR\"": "10",
		"\"Yd/Tgt\"": "10",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "-28",
		"\"AY/Tgt\"": "-4.7",
		"\"YAC\"": "88",
		"\"RACR\"": "-2.14",
		"\"Team %\"": "\"-3%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "60"
	},
	{
		"\"Player\"": "\"Dylan Laube\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Emanuel Wilson\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "6",
		"\"Rec\"": "4",
		"\"Yards\"": "45",
		"\"TD\"": "1",
		"\"YPR\"": "11.2",
		"\"Yd/Tgt\"": "7.5",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-30",
		"\"AY/Tgt\"": "-5",
		"\"YAC\"": "66",
		"\"RACR\"": "-1.5",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "36"
	},
	{
		"\"Player\"": "\"Emari Demercado\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "9",
		"\"Rec\"": "7",
		"\"Yards\"": "39",
		"\"TD\"": "0",
		"\"YPR\"": "5.6",
		"\"Yd/Tgt\"": "4.3",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "27",
		"\"AY/Tgt\"": "3",
		"\"YAC\"": "18",
		"\"RACR\"": "1.44",
		"\"Team %\"": "\"3%\"",
		"\"WOPR\"": "0.14",
		"\"AirYAC (AY+YAC)\"": "45"
	},
	{
		"\"Player\"": "\"Eric Gray\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "5",
		"\"Rec\"": "4",
		"\"Yards\"": "57",
		"\"TD\"": "0",
		"\"YPR\"": "14.2",
		"\"Yd/Tgt\"": "11.4",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "-18",
		"\"AY/Tgt\"": "-3.6",
		"\"YAC\"": "74",
		"\"RACR\"": "-3.17",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "56"
	},
	{
		"\"Player\"": "\"Ezekiel Elliott\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "4",
		"\"Rec\"": "2",
		"\"Yards\"": "11",
		"\"TD\"": "0",
		"\"YPR\"": "5.5",
		"\"Yd/Tgt\"": "2.8",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "-2",
		"\"AY/Tgt\"": "-0.5",
		"\"YAC\"": "14",
		"\"RACR\"": "-5.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "12"
	},
	{
		"\"Player\"": "\"Gus Edwards\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Hassan Haskins\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Hunter Luepke\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "6",
		"\"Rec\"": "5",
		"\"Yards\"": "73",
		"\"TD\"": "0",
		"\"YPR\"": "14.6",
		"\"Yd/Tgt\"": "12.2",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "28",
		"\"AY/Tgt\"": "4.7",
		"\"YAC\"": "48",
		"\"RACR\"": "2.61",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "76"
	},
	{
		"\"Player\"": "\"Isaac Guerendo\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "5",
		"\"TD\"": "0",
		"\"YPR\"": "5",
		"\"Yd/Tgt\"": "5",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "1",
		"\"AY/Tgt\"": "1",
		"\"YAC\"": "4",
		"\"RACR\"": "5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "5"
	},
	{
		"\"Player\"": "\"Isaiah Davis\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"JJ Taylor\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "3",
		"\"Rec\"": "2",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "0",
		"\"Yd/Tgt\"": "0",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-6",
		"\"AY/Tgt\"": "-2",
		"\"YAC\"": "1",
		"\"RACR\"": "0",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "-5"
	},
	{
		"\"Player\"": "\"JK Dobbins\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "9",
		"\"Rec\"": "8",
		"\"Yards\"": "46",
		"\"TD\"": "0",
		"\"YPR\"": "5.8",
		"\"Yd/Tgt\"": "5.1",
		"\"Tgt Shr\"": "\"12%\"",
		"\"AirYards\"": "10",
		"\"AY/Tgt\"": "1.1",
		"\"YAC\"": "57",
		"\"RACR\"": "4.6",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.18",
		"\"AirYAC (AY+YAC)\"": "67"
	},
	{
		"\"Player\"": "\"JaMycal Hasty\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "9",
		"\"Rec\"": "6",
		"\"Yards\"": "58",
		"\"TD\"": "1",
		"\"YPR\"": "9.7",
		"\"Yd/Tgt\"": "6.4",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "3",
		"\"AY/Tgt\"": "0.3",
		"\"YAC\"": "66",
		"\"RACR\"": "19.33",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.09",
		"\"AirYAC (AY+YAC)\"": "69"
	},
	{
		"\"Player\"": "\"Jahmyr Gibbs\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "9",
		"\"Rec\"": "7",
		"\"Yards\"": "92",
		"\"TD\"": "0",
		"\"YPR\"": "13.1",
		"\"Yd/Tgt\"": "10.2",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "11",
		"\"AY/Tgt\"": "1.2",
		"\"YAC\"": "87",
		"\"RACR\"": "8.36",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.16",
		"\"AirYAC (AY+YAC)\"": "98"
	},
	{
		"\"Player\"": "\"Jakob Johnson\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Jaleel McLaughlin\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "8",
		"\"Rec\"": "7",
		"\"Yards\"": "27",
		"\"TD\"": "1",
		"\"YPR\"": "3.9",
		"\"Yd/Tgt\"": "3.4",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "-35",
		"\"AY/Tgt\"": "-4.4",
		"\"YAC\"": "56",
		"\"RACR\"": "-0.77",
		"\"Team %\"": "\"-3%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "21"
	},
	{
		"\"Player\"": "\"Jamaal Williams\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "5",
		"\"Rec\"": "3",
		"\"Yards\"": "8",
		"\"TD\"": "0",
		"\"YPR\"": "2.7",
		"\"Yd/Tgt\"": "1.6",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "-28",
		"\"AY/Tgt\"": "-5.6",
		"\"YAC\"": "18",
		"\"RACR\"": "-0.29",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.03",
		"\"AirYAC (AY+YAC)\"": "-10"
	},
	{
		"\"Player\"": "\"James Conner\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "10",
		"\"Rec\"": "8",
		"\"Yards\"": "53",
		"\"TD\"": "0",
		"\"YPR\"": "6.6",
		"\"Yd/Tgt\"": "5.3",
		"\"Tgt Shr\"": "\"9%\"",
		"\"AirYards\"": "-24",
		"\"AY/Tgt\"": "-2.4",
		"\"YAC\"": "65",
		"\"RACR\"": "-2.21",
		"\"Team %\"": "\"-3%\"",
		"\"WOPR\"": "0.11",
		"\"AirYAC (AY+YAC)\"": "41"
	},
	{
		"\"Player\"": "\"James Cook\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "9",
		"\"Rec\"": "7",
		"\"Yards\"": "74",
		"\"TD\"": "0",
		"\"YPR\"": "10.6",
		"\"Yd/Tgt\"": "8.2",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "48",
		"\"AY/Tgt\"": "5.3",
		"\"YAC\"": "64",
		"\"RACR\"": "1.54",
		"\"Team %\"": "\"4%\"",
		"\"WOPR\"": "0.12",
		"\"AirYAC (AY+YAC)\"": "112"
	},
	{
		"\"Player\"": "\"Jase McClellan\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Javonte Williams\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "22",
		"\"Rec\"": "17",
		"\"Yards\"": "118",
		"\"TD\"": "0",
		"\"YPR\"": "6.9",
		"\"Yd/Tgt\"": "5.4",
		"\"Tgt Shr\"": "\"15%\"",
		"\"AirYards\"": "2",
		"\"AY/Tgt\"": "0.1",
		"\"YAC\"": "126",
		"\"RACR\"": "59",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.23",
		"\"AirYAC (AY+YAC)\"": "128"
	},
	{
		"\"Player\"": "\"Jaylen Warren\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "7",
		"\"Rec\"": "6",
		"\"Yards\"": "22",
		"\"TD\"": "0",
		"\"YPR\"": "3.7",
		"\"Yd/Tgt\"": "3.1",
		"\"Tgt Shr\"": "\"9%\"",
		"\"AirYards\"": "-3",
		"\"AY/Tgt\"": "-0.4",
		"\"YAC\"": "31",
		"\"RACR\"": "-7.33",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.13",
		"\"AirYAC (AY+YAC)\"": "28"
	},
	{
		"\"Player\"": "\"Jaylen Wright\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "1",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "0",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "-1",
		"\"AY/Tgt\"": "-1",
		"\"YAC\"": "0",
		"\"RACR\"": "0",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "-1"
	},
	{
		"\"Player\"": "\"Jeff Wilson Jr\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Jeremy McNichols\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "6",
		"\"TD\"": "0",
		"\"YPR\"": "6",
		"\"Yd/Tgt\"": "6",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "-3",
		"\"AY/Tgt\"": "-3",
		"\"YAC\"": "9",
		"\"RACR\"": "-2",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "6"
	},
	{
		"\"Player\"": "\"Jerome Ford\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "14",
		"\"Rec\"": "13",
		"\"Yards\"": "62",
		"\"TD\"": "0",
		"\"YPR\"": "4.8",
		"\"Yd/Tgt\"": "4.4",
		"\"Tgt Shr\"": "\"12%\"",
		"\"AirYards\"": "-49",
		"\"AY/Tgt\"": "-3.5",
		"\"YAC\"": "108",
		"\"RACR\"": "-1.27",
		"\"Team %\"": "\"-6%\"",
		"\"WOPR\"": "0.14",
		"\"AirYAC (AY+YAC)\"": "59"
	},
	{
		"\"Player\"": "\"Joe Mixon\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "6",
		"\"Rec\"": "4",
		"\"Yards\"": "39",
		"\"TD\"": "1",
		"\"YPR\"": "9.8",
		"\"Yd/Tgt\"": "6.5",
		"\"Tgt Shr\"": "\"12%\"",
		"\"AirYards\"": "-3",
		"\"AY/Tgt\"": "-0.5",
		"\"YAC\"": "44",
		"\"RACR\"": "-13",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.17",
		"\"AirYAC (AY+YAC)\"": "41"
	},
	{
		"\"Player\"": "\"Jonathan Taylor\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "6",
		"\"Rec\"": "4",
		"\"Yards\"": "45",
		"\"TD\"": "0",
		"\"YPR\"": "11.2",
		"\"Yd/Tgt\"": "7.5",
		"\"Tgt Shr\"": "\"13%\"",
		"\"AirYards\"": "1",
		"\"AY/Tgt\"": "0.2",
		"\"YAC\"": "48",
		"\"RACR\"": "45",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.2",
		"\"AirYAC (AY+YAC)\"": "49"
	},
	{
		"\"Player\"": "\"Jonathan Ward\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Jordan Mason\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "10",
		"\"Rec\"": "8",
		"\"Yards\"": "77",
		"\"TD\"": "0",
		"\"YPR\"": "9.6",
		"\"Yd/Tgt\"": "7.7",
		"\"Tgt Shr\"": "\"7%\"",
		"\"AirYards\"": "41",
		"\"AY/Tgt\"": "4.1",
		"\"YAC\"": "55",
		"\"RACR\"": "1.88",
		"\"Team %\"": "\"3%\"",
		"\"WOPR\"": "0.12",
		"\"AirYAC (AY+YAC)\"": "96"
	},
	{
		"\"Player\"": "\"Jordan Mims\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "4",
		"\"Rec\"": "2",
		"\"Yards\"": "13",
		"\"TD\"": "0",
		"\"YPR\"": "6.5",
		"\"Yd/Tgt\"": "3.2",
		"\"Tgt Shr\"": "\"7%\"",
		"\"AirYards\"": "-9",
		"\"AY/Tgt\"": "-2.2",
		"\"YAC\"": "10",
		"\"RACR\"": "-1.44",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.09",
		"\"AirYAC (AY+YAC)\"": "1"
	},
	{
		"\"Player\"": "\"Josh Jacobs\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "15",
		"\"Rec\"": "14",
		"\"Yards\"": "97",
		"\"TD\"": "1",
		"\"YPR\"": "6.9",
		"\"Yd/Tgt\"": "6.5",
		"\"Tgt Shr\"": "\"9%\"",
		"\"AirYards\"": "-5",
		"\"AY/Tgt\"": "-0.3",
		"\"YAC\"": "121",
		"\"RACR\"": "-19.4",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.14",
		"\"AirYAC (AY+YAC)\"": "116"
	},
	{
		"\"Player\"": "\"Julius Chestnut\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "9",
		"\"TD\"": "0",
		"\"YPR\"": "9",
		"\"Yd/Tgt\"": "9",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "-3",
		"\"AY/Tgt\"": "-3",
		"\"YAC\"": "12",
		"\"RACR\"": "-3",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "9"
	},
	{
		"\"Player\"": "\"Justice Hill\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "12",
		"\"Rec\"": "10",
		"\"Yards\"": "109",
		"\"TD\"": "1",
		"\"YPR\"": "10.9",
		"\"Yd/Tgt\"": "9.1",
		"\"Tgt Shr\"": "\"12%\"",
		"\"AirYards\"": "9",
		"\"AY/Tgt\"": "0.8",
		"\"YAC\"": "104",
		"\"RACR\"": "12.11",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.19",
		"\"AirYAC (AY+YAC)\"": "113"
	},
	{
		"\"Player\"": "\"Kareem Hunt\"",
		"\"Team\"": "\"KC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "7",
		"\"Rec\"": "5",
		"\"Yards\"": "36",
		"\"TD\"": "0",
		"\"YPR\"": "7.2",
		"\"Yd/Tgt\"": "5.1",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "-18",
		"\"AY/Tgt\"": "-2.6",
		"\"YAC\"": "46",
		"\"RACR\"": "-2",
		"\"Team %\"": "\"-3%\"",
		"\"WOPR\"": "0.1",
		"\"AirYAC (AY+YAC)\"": "28"
	},
	{
		"\"Player\"": "\"Kendre Miller\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "3",
		"\"Rec\"": "2",
		"\"Yards\"": "1",
		"\"TD\"": "0",
		"\"YPR\"": "0.5",
		"\"Yd/Tgt\"": "0.3",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "-1",
		"\"AY/Tgt\"": "-0.3",
		"\"YAC\"": "4",
		"\"RACR\"": "-1",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.12",
		"\"AirYAC (AY+YAC)\"": "3"
	},
	{
		"\"Player\"": "\"Kenneth Gainwell\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "6",
		"\"Rec\"": "3",
		"\"Yards\"": "23",
		"\"TD\"": "0",
		"\"YPR\"": "7.7",
		"\"Yd/Tgt\"": "3.8",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "12",
		"\"AY/Tgt\"": "2",
		"\"YAC\"": "12",
		"\"RACR\"": "1.92",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.1",
		"\"AirYAC (AY+YAC)\"": "24"
	},
	{
		"\"Player\"": "\"Kenneth Walker III\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "23",
		"\"Rec\"": "21",
		"\"Yards\"": "154",
		"\"TD\"": "1",
		"\"YPR\"": "7.3",
		"\"Yd/Tgt\"": "6.7",
		"\"Tgt Shr\"": "\"14%\"",
		"\"AirYards\"": "7",
		"\"AY/Tgt\"": "0.3",
		"\"YAC\"": "152",
		"\"RACR\"": "22",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.21",
		"\"AirYAC (AY+YAC)\"": "159"
	},
	{
		"\"Player\"": "\"Kenny McIntosh\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Khalil Herbert\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Khari Blasingame\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Kimani Vidal\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "40",
		"\"TD\"": "1",
		"\"YPR\"": "20",
		"\"Yd/Tgt\"": "20",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "20",
		"\"AY/Tgt\"": "10",
		"\"YAC\"": "20",
		"\"RACR\"": "2",
		"\"Team %\"": "\"7%\"",
		"\"WOPR\"": "0.15",
		"\"AirYAC (AY+YAC)\"": "40"
	},
	{
		"\"Player\"": "\"Kyle Juszczyk\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "9",
		"\"Rec\"": "5",
		"\"Yards\"": "28",
		"\"TD\"": "0",
		"\"YPR\"": "5.6",
		"\"Yd/Tgt\"": "3.1",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "32",
		"\"AY/Tgt\"": "3.6",
		"\"YAC\"": "17",
		"\"RACR\"": "0.88",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.11",
		"\"AirYAC (AY+YAC)\"": "49"
	},
	{
		"\"Player\"": "\"Kyren Williams\"",
		"\"Team\"": "\"LAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "7",
		"\"Rec\"": "7",
		"\"Yards\"": "40",
		"\"TD\"": "1",
		"\"YPR\"": "5.7",
		"\"Yd/Tgt\"": "5.7",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "-2",
		"\"AY/Tgt\"": "-0.3",
		"\"YAC\"": "42",
		"\"RACR\"": "-20",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.09",
		"\"AirYAC (AY+YAC)\"": "40"
	},
	{
		"\"Player\"": "\"Michael Burton\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "8",
		"\"TD\"": "0",
		"\"YPR\"": "4",
		"\"Yd/Tgt\"": "4",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "0",
		"\"RACR\"": "Inf",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Miles Sanders\"",
		"\"Team\"": "\"CAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "12",
		"\"Rec\"": "9",
		"\"Yards\"": "60",
		"\"TD\"": "0",
		"\"YPR\"": "6.7",
		"\"Yd/Tgt\"": "5",
		"\"Tgt Shr\"": "\"7%\"",
		"\"AirYards\"": "-8",
		"\"AY/Tgt\"": "-0.7",
		"\"YAC\"": "65",
		"\"RACR\"": "-7.5",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.11",
		"\"AirYAC (AY+YAC)\"": "57"
	},
	{
		"\"Player\"": "\"Myles Gaskin\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "11",
		"\"TD\"": "0",
		"\"YPR\"": "11",
		"\"Yd/Tgt\"": "11",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-2",
		"\"AY/Tgt\"": "-2",
		"\"YAC\"": "13",
		"\"RACR\"": "-5.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "11"
	},
	{
		"\"Player\"": "\"Najee Harris\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "16",
		"\"Rec\"": "12",
		"\"Yards\"": "121",
		"\"TD\"": "0",
		"\"YPR\"": "10.1",
		"\"Yd/Tgt\"": "7.6",
		"\"Tgt Shr\"": "\"12%\"",
		"\"AirYards\"": "-13",
		"\"AY/Tgt\"": "-0.8",
		"\"YAC\"": "121",
		"\"RACR\"": "-9.31",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.17",
		"\"AirYAC (AY+YAC)\"": "108"
	},
	{
		"\"Player\"": "\"Nick Chubb\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "3",
		"\"Rec\"": "1",
		"\"Yards\"": "10",
		"\"TD\"": "0",
		"\"YPR\"": "10",
		"\"Yd/Tgt\"": "3.3",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "10",
		"\"AY/Tgt\"": "3.3",
		"\"YAC\"": "5",
		"\"RACR\"": "1",
		"\"Team %\"": "\"3%\"",
		"\"WOPR\"": "0.11",
		"\"AirYAC (AY+YAC)\"": "15"
	},
	{
		"\"Player\"": "\"Patrick Ricard\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Patrick Taylor\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "12",
		"\"TD\"": "0",
		"\"YPR\"": "12",
		"\"Yd/Tgt\"": "12",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "3",
		"\"AY/Tgt\"": "3",
		"\"YAC\"": "9",
		"\"RACR\"": "4",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "12"
	},
	{
		"\"Player\"": "\"Pierre Strong Jr\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "7",
		"\"Rec\"": "3",
		"\"Yards\"": "44",
		"\"TD\"": "0",
		"\"YPR\"": "14.7",
		"\"Yd/Tgt\"": "6.3",
		"\"Tgt Shr\"": "\"7%\"",
		"\"AirYards\"": "-7",
		"\"AY/Tgt\"": "-1",
		"\"YAC\"": "58",
		"\"RACR\"": "-6.29",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.1",
		"\"AirYAC (AY+YAC)\"": "51"
	},
	{
		"\"Player\"": "\"Rachaad White\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "12",
		"\"Rec\"": "10",
		"\"Yards\"": "47",
		"\"TD\"": "0",
		"\"YPR\"": "4.7",
		"\"Yd/Tgt\"": "3.9",
		"\"Tgt Shr\"": "\"12%\"",
		"\"AirYards\"": "-35",
		"\"AY/Tgt\"": "-2.9",
		"\"YAC\"": "74",
		"\"RACR\"": "-1.34",
		"\"Team %\"": "\"-6%\"",
		"\"WOPR\"": "0.13",
		"\"AirYAC (AY+YAC)\"": "39"
	},
	{
		"\"Player\"": "\"Raheem Blackshear\"",
		"\"Team\"": "\"CAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Raheem Mostert\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "18",
		"\"TD\"": "0",
		"\"YPR\"": "9",
		"\"Yd/Tgt\"": "9",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "1",
		"\"AY/Tgt\"": "0.5",
		"\"YAC\"": "17",
		"\"RACR\"": "18",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "18"
	},
	{
		"\"Player\"": "\"Ray Davis\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "7",
		"\"Rec\"": "6",
		"\"Yards\"": "66",
		"\"TD\"": "0",
		"\"YPR\"": "11",
		"\"Yd/Tgt\"": "9.4",
		"\"Tgt Shr\"": "\"5%\"",
		"\"AirYards\"": "26",
		"\"AY/Tgt\"": "3.7",
		"\"YAC\"": "34",
		"\"RACR\"": "2.54",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.09",
		"\"AirYAC (AY+YAC)\"": "60"
	},
	{
		"\"Player\"": "\"Reggie Gilliam\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Rhamondre Stevenson\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "12",
		"\"Rec\"": "10",
		"\"Yards\"": "34",
		"\"TD\"": "0",
		"\"YPR\"": "3.4",
		"\"Yd/Tgt\"": "2.8",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "-30",
		"\"AY/Tgt\"": "-2.5",
		"\"YAC\"": "57",
		"\"RACR\"": "-1.13",
		"\"Team %\"": "\"-3%\"",
		"\"WOPR\"": "0.12",
		"\"AirYAC (AY+YAC)\"": "27"
	},
	{
		"\"Player\"": "\"Rico Dowdle\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "14",
		"\"Rec\"": "11",
		"\"Yards\"": "96",
		"\"TD\"": "2",
		"\"YPR\"": "8.7",
		"\"Yd/Tgt\"": "6.9",
		"\"Tgt Shr\"": "\"9%\"",
		"\"AirYards\"": "22",
		"\"AY/Tgt\"": "1.6",
		"\"YAC\"": "81",
		"\"RACR\"": "4.36",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.14",
		"\"AirYAC (AY+YAC)\"": "103"
	},
	{
		"\"Player\"": "\"Ronnie Rivers\"",
		"\"Team\"": "\"LAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Roschon Johnson\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "8",
		"\"Rec\"": "6",
		"\"Yards\"": "57",
		"\"TD\"": "0",
		"\"YPR\"": "9.5",
		"\"Yd/Tgt\"": "7.1",
		"\"Tgt Shr\"": "\"7%\"",
		"\"AirYards\"": "4",
		"\"AY/Tgt\"": "0.5",
		"\"YAC\"": "47",
		"\"RACR\"": "14.25",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.1",
		"\"AirYAC (AY+YAC)\"": "51"
	},
	{
		"\"Player\"": "\"Samaje Perine\"",
		"\"Team\"": "\"KC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "8",
		"\"Rec\"": "5",
		"\"Yards\"": "61",
		"\"TD\"": "0",
		"\"YPR\"": "12.2",
		"\"Yd/Tgt\"": "7.6",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "5",
		"\"AY/Tgt\"": "0.6",
		"\"YAC\"": "49",
		"\"RACR\"": "12.2",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.1",
		"\"AirYAC (AY+YAC)\"": "54"
	},
	{
		"\"Player\"": "\"Saquon Barkley\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "13",
		"\"Rec\"": "10",
		"\"Yards\"": "59",
		"\"TD\"": "0",
		"\"YPR\"": "5.9",
		"\"Yd/Tgt\"": "4.5",
		"\"Tgt Shr\"": "\"13%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "76",
		"\"RACR\"": "Inf",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.19",
		"\"AirYAC (AY+YAC)\"": "76"
	},
	{
		"\"Player\"": "\"Scott Matlock\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "7",
		"\"TD\"": "0",
		"\"YPR\"": "7",
		"\"Yd/Tgt\"": "7",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "2",
		"\"AY/Tgt\"": "2",
		"\"YAC\"": "5",
		"\"RACR\"": "3.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "7"
	},
	{
		"\"Player\"": "\"Sean Tucker\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "4",
		"\"Rec\"": "4",
		"\"Yards\"": "70",
		"\"TD\"": "1",
		"\"YPR\"": "17.5",
		"\"Yd/Tgt\"": "17.5",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "4",
		"\"AY/Tgt\"": "1",
		"\"YAC\"": "66",
		"\"RACR\"": "17.5",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "70"
	},
	{
		"\"Player\"": "\"Sione Vaki\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Tank Bigsby\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "2",
		"\"Rec\"": "1",
		"\"Yards\"": "28",
		"\"TD\"": "0",
		"\"YPR\"": "28",
		"\"Yd/Tgt\"": "14",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "-5",
		"\"AY/Tgt\"": "-2.5",
		"\"YAC\"": "31",
		"\"RACR\"": "-5.6",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "26"
	},
	{
		"\"Player\"": "\"Terrell Jennings\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Tony Pollard\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "14",
		"\"Rec\"": "10",
		"\"Yards\"": "34",
		"\"TD\"": "0",
		"\"YPR\"": "3.4",
		"\"Yd/Tgt\"": "2.4",
		"\"Tgt Shr\"": "\"12%\"",
		"\"AirYards\"": "-34",
		"\"AY/Tgt\"": "-2.4",
		"\"YAC\"": "50",
		"\"RACR\"": "-1",
		"\"Team %\"": "\"-4%\"",
		"\"WOPR\"": "0.15",
		"\"AirYAC (AY+YAC)\"": "16"
	},
	{
		"\"Player\"": "\"Travis Etienne\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "16",
		"\"Rec\"": "11",
		"\"Yards\"": "70",
		"\"TD\"": "0",
		"\"YPR\"": "6.4",
		"\"Yd/Tgt\"": "4.4",
		"\"Tgt Shr\"": "\"11%\"",
		"\"AirYards\"": "27",
		"\"AY/Tgt\"": "1.7",
		"\"YAC\"": "76",
		"\"RACR\"": "2.59",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.18",
		"\"AirYAC (AY+YAC)\"": "103"
	},
	{
		"\"Player\"": "\"Trey Benson\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Trey Sermon\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "7",
		"\"Rec\"": "7",
		"\"Yards\"": "38",
		"\"TD\"": "0",
		"\"YPR\"": "5.4",
		"\"Yd/Tgt\"": "5.4",
		"\"Tgt Shr\"": "\"5%\"",
		"\"AirYards\"": "-15",
		"\"AY/Tgt\"": "-2.1",
		"\"YAC\"": "53",
		"\"RACR\"": "-2.53",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "38"
	},
	{
		"\"Player\"": "\"Ty Chandler\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "3",
		"\"Rec\"": "3",
		"\"Yards\"": "17",
		"\"TD\"": "0",
		"\"YPR\"": "5.7",
		"\"Yd/Tgt\"": "5.7",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "-8",
		"\"AY/Tgt\"": "-2.7",
		"\"YAC\"": "25",
		"\"RACR\"": "-2.12",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "17"
	},
	{
		"\"Player\"": "\"Ty Johnson\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "4",
		"\"Rec\"": "4",
		"\"Yards\"": "32",
		"\"TD\"": "2",
		"\"YPR\"": "8",
		"\"Yd/Tgt\"": "8",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "27",
		"\"AY/Tgt\"": "6.8",
		"\"YAC\"": "5",
		"\"RACR\"": "1.19",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "32"
	},
	{
		"\"Player\"": "\"Tyjae Spears\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "6",
		"\"Rec\"": "6",
		"\"Yards\"": "54",
		"\"TD\"": "0",
		"\"YPR\"": "9",
		"\"Yd/Tgt\"": "9",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "-14",
		"\"AY/Tgt\"": "-2.3",
		"\"YAC\"": "68",
		"\"RACR\"": "-3.86",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.1",
		"\"AirYAC (AY+YAC)\"": "54"
	},
	{
		"\"Player\"": "\"Tyler Allgeier\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "7",
		"\"Rec\"": "7",
		"\"Yards\"": "45",
		"\"TD\"": "0",
		"\"YPR\"": "6.4",
		"\"Yd/Tgt\"": "6.4",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-2",
		"\"AY/Tgt\"": "-0.3",
		"\"YAC\"": "47",
		"\"RACR\"": "-22.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "45"
	},
	{
		"\"Player\"": "\"Tyler Badie\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "-4",
		"\"TD\"": "0",
		"\"YPR\"": "-2",
		"\"Yd/Tgt\"": "-2",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "-8",
		"\"AY/Tgt\"": "-4",
		"\"YAC\"": "4",
		"\"RACR\"": "0.5",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "-4"
	},
	{
		"\"Player\"": "\"Tyler Goodson\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "8",
		"\"Rec\"": "7",
		"\"Yards\"": "45",
		"\"TD\"": "0",
		"\"YPR\"": "6.4",
		"\"Yd/Tgt\"": "5.6",
		"\"Tgt Shr\"": "\"5%\"",
		"\"AirYards\"": "-20",
		"\"AY/Tgt\"": "-2.5",
		"\"YAC\"": "61",
		"\"RACR\"": "-2.25",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "41"
	},
	{
		"\"Player\"": "\"Tyrone Tracy Jr\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "14",
		"\"Rec\"": "13",
		"\"Yards\"": "103",
		"\"TD\"": "0",
		"\"YPR\"": "7.9",
		"\"Yd/Tgt\"": "7.4",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "0",
		"\"RACR\"": "Inf",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.13",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Will Shipley\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Zach Charbonnet\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "16",
		"\"Rec\"": "13",
		"\"Yards\"": "84",
		"\"TD\"": "0",
		"\"YPR\"": "6.5",
		"\"Yd/Tgt\"": "5.2",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "-24",
		"\"AY/Tgt\"": "-1.5",
		"\"YAC\"": "81",
		"\"RACR\"": "-3.5",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.11",
		"\"AirYAC (AY+YAC)\"": "57"
	},
	{
		"\"Player\"": "\"Zack Moss\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "18",
		"\"Rec\"": "16",
		"\"Yards\"": "129",
		"\"TD\"": "1",
		"\"YPR\"": "8.1",
		"\"Yd/Tgt\"": "7.2",
		"\"Tgt Shr\"": "\"12%\"",
		"\"AirYards\"": "-1",
		"\"AY/Tgt\"": "-0.1",
		"\"YAC\"": "138",
		"\"RACR\"": "-129",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.17",
		"\"AirYAC (AY+YAC)\"": "137"
	},
	{
		"\"Player\"": "\"Zamir White\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "2",
		"\"Rec\"": "1",
		"\"Yards\"": "14",
		"\"TD\"": "0",
		"\"YPR\"": "14",
		"\"Yd/Tgt\"": "7",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "-11",
		"\"AY/Tgt\"": "-5.5",
		"\"YAC\"": "20",
		"\"RACR\"": "-1.27",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "9"
	},
	
]

module.exports = rbRvWeeklyStatExplorerRecievingTabLastFiveWeeks;
