const rbRvWeeklyStatExplorerRecievingTabLastFiveWeeks = [
	{
		"\"Player\"": "\"Aaron Jones\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "11",
		"\"Rec\"": "9",
		"\"Yards\"": "44",
		"\"TD\"": "1",
		"\"YPR\"": "4.9",
		"\"Yd/Tgt\"": "4",
		"\"Tgt Shr\"": "\"9%\"",
		"\"AirYards\"": "-2",
		"\"AY/Tgt\"": "-0.2",
		"\"YAC\"": "52",
		"\"RACR\"": "-22",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.14",
		"\"AirYAC (AY+YAC)\"": "50"
	},
	{
		"\"Player\"": "\"Adam Prentice\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Alec Ingold\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "15",
		"\"TD\"": "0",
		"\"YPR\"": "7.5",
		"\"Yd/Tgt\"": "7.5",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "2",
		"\"AY/Tgt\"": "1",
		"\"YAC\"": "13",
		"\"RACR\"": "7.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "15"
	},
	{
		"\"Player\"": "\"Alexander Mattison\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "3",
		"\"Rec\"": "3",
		"\"Yards\"": "50",
		"\"TD\"": "0",
		"\"YPR\"": "16.7",
		"\"Yd/Tgt\"": "16.7",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "-4",
		"\"AY/Tgt\"": "-1.3",
		"\"YAC\"": "54",
		"\"RACR\"": "-12.5",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.1",
		"\"AirYAC (AY+YAC)\"": "50"
	},
	{
		"\"Player\"": "\"Alvin Kamara\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "20",
		"\"Rec\"": "17",
		"\"Yards\"": "122",
		"\"TD\"": "1",
		"\"YPR\"": "7.2",
		"\"Yd/Tgt\"": "6.1",
		"\"Tgt Shr\"": "\"16%\"",
		"\"AirYards\"": "30",
		"\"AY/Tgt\"": "1.5",
		"\"YAC\"": "116",
		"\"RACR\"": "4.07",
		"\"Team %\"": "\"3%\"",
		"\"WOPR\"": "0.27",
		"\"AirYAC (AY+YAC)\"": "146"
	},
	{
		"\"Player\"": "\"Ameer Abdullah\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "13",
		"\"Rec\"": "11",
		"\"Yards\"": "64",
		"\"TD\"": "2",
		"\"YPR\"": "5.8",
		"\"Yd/Tgt\"": "4.9",
		"\"Tgt Shr\"": "\"9%\"",
		"\"AirYards\"": "6",
		"\"AY/Tgt\"": "0.5",
		"\"YAC\"": "68",
		"\"RACR\"": "10.67",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.13",
		"\"AirYAC (AY+YAC)\"": "74"
	},
	{
		"\"Player\"": "\"Antonio Gibson\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "5",
		"\"Rec\"": "4",
		"\"Yards\"": "47",
		"\"TD\"": "0",
		"\"YPR\"": "11.8",
		"\"Yd/Tgt\"": "9.4",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-4",
		"\"AY/Tgt\"": "-0.8",
		"\"YAC\"": "51",
		"\"RACR\"": "-11.75",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "47"
	},
	{
		"\"Player\"": "\"Audric Estime\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "4",
		"\"Rec\"": "4",
		"\"Yards\"": "14",
		"\"TD\"": "0",
		"\"YPR\"": "3.5",
		"\"Yd/Tgt\"": "3.5",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "0",
		"\"RACR\"": "Inf",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Austin Ekeler\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "12",
		"\"Rec\"": "10",
		"\"Yards\"": "91",
		"\"TD\"": "0",
		"\"YPR\"": "9.1",
		"\"Yd/Tgt\"": "7.6",
		"\"Tgt Shr\"": "\"18%\"",
		"\"AirYards\"": "-20",
		"\"AY/Tgt\"": "-1.7",
		"\"YAC\"": "110",
		"\"RACR\"": "-4.55",
		"\"Team %\"": "\"-4%\"",
		"\"WOPR\"": "0.24",
		"\"AirYAC (AY+YAC)\"": "90"
	},
	{
		"\"Player\"": "\"Bijan Robinson\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "12",
		"\"Rec\"": "12",
		"\"Yards\"": "70",
		"\"TD\"": "0",
		"\"YPR\"": "5.8",
		"\"Yd/Tgt\"": "5.8",
		"\"Tgt Shr\"": "\"11%\"",
		"\"AirYards\"": "-9",
		"\"AY/Tgt\"": "-0.8",
		"\"YAC\"": "79",
		"\"RACR\"": "-7.78",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.16",
		"\"AirYAC (AY+YAC)\"": "70"
	},
	{
		"\"Player\"": "\"Blake Corum\"",
		"\"Team\"": "\"LAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "4",
		"\"Rec\"": "3",
		"\"Yards\"": "22",
		"\"TD\"": "0",
		"\"YPR\"": "7.3",
		"\"Yd/Tgt\"": "5.5",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "1",
		"\"AY/Tgt\"": "0.2",
		"\"YAC\"": "23",
		"\"RACR\"": "22",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "24"
	},
	{
		"\"Player\"": "\"Braelon Allen\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "7",
		"\"Rec\"": "6",
		"\"Yards\"": "54",
		"\"TD\"": "0",
		"\"YPR\"": "9",
		"\"Yd/Tgt\"": "7.7",
		"\"Tgt Shr\"": "\"5%\"",
		"\"AirYards\"": "-10",
		"\"AY/Tgt\"": "-1.4",
		"\"YAC\"": "64",
		"\"RACR\"": "-5.4",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "54"
	},
	{
		"\"Player\"": "\"Breece Hall\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "10",
		"\"Rec\"": "9",
		"\"Yards\"": "64",
		"\"TD\"": "1",
		"\"YPR\"": "7.1",
		"\"Yd/Tgt\"": "6.4",
		"\"Tgt Shr\"": "\"11%\"",
		"\"AirYards\"": "2",
		"\"AY/Tgt\"": "0.2",
		"\"YAC\"": "66",
		"\"RACR\"": "32",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.16",
		"\"AirYAC (AY+YAC)\"": "68"
	},
	{
		"\"Player\"": "\"Brian Robinson Jr\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "7",
		"\"Rec\"": "6",
		"\"Yards\"": "48",
		"\"TD\"": "0",
		"\"YPR\"": "8",
		"\"Yd/Tgt\"": "6.9",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "-3",
		"\"AY/Tgt\"": "-0.4",
		"\"YAC\"": "47",
		"\"RACR\"": "-16",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.08",
		"\"AirYAC (AY+YAC)\"": "44"
	},
	{
		"\"Player\"": "\"Bucky Irving\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "12",
		"\"Rec\"": "12",
		"\"Yards\"": "108",
		"\"TD\"": "0",
		"\"YPR\"": "9",
		"\"Yd/Tgt\"": "9",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "-35",
		"\"AY/Tgt\"": "-2.9",
		"\"YAC\"": "143",
		"\"RACR\"": "-3.09",
		"\"Team %\"": "\"-4%\"",
		"\"WOPR\"": "0.13",
		"\"AirYAC (AY+YAC)\"": "108"
	},
	{
		"\"Player\"": "\"CJ Ham\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "1",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "0",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "-5",
		"\"AY/Tgt\"": "-5",
		"\"YAC\"": "0",
		"\"RACR\"": "0",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "-5"
	},
	{
		"\"Player\"": "\"Cam Akers\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "3",
		"\"Rec\"": "3",
		"\"Yards\"": "17",
		"\"TD\"": "1",
		"\"YPR\"": "5.7",
		"\"Yd/Tgt\"": "5.7",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "1",
		"\"AY/Tgt\"": "0.3",
		"\"YAC\"": "16",
		"\"RACR\"": "17",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "17"
	},
	{
		"\"Player\"": "\"Carson Steele\"",
		"\"Team\"": "\"KC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "3",
		"\"Rec\"": "2",
		"\"Yards\"": "14",
		"\"TD\"": "0",
		"\"YPR\"": "7",
		"\"Yd/Tgt\"": "4.7",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "-5",
		"\"AY/Tgt\"": "-1.7",
		"\"YAC\"": "16",
		"\"RACR\"": "-2.8",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.03",
		"\"AirYAC (AY+YAC)\"": "11"
	},
	{
		"\"Player\"": "\"Chase Brown\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "21",
		"\"Rec\"": "17",
		"\"Yards\"": "168",
		"\"TD\"": "2",
		"\"YPR\"": "9.9",
		"\"Yd/Tgt\"": "8",
		"\"Tgt Shr\"": "\"13%\"",
		"\"AirYards\"": "54",
		"\"AY/Tgt\"": "2.6",
		"\"YAC\"": "140",
		"\"RACR\"": "3.11",
		"\"Team %\"": "\"4%\"",
		"\"WOPR\"": "0.23",
		"\"AirYAC (AY+YAC)\"": "194"
	},
	{
		"\"Player\"": "\"Chris Brooks\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "6",
		"\"Rec\"": "6",
		"\"Yards\"": "38",
		"\"TD\"": "0",
		"\"YPR\"": "6.3",
		"\"Yd/Tgt\"": "6.3",
		"\"Tgt Shr\"": "\"5%\"",
		"\"AirYards\"": "-24",
		"\"AY/Tgt\"": "-4",
		"\"YAC\"": "62",
		"\"RACR\"": "-1.58",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "38"
	},
	{
		"\"Player\"": "\"Chris Rodriguez Jr\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Christian McCaffrey\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "12",
		"\"Rec\"": "9",
		"\"Yards\"": "78",
		"\"TD\"": "0",
		"\"YPR\"": "8.7",
		"\"Yd/Tgt\"": "6.5",
		"\"Tgt Shr\"": "\"17%\"",
		"\"AirYards\"": "23",
		"\"AY/Tgt\"": "1.9",
		"\"YAC\"": "67",
		"\"RACR\"": "3.39",
		"\"Team %\"": "\"5%\"",
		"\"WOPR\"": "0.29",
		"\"AirYAC (AY+YAC)\"": "90"
	},
	{
		"\"Player\"": "\"Chuba Hubbard\"",
		"\"Team\"": "\"CAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "15",
		"\"Rec\"": "9",
		"\"Yards\"": "34",
		"\"TD\"": "0",
		"\"YPR\"": "3.8",
		"\"Yd/Tgt\"": "2.3",
		"\"Tgt Shr\"": "\"11%\"",
		"\"AirYards\"": "2",
		"\"AY/Tgt\"": "0.1",
		"\"YAC\"": "47",
		"\"RACR\"": "17",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.17",
		"\"AirYAC (AY+YAC)\"": "49"
	},
	{
		"\"Player\"": "\"Cordarrelle Patterson\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "6",
		"\"Rec\"": "6",
		"\"Yards\"": "34",
		"\"TD\"": "0",
		"\"YPR\"": "5.7",
		"\"Yd/Tgt\"": "5.7",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "3",
		"\"AY/Tgt\"": "0.5",
		"\"YAC\"": "31",
		"\"RACR\"": "11.33",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "34"
	},
	{
		"\"Player\"": "\"Craig Reynolds\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"D'Andre Swift\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "11",
		"\"Rec\"": "8",
		"\"Yards\"": "85",
		"\"TD\"": "0",
		"\"YPR\"": "10.6",
		"\"Yd/Tgt\"": "7.7",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "22",
		"\"AY/Tgt\"": "2",
		"\"YAC\"": "75",
		"\"RACR\"": "3.86",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.13",
		"\"AirYAC (AY+YAC)\"": "97"
	},
	{
		"\"Player\"": "\"D'Ernest Johnson\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Dameon Pierce\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "1",
		"\"TD\"": "0",
		"\"YPR\"": "1",
		"\"Yd/Tgt\"": "1",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "-1",
		"\"AY/Tgt\"": "-1",
		"\"YAC\"": "2",
		"\"RACR\"": "-1",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "1"
	},
	{
		"\"Player\"": "\"Dare Ogunbowale\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "11",
		"\"TD\"": "0",
		"\"YPR\"": "11",
		"\"Yd/Tgt\"": "11",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "-3",
		"\"AY/Tgt\"": "-3",
		"\"YAC\"": "14",
		"\"RACR\"": "-3.67",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "11"
	},
	{
		"\"Player\"": "\"Darrynton Evans\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"David Montgomery\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "18",
		"\"Rec\"": "18",
		"\"Yards\"": "156",
		"\"TD\"": "0",
		"\"YPR\"": "8.7",
		"\"Yd/Tgt\"": "8.7",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "-18",
		"\"AY/Tgt\"": "-1",
		"\"YAC\"": "174",
		"\"RACR\"": "-8.67",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.13",
		"\"AirYAC (AY+YAC)\"": "156"
	},
	{
		"\"Player\"": "\"De'Von Achane\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "31",
		"\"Rec\"": "28",
		"\"Yards\"": "192",
		"\"TD\"": "3",
		"\"YPR\"": "6.9",
		"\"Yd/Tgt\"": "6.2",
		"\"Tgt Shr\"": "\"15%\"",
		"\"AirYards\"": "-3",
		"\"AY/Tgt\"": "-0.1",
		"\"YAC\"": "233",
		"\"RACR\"": "-64",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.23",
		"\"AirYAC (AY+YAC)\"": "230"
	},
	{
		"\"Player\"": "\"DeeJay Dallas\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Derrick Henry\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "3",
		"\"Rec\"": "3",
		"\"Yards\"": "29",
		"\"TD\"": "0",
		"\"YPR\"": "9.7",
		"\"Yd/Tgt\"": "9.7",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "3",
		"\"AY/Tgt\"": "1",
		"\"YAC\"": "26",
		"\"RACR\"": "9.67",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "29"
	},
	{
		"\"Player\"": "\"Deuce Vaughn\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "2",
		"\"Rec\"": "1",
		"\"Yards\"": "4",
		"\"TD\"": "0",
		"\"YPR\"": "4",
		"\"Yd/Tgt\"": "2",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-2",
		"\"AY/Tgt\"": "-1",
		"\"YAC\"": "2",
		"\"RACR\"": "-2",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Devin Singletary\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "6",
		"\"Rec\"": "5",
		"\"Yards\"": "23",
		"\"TD\"": "0",
		"\"YPR\"": "4.6",
		"\"Yd/Tgt\"": "3.8",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-25",
		"\"AY/Tgt\"": "-4.2",
		"\"YAC\"": "31",
		"\"RACR\"": "-0.92",
		"\"Team %\"": "\"-3%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "6"
	},
	{
		"\"Player\"": "\"Emanuel Wilson\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Emari Demercado\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "6",
		"\"Rec\"": "5",
		"\"Yards\"": "18",
		"\"TD\"": "0",
		"\"YPR\"": "3.6",
		"\"Yd/Tgt\"": "3",
		"\"Tgt Shr\"": "\"5%\"",
		"\"AirYards\"": "-12",
		"\"AY/Tgt\"": "-2",
		"\"YAC\"": "24",
		"\"RACR\"": "-1.5",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "12"
	},
	{
		"\"Player\"": "\"Eric Gray\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "7",
		"\"TD\"": "0",
		"\"YPR\"": "3.5",
		"\"Yd/Tgt\"": "3.5",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "7",
		"\"RACR\"": "Inf",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "7"
	},
	{
		"\"Player\"": "\"Ezekiel Elliott\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "5",
		"\"Rec\"": "5",
		"\"Yards\"": "29",
		"\"TD\"": "0",
		"\"YPR\"": "5.8",
		"\"Yd/Tgt\"": "5.8",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "-5",
		"\"AY/Tgt\"": "-1",
		"\"YAC\"": "34",
		"\"RACR\"": "-5.8",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "29"
	},
	{
		"\"Player\"": "\"George Holani\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "-1",
		"\"TD\"": "0",
		"\"YPR\"": "-1",
		"\"Yd/Tgt\"": "-1",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "-1",
		"\"AY/Tgt\"": "-1",
		"\"YAC\"": "0",
		"\"RACR\"": "1",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "-1"
	},
	{
		"\"Player\"": "\"Gus Edwards\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "2",
		"\"Rec\"": "1",
		"\"Yards\"": "1",
		"\"TD\"": "0",
		"\"YPR\"": "1",
		"\"Yd/Tgt\"": "0.5",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "-4",
		"\"AY/Tgt\"": "-2",
		"\"YAC\"": "0",
		"\"RACR\"": "-0.25",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "-4"
	},
	{
		"\"Player\"": "\"Hassan Haskins\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Hunter Luepke\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "15",
		"\"TD\"": "0",
		"\"YPR\"": "7.5",
		"\"Yd/Tgt\"": "7.5",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "4",
		"\"AY/Tgt\"": "2",
		"\"YAC\"": "11",
		"\"RACR\"": "3.75",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.03",
		"\"AirYAC (AY+YAC)\"": "15"
	},
	{
		"\"Player\"": "\"Isaac Guerendo\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "7",
		"\"Rec\"": "7",
		"\"Yards\"": "65",
		"\"TD\"": "0",
		"\"YPR\"": "9.3",
		"\"Yd/Tgt\"": "9.3",
		"\"Tgt Shr\"": "\"7%\"",
		"\"AirYards\"": "18",
		"\"AY/Tgt\"": "2.6",
		"\"YAC\"": "47",
		"\"RACR\"": "3.61",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.12",
		"\"AirYAC (AY+YAC)\"": "65"
	},
	{
		"\"Player\"": "\"Isaiah Davis\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "10",
		"\"Rec\"": "7",
		"\"Yards\"": "57",
		"\"TD\"": "1",
		"\"YPR\"": "8.1",
		"\"Yd/Tgt\"": "5.7",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "18",
		"\"AY/Tgt\"": "1.8",
		"\"YAC\"": "55",
		"\"RACR\"": "3.17",
		"\"Team %\"": "\"2%\"",
		"\"WOPR\"": "0.16",
		"\"AirYAC (AY+YAC)\"": "73"
	},
	{
		"\"Player\"": "\"Isiah Pacheco\"",
		"\"Team\"": "\"KC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "6",
		"\"Rec\"": "4",
		"\"Yards\"": "26",
		"\"TD\"": "0",
		"\"YPR\"": "6.5",
		"\"Yd/Tgt\"": "4.3",
		"\"Tgt Shr\"": "\"5%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "33",
		"\"RACR\"": "Inf",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.08",
		"\"AirYAC (AY+YAC)\"": "33"
	},
	{
		"\"Player\"": "\"JK Dobbins\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "6",
		"\"Rec\"": "4",
		"\"Yards\"": "22",
		"\"TD\"": "0",
		"\"YPR\"": "5.5",
		"\"Yd/Tgt\"": "3.7",
		"\"Tgt Shr\"": "\"9%\"",
		"\"AirYards\"": "-2",
		"\"AY/Tgt\"": "-0.3",
		"\"YAC\"": "21",
		"\"RACR\"": "-11",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.13",
		"\"AirYAC (AY+YAC)\"": "19"
	},
	{
		"\"Player\"": "\"JaMycal Hasty\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "0",
		"\"Yd/Tgt\"": "0",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "-1",
		"\"AY/Tgt\"": "-0.5",
		"\"YAC\"": "1",
		"\"RACR\"": "0",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.03",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Jahmyr Gibbs\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "21",
		"\"Rec\"": "17",
		"\"Yards\"": "99",
		"\"TD\"": "2",
		"\"YPR\"": "5.8",
		"\"Yd/Tgt\"": "4.7",
		"\"Tgt Shr\"": "\"11%\"",
		"\"AirYards\"": "2",
		"\"AY/Tgt\"": "0.1",
		"\"YAC\"": "186",
		"\"RACR\"": "49.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.17",
		"\"AirYAC (AY+YAC)\"": "188"
	},
	{
		"\"Player\"": "\"Jaleel McLaughlin\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "6",
		"\"Rec\"": "4",
		"\"Yards\"": "13",
		"\"TD\"": "0",
		"\"YPR\"": "3.2",
		"\"Yd/Tgt\"": "2.2",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-29",
		"\"AY/Tgt\"": "-4.8",
		"\"YAC\"": "30",
		"\"RACR\"": "-0.45",
		"\"Team %\"": "\"-3%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "1"
	},
	{
		"\"Player\"": "\"Jamaal Williams\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "3",
		"\"Rec\"": "3",
		"\"Yards\"": "17",
		"\"TD\"": "0",
		"\"YPR\"": "5.7",
		"\"Yd/Tgt\"": "5.7",
		"\"Tgt Shr\"": "\"5%\"",
		"\"AirYards\"": "5",
		"\"AY/Tgt\"": "1.7",
		"\"YAC\"": "12",
		"\"RACR\"": "3.4",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.08",
		"\"AirYAC (AY+YAC)\"": "17"
	},
	{
		"\"Player\"": "\"James Conner\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "18",
		"\"Rec\"": "17",
		"\"Yards\"": "114",
		"\"TD\"": "1",
		"\"YPR\"": "6.7",
		"\"Yd/Tgt\"": "6.3",
		"\"Tgt Shr\"": "\"12%\"",
		"\"AirYards\"": "-15",
		"\"AY/Tgt\"": "-0.8",
		"\"YAC\"": "127",
		"\"RACR\"": "-7.6",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.17",
		"\"AirYAC (AY+YAC)\"": "112"
	},
	{
		"\"Player\"": "\"James Cook\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "10",
		"\"Rec\"": "9",
		"\"Yards\"": "57",
		"\"TD\"": "0",
		"\"YPR\"": "6.3",
		"\"Yd/Tgt\"": "5.7",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "-3",
		"\"AY/Tgt\"": "-0.3",
		"\"YAC\"": "65",
		"\"RACR\"": "-19",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.12",
		"\"AirYAC (AY+YAC)\"": "62"
	},
	{
		"\"Player\"": "\"Jase McClellan\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Javonte Williams\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "14",
		"\"Rec\"": "9",
		"\"Yards\"": "45",
		"\"TD\"": "0",
		"\"YPR\"": "5",
		"\"Yd/Tgt\"": "3.2",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "-23",
		"\"AY/Tgt\"": "-1.6",
		"\"YAC\"": "60",
		"\"RACR\"": "-1.96",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.14",
		"\"AirYAC (AY+YAC)\"": "37"
	},
	{
		"\"Player\"": "\"Jaylen Warren\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "20",
		"\"Rec\"": "14",
		"\"Yards\"": "129",
		"\"TD\"": "0",
		"\"YPR\"": "9.2",
		"\"Yd/Tgt\"": "6.4",
		"\"Tgt Shr\"": "\"14%\"",
		"\"AirYards\"": "-11",
		"\"AY/Tgt\"": "-0.6",
		"\"YAC\"": "141",
		"\"RACR\"": "-11.73",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.21",
		"\"AirYAC (AY+YAC)\"": "130"
	},
	{
		"\"Player\"": "\"Jaylen Wright\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "5",
		"\"Rec\"": "3",
		"\"Yards\"": "8",
		"\"TD\"": "0",
		"\"YPR\"": "2.7",
		"\"Yd/Tgt\"": "1.6",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "-5",
		"\"AY/Tgt\"": "-1",
		"\"YAC\"": "8",
		"\"RACR\"": "-1.6",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.03",
		"\"AirYAC (AY+YAC)\"": "3"
	},
	{
		"\"Player\"": "\"Jeff Wilson Jr\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "7",
		"\"TD\"": "0",
		"\"YPR\"": "7",
		"\"Yd/Tgt\"": "7",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "1",
		"\"AY/Tgt\"": "1",
		"\"YAC\"": "6",
		"\"RACR\"": "7",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "7"
	},
	{
		"\"Player\"": "\"Jeremy McNichols\"",
		"\"Team\"": "\"WAS\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "1",
		"\"TD\"": "0",
		"\"YPR\"": "0.5",
		"\"Yd/Tgt\"": "0.5",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "23",
		"\"AY/Tgt\"": "11.5",
		"\"YAC\"": "4",
		"\"RACR\"": "0.04",
		"\"Team %\"": "\"3%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "27"
	},
	{
		"\"Player\"": "\"Jerome Ford\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "12",
		"\"Rec\"": "11",
		"\"Yards\"": "97",
		"\"TD\"": "0",
		"\"YPR\"": "8.8",
		"\"Yd/Tgt\"": "8.1",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "16",
		"\"AY/Tgt\"": "1.3",
		"\"YAC\"": "106",
		"\"RACR\"": "6.06",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.1",
		"\"AirYAC (AY+YAC)\"": "122"
	},
	{
		"\"Player\"": "\"Joe Mixon\"",
		"\"Team\"": "\"HOU\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "22",
		"\"Rec\"": "16",
		"\"Yards\"": "118",
		"\"TD\"": "0",
		"\"YPR\"": "7.4",
		"\"Yd/Tgt\"": "5.4",
		"\"Tgt Shr\"": "\"18%\"",
		"\"AirYards\"": "9",
		"\"AY/Tgt\"": "0.4",
		"\"YAC\"": "129",
		"\"RACR\"": "13.11",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.28",
		"\"AirYAC (AY+YAC)\"": "138"
	},
	{
		"\"Player\"": "\"Jonathan Taylor\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "5",
		"\"Rec\"": "3",
		"\"Yards\"": "14",
		"\"TD\"": "1",
		"\"YPR\"": "4.7",
		"\"Yd/Tgt\"": "2.8",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-5",
		"\"AY/Tgt\"": "-1",
		"\"YAC\"": "18",
		"\"RACR\"": "-2.8",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "13"
	},
	{
		"\"Player\"": "\"Jonathon Brooks\"",
		"\"Team\"": "\"CAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "3",
		"\"Rec\"": "3",
		"\"Yards\"": "23",
		"\"TD\"": "0",
		"\"YPR\"": "7.7",
		"\"Yd/Tgt\"": "7.7",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "-8",
		"\"AY/Tgt\"": "-2.7",
		"\"YAC\"": "31",
		"\"RACR\"": "-2.88",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "23"
	},
	{
		"\"Player\"": "\"Jordan Mason\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "2",
		"\"Rec\"": "1",
		"\"Yards\"": "5",
		"\"TD\"": "0",
		"\"YPR\"": "5",
		"\"Yd/Tgt\"": "2.5",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "3",
		"\"AY/Tgt\"": "1.5",
		"\"YAC\"": "2",
		"\"RACR\"": "1.67",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "5"
	},
	{
		"\"Player\"": "\"Jordan Mims\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Josh Jacobs\"",
		"\"Team\"": "\"GB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "14",
		"\"Rec\"": "12",
		"\"Yards\"": "174",
		"\"TD\"": "0",
		"\"YPR\"": "14.5",
		"\"Yd/Tgt\"": "12.4",
		"\"Tgt Shr\"": "\"12%\"",
		"\"AirYards\"": "-15",
		"\"AY/Tgt\"": "-1.1",
		"\"YAC\"": "188",
		"\"RACR\"": "-11.6",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.18",
		"\"AirYAC (AY+YAC)\"": "173"
	},
	{
		"\"Player\"": "\"Joshua Kelley\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Julius Chestnut\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "2",
		"\"TD\"": "0",
		"\"YPR\"": "2",
		"\"Yd/Tgt\"": "2",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "2",
		"\"RACR\"": "Inf",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "2"
	},
	{
		"\"Player\"": "\"Justice Hill\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "20",
		"\"Rec\"": "15",
		"\"Yards\"": "111",
		"\"TD\"": "1",
		"\"YPR\"": "7.4",
		"\"Yd/Tgt\"": "5.6",
		"\"Tgt Shr\"": "\"18%\"",
		"\"AirYards\"": "-11",
		"\"AY/Tgt\"": "-0.6",
		"\"YAC\"": "142",
		"\"RACR\"": "-10.09",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.26",
		"\"AirYAC (AY+YAC)\"": "131"
	},
	{
		"\"Player\"": "\"Kareem Hunt\"",
		"\"Team\"": "\"KC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "11",
		"\"Rec\"": "7",
		"\"Yards\"": "36",
		"\"TD\"": "0",
		"\"YPR\"": "5.1",
		"\"Yd/Tgt\"": "3.3",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "-24",
		"\"AY/Tgt\"": "-2.2",
		"\"YAC\"": "52",
		"\"RACR\"": "-1.5",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.08",
		"\"AirYAC (AY+YAC)\"": "28"
	},
	{
		"\"Player\"": "\"Ke'Shawn Vaughn\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Keaton Mitchell\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Keilan Robinson\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Kendre Miller\"",
		"\"Team\"": "\"NO\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "2",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "0",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "1",
		"\"AY/Tgt\"": "0.5",
		"\"YAC\"": "0",
		"\"RACR\"": "0",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "1"
	},
	{
		"\"Player\"": "\"Kene Nwangwu\"",
		"\"Team\"": "\"NYJ\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Kenneth Gainwell\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "6",
		"\"Rec\"": "6",
		"\"Yards\"": "53",
		"\"TD\"": "0",
		"\"YPR\"": "8.8",
		"\"Yd/Tgt\"": "8.8",
		"\"Tgt Shr\"": "\"5%\"",
		"\"AirYards\"": "3",
		"\"AY/Tgt\"": "0.5",
		"\"YAC\"": "50",
		"\"RACR\"": "17.67",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.08",
		"\"AirYAC (AY+YAC)\"": "53"
	},
	{
		"\"Player\"": "\"Kenneth Walker III\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "11",
		"\"Rec\"": "8",
		"\"Yards\"": "54",
		"\"TD\"": "0",
		"\"YPR\"": "6.8",
		"\"Yd/Tgt\"": "4.9",
		"\"Tgt Shr\"": "\"12%\"",
		"\"AirYards\"": "-23",
		"\"AY/Tgt\"": "-2.1",
		"\"YAC\"": "79",
		"\"RACR\"": "-2.35",
		"\"Team %\"": "\"-4%\"",
		"\"WOPR\"": "0.16",
		"\"AirYAC (AY+YAC)\"": "56"
	},
	{
		"\"Player\"": "\"Kenny McIntosh\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "7",
		"\"TD\"": "0",
		"\"YPR\"": "3.5",
		"\"Yd/Tgt\"": "3.5",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "3",
		"\"AY/Tgt\"": "1.5",
		"\"YAC\"": "4",
		"\"RACR\"": "2.33",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "7"
	},
	{
		"\"Player\"": "\"Khalil Herbert\"",
		"\"Team\"": "\"CIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "7",
		"\"TD\"": "0",
		"\"YPR\"": "7",
		"\"Yd/Tgt\"": "7",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "-2",
		"\"AY/Tgt\"": "-2",
		"\"YAC\"": "9",
		"\"RACR\"": "-3.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "7"
	},
	{
		"\"Player\"": "\"Khari Blasingame\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Kimani Vidal\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "4",
		"\"Rec\"": "2",
		"\"Yards\"": "13",
		"\"TD\"": "0",
		"\"YPR\"": "6.5",
		"\"Yd/Tgt\"": "3.2",
		"\"Tgt Shr\"": "\"5%\"",
		"\"AirYards\"": "8",
		"\"AY/Tgt\"": "2",
		"\"YAC\"": "11",
		"\"RACR\"": "1.62",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.08",
		"\"AirYAC (AY+YAC)\"": "19"
	},
	{
		"\"Player\"": "\"Kyle Juszczyk\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "5",
		"\"Rec\"": "4",
		"\"Yards\"": "29",
		"\"TD\"": "0",
		"\"YPR\"": "7.2",
		"\"Yd/Tgt\"": "5.8",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "46",
		"\"AY/Tgt\"": "9.2",
		"\"YAC\"": "10",
		"\"RACR\"": "0.63",
		"\"Team %\"": "\"4%\"",
		"\"WOPR\"": "0.09",
		"\"AirYAC (AY+YAC)\"": "56"
	},
	{
		"\"Player\"": "\"Kyren Williams\"",
		"\"Team\"": "\"LAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "5",
		"\"Rec\"": "5",
		"\"Yards\"": "23",
		"\"TD\"": "0",
		"\"YPR\"": "4.6",
		"\"Yd/Tgt\"": "4.6",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "9",
		"\"AY/Tgt\"": "1.8",
		"\"YAC\"": "14",
		"\"RACR\"": "2.56",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "23"
	},
	{
		"\"Player\"": "\"Michael Burton\"",
		"\"Team\"": "\"DEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "6",
		"\"TD\"": "0",
		"\"YPR\"": "3",
		"\"Yd/Tgt\"": "3",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "0",
		"\"RACR\"": "Inf",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.03",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Mike Boone\"",
		"\"Team\"": "\"CAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Najee Harris\"",
		"\"Team\"": "\"PIT\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "14",
		"\"Rec\"": "13",
		"\"Yards\"": "104",
		"\"TD\"": "0",
		"\"YPR\"": "8",
		"\"Yd/Tgt\"": "7.4",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "-37",
		"\"AY/Tgt\"": "-2.6",
		"\"YAC\"": "146",
		"\"RACR\"": "-2.81",
		"\"Team %\"": "\"-3%\"",
		"\"WOPR\"": "0.13",
		"\"AirYAC (AY+YAC)\"": "109"
	},
	{
		"\"Player\"": "\"Nick Chubb\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "5",
		"\"Rec\"": "3",
		"\"Yards\"": "25",
		"\"TD\"": "1",
		"\"YPR\"": "8.3",
		"\"Yd/Tgt\"": "5",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "24",
		"\"RACR\"": "Inf",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "24"
	},
	{
		"\"Player\"": "\"Patrick Ricard\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "5",
		"\"TD\"": "0",
		"\"YPR\"": "5",
		"\"Yd/Tgt\"": "5",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "2",
		"\"AY/Tgt\"": "2",
		"\"YAC\"": "3",
		"\"RACR\"": "2.5",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "5"
	},
	{
		"\"Player\"": "\"Patrick Taylor\"",
		"\"Team\"": "\"SF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "1",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "0",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.03",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Pierre Strong Jr\"",
		"\"Team\"": "\"CLE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "9",
		"\"TD\"": "0",
		"\"YPR\"": "4.5",
		"\"Yd/Tgt\"": "4.5",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "9",
		"\"RACR\"": "Inf",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "9"
	},
	{
		"\"Player\"": "\"Rachaad White\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "7",
		"\"Rec\"": "6",
		"\"Yards\"": "48",
		"\"TD\"": "2",
		"\"YPR\"": "8",
		"\"Yd/Tgt\"": "6.9",
		"\"Tgt Shr\"": "\"6%\"",
		"\"AirYards\"": "-25",
		"\"AY/Tgt\"": "-3.6",
		"\"YAC\"": "72",
		"\"RACR\"": "-1.92",
		"\"Team %\"": "\"-3%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "47"
	},
	{
		"\"Player\"": "\"Raheem Blackshear\"",
		"\"Team\"": "\"CAR\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Raheem Mostert\"",
		"\"Team\"": "\"MIA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "7",
		"\"Rec\"": "6",
		"\"Yards\"": "25",
		"\"TD\"": "0",
		"\"YPR\"": "4.2",
		"\"Yd/Tgt\"": "3.6",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "7",
		"\"AY/Tgt\"": "1",
		"\"YAC\"": "20",
		"\"RACR\"": "3.57",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "27"
	},
	{
		"\"Player\"": "\"Rasheen Ali\"",
		"\"Team\"": "\"BAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Ray Davis\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "3",
		"\"Rec\"": "3",
		"\"Yards\"": "18",
		"\"TD\"": "1",
		"\"YPR\"": "6",
		"\"Yd/Tgt\"": "6",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "9",
		"\"AY/Tgt\"": "3",
		"\"YAC\"": "9",
		"\"RACR\"": "2",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "18"
	},
	{
		"\"Player\"": "\"Reggie Gilliam\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Rhamondre Stevenson\"",
		"\"Team\"": "\"NE\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "10",
		"\"Rec\"": "8",
		"\"Yards\"": "53",
		"\"TD\"": "0",
		"\"YPR\"": "6.6",
		"\"Yd/Tgt\"": "5.3",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "-11",
		"\"AY/Tgt\"": "-1.1",
		"\"YAC\"": "69",
		"\"RACR\"": "-4.82",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.11",
		"\"AirYAC (AY+YAC)\"": "58"
	},
	{
		"\"Player\"": "\"Rico Dowdle\"",
		"\"Team\"": "\"DAL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "13",
		"\"Rec\"": "9",
		"\"Yards\"": "39",
		"\"TD\"": "0",
		"\"YPR\"": "4.3",
		"\"Yd/Tgt\"": "3",
		"\"Tgt Shr\"": "\"7%\"",
		"\"AirYards\"": "-25",
		"\"AY/Tgt\"": "-1.9",
		"\"YAC\"": "62",
		"\"RACR\"": "-1.56",
		"\"Team %\"": "\"-2%\"",
		"\"WOPR\"": "0.09",
		"\"AirYAC (AY+YAC)\"": "37"
	},
	{
		"\"Player\"": "\"Roschon Johnson\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "18",
		"\"TD\"": "0",
		"\"YPR\"": "9",
		"\"Yd/Tgt\"": "9",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "7",
		"\"AY/Tgt\"": "3.5",
		"\"YAC\"": "11",
		"\"RACR\"": "2.57",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.03",
		"\"AirYAC (AY+YAC)\"": "18"
	},
	{
		"\"Player\"": "\"Samaje Perine\"",
		"\"Team\"": "\"KC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "10",
		"\"Rec\"": "7",
		"\"Yards\"": "73",
		"\"TD\"": "0",
		"\"YPR\"": "10.4",
		"\"Yd/Tgt\"": "7.3",
		"\"Tgt Shr\"": "\"5%\"",
		"\"AirYards\"": "-16",
		"\"AY/Tgt\"": "-1.6",
		"\"YAC\"": "78",
		"\"RACR\"": "-4.56",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.07",
		"\"AirYAC (AY+YAC)\"": "62"
	},
	{
		"\"Player\"": "\"Saquon Barkley\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "13",
		"\"Rec\"": "10",
		"\"Yards\"": "118",
		"\"TD\"": "0",
		"\"YPR\"": "11.8",
		"\"Yd/Tgt\"": "9.1",
		"\"Tgt Shr\"": "\"12%\"",
		"\"AirYards\"": "27",
		"\"AY/Tgt\"": "2.1",
		"\"YAC\"": "112",
		"\"RACR\"": "4.37",
		"\"Team %\"": "\"3%\"",
		"\"WOPR\"": "0.2",
		"\"AirYAC (AY+YAC)\"": "139"
	},
	{
		"\"Player\"": "\"Scott Matlock\"",
		"\"Team\"": "\"LAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "2",
		"\"TD\"": "0",
		"\"YPR\"": "2",
		"\"Yd/Tgt\"": "2",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "1",
		"\"AY/Tgt\"": "1",
		"\"YAC\"": "1",
		"\"RACR\"": "2",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "2"
	},
	{
		"\"Player\"": "\"Sean Tucker\"",
		"\"Team\"": "\"TB\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "3",
		"\"Rec\"": "1",
		"\"Yards\"": "7",
		"\"TD\"": "0",
		"\"YPR\"": "7",
		"\"Yd/Tgt\"": "2.3",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "3",
		"\"AY/Tgt\"": "1",
		"\"YAC\"": "2",
		"\"RACR\"": "2.33",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "5"
	},
	{
		"\"Player\"": "\"Sincere McCormick\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "5",
		"\"Rec\"": "4",
		"\"Yards\"": "12",
		"\"TD\"": "0",
		"\"YPR\"": "3",
		"\"Yd/Tgt\"": "2.4",
		"\"Tgt Shr\"": "\"4%\"",
		"\"AirYards\"": "-12",
		"\"AY/Tgt\"": "-2.4",
		"\"YAC\"": "27",
		"\"RACR\"": "-1",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.06",
		"\"AirYAC (AY+YAC)\"": "15"
	},
	{
		"\"Player\"": "\"Sione Vaki\"",
		"\"Team\"": "\"DET\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Tank Bigsby\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "4",
		"\"Rec\"": "2",
		"\"Yards\"": "14",
		"\"TD\"": "0",
		"\"YPR\"": "7",
		"\"Yd/Tgt\"": "3.5",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "-9",
		"\"AY/Tgt\"": "-2.2",
		"\"YAC\"": "15",
		"\"RACR\"": "-1.56",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "6"
	},
	{
		"\"Player\"": "\"Tony Pollard\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "17",
		"\"Rec\"": "11",
		"\"Yards\"": "79",
		"\"TD\"": "0",
		"\"YPR\"": "7.2",
		"\"Yd/Tgt\"": "4.6",
		"\"Tgt Shr\"": "\"11%\"",
		"\"AirYards\"": "15",
		"\"AY/Tgt\"": "0.9",
		"\"YAC\"": "69",
		"\"RACR\"": "5.27",
		"\"Team %\"": "\"1%\"",
		"\"WOPR\"": "0.17",
		"\"AirYAC (AY+YAC)\"": "84"
	},
	{
		"\"Player\"": "\"Travis Etienne\"",
		"\"Team\"": "\"JAC\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "15",
		"\"Rec\"": "14",
		"\"Yards\"": "88",
		"\"TD\"": "0",
		"\"YPR\"": "6.3",
		"\"Yd/Tgt\"": "5.9",
		"\"Tgt Shr\"": "\"10%\"",
		"\"AirYards\"": "-14",
		"\"AY/Tgt\"": "-0.9",
		"\"YAC\"": "100",
		"\"RACR\"": "-6.29",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.15",
		"\"AirYAC (AY+YAC)\"": "86"
	},
	{
		"\"Player\"": "\"Travis Homer\"",
		"\"Team\"": "\"CHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "3",
		"\"Rec\"": "3",
		"\"Yards\"": "11",
		"\"TD\"": "0",
		"\"YPR\"": "3.7",
		"\"Yd/Tgt\"": "3.7",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "1",
		"\"AY/Tgt\"": "0.3",
		"\"YAC\"": "10",
		"\"RACR\"": "11",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.05",
		"\"AirYAC (AY+YAC)\"": "11"
	},
	{
		"\"Player\"": "\"Trey Benson\"",
		"\"Team\"": "\"ARI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "1",
		"\"Rec\"": "1",
		"\"Yards\"": "4",
		"\"TD\"": "0",
		"\"YPR\"": "4",
		"\"Yd/Tgt\"": "4",
		"\"Tgt Shr\"": "\"1%\"",
		"\"AirYards\"": "-5",
		"\"AY/Tgt\"": "-5",
		"\"YAC\"": "9",
		"\"RACR\"": "-0.8",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.01",
		"\"AirYAC (AY+YAC)\"": "4"
	},
	{
		"\"Player\"": "\"Trey Sermon\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "3",
		"\"Rec\"": "3",
		"\"Yards\"": "12",
		"\"TD\"": "0",
		"\"YPR\"": "4",
		"\"Yd/Tgt\"": "4",
		"\"Tgt Shr\"": "\"3%\"",
		"\"AirYards\"": "3",
		"\"AY/Tgt\"": "1",
		"\"YAC\"": "9",
		"\"RACR\"": "4",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.04",
		"\"AirYAC (AY+YAC)\"": "12"
	},
	{
		"\"Player\"": "\"Ty Chandler\"",
		"\"Team\"": "\"MIN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "2",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Ty Johnson\"",
		"\"Team\"": "\"BUF\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "10",
		"\"Rec\"": "8",
		"\"Yards\"": "178",
		"\"TD\"": "1",
		"\"YPR\"": "22.2",
		"\"Yd/Tgt\"": "17.8",
		"\"Tgt Shr\"": "\"8%\"",
		"\"AirYards\"": "78",
		"\"AY/Tgt\"": "7.8",
		"\"YAC\"": "119",
		"\"RACR\"": "2.28",
		"\"Team %\"": "\"7%\"",
		"\"WOPR\"": "0.17",
		"\"AirYAC (AY+YAC)\"": "197"
	},
	{
		"\"Player\"": "\"Tyjae Spears\"",
		"\"Team\"": "\"TEN\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "12",
		"\"Rec\"": "9",
		"\"Yards\"": "97",
		"\"TD\"": "1",
		"\"YPR\"": "10.8",
		"\"Yd/Tgt\"": "8.1",
		"\"Tgt Shr\"": "\"9%\"",
		"\"AirYards\"": "-13",
		"\"AY/Tgt\"": "-1.1",
		"\"YAC\"": "107",
		"\"RACR\"": "-7.46",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.13",
		"\"AirYAC (AY+YAC)\"": "94"
	},
	{
		"\"Player\"": "\"Tyler Allgeier\"",
		"\"Team\"": "\"ATL\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "2",
		"\"Rec\"": "2",
		"\"Yards\"": "5",
		"\"TD\"": "0",
		"\"YPR\"": "2.5",
		"\"Yd/Tgt\"": "2.5",
		"\"Tgt Shr\"": "\"2%\"",
		"\"AirYards\"": "-6",
		"\"AY/Tgt\"": "-3",
		"\"YAC\"": "11",
		"\"RACR\"": "-0.83",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.02",
		"\"AirYAC (AY+YAC)\"": "5"
	},
	{
		"\"Player\"": "\"Tyler Goodson\"",
		"\"Team\"": "\"IND\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "3",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Tyrone Tracy Jr\"",
		"\"Team\"": "\"NYG\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "4",
		"\"Tgt\"": "21",
		"\"Rec\"": "12",
		"\"Yards\"": "103",
		"\"TD\"": "0",
		"\"YPR\"": "8.6",
		"\"Yd/Tgt\"": "4.9",
		"\"Tgt Shr\"": "\"15%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "0",
		"\"YAC\"": "0",
		"\"RACR\"": "Inf",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0.22",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Will Shipley\"",
		"\"Team\"": "\"PHI\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	{
		"\"Player\"": "\"Zach Charbonnet\"",
		"\"Team\"": "\"SEA\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "5",
		"\"Tgt\"": "16",
		"\"Rec\"": "12",
		"\"Yards\"": "86",
		"\"TD\"": "0",
		"\"YPR\"": "7.2",
		"\"Yd/Tgt\"": "5.4",
		"\"Tgt Shr\"": "\"11%\"",
		"\"AirYards\"": "-15",
		"\"AY/Tgt\"": "-0.9",
		"\"YAC\"": "103",
		"\"RACR\"": "-5.73",
		"\"Team %\"": "\"-1%\"",
		"\"WOPR\"": "0.15",
		"\"AirYAC (AY+YAC)\"": "88"
	},
	{
		"\"Player\"": "\"Zamir White\"",
		"\"Team\"": "\"LV\"",
		"\"Pos\"": "\"RB\"",
		"\"GMs\"": "1",
		"\"Tgt\"": "0",
		"\"Rec\"": "0",
		"\"Yards\"": "0",
		"\"TD\"": "0",
		"\"YPR\"": "NA",
		"\"Yd/Tgt\"": "NA",
		"\"Tgt Shr\"": "\"0%\"",
		"\"AirYards\"": "0",
		"\"AY/Tgt\"": "NA",
		"\"YAC\"": "0",
		"\"RACR\"": "NA",
		"\"Team %\"": "\"0%\"",
		"\"WOPR\"": "0",
		"\"AirYAC (AY+YAC)\"": "0"
	},
	
]

module.exports = rbRvWeeklyStatExplorerRecievingTabLastFiveWeeks;