const rotovizPositiveScriptOffensivePaceAndRunPassReportLastFiveWeeks = [
	{
		"\"Team\"": "\"TB\"",
		"\"GMs\"": "3",
		"\"Plays\"": "22",
		"\"Sec/Snap\"": "28.8",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"49%\"",
		"\"Rush%\"": "\"51%\"",
		"\"Pass\"": "11",
		"\"Rush\"": "11",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"MIN\"",
		"\"GMs\"": "3",
		"\"Plays\"": "32",
		"\"Sec/Snap\"": "24.6",
		"\"No-Huddle\"": "\"16%\"",
		"\"Pass%\"": "\"59%\"",
		"\"Rush%\"": "\"41%\"",
		"\"Pass\"": "19",
		"\"Rush\"": "13",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"CHI\"",
		"\"GMs\"": "2",
		"\"Plays\"": "37",
		"\"Sec/Snap\"": "28.5",
		"\"No-Huddle\"": "\"26%\"",
		"\"Pass%\"": "\"51%\"",
		"\"Rush%\"": "\"49%\"",
		"\"Pass\"": "19",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"BAL\"",
		"\"GMs\"": "4",
		"\"Plays\"": "43",
		"\"Sec/Snap\"": "30.7",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"33%\"",
		"\"Rush%\"": "\"67%\"",
		"\"Pass\"": "14",
		"\"Rush\"": "29",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"CIN\"",
		"\"GMs\"": "5",
		"\"Plays\"": "38",
		"\"Sec/Snap\"": "26.4",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"53%\"",
		"\"Rush%\"": "\"47%\"",
		"\"Pass\"": "20",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"HOU\"",
		"\"GMs\"": "3",
		"\"Plays\"": "46",
		"\"Sec/Snap\"": "29.8",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"57%\"",
		"\"Rush%\"": "\"43%\"",
		"\"Pass\"": "26",
		"\"Rush\"": "20",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"IND\"",
		"\"GMs\"": "3",
		"\"Plays\"": "7",
		"\"Sec/Snap\"": "27.2",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"79%\"",
		"\"Rush%\"": "\"21%\"",
		"\"Pass\"": "6",
		"\"Rush\"": "2",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"JAC\"",
		"\"GMs\"": "2",
		"\"Plays\"": "17",
		"\"Sec/Snap\"": "29.5",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"34%\"",
		"\"Rush%\"": "\"66%\"",
		"\"Pass\"": "6",
		"\"Rush\"": "12",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"WAS\"",
		"\"GMs\"": "4",
		"\"Plays\"": "48",
		"\"Sec/Snap\"": "30.2",
		"\"No-Huddle\"": "\"66%\"",
		"\"Pass%\"": "\"42%\"",
		"\"Rush%\"": "\"58%\"",
		"\"Pass\"": "20",
		"\"Rush\"": "28",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"LV\"",
		"\"GMs\"": "1",
		"\"Plays\"": "7",
		"\"Sec/Snap\"": "39",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"41%\"",
		"\"Rush%\"": "\"59%\"",
		"\"Pass\"": "3",
		"\"Rush\"": "4",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"DEN\"",
		"\"GMs\"": "3",
		"\"Plays\"": "25",
		"\"Sec/Snap\"": "29.7",
		"\"No-Huddle\"": "\"8%\"",
		"\"Pass%\"": "\"39%\"",
		"\"Rush%\"": "\"61%\"",
		"\"Pass\"": "10",
		"\"Rush\"": "16",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"SF\"",
		"\"GMs\"": "3",
		"\"Plays\"": "41",
		"\"Sec/Snap\"": "31.4",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"43%\"",
		"\"Rush%\"": "\"57%\"",
		"\"Pass\"": "17",
		"\"Rush\"": "23",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"GB\"",
		"\"GMs\"": "3",
		"\"Plays\"": "43",
		"\"Sec/Snap\"": "31.1",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"44%\"",
		"\"Rush%\"": "\"56%\"",
		"\"Pass\"": "19",
		"\"Rush\"": "24",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"SEA\"",
		"\"GMs\"": "2",
		"\"Plays\"": "8",
		"\"Sec/Snap\"": "26.3",
		"\"No-Huddle\"": "\"10%\"",
		"\"Pass%\"": "\"45%\"",
		"\"Rush%\"": "\"55%\"",
		"\"Pass\"": "4",
		"\"Rush\"": "4",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"NYG\"",
		"\"GMs\"": "1",
		"\"Plays\"": "4",
		"\"Sec/Snap\"": "29.1",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"58%\"",
		"\"Rush%\"": "\"42%\"",
		"\"Pass\"": "3",
		"\"Rush\"": "2",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"KC\"",
		"\"GMs\"": "3",
		"\"Plays\"": "58",
		"\"Sec/Snap\"": "28.3",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"40%\"",
		"\"Rush%\"": "\"60%\"",
		"\"Pass\"": "23",
		"\"Rush\"": "35",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"PHI\"",
		"\"GMs\"": "4",
		"\"Plays\"": "50",
		"\"Sec/Snap\"": "32.3",
		"\"No-Huddle\"": "\"23%\"",
		"\"Pass%\"": "\"30%\"",
		"\"Rush%\"": "\"70%\"",
		"\"Pass\"": "15",
		"\"Rush\"": "35",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"LAC\"",
		"\"GMs\"": "3",
		"\"Plays\"": "58",
		"\"Sec/Snap\"": "28.6",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"50%\"",
		"\"Rush%\"": "\"50%\"",
		"\"Pass\"": "29",
		"\"Rush\"": "29",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"PIT\"",
		"\"GMs\"": "3",
		"\"Plays\"": "63",
		"\"Sec/Snap\"": "28.4",
		"\"No-Huddle\"": "\"19%\"",
		"\"Pass%\"": "\"35%\"",
		"\"Rush%\"": "\"65%\"",
		"\"Pass\"": "22",
		"\"Rush\"": "41",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"ATL\"",
		"\"GMs\"": "3",
		"\"Plays\"": "26",
		"\"Sec/Snap\"": "28.7",
		"\"No-Huddle\"": "\"15%\"",
		"\"Pass%\"": "\"32%\"",
		"\"Rush%\"": "\"68%\"",
		"\"Pass\"": "8",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"DET\"",
		"\"GMs\"": "4",
		"\"Plays\"": "47",
		"\"Sec/Snap\"": "31.7",
		"\"No-Huddle\"": "\"1%\"",
		"\"Pass%\"": "\"47%\"",
		"\"Rush%\"": "\"53%\"",
		"\"Pass\"": "22",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"NE\"",
		"\"GMs\"": "1",
		"\"Plays\"": "6",
		"\"Sec/Snap\"": "28.4",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"46%\"",
		"\"Rush%\"": "\"54%\"",
		"\"Pass\"": "3",
		"\"Rush\"": "3",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"TEN\"",
		"\"GMs\"": "2",
		"\"Plays\"": "10",
		"\"Sec/Snap\"": "23.4",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"50%\"",
		"\"Rush%\"": "\"50%\"",
		"\"Pass\"": "5",
		"\"Rush\"": "5",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"BUF\"",
		"\"GMs\"": "2",
		"\"Plays\"": "38",
		"\"Sec/Snap\"": "31.3",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"50%\"",
		"\"Rush%\"": "\"50%\"",
		"\"Pass\"": "19",
		"\"Rush\"": "19",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"MIA\"",
		"\"GMs\"": "2",
		"\"Plays\"": "37",
		"\"Sec/Snap\"": "29.3",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"36%\"",
		"\"Rush%\"": "\"64%\"",
		"\"Pass\"": "13",
		"\"Rush\"": "24",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"LAR\"",
		"\"GMs\"": "3",
		"\"Plays\"": "30",
		"\"Sec/Snap\"": "24.7",
		"\"No-Huddle\"": "\"5%\"",
		"\"Pass%\"": "\"45%\"",
		"\"Rush%\"": "\"55%\"",
		"\"Pass\"": "14",
		"\"Rush\"": "17",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"NYJ\"",
		"\"GMs\"": "2",
		"\"Plays\"": "4",
		"\"Sec/Snap\"": "26.3",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"50%\"",
		"\"Rush%\"": "\"50%\"",
		"\"Pass\"": "2",
		"\"Rush\"": "2",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"CAR\"",
		"\"GMs\"": "1",
		"\"Plays\"": "1",
		"\"Sec/Snap\"": "27.7",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"33%\"",
		"\"Rush%\"": "\"67%\"",
		"\"Pass\"": "0",
		"\"Rush\"": "1",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"ARI\"",
		"\"GMs\"": "1",
		"\"Plays\"": "13",
		"\"Sec/Snap\"": "30.2",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"31%\"",
		"\"Rush%\"": "\"69%\"",
		"\"Pass\"": "4",
		"\"Rush\"": "9",
		"\"No Play (Penalty)\"": "0"
	},
	
]

module.exports = rotovizPositiveScriptOffensivePaceAndRunPassReportLastFiveWeeks;