const rotovizNegativeScriptOffensivePaceAndRunPassReportLastFiveWeeks = [
	{
		"\"Team\"": "\"KC\"",
		"\"GMs\"": "5",
		"\"Plays\"": "25",
		"\"Sec/Snap\"": "26.7",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"63%\"",
		"\"Rush%\"": "\"37%\"",
		"\"Pass\"": "16",
		"\"Rush\"": "9",
		"\"No Play (Penalty)\"": "29"
	},
	{
		"\"Team\"": "\"DET\"",
		"\"GMs\"": "6",
		"\"Plays\"": "32",
		"\"Sec/Snap\"": "23.4",
		"\"No-Huddle\"": "\"9%\"",
		"\"Pass%\"": "\"70%\"",
		"\"Rush%\"": "\"30%\"",
		"\"Pass\"": "22",
		"\"Rush\"": "10",
		"\"No Play (Penalty)\"": "26"
	},
	{
		"\"Team\"": "\"CAR\"",
		"\"GMs\"": "12",
		"\"Plays\"": "78",
		"\"Sec/Snap\"": "24.7",
		"\"No-Huddle\"": "\"14%\"",
		"\"Pass%\"": "\"63%\"",
		"\"Rush%\"": "\"37%\"",
		"\"Pass\"": "49",
		"\"Rush\"": "29",
		"\"No Play (Penalty)\"": "32"
	},
	{
		"\"Team\"": "\"HOU\"",
		"\"GMs\"": "7",
		"\"Plays\"": "37",
		"\"Sec/Snap\"": "23.9",
		"\"No-Huddle\"": "\"19%\"",
		"\"Pass%\"": "\"68%\"",
		"\"Rush%\"": "\"32%\"",
		"\"Pass\"": "25",
		"\"Rush\"": "12",
		"\"No Play (Penalty)\"": "32"
	},
	{
		"\"Team\"": "\"CIN\"",
		"\"GMs\"": "8",
		"\"Plays\"": "33",
		"\"Sec/Snap\"": "27.3",
		"\"No-Huddle\"": "\"13%\"",
		"\"Pass%\"": "\"70%\"",
		"\"Rush%\"": "\"30%\"",
		"\"Pass\"": "24",
		"\"Rush\"": "10",
		"\"No Play (Penalty)\"": "33"
	},
	{
		"\"Team\"": "\"IND\"",
		"\"GMs\"": "8",
		"\"Plays\"": "48",
		"\"Sec/Snap\"": "23",
		"\"No-Huddle\"": "\"26%\"",
		"\"Pass%\"": "\"66%\"",
		"\"Rush%\"": "\"34%\"",
		"\"Pass\"": "32",
		"\"Rush\"": "16",
		"\"No Play (Penalty)\"": "34"
	},
	{
		"\"Team\"": "\"TB\"",
		"\"GMs\"": "8",
		"\"Plays\"": "43",
		"\"Sec/Snap\"": "24.2",
		"\"No-Huddle\"": "\"12%\"",
		"\"Pass%\"": "\"71%\"",
		"\"Rush%\"": "\"29%\"",
		"\"Pass\"": "30",
		"\"Rush\"": "12",
		"\"No Play (Penalty)\"": "40"
	},
	{
		"\"Team\"": "\"MIN\"",
		"\"GMs\"": "6",
		"\"Plays\"": "35",
		"\"Sec/Snap\"": "24",
		"\"No-Huddle\"": "\"21%\"",
		"\"Pass%\"": "\"73%\"",
		"\"Rush%\"": "\"27%\"",
		"\"Pass\"": "26",
		"\"Rush\"": "10",
		"\"No Play (Penalty)\"": "46"
	},
	{
		"\"Team\"": "\"TEN\"",
		"\"GMs\"": "9",
		"\"Plays\"": "46",
		"\"Sec/Snap\"": "25",
		"\"No-Huddle\"": "\"32%\"",
		"\"Pass%\"": "\"66%\"",
		"\"Rush%\"": "\"34%\"",
		"\"Pass\"": "30",
		"\"Rush\"": "16",
		"\"No Play (Penalty)\"": "43"
	},
	{
		"\"Team\"": "\"PIT\"",
		"\"GMs\"": "9",
		"\"Plays\"": "54",
		"\"Sec/Snap\"": "25.6",
		"\"No-Huddle\"": "\"26%\"",
		"\"Pass%\"": "\"64%\"",
		"\"Rush%\"": "\"36%\"",
		"\"Pass\"": "34",
		"\"Rush\"": "19",
		"\"No Play (Penalty)\"": "38"
	},
	{
		"\"Team\"": "\"ARI\"",
		"\"GMs\"": "10",
		"\"Plays\"": "53",
		"\"Sec/Snap\"": "23.4",
		"\"No-Huddle\"": "\"30%\"",
		"\"Pass%\"": "\"66%\"",
		"\"Rush%\"": "\"34%\"",
		"\"Pass\"": "35",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "33"
	},
	{
		"\"Team\"": "\"CHI\"",
		"\"GMs\"": "8",
		"\"Plays\"": "36",
		"\"Sec/Snap\"": "24.8",
		"\"No-Huddle\"": "\"20%\"",
		"\"Pass%\"": "\"60%\"",
		"\"Rush%\"": "\"40%\"",
		"\"Pass\"": "22",
		"\"Rush\"": "14",
		"\"No Play (Penalty)\"": "30"
	},
	{
		"\"Team\"": "\"DEN\"",
		"\"GMs\"": "8",
		"\"Plays\"": "36",
		"\"Sec/Snap\"": "26.6",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"63%\"",
		"\"Rush%\"": "\"37%\"",
		"\"Pass\"": "23",
		"\"Rush\"": "14",
		"\"No Play (Penalty)\"": "33"
	},
	{
		"\"Team\"": "\"MIA\"",
		"\"GMs\"": "6",
		"\"Plays\"": "22",
		"\"Sec/Snap\"": "27.5",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"66%\"",
		"\"Rush%\"": "\"34%\"",
		"\"Pass\"": "15",
		"\"Rush\"": "8",
		"\"No Play (Penalty)\"": "24"
	},
	{
		"\"Team\"": "\"NE\"",
		"\"GMs\"": "8",
		"\"Plays\"": "51",
		"\"Sec/Snap\"": "24.5",
		"\"No-Huddle\"": "\"16%\"",
		"\"Pass%\"": "\"66%\"",
		"\"Rush%\"": "\"34%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "17",
		"\"No Play (Penalty)\"": "35"
	},
	{
		"\"Team\"": "\"SEA\"",
		"\"GMs\"": "7",
		"\"Plays\"": "32",
		"\"Sec/Snap\"": "23.8",
		"\"No-Huddle\"": "\"25%\"",
		"\"Pass%\"": "\"70%\"",
		"\"Rush%\"": "\"30%\"",
		"\"Pass\"": "23",
		"\"Rush\"": "10",
		"\"No Play (Penalty)\"": "40"
	},
	{
		"\"Team\"": "\"NYG\"",
		"\"GMs\"": "8",
		"\"Plays\"": "57",
		"\"Sec/Snap\"": "26.1",
		"\"No-Huddle\"": "\"19%\"",
		"\"Pass%\"": "\"62%\"",
		"\"Rush%\"": "\"38%\"",
		"\"Pass\"": "35",
		"\"Rush\"": "22",
		"\"No Play (Penalty)\"": "30"
	},
	{
		"\"Team\"": "\"NYJ\"",
		"\"GMs\"": "9",
		"\"Plays\"": "66",
		"\"Sec/Snap\"": "24.7",
		"\"No-Huddle\"": "\"18%\"",
		"\"Pass%\"": "\"71%\"",
		"\"Rush%\"": "\"29%\"",
		"\"Pass\"": "47",
		"\"Rush\"": "19",
		"\"No Play (Penalty)\"": "38"
	},
	{
		"\"Team\"": "\"ATL\"",
		"\"GMs\"": "6",
		"\"Plays\"": "66",
		"\"Sec/Snap\"": "24.7",
		"\"No-Huddle\"": "\"14%\"",
		"\"Pass%\"": "\"60%\"",
		"\"Rush%\"": "\"40%\"",
		"\"Pass\"": "40",
		"\"Rush\"": "27",
		"\"No Play (Penalty)\"": "55"
	},
	{
		"\"Team\"": "\"BUF\"",
		"\"GMs\"": "6",
		"\"Plays\"": "26",
		"\"Sec/Snap\"": "26.3",
		"\"No-Huddle\"": "\"27%\"",
		"\"Pass%\"": "\"68%\"",
		"\"Rush%\"": "\"32%\"",
		"\"Pass\"": "18",
		"\"Rush\"": "8",
		"\"No Play (Penalty)\"": "31"
	},
	{
		"\"Team\"": "\"LV\"",
		"\"GMs\"": "7",
		"\"Plays\"": "47",
		"\"Sec/Snap\"": "25.4",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"72%\"",
		"\"Rush%\"": "\"28%\"",
		"\"Pass\"": "34",
		"\"Rush\"": "13",
		"\"No Play (Penalty)\"": "35"
	},
	{
		"\"Team\"": "\"JAC\"",
		"\"GMs\"": "5",
		"\"Plays\"": "29",
		"\"Sec/Snap\"": "24.4",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"69%\"",
		"\"Rush%\"": "\"31%\"",
		"\"Pass\"": "20",
		"\"Rush\"": "9",
		"\"No Play (Penalty)\"": "25"
	},
	{
		"\"Team\"": "\"LAR\"",
		"\"GMs\"": "8",
		"\"Plays\"": "46",
		"\"Sec/Snap\"": "22.7",
		"\"No-Huddle\"": "\"14%\"",
		"\"Pass%\"": "\"68%\"",
		"\"Rush%\"": "\"32%\"",
		"\"Pass\"": "31",
		"\"Rush\"": "15",
		"\"No Play (Penalty)\"": "39"
	},
	{
		"\"Team\"": "\"SF\"",
		"\"GMs\"": "3",
		"\"Plays\"": "11",
		"\"Sec/Snap\"": "28.3",
		"\"No-Huddle\"": "\"5%\"",
		"\"Pass%\"": "\"61%\"",
		"\"Rush%\"": "\"39%\"",
		"\"Pass\"": "7",
		"\"Rush\"": "4",
		"\"No Play (Penalty)\"": "25"
	},
	{
		"\"Team\"": "\"WAS\"",
		"\"GMs\"": "11",
		"\"Plays\"": "60",
		"\"Sec/Snap\"": "25.6",
		"\"No-Huddle\"": "\"13%\"",
		"\"Pass%\"": "\"70%\"",
		"\"Rush%\"": "\"30%\"",
		"\"Pass\"": "42",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "30"
	},
	{
		"\"Team\"": "\"CLE\"",
		"\"GMs\"": "8",
		"\"Plays\"": "41",
		"\"Sec/Snap\"": "25.6",
		"\"No-Huddle\"": "\"9%\"",
		"\"Pass%\"": "\"58%\"",
		"\"Rush%\"": "\"42%\"",
		"\"Pass\"": "24",
		"\"Rush\"": "17",
		"\"No Play (Penalty)\"": "32"
	},
	{
		"\"Team\"": "\"GB\"",
		"\"GMs\"": "7",
		"\"Plays\"": "42",
		"\"Sec/Snap\"": "24",
		"\"No-Huddle\"": "\"23%\"",
		"\"Pass%\"": "\"67%\"",
		"\"Rush%\"": "\"33%\"",
		"\"Pass\"": "28",
		"\"Rush\"": "14",
		"\"No Play (Penalty)\"": "36"
	},
	{
		"\"Team\"": "\"DAL\"",
		"\"GMs\"": "5",
		"\"Plays\"": "21",
		"\"Sec/Snap\"": "25.7",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"61%\"",
		"\"Rush%\"": "\"39%\"",
		"\"Pass\"": "13",
		"\"Rush\"": "8",
		"\"No Play (Penalty)\"": "24"
	},
	{
		"\"Team\"": "\"NO\"",
		"\"GMs\"": "8",
		"\"Plays\"": "52",
		"\"Sec/Snap\"": "25.1",
		"\"No-Huddle\"": "\"13%\"",
		"\"Pass%\"": "\"65%\"",
		"\"Rush%\"": "\"35%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "30"
	},
	{
		"\"Team\"": "\"PHI\"",
		"\"GMs\"": "7",
		"\"Plays\"": "38",
		"\"Sec/Snap\"": "26.9",
		"\"No-Huddle\"": "\"24%\"",
		"\"Pass%\"": "\"60%\"",
		"\"Rush%\"": "\"40%\"",
		"\"Pass\"": "23",
		"\"Rush\"": "15",
		"\"No Play (Penalty)\"": "35"
	},
	{
		"\"Team\"": "\"BAL\"",
		"\"GMs\"": "2",
		"\"Plays\"": "2",
		"\"Sec/Snap\"": "22.2",
		"\"No-Huddle\"": "\"12%\"",
		"\"Pass%\"": "\"81%\"",
		"\"Rush%\"": "\"19%\"",
		"\"Pass\"": "2",
		"\"Rush\"": "0",
		"\"No Play (Penalty)\"": "29"
	},
	{
		"\"Team\"": "\"LAC\"",
		"\"GMs\"": "5",
		"\"Plays\"": "36",
		"\"Sec/Snap\"": "23.3",
		"\"No-Huddle\"": "\"26%\"",
		"\"Pass%\"": "\"68%\"",
		"\"Rush%\"": "\"32%\"",
		"\"Pass\"": "25",
		"\"Rush\"": "11",
		"\"No Play (Penalty)\"": "37"
	},
	
]

module.exports = rotovizNegativeScriptOffensivePaceAndRunPassReportLastFiveWeeks;