const rotovizPositiveScriptOffensivePaceAndRunPassReportLastFiveWeeks = [
	{
		"\"Team\"": "\"KC\"",
		"\"GMs\"": "16",
		"\"Plays\"": "42",
		"\"Sec/Snap\"": "29.1",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"52%\"",
		"\"Rush%\"": "\"48%\"",
		"\"Pass\"": "22",
		"\"Rush\"": "20",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"ATL\"",
		"\"GMs\"": "5",
		"\"Plays\"": "9",
		"\"Sec/Snap\"": "24.2",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"39%\"",
		"\"Rush%\"": "\"61%\"",
		"\"Pass\"": "3",
		"\"Rush\"": "5",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"BAL\"",
		"\"GMs\"": "17",
		"\"Plays\"": "46",
		"\"Sec/Snap\"": "30.1",
		"\"No-Huddle\"": "\"9%\"",
		"\"Pass%\"": "\"43%\"",
		"\"Rush%\"": "\"57%\"",
		"\"Pass\"": "20",
		"\"Rush\"": "26",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"CLE\"",
		"\"GMs\"": "8",
		"\"Plays\"": "29",
		"\"Sec/Snap\"": "28.7",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"50%\"",
		"\"Rush%\"": "\"50%\"",
		"\"Pass\"": "15",
		"\"Rush\"": "15",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"JAC\"",
		"\"GMs\"": "11",
		"\"Plays\"": "27",
		"\"Sec/Snap\"": "29.3",
		"\"No-Huddle\"": "\"14%\"",
		"\"Pass%\"": "\"46%\"",
		"\"Rush%\"": "\"54%\"",
		"\"Pass\"": "12",
		"\"Rush\"": "15",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"MIN\"",
		"\"GMs\"": "10",
		"\"Plays\"": "27",
		"\"Sec/Snap\"": "28.1",
		"\"No-Huddle\"": "\"26%\"",
		"\"Pass%\"": "\"52%\"",
		"\"Rush%\"": "\"48%\"",
		"\"Pass\"": "14",
		"\"Rush\"": "13",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"SF\"",
		"\"GMs\"": "17",
		"\"Plays\"": "41",
		"\"Sec/Snap\"": "30.9",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"42%\"",
		"\"Rush%\"": "\"58%\"",
		"\"Pass\"": "17",
		"\"Rush\"": "24",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"GB\"",
		"\"GMs\"": "11",
		"\"Plays\"": "30",
		"\"Sec/Snap\"": "30.2",
		"\"No-Huddle\"": "\"1%\"",
		"\"Pass%\"": "\"40%\"",
		"\"Rush%\"": "\"60%\"",
		"\"Pass\"": "12",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"PHI\"",
		"\"GMs\"": "11",
		"\"Plays\"": "24",
		"\"Sec/Snap\"": "28.9",
		"\"No-Huddle\"": "\"11%\"",
		"\"Pass%\"": "\"47%\"",
		"\"Rush%\"": "\"53%\"",
		"\"Pass\"": "11",
		"\"Rush\"": "13",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"LAR\"",
		"\"GMs\"": "9",
		"\"Plays\"": "25",
		"\"Sec/Snap\"": "29.7",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"41%\"",
		"\"Rush%\"": "\"59%\"",
		"\"Pass\"": "10",
		"\"Rush\"": "15",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"DAL\"",
		"\"GMs\"": "11",
		"\"Plays\"": "37",
		"\"Sec/Snap\"": "29.6",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"52%\"",
		"\"Rush%\"": "\"48%\"",
		"\"Pass\"": "19",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"BUF\"",
		"\"GMs\"": "15",
		"\"Plays\"": "39",
		"\"Sec/Snap\"": "31",
		"\"No-Huddle\"": "\"5%\"",
		"\"Pass%\"": "\"43%\"",
		"\"Rush%\"": "\"57%\"",
		"\"Pass\"": "17",
		"\"Rush\"": "22",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"LV\"",
		"\"GMs\"": "8",
		"\"Plays\"": "21",
		"\"Sec/Snap\"": "29.3",
		"\"No-Huddle\"": "\"5%\"",
		"\"Pass%\"": "\"49%\"",
		"\"Rush%\"": "\"51%\"",
		"\"Pass\"": "10",
		"\"Rush\"": "11",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"DET\"",
		"\"GMs\"": "15",
		"\"Plays\"": "39",
		"\"Sec/Snap\"": "28.7",
		"\"No-Huddle\"": "\"1%\"",
		"\"Pass%\"": "\"50%\"",
		"\"Rush%\"": "\"50%\"",
		"\"Pass\"": "20",
		"\"Rush\"": "19",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"IND\"",
		"\"GMs\"": "8",
		"\"Plays\"": "19",
		"\"Sec/Snap\"": "27.7",
		"\"No-Huddle\"": "\"11%\"",
		"\"Pass%\"": "\"44%\"",
		"\"Rush%\"": "\"56%\"",
		"\"Pass\"": "8",
		"\"Rush\"": "11",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"TB\"",
		"\"GMs\"": "12",
		"\"Plays\"": "27",
		"\"Sec/Snap\"": "29.5",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"44%\"",
		"\"Rush%\"": "\"56%\"",
		"\"Pass\"": "12",
		"\"Rush\"": "15",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"LAC\"",
		"\"GMs\"": "8",
		"\"Plays\"": "24",
		"\"Sec/Snap\"": "27.4",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"48%\"",
		"\"Rush%\"": "\"52%\"",
		"\"Pass\"": "11",
		"\"Rush\"": "12",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"ARI\"",
		"\"GMs\"": "7",
		"\"Plays\"": "20",
		"\"Sec/Snap\"": "30.2",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"40%\"",
		"\"Rush%\"": "\"60%\"",
		"\"Pass\"": "8",
		"\"Rush\"": "12",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"DEN\"",
		"\"GMs\"": "7",
		"\"Plays\"": "19",
		"\"Sec/Snap\"": "29.2",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"45%\"",
		"\"Rush%\"": "\"55%\"",
		"\"Pass\"": "8",
		"\"Rush\"": "10",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"WAS\"",
		"\"GMs\"": "5",
		"\"Plays\"": "5",
		"\"Sec/Snap\"": "28.1",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"55%\"",
		"\"Rush%\"": "\"45%\"",
		"\"Pass\"": "3",
		"\"Rush\"": "2",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"MIA\"",
		"\"GMs\"": "11",
		"\"Plays\"": "32",
		"\"Sec/Snap\"": "29.6",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"44%\"",
		"\"Rush%\"": "\"56%\"",
		"\"Pass\"": "14",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"NO\"",
		"\"GMs\"": "11",
		"\"Plays\"": "33",
		"\"Sec/Snap\"": "30.6",
		"\"No-Huddle\"": "\"1%\"",
		"\"Pass%\"": "\"40%\"",
		"\"Rush%\"": "\"60%\"",
		"\"Pass\"": "13",
		"\"Rush\"": "20",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"HOU\"",
		"\"GMs\"": "12",
		"\"Plays\"": "25",
		"\"Sec/Snap\"": "29.4",
		"\"No-Huddle\"": "\"14%\"",
		"\"Pass%\"": "\"51%\"",
		"\"Rush%\"": "\"49%\"",
		"\"Pass\"": "13",
		"\"Rush\"": "13",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"NE\"",
		"\"GMs\"": "6",
		"\"Plays\"": "12",
		"\"Sec/Snap\"": "27.7",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"53%\"",
		"\"Rush%\"": "\"47%\"",
		"\"Pass\"": "6",
		"\"Rush\"": "6",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"SEA\"",
		"\"GMs\"": "8",
		"\"Plays\"": "19",
		"\"Sec/Snap\"": "27.3",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"48%\"",
		"\"Rush%\"": "\"52%\"",
		"\"Pass\"": "9",
		"\"Rush\"": "10",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"PIT\"",
		"\"GMs\"": "9",
		"\"Plays\"": "18",
		"\"Sec/Snap\"": "30.4",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"40%\"",
		"\"Rush%\"": "\"60%\"",
		"\"Pass\"": "7",
		"\"Rush\"": "11",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"CIN\"",
		"\"GMs\"": "9",
		"\"Plays\"": "24",
		"\"Sec/Snap\"": "31.8",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"56%\"",
		"\"Rush%\"": "\"44%\"",
		"\"Pass\"": "14",
		"\"Rush\"": "11",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"CAR\"",
		"\"GMs\"": "3",
		"\"Plays\"": "4",
		"\"Sec/Snap\"": "28.7",
		"\"No-Huddle\"": "\"9%\"",
		"\"Pass%\"": "\"49%\"",
		"\"Rush%\"": "\"51%\"",
		"\"Pass\"": "2",
		"\"Rush\"": "2",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"CHI\"",
		"\"GMs\"": "10",
		"\"Plays\"": "34",
		"\"Sec/Snap\"": "30.3",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"41%\"",
		"\"Rush%\"": "\"59%\"",
		"\"Pass\"": "14",
		"\"Rush\"": "20",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"TEN\"",
		"\"GMs\"": "8",
		"\"Plays\"": "22",
		"\"Sec/Snap\"": "30.8",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"48%\"",
		"\"Rush%\"": "\"52%\"",
		"\"Pass\"": "11",
		"\"Rush\"": "11",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"NYJ\"",
		"\"GMs\"": "5",
		"\"Plays\"": "11",
		"\"Sec/Snap\"": "28.8",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"48%\"",
		"\"Rush%\"": "\"52%\"",
		"\"Pass\"": "6",
		"\"Rush\"": "6",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"NYG\"",
		"\"GMs\"": "4",
		"\"Plays\"": "10",
		"\"Sec/Snap\"": "28.1",
		"\"No-Huddle\"": "\"12%\"",
		"\"Pass%\"": "\"47%\"",
		"\"Rush%\"": "\"53%\"",
		"\"Pass\"": "5",
		"\"Rush\"": "5",
		"\"No Play (Penalty)\"": "0"
	},
	
]

module.exports = rotovizPositiveScriptOffensivePaceAndRunPassReportLastFiveWeeks;