const rotovizNegativeScriptOffensivePaceAndRunPassReportLastFiveWeeks = [
	{
		"\"Team\"": "\"LAR\"",
		"\"GMs\"": "5",
		"\"Plays\"": "58",
		"\"Sec/Snap\"": "25.5",
		"\"No-Huddle\"": "\"17%\"",
		"\"Pass%\"": "\"69%\"",
		"\"Rush%\"": "\"31%\"",
		"\"Pass\"": "40",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"MIN\"",
		"\"GMs\"": "3",
		"\"Plays\"": "18",
		"\"Sec/Snap\"": "26",
		"\"No-Huddle\"": "\"12%\"",
		"\"Pass%\"": "\"69%\"",
		"\"Rush%\"": "\"31%\"",
		"\"Pass\"": "12",
		"\"Rush\"": "6",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"TEN\"",
		"\"GMs\"": "4",
		"\"Plays\"": "57",
		"\"Sec/Snap\"": "27",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"66%\"",
		"\"Rush%\"": "\"34%\"",
		"\"Pass\"": "38",
		"\"Rush\"": "20",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"HOU\"",
		"\"GMs\"": "3",
		"\"Plays\"": "14",
		"\"Sec/Snap\"": "22.4",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"67%\"",
		"\"Rush%\"": "\"33%\"",
		"\"Pass\"": "9",
		"\"Rush\"": "5",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"IND\"",
		"\"GMs\"": "5",
		"\"Plays\"": "55",
		"\"Sec/Snap\"": "24.1",
		"\"No-Huddle\"": "\"17%\"",
		"\"Pass%\"": "\"67%\"",
		"\"Rush%\"": "\"33%\"",
		"\"Pass\"": "37",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"JAC\"",
		"\"GMs\"": "3",
		"\"Plays\"": "60",
		"\"Sec/Snap\"": "24.5",
		"\"No-Huddle\"": "\"21%\"",
		"\"Pass%\"": "\"66%\"",
		"\"Rush%\"": "\"34%\"",
		"\"Pass\"": "39",
		"\"Rush\"": "21",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"ARI\"",
		"\"GMs\"": "2",
		"\"Plays\"": "23",
		"\"Sec/Snap\"": "26.4",
		"\"No-Huddle\"": "\"17%\"",
		"\"Pass%\"": "\"77%\"",
		"\"Rush%\"": "\"23%\"",
		"\"Pass\"": "18",
		"\"Rush\"": "5",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"NYJ\"",
		"\"GMs\"": "4",
		"\"Plays\"": "69",
		"\"Sec/Snap\"": "26.7",
		"\"No-Huddle\"": "\"15%\"",
		"\"Pass%\"": "\"66%\"",
		"\"Rush%\"": "\"34%\"",
		"\"Pass\"": "46",
		"\"Rush\"": "23",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"TB\"",
		"\"GMs\"": "3",
		"\"Plays\"": "43",
		"\"Sec/Snap\"": "26.2",
		"\"No-Huddle\"": "\"11%\"",
		"\"Pass%\"": "\"64%\"",
		"\"Rush%\"": "\"36%\"",
		"\"Pass\"": "27",
		"\"Rush\"": "16",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"ATL\"",
		"\"GMs\"": "3",
		"\"Plays\"": "43",
		"\"Sec/Snap\"": "29.5",
		"\"No-Huddle\"": "\"20%\"",
		"\"Pass%\"": "\"56%\"",
		"\"Rush%\"": "\"44%\"",
		"\"Pass\"": "24",
		"\"Rush\"": "19",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"CHI\"",
		"\"GMs\"": "5",
		"\"Plays\"": "75",
		"\"Sec/Snap\"": "23.4",
		"\"No-Huddle\"": "\"28%\"",
		"\"Pass%\"": "\"70%\"",
		"\"Rush%\"": "\"30%\"",
		"\"Pass\"": "52",
		"\"Rush\"": "22",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"NO\"",
		"\"GMs\"": "1",
		"\"Plays\"": "30",
		"\"Sec/Snap\"": "19",
		"\"No-Huddle\"": "\"23%\"",
		"\"Pass%\"": "\"77%\"",
		"\"Rush%\"": "\"23%\"",
		"\"Pass\"": "23",
		"\"Rush\"": "7",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"SEA\"",
		"\"GMs\"": "2",
		"\"Plays\"": "47",
		"\"Sec/Snap\"": "22.3",
		"\"No-Huddle\"": "\"30%\"",
		"\"Pass%\"": "\"75%\"",
		"\"Rush%\"": "\"25%\"",
		"\"Pass\"": "35",
		"\"Rush\"": "12",
		"\"No Play (Penalty)\"": "4"
	},
	{
		"\"Team\"": "\"PHI\"",
		"\"GMs\"": "2",
		"\"Plays\"": "23",
		"\"Sec/Snap\"": "25.8",
		"\"No-Huddle\"": "\"23%\"",
		"\"Pass%\"": "\"44%\"",
		"\"Rush%\"": "\"56%\"",
		"\"Pass\"": "10",
		"\"Rush\"": "13",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"CIN\"",
		"\"GMs\"": "4",
		"\"Plays\"": "35",
		"\"Sec/Snap\"": "25.2",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"71%\"",
		"\"Rush%\"": "\"29%\"",
		"\"Pass\"": "25",
		"\"Rush\"": "10",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"DEN\"",
		"\"GMs\"": "2",
		"\"Plays\"": "29",
		"\"Sec/Snap\"": "24",
		"\"No-Huddle\"": "\"22%\"",
		"\"Pass%\"": "\"61%\"",
		"\"Rush%\"": "\"39%\"",
		"\"Pass\"": "17",
		"\"Rush\"": "11",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"CAR\"",
		"\"GMs\"": "2",
		"\"Plays\"": "49",
		"\"Sec/Snap\"": "25.1",
		"\"No-Huddle\"": "\"8%\"",
		"\"Pass%\"": "\"68%\"",
		"\"Rush%\"": "\"32%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "15",
		"\"No Play (Penalty)\"": "4"
	},
	{
		"\"Team\"": "\"LV\"",
		"\"GMs\"": "4",
		"\"Plays\"": "101",
		"\"Sec/Snap\"": "21.6",
		"\"No-Huddle\"": "\"17%\"",
		"\"Pass%\"": "\"76%\"",
		"\"Rush%\"": "\"24%\"",
		"\"Pass\"": "77",
		"\"Rush\"": "24",
		"\"No Play (Penalty)\"": "4"
	},
	{
		"\"Team\"": "\"SF\"",
		"\"GMs\"": "2",
		"\"Plays\"": "35",
		"\"Sec/Snap\"": "24.9",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"62%\"",
		"\"Rush%\"": "\"38%\"",
		"\"Pass\"": "21",
		"\"Rush\"": "13",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"DAL\"",
		"\"GMs\"": "4",
		"\"Plays\"": "78",
		"\"Sec/Snap\"": "21.6",
		"\"No-Huddle\"": "\"19%\"",
		"\"Pass%\"": "\"72%\"",
		"\"Rush%\"": "\"28%\"",
		"\"Pass\"": "56",
		"\"Rush\"": "22",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"NYG\"",
		"\"GMs\"": "4",
		"\"Plays\"": "74",
		"\"Sec/Snap\"": "27.6",
		"\"No-Huddle\"": "\"15%\"",
		"\"Pass%\"": "\"59%\"",
		"\"Rush%\"": "\"41%\"",
		"\"Pass\"": "44",
		"\"Rush\"": "31",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"BUF\"",
		"\"GMs\"": "1",
		"\"Plays\"": "8",
		"\"Sec/Snap\"": "12.5",
		"\"No-Huddle\"": "\"13%\"",
		"\"Pass%\"": "\"87%\"",
		"\"Rush%\"": "\"13%\"",
		"\"Pass\"": "7",
		"\"Rush\"": "1",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"MIA\"",
		"\"GMs\"": "1",
		"\"Plays\"": "7",
		"\"Sec/Snap\"": "30.2",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"50%\"",
		"\"Rush%\"": "\"50%\"",
		"\"Pass\"": "4",
		"\"Rush\"": "4",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"CLE\"",
		"\"GMs\"": "2",
		"\"Plays\"": "71",
		"\"Sec/Snap\"": "23.7",
		"\"No-Huddle\"": "\"23%\"",
		"\"Pass%\"": "\"73%\"",
		"\"Rush%\"": "\"27%\"",
		"\"Pass\"": "51",
		"\"Rush\"": "19",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"NE\"",
		"\"GMs\"": "3",
		"\"Plays\"": "56",
		"\"Sec/Snap\"": "24.4",
		"\"No-Huddle\"": "\"19%\"",
		"\"Pass%\"": "\"68%\"",
		"\"Rush%\"": "\"32%\"",
		"\"Pass\"": "38",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"GB\"",
		"\"GMs\"": "1",
		"\"Plays\"": "21",
		"\"Sec/Snap\"": "22.1",
		"\"No-Huddle\"": "\"27%\"",
		"\"Pass%\"": "\"73%\"",
		"\"Rush%\"": "\"27%\"",
		"\"Pass\"": "15",
		"\"Rush\"": "6",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"KC\"",
		"\"GMs\"": "3",
		"\"Plays\"": "32",
		"\"Sec/Snap\"": "27.4",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"63%\"",
		"\"Rush%\"": "\"37%\"",
		"\"Pass\"": "20",
		"\"Rush\"": "12",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"BAL\"",
		"\"GMs\"": "2",
		"\"Plays\"": "34",
		"\"Sec/Snap\"": "25.4",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"60%\"",
		"\"Rush%\"": "\"40%\"",
		"\"Pass\"": "21",
		"\"Rush\"": "14",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"WAS\"",
		"\"GMs\"": "3",
		"\"Plays\"": "24",
		"\"Sec/Snap\"": "17.6",
		"\"No-Huddle\"": "\"70%\"",
		"\"Pass%\"": "\"77%\"",
		"\"Rush%\"": "\"23%\"",
		"\"Pass\"": "19",
		"\"Rush\"": "6",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"PIT\"",
		"\"GMs\"": "2",
		"\"Plays\"": "44",
		"\"Sec/Snap\"": "30.9",
		"\"No-Huddle\"": "\"16%\"",
		"\"Pass%\"": "\"45%\"",
		"\"Rush%\"": "\"55%\"",
		"\"Pass\"": "20",
		"\"Rush\"": "24",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"DET\"",
		"\"GMs\"": "1",
		"\"Plays\"": "13",
		"\"Sec/Snap\"": "26.3",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"50%\"",
		"\"Rush%\"": "\"50%\"",
		"\"Pass\"": "6",
		"\"Rush\"": "6",
		"\"No Play (Penalty)\"": "0"
	},
	
]

module.exports = rotovizNegativeScriptOffensivePaceAndRunPassReportLastFiveWeeks;