const rotovizNeutralScriptOffensivePaceAndRunPassReportLastFiveWeeks = [
	{
		"\"Team\"": "\"DET\"",
		"\"GMs\"": "22",
		"\"Plays\"": "66",
		"\"Sec/Snap\"": "28.6",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"56%\"",
		"\"Rush%\"": "\"44%\"",
		"\"Pass\"": "37",
		"\"Rush\"": "29",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"KC\"",
		"\"GMs\"": "23",
		"\"Plays\"": "61",
		"\"Sec/Snap\"": "27.8",
		"\"No-Huddle\"": "\"1%\"",
		"\"Pass%\"": "\"60%\"",
		"\"Rush%\"": "\"40%\"",
		"\"Pass\"": "36",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"ATL\"",
		"\"GMs\"": "19",
		"\"Plays\"": "59",
		"\"Sec/Snap\"": "27.2",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"50%\"",
		"\"Rush%\"": "\"50%\"",
		"\"Pass\"": "29",
		"\"Rush\"": "29",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"CAR\"",
		"\"GMs\"": "19",
		"\"Plays\"": "55",
		"\"Sec/Snap\"": "29.1",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"54%\"",
		"\"Rush%\"": "\"46%\"",
		"\"Pass\"": "30",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"BAL\"",
		"\"GMs\"": "21",
		"\"Plays\"": "63",
		"\"Sec/Snap\"": "28.8",
		"\"No-Huddle\"": "\"13%\"",
		"\"Pass%\"": "\"53%\"",
		"\"Rush%\"": "\"47%\"",
		"\"Pass\"": "34",
		"\"Rush\"": "29",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"HOU\"",
		"\"GMs\"": "21",
		"\"Plays\"": "61",
		"\"Sec/Snap\"": "28.2",
		"\"No-Huddle\"": "\"10%\"",
		"\"Pass%\"": "\"56%\"",
		"\"Rush%\"": "\"44%\"",
		"\"Pass\"": "34",
		"\"Rush\"": "27",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"CIN\"",
		"\"GMs\"": "19",
		"\"Plays\"": "59",
		"\"Sec/Snap\"": "29.9",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"63%\"",
		"\"Rush%\"": "\"37%\"",
		"\"Pass\"": "38",
		"\"Rush\"": "22",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"CLE\"",
		"\"GMs\"": "20",
		"\"Plays\"": "68",
		"\"Sec/Snap\"": "27.2",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"56%\"",
		"\"Rush%\"": "\"44%\"",
		"\"Pass\"": "39",
		"\"Rush\"": "30",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"IND\"",
		"\"GMs\"": "19",
		"\"Plays\"": "61",
		"\"Sec/Snap\"": "27.4",
		"\"No-Huddle\"": "\"14%\"",
		"\"Pass%\"": "\"54%\"",
		"\"Rush%\"": "\"46%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "28",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"JAC\"",
		"\"GMs\"": "19",
		"\"Plays\"": "62",
		"\"Sec/Snap\"": "28.5",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"56%\"",
		"\"Rush%\"": "\"44%\"",
		"\"Pass\"": "35",
		"\"Rush\"": "27",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"MIN\"",
		"\"GMs\"": "19",
		"\"Plays\"": "61",
		"\"Sec/Snap\"": "27.2",
		"\"No-Huddle\"": "\"13%\"",
		"\"Pass%\"": "\"61%\"",
		"\"Rush%\"": "\"39%\"",
		"\"Pass\"": "37",
		"\"Rush\"": "23",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"TB\"",
		"\"GMs\"": "21",
		"\"Plays\"": "61",
		"\"Sec/Snap\"": "28.6",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"58%\"",
		"\"Rush%\"": "\"42%\"",
		"\"Pass\"": "35",
		"\"Rush\"": "26",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"TEN\"",
		"\"GMs\"": "19",
		"\"Plays\"": "59",
		"\"Sec/Snap\"": "29.1",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"55%\"",
		"\"Rush%\"": "\"45%\"",
		"\"Pass\"": "32",
		"\"Rush\"": "27",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"NO\"",
		"\"GMs\"": "19",
		"\"Plays\"": "63",
		"\"Sec/Snap\"": "27.5",
		"\"No-Huddle\"": "\"5%\"",
		"\"Pass%\"": "\"57%\"",
		"\"Rush%\"": "\"43%\"",
		"\"Pass\"": "36",
		"\"Rush\"": "27",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"PIT\"",
		"\"GMs\"": "20",
		"\"Plays\"": "61",
		"\"Sec/Snap\"": "29.4",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"47%\"",
		"\"Rush%\"": "\"53%\"",
		"\"Pass\"": "28",
		"\"Rush\"": "32",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"SF\"",
		"\"GMs\"": "22",
		"\"Plays\"": "61",
		"\"Sec/Snap\"": "30.8",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"54%\"",
		"\"Rush%\"": "\"46%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "28",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"WAS\"",
		"\"GMs\"": "19",
		"\"Plays\"": "61",
		"\"Sec/Snap\"": "28.7",
		"\"No-Huddle\"": "\"13%\"",
		"\"Pass%\"": "\"63%\"",
		"\"Rush%\"": "\"37%\"",
		"\"Pass\"": "39",
		"\"Rush\"": "23",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"ARI\"",
		"\"GMs\"": "19",
		"\"Plays\"": "59",
		"\"Sec/Snap\"": "28.3",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"54%\"",
		"\"Rush%\"": "\"46%\"",
		"\"Pass\"": "32",
		"\"Rush\"": "27",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"CHI\"",
		"\"GMs\"": "19",
		"\"Plays\"": "63",
		"\"Sec/Snap\"": "29.7",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"52%\"",
		"\"Rush%\"": "\"48%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "30",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"GB\"",
		"\"GMs\"": "21",
		"\"Plays\"": "63",
		"\"Sec/Snap\"": "28.4",
		"\"No-Huddle\"": "\"5%\"",
		"\"Pass%\"": "\"54%\"",
		"\"Rush%\"": "\"46%\"",
		"\"Pass\"": "34",
		"\"Rush\"": "29",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"LV\"",
		"\"GMs\"": "19",
		"\"Plays\"": "56",
		"\"Sec/Snap\"": "29.2",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"57%\"",
		"\"Rush%\"": "\"43%\"",
		"\"Pass\"": "32",
		"\"Rush\"": "24",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"DEN\"",
		"\"GMs\"": "19",
		"\"Plays\"": "58",
		"\"Sec/Snap\"": "28.8",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"54%\"",
		"\"Rush%\"": "\"46%\"",
		"\"Pass\"": "31",
		"\"Rush\"": "27",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"MIA\"",
		"\"GMs\"": "20",
		"\"Plays\"": "62",
		"\"Sec/Snap\"": "28.7",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"58%\"",
		"\"Rush%\"": "\"42%\"",
		"\"Pass\"": "36",
		"\"Rush\"": "26",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"LAC\"",
		"\"GMs\"": "19",
		"\"Plays\"": "63",
		"\"Sec/Snap\"": "26.7",
		"\"No-Huddle\"": "\"12%\"",
		"\"Pass%\"": "\"58%\"",
		"\"Rush%\"": "\"42%\"",
		"\"Pass\"": "37",
		"\"Rush\"": "27",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"PHI\"",
		"\"GMs\"": "20",
		"\"Plays\"": "65",
		"\"Sec/Snap\"": "28.4",
		"\"No-Huddle\"": "\"16%\"",
		"\"Pass%\"": "\"52%\"",
		"\"Rush%\"": "\"48%\"",
		"\"Pass\"": "34",
		"\"Rush\"": "31",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"NE\"",
		"\"GMs\"": "19",
		"\"Plays\"": "59",
		"\"Sec/Snap\"": "27.9",
		"\"No-Huddle\"": "\"9%\"",
		"\"Pass%\"": "\"55%\"",
		"\"Rush%\"": "\"45%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "27",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"SEA\"",
		"\"GMs\"": "19",
		"\"Plays\"": "58",
		"\"Sec/Snap\"": "27.1",
		"\"No-Huddle\"": "\"12%\"",
		"\"Pass%\"": "\"61%\"",
		"\"Rush%\"": "\"39%\"",
		"\"Pass\"": "36",
		"\"Rush\"": "23",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"LAR\"",
		"\"GMs\"": "20",
		"\"Plays\"": "59",
		"\"Sec/Snap\"": "29",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"59%\"",
		"\"Rush%\"": "\"41%\"",
		"\"Pass\"": "35",
		"\"Rush\"": "24",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"NYG\"",
		"\"GMs\"": "19",
		"\"Plays\"": "58",
		"\"Sec/Snap\"": "28.2",
		"\"No-Huddle\"": "\"11%\"",
		"\"Pass%\"": "\"52%\"",
		"\"Rush%\"": "\"48%\"",
		"\"Pass\"": "30",
		"\"Rush\"": "28",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"DAL\"",
		"\"GMs\"": "20",
		"\"Plays\"": "65",
		"\"Sec/Snap\"": "26.8",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"61%\"",
		"\"Rush%\"": "\"39%\"",
		"\"Pass\"": "40",
		"\"Rush\"": "26",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"BUF\"",
		"\"GMs\"": "21",
		"\"Plays\"": "64",
		"\"Sec/Snap\"": "28.6",
		"\"No-Huddle\"": "\"8%\"",
		"\"Pass%\"": "\"54%\"",
		"\"Rush%\"": "\"46%\"",
		"\"Pass\"": "35",
		"\"Rush\"": "29",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"NYJ\"",
		"\"GMs\"": "19",
		"\"Plays\"": "54",
		"\"Sec/Snap\"": "27.9",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"58%\"",
		"\"Rush%\"": "\"42%\"",
		"\"Pass\"": "31",
		"\"Rush\"": "22",
		"\"No Play (Penalty)\"": "2"
	},
	
]

module.exports = rotovizNeutralScriptOffensivePaceAndRunPassReportLastFiveWeeks;