const rotovizNeutralScriptOffensivePaceAndRunPassReportLastFiveWeeks = [
	{
		"\"Team\"": "\"BUF\"",
		"\"GMs\"": "23",
		"\"Plays\"": "64",
		"\"Sec/Snap\"": "28",
		"\"No-Huddle\"": "\"8%\"",
		"\"Pass%\"": "\"61%\"",
		"\"Rush%\"": "\"39%\"",
		"\"Pass\"": "39",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "53"
	},
	{
		"\"Team\"": "\"LAR\"",
		"\"GMs\"": "22",
		"\"Plays\"": "53",
		"\"Sec/Snap\"": "30.3",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"58%\"",
		"\"Rush%\"": "\"42%\"",
		"\"Pass\"": "31",
		"\"Rush\"": "23",
		"\"No Play (Penalty)\"": "53"
	},
	{
		"\"Team\"": "\"ATL\"",
		"\"GMs\"": "22",
		"\"Plays\"": "58",
		"\"Sec/Snap\"": "29.3",
		"\"No-Huddle\"": "\"11%\"",
		"\"Pass%\"": "\"46%\"",
		"\"Rush%\"": "\"54%\"",
		"\"Pass\"": "26",
		"\"Rush\"": "32",
		"\"No Play (Penalty)\"": "51"
	},
	{
		"\"Team\"": "\"NO\"",
		"\"GMs\"": "22",
		"\"Plays\"": "60",
		"\"Sec/Snap\"": "28.9",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"50%\"",
		"\"Rush%\"": "\"50%\"",
		"\"Pass\"": "30",
		"\"Rush\"": "30",
		"\"No Play (Penalty)\"": "55"
	},
	{
		"\"Team\"": "\"CAR\"",
		"\"GMs\"": "22",
		"\"Plays\"": "54",
		"\"Sec/Snap\"": "29.3",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"51%\"",
		"\"Rush%\"": "\"49%\"",
		"\"Pass\"": "27",
		"\"Rush\"": "26",
		"\"No Play (Penalty)\"": "52"
	},
	{
		"\"Team\"": "\"CLE\"",
		"\"GMs\"": "21",
		"\"Plays\"": "64",
		"\"Sec/Snap\"": "28.8",
		"\"No-Huddle\"": "\"8%\"",
		"\"Pass%\"": "\"52%\"",
		"\"Rush%\"": "\"48%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "31",
		"\"No Play (Penalty)\"": "51"
	},
	{
		"\"Team\"": "\"CHI\"",
		"\"GMs\"": "22",
		"\"Plays\"": "57",
		"\"Sec/Snap\"": "29.8",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"46%\"",
		"\"Rush%\"": "\"54%\"",
		"\"Pass\"": "26",
		"\"Rush\"": "31",
		"\"No Play (Penalty)\"": "56"
	},
	{
		"\"Team\"": "\"SF\"",
		"\"GMs\"": "25",
		"\"Plays\"": "62",
		"\"Sec/Snap\"": "30.6",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"53%\"",
		"\"Rush%\"": "\"47%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "30",
		"\"No Play (Penalty)\"": "52"
	},
	{
		"\"Team\"": "\"PIT\"",
		"\"GMs\"": "22",
		"\"Plays\"": "64",
		"\"Sec/Snap\"": "28.2",
		"\"No-Huddle\"": "\"8%\"",
		"\"Pass%\"": "\"53%\"",
		"\"Rush%\"": "\"47%\"",
		"\"Pass\"": "34",
		"\"Rush\"": "30",
		"\"No Play (Penalty)\"": "48"
	},
	{
		"\"Team\"": "\"CIN\"",
		"\"GMs\"": "24",
		"\"Plays\"": "67",
		"\"Sec/Snap\"": "28.1",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"65%\"",
		"\"Rush%\"": "\"35%\"",
		"\"Pass\"": "43",
		"\"Rush\"": "23",
		"\"No Play (Penalty)\"": "53"
	},
	{
		"\"Team\"": "\"DET\"",
		"\"GMs\"": "22",
		"\"Plays\"": "62",
		"\"Sec/Snap\"": "28.3",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"53%\"",
		"\"Rush%\"": "\"47%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "29",
		"\"No Play (Penalty)\"": "56"
	},
	{
		"\"Team\"": "\"PHI\"",
		"\"GMs\"": "25",
		"\"Plays\"": "70",
		"\"Sec/Snap\"": "27.9",
		"\"No-Huddle\"": "\"21%\"",
		"\"Pass%\"": "\"53%\"",
		"\"Rush%\"": "\"47%\"",
		"\"Pass\"": "37",
		"\"Rush\"": "33",
		"\"No Play (Penalty)\"": "52"
	},
	{
		"\"Team\"": "\"IND\"",
		"\"GMs\"": "22",
		"\"Plays\"": "60",
		"\"Sec/Snap\"": "27",
		"\"No-Huddle\"": "\"14%\"",
		"\"Pass%\"": "\"58%\"",
		"\"Rush%\"": "\"42%\"",
		"\"Pass\"": "34",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "52"
	},
	{
		"\"Team\"": "\"HOU\"",
		"\"GMs\"": "22",
		"\"Plays\"": "56",
		"\"Sec/Snap\"": "28.4",
		"\"No-Huddle\"": "\"5%\"",
		"\"Pass%\"": "\"54%\"",
		"\"Rush%\"": "\"46%\"",
		"\"Pass\"": "31",
		"\"Rush\"": "26",
		"\"No Play (Penalty)\"": "53"
	},
	{
		"\"Team\"": "\"NE\"",
		"\"GMs\"": "22",
		"\"Plays\"": "58",
		"\"Sec/Snap\"": "28.2",
		"\"No-Huddle\"": "\"8%\"",
		"\"Pass%\"": "\"56%\"",
		"\"Rush%\"": "\"44%\"",
		"\"Pass\"": "32",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "56"
	},
	{
		"\"Team\"": "\"MIA\"",
		"\"GMs\"": "23",
		"\"Plays\"": "56",
		"\"Sec/Snap\"": "28.7",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"59%\"",
		"\"Rush%\"": "\"41%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "23",
		"\"No Play (Penalty)\"": "50"
	},
	{
		"\"Team\"": "\"NYJ\"",
		"\"GMs\"": "22",
		"\"Plays\"": "54",
		"\"Sec/Snap\"": "27.6",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"57%\"",
		"\"Rush%\"": "\"43%\"",
		"\"Pass\"": "31",
		"\"Rush\"": "23",
		"\"No Play (Penalty)\"": "50"
	},
	{
		"\"Team\"": "\"BAL\"",
		"\"GMs\"": "23",
		"\"Plays\"": "66",
		"\"Sec/Snap\"": "29.6",
		"\"No-Huddle\"": "\"8%\"",
		"\"Pass%\"": "\"49%\"",
		"\"Rush%\"": "\"51%\"",
		"\"Pass\"": "32",
		"\"Rush\"": "33",
		"\"No Play (Penalty)\"": "46"
	},
	{
		"\"Team\"": "\"JAC\"",
		"\"GMs\"": "24",
		"\"Plays\"": "64",
		"\"Sec/Snap\"": "27",
		"\"No-Huddle\"": "\"9%\"",
		"\"Pass%\"": "\"56%\"",
		"\"Rush%\"": "\"44%\"",
		"\"Pass\"": "36",
		"\"Rush\"": "28",
		"\"No Play (Penalty)\"": "53"
	},
	{
		"\"Team\"": "\"WAS\"",
		"\"GMs\"": "22",
		"\"Plays\"": "63",
		"\"Sec/Snap\"": "29.7",
		"\"No-Huddle\"": "\"5%\"",
		"\"Pass%\"": "\"51%\"",
		"\"Rush%\"": "\"49%\"",
		"\"Pass\"": "32",
		"\"Rush\"": "31",
		"\"No Play (Penalty)\"": "49"
	},
	{
		"\"Team\"": "\"NYG\"",
		"\"GMs\"": "24",
		"\"Plays\"": "59",
		"\"Sec/Snap\"": "29",
		"\"No-Huddle\"": "\"15%\"",
		"\"Pass%\"": "\"51%\"",
		"\"Rush%\"": "\"49%\"",
		"\"Pass\"": "30",
		"\"Rush\"": "29",
		"\"No Play (Penalty)\"": "50"
	},
	{
		"\"Team\"": "\"TEN\"",
		"\"GMs\"": "22",
		"\"Plays\"": "57",
		"\"Sec/Snap\"": "30",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"52%\"",
		"\"Rush%\"": "\"48%\"",
		"\"Pass\"": "30",
		"\"Rush\"": "27",
		"\"No Play (Penalty)\"": "49"
	},
	{
		"\"Team\"": "\"KC\"",
		"\"GMs\"": "25",
		"\"Plays\"": "65",
		"\"Sec/Snap\"": "27.8",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"62%\"",
		"\"Rush%\"": "\"38%\"",
		"\"Pass\"": "41",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "45"
	},
	{
		"\"Team\"": "\"ARI\"",
		"\"GMs\"": "22",
		"\"Plays\"": "57",
		"\"Sec/Snap\"": "27.4",
		"\"No-Huddle\"": "\"26%\"",
		"\"Pass%\"": "\"59%\"",
		"\"Rush%\"": "\"41%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "24",
		"\"No Play (Penalty)\"": "54"
	},
	{
		"\"Team\"": "\"LAC\"",
		"\"GMs\"": "22",
		"\"Plays\"": "65",
		"\"Sec/Snap\"": "26.5",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"63%\"",
		"\"Rush%\"": "\"37%\"",
		"\"Pass\"": "41",
		"\"Rush\"": "24",
		"\"No Play (Penalty)\"": "47"
	},
	{
		"\"Team\"": "\"LV\"",
		"\"GMs\"": "22",
		"\"Plays\"": "59",
		"\"Sec/Snap\"": "29.3",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"58%\"",
		"\"Rush%\"": "\"42%\"",
		"\"Pass\"": "34",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "49"
	},
	{
		"\"Team\"": "\"MIN\"",
		"\"GMs\"": "23",
		"\"Plays\"": "62",
		"\"Sec/Snap\"": "26.7",
		"\"No-Huddle\"": "\"12%\"",
		"\"Pass%\"": "\"65%\"",
		"\"Rush%\"": "\"35%\"",
		"\"Pass\"": "40",
		"\"Rush\"": "22",
		"\"No Play (Penalty)\"": "50"
	},
	{
		"\"Team\"": "\"GB\"",
		"\"GMs\"": "22",
		"\"Plays\"": "56",
		"\"Sec/Snap\"": "29.9",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"56%\"",
		"\"Rush%\"": "\"44%\"",
		"\"Pass\"": "31",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "54"
	},
	{
		"\"Team\"": "\"DAL\"",
		"\"GMs\"": "24",
		"\"Plays\"": "66",
		"\"Sec/Snap\"": "27",
		"\"No-Huddle\"": "\"11%\"",
		"\"Pass%\"": "\"53%\"",
		"\"Rush%\"": "\"47%\"",
		"\"Pass\"": "35",
		"\"Rush\"": "31",
		"\"No Play (Penalty)\"": "56"
	},
	{
		"\"Team\"": "\"TB\"",
		"\"GMs\"": "22",
		"\"Plays\"": "64",
		"\"Sec/Snap\"": "27.2",
		"\"No-Huddle\"": "\"8%\"",
		"\"Pass%\"": "\"60%\"",
		"\"Rush%\"": "\"40%\"",
		"\"Pass\"": "39",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "52"
	},
	{
		"\"Team\"": "\"SEA\"",
		"\"GMs\"": "22",
		"\"Plays\"": "59",
		"\"Sec/Snap\"": "28",
		"\"No-Huddle\"": "\"14%\"",
		"\"Pass%\"": "\"60%\"",
		"\"Rush%\"": "\"40%\"",
		"\"Pass\"": "35",
		"\"Rush\"": "24",
		"\"No Play (Penalty)\"": "50"
	},
	{
		"\"Team\"": "\"DEN\"",
		"\"GMs\"": "22",
		"\"Plays\"": "58",
		"\"Sec/Snap\"": "28",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"56%\"",
		"\"Rush%\"": "\"44%\"",
		"\"Pass\"": "32",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "43"
	},
	
]

module.exports = rotovizNeutralScriptOffensivePaceAndRunPassReportLastFiveWeeks;