const rotovizNeutralScriptOffensivePaceAndRunPassReportLastFiveWeeks = [
	{
		"\"Team\"": "\"MIN\"",
		"\"GMs\"": "5",
		"\"Plays\"": "67",
		"\"Sec/Snap\"": "29.8",
		"\"No-Huddle\"": "\"9%\"",
		"\"Pass%\"": "\"54%\"",
		"\"Rush%\"": "\"46%\"",
		"\"Pass\"": "36",
		"\"Rush\"": "31",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"LAR\"",
		"\"GMs\"": "5",
		"\"Plays\"": "55",
		"\"Sec/Snap\"": "27.2",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"56%\"",
		"\"Rush%\"": "\"44%\"",
		"\"Pass\"": "31",
		"\"Rush\"": "24",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"BAL\"",
		"\"GMs\"": "4",
		"\"Plays\"": "59",
		"\"Sec/Snap\"": "26.1",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"59%\"",
		"\"Rush%\"": "\"41%\"",
		"\"Pass\"": "35",
		"\"Rush\"": "24",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"CLE\"",
		"\"GMs\"": "4",
		"\"Plays\"": "60",
		"\"Sec/Snap\"": "26.5",
		"\"No-Huddle\"": "\"8%\"",
		"\"Pass%\"": "\"61%\"",
		"\"Rush%\"": "\"39%\"",
		"\"Pass\"": "36",
		"\"Rush\"": "23",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"DET\"",
		"\"GMs\"": "5",
		"\"Plays\"": "55",
		"\"Sec/Snap\"": "28.3",
		"\"No-Huddle\"": "\"10%\"",
		"\"Pass%\"": "\"52%\"",
		"\"Rush%\"": "\"48%\"",
		"\"Pass\"": "28",
		"\"Rush\"": "26",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"TEN\"",
		"\"GMs\"": "5",
		"\"Plays\"": "60",
		"\"Sec/Snap\"": "31.4",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"48%\"",
		"\"Rush%\"": "\"52%\"",
		"\"Pass\"": "29",
		"\"Rush\"": "31",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"HOU\"",
		"\"GMs\"": "5",
		"\"Plays\"": "69",
		"\"Sec/Snap\"": "29.7",
		"\"No-Huddle\"": "\"5%\"",
		"\"Pass%\"": "\"57%\"",
		"\"Rush%\"": "\"43%\"",
		"\"Pass\"": "39",
		"\"Rush\"": "30",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"IND\"",
		"\"GMs\"": "5",
		"\"Plays\"": "54",
		"\"Sec/Snap\"": "27",
		"\"No-Huddle\"": "\"10%\"",
		"\"Pass%\"": "\"55%\"",
		"\"Rush%\"": "\"45%\"",
		"\"Pass\"": "30",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"GB\"",
		"\"GMs\"": "4",
		"\"Plays\"": "60",
		"\"Sec/Snap\"": "31.1",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"43%\"",
		"\"Rush%\"": "\"57%\"",
		"\"Pass\"": "25",
		"\"Rush\"": "34",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"JAC\"",
		"\"GMs\"": "4",
		"\"Plays\"": "41",
		"\"Sec/Snap\"": "25.7",
		"\"No-Huddle\"": "\"8%\"",
		"\"Pass%\"": "\"58%\"",
		"\"Rush%\"": "\"42%\"",
		"\"Pass\"": "24",
		"\"Rush\"": "17",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"MIA\"",
		"\"GMs\"": "5",
		"\"Plays\"": "66",
		"\"Sec/Snap\"": "31.6",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"57%\"",
		"\"Rush%\"": "\"43%\"",
		"\"Pass\"": "38",
		"\"Rush\"": "28",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"ARI\"",
		"\"GMs\"": "4",
		"\"Plays\"": "52",
		"\"Sec/Snap\"": "28.2",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"53%\"",
		"\"Rush%\"": "\"47%\"",
		"\"Pass\"": "27",
		"\"Rush\"": "24",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"NE\"",
		"\"GMs\"": "5",
		"\"Plays\"": "62",
		"\"Sec/Snap\"": "27.4",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"59%\"",
		"\"Rush%\"": "\"41%\"",
		"\"Pass\"": "36",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"NYJ\"",
		"\"GMs\"": "4",
		"\"Plays\"": "58",
		"\"Sec/Snap\"": "28.2",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"57%\"",
		"\"Rush%\"": "\"43%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"TB\"",
		"\"GMs\"": "4",
		"\"Plays\"": "56",
		"\"Sec/Snap\"": "27.6",
		"\"No-Huddle\"": "\"5%\"",
		"\"Pass%\"": "\"59%\"",
		"\"Rush%\"": "\"41%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "23",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"ATL\"",
		"\"GMs\"": "4",
		"\"Plays\"": "62",
		"\"Sec/Snap\"": "28.8",
		"\"No-Huddle\"": "\"14%\"",
		"\"Pass%\"": "\"51%\"",
		"\"Rush%\"": "\"49%\"",
		"\"Pass\"": "32",
		"\"Rush\"": "30",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"CHI\"",
		"\"GMs\"": "5",
		"\"Plays\"": "61",
		"\"Sec/Snap\"": "28.8",
		"\"No-Huddle\"": "\"25%\"",
		"\"Pass%\"": "\"56%\"",
		"\"Rush%\"": "\"44%\"",
		"\"Pass\"": "34",
		"\"Rush\"": "27",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"WAS\"",
		"\"GMs\"": "5",
		"\"Plays\"": "60",
		"\"Sec/Snap\"": "25.1",
		"\"No-Huddle\"": "\"62%\"",
		"\"Pass%\"": "\"53%\"",
		"\"Rush%\"": "\"47%\"",
		"\"Pass\"": "31",
		"\"Rush\"": "28",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"LAC\"",
		"\"GMs\"": "4",
		"\"Plays\"": "58",
		"\"Sec/Snap\"": "29",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"54%\"",
		"\"Rush%\"": "\"46%\"",
		"\"Pass\"": "31",
		"\"Rush\"": "27",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"NO\"",
		"\"GMs\"": "4",
		"\"Plays\"": "68",
		"\"Sec/Snap\"": "28.2",
		"\"No-Huddle\"": "\"8%\"",
		"\"Pass%\"": "\"49%\"",
		"\"Rush%\"": "\"51%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "35",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"SEA\"",
		"\"GMs\"": "4",
		"\"Plays\"": "60",
		"\"Sec/Snap\"": "28.2",
		"\"No-Huddle\"": "\"21%\"",
		"\"Pass%\"": "\"58%\"",
		"\"Rush%\"": "\"42%\"",
		"\"Pass\"": "35",
		"\"Rush\"": "26",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"BUF\"",
		"\"GMs\"": "4",
		"\"Plays\"": "64",
		"\"Sec/Snap\"": "29.5",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"60%\"",
		"\"Rush%\"": "\"40%\"",
		"\"Pass\"": "39",
		"\"Rush\"": "26",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"CIN\"",
		"\"GMs\"": "4",
		"\"Plays\"": "78",
		"\"Sec/Snap\"": "26.6",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"71%\"",
		"\"Rush%\"": "\"29%\"",
		"\"Pass\"": "55",
		"\"Rush\"": "23",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"PHI\"",
		"\"GMs\"": "5",
		"\"Plays\"": "65",
		"\"Sec/Snap\"": "31.7",
		"\"No-Huddle\"": "\"27%\"",
		"\"Pass%\"": "\"43%\"",
		"\"Rush%\"": "\"57%\"",
		"\"Pass\"": "28",
		"\"Rush\"": "37",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"DEN\"",
		"\"GMs\"": "5",
		"\"Plays\"": "63",
		"\"Sec/Snap\"": "27.9",
		"\"No-Huddle\"": "\"17%\"",
		"\"Pass%\"": "\"60%\"",
		"\"Rush%\"": "\"40%\"",
		"\"Pass\"": "38",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"CAR\"",
		"\"GMs\"": "4",
		"\"Plays\"": "51",
		"\"Sec/Snap\"": "29.4",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"52%\"",
		"\"Rush%\"": "\"48%\"",
		"\"Pass\"": "26",
		"\"Rush\"": "24",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"KC\"",
		"\"GMs\"": "5",
		"\"Plays\"": "66",
		"\"Sec/Snap\"": "29.2",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"58%\"",
		"\"Rush%\"": "\"42%\"",
		"\"Pass\"": "38",
		"\"Rush\"": "28",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"LV\"",
		"\"GMs\"": "4",
		"\"Plays\"": "46",
		"\"Sec/Snap\"": "30.4",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"60%\"",
		"\"Rush%\"": "\"40%\"",
		"\"Pass\"": "27",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"DAL\"",
		"\"GMs\"": "5",
		"\"Plays\"": "56",
		"\"Sec/Snap\"": "28.9",
		"\"No-Huddle\"": "\"5%\"",
		"\"Pass%\"": "\"58%\"",
		"\"Rush%\"": "\"42%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "23",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"SF\"",
		"\"GMs\"": "4",
		"\"Plays\"": "59",
		"\"Sec/Snap\"": "31.9",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"52%\"",
		"\"Rush%\"": "\"48%\"",
		"\"Pass\"": "30",
		"\"Rush\"": "28",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"PIT\"",
		"\"GMs\"": "4",
		"\"Plays\"": "70",
		"\"Sec/Snap\"": "28.4",
		"\"No-Huddle\"": "\"23%\"",
		"\"Pass%\"": "\"48%\"",
		"\"Rush%\"": "\"52%\"",
		"\"Pass\"": "34",
		"\"Rush\"": "36",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"NYG\"",
		"\"GMs\"": "4",
		"\"Plays\"": "48",
		"\"Sec/Snap\"": "27.6",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"49%\"",
		"\"Rush%\"": "\"51%\"",
		"\"Pass\"": "23",
		"\"Rush\"": "24",
		"\"No Play (Penalty)\"": "3"
	},
	
]

module.exports = rotovizNeutralScriptOffensivePaceAndRunPassReportLastFiveWeeks;