const rotovizNegativeScriptOffensivePaceAndRunPassReportLastFiveWeeks = [
	{
		"\"Team\"": "\"SEA\"",
		"\"GMs\"": "3",
		"\"Plays\"": "56",
		"\"Sec/Snap\"": "20",
		"\"No-Huddle\"": "\"36%\"",
		"\"Pass%\"": "\"77%\"",
		"\"Rush%\"": "\"23%\"",
		"\"Pass\"": "44",
		"\"Rush\"": "13",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"JAC\"",
		"\"GMs\"": "4",
		"\"Plays\"": "50",
		"\"Sec/Snap\"": "26.4",
		"\"No-Huddle\"": "\"26%\"",
		"\"Pass%\"": "\"65%\"",
		"\"Rush%\"": "\"35%\"",
		"\"Pass\"": "33",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"WAS\"",
		"\"GMs\"": "2",
		"\"Plays\"": "20",
		"\"Sec/Snap\"": "23.8",
		"\"No-Huddle\"": "\"61%\"",
		"\"Pass%\"": "\"69%\"",
		"\"Rush%\"": "\"31%\"",
		"\"Pass\"": "14",
		"\"Rush\"": "6",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"ARI\"",
		"\"GMs\"": "2",
		"\"Plays\"": "30",
		"\"Sec/Snap\"": "24.3",
		"\"No-Huddle\"": "\"19%\"",
		"\"Pass%\"": "\"64%\"",
		"\"Rush%\"": "\"36%\"",
		"\"Pass\"": "19",
		"\"Rush\"": "11",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"NE\"",
		"\"GMs\"": "3",
		"\"Plays\"": "49",
		"\"Sec/Snap\"": "23.2",
		"\"No-Huddle\"": "\"11%\"",
		"\"Pass%\"": "\"69%\"",
		"\"Rush%\"": "\"31%\"",
		"\"Pass\"": "34",
		"\"Rush\"": "15",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"NO\"",
		"\"GMs\"": "3",
		"\"Plays\"": "74",
		"\"Sec/Snap\"": "20.8",
		"\"No-Huddle\"": "\"26%\"",
		"\"Pass%\"": "\"71%\"",
		"\"Rush%\"": "\"29%\"",
		"\"Pass\"": "52",
		"\"Rush\"": "21",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"CLE\"",
		"\"GMs\"": "3",
		"\"Plays\"": "88",
		"\"Sec/Snap\"": "24.4",
		"\"No-Huddle\"": "\"19%\"",
		"\"Pass%\"": "\"70%\"",
		"\"Rush%\"": "\"30%\"",
		"\"Pass\"": "62",
		"\"Rush\"": "26",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"TEN\"",
		"\"GMs\"": "4",
		"\"Plays\"": "55",
		"\"Sec/Snap\"": "27.1",
		"\"No-Huddle\"": "\"9%\"",
		"\"Pass%\"": "\"64%\"",
		"\"Rush%\"": "\"36%\"",
		"\"Pass\"": "35",
		"\"Rush\"": "20",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"IND\"",
		"\"GMs\"": "5",
		"\"Plays\"": "64",
		"\"Sec/Snap\"": "25.9",
		"\"No-Huddle\"": "\"17%\"",
		"\"Pass%\"": "\"60%\"",
		"\"Rush%\"": "\"40%\"",
		"\"Pass\"": "38",
		"\"Rush\"": "26",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"DEN\"",
		"\"GMs\"": "3",
		"\"Plays\"": "39",
		"\"Sec/Snap\"": "23.7",
		"\"No-Huddle\"": "\"22%\"",
		"\"Pass%\"": "\"64%\"",
		"\"Rush%\"": "\"36%\"",
		"\"Pass\"": "25",
		"\"Rush\"": "14",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"LV\"",
		"\"GMs\"": "4",
		"\"Plays\"": "78",
		"\"Sec/Snap\"": "23.1",
		"\"No-Huddle\"": "\"19%\"",
		"\"Pass%\"": "\"68%\"",
		"\"Rush%\"": "\"32%\"",
		"\"Pass\"": "53",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "4"
	},
	{
		"\"Team\"": "\"ATL\"",
		"\"GMs\"": "4",
		"\"Plays\"": "44",
		"\"Sec/Snap\"": "26.9",
		"\"No-Huddle\"": "\"20%\"",
		"\"Pass%\"": "\"52%\"",
		"\"Rush%\"": "\"48%\"",
		"\"Pass\"": "23",
		"\"Rush\"": "21",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"CAR\"",
		"\"GMs\"": "3",
		"\"Plays\"": "40",
		"\"Sec/Snap\"": "25.4",
		"\"No-Huddle\"": "\"11%\"",
		"\"Pass%\"": "\"63%\"",
		"\"Rush%\"": "\"37%\"",
		"\"Pass\"": "25",
		"\"Rush\"": "15",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"DAL\"",
		"\"GMs\"": "4",
		"\"Plays\"": "74",
		"\"Sec/Snap\"": "21.6",
		"\"No-Huddle\"": "\"21%\"",
		"\"Pass%\"": "\"71%\"",
		"\"Rush%\"": "\"29%\"",
		"\"Pass\"": "52",
		"\"Rush\"": "22",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"NYG\"",
		"\"GMs\"": "5",
		"\"Plays\"": "77",
		"\"Sec/Snap\"": "26",
		"\"No-Huddle\"": "\"21%\"",
		"\"Pass%\"": "\"60%\"",
		"\"Rush%\"": "\"40%\"",
		"\"Pass\"": "46",
		"\"Rush\"": "31",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"NYJ\"",
		"\"GMs\"": "5",
		"\"Plays\"": "66",
		"\"Sec/Snap\"": "26.8",
		"\"No-Huddle\"": "\"14%\"",
		"\"Pass%\"": "\"69%\"",
		"\"Rush%\"": "\"31%\"",
		"\"Pass\"": "45",
		"\"Rush\"": "20",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"BUF\"",
		"\"GMs\"": "2",
		"\"Plays\"": "8",
		"\"Sec/Snap\"": "15.3",
		"\"No-Huddle\"": "\"12%\"",
		"\"Pass%\"": "\"88%\"",
		"\"Rush%\"": "\"12%\"",
		"\"Pass\"": "7",
		"\"Rush\"": "1",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"DET\"",
		"\"GMs\"": "2",
		"\"Plays\"": "16",
		"\"Sec/Snap\"": "26.7",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"52%\"",
		"\"Rush%\"": "\"48%\"",
		"\"Pass\"": "8",
		"\"Rush\"": "8",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"MIN\"",
		"\"GMs\"": "3",
		"\"Plays\"": "47",
		"\"Sec/Snap\"": "30",
		"\"No-Huddle\"": "\"12%\"",
		"\"Pass%\"": "\"68%\"",
		"\"Rush%\"": "\"32%\"",
		"\"Pass\"": "32",
		"\"Rush\"": "15",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"SF\"",
		"\"GMs\"": "2",
		"\"Plays\"": "27",
		"\"Sec/Snap\"": "20.8",
		"\"No-Huddle\"": "\"9%\"",
		"\"Pass%\"": "\"64%\"",
		"\"Rush%\"": "\"36%\"",
		"\"Pass\"": "17",
		"\"Rush\"": "9",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"PIT\"",
		"\"GMs\"": "2",
		"\"Plays\"": "13",
		"\"Sec/Snap\"": "25.2",
		"\"No-Huddle\"": "\"17%\"",
		"\"Pass%\"": "\"72%\"",
		"\"Rush%\"": "\"28%\"",
		"\"Pass\"": "9",
		"\"Rush\"": "4",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"BAL\"",
		"\"GMs\"": "2",
		"\"Plays\"": "18",
		"\"Sec/Snap\"": "30.1",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"49%\"",
		"\"Rush%\"": "\"51%\"",
		"\"Pass\"": "9",
		"\"Rush\"": "9",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"TB\"",
		"\"GMs\"": "4",
		"\"Plays\"": "56",
		"\"Sec/Snap\"": "24.7",
		"\"No-Huddle\"": "\"15%\"",
		"\"Pass%\"": "\"66%\"",
		"\"Rush%\"": "\"34%\"",
		"\"Pass\"": "37",
		"\"Rush\"": "19",
		"\"No Play (Penalty)\"": "2"
	},
	{
		"\"Team\"": "\"LAR\"",
		"\"GMs\"": "2",
		"\"Plays\"": "30",
		"\"Sec/Snap\"": "30.5",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"52%\"",
		"\"Rush%\"": "\"48%\"",
		"\"Pass\"": "16",
		"\"Rush\"": "15",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"HOU\"",
		"\"GMs\"": "2",
		"\"Plays\"": "11",
		"\"Sec/Snap\"": "19.3",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"79%\"",
		"\"Rush%\"": "\"21%\"",
		"\"Pass\"": "9",
		"\"Rush\"": "2",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"CHI\"",
		"\"GMs\"": "3",
		"\"Plays\"": "56",
		"\"Sec/Snap\"": "23.2",
		"\"No-Huddle\"": "\"30%\"",
		"\"Pass%\"": "\"68%\"",
		"\"Rush%\"": "\"32%\"",
		"\"Pass\"": "38",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "3"
	},
	{
		"\"Team\"": "\"PHI\"",
		"\"GMs\"": "1",
		"\"Plays\"": "11",
		"\"Sec/Snap\"": "26.1",
		"\"No-Huddle\"": "\"24%\"",
		"\"Pass%\"": "\"41%\"",
		"\"Rush%\"": "\"59%\"",
		"\"Pass\"": "4",
		"\"Rush\"": "6",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"CIN\"",
		"\"GMs\"": "3",
		"\"Plays\"": "14",
		"\"Sec/Snap\"": "27.2",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"67%\"",
		"\"Rush%\"": "\"33%\"",
		"\"Pass\"": "9",
		"\"Rush\"": "5",
		"\"No Play (Penalty)\"": "0"
	},
	{
		"\"Team\"": "\"MIA\"",
		"\"GMs\"": "1",
		"\"Plays\"": "17",
		"\"Sec/Snap\"": "30.2",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"50%\"",
		"\"Rush%\"": "\"50%\"",
		"\"Pass\"": "9",
		"\"Rush\"": "9",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"GB\"",
		"\"GMs\"": "1",
		"\"Plays\"": "21",
		"\"Sec/Snap\"": "22.1",
		"\"No-Huddle\"": "\"27%\"",
		"\"Pass%\"": "\"73%\"",
		"\"Rush%\"": "\"27%\"",
		"\"Pass\"": "15",
		"\"Rush\"": "6",
		"\"No Play (Penalty)\"": "1"
	},
	{
		"\"Team\"": "\"KC\"",
		"\"GMs\"": "2",
		"\"Plays\"": "28",
		"\"Sec/Snap\"": "29.7",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"58%\"",
		"\"Rush%\"": "\"42%\"",
		"\"Pass\"": "16",
		"\"Rush\"": "12",
		"\"No Play (Penalty)\"": "0"
	},
	
]

module.exports = rotovizNegativeScriptOffensivePaceAndRunPassReportLastFiveWeeks;