const rotovizPositiveScriptOffensivePaceAndRunPassReportLastFiveWeeks = [
	{
		"\"Team\"": "\"BUF\"",
		"\"GMs\"": "19",
		"\"Plays\"": "38",
		"\"Sec/Snap\"": "28.9",
		"\"No-Huddle\"": "\"5%\"",
		"\"Pass%\"": "\"52%\"",
		"\"Rush%\"": "\"48%\"",
		"\"Pass\"": "20",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "20"
	},
	{
		"\"Team\"": "\"ATL\"",
		"\"GMs\"": "9",
		"\"Plays\"": "11",
		"\"Sec/Snap\"": "29.1",
		"\"No-Huddle\"": "\"9%\"",
		"\"Pass%\"": "\"38%\"",
		"\"Rush%\"": "\"62%\"",
		"\"Pass\"": "4",
		"\"Rush\"": "7",
		"\"No Play (Penalty)\"": "29"
	},
	{
		"\"Team\"": "\"CLE\"",
		"\"GMs\"": "14",
		"\"Plays\"": "27",
		"\"Sec/Snap\"": "30.7",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"33%\"",
		"\"Rush%\"": "\"67%\"",
		"\"Pass\"": "9",
		"\"Rush\"": "18",
		"\"No Play (Penalty)\"": "26"
	},
	{
		"\"Team\"": "\"SF\"",
		"\"GMs\"": "23",
		"\"Plays\"": "42",
		"\"Sec/Snap\"": "31.4",
		"\"No-Huddle\"": "\"5%\"",
		"\"Pass%\"": "\"41%\"",
		"\"Rush%\"": "\"59%\"",
		"\"Pass\"": "17",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "17"
	},
	{
		"\"Team\"": "\"CHI\"",
		"\"GMs\"": "10",
		"\"Plays\"": "16",
		"\"Sec/Snap\"": "29.4",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"40%\"",
		"\"Rush%\"": "\"60%\"",
		"\"Pass\"": "6",
		"\"Rush\"": "10",
		"\"No Play (Penalty)\"": "23"
	},
	{
		"\"Team\"": "\"PIT\"",
		"\"GMs\"": "12",
		"\"Plays\"": "16",
		"\"Sec/Snap\"": "28.7",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"40%\"",
		"\"Rush%\"": "\"60%\"",
		"\"Pass\"": "6",
		"\"Rush\"": "9",
		"\"No Play (Penalty)\"": "26"
	},
	{
		"\"Team\"": "\"DET\"",
		"\"GMs\"": "17",
		"\"Plays\"": "40",
		"\"Sec/Snap\"": "28.7",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"49%\"",
		"\"Rush%\"": "\"51%\"",
		"\"Pass\"": "20",
		"\"Rush\"": "20",
		"\"No Play (Penalty)\"": "21"
	},
	{
		"\"Team\"": "\"PHI\"",
		"\"GMs\"": "25",
		"\"Plays\"": "43",
		"\"Sec/Snap\"": "28.7",
		"\"No-Huddle\"": "\"14%\"",
		"\"Pass%\"": "\"43%\"",
		"\"Rush%\"": "\"57%\"",
		"\"Pass\"": "19",
		"\"Rush\"": "25",
		"\"No Play (Penalty)\"": "17"
	},
	{
		"\"Team\"": "\"HOU\"",
		"\"GMs\"": "9",
		"\"Plays\"": "17",
		"\"Sec/Snap\"": "28.2",
		"\"No-Huddle\"": "\"16%\"",
		"\"Pass%\"": "\"47%\"",
		"\"Rush%\"": "\"53%\"",
		"\"Pass\"": "8",
		"\"Rush\"": "9",
		"\"No Play (Penalty)\"": "24"
	},
	{
		"\"Team\"": "\"MIA\"",
		"\"GMs\"": "11",
		"\"Plays\"": "29",
		"\"Sec/Snap\"": "28.3",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"49%\"",
		"\"Rush%\"": "\"51%\"",
		"\"Pass\"": "14",
		"\"Rush\"": "15",
		"\"No Play (Penalty)\"": "21"
	},
	{
		"\"Team\"": "\"BAL\"",
		"\"GMs\"": "24",
		"\"Plays\"": "43",
		"\"Sec/Snap\"": "29.4",
		"\"No-Huddle\"": "\"11%\"",
		"\"Pass%\"": "\"45%\"",
		"\"Rush%\"": "\"55%\"",
		"\"Pass\"": "20",
		"\"Rush\"": "24",
		"\"No Play (Penalty)\"": "22"
	},
	{
		"\"Team\"": "\"WAS\"",
		"\"GMs\"": "10",
		"\"Plays\"": "17",
		"\"Sec/Snap\"": "31",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"46%\"",
		"\"Rush%\"": "\"54%\"",
		"\"Pass\"": "8",
		"\"Rush\"": "9",
		"\"No Play (Penalty)\"": "24"
	},
	{
		"\"Team\"": "\"JAC\"",
		"\"GMs\"": "16",
		"\"Plays\"": "28",
		"\"Sec/Snap\"": "28.7",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"48%\"",
		"\"Rush%\"": "\"52%\"",
		"\"Pass\"": "14",
		"\"Rush\"": "15",
		"\"No Play (Penalty)\"": "19"
	},
	{
		"\"Team\"": "\"TEN\"",
		"\"GMs\"": "13",
		"\"Plays\"": "23",
		"\"Sec/Snap\"": "29.9",
		"\"No-Huddle\"": "\"2%\"",
		"\"Pass%\"": "\"40%\"",
		"\"Rush%\"": "\"60%\"",
		"\"Pass\"": "9",
		"\"Rush\"": "14",
		"\"No Play (Penalty)\"": "26"
	},
	{
		"\"Team\"": "\"KC\"",
		"\"GMs\"": "23",
		"\"Plays\"": "44",
		"\"Sec/Snap\"": "28",
		"\"No-Huddle\"": "\"0%\"",
		"\"Pass%\"": "\"53%\"",
		"\"Rush%\"": "\"47%\"",
		"\"Pass\"": "23",
		"\"Rush\"": "21",
		"\"No Play (Penalty)\"": "20"
	},
	{
		"\"Team\"": "\"LAC\"",
		"\"GMs\"": "17",
		"\"Plays\"": "34",
		"\"Sec/Snap\"": "28.4",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"56%\"",
		"\"Rush%\"": "\"44%\"",
		"\"Pass\"": "19",
		"\"Rush\"": "15",
		"\"No Play (Penalty)\"": "23"
	},
	{
		"\"Team\"": "\"MIN\"",
		"\"GMs\"": "16",
		"\"Plays\"": "25",
		"\"Sec/Snap\"": "28.8",
		"\"No-Huddle\"": "\"18%\"",
		"\"Pass%\"": "\"53%\"",
		"\"Rush%\"": "\"47%\"",
		"\"Pass\"": "13",
		"\"Rush\"": "12",
		"\"No Play (Penalty)\"": "19"
	},
	{
		"\"Team\"": "\"TB\"",
		"\"GMs\"": "13",
		"\"Plays\"": "21",
		"\"Sec/Snap\"": "26.9",
		"\"No-Huddle\"": "\"9%\"",
		"\"Pass%\"": "\"50%\"",
		"\"Rush%\"": "\"50%\"",
		"\"Pass\"": "11",
		"\"Rush\"": "11",
		"\"No Play (Penalty)\"": "24"
	},
	{
		"\"Team\"": "\"NE\"",
		"\"GMs\"": "10",
		"\"Plays\"": "17",
		"\"Sec/Snap\"": "28.1",
		"\"No-Huddle\"": "\"7%\"",
		"\"Pass%\"": "\"48%\"",
		"\"Rush%\"": "\"52%\"",
		"\"Pass\"": "8",
		"\"Rush\"": "9",
		"\"No Play (Penalty)\"": "24"
	},
	{
		"\"Team\"": "\"LAR\"",
		"\"GMs\"": "10",
		"\"Plays\"": "20",
		"\"Sec/Snap\"": "31.6",
		"\"No-Huddle\"": "\"5%\"",
		"\"Pass%\"": "\"48%\"",
		"\"Rush%\"": "\"52%\"",
		"\"Pass\"": "10",
		"\"Rush\"": "11",
		"\"No Play (Penalty)\"": "23"
	},
	{
		"\"Team\"": "\"DAL\"",
		"\"GMs\"": "18",
		"\"Plays\"": "40",
		"\"Sec/Snap\"": "28.8",
		"\"No-Huddle\"": "\"6%\"",
		"\"Pass%\"": "\"46%\"",
		"\"Rush%\"": "\"54%\"",
		"\"Pass\"": "18",
		"\"Rush\"": "21",
		"\"No Play (Penalty)\"": "19"
	},
	{
		"\"Team\"": "\"DEN\"",
		"\"GMs\"": "10",
		"\"Plays\"": "11",
		"\"Sec/Snap\"": "24.6",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"42%\"",
		"\"Rush%\"": "\"58%\"",
		"\"Pass\"": "5",
		"\"Rush\"": "6",
		"\"No Play (Penalty)\"": "35"
	},
	{
		"\"Team\"": "\"LV\"",
		"\"GMs\"": "15",
		"\"Plays\"": "19",
		"\"Sec/Snap\"": "29.7",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"49%\"",
		"\"Rush%\"": "\"51%\"",
		"\"Pass\"": "9",
		"\"Rush\"": "10",
		"\"No Play (Penalty)\"": "21"
	},
	{
		"\"Team\"": "\"GB\"",
		"\"GMs\"": "9",
		"\"Plays\"": "20",
		"\"Sec/Snap\"": "31",
		"\"No-Huddle\"": "\"1%\"",
		"\"Pass%\"": "\"44%\"",
		"\"Rush%\"": "\"56%\"",
		"\"Pass\"": "9",
		"\"Rush\"": "11",
		"\"No Play (Penalty)\"": "23"
	},
	{
		"\"Team\"": "\"CAR\"",
		"\"GMs\"": "11",
		"\"Plays\"": "23",
		"\"Sec/Snap\"": "30.5",
		"\"No-Huddle\"": "\"4%\"",
		"\"Pass%\"": "\"36%\"",
		"\"Rush%\"": "\"64%\"",
		"\"Pass\"": "8",
		"\"Rush\"": "15",
		"\"No Play (Penalty)\"": "22"
	},
	{
		"\"Team\"": "\"IND\"",
		"\"GMs\"": "10",
		"\"Plays\"": "14",
		"\"Sec/Snap\"": "27.1",
		"\"No-Huddle\"": "\"9%\"",
		"\"Pass%\"": "\"49%\"",
		"\"Rush%\"": "\"51%\"",
		"\"Pass\"": "7",
		"\"Rush\"": "7",
		"\"No Play (Penalty)\"": "23"
	},
	{
		"\"Team\"": "\"CIN\"",
		"\"GMs\"": "18",
		"\"Plays\"": "35",
		"\"Sec/Snap\"": "29.3",
		"\"No-Huddle\"": "\"3%\"",
		"\"Pass%\"": "\"56%\"",
		"\"Rush%\"": "\"44%\"",
		"\"Pass\"": "20",
		"\"Rush\"": "16",
		"\"No Play (Penalty)\"": "19"
	},
	{
		"\"Team\"": "\"SEA\"",
		"\"GMs\"": "10",
		"\"Plays\"": "23",
		"\"Sec/Snap\"": "26.7",
		"\"No-Huddle\"": "\"9%\"",
		"\"Pass%\"": "\"44%\"",
		"\"Rush%\"": "\"56%\"",
		"\"Pass\"": "10",
		"\"Rush\"": "13",
		"\"No Play (Penalty)\"": "26"
	},
	{
		"\"Team\"": "\"NYG\"",
		"\"GMs\"": "8",
		"\"Plays\"": "11",
		"\"Sec/Snap\"": "28.1",
		"\"No-Huddle\"": "\"8%\"",
		"\"Pass%\"": "\"36%\"",
		"\"Rush%\"": "\"64%\"",
		"\"Pass\"": "4",
		"\"Rush\"": "7",
		"\"No Play (Penalty)\"": "19"
	},
	{
		"\"Team\"": "\"NYJ\"",
		"\"GMs\"": "7",
		"\"Plays\"": "8",
		"\"Sec/Snap\"": "28.3",
		"\"No-Huddle\"": "\"1%\"",
		"\"Pass%\"": "\"26%\"",
		"\"Rush%\"": "\"74%\"",
		"\"Pass\"": "2",
		"\"Rush\"": "6",
		"\"No Play (Penalty)\"": "27"
	},
	{
		"\"Team\"": "\"ARI\"",
		"\"GMs\"": "7",
		"\"Plays\"": "13",
		"\"Sec/Snap\"": "27.5",
		"\"No-Huddle\"": "\"5%\"",
		"\"Pass%\"": "\"45%\"",
		"\"Rush%\"": "\"55%\"",
		"\"Pass\"": "6",
		"\"Rush\"": "7",
		"\"No Play (Penalty)\"": "23"
	},
	{
		"\"Team\"": "\"NO\"",
		"\"GMs\"": "15",
		"\"Plays\"": "25",
		"\"Sec/Snap\"": "30.9",
		"\"No-Huddle\"": "\"1%\"",
		"\"Pass%\"": "\"41%\"",
		"\"Rush%\"": "\"59%\"",
		"\"Pass\"": "10",
		"\"Rush\"": "15",
		"\"No Play (Penalty)\"": "20"
	},
	
]

module.exports = rotovizPositiveScriptOffensivePaceAndRunPassReportLastFiveWeeks;