const rvDynastyRankingsTEP = [
	{
		"\"\"": "\"1\"",
		"\"Rank\"": "1",
		"\"Player\"": "\"C.J. Stroud\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "1",
		"\"AVGRank\"": "1",
		"\"AVGTier\"": "1",
		"\"Siegele8.25\"": "1"
	},
	{
		"\"\"": "\"2\"",
		"\"Rank\"": "2",
		"\"Player\"": "\"Josh Allen\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "2",
		"\"AVGRank\"": "2",
		"\"AVGTier\"": "1",
		"\"Siegele8.25\"": "2"
	},
	{
		"\"\"": "\"3\"",
		"\"Rank\"": "3",
		"\"Player\"": "\"Patrick Mahomes\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "3",
		"\"AVGRank\"": "3",
		"\"AVGTier\"": "1",
		"\"Siegele8.25\"": "3"
	},
	{
		"\"\"": "\"4\"",
		"\"Rank\"": "4",
		"\"Player\"": "\"Jalen Hurts\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "4",
		"\"AVGRank\"": "4",
		"\"AVGTier\"": "1",
		"\"Siegele8.25\"": "4"
	},
	{
		"\"\"": "\"5\"",
		"\"Rank\"": "5",
		"\"Player\"": "\"CeeDee Lamb\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "1",
		"\"AVGRank\"": "5",
		"\"AVGTier\"": "1",
		"\"Siegele8.25\"": "5"
	},
	{
		"\"\"": "\"6\"",
		"\"Rank\"": "6",
		"\"Player\"": "\"Ja'Marr Chase\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "2",
		"\"AVGRank\"": "7",
		"\"AVGTier\"": "1",
		"\"Siegele8.25\"": "7"
	},
	{
		"\"\"": "\"7\"",
		"\"Rank\"": "7",
		"\"Player\"": "\"Caleb Williams\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "5",
		"\"AVGRank\"": "6",
		"\"AVGTier\"": "1",
		"\"Siegele8.25\"": "6"
	},
	{
		"\"\"": "\"8\"",
		"\"Rank\"": "8",
		"\"Player\"": "\"Justin Jefferson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "3",
		"\"AVGRank\"": "8",
		"\"AVGTier\"": "1",
		"\"Siegele8.25\"": "8"
	},
	{
		"\"\"": "\"9\"",
		"\"Rank\"": "9",
		"\"Player\"": "\"Breece Hall\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "1",
		"\"AVGRank\"": "10",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "10"
	},
	{
		"\"\"": "\"10\"",
		"\"Rank\"": "10",
		"\"Player\"": "\"Jayden Daniels\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "6",
		"\"AVGRank\"": "9",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "9"
	},
	{
		"\"\"": "\"11\"",
		"\"Rank\"": "11",
		"\"Player\"": "\"Bijan Robinson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "2",
		"\"AVGRank\"": "11",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "11"
	},
	{
		"\"\"": "\"12\"",
		"\"Rank\"": "12",
		"\"Player\"": "\"Sam LaPorta\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "1",
		"\"AVGRank\"": "12",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "12"
	},
	{
		"\"\"": "\"13\"",
		"\"Rank\"": "13",
		"\"Player\"": "\"Garrett Wilson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "4",
		"\"AVGRank\"": "13",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "13"
	},
	{
		"\"\"": "\"14\"",
		"\"Rank\"": "14",
		"\"Player\"": "\"Jordan Love\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "7",
		"\"AVGRank\"": "14",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "14"
	},
	{
		"\"\"": "\"15\"",
		"\"Rank\"": "15",
		"\"Player\"": "\"Amon-Ra St. Brown\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "5",
		"\"AVGRank\"": "15",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "15"
	},
	{
		"\"\"": "\"16\"",
		"\"Rank\"": "16",
		"\"Player\"": "\"Malik Nabers\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "6",
		"\"AVGRank\"": "16",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "16"
	},
	{
		"\"\"": "\"17\"",
		"\"Rank\"": "17",
		"\"Player\"": "\"Trey McBride\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "2",
		"\"AVGRank\"": "18",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "18"
	},
	{
		"\"\"": "\"18\"",
		"\"Rank\"": "18",
		"\"Player\"": "\"Marvin Harrison\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "7",
		"\"AVGRank\"": "17",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "17"
	},
	{
		"\"\"": "\"19\"",
		"\"Rank\"": "19",
		"\"Player\"": "\"Anthony Richardson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "8",
		"\"AVGRank\"": "19",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "19"
	},
	{
		"\"\"": "\"20\"",
		"\"Rank\"": "20",
		"\"Player\"": "\"Puka Nacua\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "8",
		"\"AVGRank\"": "20",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "20"
	},
	{
		"\"\"": "\"21\"",
		"\"Rank\"": "21",
		"\"Player\"": "\"Lamar Jackson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "9",
		"\"AVGRank\"": "22",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "22"
	},
	{
		"\"\"": "\"22\"",
		"\"Rank\"": "22",
		"\"Player\"": "\"Brock Bowers\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "3",
		"\"AVGRank\"": "21",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "21"
	},
	{
		"\"\"": "\"23\"",
		"\"Rank\"": "23",
		"\"Player\"": "\"Kyler Murray\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "10",
		"\"AVGRank\"": "23",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "23"
	},
	{
		"\"\"": "\"24\"",
		"\"Rank\"": "24",
		"\"Player\"": "\"Joe Burrow\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "11",
		"\"AVGRank\"": "24",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "24"
	},
	{
		"\"\"": "\"25\"",
		"\"Rank\"": "25",
		"\"Player\"": "\"Jahmyr Gibbs\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "3",
		"\"AVGRank\"": "25",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "25"
	},
	{
		"\"\"": "\"26\"",
		"\"Rank\"": "26",
		"\"Player\"": "\"Chris Olave\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "9",
		"\"AVGRank\"": "26",
		"\"AVGTier\"": "2",
		"\"Siegele8.25\"": "26"
	},
	{
		"\"\"": "\"27\"",
		"\"Rank\"": "27",
		"\"Player\"": "\"Nico Collins\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "10",
		"\"AVGRank\"": "27",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "27"
	},
	{
		"\"\"": "\"28\"",
		"\"Rank\"": "28",
		"\"Player\"": "\"Christian McCaffrey\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "4",
		"\"AVGRank\"": "28",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "28"
	},
	{
		"\"\"": "\"29\"",
		"\"Rank\"": "29",
		"\"Player\"": "\"Drake London\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "11",
		"\"AVGRank\"": "29",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "29"
	},
	{
		"\"\"": "\"30\"",
		"\"Rank\"": "30",
		"\"Player\"": "\"Devon Achane\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "5",
		"\"AVGRank\"": "30",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "30"
	},
	{
		"\"\"": "\"31\"",
		"\"Rank\"": "31",
		"\"Player\"": "\"A.J. Brown\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "12",
		"\"AVGRank\"": "31",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "31"
	},
	{
		"\"\"": "\"32\"",
		"\"Rank\"": "32",
		"\"Player\"": "\"Trevor Lawrence\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "12",
		"\"AVGRank\"": "33",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "33"
	},
	{
		"\"\"": "\"33\"",
		"\"Rank\"": "33",
		"\"Player\"": "\"Xavier Worthy\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "13",
		"\"AVGRank\"": "32",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "32"
	},
	{
		"\"\"": "\"34\"",
		"\"Rank\"": "34",
		"\"Player\"": "\"Tyreek Hill\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "14",
		"\"AVGRank\"": "34",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "34"
	},
	{
		"\"\"": "\"35\"",
		"\"Rank\"": "35",
		"\"Player\"": "\"Dalton Kincaid\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "4",
		"\"AVGRank\"": "35",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "35"
	},
	{
		"\"\"": "\"36\"",
		"\"Rank\"": "36",
		"\"Player\"": "\"Kyle Pitts\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "5",
		"\"AVGRank\"": "36",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "36"
	},
	{
		"\"\"": "\"37\"",
		"\"Rank\"": "37",
		"\"Player\"": "\"Dak Prescott\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "13",
		"\"AVGRank\"": "37",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "37"
	},
	{
		"\"\"": "\"38\"",
		"\"Rank\"": "38",
		"\"Player\"": "\"Jaylen Waddle\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "15",
		"\"AVGRank\"": "38",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "38"
	},
	{
		"\"\"": "\"39\"",
		"\"Rank\"": "39",
		"\"Player\"": "\"Justin Herbert\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "14",
		"\"AVGRank\"": "39",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "39"
	},
	{
		"\"\"": "\"40\"",
		"\"Rank\"": "40",
		"\"Player\"": "\"Tee Higgins\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "16",
		"\"AVGRank\"": "40",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "40"
	},
	{
		"\"\"": "\"41\"",
		"\"Rank\"": "41",
		"\"Player\"": "\"Brock Purdy\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "15",
		"\"AVGRank\"": "41",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "41"
	},
	{
		"\"\"": "\"42\"",
		"\"Rank\"": "42",
		"\"Player\"": "\"Jonathan Taylor\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "6",
		"\"AVGRank\"": "42",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "42"
	},
	{
		"\"\"": "\"43\"",
		"\"Rank\"": "43",
		"\"Player\"": "\"Zay Flowers\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "17",
		"\"AVGRank\"": "43",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "43"
	},
	{
		"\"\"": "\"44\"",
		"\"Rank\"": "44",
		"\"Player\"": "\"Brandon Aiyuk\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "18",
		"\"AVGRank\"": "44",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "44"
	},
	{
		"\"\"": "\"45\"",
		"\"Rank\"": "45",
		"\"Player\"": "\"Tua Tagovailoa\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "16",
		"\"AVGRank\"": "45",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "45"
	},
	{
		"\"\"": "\"46\"",
		"\"Rank\"": "46",
		"\"Player\"": "\"Rashee Rice\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "19",
		"\"AVGRank\"": "46",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "46"
	},
	{
		"\"\"": "\"47\"",
		"\"Rank\"": "47",
		"\"Player\"": "\"Jared Goff\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "17",
		"\"AVGRank\"": "47",
		"\"AVGTier\"": "3",
		"\"Siegele8.25\"": "47"
	},
	{
		"\"\"": "\"48\"",
		"\"Rank\"": "48",
		"\"Player\"": "\"Jaxon Smith-Njigba\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "20",
		"\"AVGRank\"": "48",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "48"
	},
	{
		"\"\"": "\"49\"",
		"\"Rank\"": "49",
		"\"Player\"": "\"DeVonta Smith\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "21",
		"\"AVGRank\"": "49",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "49"
	},
	{
		"\"\"": "\"50\"",
		"\"Rank\"": "50",
		"\"Player\"": "\"Rome Odunze\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "22",
		"\"AVGRank\"": "50",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "50"
	},
	{
		"\"\"": "\"51\"",
		"\"Rank\"": "51",
		"\"Player\"": "\"Jonathon Brooks\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "7",
		"\"AVGRank\"": "51",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "51"
	},
	{
		"\"\"": "\"52\"",
		"\"Rank\"": "52",
		"\"Player\"": "\"Jayden Reed\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "23",
		"\"AVGRank\"": "52",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "52"
	},
	{
		"\"\"": "\"53\"",
		"\"Rank\"": "53",
		"\"Player\"": "\"DJ Moore\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "24",
		"\"AVGRank\"": "54",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "54"
	},
	{
		"\"\"": "\"54\"",
		"\"Rank\"": "54",
		"\"Player\"": "\"Drake Maye\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "18",
		"\"AVGRank\"": "53",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "53"
	},
	{
		"\"\"": "\"55\"",
		"\"Rank\"": "55",
		"\"Player\"": "\"Tank Dell\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "25",
		"\"AVGRank\"": "56",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "56"
	},
	{
		"\"\"": "\"56\"",
		"\"Rank\"": "55",
		"\"Player\"": "\"Bo Nix\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "19",
		"\"AVGRank\"": "55",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "55"
	},
	{
		"\"\"": "\"57\"",
		"\"Rank\"": "57",
		"\"Player\"": "\"DK Metcalf\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "26",
		"\"AVGRank\"": "57",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "57"
	},
	{
		"\"\"": "\"58\"",
		"\"Rank\"": "58",
		"\"Player\"": "\"Kenneth Walker\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "8",
		"\"AVGRank\"": "58",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "58"
	},
	{
		"\"\"": "\"59\"",
		"\"Rank\"": "59",
		"\"Player\"": "\"Kyren Williams\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "9",
		"\"AVGRank\"": "59",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "59"
	},
	{
		"\"\"": "\"60\"",
		"\"Rank\"": "60",
		"\"Player\"": "\"Travis Etienne\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "10",
		"\"AVGRank\"": "60",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "60"
	},
	{
		"\"\"": "\"61\"",
		"\"Rank\"": "61",
		"\"Player\"": "\"Deebo Samuel\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "27",
		"\"AVGRank\"": "61",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "61"
	},
	{
		"\"\"": "\"62\"",
		"\"Rank\"": "62",
		"\"Player\"": "\"T.J. Hockenson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "6",
		"\"AVGRank\"": "63",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "63"
	},
	{
		"\"\"": "\"63\"",
		"\"Rank\"": "63",
		"\"Player\"": "\"Brian Thomas\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "28",
		"\"AVGRank\"": "62",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "62"
	},
	{
		"\"\"": "\"64\"",
		"\"Rank\"": "64",
		"\"Player\"": "\"Jordan Addison\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "29",
		"\"AVGRank\"": "64",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "64"
	},
	{
		"\"\"": "\"65\"",
		"\"Rank\"": "65",
		"\"Player\"": "\"Mark Andrews\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "7",
		"\"AVGRank\"": "66",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "66"
	},
	{
		"\"\"": "\"66\"",
		"\"Rank\"": "66",
		"\"Player\"": "\"Ladd McConkey\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "30",
		"\"AVGRank\"": "65",
		"\"AVGTier\"": "4",
		"\"Siegele8.25\"": "65"
	},
	{
		"\"\"": "\"67\"",
		"\"Rank\"": "67",
		"\"Player\"": "\"Stefon Diggs\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "31",
		"\"AVGRank\"": "67",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "67"
	},
	{
		"\"\"": "\"68\"",
		"\"Rank\"": "68",
		"\"Player\"": "\"Jameson Williams\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "32",
		"\"AVGRank\"": "68",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "68"
	},
	{
		"\"\"": "\"69\"",
		"\"Rank\"": "69",
		"\"Player\"": "\"George Pickens\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "33",
		"\"AVGRank\"": "69",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "69"
	},
	{
		"\"\"": "\"70\"",
		"\"Rank\"": "70",
		"\"Player\"": "\"Bryce Young\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "20",
		"\"AVGRank\"": "70",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "70"
	},
	{
		"\"\"": "\"71\"",
		"\"Rank\"": "71",
		"\"Player\"": "\"James Cook\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "11",
		"\"AVGRank\"": "71",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "71"
	},
	{
		"\"\"": "\"72\"",
		"\"Rank\"": "72",
		"\"Player\"": "\"Michael Pittman\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "34",
		"\"AVGRank\"": "72",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "72"
	},
	{
		"\"\"": "\"73\"",
		"\"Rank\"": "73",
		"\"Player\"": "\"Mike Evans\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "35",
		"\"AVGRank\"": "73",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "73"
	},
	{
		"\"\"": "\"74\"",
		"\"Rank\"": "74",
		"\"Player\"": "\"Travis Kelce\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "8",
		"\"AVGRank\"": "75",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "75"
	},
	{
		"\"\"": "\"75\"",
		"\"Rank\"": "75",
		"\"Player\"": "\"Keon Coleman\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "36",
		"\"AVGRank\"": "74",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "74"
	},
	{
		"\"\"": "\"76\"",
		"\"Rank\"": "76",
		"\"Player\"": "\"Christian Watson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "37",
		"\"AVGRank\"": "76",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "76"
	},
	{
		"\"\"": "\"77\"",
		"\"Rank\"": "77",
		"\"Player\"": "\"George Kittle\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "9",
		"\"AVGRank\"": "77",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "77"
	},
	{
		"\"\"": "\"78\"",
		"\"Rank\"": "78",
		"\"Player\"": "\"Kirk Cousins\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "21",
		"\"AVGRank\"": "78",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "78"
	},
	{
		"\"\"": "\"79\"",
		"\"Rank\"": "79",
		"\"Player\"": "\"Cooper Kupp\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "38",
		"\"AVGRank\"": "79",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "79"
	},
	{
		"\"\"": "\"80\"",
		"\"Rank\"": "80",
		"\"Player\"": "\"Davante Adams\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "39",
		"\"AVGRank\"": "80",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "80"
	},
	{
		"\"\"": "\"81\"",
		"\"Rank\"": "81",
		"\"Player\"": "\"Deshaun Watson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "22",
		"\"AVGRank\"": "81",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "81"
	},
	{
		"\"\"": "\"82\"",
		"\"Rank\"": "82",
		"\"Player\"": "\"Terry McLaurin\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "40",
		"\"AVGRank\"": "83",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "83"
	},
	{
		"\"\"": "\"83\"",
		"\"Rank\"": "83",
		"\"Player\"": "\"J.J. McCarthy\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "23",
		"\"AVGRank\"": "82",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "82"
	},
	{
		"\"\"": "\"84\"",
		"\"Rank\"": "84",
		"\"Player\"": "\"Diontae Johnson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "41",
		"\"AVGRank\"": "84",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "84"
	},
	{
		"\"\"": "\"85\"",
		"\"Rank\"": "85",
		"\"Player\"": "\"Isiah Pacheco\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "12",
		"\"AVGRank\"": "85",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "85"
	},
	{
		"\"\"": "\"86\"",
		"\"Rank\"": "86",
		"\"Player\"": "\"Saquon Barkley\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "13",
		"\"AVGRank\"": "86",
		"\"AVGTier\"": "5",
		"\"Siegele8.25\"": "86"
	},
	{
		"\"\"": "\"87\"",
		"\"Rank\"": "87",
		"\"Player\"": "\"Geno Smith\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "24",
		"\"AVGRank\"": "87",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "87"
	},
	{
		"\"\"": "\"88\"",
		"\"Rank\"": "88",
		"\"Player\"": "\"Jaylen Warren\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "14",
		"\"AVGRank\"": "88",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "88"
	},
	{
		"\"\"": "\"89\"",
		"\"Rank\"": "89",
		"\"Player\"": "\"Chase Brown\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "15",
		"\"AVGRank\"": "89",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "89"
	},
	{
		"\"\"": "\"90\"",
		"\"Rank\"": "90",
		"\"Player\"": "\"Rhamondre Stevenson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "16",
		"\"AVGRank\"": "90",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "90"
	},
	{
		"\"\"": "\"91\"",
		"\"Rank\"": "91",
		"\"Player\"": "\"Matthew Stafford\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "25",
		"\"AVGRank\"": "92",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "92"
	},
	{
		"\"\"": "\"92\"",
		"\"Rank\"": "92",
		"\"Player\"": "\"Adonai Mitchell\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "42",
		"\"AVGRank\"": "91",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "91"
	},
	{
		"\"\"": "\"93\"",
		"\"Rank\"": "93",
		"\"Player\"": "\"Tyjae Spears\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "17",
		"\"AVGRank\"": "93",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "93"
	},
	{
		"\"\"": "\"94\"",
		"\"Rank\"": "94",
		"\"Player\"": "\"Christian Kirk\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "43",
		"\"AVGRank\"": "94",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "94"
	},
	{
		"\"\"": "\"95\"",
		"\"Rank\"": "95",
		"\"Player\"": "\"David Njoku\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "10",
		"\"AVGRank\"": "95",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "95"
	},
	{
		"\"\"": "\"96\"",
		"\"Rank\"": "96",
		"\"Player\"": "\"Dontayvion Wicks\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "44",
		"\"AVGRank\"": "96",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "96"
	},
	{
		"\"\"": "\"97\"",
		"\"Rank\"": "97",
		"\"Player\"": "\"Evan Engram\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "11",
		"\"AVGRank\"": "97",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "97"
	},
	{
		"\"\"": "\"98\"",
		"\"Rank\"": "98",
		"\"Player\"": "\"Jerry Jeudy\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "45",
		"\"AVGRank\"": "99",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "99"
	},
	{
		"\"\"": "\"99\"",
		"\"Rank\"": "99",
		"\"Player\"": "\"Trey Benson\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "18",
		"\"AVGRank\"": "98",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "98"
	},
	{
		"\"\"": "\"100\"",
		"\"Rank\"": "100",
		"\"Player\"": "\"Justin Fields\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "26",
		"\"AVGRank\"": "100",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "100"
	},
	{
		"\"\"": "\"101\"",
		"\"Rank\"": "101",
		"\"Player\"": "\"Josh Jacobs\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "19",
		"\"AVGRank\"": "101",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "101"
	},
	{
		"\"\"": "\"102\"",
		"\"Rank\"": "102",
		"\"Player\"": "\"Derrick Henry\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "20",
		"\"AVGRank\"": "102",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "102"
	},
	{
		"\"\"": "\"103\"",
		"\"Rank\"": "103",
		"\"Player\"": "\"Javonte Williams\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "21",
		"\"AVGRank\"": "103",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "103"
	},
	{
		"\"\"": "\"104\"",
		"\"Rank\"": "104",
		"\"Player\"": "\"Ja'Lynn Polk\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "46",
		"\"AVGRank\"": "104",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "104"
	},
	{
		"\"\"": "\"105\"",
		"\"Rank\"": "105",
		"\"Player\"": "\"Will Levis\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "27",
		"\"AVGRank\"": "106",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "106"
	},
	{
		"\"\"": "\"106\"",
		"\"Rank\"": "106",
		"\"Player\"": "\"Ben Sinnott\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "12",
		"\"AVGRank\"": "105",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "105"
	},
	{
		"\"\"": "\"107\"",
		"\"Rank\"": "107",
		"\"Player\"": "\"Marquise Brown\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "47",
		"\"AVGRank\"": "107",
		"\"AVGTier\"": "6",
		"\"Siegele8.25\"": "107"
	},
	{
		"\"\"": "\"108\"",
		"\"Rank\"": "108",
		"\"Player\"": "\"Baker Mayfield\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "28",
		"\"AVGRank\"": "108",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "108"
	},
	{
		"\"\"": "\"109\"",
		"\"Rank\"": "109",
		"\"Player\"": "\"Keenan Allen\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "48",
		"\"AVGRank\"": "109",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "109"
	},
	{
		"\"\"": "\"110\"",
		"\"Rank\"": "110",
		"\"Player\"": "\"D'Andre Swift\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "22",
		"\"AVGRank\"": "110",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "110"
	},
	{
		"\"\"": "\"111\"",
		"\"Rank\"": "111",
		"\"Player\"": "\"Amari Cooper\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "49",
		"\"AVGRank\"": "111",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "111"
	},
	{
		"\"\"": "\"112\"",
		"\"Rank\"": "112",
		"\"Player\"": "\"Aaron Rodgers\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "29",
		"\"AVGRank\"": "112",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "112"
	},
	{
		"\"\"": "\"113\"",
		"\"Rank\"": "113",
		"\"Player\"": "\"Derek Carr\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "30",
		"\"AVGRank\"": "113",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "113"
	},
	{
		"\"\"": "\"114\"",
		"\"Rank\"": "114",
		"\"Player\"": "\"Josh Downs\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "50",
		"\"AVGRank\"": "114",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "114"
	},
	{
		"\"\"": "\"115\"",
		"\"Rank\"": "115",
		"\"Player\"": "\"Daniel Jones\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "31",
		"\"AVGRank\"": "115",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "115"
	},
	{
		"\"\"": "\"116\"",
		"\"Rank\"": "116",
		"\"Player\"": "\"Luke Musgrave\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "13",
		"\"AVGRank\"": "116",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "116"
	},
	{
		"\"\"": "\"117\"",
		"\"Rank\"": "117",
		"\"Player\"": "\"Xavier Legette\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "51",
		"\"AVGRank\"": "117",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "117"
	},
	{
		"\"\"": "\"118\"",
		"\"Rank\"": "118",
		"\"Player\"": "\"Braelon Allen\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "23",
		"\"AVGRank\"": "118",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "118"
	},
	{
		"\"\"": "\"119\"",
		"\"Rank\"": "119",
		"\"Player\"": "\"Ricky Pearsall\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "52",
		"\"AVGRank\"": "119",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "119"
	},
	{
		"\"\"": "\"120\"",
		"\"Rank\"": "120",
		"\"Player\"": "\"Jaylen Wright\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "24",
		"\"AVGRank\"": "120",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "120"
	},
	{
		"\"\"": "\"121\"",
		"\"Rank\"": "121",
		"\"Player\"": "\"Jaleel McLaughlin\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "25",
		"\"AVGRank\"": "121",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "121"
	},
	{
		"\"\"": "\"122\"",
		"\"Rank\"": "122",
		"\"Player\"": "\"Zamir White\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "26",
		"\"AVGRank\"": "123",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "123"
	},
	{
		"\"\"": "\"123\"",
		"\"Rank\"": "123",
		"\"Player\"": "\"Blake Corum\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "27",
		"\"AVGRank\"": "122",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "122"
	},
	{
		"\"\"": "\"124\"",
		"\"Rank\"": "124",
		"\"Player\"": "\"Aaron Jones\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "28",
		"\"AVGRank\"": "124",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "124"
	},
	{
		"\"\"": "\"125\"",
		"\"Rank\"": "125",
		"\"Player\"": "\"Najee Harris\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "29",
		"\"AVGRank\"": "126",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "126"
	},
	{
		"\"\"": "\"126\"",
		"\"Rank\"": "126",
		"\"Player\"": "\"Jalen McMillan\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "53",
		"\"AVGRank\"": "125",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "125"
	},
	{
		"\"\"": "\"127\"",
		"\"Rank\"": "127",
		"\"Player\"": "\"Calvin Ridley\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "54",
		"\"AVGRank\"": "128",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "128"
	},
	{
		"\"\"": "\"128\"",
		"\"Rank\"": "128",
		"\"Player\"": "\"Bucky Irving\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "30",
		"\"AVGRank\"": "127",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "127"
	},
	{
		"\"\"": "\"129\"",
		"\"Rank\"": "129",
		"\"Player\"": "\"Cole Kmet\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "14",
		"\"AVGRank\"": "129",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "129"
	},
	{
		"\"\"": "\"130\"",
		"\"Rank\"": "130",
		"\"Player\"": "\"Zach Charbonnet\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "31",
		"\"AVGRank\"": "130",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "130"
	},
	{
		"\"\"": "\"131\"",
		"\"Rank\"": "131",
		"\"Player\"": "\"James Conner\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "32",
		"\"AVGRank\"": "132",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "132"
	},
	{
		"\"\"": "\"132\"",
		"\"Rank\"": "132",
		"\"Player\"": "\"Michael Penix\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "32",
		"\"AVGRank\"": "131",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "131"
	},
	{
		"\"\"": "\"133\"",
		"\"Rank\"": "133",
		"\"Player\"": "\"Marvin Mims\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "55",
		"\"AVGRank\"": "133",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "133"
	},
	{
		"\"\"": "\"134\"",
		"\"Rank\"": "134",
		"\"Player\"": "\"Tyler Allgeier\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "33",
		"\"AVGRank\"": "134",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "134"
	},
	{
		"\"\"": "\"135\"",
		"\"Rank\"": "135",
		"\"Player\"": "\"David Montgomery\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "34",
		"\"AVGRank\"": "135",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "135"
	},
	{
		"\"\"": "\"136\"",
		"\"Rank\"": "136",
		"\"Player\"": "\"Jake Ferguson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "15",
		"\"AVGRank\"": "136",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "136"
	},
	{
		"\"\"": "\"137\"",
		"\"Rank\"": "137",
		"\"Player\"": "\"Courtland Sutton\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "56",
		"\"AVGRank\"": "137",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "137"
	},
	{
		"\"\"": "\"138\"",
		"\"Rank\"": "138",
		"\"Player\"": "\"Pat Freiermuth\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "16",
		"\"AVGRank\"": "139",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "139"
	},
	{
		"\"\"": "\"139\"",
		"\"Rank\"": "139",
		"\"Player\"": "\"MarShawn Lloyd\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "35",
		"\"AVGRank\"": "138",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "138"
	},
	{
		"\"\"": "\"140\"",
		"\"Rank\"": "140",
		"\"Player\"": "\"Wan'Dale Robinson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "57",
		"\"AVGRank\"": "140",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "140"
	},
	{
		"\"\"": "\"141\"",
		"\"Rank\"": "141",
		"\"Player\"": "\"Joe Mixon\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "36",
		"\"AVGRank\"": "141",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "141"
	},
	{
		"\"\"": "\"142\"",
		"\"Rank\"": "142",
		"\"Player\"": "\"Raheem Mostert\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "37",
		"\"AVGRank\"": "142",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "142"
	},
	{
		"\"\"": "\"143\"",
		"\"Rank\"": "143",
		"\"Player\"": "\"Tony Pollard\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "38",
		"\"AVGRank\"": "143",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "143"
	},
	{
		"\"\"": "\"144\"",
		"\"Rank\"": "144",
		"\"Player\"": "\"Audric Estime\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "39",
		"\"AVGRank\"": "144",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "144"
	},
	{
		"\"\"": "\"145\"",
		"\"Rank\"": "145",
		"\"Player\"": "\"Rachaad White\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "40",
		"\"AVGRank\"": "146",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "146"
	},
	{
		"\"\"": "\"146\"",
		"\"Rank\"": "146",
		"\"Player\"": "\"Tyrone Tracy\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "41",
		"\"AVGRank\"": "145",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "145"
	},
	{
		"\"\"": "\"147\"",
		"\"Rank\"": "147",
		"\"Player\"": "\"Ray Davis\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "42",
		"\"AVGRank\"": "147",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "147"
	},
	{
		"\"\"": "\"148\"",
		"\"Rank\"": "148",
		"\"Player\"": "\"Chris Godwin\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "58",
		"\"AVGRank\"": "149",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "149"
	},
	{
		"\"\"": "\"149\"",
		"\"Rank\"": "149",
		"\"Player\"": "\"Ja'Tavion Sanders\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "17",
		"\"AVGRank\"": "148",
		"\"AVGTier\"": "7",
		"\"Siegele8.25\"": "148"
	},
	{
		"\"\"": "\"150\"",
		"\"Rank\"": "150",
		"\"Player\"": "\"Brian Robinson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "43",
		"\"AVGRank\"": "150",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "150"
	},
	{
		"\"\"": "\"151\"",
		"\"Rank\"": "151",
		"\"Player\"": "\"Gardner Minshew\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "33",
		"\"AVGRank\"": "151",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "151"
	},
	{
		"\"\"": "\"152\"",
		"\"Rank\"": "152",
		"\"Player\"": "\"Alvin Kamara\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "44",
		"\"AVGRank\"": "152",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "152"
	},
	{
		"\"\"": "\"153\"",
		"\"Rank\"": "153",
		"\"Player\"": "\"Devin Singletary\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "45",
		"\"AVGRank\"": "153",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "153"
	},
	{
		"\"\"": "\"154\"",
		"\"Rank\"": "154",
		"\"Player\"": "\"Will Shipley\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "46",
		"\"AVGRank\"": "154",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "154"
	},
	{
		"\"\"": "\"155\"",
		"\"Rank\"": "155",
		"\"Player\"": "\"DeAndre Hopkins\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "59",
		"\"AVGRank\"": "156",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "156"
	},
	{
		"\"\"": "\"156\"",
		"\"Rank\"": "156",
		"\"Player\"": "\"Troy Franklin\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "60",
		"\"AVGRank\"": "155",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "155"
	},
	{
		"\"\"": "\"157\"",
		"\"Rank\"": "157",
		"\"Player\"": "\"Sam Darnold\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "34",
		"\"AVGRank\"": "158",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "158"
	},
	{
		"\"\"": "\"158\"",
		"\"Rank\"": "158",
		"\"Player\"": "\"Kimani Vidal\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "47",
		"\"AVGRank\"": "157",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "157"
	},
	{
		"\"\"": "\"159\"",
		"\"Rank\"": "159",
		"\"Player\"": "\"Romeo Doubs\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "61",
		"\"AVGRank\"": "159",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "159"
	},
	{
		"\"\"": "\"160\"",
		"\"Rank\"": "160",
		"\"Player\"": "\"Nick Chubb\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "48",
		"\"AVGRank\"": "160",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "160"
	},
	{
		"\"\"": "\"161\"",
		"\"Rank\"": "161",
		"\"Player\"": "\"Kendre Miller\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "49",
		"\"AVGRank\"": "161",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "161"
	},
	{
		"\"\"": "\"162\"",
		"\"Rank\"": "162",
		"\"Player\"": "\"Zack Moss\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "50",
		"\"AVGRank\"": "162",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "162"
	},
	{
		"\"\"": "\"163\"",
		"\"Rank\"": "163",
		"\"Player\"": "\"Michael Mayer\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "18",
		"\"AVGRank\"": "163",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "163"
	},
	{
		"\"\"": "\"164\"",
		"\"Rank\"": "164",
		"\"Player\"": "\"Dallas Goedert\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "19",
		"\"AVGRank\"": "164",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "164"
	},
	{
		"\"\"": "\"165\"",
		"\"Rank\"": "165",
		"\"Player\"": "\"J.K. Dobbins\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "51",
		"\"AVGRank\"": "165",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "165"
	},
	{
		"\"\"": "\"166\"",
		"\"Rank\"": "166",
		"\"Player\"": "\"Rashod Bateman\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "62",
		"\"AVGRank\"": "167",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "167"
	},
	{
		"\"\"": "\"167\"",
		"\"Rank\"": "167",
		"\"Player\"": "\"Luke McCaffrey\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "63",
		"\"AVGRank\"": "166",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "166"
	},
	{
		"\"\"": "\"168\"",
		"\"Rank\"": "168",
		"\"Player\"": "\"Tyler Lockett\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "64",
		"\"AVGRank\"": "168",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "168"
	},
	{
		"\"\"": "\"169\"",
		"\"Rank\"": "169",
		"\"Player\"": "\"Ty Chandler\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "52",
		"\"AVGRank\"": "169",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "169"
	},
	{
		"\"\"": "\"170\"",
		"\"Rank\"": "170",
		"\"Player\"": "\"Tyler Conklin\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "20",
		"\"AVGRank\"": "170",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "170"
	},
	{
		"\"\"": "\"171\"",
		"\"Rank\"": "171",
		"\"Player\"": "\"Rico Dowdle\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "53",
		"\"AVGRank\"": "171",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "171"
	},
	{
		"\"\"": "\"172\"",
		"\"Rank\"": "172",
		"\"Player\"": "\"Jakobi Meyers\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "65",
		"\"AVGRank\"": "173",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "173"
	},
	{
		"\"\"": "\"173\"",
		"\"Rank\"": "173",
		"\"Player\"": "\"Malik Washington\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "66",
		"\"AVGRank\"": "172",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "172"
	},
	{
		"\"\"": "\"174\"",
		"\"Rank\"": "174",
		"\"Player\"": "\"Jordan Mason\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "54",
		"\"AVGRank\"": "174",
		"\"AVGTier\"": "8",
		"\"Siegele8.25\"": "174"
	},
	{
		"\"\"": "\"175\"",
		"\"Rank\"": "175",
		"\"Player\"": "\"Rashid Shaheed\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "67",
		"\"AVGRank\"": "175",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "175"
	},
	{
		"\"\"": "\"176\"",
		"\"Rank\"": "176",
		"\"Player\"": "\"Jerome Ford\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "55",
		"\"AVGRank\"": "176",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "176"
	},
	{
		"\"\"": "\"177\"",
		"\"Rank\"": "177",
		"\"Player\"": "\"Quentin Johnston\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "68",
		"\"AVGRank\"": "178",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "178"
	},
	{
		"\"\"": "\"178\"",
		"\"Rank\"": "178",
		"\"Player\"": "\"Andrei Iosivas\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "69",
		"\"AVGRank\"": "177",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "177"
	},
	{
		"\"\"": "\"179\"",
		"\"Rank\"": "179",
		"\"Player\"": "\"Khalil Herbert\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "56",
		"\"AVGRank\"": "179",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "179"
	},
	{
		"\"\"": "\"180\"",
		"\"Rank\"": "180",
		"\"Player\"": "\"Demario Douglas\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "70",
		"\"AVGRank\"": "180",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "180"
	},
	{
		"\"\"": "\"181\"",
		"\"Rank\"": "181",
		"\"Player\"": "\"Jalin Hyatt\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "71",
		"\"AVGRank\"": "182",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "182"
	},
	{
		"\"\"": "\"182\"",
		"\"Rank\"": "182",
		"\"Player\"": "\"Javon Baker\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "72",
		"\"AVGRank\"": "181",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "181"
	},
	{
		"\"\"": "\"183\"",
		"\"Rank\"": "183",
		"\"Player\"": "\"Juwan Johnson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "21",
		"\"AVGRank\"": "183",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "183"
	},
	{
		"\"\"": "\"184\"",
		"\"Rank\"": "184",
		"\"Player\"": "\"Russell Wilson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "35",
		"\"AVGRank\"": "185",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "185"
	},
	{
		"\"\"": "\"185\"",
		"\"Rank\"": "185",
		"\"Player\"": "\"Jermaine Burton\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "73",
		"\"AVGRank\"": "184",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "184"
	},
	{
		"\"\"": "\"186\"",
		"\"Rank\"": "186",
		"\"Player\"": "\"Gabe Davis\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "74",
		"\"AVGRank\"": "187",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "187"
	},
	{
		"\"\"": "\"187\"",
		"\"Rank\"": "187",
		"\"Player\"": "\"Malachi Corley\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "75",
		"\"AVGRank\"": "186",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "186"
	},
	{
		"\"\"": "\"188\"",
		"\"Rank\"": "188",
		"\"Player\"": "\"Khalil Shakir\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "76",
		"\"AVGRank\"": "188",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "188"
	},
	{
		"\"\"": "\"189\"",
		"\"Rank\"": "189",
		"\"Player\"": "\"Dalton Schultz\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "22",
		"\"AVGRank\"": "189",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "189"
	},
	{
		"\"\"": "\"190\"",
		"\"Rank\"": "190",
		"\"Player\"": "\"Mike Williams\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "77",
		"\"AVGRank\"": "190",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "190"
	},
	{
		"\"\"": "\"191\"",
		"\"Rank\"": "191",
		"\"Player\"": "\"Tank Bigsby\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "57",
		"\"AVGRank\"": "191",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "191"
	},
	{
		"\"\"": "\"192\"",
		"\"Rank\"": "192",
		"\"Player\"": "\"Noah Fant\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "23",
		"\"AVGRank\"": "192",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "192"
	},
	{
		"\"\"": "\"193\"",
		"\"Rank\"": "193",
		"\"Player\"": "\"Chuba Hubbard\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "58",
		"\"AVGRank\"": "193",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "193"
	},
	{
		"\"\"": "\"194\"",
		"\"Rank\"": "194",
		"\"Player\"": "\"Curtis Samuel\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "78",
		"\"AVGRank\"": "194",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "194"
	},
	{
		"\"\"": "\"195\"",
		"\"Rank\"": "195",
		"\"Player\"": "\"Tucker Kraft\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "24",
		"\"AVGRank\"": "195",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "195"
	},
	{
		"\"\"": "\"196\"",
		"\"Rank\"": "196",
		"\"Player\"": "\"Isaiah Likely\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "25",
		"\"AVGRank\"": "196",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "196"
	},
	{
		"\"\"": "\"197\"",
		"\"Rank\"": "197",
		"\"Player\"": "\"Austin Ekeler\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "59",
		"\"AVGRank\"": "197",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "197"
	},
	{
		"\"\"": "\"198\"",
		"\"Rank\"": "198",
		"\"Player\"": "\"Roschon Johnson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "60",
		"\"AVGRank\"": "198",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "198"
	},
	{
		"\"\"": "\"199\"",
		"\"Rank\"": "199",
		"\"Player\"": "\"Dylan Laube\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "61",
		"\"AVGRank\"": "199",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "199"
	},
	{
		"\"\"": "\"200\"",
		"\"Rank\"": "200",
		"\"Player\"": "\"Joshua Palmer\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "79",
		"\"AVGRank\"": "201",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "201"
	},
	{
		"\"\"": "\"201\"",
		"\"Rank\"": "201",
		"\"Player\"": "\"Roman Wilson\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "80",
		"\"AVGRank\"": "200",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "200"
	},
	{
		"\"\"": "\"202\"",
		"\"Rank\"": "202",
		"\"Player\"": "\"Dameon Pierce\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "62",
		"\"AVGRank\"": "202",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "202"
	},
	{
		"\"\"": "\"203\"",
		"\"Rank\"": "203",
		"\"Player\"": "\"Hunter Henry\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "26",
		"\"AVGRank\"": "203",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "203"
	},
	{
		"\"\"": "\"204\"",
		"\"Rank\"": "204",
		"\"Player\"": "\"Theo Johnson\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "27",
		"\"AVGRank\"": "204",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "204"
	},
	{
		"\"\"": "\"205\"",
		"\"Rank\"": "205",
		"\"Player\"": "\"Jalen Tolbert\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "81",
		"\"AVGRank\"": "205",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "205"
	},
	{
		"\"\"": "\"206\"",
		"\"Rank\"": "206",
		"\"Player\"": "\"Devontez Walker\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "82",
		"\"AVGRank\"": "206",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "206"
	},
	{
		"\"\"": "\"207\"",
		"\"Rank\"": "207",
		"\"Player\"": "\"Isaac Guerendo\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "63",
		"\"AVGRank\"": "207",
		"\"AVGTier\"": "9",
		"\"Siegele8.25\"": "207"
	},
	{
		"\"\"": "\"208\"",
		"\"Rank\"": "208",
		"\"Player\"": "\"Keaton Mitchell\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "64",
		"\"AVGRank\"": "209",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "209"
	},
	{
		"\"\"": "\"209\"",
		"\"Rank\"": "209",
		"\"Player\"": "\"Jordan Whittington\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "83",
		"\"AVGRank\"": "208",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "208"
	},
	{
		"\"\"": "\"210\"",
		"\"Rank\"": "210",
		"\"Player\"": "\"Gus Edwards\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "65",
		"\"AVGRank\"": "210",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "210"
	},
	{
		"\"\"": "\"211\"",
		"\"Rank\"": "211",
		"\"Player\"": "\"Michael Wilson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "84",
		"\"AVGRank\"": "211",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "211"
	},
	{
		"\"\"": "\"212\"",
		"\"Rank\"": "212",
		"\"Player\"": "\"Jahan Dotson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "85",
		"\"AVGRank\"": "212",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "212"
	},
	{
		"\"\"": "\"213\"",
		"\"Rank\"": "213",
		"\"Player\"": "\"Trey Lance\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "36",
		"\"AVGRank\"": "213",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "213"
	},
	{
		"\"\"": "\"214\"",
		"\"Rank\"": "214",
		"\"Player\"": "\"Antonio Gibson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "66",
		"\"AVGRank\"": "215",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "215"
	},
	{
		"\"\"": "\"215\"",
		"\"Rank\"": "215",
		"\"Player\"": "\"Cade Stover\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "28",
		"\"AVGRank\"": "214",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "214"
	},
	{
		"\"\"": "\"216\"",
		"\"Rank\"": "216",
		"\"Player\"": "\"Sam Howell\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "37",
		"\"AVGRank\"": "216",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "216"
	},
	{
		"\"\"": "\"217\"",
		"\"Rank\"": "217",
		"\"Player\"": "\"Mike Gesicki\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "29",
		"\"AVGRank\"": "217",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "217"
	},
	{
		"\"\"": "\"218\"",
		"\"Rank\"": "218",
		"\"Player\"": "\"Jacob Cowing\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "86",
		"\"AVGRank\"": "218",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "218"
	},
	{
		"\"\"": "\"219\"",
		"\"Rank\"": "219",
		"\"Player\"": "\"Jonathan Mingo\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "87",
		"\"AVGRank\"": "219",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "219"
	},
	{
		"\"\"": "\"220\"",
		"\"Rank\"": "220",
		"\"Player\"": "\"Treylon Burks\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "88",
		"\"AVGRank\"": "221",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "221"
	},
	{
		"\"\"": "\"221\"",
		"\"Rank\"": "221",
		"\"Player\"": "\"Blake Watson\"",
		"\"Experience\"": "\"\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "67",
		"\"AVGRank\"": "220",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "220"
	},
	{
		"\"\"": "\"222\"",
		"\"Rank\"": "222",
		"\"Player\"": "\"Greg Dortch\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "89",
		"\"AVGRank\"": "223",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "223"
	},
	{
		"\"\"": "\"223\"",
		"\"Rank\"": "223",
		"\"Player\"": "\"Jacoby Brissett\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "38",
		"\"AVGRank\"": "222",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "222"
	},
	{
		"\"\"": "\"224\"",
		"\"Rank\"": "224",
		"\"Player\"": "\"Darnell Mooney\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "90",
		"\"AVGRank\"": "224",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "224"
	},
	{
		"\"\"": "\"225\"",
		"\"Rank\"": "225",
		"\"Player\"": "\"DJ Chark\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "91",
		"\"AVGRank\"": "226",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "226"
	},
	{
		"\"\"": "\"226\"",
		"\"Rank\"": "226",
		"\"Player\"": "\"Spencer Rattler\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "39",
		"\"AVGRank\"": "225",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "225"
	},
	{
		"\"\"": "\"227\"",
		"\"Rank\"": "227",
		"\"Player\"": "\"Rondale Moore\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "92",
		"\"AVGRank\"": "228",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "228"
	},
	{
		"\"\"": "\"228\"",
		"\"Rank\"": "228",
		"\"Player\"": "\"Johnny Wilson\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "93",
		"\"AVGRank\"": "227",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "227"
	},
	{
		"\"\"": "\"229\"",
		"\"Rank\"": "229",
		"\"Player\"": "\"Greg Dulcich\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "30",
		"\"AVGRank\"": "229",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "229"
	},
	{
		"\"\"": "\"230\"",
		"\"Rank\"": "230",
		"\"Player\"": "\"Aidan O'Connell\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "40",
		"\"AVGRank\"": "230",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "230"
	},
	{
		"\"\"": "\"231\"",
		"\"Rank\"": "231",
		"\"Player\"": "\"Chigoziem Okonkwo\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "31",
		"\"AVGRank\"": "232",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "232"
	},
	{
		"\"\"": "\"232\"",
		"\"Rank\"": "232",
		"\"Player\"": "\"Demarcus Robinson\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "94",
		"\"AVGRank\"": "231",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "231"
	},
	{
		"\"\"": "\"233\"",
		"\"Rank\"": "233",
		"\"Player\"": "\"Trey Palmer\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "95",
		"\"AVGRank\"": "233",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "233"
	},
	{
		"\"\"": "\"234\"",
		"\"Rank\"": "234",
		"\"Player\"": "\"Isaiah Davis\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "68",
		"\"AVGRank\"": "234",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "234"
	},
	{
		"\"\"": "\"235\"",
		"\"Rank\"": "235",
		"\"Player\"": "\"Bo Melton\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "96",
		"\"AVGRank\"": "235",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "235"
	},
	{
		"\"\"": "\"236\"",
		"\"Rank\"": "236",
		"\"Player\"": "\"Jared Wiley\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "32",
		"\"AVGRank\"": "236",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "236"
	},
	{
		"\"\"": "\"237\"",
		"\"Rank\"": "237",
		"\"Player\"": "\"Cade Otton\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "33",
		"\"AVGRank\"": "238",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "238"
	},
	{
		"\"\"": "\"238\"",
		"\"Rank\"": "238",
		"\"Player\"": "\"Rasheen Ali\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "69",
		"\"AVGRank\"": "237",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "237"
	},
	{
		"\"\"": "\"239\"",
		"\"Rank\"": "239",
		"\"Player\"": "\"A.T. Perry\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "97",
		"\"AVGRank\"": "239",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "239"
	},
	{
		"\"\"": "\"240\"",
		"\"Rank\"": "240",
		"\"Player\"": "\"Dalvin Cook\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"FA\"",
		"\"PosRank\"": "70",
		"\"AVGRank\"": "240",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "240"
	},
	{
		"\"\"": "\"241\"",
		"\"Rank\"": "241",
		"\"Player\"": "\"Mac Jones\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "41",
		"\"AVGRank\"": "241",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "241"
	},
	{
		"\"\"": "\"242\"",
		"\"Rank\"": "242",
		"\"Player\"": "\"Brandin Cooks\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "98",
		"\"AVGRank\"": "243",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "243"
	},
	{
		"\"\"": "\"243\"",
		"\"Rank\"": "243",
		"\"Player\"": "\"Jaheim Bell\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "34",
		"\"AVGRank\"": "242",
		"\"AVGTier\"": "10",
		"\"Siegele8.25\"": "242"
	},
	{
		"\"\"": "\"244\"",
		"\"Rank\"": "244",
		"\"Player\"": "\"Elijah Moore\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "99",
		"\"AVGRank\"": "244",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "244"
	},
	{
		"\"\"": "\"245\"",
		"\"Rank\"": "245",
		"\"Player\"": "\"Adam Thielen\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "100",
		"\"AVGRank\"": "245",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "245"
	},
	{
		"\"\"": "\"246\"",
		"\"Rank\"": "246",
		"\"Player\"": "\"Jonnu Smith\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "35",
		"\"AVGRank\"": "246",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "246"
	},
	{
		"\"\"": "\"247\"",
		"\"Rank\"": "247",
		"\"Player\"": "\"Pierre Strong\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "71",
		"\"AVGRank\"": "248",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "248"
	},
	{
		"\"\"": "\"248\"",
		"\"Rank\"": "248",
		"\"Player\"": "\"Bub Means\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "101",
		"\"AVGRank\"": "247",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "247"
	},
	{
		"\"\"": "\"249\"",
		"\"Rank\"": "249",
		"\"Player\"": "\"Jordan Travis\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "42",
		"\"AVGRank\"": "249",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "249"
	},
	{
		"\"\"": "\"250\"",
		"\"Rank\"": "250",
		"\"Player\"": "\"Ryan Flournoy\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "102",
		"\"AVGRank\"": "250",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "250"
	},
	{
		"\"\"": "\"251\"",
		"\"Rank\"": "251",
		"\"Player\"": "\"Miles Sanders\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "72",
		"\"AVGRank\"": "252",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "252"
	},
	{
		"\"\"": "\"252\"",
		"\"Rank\"": "252",
		"\"Player\"": "\"Erick All\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "36",
		"\"AVGRank\"": "251",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "251"
	},
	{
		"\"\"": "\"253\"",
		"\"Rank\"": "253",
		"\"Player\"": "\"Zay Jones\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"FA\"",
		"\"PosRank\"": "103",
		"\"AVGRank\"": "253",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "253"
	},
	{
		"\"\"": "\"254\"",
		"\"Rank\"": "254",
		"\"Player\"": "\"Israel Abanikanda\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "73",
		"\"AVGRank\"": "255",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "255"
	},
	{
		"\"\"": "\"255\"",
		"\"Rank\"": "255",
		"\"Player\"": "\"Brenden Rice\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "104",
		"\"AVGRank\"": "254",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "254"
	},
	{
		"\"\"": "\"256\"",
		"\"Rank\"": "256",
		"\"Player\"": "\"Hendon Hooker\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "43",
		"\"AVGRank\"": "256",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "256"
	},
	{
		"\"\"": "\"257\"",
		"\"Rank\"": "257",
		"\"Player\"": "\"Jamari Thrash\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "105",
		"\"AVGRank\"": "257",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "257"
	},
	{
		"\"\"": "\"258\"",
		"\"Rank\"": "258",
		"\"Player\"": "\"Jawhar Jordan\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "74",
		"\"AVGRank\"": "258",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "258"
	},
	{
		"\"\"": "\"259\"",
		"\"Rank\"": "259",
		"\"Player\"": "\"Kenny Pickett\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "44",
		"\"AVGRank\"": "260",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "260"
	},
	{
		"\"\"": "\"260\"",
		"\"Rank\"": "260",
		"\"Player\"": "\"Anthony Gould\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "106",
		"\"AVGRank\"": "259",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "259"
	},
	{
		"\"\"": "\"261\"",
		"\"Rank\"": "261",
		"\"Player\"": "\"Alexander Mattison\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "75",
		"\"AVGRank\"": "261",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "261"
	},
	{
		"\"\"": "\"262\"",
		"\"Rank\"": "262",
		"\"Player\"": "\"Jase McClellan\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "76",
		"\"AVGRank\"": "262",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "262"
	},
	{
		"\"\"": "\"263\"",
		"\"Rank\"": "263",
		"\"Player\"": "\"Cody Schrader\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "77",
		"\"AVGRank\"": "263",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "263"
	},
	{
		"\"\"": "\"264\"",
		"\"Rank\"": "264",
		"\"Player\"": "\"Tyler Boyd\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "107",
		"\"AVGRank\"": "265",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "265"
	},
	{
		"\"\"": "\"265\"",
		"\"Rank\"": "265",
		"\"Player\"": "\"Frank Gore\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "78",
		"\"AVGRank\"": "264",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "264"
	},
	{
		"\"\"": "\"266\"",
		"\"Rank\"": "266",
		"\"Player\"": "\"Sam Hartman\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "45",
		"\"AVGRank\"": "266",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "266"
	},
	{
		"\"\"": "\"267\"",
		"\"Rank\"": "267",
		"\"Player\"": "\"Ryan Tannehill\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"FA\"",
		"\"PosRank\"": "46",
		"\"AVGRank\"": "268",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "268"
	},
	{
		"\"\"": "\"268\"",
		"\"Rank\"": "268",
		"\"Player\"": "\"George Holani\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "79",
		"\"AVGRank\"": "267",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "267"
	},
	{
		"\"\"": "\"269\"",
		"\"Rank\"": "269",
		"\"Player\"": "\"Sean Tucker\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "80",
		"\"AVGRank\"": "269",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "269"
	},
	{
		"\"\"": "\"270\"",
		"\"Rank\"": "270",
		"\"Player\"": "\"Chris Rodriguez",
		"\"Experience\"": " Jr.\"",
		"\"POS\"": "\"Veteran\"",
		"\"Team\"": "\"RB\"",
		"\"PosRank\"": "\"#N/A\"",
		"\"AVGRank\"": "81",
		"\"AVGTier\"": "270",
		"\"Siegele8.25\"": "11"
	},
	{
		"\"\"": "\"271\"",
		"\"Rank\"": "271",
		"\"Player\"": "\"Justyn Ross\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "108",
		"\"AVGRank\"": "271",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "271"
	},
	{
		"\"\"": "\"272\"",
		"\"Rank\"": "272",
		"\"Player\"": "\"Elijah Mitchell\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "82",
		"\"AVGRank\"": "272",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "272"
	},
	{
		"\"\"": "\"273\"",
		"\"Rank\"": "273",
		"\"Player\"": "\"Zach Evans\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "83",
		"\"AVGRank\"": "273",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "273"
	},
	{
		"\"\"": "\"274\"",
		"\"Rank\"": "274",
		"\"Player\"": "\"Jaden Shirden\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "84",
		"\"AVGRank\"": "274",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "274"
	},
	{
		"\"\"": "\"275\"",
		"\"Rank\"": "275",
		"\"Player\"": "\"K.J. Osborn\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "109",
		"\"AVGRank\"": "276",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "276"
	},
	{
		"\"\"": "\"276\"",
		"\"Rank\"": "276",
		"\"Player\"": "\"Michael Pratt\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "47",
		"\"AVGRank\"": "275",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "275"
	},
	{
		"\"\"": "\"277\"",
		"\"Rank\"": "277",
		"\"Player\"": "\"Jimmy Garoppolo\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "48",
		"\"AVGRank\"": "278",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "278"
	},
	{
		"\"\"": "\"278\"",
		"\"Rank\"": "278",
		"\"Player\"": "\"Luke Schoonmaker\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "37",
		"\"AVGRank\"": "277",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "277"
	},
	{
		"\"\"": "\"279\"",
		"\"Rank\"": "279",
		"\"Player\"": "\"Tyler Higbee\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "38",
		"\"AVGRank\"": "279",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "279"
	},
	{
		"\"\"": "\"280\"",
		"\"Rank\"": "280",
		"\"Player\"": "\"Michael Thomas\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "110",
		"\"AVGRank\"": "280",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "280"
	},
	{
		"\"\"": "\"281\"",
		"\"Rank\"": "281",
		"\"Player\"": "\"Justice Hill\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "85",
		"\"AVGRank\"": "281",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "281"
	},
	{
		"\"\"": "\"282\"",
		"\"Rank\"": "282",
		"\"Player\"": "\"Parker Washington\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "111",
		"\"AVGRank\"": "282",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "282"
	},
	{
		"\"\"": "\"283\"",
		"\"Rank\"": "283",
		"\"Player\"": "\"Darnell Washington\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "39",
		"\"AVGRank\"": "283",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "283"
	},
	{
		"\"\"": "\"284\"",
		"\"Rank\"": "284",
		"\"Player\"": "\"Taysom Hill\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"#N/A\"",
		"\"PosRank\"": "40",
		"\"AVGRank\"": "284",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "284"
	},
	{
		"\"\"": "\"285\"",
		"\"Rank\"": "285",
		"\"Player\"": "\"Dillon Johnson\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "86",
		"\"AVGRank\"": "285",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "285"
	},
	{
		"\"\"": "\"286\"",
		"\"Rank\"": "286",
		"\"Player\"": "\"AJ Dillon\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "87",
		"\"AVGRank\"": "287",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "287"
	},
	{
		"\"\"": "\"287\"",
		"\"Rank\"": "287",
		"\"Player\"": "\"Jalen Coker\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "112",
		"\"AVGRank\"": "286",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "286"
	},
	{
		"\"\"": "\"288\"",
		"\"Rank\"": "288",
		"\"Player\"": "\"Jack Westover\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "41",
		"\"AVGRank\"": "288",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "288"
	},
	{
		"\"\"": "\"289\"",
		"\"Rank\"": "289",
		"\"Player\"": "\"Ainias Smith\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "113",
		"\"AVGRank\"": "289",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "289"
	},
	{
		"\"\"": "\"290\"",
		"\"Rank\"": "290",
		"\"Player\"": "\"Joe Milton\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "49",
		"\"AVGRank\"": "290",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "290"
	},
	{
		"\"\"": "\"291\"",
		"\"Rank\"": "291",
		"\"Player\"": "\"Tanner McLachlan\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "42",
		"\"AVGRank\"": "291",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "291"
	},
	{
		"\"\"": "\"292\"",
		"\"Rank\"": "292",
		"\"Player\"": "\"Emani Bailey\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "88",
		"\"AVGRank\"": "292",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "292"
	},
	{
		"\"\"": "\"293\"",
		"\"Rank\"": "293",
		"\"Player\"": "\"Kendall Milton\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "89",
		"\"AVGRank\"": "293",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "293"
	},
	{
		"\"\"": "\"294\"",
		"\"Rank\"": "294",
		"\"Player\"": "\"Isaiah Williams\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "114",
		"\"AVGRank\"": "294",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "294"
	},
	{
		"\"\"": "\"295\"",
		"\"Rank\"": "295",
		"\"Player\"": "\"Devin Leary\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "50",
		"\"AVGRank\"": "295",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "295"
	},
	{
		"\"\"": "\"296\"",
		"\"Rank\"": "296",
		"\"Player\"": "\"Austin Reed\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "51",
		"\"AVGRank\"": "296",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "296"
	},
	{
		"\"\"": "\"297\"",
		"\"Rank\"": "297",
		"\"Player\"": "\"Keilan Robinson\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "90",
		"\"AVGRank\"": "297",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "297"
	},
	{
		"\"\"": "\"298\"",
		"\"Rank\"": "298",
		"\"Player\"": "\"Kareem Hunt\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"FA\"",
		"\"PosRank\"": "91",
		"\"AVGRank\"": "299",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "299"
	},
	{
		"\"\"": "\"299\"",
		"\"Rank\"": "299",
		"\"Player\"": "\"Dallin Holker\"",
		"\"Experience\"": "\"Rookie\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "43",
		"\"AVGRank\"": "298",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "298"
	},
	{
		"\"\"": "\"300\"",
		"\"Rank\"": "300",
		"\"Player\"": "\"Darren Waller\"",
		"\"Experience\"": "\"Veteran\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "44",
		"\"AVGRank\"": "301",
		"\"AVGTier\"": "11",
		"\"Siegele8.25\"": "301"
	},
	
]

module.exports = rvDynastyRankingsTEP;
