const rvDynastyRankingsTEP = [
	{
		"\"\"": "\"1\"",
		"\"Rank\"": "1",
		"\"Player\"": "\"Jalen Hurts\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "1",
		"\"AVGRank\"": "1",
		"\"AVGTier\"": "1",
		"\"Siegele11.11\"": "1"
	},
	{
		"\"\"": "\"2\"",
		"\"Rank\"": "2",
		"\"Player\"": "\"Justin Jefferson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "1",
		"\"AVGRank\"": "2",
		"\"AVGTier\"": "1",
		"\"Siegele11.11\"": "2"
	},
	{
		"\"\"": "\"3\"",
		"\"Rank\"": "3",
		"\"Player\"": "\"Ja'Marr Chase\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "2",
		"\"AVGRank\"": "3",
		"\"AVGTier\"": "1",
		"\"Siegele11.11\"": "3"
	},
	{
		"\"\"": "\"4\"",
		"\"Rank\"": "4",
		"\"Player\"": "\"Josh Allen\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "2",
		"\"AVGRank\"": "4",
		"\"AVGTier\"": "1",
		"\"Siegele11.11\"": "4"
	},
	{
		"\"\"": "\"5\"",
		"\"Rank\"": "5",
		"\"Player\"": "\"Patrick Mahomes\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "3",
		"\"AVGRank\"": "5",
		"\"AVGTier\"": "1",
		"\"Siegele11.11\"": "5"
	},
	{
		"\"\"": "\"6\"",
		"\"Rank\"": "6",
		"\"Player\"": "\"Bijan Robinson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "1",
		"\"AVGRank\"": "6",
		"\"AVGTier\"": "1",
		"\"Siegele11.11\"": "6"
	},
	{
		"\"\"": "\"7\"",
		"\"Rank\"": "7",
		"\"Player\"": "\"C.J. Stroud\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "4",
		"\"AVGRank\"": "7",
		"\"AVGTier\"": "1",
		"\"Siegele11.11\"": "7"
	},
	{
		"\"\"": "\"8\"",
		"\"Rank\"": "8",
		"\"Player\"": "\"CeeDee Lamb\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "3",
		"\"AVGRank\"": "8",
		"\"AVGTier\"": "1",
		"\"Siegele11.11\"": "8"
	},
	{
		"\"\"": "\"9\"",
		"\"Rank\"": "9",
		"\"Player\"": "\"Christian McCaffrey\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "2",
		"\"AVGRank\"": "9",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "9"
	},
	{
		"\"\"": "\"10\"",
		"\"Rank\"": "10",
		"\"Player\"": "\"Justin Herbert\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "5",
		"\"AVGRank\"": "10",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "10"
	},
	{
		"\"\"": "\"11\"",
		"\"Rank\"": "11",
		"\"Player\"": "\"Joe Burrow\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "6",
		"\"AVGRank\"": "11",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "11"
	},
	{
		"\"\"": "\"12\"",
		"\"Rank\"": "12",
		"\"Player\"": "\"Garrett Wilson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "4",
		"\"AVGRank\"": "12",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "12"
	},
	{
		"\"\"": "\"13\"",
		"\"Rank\"": "13",
		"\"Player\"": "\"Breece Hall\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "3",
		"\"AVGRank\"": "13",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "13"
	},
	{
		"\"\"": "\"14\"",
		"\"Rank\"": "14",
		"\"Player\"": "\"Tua Tagovailoa\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "7",
		"\"AVGRank\"": "14",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "14"
	},
	{
		"\"\"": "\"15\"",
		"\"Rank\"": "15",
		"\"Player\"": "\"Justin Fields\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "8",
		"\"AVGRank\"": "15",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "15"
	},
	{
		"\"\"": "\"16\"",
		"\"Rank\"": "16",
		"\"Player\"": "\"Jonathan Taylor\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "4",
		"\"AVGRank\"": "16",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "16"
	},
	{
		"\"\"": "\"17\"",
		"\"Rank\"": "17",
		"\"Player\"": "\"A.J. Brown\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "5",
		"\"AVGRank\"": "17",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "17"
	},
	{
		"\"\"": "\"18\"",
		"\"Rank\"": "18",
		"\"Player\"": "\"Amon-Ra St. Brown\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "6",
		"\"AVGRank\"": "18",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "18"
	},
	{
		"\"\"": "\"19\"",
		"\"Rank\"": "19",
		"\"Player\"": "\"Tyreek Hill\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "7",
		"\"AVGRank\"": "19",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "19"
	},
	{
		"\"\"": "\"20\"",
		"\"Rank\"": "20",
		"\"Player\"": "\"Sam LaPorta\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "1",
		"\"AVGRank\"": "20",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "20"
	},
	{
		"\"\"": "\"21\"",
		"\"Rank\"": "21",
		"\"Player\"": "\"Devon Achane\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "5",
		"\"AVGRank\"": "21",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "21"
	},
	{
		"\"\"": "\"22\"",
		"\"Rank\"": "22",
		"\"Player\"": "\"Anthony Richardson\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "9",
		"\"AVGRank\"": "22",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "22"
	},
	{
		"\"\"": "\"23\"",
		"\"Rank\"": "23",
		"\"Player\"": "\"Travis Etienne\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "6",
		"\"AVGRank\"": "23",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "23"
	},
	{
		"\"\"": "\"24\"",
		"\"Rank\"": "24",
		"\"Player\"": "\"Lamar Jackson\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "10",
		"\"AVGRank\"": "24",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "24"
	},
	{
		"\"\"": "\"25\"",
		"\"Rank\"": "25",
		"\"Player\"": "\"Trevor Lawrence\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "11",
		"\"AVGRank\"": "25",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "25"
	},
	{
		"\"\"": "\"26\"",
		"\"Rank\"": "26",
		"\"Player\"": "\"Chris Olave\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "8",
		"\"AVGRank\"": "26",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "26"
	},
	{
		"\"\"": "\"27\"",
		"\"Rank\"": "27",
		"\"Player\"": "\"Jahmyr Gibbs\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "7",
		"\"AVGRank\"": "27",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "27"
	},
	{
		"\"\"": "\"28\"",
		"\"Rank\"": "28",
		"\"Player\"": "\"Kyler Murray\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "12",
		"\"AVGRank\"": "28",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "28"
	},
	{
		"\"\"": "\"29\"",
		"\"Rank\"": "29",
		"\"Player\"": "\"T.J. Hockenson\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "2",
		"\"AVGRank\"": "29",
		"\"AVGTier\"": "3",
		"\"Siegele11.11\"": "29"
	},
	{
		"\"\"": "\"30\"",
		"\"Rank\"": "30",
		"\"Player\"": "\"Jaxon Smith-Njigba\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "9",
		"\"AVGRank\"": "30",
		"\"AVGTier\"": "3",
		"\"Siegele11.11\"": "30"
	},
	{
		"\"\"": "\"31\"",
		"\"Rank\"": "31",
		"\"Player\"": "\"DeVonta Smith\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "10",
		"\"AVGRank\"": "31",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "31"
	},
	{
		"\"\"": "\"32\"",
		"\"Rank\"": "32",
		"\"Player\"": "\"Kenneth Walker\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "8",
		"\"AVGRank\"": "32",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "32"
	},
	{
		"\"\"": "\"33\"",
		"\"Rank\"": "33",
		"\"Player\"": "\"Bryce Young\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "13",
		"\"AVGRank\"": "33",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "33"
	},
	{
		"\"\"": "\"34\"",
		"\"Rank\"": "34",
		"\"Player\"": "\"Jordan Addison\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "11",
		"\"AVGRank\"": "34",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "34"
	},
	{
		"\"\"": "\"35\"",
		"\"Rank\"": "35",
		"\"Player\"": "\"Jaylen Waddle\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "12",
		"\"AVGRank\"": "35",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "35"
	},
	{
		"\"\"": "\"36\"",
		"\"Rank\"": "36",
		"\"Player\"": "\"Sam Howell\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "14",
		"\"AVGRank\"": "36",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "36"
	},
	{
		"\"\"": "\"37\"",
		"\"Rank\"": "37",
		"\"Player\"": "\"Brandon Aiyuk\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "13",
		"\"AVGRank\"": "37",
		"\"AVGTier\"": "2",
		"\"Siegele11.11\"": "37"
	},
	{
		"\"\"": "\"38\"",
		"\"Rank\"": "38",
		"\"Player\"": "\"DJ Moore\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "14",
		"\"AVGRank\"": "39",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "39"
	},
	{
		"\"\"": "\"39\"",
		"\"Rank\"": "39",
		"\"Player\"": "\"Puka Nacua\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "15",
		"\"AVGRank\"": "38",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "38"
	},
	{
		"\"\"": "\"40\"",
		"\"Rank\"": "40",
		"\"Player\"": "\"Stefon Diggs\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "16",
		"\"AVGRank\"": "40",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "40"
	},
	{
		"\"\"": "\"41\"",
		"\"Rank\"": "41",
		"\"Player\"": "\"Mark Andrews\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "3",
		"\"AVGRank\"": "41",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "41"
	},
	{
		"\"\"": "\"42\"",
		"\"Rank\"": "42",
		"\"Player\"": "\"Saquon Barkley\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "9",
		"\"AVGRank\"": "42",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "42"
	},
	{
		"\"\"": "\"43\"",
		"\"Rank\"": "43",
		"\"Player\"": "\"Dalton Kincaid\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "4",
		"\"AVGRank\"": "43",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "43"
	},
	{
		"\"\"": "\"44\"",
		"\"Rank\"": "44",
		"\"Player\"": "\"Tee Higgins\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "17",
		"\"AVGRank\"": "44",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "44"
	},
	{
		"\"\"": "\"45\"",
		"\"Rank\"": "45",
		"\"Player\"": "\"Brock Purdy\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "15",
		"\"AVGRank\"": "45",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "45"
	},
	{
		"\"\"": "\"46\"",
		"\"Rank\"": "46",
		"\"Player\"": "\"Cooper Kupp\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "18",
		"\"AVGRank\"": "46",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "46"
	},
	{
		"\"\"": "\"47\"",
		"\"Rank\"": "47",
		"\"Player\"": "\"Drake London\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "19",
		"\"AVGRank\"": "47",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "47"
	},
	{
		"\"\"": "\"48\"",
		"\"Rank\"": "48",
		"\"Player\"": "\"Kyle Pitts\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "5",
		"\"AVGRank\"": "48",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "48"
	},
	{
		"\"\"": "\"49\"",
		"\"Rank\"": "49",
		"\"Player\"": "\"Deebo Samuel\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "20",
		"\"AVGRank\"": "49",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "49"
	},
	{
		"\"\"": "\"50\"",
		"\"Rank\"": "50",
		"\"Player\"": "\"Austin Ekeler\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "10",
		"\"AVGRank\"": "50",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "50"
	},
	{
		"\"\"": "\"51\"",
		"\"Rank\"": "51",
		"\"Player\"": "\"D'Andre Swift\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "11",
		"\"AVGRank\"": "51",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "51"
	},
	{
		"\"\"": "\"52\"",
		"\"Rank\"": "52",
		"\"Player\"": "\"Tony Pollard\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "12",
		"\"AVGRank\"": "52",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "52"
	},
	{
		"\"\"": "\"53\"",
		"\"Rank\"": "53",
		"\"Player\"": "\"Josh Jacobs\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "13",
		"\"AVGRank\"": "53",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "53"
	},
	{
		"\"\"": "\"54\"",
		"\"Rank\"": "54",
		"\"Player\"": "\"Zay Flowers\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "21",
		"\"AVGRank\"": "54",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "54"
	},
	{
		"\"\"": "\"55\"",
		"\"Rank\"": "55",
		"\"Player\"": "\"Travis Kelce\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "6",
		"\"AVGRank\"": "55",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "55"
	},
	{
		"\"\"": "\"56\"",
		"\"Rank\"": "56",
		"\"Player\"": "\"Davante Adams\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "22",
		"\"AVGRank\"": "56",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "56"
	},
	{
		"\"\"": "\"57\"",
		"\"Rank\"": "57",
		"\"Player\"": "\"Keenan Allen\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "23",
		"\"AVGRank\"": "57",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "57"
	},
	{
		"\"\"": "\"58\"",
		"\"Rank\"": "58",
		"\"Player\"": "\"Mike Evans\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "24",
		"\"AVGRank\"": "58",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "58"
	},
	{
		"\"\"": "\"59\"",
		"\"Rank\"": "59",
		"\"Player\"": "\"Jared Goff\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "16",
		"\"AVGRank\"": "59",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "59"
	},
	{
		"\"\"": "\"60\"",
		"\"Rank\"": "60",
		"\"Player\"": "\"George Kittle\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "7",
		"\"AVGRank\"": "60",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "60"
	},
	{
		"\"\"": "\"61\"",
		"\"Rank\"": "61",
		"\"Player\"": "\"Deshaun Watson\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "17",
		"\"AVGRank\"": "61",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "61"
	},
	{
		"\"\"": "\"62\"",
		"\"Rank\"": "62",
		"\"Player\"": "\"DK Metcalf\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "25",
		"\"AVGRank\"": "62",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "62"
	},
	{
		"\"\"": "\"63\"",
		"\"Rank\"": "63",
		"\"Player\"": "\"Will Levis\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "18",
		"\"AVGRank\"": "63",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "63"
	},
	{
		"\"\"": "\"64\"",
		"\"Rank\"": "64",
		"\"Player\"": "\"Christian Watson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "26",
		"\"AVGRank\"": "64",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "64"
	},
	{
		"\"\"": "\"65\"",
		"\"Rank\"": "65",
		"\"Player\"": "\"Jahan Dotson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "27",
		"\"AVGRank\"": "65",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "65"
	},
	{
		"\"\"": "\"66\"",
		"\"Rank\"": "66",
		"\"Player\"": "\"Trey McBride\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "8",
		"\"AVGRank\"": "66",
		"\"AVGTier\"": "4",
		"\"Siegele11.11\"": "66"
	},
	{
		"\"\"": "\"67\"",
		"\"Rank\"": "67",
		"\"Player\"": "\"Diontae Johnson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "28",
		"\"AVGRank\"": "67",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "67"
	},
	{
		"\"\"": "\"68\"",
		"\"Rank\"": "68",
		"\"Player\"": "\"Terry McLaurin\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "29",
		"\"AVGRank\"": "68",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "68"
	},
	{
		"\"\"": "\"69\"",
		"\"Rank\"": "69",
		"\"Player\"": "\"Rashee Rice\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "30",
		"\"AVGRank\"": "69",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "69"
	},
	{
		"\"\"": "\"70\"",
		"\"Rank\"": "70",
		"\"Player\"": "\"Dak Prescott\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "19",
		"\"AVGRank\"": "70",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "70"
	},
	{
		"\"\"": "\"71\"",
		"\"Rank\"": "71",
		"\"Player\"": "\"Marquise Brown\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "31",
		"\"AVGRank\"": "71",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "71"
	},
	{
		"\"\"": "\"72\"",
		"\"Rank\"": "72",
		"\"Player\"": "\"Michael Pittman\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "32",
		"\"AVGRank\"": "72",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "72"
	},
	{
		"\"\"": "\"73\"",
		"\"Rank\"": "73",
		"\"Player\"": "\"Quentin Johnston\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "33",
		"\"AVGRank\"": "73",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "73"
	},
	{
		"\"\"": "\"74\"",
		"\"Rank\"": "74",
		"\"Player\"": "\"Nico Collins\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "34",
		"\"AVGRank\"": "74",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "74"
	},
	{
		"\"\"": "\"75\"",
		"\"Rank\"": "75",
		"\"Player\"": "\"George Pickens\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "35",
		"\"AVGRank\"": "75",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "75"
	},
	{
		"\"\"": "\"76\"",
		"\"Rank\"": "76",
		"\"Player\"": "\"Marvin Mims\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "36",
		"\"AVGRank\"": "76",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "76"
	},
	{
		"\"\"": "\"77\"",
		"\"Rank\"": "77",
		"\"Player\"": "\"Josh Downs\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "37",
		"\"AVGRank\"": "77",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "77"
	},
	{
		"\"\"": "\"78\"",
		"\"Rank\"": "78",
		"\"Player\"": "\"David Montgomery\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "14",
		"\"AVGRank\"": "78",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "78"
	},
	{
		"\"\"": "\"79\"",
		"\"Rank\"": "79",
		"\"Player\"": "\"Rhamondre Stevenson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "15",
		"\"AVGRank\"": "79",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "79"
	},
	{
		"\"\"": "\"80\"",
		"\"Rank\"": "80",
		"\"Player\"": "\"Jordan Love\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "20",
		"\"AVGRank\"": "80",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "80"
	},
	{
		"\"\"": "\"81\"",
		"\"Rank\"": "81",
		"\"Player\"": "\"Javonte Williams\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "16",
		"\"AVGRank\"": "81",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "81"
	},
	{
		"\"\"": "\"82\"",
		"\"Rank\"": "82",
		"\"Player\"": "\"Cole Kmet\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "9",
		"\"AVGRank\"": "82",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "82"
	},
	{
		"\"\"": "\"83\"",
		"\"Rank\"": "83",
		"\"Player\"": "\"Calvin Ridley\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "38",
		"\"AVGRank\"": "83",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "83"
	},
	{
		"\"\"": "\"84\"",
		"\"Rank\"": "84",
		"\"Player\"": "\"Jakobi Meyers\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "39",
		"\"AVGRank\"": "84",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "84"
	},
	{
		"\"\"": "\"85\"",
		"\"Rank\"": "85",
		"\"Player\"": "\"Matthew Stafford\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "21",
		"\"AVGRank\"": "85",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "85"
	},
	{
		"\"\"": "\"86\"",
		"\"Rank\"": "86",
		"\"Player\"": "\"Evan Engram\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "10",
		"\"AVGRank\"": "86",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "86"
	},
	{
		"\"\"": "\"87\"",
		"\"Rank\"": "87",
		"\"Player\"": "\"Geno Smith\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "22",
		"\"AVGRank\"": "87",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "87"
	},
	{
		"\"\"": "\"88\"",
		"\"Rank\"": "88",
		"\"Player\"": "\"Christian Kirk\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "40",
		"\"AVGRank\"": "88",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "88"
	},
	{
		"\"\"": "\"89\"",
		"\"Rank\"": "89",
		"\"Player\"": "\"Kirk Cousins\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "23",
		"\"AVGRank\"": "89",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "89"
	},
	{
		"\"\"": "\"90\"",
		"\"Rank\"": "90",
		"\"Player\"": "\"Tyjae Spears\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "17",
		"\"AVGRank\"": "90",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "90"
	},
	{
		"\"\"": "\"91\"",
		"\"Rank\"": "91",
		"\"Player\"": "\"Alvin Kamara\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "18",
		"\"AVGRank\"": "91",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "91"
	},
	{
		"\"\"": "\"92\"",
		"\"Rank\"": "92",
		"\"Player\"": "\"Jerry Jeudy\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "41",
		"\"AVGRank\"": "92",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "92"
	},
	{
		"\"\"": "\"93\"",
		"\"Rank\"": "93",
		"\"Player\"": "\"Jameson Williams\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "42",
		"\"AVGRank\"": "93",
		"\"AVGTier\"": "5",
		"\"Siegele11.11\"": "93"
	},
	{
		"\"\"": "\"94\"",
		"\"Rank\"": "94",
		"\"Player\"": "\"Raheem Mostert\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "19",
		"\"AVGRank\"": "94",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "94"
	},
	{
		"\"\"": "\"95\"",
		"\"Rank\"": "95",
		"\"Player\"": "\"Nathaniel Dell\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"\"",
		"\"PosRank\"": "43",
		"\"AVGRank\"": "95",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "95"
	},
	{
		"\"\"": "\"96\"",
		"\"Rank\"": "96",
		"\"Player\"": "\"Derek Carr\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "24",
		"\"AVGRank\"": "96",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "96"
	},
	{
		"\"\"": "\"97\"",
		"\"Rank\"": "97",
		"\"Player\"": "\"Rachaad White\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "20",
		"\"AVGRank\"": "97",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "97"
	},
	{
		"\"\"": "\"98\"",
		"\"Rank\"": "98",
		"\"Player\"": "\"Aaron Jones\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "21",
		"\"AVGRank\"": "98",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "98"
	},
	{
		"\"\"": "\"99\"",
		"\"Rank\"": "99",
		"\"Player\"": "\"Wan'Dale Robinson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "44",
		"\"AVGRank\"": "99",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "99"
	},
	{
		"\"\"": "\"100\"",
		"\"Rank\"": "100",
		"\"Player\"": "\"Derrick Henry\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "22",
		"\"AVGRank\"": "100",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "100"
	},
	{
		"\"\"": "\"101\"",
		"\"Rank\"": "101",
		"\"Player\"": "\"Pat Freiermuth\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "11",
		"\"AVGRank\"": "101",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "101"
	},
	{
		"\"\"": "\"102\"",
		"\"Rank\"": "102",
		"\"Player\"": "\"Amari Cooper\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "45",
		"\"AVGRank\"": "102",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "102"
	},
	{
		"\"\"": "\"103\"",
		"\"Rank\"": "103",
		"\"Player\"": "\"Jalin Hyatt\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "46",
		"\"AVGRank\"": "103",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "103"
	},
	{
		"\"\"": "\"104\"",
		"\"Rank\"": "104",
		"\"Player\"": "\"James Cook\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "23",
		"\"AVGRank\"": "104",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "104"
	},
	{
		"\"\"": "\"105\"",
		"\"Rank\"": "105",
		"\"Player\"": "\"Luke Musgrave\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "12",
		"\"AVGRank\"": "105",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "105"
	},
	{
		"\"\"": "\"106\"",
		"\"Rank\"": "106",
		"\"Player\"": "\"DeAndre Hopkins\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "47",
		"\"AVGRank\"": "106",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "106"
	},
	{
		"\"\"": "\"107\"",
		"\"Rank\"": "107",
		"\"Player\"": "\"Chris Godwin\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "48",
		"\"AVGRank\"": "107",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "107"
	},
	{
		"\"\"": "\"108\"",
		"\"Rank\"": "108",
		"\"Player\"": "\"Zach Charbonnet\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "24",
		"\"AVGRank\"": "108",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "108"
	},
	{
		"\"\"": "\"109\"",
		"\"Rank\"": "109",
		"\"Player\"": "\"Roschon Johnson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "25",
		"\"AVGRank\"": "109",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "109"
	},
	{
		"\"\"": "\"110\"",
		"\"Rank\"": "110",
		"\"Player\"": "\"Russell Wilson\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "25",
		"\"AVGRank\"": "110",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "110"
	},
	{
		"\"\"": "\"111\"",
		"\"Rank\"": "111",
		"\"Player\"": "\"Gabe Davis\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "49",
		"\"AVGRank\"": "111",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "111"
	},
	{
		"\"\"": "\"112\"",
		"\"Rank\"": "112",
		"\"Player\"": "\"Brian Robinson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "26",
		"\"AVGRank\"": "112",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "112"
	},
	{
		"\"\"": "\"113\"",
		"\"Rank\"": "113",
		"\"Player\"": "\"Tyler Lockett\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "50",
		"\"AVGRank\"": "113",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "113"
	},
	{
		"\"\"": "\"114\"",
		"\"Rank\"": "114",
		"\"Player\"": "\"Kenny Pickett\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "26",
		"\"AVGRank\"": "114",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "114"
	},
	{
		"\"\"": "\"115\"",
		"\"Rank\"": "115",
		"\"Player\"": "\"Michael Mayer\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "13",
		"\"AVGRank\"": "115",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "115"
	},
	{
		"\"\"": "\"116\"",
		"\"Rank\"": "116",
		"\"Player\"": "\"Kyren Williams\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "27",
		"\"AVGRank\"": "116",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "116"
	},
	{
		"\"\"": "\"117\"",
		"\"Rank\"": "117",
		"\"Player\"": "\"Aidan O'Connell\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "27",
		"\"AVGRank\"": "117",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "117"
	},
	{
		"\"\"": "\"118\"",
		"\"Rank\"": "118",
		"\"Player\"": "\"Adam Thielen\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "51",
		"\"AVGRank\"": "118",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "118"
	},
	{
		"\"\"": "\"119\"",
		"\"Rank\"": "119",
		"\"Player\"": "\"Nick Chubb\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "28",
		"\"AVGRank\"": "119",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "119"
	},
	{
		"\"\"": "\"120\"",
		"\"Rank\"": "120",
		"\"Player\"": "\"Dallas Goedert\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "14",
		"\"AVGRank\"": "120",
		"\"AVGTier\"": "6",
		"\"Siegele11.11\"": "120"
	},
	{
		"\"\"": "\"121\"",
		"\"Rank\"": "121",
		"\"Player\"": "\"Keaton Mitchell\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "29",
		"\"AVGRank\"": "121",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "121"
	},
	{
		"\"\"": "\"122\"",
		"\"Rank\"": "122",
		"\"Player\"": "\"Jaylen Warren\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "30",
		"\"AVGRank\"": "122",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "122"
	},
	{
		"\"\"": "\"123\"",
		"\"Rank\"": "123",
		"\"Player\"": "\"Treylon Burks\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "52",
		"\"AVGRank\"": "123",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "123"
	},
	{
		"\"\"": "\"124\"",
		"\"Rank\"": "124",
		"\"Player\"": "\"Jerome Ford\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "31",
		"\"AVGRank\"": "124",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "124"
	},
	{
		"\"\"": "\"125\"",
		"\"Rank\"": "125",
		"\"Player\"": "\"Joe Mixon\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "32",
		"\"AVGRank\"": "125",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "125"
	},
	{
		"\"\"": "\"126\"",
		"\"Rank\"": "126",
		"\"Player\"": "\"J.K. Dobbins\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "33",
		"\"AVGRank\"": "126",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "126"
	},
	{
		"\"\"": "\"127\"",
		"\"Rank\"": "127",
		"\"Player\"": "\"Isiah Pacheco\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "34",
		"\"AVGRank\"": "127",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "127"
	},
	{
		"\"\"": "\"128\"",
		"\"Rank\"": "128",
		"\"Player\"": "\"Kendre Miller\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "35",
		"\"AVGRank\"": "128",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "128"
	},
	{
		"\"\"": "\"129\"",
		"\"Rank\"": "129",
		"\"Player\"": "\"Khalil Herbert\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "36",
		"\"AVGRank\"": "130",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "130"
	},
	{
		"\"\"": "\"130\"",
		"\"Rank\"": "130",
		"\"Player\"": "\"Jaleel McLaughlin\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "37",
		"\"AVGRank\"": "129",
		"\"AVGTier\"": "NA",
		"\"Siegele11.11\"": "129"
	},
	{
		"\"\"": "\"131\"",
		"\"Rank\"": "131",
		"\"Player\"": "\"Mac Jones\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "28",
		"\"AVGRank\"": "131",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "131"
	},
	{
		"\"\"": "\"132\"",
		"\"Rank\"": "132",
		"\"Player\"": "\"Michael Wilson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "53",
		"\"AVGRank\"": "132",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "132"
	},
	{
		"\"\"": "\"133\"",
		"\"Rank\"": "133",
		"\"Player\"": "\"Jake Ferguson\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "15",
		"\"AVGRank\"": "133",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "133"
	},
	{
		"\"\"": "\"134\"",
		"\"Rank\"": "134",
		"\"Player\"": "\"Daniel Jones\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "29",
		"\"AVGRank\"": "134",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "134"
	},
	{
		"\"\"": "\"135\"",
		"\"Rank\"": "135",
		"\"Player\"": "\"Courtland Sutton\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "54",
		"\"AVGRank\"": "135",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "135"
	},
	{
		"\"\"": "\"136\"",
		"\"Rank\"": "136",
		"\"Player\"": "\"Romeo Doubs\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "55",
		"\"AVGRank\"": "136",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "136"
	},
	{
		"\"\"": "\"137\"",
		"\"Rank\"": "137",
		"\"Player\"": "\"Darren Waller\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "16",
		"\"AVGRank\"": "137",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "137"
	},
	{
		"\"\"": "\"138\"",
		"\"Rank\"": "138",
		"\"Player\"": "\"Baker Mayfield\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "30",
		"\"AVGRank\"": "138",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "138"
	},
	{
		"\"\"": "\"139\"",
		"\"Rank\"": "139",
		"\"Player\"": "\"Aaron Rodgers\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "31",
		"\"AVGRank\"": "139",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "139"
	},
	{
		"\"\"": "\"140\"",
		"\"Rank\"": "140",
		"\"Player\"": "\"Gardner Minshew\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "32",
		"\"AVGRank\"": "140",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "140"
	},
	{
		"\"\"": "\"141\"",
		"\"Rank\"": "141",
		"\"Player\"": "\"Tank Bigsby\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "38",
		"\"AVGRank\"": "141",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "141"
	},
	{
		"\"\"": "\"142\"",
		"\"Rank\"": "142",
		"\"Player\"": "\"Najee Harris\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "39",
		"\"AVGRank\"": "142",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "142"
	},
	{
		"\"\"": "\"143\"",
		"\"Rank\"": "143",
		"\"Player\"": "\"Alexander Mattison\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "40",
		"\"AVGRank\"": "143",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "143"
	},
	{
		"\"\"": "\"144\"",
		"\"Rank\"": "144",
		"\"Player\"": "\"Chuba Hubbard\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "41",
		"\"AVGRank\"": "144",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "144"
	},
	{
		"\"\"": "\"145\"",
		"\"Rank\"": "145",
		"\"Player\"": "\"Rashid Shaheed\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "56",
		"\"AVGRank\"": "145",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "145"
	},
	{
		"\"\"": "\"146\"",
		"\"Rank\"": "146",
		"\"Player\"": "\"Elijah Moore\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "57",
		"\"AVGRank\"": "146",
		"\"AVGTier\"": "7",
		"\"Siegele11.11\"": "146"
	},
	{
		"\"\"": "\"147\"",
		"\"Rank\"": "147",
		"\"Player\"": "\"Gus Edwards\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "42",
		"\"AVGRank\"": "147",
		"\"AVGTier\"": "8",
		"\"Siegele11.11\"": "147"
	},
	{
		"\"\"": "\"148\"",
		"\"Rank\"": "148",
		"\"Player\"": "\"Tyler Allgeier\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "43",
		"\"AVGRank\"": "149",
		"\"AVGTier\"": "8",
		"\"Siegele11.11\"": "149"
	},
	{
		"\"\"": "\"149\"",
		"\"Rank\"": "149",
		"\"Player\"": "\"Jayden Reed\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "58",
		"\"AVGRank\"": "148",
		"\"AVGTier\"": "8",
		"\"Siegele11.11\"": "148"
	},
	{
		"\"\"": "\"150\"",
		"\"Rank\"": "150",
		"\"Player\"": "\"James Conner\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "44",
		"\"AVGRank\"": "150",
		"\"AVGTier\"": "8",
		"\"Siegele11.11\"": "150"
	},
	{
		"\"\"": "\"151\"",
		"\"Rank\"": "151",
		"\"Player\"": "\"David Njoku\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "17",
		"\"AVGRank\"": "151",
		"\"AVGTier\"": "8",
		"\"Siegele11.11\"": "151"
	},
	{
		"\"\"": "\"152\"",
		"\"Rank\"": "152",
		"\"Player\"": "\"Antonio Gibson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "45",
		"\"AVGRank\"": "152",
		"\"AVGTier\"": "8",
		"\"Siegele11.11\"": "152"
	},
	{
		"\"\"": "\"153\"",
		"\"Rank\"": "153",
		"\"Player\"": "\"Rashod Bateman\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "59",
		"\"AVGRank\"": "153",
		"\"AVGTier\"": "8",
		"\"Siegele11.11\"": "153"
	},
	{
		"\"\"": "\"154\"",
		"\"Rank\"": "154",
		"\"Player\"": "\"Dameon Pierce\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "46",
		"\"AVGRank\"": "154",
		"\"AVGTier\"": "8",
		"\"Siegele11.11\"": "154"
	},
	{
		"\"\"": "\"155\"",
		"\"Rank\"": "155",
		"\"Player\"": "\"Rondale Moore\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "60",
		"\"AVGRank\"": "155",
		"\"AVGTier\"": "8",
		"\"Siegele11.11\"": "155"
	},
	{
		"\"\"": "\"156\"",
		"\"Rank\"": "156",
		"\"Player\"": "\"Miles Sanders\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "47",
		"\"AVGRank\"": "156",
		"\"AVGTier\"": "8",
		"\"Siegele11.11\"": "156"
	},
	{
		"\"\"": "\"157\"",
		"\"Rank\"": "157",
		"\"Player\"": "\"Dalton Schultz\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "18",
		"\"AVGRank\"": "157",
		"\"AVGTier\"": "8",
		"\"Siegele11.11\"": "157"
	},
	{
		"\"\"": "\"158\"",
		"\"Rank\"": "158",
		"\"Player\"": "\"Michael Thomas\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "61",
		"\"AVGRank\"": "158",
		"\"AVGTier\"": "8",
		"\"Siegele11.11\"": "158"
	},
	{
		"\"\"": "\"159\"",
		"\"Rank\"": "159",
		"\"Player\"": "\"Mike Williams\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "62",
		"\"AVGRank\"": "159",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "159"
	},
	{
		"\"\"": "\"160\"",
		"\"Rank\"": "160",
		"\"Player\"": "\"Jimmy Garoppolo\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "33",
		"\"AVGRank\"": "160",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "160"
	},
	{
		"\"\"": "\"161\"",
		"\"Rank\"": "161",
		"\"Player\"": "\"Ryan Tannehill\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "34",
		"\"AVGRank\"": "162",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "162"
	},
	{
		"\"\"": "\"162\"",
		"\"Rank\"": "162",
		"\"Player\"": "\"Jonathan Mingo\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "63",
		"\"AVGRank\"": "161",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "161"
	},
	{
		"\"\"": "\"163\"",
		"\"Rank\"": "163",
		"\"Player\"": "\"Kenneth Gainwell\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "48",
		"\"AVGRank\"": "163",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "163"
	},
	{
		"\"\"": "\"164\"",
		"\"Rank\"": "164",
		"\"Player\"": "\"Dalvin Cook\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "49",
		"\"AVGRank\"": "164",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "164"
	},
	{
		"\"\"": "\"165\"",
		"\"Rank\"": "165",
		"\"Player\"": "\"Greg Dulcich\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "19",
		"\"AVGRank\"": "165",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "165"
	},
	{
		"\"\"": "\"166\"",
		"\"Rank\"": "166",
		"\"Player\"": "\"Curtis Samuel\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "64",
		"\"AVGRank\"": "166",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "166"
	},
	{
		"\"\"": "\"167\"",
		"\"Rank\"": "167",
		"\"Player\"": "\"Irv Smith\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "20",
		"\"AVGRank\"": "167",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "167"
	},
	{
		"\"\"": "\"168\"",
		"\"Rank\"": "168",
		"\"Player\"": "\"Darnell Mooney\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "65",
		"\"AVGRank\"": "169",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "169"
	},
	{
		"\"\"": "\"169\"",
		"\"Rank\"": "169",
		"\"Player\"": "\"Andrei Iosivas\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "66",
		"\"AVGRank\"": "168",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "168"
	},
	{
		"\"\"": "\"170\"",
		"\"Rank\"": "170",
		"\"Player\"": "\"AJ Dillon\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "50",
		"\"AVGRank\"": "170",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "170"
	},
	{
		"\"\"": "\"171\"",
		"\"Rank\"": "171",
		"\"Player\"": "\"Zay Jones\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "67",
		"\"AVGRank\"": "171",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "171"
	},
	{
		"\"\"": "\"172\"",
		"\"Rank\"": "172",
		"\"Player\"": "\"Desmond Ridder\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "35",
		"\"AVGRank\"": "172",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "172"
	},
	{
		"\"\"": "\"173\"",
		"\"Rank\"": "173",
		"\"Player\"": "\"Elijah Mitchell\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "51",
		"\"AVGRank\"": "173",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "173"
	},
	{
		"\"\"": "\"174\"",
		"\"Rank\"": "174",
		"\"Player\"": "\"Rico Dowdle\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "52",
		"\"AVGRank\"": "174",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "174"
	},
	{
		"\"\"": "\"175\"",
		"\"Rank\"": "175",
		"\"Player\"": "\"Chigoziem Okonkwo\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "21",
		"\"AVGRank\"": "175",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "175"
	},
	{
		"\"\"": "\"176\"",
		"\"Rank\"": "176",
		"\"Player\"": "\"Kareem Hunt\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "53",
		"\"AVGRank\"": "176",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "176"
	},
	{
		"\"\"": "\"177\"",
		"\"Rank\"": "177",
		"\"Player\"": "\"Hunter Henry\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "22",
		"\"AVGRank\"": "177",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "177"
	},
	{
		"\"\"": "\"178\"",
		"\"Rank\"": "178",
		"\"Player\"": "\"Trey Palmer\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "68",
		"\"AVGRank\"": "178",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "178"
	},
	{
		"\"\"": "\"179\"",
		"\"Rank\"": "179",
		"\"Player\"": "\"Samaje Perine\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "54",
		"\"AVGRank\"": "179",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "179"
	},
	{
		"\"\"": "\"180\"",
		"\"Rank\"": "180",
		"\"Player\"": "\"Pierre Strong\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "55",
		"\"AVGRank\"": "180",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "180"
	},
	{
		"\"\"": "\"181\"",
		"\"Rank\"": "181",
		"\"Player\"": "\"Chase Brown\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "56",
		"\"AVGRank\"": "181",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "181"
	},
	{
		"\"\"": "\"182\"",
		"\"Rank\"": "182",
		"\"Player\"": "\"Zach Evans\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "57",
		"\"AVGRank\"": "182",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "182"
	},
	{
		"\"\"": "\"183\"",
		"\"Rank\"": "183",
		"\"Player\"": "\"Noah Fant\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "23",
		"\"AVGRank\"": "183",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "183"
	},
	{
		"\"\"": "\"184\"",
		"\"Rank\"": "184",
		"\"Player\"": "\"Sean Tucker\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "58",
		"\"AVGRank\"": "184",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "184"
	},
	{
		"\"\"": "\"185\"",
		"\"Rank\"": "185",
		"\"Player\"": "\"Skyy Moore\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "69",
		"\"AVGRank\"": "185",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "185"
	},
	{
		"\"\"": "\"186\"",
		"\"Rank\"": "186",
		"\"Player\"": "\"Jerick McKinnon\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "59",
		"\"AVGRank\"": "186",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "186"
	},
	{
		"\"\"": "\"187\"",
		"\"Rank\"": "187",
		"\"Player\"": "\"Tyler Boyd\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "70",
		"\"AVGRank\"": "187",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "187"
	},
	{
		"\"\"": "\"188\"",
		"\"Rank\"": "188",
		"\"Player\"": "\"Brandin Cooks\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "71",
		"\"AVGRank\"": "188",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "188"
	},
	{
		"\"\"": "\"189\"",
		"\"Rank\"": "189",
		"\"Player\"": "\"Rashaad Penny\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "60",
		"\"AVGRank\"": "189",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "189"
	},
	{
		"\"\"": "\"190\"",
		"\"Rank\"": "190",
		"\"Player\"": "\"Tyler Higbee\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "24",
		"\"AVGRank\"": "190",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "190"
	},
	{
		"\"\"": "\"191\"",
		"\"Rank\"": "191",
		"\"Player\"": "\"Hendon Hooker\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "36",
		"\"AVGRank\"": "191",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "191"
	},
	{
		"\"\"": "\"192\"",
		"\"Rank\"": "192",
		"\"Player\"": "\"Taysom Hill\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"\"",
		"\"PosRank\"": "25",
		"\"AVGRank\"": "192",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "192"
	},
	{
		"\"\"": "\"193\"",
		"\"Rank\"": "193",
		"\"Player\"": "\"Odell Beckham\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "72",
		"\"AVGRank\"": "193",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "193"
	},
	{
		"\"\"": "\"194\"",
		"\"Rank\"": "194",
		"\"Player\"": "\"Devin Singletary\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "61",
		"\"AVGRank\"": "194",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "194"
	},
	{
		"\"\"": "\"195\"",
		"\"Rank\"": "195",
		"\"Player\"": "\"Jeff Wilson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "62",
		"\"AVGRank\"": "195",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "195"
	},
	{
		"\"\"": "\"196\"",
		"\"Rank\"": "196",
		"\"Player\"": "\"Tutu Atwell\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "73",
		"\"AVGRank\"": "196",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "196"
	},
	{
		"\"\"": "\"197\"",
		"\"Rank\"": "197",
		"\"Player\"": "\"Kadarius Toney\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "74",
		"\"AVGRank\"": "197",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "197"
	},
	{
		"\"\"": "\"198\"",
		"\"Rank\"": "198",
		"\"Player\"": "\"DJ Chark\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "75",
		"\"AVGRank\"": "198",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "198"
	},
	{
		"\"\"": "\"199\"",
		"\"Rank\"": "199",
		"\"Player\"": "\"Khalil Shakir\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "76",
		"\"AVGRank\"": "199",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "199"
	},
	{
		"\"\"": "\"200\"",
		"\"Rank\"": "200",
		"\"Player\"": "\"Tyler Conklin\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "26",
		"\"AVGRank\"": "200",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "200"
	},
	{
		"\"\"": "\"201\"",
		"\"Rank\"": "201",
		"\"Player\"": "\"Jamaal Williams\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "63",
		"\"AVGRank\"": "201",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "201"
	},
	{
		"\"\"": "\"202\"",
		"\"Rank\"": "202",
		"\"Player\"": "\"Gerald Everett\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "27",
		"\"AVGRank\"": "202",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "202"
	},
	{
		"\"\"": "\"203\"",
		"\"Rank\"": "203",
		"\"Player\"": "\"D'Onta Foreman\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "64",
		"\"AVGRank\"": "203",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "203"
	},
	{
		"\"\"": "\"204\"",
		"\"Rank\"": "204",
		"\"Player\"": "\"Justice Hill\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "65",
		"\"AVGRank\"": "204",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "204"
	},
	{
		"\"\"": "\"205\"",
		"\"Rank\"": "205",
		"\"Player\"": "\"Israel Abanikanda\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "66",
		"\"AVGRank\"": "205",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "205"
	},
	{
		"\"\"": "\"206\"",
		"\"Rank\"": "206",
		"\"Player\"": "\"Darnell Washington\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "28",
		"\"AVGRank\"": "206",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "206"
	},
	{
		"\"\"": "\"207\"",
		"\"Rank\"": "207",
		"\"Player\"": "\"Zamir White\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "67",
		"\"AVGRank\"": "207",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "207"
	},
	{
		"\"\"": "\"208\"",
		"\"Rank\"": "208",
		"\"Player\"": "\"K.J. Osborn\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "77",
		"\"AVGRank\"": "208",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "208"
	},
	{
		"\"\"": "\"209\"",
		"\"Rank\"": "209",
		"\"Player\"": "\"Joshua Palmer\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "78",
		"\"AVGRank\"": "209",
		"\"AVGTier\"": "9",
		"\"Siegele11.11\"": "209"
	},
	{
		"\"\"": "\"210\"",
		"\"Rank\"": "210",
		"\"Player\"": "\"Juwan Johnson\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "29",
		"\"AVGRank\"": "210",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "210"
	},
	{
		"\"\"": "\"211\"",
		"\"Rank\"": "211",
		"\"Player\"": "\"Trey Lance\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "37",
		"\"AVGRank\"": "211",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "211"
	},
	{
		"\"\"": "\"212\"",
		"\"Rank\"": "212",
		"\"Player\"": "\"Cade Otton\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "30",
		"\"AVGRank\"": "212",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "212"
	},
	{
		"\"\"": "\"213\"",
		"\"Rank\"": "213",
		"\"Player\"": "\"Luke Schoonmaker\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "31",
		"\"AVGRank\"": "213",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "213"
	},
	{
		"\"\"": "\"214\"",
		"\"Rank\"": "214",
		"\"Player\"": "\"Jordan Mason\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "68",
		"\"AVGRank\"": "214",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "214"
	},
	{
		"\"\"": "\"215\"",
		"\"Rank\"": "215",
		"\"Player\"": "\"Darrell Henderson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"FA\"",
		"\"PosRank\"": "69",
		"\"AVGRank\"": "215",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "215"
	},
	{
		"\"\"": "\"216\"",
		"\"Rank\"": "216",
		"\"Player\"": "\"Joshua Kelley\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "70",
		"\"AVGRank\"": "216",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "216"
	},
	{
		"\"\"": "\"217\"",
		"\"Rank\"": "217",
		"\"Player\"": "\"Zach Ertz\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"FA\"",
		"\"PosRank\"": "32",
		"\"AVGRank\"": "217",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "217"
	},
	{
		"\"\"": "\"218\"",
		"\"Rank\"": "218",
		"\"Player\"": "\"Chase Claypool\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "79",
		"\"AVGRank\"": "218",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "218"
	},
	{
		"\"\"": "\"219\"",
		"\"Rank\"": "219",
		"\"Player\"": "\"Dontayvion Wicks\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "80",
		"\"AVGRank\"": "219",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "219"
	},
	{
		"\"\"": "\"220\"",
		"\"Rank\"": "220",
		"\"Player\"": "\"Evan Hull\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "71",
		"\"AVGRank\"": "220",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "220"
	},
	{
		"\"\"": "\"221\"",
		"\"Rank\"": "221",
		"\"Player\"": "\"Kylen Granson\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "33",
		"\"AVGRank\"": "221",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "221"
	},
	{
		"\"\"": "\"222\"",
		"\"Rank\"": "222",
		"\"Player\"": "\"Jelani Woods\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "34",
		"\"AVGRank\"": "222",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "222"
	},
	{
		"\"\"": "\"223\"",
		"\"Rank\"": "223",
		"\"Player\"": "\"Cam Akers\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "72",
		"\"AVGRank\"": "223",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "223"
	},
	{
		"\"\"": "\"224\"",
		"\"Rank\"": "224",
		"\"Player\"": "\"Mike Gesicki\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "35",
		"\"AVGRank\"": "224",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "224"
	},
	{
		"\"\"": "\"225\"",
		"\"Rank\"": "225",
		"\"Player\"": "\"Deuce Vaughn\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "73",
		"\"AVGRank\"": "225",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "225"
	},
	{
		"\"\"": "\"226\"",
		"\"Rank\"": "226",
		"\"Player\"": "\"Ezekiel Elliott\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "74",
		"\"AVGRank\"": "226",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "226"
	},
	{
		"\"\"": "\"227\"",
		"\"Rank\"": "227",
		"\"Player\"": "\"Alec Pierce\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "81",
		"\"AVGRank\"": "227",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "227"
	},
	{
		"\"\"": "\"228\"",
		"\"Rank\"": "228",
		"\"Player\"": "\"Damien Harris\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "75",
		"\"AVGRank\"": "228",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "228"
	},
	{
		"\"\"": "\"229\"",
		"\"Rank\"": "229",
		"\"Player\"": "\"John Metchie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "82",
		"\"AVGRank\"": "229",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "229"
	},
	{
		"\"\"": "\"230\"",
		"\"Rank\"": "230",
		"\"Player\"": "\"Isaiah Likely\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "36",
		"\"AVGRank\"": "230",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "230"
	},
	{
		"\"\"": "\"231\"",
		"\"Rank\"": "231",
		"\"Player\"": "\"Cedric Tillman\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "83",
		"\"AVGRank\"": "232",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "232"
	},
	{
		"\"\"": "\"232\"",
		"\"Rank\"": "232",
		"\"Player\"": "\"Jonnu Smith\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "37",
		"\"AVGRank\"": "231",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "231"
	},
	{
		"\"\"": "\"233\"",
		"\"Rank\"": "233",
		"\"Player\"": "\"Tucker Kraft\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "38",
		"\"AVGRank\"": "233",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "233"
	},
	{
		"\"\"": "\"234\"",
		"\"Rank\"": "234",
		"\"Player\"": "\"Dawson Knox\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "39",
		"\"AVGRank\"": "234",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "234"
	},
	{
		"\"\"": "\"235\"",
		"\"Rank\"": "235",
		"\"Player\"": "\"Zach Wilson\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "38",
		"\"AVGRank\"": "235",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "235"
	},
	{
		"\"\"": "\"236\"",
		"\"Rank\"": "236",
		"\"Player\"": "\"Ty Chandler\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "76",
		"\"AVGRank\"": "236",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "236"
	},
	{
		"\"\"": "\"237\"",
		"\"Rank\"": "237",
		"\"Player\"": "\"Dyami Brown\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "84",
		"\"AVGRank\"": "237",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "237"
	},
	{
		"\"\"": "\"238\"",
		"\"Rank\"": "238",
		"\"Player\"": "\"DeWayne McBride\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "77",
		"\"AVGRank\"": "238",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "238"
	},
	{
		"\"\"": "\"239\"",
		"\"Rank\"": "239",
		"\"Player\"": "\"Jalen Tolbert\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "85",
		"\"AVGRank\"": "239",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "239"
	},
	{
		"\"\"": "\"240\"",
		"\"Rank\"": "240",
		"\"Player\"": "\"Durham Smythe\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "40",
		"\"AVGRank\"": "240",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "240"
	},
	{
		"\"\"": "\"241\"",
		"\"Rank\"": "241",
		"\"Player\"": "\"A.T. Perry\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "86",
		"\"AVGRank\"": "241",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "241"
	},
	{
		"\"\"": "\"242\"",
		"\"Rank\"": "242",
		"\"Player\"": "\"Isaiah Hodgins\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "87",
		"\"AVGRank\"": "242",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "242"
	},
	{
		"\"\"": "\"243\"",
		"\"Rank\"": "243",
		"\"Player\"": "\"Albert Okwuegbunam\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "41",
		"\"AVGRank\"": "243",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "243"
	},
	{
		"\"\"": "\"244\"",
		"\"Rank\"": "244",
		"\"Player\"": "\"Michael Gallup\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "88",
		"\"AVGRank\"": "244",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "244"
	},
	{
		"\"\"": "\"245\"",
		"\"Rank\"": "245",
		"\"Player\"": "\"Allen Lazard\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "89",
		"\"AVGRank\"": "245",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "245"
	},
	{
		"\"\"": "\"246\"",
		"\"Rank\"": "246",
		"\"Player\"": "\"Isaiah Spiller\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "78",
		"\"AVGRank\"": "246",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "246"
	},
	{
		"\"\"": "\"247\"",
		"\"Rank\"": "247",
		"\"Player\"": "\"Latavius Murray\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "79",
		"\"AVGRank\"": "247",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "247"
	},
	{
		"\"\"": "\"248\"",
		"\"Rank\"": "248",
		"\"Player\"": "\"Chris Rodriguez",
		"\"POS\"": " Jr.\"",
		"\"Team\"": "\"RB\"",
		"\"PosRank\"": "\"\"",
		"\"AVGRank\"": "80",
		"\"AVGTier\"": "248",
		"\"Siegele11.11\"": "10"
	},
	{
		"\"\"": "\"249\"",
		"\"Rank\"": "249",
		"\"Player\"": "\"Tre Tucker\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "90",
		"\"AVGRank\"": "249",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "249"
	},
	{
		"\"\"": "\"250\"",
		"\"Rank\"": "250",
		"\"Player\"": "\"Clyde Edwards-Helaire\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "81",
		"\"AVGRank\"": "250",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "250"
	},
	{
		"\"\"": "\"251\"",
		"\"Rank\"": "251",
		"\"Player\"": "\"Tyquan Thornton\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "91",
		"\"AVGRank\"": "251",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "251"
	},
	{
		"\"\"": "\"252\"",
		"\"Rank\"": "252",
		"\"Player\"": "\"Daniel Bellinger\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "42",
		"\"AVGRank\"": "252",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "252"
	},
	{
		"\"\"": "\"253\"",
		"\"Rank\"": "253",
		"\"Player\"": "\"Mecole Hardman\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "92",
		"\"AVGRank\"": "253",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "253"
	},
	{
		"\"\"": "\"254\"",
		"\"Rank\"": "254",
		"\"Player\"": "\"Kayshon Boutte\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "93",
		"\"AVGRank\"": "255",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "255"
	},
	{
		"\"\"": "\"255\"",
		"\"Rank\"": "255",
		"\"Player\"": "\"Josh Reynolds\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "94",
		"\"AVGRank\"": "254",
		"\"AVGTier\"": "10",
		"\"Siegele11.11\"": "254"
	},
	{
		"\"\"": "\"256\"",
		"\"Rank\"": "256",
		"\"Player\"": "\"Hunter Renfrow\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "95",
		"\"AVGRank\"": "256",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "256"
	},
	{
		"\"\"": "\"257\"",
		"\"Rank\"": "257",
		"\"Player\"": "\"Terrace Marshall\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "96",
		"\"AVGRank\"": "257",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "257"
	},
	{
		"\"\"": "\"258\"",
		"\"Rank\"": "258",
		"\"Player\"": "\"Hayden Hurst\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "43",
		"\"AVGRank\"": "258",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "258"
	},
	{
		"\"\"": "\"259\"",
		"\"Rank\"": "259",
		"\"Player\"": "\"Chris Evans\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "82",
		"\"AVGRank\"": "259",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "259"
	},
	{
		"\"\"": "\"260\"",
		"\"Rank\"": "260",
		"\"Player\"": "\"JuJu Smith-Schuster\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "97",
		"\"AVGRank\"": "260",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "260"
	},
	{
		"\"\"": "\"261\"",
		"\"Rank\"": "261",
		"\"Player\"": "\"Eric Gray\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "83",
		"\"AVGRank\"": "261",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "261"
	},
	{
		"\"\"": "\"262\"",
		"\"Rank\"": "262",
		"\"Player\"": "\"DeVante Parker\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "98",
		"\"AVGRank\"": "262",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "262"
	},
	{
		"\"\"": "\"263\"",
		"\"Rank\"": "263",
		"\"Player\"": "\"Richie James\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "99",
		"\"AVGRank\"": "263",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "263"
	},
	{
		"\"\"": "\"264\"",
		"\"Rank\"": "264",
		"\"Player\"": "\"Parris Campbell\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "100",
		"\"AVGRank\"": "264",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "264"
	},
	{
		"\"\"": "\"265\"",
		"\"Rank\"": "265",
		"\"Player\"": "\"Donovan Peoples-Jones\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "101",
		"\"AVGRank\"": "265",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "265"
	},
	{
		"\"\"": "\"266\"",
		"\"Rank\"": "266",
		"\"Player\"": "\"Laviska Shenault\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "102",
		"\"AVGRank\"": "266",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "266"
	},
	{
		"\"\"": "\"267\"",
		"\"Rank\"": "267",
		"\"Player\"": "\"Leonard Fournette\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "84",
		"\"AVGRank\"": "267",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "267"
	},
	{
		"\"\"": "\"268\"",
		"\"Rank\"": "268",
		"\"Player\"": "\"Tyler Scott\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "103",
		"\"AVGRank\"": "268",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "268"
	},
	{
		"\"\"": "\"269\"",
		"\"Rank\"": "269",
		"\"Player\"": "\"KJ Hamler\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "104",
		"\"AVGRank\"": "269",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "269"
	},
	{
		"\"\"": "\"270\"",
		"\"Rank\"": "270",
		"\"Player\"": "\"Charlie Jones\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "105",
		"\"AVGRank\"": "270",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "270"
	},
	{
		"\"\"": "\"271\"",
		"\"Rank\"": "271",
		"\"Player\"": "\"Zack Kuntz\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "44",
		"\"AVGRank\"": "271",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "271"
	},
	{
		"\"\"": "\"272\"",
		"\"Rank\"": "272",
		"\"Player\"": "\"Deneric Prince\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "85",
		"\"AVGRank\"": "272",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "272"
	},
	{
		"\"\"": "\"273\"",
		"\"Rank\"": "273",
		"\"Player\"": "\"Robert Woods\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "106",
		"\"AVGRank\"": "273",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "273"
	},
	{
		"\"\"": "\"274\"",
		"\"Rank\"": "274",
		"\"Player\"": "\"Sam Darnold\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "39",
		"\"AVGRank\"": "274",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "274"
	},
	{
		"\"\"": "\"275\"",
		"\"Rank\"": "275",
		"\"Player\"": "\"Cordarrelle Patterson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "86",
		"\"AVGRank\"": "275",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "275"
	},
	{
		"\"\"": "\"276\"",
		"\"Rank\"": "276",
		"\"Player\"": "\"Bailey Zappe\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "40",
		"\"AVGRank\"": "276",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "276"
	},
	{
		"\"\"": "\"277\"",
		"\"Rank\"": "277",
		"\"Player\"": "\"Zonovan Knight\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "87",
		"\"AVGRank\"": "277",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "277"
	},
	{
		"\"\"": "\"278\"",
		"\"Rank\"": "278",
		"\"Player\"": "\"David Bell\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "107",
		"\"AVGRank\"": "278",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "278"
	},
	{
		"\"\"": "\"279\"",
		"\"Rank\"": "279",
		"\"Player\"": "\"Kenny McIntosh\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "88",
		"\"AVGRank\"": "279",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "279"
	},
	{
		"\"\"": "\"280\"",
		"\"Rank\"": "280",
		"\"Player\"": "\"Xavier Hutchinson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "108",
		"\"AVGRank\"": "280",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "280"
	},
	{
		"\"\"": "\"281\"",
		"\"Rank\"": "281",
		"\"Player\"": "\"James Robinson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "89",
		"\"AVGRank\"": "281",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "281"
	},
	{
		"\"\"": "\"282\"",
		"\"Rank\"": "282",
		"\"Player\"": "\"Jake Haener\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "41",
		"\"AVGRank\"": "282",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "282"
	},
	{
		"\"\"": "\"283\"",
		"\"Rank\"": "283",
		"\"Player\"": "\"Michael Carter\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "90",
		"\"AVGRank\"": "283",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "283"
	},
	{
		"\"\"": "\"284\"",
		"\"Rank\"": "284",
		"\"Player\"": "\"Parker Washington\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "109",
		"\"AVGRank\"": "284",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "284"
	},
	{
		"\"\"": "\"285\"",
		"\"Rank\"": "285",
		"\"Player\"": "\"Malik Willis\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "42",
		"\"AVGRank\"": "285",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "285"
	},
	{
		"\"\"": "\"286\"",
		"\"Rank\"": "286",
		"\"Player\"": "\"Isaiah McKenzie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "110",
		"\"AVGRank\"": "286",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "286"
	},
	{
		"\"\"": "\"287\"",
		"\"Rank\"": "287",
		"\"Player\"": "\"Tommy Tremble\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "45",
		"\"AVGRank\"": "287",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "287"
	},
	{
		"\"\"": "\"288\"",
		"\"Rank\"": "288",
		"\"Player\"": "\"Corey Davis\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"FA\"",
		"\"PosRank\"": "111",
		"\"AVGRank\"": "288",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "288"
	},
	{
		"\"\"": "\"289\"",
		"\"Rank\"": "289",
		"\"Player\"": "\"Danny Gray\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "112",
		"\"AVGRank\"": "289",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "289"
	},
	{
		"\"\"": "\"290\"",
		"\"Rank\"": "290",
		"\"Player\"": "\"Marquez Valdes-Scantling\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "113",
		"\"AVGRank\"": "290",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "290"
	},
	{
		"\"\"": "\"291\"",
		"\"Rank\"": "291",
		"\"Player\"": "\"Hassan Haskins\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "91",
		"\"AVGRank\"": "292",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "292"
	},
	{
		"\"\"": "\"292\"",
		"\"Rank\"": "292",
		"\"Player\"": "\"Taylor Heinicke\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "43",
		"\"AVGRank\"": "291",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "291"
	},
	{
		"\"\"": "\"293\"",
		"\"Rank\"": "293",
		"\"Player\"": "\"Ronald Jones\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"FA\"",
		"\"PosRank\"": "92",
		"\"AVGRank\"": "293",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "293"
	},
	{
		"\"\"": "\"294\"",
		"\"Rank\"": "294",
		"\"Player\"": "\"Tyrion Davis-Price\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "93",
		"\"AVGRank\"": "294",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "294"
	},
	{
		"\"\"": "\"295\"",
		"\"Rank\"": "295",
		"\"Player\"": "\"Nyheim Hines\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "94",
		"\"AVGRank\"": "295",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "295"
	},
	{
		"\"\"": "\"296\"",
		"\"Rank\"": "296",
		"\"Player\"": "\"Caleb Huntley\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"FA\"",
		"\"PosRank\"": "95",
		"\"AVGRank\"": "296",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "296"
	},
	{
		"\"\"": "\"297\"",
		"\"Rank\"": "297",
		"\"Player\"": "\"Marlon Mack\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "96",
		"\"AVGRank\"": "297",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "297"
	},
	{
		"\"\"": "\"298\"",
		"\"Rank\"": "298",
		"\"Player\"": "\"Kevin Harris\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "97",
		"\"AVGRank\"": "298",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "298"
	},
	{
		"\"\"": "\"299\"",
		"\"Rank\"": "299",
		"\"Player\"": "\"Russell Gage\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "114",
		"\"AVGRank\"": "299",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "299"
	},
	{
		"\"\"": "\"300\"",
		"\"Rank\"": "300",
		"\"Player\"": "\"D'Ernest Johnson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "98",
		"\"AVGRank\"": "300",
		"\"AVGTier\"": "11",
		"\"Siegele11.11\"": "300"
	},
	
]

module.exports = rvDynastyRankingsTEP;