const rvDynastyRankingsTEP = [
	{
		"\"\"": "\"1\"",
		"\"Rank\"": "1",
		"\"Player\"": "\"Jalen Hurts\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "1",
		"\"AVGRank\"": "2.5",
		"\"AVGTier\"": "1",
		"\"Siegele1.5\"": "4",
		"\"Patrick1.3\"": "1"
	},
	{
		"\"\"": "\"2\"",
		"\"Rank\"": "2",
		"\"Player\"": "\"Josh Allen\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "2",
		"\"AVGRank\"": "3.5",
		"\"AVGTier\"": "1",
		"\"Siegele1.5\"": "5",
		"\"Patrick1.3\"": "2"
	},
	{
		"\"\"": "\"3\"",
		"\"Rank\"": "3",
		"\"Player\"": "\"Justin Jefferson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "1",
		"\"AVGRank\"": "4.5",
		"\"AVGTier\"": "1",
		"\"Siegele1.5\"": "1",
		"\"Patrick1.3\"": "8"
	},
	{
		"\"\"": "\"4\"",
		"\"Rank\"": "4",
		"\"Player\"": "\"Patrick Mahomes\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "3",
		"\"AVGRank\"": "5",
		"\"AVGTier\"": "1",
		"\"Siegele1.5\"": "6",
		"\"Patrick1.3\"": "4"
	},
	{
		"\"\"": "\"5\"",
		"\"Rank\"": "5",
		"\"Player\"": "\"CeeDee Lamb\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "2",
		"\"AVGRank\"": "5.5",
		"\"AVGTier\"": "1",
		"\"Siegele1.5\"": "2",
		"\"Patrick1.3\"": "9"
	},
	{
		"\"\"": "\"6\"",
		"\"Rank\"": "6",
		"\"Player\"": "\"Lamar Jackson\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "4",
		"\"AVGRank\"": "6",
		"\"AVGTier\"": "1",
		"\"Siegele1.5\"": "9",
		"\"Patrick1.3\"": "3"
	},
	{
		"\"\"": "\"7\"",
		"\"Rank\"": "7",
		"\"Player\"": "\"C.J. Stroud\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "5",
		"\"AVGRank\"": "6",
		"\"AVGTier\"": "1",
		"\"Siegele1.5\"": "7",
		"\"Patrick1.3\"": "5"
	},
	{
		"\"\"": "\"8\"",
		"\"Rank\"": "8",
		"\"Player\"": "\"Ja'Marr Chase\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "3",
		"\"AVGRank\"": "6.5",
		"\"AVGTier\"": "1",
		"\"Siegele1.5\"": "3",
		"\"Patrick1.3\"": "10"
	},
	{
		"\"\"": "\"9\"",
		"\"Rank\"": "9",
		"\"Player\"": "\"Anthony Richardson\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "6",
		"\"AVGRank\"": "11",
		"\"AVGTier\"": "1",
		"\"Siegele1.5\"": "16",
		"\"Patrick1.3\"": "6"
	},
	{
		"\"\"": "\"10\"",
		"\"Rank\"": "10",
		"\"Player\"": "\"Amon-Ra St. Brown\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "4",
		"\"AVGRank\"": "11.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "10",
		"\"Patrick1.3\"": "13"
	},
	{
		"\"\"": "\"11\"",
		"\"Rank\"": "11",
		"\"Player\"": "\"Breece Hall\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "1",
		"\"AVGRank\"": "13",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "12",
		"\"Patrick1.3\"": "14"
	},
	{
		"\"\"": "\"12\"",
		"\"Rank\"": "12",
		"\"Player\"": "\"Jahmyr Gibbs\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "2",
		"\"AVGRank\"": "13.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "11",
		"\"Patrick1.3\"": "16"
	},
	{
		"\"\"": "\"13\"",
		"\"Rank\"": "13",
		"\"Player\"": "\"Justin Herbert\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "7",
		"\"AVGRank\"": "13.5",
		"\"AVGTier\"": "1",
		"\"Siegele1.5\"": "20",
		"\"Patrick1.3\"": "7"
	},
	{
		"\"\"": "\"14\"",
		"\"Rank\"": "14",
		"\"Player\"": "\"Bijan Robinson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "3",
		"\"AVGRank\"": "15",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "15",
		"\"Patrick1.3\"": "15"
	},
	{
		"\"\"": "\"15\"",
		"\"Rank\"": "15",
		"\"Player\"": "\"Garrett Wilson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "5",
		"\"AVGRank\"": "15.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "14",
		"\"Patrick1.3\"": "17"
	},
	{
		"\"\"": "\"16\"",
		"\"Rank\"": "16",
		"\"Player\"": "\"Joe Burrow\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "8",
		"\"AVGRank\"": "15.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "19",
		"\"Patrick1.3\"": "12"
	},
	{
		"\"\"": "\"17\"",
		"\"Rank\"": "17",
		"\"Player\"": "\"Christian McCaffrey\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "4",
		"\"AVGRank\"": "21",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "18",
		"\"Patrick1.3\"": "24"
	},
	{
		"\"\"": "\"18\"",
		"\"Rank\"": "18",
		"\"Player\"": "\"Chris Olave\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "6",
		"\"AVGRank\"": "21.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "25",
		"\"Patrick1.3\"": "18"
	},
	{
		"\"\"": "\"19\"",
		"\"Rank\"": "19",
		"\"Player\"": "\"A.J. Brown\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "7",
		"\"AVGRank\"": "22.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "26",
		"\"Patrick1.3\"": "19"
	},
	{
		"\"\"": "\"20\"",
		"\"Rank\"": "20",
		"\"Player\"": "\"Sam LaPorta\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "1",
		"\"AVGRank\"": "22.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "13",
		"\"Patrick1.3\"": "32"
	},
	{
		"\"\"": "\"21\"",
		"\"Rank\"": "21",
		"\"Player\"": "\"Devon Achane\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "5",
		"\"AVGRank\"": "23",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "17",
		"\"Patrick1.3\"": "29"
	},
	{
		"\"\"": "\"22\"",
		"\"Rank\"": "22",
		"\"Player\"": "\"Puka Nacua\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "8",
		"\"AVGRank\"": "23",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "23",
		"\"Patrick1.3\"": "23"
	},
	{
		"\"\"": "\"23\"",
		"\"Rank\"": "23",
		"\"Player\"": "\"Brock Purdy\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "9",
		"\"AVGRank\"": "24",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "22",
		"\"Patrick1.3\"": "26"
	},
	{
		"\"\"": "\"24\"",
		"\"Rank\"": "24",
		"\"Player\"": "\"Tyreek Hill\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "9",
		"\"AVGRank\"": "24.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "28",
		"\"Patrick1.3\"": "21"
	},
	{
		"\"\"": "\"25\"",
		"\"Rank\"": "25",
		"\"Player\"": "\"Kyler Murray\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "10",
		"\"AVGRank\"": "24.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "24",
		"\"Patrick1.3\"": "25"
	},
	{
		"\"\"": "\"26\"",
		"\"Rank\"": "26",
		"\"Player\"": "\"Justin Fields\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "11",
		"\"AVGRank\"": "25.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "8",
		"\"Patrick1.3\"": "43"
	},
	{
		"\"\"": "\"27\"",
		"\"Rank\"": "27",
		"\"Player\"": "\"Brandon Aiyuk\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "10",
		"\"AVGRank\"": "26.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "31",
		"\"Patrick1.3\"": "22"
	},
	{
		"\"\"": "\"28\"",
		"\"Rank\"": "28",
		"\"Player\"": "\"Trey McBride\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "2",
		"\"AVGRank\"": "27.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "21",
		"\"Patrick1.3\"": "34"
	},
	{
		"\"\"": "\"29\"",
		"\"Rank\"": "29",
		"\"Player\"": "\"Dak Prescott\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "12",
		"\"AVGRank\"": "30.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "34",
		"\"Patrick1.3\"": "27"
	},
	{
		"\"\"": "\"30\"",
		"\"Rank\"": "30",
		"\"Player\"": "\"Tua Tagovailoa\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "13",
		"\"AVGRank\"": "31",
		"\"AVGTier\"": "3",
		"\"Siegele1.5\"": "51",
		"\"Patrick1.3\"": "11"
	},
	{
		"\"\"": "\"31\"",
		"\"Rank\"": "31",
		"\"Player\"": "\"Jaylen Waddle\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "11",
		"\"AVGRank\"": "32",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "44",
		"\"Patrick1.3\"": "20"
	},
	{
		"\"\"": "\"32\"",
		"\"Rank\"": "32",
		"\"Player\"": "\"Jonathan Taylor\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "6",
		"\"AVGRank\"": "33",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "38",
		"\"Patrick1.3\"": "28"
	},
	{
		"\"\"": "\"33\"",
		"\"Rank\"": "33",
		"\"Player\"": "\"DJ Moore\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "12",
		"\"AVGRank\"": "33",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "29",
		"\"Patrick1.3\"": "37"
	},
	{
		"\"\"": "\"34\"",
		"\"Rank\"": "34",
		"\"Player\"": "\"DeVonta Smith\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "13",
		"\"AVGRank\"": "33.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "37",
		"\"Patrick1.3\"": "30"
	},
	{
		"\"\"": "\"35\"",
		"\"Rank\"": "35",
		"\"Player\"": "\"Tee Higgins\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "14",
		"\"AVGRank\"": "33.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "36",
		"\"Patrick1.3\"": "31"
	},
	{
		"\"\"": "\"36\"",
		"\"Rank\"": "36",
		"\"Player\"": "\"Jordan Addison\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "15",
		"\"AVGRank\"": "33.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "27",
		"\"Patrick1.3\"": "40"
	},
	{
		"\"\"": "\"37\"",
		"\"Rank\"": "37",
		"\"Player\"": "\"Jordan Love\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "14",
		"\"AVGRank\"": "36",
		"\"AVGTier\"": "3",
		"\"Siegele1.5\"": "30",
		"\"Patrick1.3\"": "42"
	},
	{
		"\"\"": "\"38\"",
		"\"Rank\"": "38",
		"\"Player\"": "\"Travis Etienne\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "7",
		"\"AVGRank\"": "37.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "39",
		"\"Patrick1.3\"": "36"
	},
	{
		"\"\"": "\"39\"",
		"\"Rank\"": "39",
		"\"Player\"": "\"Rashee Rice\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "16",
		"\"AVGRank\"": "39.5",
		"\"AVGTier\"": "3",
		"\"Siegele1.5\"": "32",
		"\"Patrick1.3\"": "47"
	},
	{
		"\"\"": "\"40\"",
		"\"Rank\"": "40",
		"\"Player\"": "\"Jaxon Smith-Njigba\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "17",
		"\"AVGRank\"": "40.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "40",
		"\"Patrick1.3\"": "41"
	},
	{
		"\"\"": "\"41\"",
		"\"Rank\"": "41",
		"\"Player\"": "\"Zay Flowers\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "18",
		"\"AVGRank\"": "40.5",
		"\"AVGTier\"": "3",
		"\"Siegele1.5\"": "33",
		"\"Patrick1.3\"": "48"
	},
	{
		"\"\"": "\"42\"",
		"\"Rank\"": "42",
		"\"Player\"": "\"DK Metcalf\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "19",
		"\"AVGRank\"": "41",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "43",
		"\"Patrick1.3\"": "39"
	},
	{
		"\"\"": "\"43\"",
		"\"Rank\"": "43",
		"\"Player\"": "\"Drake London\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "20",
		"\"AVGRank\"": "42.5",
		"\"AVGTier\"": "2",
		"\"Siegele1.5\"": "47",
		"\"Patrick1.3\"": "38"
	},
	{
		"\"\"": "\"44\"",
		"\"Rank\"": "44",
		"\"Player\"": "\"Kyren Williams\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "8",
		"\"AVGRank\"": "44",
		"\"AVGTier\"": "3",
		"\"Siegele1.5\"": "35",
		"\"Patrick1.3\"": "53"
	},
	{
		"\"\"": "\"45\"",
		"\"Rank\"": "45",
		"\"Player\"": "\"T.J. Hockenson\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "3",
		"\"AVGRank\"": "46",
		"\"AVGTier\"": "3",
		"\"Siegele1.5\"": "59",
		"\"Patrick1.3\"": "33"
	},
	{
		"\"\"": "\"46\"",
		"\"Rank\"": "46",
		"\"Player\"": "\"Nathaniel Dell\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"\"",
		"\"PosRank\"": "21",
		"\"AVGRank\"": "47",
		"\"AVGTier\"": "3",
		"\"Siegele1.5\"": "42",
		"\"Patrick1.3\"": "52"
	},
	{
		"\"\"": "\"47\"",
		"\"Rank\"": "47",
		"\"Player\"": "\"Deebo Samuel\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "22",
		"\"AVGRank\"": "47.5",
		"\"AVGTier\"": "3",
		"\"Siegele1.5\"": "46",
		"\"Patrick1.3\"": "49"
	},
	{
		"\"\"": "\"48\"",
		"\"Rank\"": "48",
		"\"Player\"": "\"Michael Pittman\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "23",
		"\"AVGRank\"": "47.5",
		"\"AVGTier\"": "3",
		"\"Siegele1.5\"": "49",
		"\"Patrick1.3\"": "46"
	},
	{
		"\"\"": "\"49\"",
		"\"Rank\"": "49",
		"\"Player\"": "\"Kenneth Walker\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "9",
		"\"AVGRank\"": "48.5",
		"\"AVGTier\"": "3",
		"\"Siegele1.5\"": "41",
		"\"Patrick1.3\"": "56"
	},
	{
		"\"\"": "\"50\"",
		"\"Rank\"": "50",
		"\"Player\"": "\"Mark Andrews\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "4",
		"\"AVGRank\"": "49",
		"\"AVGTier\"": "3",
		"\"Siegele1.5\"": "63",
		"\"Patrick1.3\"": "35"
	},
	{
		"\"\"": "\"51\"",
		"\"Rank\"": "51",
		"\"Player\"": "\"Trevor Lawrence\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "15",
		"\"AVGRank\"": "50.5",
		"\"AVGTier\"": "4",
		"\"Siegele1.5\"": "56",
		"\"Patrick1.3\"": "45"
	},
	{
		"\"\"": "\"52\"",
		"\"Rank\"": "52",
		"\"Player\"": "\"Christian Watson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "24",
		"\"AVGRank\"": "53",
		"\"AVGTier\"": "4",
		"\"Siegele1.5\"": "55",
		"\"Patrick1.3\"": "51"
	},
	{
		"\"\"": "\"53\"",
		"\"Rank\"": "53",
		"\"Player\"": "\"George Pickens\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "25",
		"\"AVGRank\"": "53.5",
		"\"AVGTier\"": "4",
		"\"Siegele1.5\"": "57",
		"\"Patrick1.3\"": "50"
	},
	{
		"\"\"": "\"54\"",
		"\"Rank\"": "54",
		"\"Player\"": "\"James Cook\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "10",
		"\"AVGRank\"": "54.5",
		"\"AVGTier\"": "4",
		"\"Siegele1.5\"": "50",
		"\"Patrick1.3\"": "59"
	},
	{
		"\"\"": "\"55\"",
		"\"Rank\"": "55",
		"\"Player\"": "\"Saquon Barkley\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "11",
		"\"AVGRank\"": "56.5",
		"\"AVGTier\"": "4",
		"\"Siegele1.5\"": "58",
		"\"Patrick1.3\"": "55"
	},
	{
		"\"\"": "\"56\"",
		"\"Rank\"": "56",
		"\"Player\"": "\"Dalton Kincaid\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "5",
		"\"AVGRank\"": "59",
		"\"AVGTier\"": "3",
		"\"Siegele1.5\"": "45",
		"\"Patrick1.3\"": "73"
	},
	{
		"\"\"": "\"57\"",
		"\"Rank\"": "57",
		"\"Player\"": "\"Deshaun Watson\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "16",
		"\"AVGRank\"": "60",
		"\"AVGTier\"": "4",
		"\"Siegele1.5\"": "76",
		"\"Patrick1.3\"": "44"
	},
	{
		"\"\"": "\"58\"",
		"\"Rank\"": "58",
		"\"Player\"": "\"Davante Adams\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "26",
		"\"AVGRank\"": "62.5",
		"\"AVGTier\"": "4",
		"\"Siegele1.5\"": "64",
		"\"Patrick1.3\"": "61"
	},
	{
		"\"\"": "\"59\"",
		"\"Rank\"": "59",
		"\"Player\"": "\"Rachaad White\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "12",
		"\"AVGRank\"": "63",
		"\"AVGTier\"": "4",
		"\"Siegele1.5\"": "69",
		"\"Patrick1.3\"": "57"
	},
	{
		"\"\"": "\"60\"",
		"\"Rank\"": "60",
		"\"Player\"": "\"Jared Goff\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "17",
		"\"AVGRank\"": "63",
		"\"AVGTier\"": "4",
		"\"Siegele1.5\"": "52",
		"\"Patrick1.3\"": "74"
	},
	{
		"\"\"": "\"61\"",
		"\"Rank\"": "61",
		"\"Player\"": "\"Cooper Kupp\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "27",
		"\"AVGRank\"": "64.5",
		"\"AVGTier\"": "4",
		"\"Siegele1.5\"": "62",
		"\"Patrick1.3\"": "67"
	},
	{
		"\"\"": "\"62\"",
		"\"Rank\"": "62",
		"\"Player\"": "\"Jayden Reed\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "28",
		"\"AVGRank\"": "63.5",
		"\"AVGTier\"": "3",
		"\"Siegele1.5\"": "48",
		"\"Patrick1.3\"": "79"
	},
	{
		"\"\"": "\"63\"",
		"\"Rank\"": "63",
		"\"Player\"": "\"Bryce Young\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "18",
		"\"AVGRank\"": "65",
		"\"AVGTier\"": "4",
		"\"Siegele1.5\"": "54",
		"\"Patrick1.3\"": "76"
	},
	{
		"\"\"": "\"64\"",
		"\"Rank\"": "64",
		"\"Player\"": "\"Nico Collins\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "29",
		"\"AVGRank\"": "65.5",
		"\"AVGTier\"": "4",
		"\"Siegele1.5\"": "53",
		"\"Patrick1.3\"": "78"
	},
	{
		"\"\"": "\"65\"",
		"\"Rank\"": "65",
		"\"Player\"": "\"Kyle Pitts\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "6",
		"\"AVGRank\"": "66",
		"\"AVGTier\"": "4",
		"\"Siegele1.5\"": "61",
		"\"Patrick1.3\"": "71"
	},
	{
		"\"\"": "\"66\"",
		"\"Rank\"": "66",
		"\"Player\"": "\"Stefon Diggs\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "30",
		"\"AVGRank\"": "67.5",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "71",
		"\"Patrick1.3\"": "64"
	},
	{
		"\"\"": "\"67\"",
		"\"Rank\"": "67",
		"\"Player\"": "\"Keenan Allen\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "31",
		"\"AVGRank\"": "68",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "73",
		"\"Patrick1.3\"": "63"
	},
	{
		"\"\"": "\"68\"",
		"\"Rank\"": "68",
		"\"Player\"": "\"Evan Engram\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "7",
		"\"AVGRank\"": "68",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "67",
		"\"Patrick1.3\"": "69"
	},
	{
		"\"\"": "\"69\"",
		"\"Rank\"": "69",
		"\"Player\"": "\"Travis Kelce\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "8",
		"\"AVGRank\"": "68.5",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "77",
		"\"Patrick1.3\"": "60"
	},
	{
		"\"\"": "\"70\"",
		"\"Rank\"": "70",
		"\"Player\"": "\"Josh Jacobs\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "13",
		"\"AVGRank\"": "71.5",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "89",
		"\"Patrick1.3\"": "54"
	},
	{
		"\"\"": "\"71\"",
		"\"Rank\"": "71",
		"\"Player\"": "\"George Kittle\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "9",
		"\"AVGRank\"": "71.5",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "75",
		"\"Patrick1.3\"": "68"
	},
	{
		"\"\"": "\"72\"",
		"\"Rank\"": "72",
		"\"Player\"": "\"Terry McLaurin\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "32",
		"\"AVGRank\"": "74.5",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "68",
		"\"Patrick1.3\"": "81"
	},
	{
		"\"\"": "\"73\"",
		"\"Rank\"": "73",
		"\"Player\"": "\"Cole Kmet\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "10",
		"\"AVGRank\"": "80",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "65",
		"\"Patrick1.3\"": "95"
	},
	{
		"\"\"": "\"74\"",
		"\"Rank\"": "74",
		"\"Player\"": "\"Kirk Cousins\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "19",
		"\"AVGRank\"": "80.5",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "70",
		"\"Patrick1.3\"": "91"
	},
	{
		"\"\"": "\"75\"",
		"\"Rank\"": "75",
		"\"Player\"": "\"Rhamondre Stevenson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "14",
		"\"AVGRank\"": "81.5",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "79",
		"\"Patrick1.3\"": "84"
	},
	{
		"\"\"": "\"76\"",
		"\"Rank\"": "76",
		"\"Player\"": "\"D'Andre Swift\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "15",
		"\"AVGRank\"": "81.5",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "105",
		"\"Patrick1.3\"": "58"
	},
	{
		"\"\"": "\"77\"",
		"\"Rank\"": "77",
		"\"Player\"": "\"David Montgomery\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "16",
		"\"AVGRank\"": "83",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "80",
		"\"Patrick1.3\"": "86"
	},
	{
		"\"\"": "\"78\"",
		"\"Rank\"": "78",
		"\"Player\"": "\"Amari Cooper\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "33",
		"\"AVGRank\"": "84.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "107",
		"\"Patrick1.3\"": "62"
	},
	{
		"\"\"": "\"79\"",
		"\"Rank\"": "79",
		"\"Player\"": "\"Javonte Williams\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "17",
		"\"AVGRank\"": "85",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "83",
		"\"Patrick1.3\"": "87"
	},
	{
		"\"\"": "\"80\"",
		"\"Rank\"": "80",
		"\"Player\"": "\"David Njoku\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "11",
		"\"AVGRank\"": "86.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "103",
		"\"Patrick1.3\"": "70"
	},
	{
		"\"\"": "\"81\"",
		"\"Rank\"": "81",
		"\"Player\"": "\"Najee Harris\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "18",
		"\"AVGRank\"": "88",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "84",
		"\"Patrick1.3\"": "92"
	},
	{
		"\"\"": "\"82\"",
		"\"Rank\"": "82",
		"\"Player\"": "\"Tony Pollard\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "19",
		"\"AVGRank\"": "89.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "113",
		"\"Patrick1.3\"": "66"
	},
	{
		"\"\"": "\"83\"",
		"\"Rank\"": "83",
		"\"Player\"": "\"Pat Freiermuth\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "12",
		"\"AVGRank\"": "89.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "85",
		"\"Patrick1.3\"": "94"
	},
	{
		"\"\"": "\"84\"",
		"\"Rank\"": "84",
		"\"Player\"": "\"Raheem Mostert\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "20",
		"\"AVGRank\"": "90",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "81",
		"\"Patrick1.3\"": "99"
	},
	{
		"\"\"": "\"85\"",
		"\"Rank\"": "85",
		"\"Player\"": "\"Jameson Williams\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "34",
		"\"AVGRank\"": "90.5",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "60",
		"\"Patrick1.3\"": "121"
	},
	{
		"\"\"": "\"86\"",
		"\"Rank\"": "86",
		"\"Player\"": "\"Diontae Johnson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "35",
		"\"AVGRank\"": "90.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "101",
		"\"Patrick1.3\"": "80"
	},
	{
		"\"\"": "\"87\"",
		"\"Rank\"": "87",
		"\"Player\"": "\"Luke Musgrave\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "13",
		"\"AVGRank\"": "90.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "88",
		"\"Patrick1.3\"": "93"
	},
	{
		"\"\"": "\"88\"",
		"\"Rank\"": "88",
		"\"Player\"": "\"Chris Godwin\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "36",
		"\"AVGRank\"": "92.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "102",
		"\"Patrick1.3\"": "83"
	},
	{
		"\"\"": "\"89\"",
		"\"Rank\"": "89",
		"\"Player\"": "\"Christian Kirk\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "37",
		"\"AVGRank\"": "94",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "123",
		"\"Patrick1.3\"": "65"
	},
	{
		"\"\"": "\"90\"",
		"\"Rank\"": "90",
		"\"Player\"": "\"Baker Mayfield\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "20",
		"\"AVGRank\"": "94",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "99",
		"\"Patrick1.3\"": "89"
	},
	{
		"\"\"": "\"91\"",
		"\"Rank\"": "91",
		"\"Player\"": "\"Mike Evans\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "38",
		"\"AVGRank\"": "94.5",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "74",
		"\"Patrick1.3\"": "115"
	},
	{
		"\"\"": "\"92\"",
		"\"Rank\"": "92",
		"\"Player\"": "\"Matthew Stafford\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "21",
		"\"AVGRank\"": "94.5",
		"\"AVGTier\"": "5",
		"\"Siegele1.5\"": "66",
		"\"Patrick1.3\"": "123"
	},
	{
		"\"\"": "\"93\"",
		"\"Rank\"": "93",
		"\"Player\"": "\"Michael Mayer\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "14",
		"\"AVGRank\"": "95.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "95",
		"\"Patrick1.3\"": "96"
	},
	{
		"\"\"": "\"94\"",
		"\"Rank\"": "94",
		"\"Player\"": "\"Josh Downs\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "39",
		"\"AVGRank\"": "95.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "87",
		"\"Patrick1.3\"": "104"
	},
	{
		"\"\"": "\"95\"",
		"\"Rank\"": "95",
		"\"Player\"": "\"Alvin Kamara\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "21",
		"\"AVGRank\"": "96",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "104",
		"\"Patrick1.3\"": "88"
	},
	{
		"\"\"": "\"96\"",
		"\"Rank\"": "96",
		"\"Player\"": "\"Sam Howell\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "22",
		"\"AVGRank\"": "96.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "118",
		"\"Patrick1.3\"": "75"
	},
	{
		"\"\"": "\"97\"",
		"\"Rank\"": "97",
		"\"Player\"": "\"Brian Robinson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "22",
		"\"AVGRank\"": "97.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "98",
		"\"Patrick1.3\"": "97"
	},
	{
		"\"\"": "\"98\"",
		"\"Rank\"": "98",
		"\"Player\"": "\"Calvin Ridley\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "40",
		"\"AVGRank\"": "98",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "114",
		"\"Patrick1.3\"": "82"
	},
	{
		"\"\"": "\"99\"",
		"\"Rank\"": "99",
		"\"Player\"": "\"Will Levis\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "23",
		"\"AVGRank\"": "98",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "106",
		"\"Patrick1.3\"": "90"
	},
	{
		"\"\"": "\"100\"",
		"\"Rank\"": "100",
		"\"Player\"": "\"Derek Carr\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "24",
		"\"AVGRank\"": "101.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "78",
		"\"Patrick1.3\"": "125"
	},
	{
		"\"\"": "\"101\"",
		"\"Rank\"": "101",
		"\"Player\"": "\"Marvin Mims\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "41",
		"\"AVGRank\"": "102",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "92",
		"\"Patrick1.3\"": "112"
	},
	{
		"\"\"": "\"102\"",
		"\"Rank\"": "102",
		"\"Player\"": "\"Austin Ekeler\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "23",
		"\"AVGRank\"": "102.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "128",
		"\"Patrick1.3\"": "77"
	},
	{
		"\"\"": "\"103\"",
		"\"Rank\"": "103",
		"\"Player\"": "\"Dallas Goedert\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "15",
		"\"AVGRank\"": "105",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "138",
		"\"Patrick1.3\"": "72"
	},
	{
		"\"\"": "\"104\"",
		"\"Rank\"": "104",
		"\"Player\"": "\"Wan'Dale Robinson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "42",
		"\"AVGRank\"": "105.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "91",
		"\"Patrick1.3\"": "120"
	},
	{
		"\"\"": "\"105\"",
		"\"Rank\"": "105",
		"\"Player\"": "\"Geno Smith\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "25",
		"\"AVGRank\"": "106",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "90",
		"\"Patrick1.3\"": "122"
	},
	{
		"\"\"": "\"106\"",
		"\"Rank\"": "106",
		"\"Player\"": "\"Jaylen Warren\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "24",
		"\"AVGRank\"": "108",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "82",
		"\"Patrick1.3\"": "134"
	},
	{
		"\"\"": "\"107\"",
		"\"Rank\"": "107",
		"\"Player\"": "\"Isiah Pacheco\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "25",
		"\"AVGRank\"": "110.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "86",
		"\"Patrick1.3\"": "135"
	},
	{
		"\"\"": "\"108\"",
		"\"Rank\"": "108",
		"\"Player\"": "\"Derrick Henry\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "26",
		"\"AVGRank\"": "111",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "120",
		"\"Patrick1.3\"": "102"
	},
	{
		"\"\"": "\"109\"",
		"\"Rank\"": "109",
		"\"Player\"": "\"Jalin Hyatt\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "43",
		"\"AVGRank\"": "111",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "93",
		"\"Patrick1.3\"": "129"
	},
	{
		"\"\"": "\"110\"",
		"\"Rank\"": "110",
		"\"Player\"": "\"Nick Chubb\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "27",
		"\"AVGRank\"": "112.5",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "127",
		"\"Patrick1.3\"": "98"
	},
	{
		"\"\"": "\"111\"",
		"\"Rank\"": "111",
		"\"Player\"": "\"Jerome Ford\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "28",
		"\"AVGRank\"": "112.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "108",
		"\"Patrick1.3\"": "117"
	},
	{
		"\"\"": "\"112\"",
		"\"Rank\"": "112",
		"\"Player\"": "\"Daniel Jones\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "26",
		"\"AVGRank\"": "113",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "72",
		"\"Patrick1.3\"": "154"
	},
	{
		"\"\"": "\"113\"",
		"\"Rank\"": "113",
		"\"Player\"": "\"DeAndre Hopkins\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "44",
		"\"AVGRank\"": "113.5",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "124",
		"\"Patrick1.3\"": "103"
	},
	{
		"\"\"": "\"114\"",
		"\"Rank\"": "114",
		"\"Player\"": "\"Jerry Jeudy\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "45",
		"\"AVGRank\"": "114",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "119",
		"\"Patrick1.3\"": "109"
	},
	{
		"\"\"": "\"115\"",
		"\"Rank\"": "115",
		"\"Player\"": "\"Tyjae Spears\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "29",
		"\"AVGRank\"": "114.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "97",
		"\"Patrick1.3\"": "132"
	},
	{
		"\"\"": "\"116\"",
		"\"Rank\"": "116",
		"\"Player\"": "\"Roschon Johnson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "30",
		"\"AVGRank\"": "114.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "111",
		"\"Patrick1.3\"": "118"
	},
	{
		"\"\"": "\"117\"",
		"\"Rank\"": "117",
		"\"Player\"": "\"Joe Mixon\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "31",
		"\"AVGRank\"": "115",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "130",
		"\"Patrick1.3\"": "100"
	},
	{
		"\"\"": "\"118\"",
		"\"Rank\"": "118",
		"\"Player\"": "\"Jahan Dotson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "46",
		"\"AVGRank\"": "115.5",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "146",
		"\"Patrick1.3\"": "85"
	},
	{
		"\"\"": "\"119\"",
		"\"Rank\"": "119",
		"\"Player\"": "\"Quentin Johnston\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "47",
		"\"AVGRank\"": "115.5",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "100",
		"\"Patrick1.3\"": "131"
	},
	{
		"\"\"": "\"120\"",
		"\"Rank\"": "120",
		"\"Player\"": "\"Tyler Lockett\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "48",
		"\"AVGRank\"": "116.5",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "125",
		"\"Patrick1.3\"": "108"
	},
	{
		"\"\"": "\"121\"",
		"\"Rank\"": "121",
		"\"Player\"": "\"James Conner\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "32",
		"\"AVGRank\"": "117",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "133",
		"\"Patrick1.3\"": "101"
	},
	{
		"\"\"": "\"122\"",
		"\"Rank\"": "122",
		"\"Player\"": "\"Marquise Brown\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "49",
		"\"AVGRank\"": "117.5",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "122",
		"\"Patrick1.3\"": "113"
	},
	{
		"\"\"": "\"123\"",
		"\"Rank\"": "123",
		"\"Player\"": "\"Jake Ferguson\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "16",
		"\"AVGRank\"": "117.5",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "116",
		"\"Patrick1.3\"": "119"
	},
	{
		"\"\"": "\"124\"",
		"\"Rank\"": "124",
		"\"Player\"": "\"Aaron Jones\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "33",
		"\"AVGRank\"": "118.5",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "109",
		"\"Patrick1.3\"": "128"
	},
	{
		"\"\"": "\"125\"",
		"\"Rank\"": "125",
		"\"Player\"": "\"Courtland Sutton\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "50",
		"\"AVGRank\"": "119.5",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "129",
		"\"Patrick1.3\"": "110"
	},
	{
		"\"\"": "\"126\"",
		"\"Rank\"": "126",
		"\"Player\"": "\"Kendre Miller\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "34",
		"\"AVGRank\"": "120",
		"\"AVGTier\"": "6",
		"\"Siegele1.5\"": "96",
		"\"Patrick1.3\"": "144"
	},
	{
		"\"\"": "\"127\"",
		"\"Rank\"": "127",
		"\"Player\"": "\"Aaron Rodgers\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "27",
		"\"AVGRank\"": "121",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "115",
		"\"Patrick1.3\"": "127"
	},
	{
		"\"\"": "\"128\"",
		"\"Rank\"": "128",
		"\"Player\"": "\"Treylon Burks\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "51",
		"\"AVGRank\"": "121.5",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "137",
		"\"Patrick1.3\"": "106"
	},
	{
		"\"\"": "\"129\"",
		"\"Rank\"": "129",
		"\"Player\"": "\"Zach Charbonnet\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "35",
		"\"AVGRank\"": "121.5",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "110",
		"\"Patrick1.3\"": "133"
	},
	{
		"\"\"": "\"130\"",
		"\"Rank\"": "130",
		"\"Player\"": "\"Gabe Davis\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "52",
		"\"AVGRank\"": "124.5",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "142",
		"\"Patrick1.3\"": "107"
	},
	{
		"\"\"": "\"131\"",
		"\"Rank\"": "131",
		"\"Player\"": "\"Romeo Doubs\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "53",
		"\"AVGRank\"": "126",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "141",
		"\"Patrick1.3\"": "111"
	},
	{
		"\"\"": "\"132\"",
		"\"Rank\"": "132",
		"\"Player\"": "\"Russell Wilson\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "28",
		"\"AVGRank\"": "134.5",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "143",
		"\"Patrick1.3\"": "126"
	},
	{
		"\"\"": "\"133\"",
		"\"Rank\"": "133",
		"\"Player\"": "\"Rashid Shaheed\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "54",
		"\"AVGRank\"": "136.5",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "157",
		"\"Patrick1.3\"": "116"
	},
	{
		"\"\"": "\"134\"",
		"\"Rank\"": "134",
		"\"Player\"": "\"Chase Brown\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "36",
		"\"AVGRank\"": "138",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "112",
		"\"Patrick1.3\"": "164"
	},
	{
		"\"\"": "\"135\"",
		"\"Rank\"": "135",
		"\"Player\"": "\"Mike Williams\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "55",
		"\"AVGRank\"": "139.5",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "131",
		"\"Patrick1.3\"": "148"
	},
	{
		"\"\"": "\"136\"",
		"\"Rank\"": "136",
		"\"Player\"": "\"Jakobi Meyers\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "56",
		"\"AVGRank\"": "140.5",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "121",
		"\"Patrick1.3\"": "160"
	},
	{
		"\"\"": "\"137\"",
		"\"Rank\"": "137",
		"\"Player\"": "\"Kenny Pickett\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "29",
		"\"AVGRank\"": "141",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "126",
		"\"Patrick1.3\"": "156"
	},
	{
		"\"\"": "\"138\"",
		"\"Rank\"": "138",
		"\"Player\"": "\"Miles Sanders\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "37",
		"\"AVGRank\"": "141.5",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "145",
		"\"Patrick1.3\"": "138"
	},
	{
		"\"\"": "\"139\"",
		"\"Rank\"": "139",
		"\"Player\"": "\"Antonio Gibson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "38",
		"\"AVGRank\"": "142",
		"\"AVGTier\"": "7",
		"\"Siegele1.5\"": "135",
		"\"Patrick1.3\"": "149"
	},
	{
		"\"\"": "\"140\"",
		"\"Rank\"": "140",
		"\"Player\"": "\"Elijah Moore\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "57",
		"\"AVGRank\"": "142.5",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "180",
		"\"Patrick1.3\"": "105"
	},
	{
		"\"\"": "\"141\"",
		"\"Rank\"": "141",
		"\"Player\"": "\"Khalil Herbert\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "39",
		"\"AVGRank\"": "143",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "140",
		"\"Patrick1.3\"": "146"
	},
	{
		"\"\"": "\"142\"",
		"\"Rank\"": "142",
		"\"Player\"": "\"Dameon Pierce\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "40",
		"\"AVGRank\"": "143.5",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "173",
		"\"Patrick1.3\"": "114"
	},
	{
		"\"\"": "\"143\"",
		"\"Rank\"": "143",
		"\"Player\"": "\"Tyler Allgeier\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "41",
		"\"AVGRank\"": "144",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "152",
		"\"Patrick1.3\"": "136"
	},
	{
		"\"\"": "\"144\"",
		"\"Rank\"": "144",
		"\"Player\"": "\"Isaiah Likely\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "17",
		"\"AVGRank\"": "144",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "147",
		"\"Patrick1.3\"": "141"
	},
	{
		"\"\"": "\"145\"",
		"\"Rank\"": "145",
		"\"Player\"": "\"Dalton Schultz\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "18",
		"\"AVGRank\"": "144.5",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "150",
		"\"Patrick1.3\"": "139"
	},
	{
		"\"\"": "\"146\"",
		"\"Rank\"": "146",
		"\"Player\"": "\"Chuba Hubbard\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "42",
		"\"AVGRank\"": "146.5",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "132",
		"\"Patrick1.3\"": "161"
	},
	{
		"\"\"": "\"147\"",
		"\"Rank\"": "147",
		"\"Player\"": "\"Keaton Mitchell\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "43",
		"\"AVGRank\"": "149",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "136",
		"\"Patrick1.3\"": "162"
	},
	{
		"\"\"": "\"148\"",
		"\"Rank\"": "148",
		"\"Player\"": "\"J.K. Dobbins\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "44",
		"\"AVGRank\"": "151",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "94",
		"\"Patrick1.3\"": "208"
	},
	{
		"\"\"": "\"149\"",
		"\"Rank\"": "149",
		"\"Player\"": "\"Rashod Bateman\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "58",
		"\"AVGRank\"": "151.5",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "163",
		"\"Patrick1.3\"": "140"
	},
	{
		"\"\"": "\"150\"",
		"\"Rank\"": "150",
		"\"Player\"": "\"Zamir White\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "45",
		"\"AVGRank\"": "152.5",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "134",
		"\"Patrick1.3\"": "171"
	},
	{
		"\"\"": "\"151\"",
		"\"Rank\"": "151",
		"\"Player\"": "\"Darren Waller\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "19",
		"\"AVGRank\"": "153.5",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "148",
		"\"Patrick1.3\"": "159"
	},
	{
		"\"\"": "\"152\"",
		"\"Rank\"": "152",
		"\"Player\"": "\"Tucker Kraft\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "20",
		"\"AVGRank\"": "153.5",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "117",
		"\"Patrick1.3\"": "190"
	},
	{
		"\"\"": "\"153\"",
		"\"Rank\"": "153",
		"\"Player\"": "\"Aidan O'Connell\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "30",
		"\"AVGRank\"": "154.5",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "154",
		"\"Patrick1.3\"": "155"
	},
	{
		"\"\"": "\"154\"",
		"\"Rank\"": "154",
		"\"Player\"": "\"Chigoziem Okonkwo\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "21",
		"\"AVGRank\"": "156",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "170",
		"\"Patrick1.3\"": "142"
	},
	{
		"\"\"": "\"155\"",
		"\"Rank\"": "155",
		"\"Player\"": "\"Tank Bigsby\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "46",
		"\"AVGRank\"": "156",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "161",
		"\"Patrick1.3\"": "151"
	},
	{
		"\"\"": "\"156\"",
		"\"Rank\"": "156",
		"\"Player\"": "\"Alexander Mattison\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "47",
		"\"AVGRank\"": "161",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "179",
		"\"Patrick1.3\"": "143"
	},
	{
		"\"\"": "\"157\"",
		"\"Rank\"": "157",
		"\"Player\"": "\"Greg Dulcich\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "22",
		"\"AVGRank\"": "161.5",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "165",
		"\"Patrick1.3\"": "158"
	},
	{
		"\"\"": "\"158\"",
		"\"Rank\"": "158",
		"\"Player\"": "\"Michael Wilson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "59",
		"\"AVGRank\"": "161.5",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "156",
		"\"Patrick1.3\"": "167"
	},
	{
		"\"\"": "\"159\"",
		"\"Rank\"": "159",
		"\"Player\"": "\"Rondale Moore\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "60",
		"\"AVGRank\"": "162",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "159",
		"\"Patrick1.3\"": "165"
	},
	{
		"\"\"": "\"160\"",
		"\"Rank\"": "160",
		"\"Player\"": "\"Gardner Minshew\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "31",
		"\"AVGRank\"": "162.5",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "155",
		"\"Patrick1.3\"": "170"
	},
	{
		"\"\"": "\"161\"",
		"\"Rank\"": "161",
		"\"Player\"": "\"Mac Jones\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "32",
		"\"AVGRank\"": "164.5",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "149",
		"\"Patrick1.3\"": "180"
	},
	{
		"\"\"": "\"162\"",
		"\"Rank\"": "162",
		"\"Player\"": "\"Adam Thielen\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "61",
		"\"AVGRank\"": "167",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "204",
		"\"Patrick1.3\"": "130"
	},
	{
		"\"\"": "\"163\"",
		"\"Rank\"": "163",
		"\"Player\"": "\"AJ Dillon\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "48",
		"\"AVGRank\"": "167.5",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "190",
		"\"Patrick1.3\"": "145"
	},
	{
		"\"\"": "\"164\"",
		"\"Rank\"": "164",
		"\"Player\"": "\"Tyler Higbee\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "23",
		"\"AVGRank\"": "167.5",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "182",
		"\"Patrick1.3\"": "153"
	},
	{
		"\"\"": "\"165\"",
		"\"Rank\"": "165",
		"\"Player\"": "\"Jimmy Garoppolo\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "33",
		"\"AVGRank\"": "168",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "158",
		"\"Patrick1.3\"": "178"
	},
	{
		"\"\"": "\"166\"",
		"\"Rank\"": "166",
		"\"Player\"": "\"Jonathan Mingo\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "62",
		"\"AVGRank\"": "168",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "189",
		"\"Patrick1.3\"": "147"
	},
	{
		"\"\"": "\"167\"",
		"\"Rank\"": "167",
		"\"Player\"": "\"Darnell Mooney\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "63",
		"\"AVGRank\"": "168.5",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "168",
		"\"Patrick1.3\"": "169"
	},
	{
		"\"\"": "\"168\"",
		"\"Rank\"": "168",
		"\"Player\"": "\"Elijah Mitchell\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "49",
		"\"AVGRank\"": "169.5",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "176",
		"\"Patrick1.3\"": "163"
	},
	{
		"\"\"": "\"169\"",
		"\"Rank\"": "169",
		"\"Player\"": "\"Brandin Cooks\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "64",
		"\"AVGRank\"": "171",
		"\"AVGTier\"": "8",
		"\"Siegele1.5\"": "192",
		"\"Patrick1.3\"": "150"
	},
	{
		"\"\"": "\"170\"",
		"\"Rank\"": "170",
		"\"Player\"": "\"Ryan Tannehill\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"TEN\"",
		"\"PosRank\"": "34",
		"\"AVGRank\"": "171.5",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "162",
		"\"Patrick1.3\"": "181"
	},
	{
		"\"\"": "\"171\"",
		"\"Rank\"": "171",
		"\"Player\"": "\"Ty Chandler\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "50",
		"\"AVGRank\"": "173",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "144",
		"\"Patrick1.3\"": "202"
	},
	{
		"\"\"": "\"172\"",
		"\"Rank\"": "172",
		"\"Player\"": "\"Juwan Johnson\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "24",
		"\"AVGRank\"": "173.5",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "210",
		"\"Patrick1.3\"": "137"
	},
	{
		"\"\"": "\"173\"",
		"\"Rank\"": "173",
		"\"Player\"": "\"Israel Abanikanda\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "51",
		"\"AVGRank\"": "173.5",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "153",
		"\"Patrick1.3\"": "194"
	},
	{
		"\"\"": "\"174\"",
		"\"Rank\"": "174",
		"\"Player\"": "\"Noah Fant\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"SEA\"",
		"\"PosRank\"": "25",
		"\"AVGRank\"": "174",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "151",
		"\"Patrick1.3\"": "197"
	},
	{
		"\"\"": "\"175\"",
		"\"Rank\"": "175",
		"\"Player\"": "\"Zay Jones\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "65",
		"\"AVGRank\"": "177",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "186",
		"\"Patrick1.3\"": "168"
	},
	{
		"\"\"": "\"176\"",
		"\"Rank\"": "176",
		"\"Player\"": "\"Luke Schoonmaker\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "26",
		"\"AVGRank\"": "175",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "193",
		"\"Patrick1.3\"": "157"
	},
	{
		"\"\"": "\"177\"",
		"\"Rank\"": "177",
		"\"Player\"": "\"Michael Thomas\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "66",
		"\"AVGRank\"": "179",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "167",
		"\"Patrick1.3\"": "191"
	},
	{
		"\"\"": "\"178\"",
		"\"Rank\"": "178",
		"\"Player\"": "\"Trey Palmer\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "67",
		"\"AVGRank\"": "179",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "172",
		"\"Patrick1.3\"": "186"
	},
	{
		"\"\"": "\"179\"",
		"\"Rank\"": "179",
		"\"Player\"": "\"Hendon Hooker\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "35",
		"\"AVGRank\"": "182.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "183",
		"\"Patrick1.3\"": "182"
	},
	{
		"\"\"": "\"180\"",
		"\"Rank\"": "180",
		"\"Player\"": "\"Dontayvion Wicks\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "68",
		"\"AVGRank\"": "183.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "178",
		"\"Patrick1.3\"": "189"
	},
	{
		"\"\"": "\"181\"",
		"\"Rank\"": "181",
		"\"Player\"": "\"Justice Hill\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "52",
		"\"AVGRank\"": "184.5",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "197",
		"\"Patrick1.3\"": "172"
	},
	{
		"\"\"": "\"182\"",
		"\"Rank\"": "182",
		"\"Player\"": "\"Devin Singletary\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "53",
		"\"AVGRank\"": "185",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "169",
		"\"Patrick1.3\"": "201"
	},
	{
		"\"\"": "\"183\"",
		"\"Rank\"": "183",
		"\"Player\"": "\"Tyler Boyd\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "69",
		"\"AVGRank\"": "186",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "188",
		"\"Patrick1.3\"": "184"
	},
	{
		"\"\"": "\"184\"",
		"\"Rank\"": "184",
		"\"Player\"": "\"Dalvin Cook\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "54",
		"\"AVGRank\"": "187.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "164",
		"\"Patrick1.3\"": "211"
	},
	{
		"\"\"": "\"185\"",
		"\"Rank\"": "185",
		"\"Player\"": "\"Kylen Granson\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "27",
		"\"AVGRank\"": "191",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "230",
		"\"Patrick1.3\"": "152"
	},
	{
		"\"\"": "\"186\"",
		"\"Rank\"": "186",
		"\"Player\"": "\"Zach Evans\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "55",
		"\"AVGRank\"": "191.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "171",
		"\"Patrick1.3\"": "212"
	},
	{
		"\"\"": "\"187\"",
		"\"Rank\"": "187",
		"\"Player\"": "\"Hunter Henry\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "28",
		"\"AVGRank\"": "191.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "187",
		"\"Patrick1.3\"": "196"
	},
	{
		"\"\"": "\"188\"",
		"\"Rank\"": "188",
		"\"Player\"": "\"Curtis Samuel\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "70",
		"\"AVGRank\"": "196",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "166",
		"\"Patrick1.3\"": "226"
	},
	{
		"\"\"": "\"189\"",
		"\"Rank\"": "189",
		"\"Player\"": "\"Desmond Ridder\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "36",
		"\"AVGRank\"": "198",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "217",
		"\"Patrick1.3\"": "179"
	},
	{
		"\"\"": "\"190\"",
		"\"Rank\"": "190",
		"\"Player\"": "\"Darnell Washington\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "29",
		"\"AVGRank\"": "198.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "198",
		"\"Patrick1.3\"": "199"
	},
	{
		"\"\"": "\"191\"",
		"\"Rank\"": "191",
		"\"Player\"": "\"DJ Chark\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "71",
		"\"AVGRank\"": "202",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "221",
		"\"Patrick1.3\"": "183"
	},
	{
		"\"\"": "\"192\"",
		"\"Rank\"": "192",
		"\"Player\"": "\"Sean Tucker\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "56",
		"\"AVGRank\"": "203.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "174",
		"\"Patrick1.3\"": "233"
	},
	{
		"\"\"": "\"193\"",
		"\"Rank\"": "193",
		"\"Player\"": "\"Justyn Ross\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "72",
		"\"AVGRank\"": "205.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "196",
		"\"Patrick1.3\"": "215"
	},
	{
		"\"\"": "\"194\"",
		"\"Rank\"": "194",
		"\"Player\"": "\"Alec Pierce\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "73",
		"\"AVGRank\"": "206",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "246",
		"\"Patrick1.3\"": "166"
	},
	{
		"\"\"": "\"195\"",
		"\"Rank\"": "195",
		"\"Player\"": "\"Pierre Strong\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "57",
		"\"AVGRank\"": "206.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "207",
		"\"Patrick1.3\"": "206"
	},
	{
		"\"\"": "\"196\"",
		"\"Rank\"": "196",
		"\"Player\"": "\"Andrei Iosivas\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "74",
		"\"AVGRank\"": "206.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "160",
		"\"Patrick1.3\"": "253"
	},
	{
		"\"\"": "\"197\"",
		"\"Rank\"": "197",
		"\"Player\"": "\"Kenneth Gainwell\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "58",
		"\"AVGRank\"": "207.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "241",
		"\"Patrick1.3\"": "174"
	},
	{
		"\"\"": "\"198\"",
		"\"Rank\"": "198",
		"\"Player\"": "\"Jerick McKinnon\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "59",
		"\"AVGRank\"": "208",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "243",
		"\"Patrick1.3\"": "173"
	},
	{
		"\"\"": "\"199\"",
		"\"Rank\"": "199",
		"\"Player\"": "\"Trey Lance\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "37",
		"\"AVGRank\"": "209.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "199",
		"\"Patrick1.3\"": "220"
	},
	{
		"\"\"": "\"200\"",
		"\"Rank\"": "200",
		"\"Player\"": "\"Samaje Perine\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "60",
		"\"AVGRank\"": "212",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "214",
		"\"Patrick1.3\"": "210"
	},
	{
		"\"\"": "\"201\"",
		"\"Rank\"": "201",
		"\"Player\"": "\"Taysom Hill\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"\"",
		"\"PosRank\"": "30",
		"\"AVGRank\"": "212.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "184",
		"\"Patrick1.3\"": "241"
	},
	{
		"\"\"": "\"202\"",
		"\"Rank\"": "202",
		"\"Player\"": "\"Joe Flacco\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "38",
		"\"AVGRank\"": "212.5",
		"\"AVGTier\"": "9",
		"\"Siegele1.5\"": "301",
		"\"Patrick1.3\"": "124"
	},
	{
		"\"\"": "\"203\"",
		"\"Rank\"": "203",
		"\"Player\"": "\"K.J. Osborn\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "75",
		"\"AVGRank\"": "214.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "201",
		"\"Patrick1.3\"": "228"
	},
	{
		"\"\"": "\"204\"",
		"\"Rank\"": "204",
		"\"Player\"": "\"Skyy Moore\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "76",
		"\"AVGRank\"": "215.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "239",
		"\"Patrick1.3\"": "192"
	},
	{
		"\"\"": "\"205\"",
		"\"Rank\"": "205",
		"\"Player\"": "\"Jamaal Williams\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "61",
		"\"AVGRank\"": "216",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "223",
		"\"Patrick1.3\"": "209"
	},
	{
		"\"\"": "\"206\"",
		"\"Rank\"": "206",
		"\"Player\"": "\"D'Onta Foreman\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "62",
		"\"AVGRank\"": "216",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "227",
		"\"Patrick1.3\"": "205"
	},
	{
		"\"\"": "\"207\"",
		"\"Rank\"": "207",
		"\"Player\"": "\"Bailey Zappe\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "39",
		"\"AVGRank\"": "216",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "215",
		"\"Patrick1.3\"": "217"
	},
	{
		"\"\"": "\"208\"",
		"\"Rank\"": "208",
		"\"Player\"": "\"Evan Hull\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "63",
		"\"AVGRank\"": "216.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "229",
		"\"Patrick1.3\"": "204"
	},
	{
		"\"\"": "\"209\"",
		"\"Rank\"": "209",
		"\"Player\"": "\"Kadarius Toney\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "77",
		"\"AVGRank\"": "217",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "220",
		"\"Patrick1.3\"": "214"
	},
	{
		"\"\"": "\"210\"",
		"\"Rank\"": "210",
		"\"Player\"": "\"Cam Akers\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "64",
		"\"AVGRank\"": "218",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "238",
		"\"Patrick1.3\"": "198"
	},
	{
		"\"\"": "\"211\"",
		"\"Rank\"": "211",
		"\"Player\"": "\"Khalil Shakir\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "78",
		"\"AVGRank\"": "218",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "185",
		"\"Patrick1.3\"": "251"
	},
	{
		"\"\"": "\"212\"",
		"\"Rank\"": "212",
		"\"Player\"": "\"Isaiah Hodgins\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "79",
		"\"AVGRank\"": "219",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "251",
		"\"Patrick1.3\"": "187"
	},
	{
		"\"\"": "\"213\"",
		"\"Rank\"": "213",
		"\"Player\"": "\"Cedric Tillman\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "80",
		"\"AVGRank\"": "220",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "216",
		"\"Patrick1.3\"": "224"
	},
	{
		"\"\"": "\"214\"",
		"\"Rank\"": "214",
		"\"Player\"": "\"Taylor Heinicke\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "40",
		"\"AVGRank\"": "220",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "222",
		"\"Patrick1.3\"": "218"
	},
	{
		"\"\"": "\"215\"",
		"\"Rank\"": "215",
		"\"Player\"": "\"Jaleel McLaughlin\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "65",
		"\"AVGRank\"": "220",
		"\"AVGTier\"": "NA",
		"\"Siegele1.5\"": "139",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"216\"",
		"\"Rank\"": "216",
		"\"Player\"": "\"Gerald Everett\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "31",
		"\"AVGRank\"": "221",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "249",
		"\"Patrick1.3\"": "193"
	},
	{
		"\"\"": "\"217\"",
		"\"Rank\"": "217",
		"\"Player\"": "\"Kareem Hunt\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "66",
		"\"AVGRank\"": "221.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "206",
		"\"Patrick1.3\"": "237"
	},
	{
		"\"\"": "\"218\"",
		"\"Rank\"": "218",
		"\"Player\"": "\"Rashaad Penny\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "67",
		"\"AVGRank\"": "221.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "209",
		"\"Patrick1.3\"": "234"
	},
	{
		"\"\"": "\"219\"",
		"\"Rank\"": "219",
		"\"Player\"": "\"Odell Beckham\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "81",
		"\"AVGRank\"": "222",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "259",
		"\"Patrick1.3\"": "185"
	},
	{
		"\"\"": "\"220\"",
		"\"Rank\"": "220",
		"\"Player\"": "\"Jelani Woods\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "32",
		"\"AVGRank\"": "223",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "233",
		"\"Patrick1.3\"": "213"
	},
	{
		"\"\"": "\"221\"",
		"\"Rank\"": "221",
		"\"Player\"": "\"Jeff Wilson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "68",
		"\"AVGRank\"": "223.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "218",
		"\"Patrick1.3\"": "229"
	},
	{
		"\"\"": "\"222\"",
		"\"Rank\"": "222",
		"\"Player\"": "\"Chris Rodriguez",
		"\"POS\"": " Jr.\"",
		"\"Team\"": "\"RB\"",
		"\"PosRank\"": "\"\"",
		"\"AVGRank\"": "69",
		"\"AVGTier\"": "224",
		"\"Siegele1.5\"": "10",
		"\"Patrick1.3\"": "177"
	},
	{
		"\"\"": "\"223\"",
		"\"Rank\"": "223",
		"\"Player\"": "\"Joshua Palmer\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "82",
		"\"AVGRank\"": "225.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "203",
		"\"Patrick1.3\"": "248"
	},
	{
		"\"\"": "\"224\"",
		"\"Rank\"": "224",
		"\"Player\"": "\"Ezekiel Elliott\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "70",
		"\"AVGRank\"": "226",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "245",
		"\"Patrick1.3\"": "207"
	},
	{
		"\"\"": "\"225\"",
		"\"Rank\"": "225",
		"\"Player\"": "\"Tutu Atwell\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "83",
		"\"AVGRank\"": "227",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "219",
		"\"Patrick1.3\"": "235"
	},
	{
		"\"\"": "\"226\"",
		"\"Rank\"": "226",
		"\"Player\"": "\"Damien Harris\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "71",
		"\"AVGRank\"": "230",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "257",
		"\"Patrick1.3\"": "203"
	},
	{
		"\"\"": "\"227\"",
		"\"Rank\"": "227",
		"\"Player\"": "\"Irv Smith\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "33",
		"\"AVGRank\"": "230.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "261",
		"\"Patrick1.3\"": "200"
	},
	{
		"\"\"": "\"228\"",
		"\"Rank\"": "228",
		"\"Player\"": "\"Deuce Vaughn\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "72",
		"\"AVGRank\"": "231.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "240",
		"\"Patrick1.3\"": "223"
	},
	{
		"\"\"": "\"229\"",
		"\"Rank\"": "229",
		"\"Player\"": "\"Richie James\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "84",
		"\"AVGRank\"": "234",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "225",
		"\"Patrick1.3\"": "243"
	},
	{
		"\"\"": "\"230\"",
		"\"Rank\"": "230",
		"\"Player\"": "\"Parker Washington\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"JAC\"",
		"\"PosRank\"": "85",
		"\"AVGRank\"": "235",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "194",
		"\"Patrick1.3\"": "276"
	},
	{
		"\"\"": "\"231\"",
		"\"Rank\"": "231",
		"\"Player\"": "\"Hunter Renfrow\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "86",
		"\"AVGRank\"": "237.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "244",
		"\"Patrick1.3\"": "231"
	},
	{
		"\"\"": "\"232\"",
		"\"Rank\"": "232",
		"\"Player\"": "\"Sam Darnold\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "41",
		"\"AVGRank\"": "237.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "212",
		"\"Patrick1.3\"": "263"
	},
	{
		"\"\"": "\"233\"",
		"\"Rank\"": "233",
		"\"Player\"": "\"Zack Moss\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "73",
		"\"AVGRank\"": "238",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "175",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"234\"",
		"\"Rank\"": "234",
		"\"Player\"": "\"Jacoby Brissett\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "42",
		"\"AVGRank\"": "238",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "301",
		"\"Patrick1.3\"": "175"
	},
	{
		"\"\"": "\"235\"",
		"\"Rank\"": "235",
		"\"Player\"": "\"Mason Rudolph\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"PIT\"",
		"\"PosRank\"": "43",
		"\"AVGRank\"": "238.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "301",
		"\"Patrick1.3\"": "176"
	},
	{
		"\"\"": "\"236\"",
		"\"Rank\"": "236",
		"\"Player\"": "\"A.T. Perry\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "87",
		"\"AVGRank\"": "239",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "234",
		"\"Patrick1.3\"": "244"
	},
	{
		"\"\"": "\"237\"",
		"\"Rank\"": "237",
		"\"Player\"": "\"Tyrod Taylor\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "44",
		"\"AVGRank\"": "239",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "301",
		"\"Patrick1.3\"": "177"
	},
	{
		"\"\"": "\"238\"",
		"\"Rank\"": "238",
		"\"Player\"": "\"JuJu Smith-Schuster\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "88",
		"\"AVGRank\"": "239.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "284",
		"\"Patrick1.3\"": "195"
	},
	{
		"\"\"": "\"239\"",
		"\"Rank\"": "239",
		"\"Player\"": "\"Gus Edwards\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "74",
		"\"AVGRank\"": "241",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "181",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"240\"",
		"\"Rank\"": "240",
		"\"Player\"": "\"Xavier Hutchinson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "89",
		"\"AVGRank\"": "240.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "213",
		"\"Patrick1.3\"": "268"
	},
	{
		"\"\"": "\"241\"",
		"\"Rank\"": "241",
		"\"Player\"": "\"John Metchie\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "90",
		"\"AVGRank\"": "242.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "258",
		"\"Patrick1.3\"": "227"
	},
	{
		"\"\"": "\"242\"",
		"\"Rank\"": "242",
		"\"Player\"": "\"Allen Lazard\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "91",
		"\"AVGRank\"": "244",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "272",
		"\"Patrick1.3\"": "216"
	},
	{
		"\"\"": "\"243\"",
		"\"Rank\"": "243",
		"\"Player\"": "\"Tommy Tremble\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "34",
		"\"AVGRank\"": "244.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "301",
		"\"Patrick1.3\"": "188"
	},
	{
		"\"\"": "\"244\"",
		"\"Rank\"": "244",
		"\"Player\"": "\"Albert Okwuegbunam\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"PHI\"",
		"\"PosRank\"": "35",
		"\"AVGRank\"": "245",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "252",
		"\"Patrick1.3\"": "238"
	},
	{
		"\"\"": "\"245\"",
		"\"Rank\"": "245",
		"\"Player\"": "\"Michael Gallup\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "92",
		"\"AVGRank\"": "246",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "256",
		"\"Patrick1.3\"": "236"
	},
	{
		"\"\"": "\"246\"",
		"\"Rank\"": "246",
		"\"Player\"": "\"Rico Dowdle\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DAL\"",
		"\"PosRank\"": "75",
		"\"AVGRank\"": "246",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "191",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"247\"",
		"\"Rank\"": "247",
		"\"Player\"": "\"Mike Gesicki\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "36",
		"\"AVGRank\"": "246.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "271",
		"\"Patrick1.3\"": "222"
	},
	{
		"\"\"": "\"248\"",
		"\"Rank\"": "248",
		"\"Player\"": "\"Cade Otton\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"TB\"",
		"\"PosRank\"": "37",
		"\"AVGRank\"": "247",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "211",
		"\"Patrick1.3\"": "283"
	},
	{
		"\"\"": "\"249\"",
		"\"Rank\"": "249",
		"\"Player\"": "\"Chase Claypool\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"MIA\"",
		"\"PosRank\"": "93",
		"\"AVGRank\"": "247.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "270",
		"\"Patrick1.3\"": "225"
	},
	{
		"\"\"": "\"250\"",
		"\"Rank\"": "250",
		"\"Player\"": "\"Tyquan Thornton\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "94",
		"\"AVGRank\"": "247.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "250",
		"\"Patrick1.3\"": "245"
	},
	{
		"\"\"": "\"251\"",
		"\"Rank\"": "251",
		"\"Player\"": "\"Bo Melton\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"GB\"",
		"\"PosRank\"": "95",
		"\"AVGRank\"": "248",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "195",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"252\"",
		"\"Rank\"": "252",
		"\"Player\"": "\"Terrace Marshall\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "96",
		"\"AVGRank\"": "249.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "280",
		"\"Patrick1.3\"": "219"
	},
	{
		"\"\"": "\"253\"",
		"\"Rank\"": "253",
		"\"Player\"": "\"Kayshon Boutte\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "97",
		"\"AVGRank\"": "250",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "279",
		"\"Patrick1.3\"": "221"
	},
	{
		"\"\"": "\"254\"",
		"\"Rank\"": "254",
		"\"Player\"": "\"Dawson Knox\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "38",
		"\"AVGRank\"": "250.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "262",
		"\"Patrick1.3\"": "239"
	},
	{
		"\"\"": "\"255\"",
		"\"Rank\"": "255",
		"\"Player\"": "\"Demarcus Robinson\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LAR\"",
		"\"PosRank\"": "98",
		"\"AVGRank\"": "250.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "200",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"256\"",
		"\"Rank\"": "256",
		"\"Player\"": "\"Demario Douglas\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "99",
		"\"AVGRank\"": "251.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "202",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"257\"",
		"\"Rank\"": "257",
		"\"Player\"": "\"Tyler Conklin\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "39",
		"\"AVGRank\"": "253",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "205",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"258\"",
		"\"Rank\"": "258",
		"\"Player\"": "\"Jordan Mason\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"SF\"",
		"\"PosRank\"": "76",
		"\"AVGRank\"": "253",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "226",
		"\"Patrick1.3\"": "280"
	},
	{
		"\"\"": "\"259\"",
		"\"Rank\"": "259",
		"\"Player\"": "\"Zach Wilson\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "45",
		"\"AVGRank\"": "254.5",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "208",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"260\"",
		"\"Rank\"": "260",
		"\"Player\"": "\"DeWayne McBride\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"MIN\"",
		"\"PosRank\"": "77",
		"\"AVGRank\"": "256",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "265",
		"\"Patrick1.3\"": "247"
	},
	{
		"\"\"": "\"261\"",
		"\"Rank\"": "261",
		"\"Player\"": "\"Hayden Hurst\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "40",
		"\"AVGRank\"": "257",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "282",
		"\"Patrick1.3\"": "232"
	},
	{
		"\"\"": "\"262\"",
		"\"Rank\"": "262",
		"\"Player\"": "\"Kevin Harris\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "78",
		"\"AVGRank\"": "257.5",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "224",
		"\"Patrick1.3\"": "291"
	},
	{
		"\"\"": "\"263\"",
		"\"Rank\"": "263",
		"\"Player\"": "\"Parris Campbell\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "100",
		"\"AVGRank\"": "258.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "287",
		"\"Patrick1.3\"": "230"
	},
	{
		"\"\"": "\"264\"",
		"\"Rank\"": "264",
		"\"Player\"": "\"Clyde Edwards-Helaire\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "79",
		"\"AVGRank\"": "259",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "263",
		"\"Patrick1.3\"": "255"
	},
	{
		"\"\"": "\"265\"",
		"\"Rank\"": "265",
		"\"Player\"": "\"Jake Haener\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "46",
		"\"AVGRank\"": "260.5",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "247",
		"\"Patrick1.3\"": "274"
	},
	{
		"\"\"": "\"266\"",
		"\"Rank\"": "266",
		"\"Player\"": "\"Daniel Bellinger\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "41",
		"\"AVGRank\"": "262.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "276",
		"\"Patrick1.3\"": "249"
	},
	{
		"\"\"": "\"267\"",
		"\"Rank\"": "267",
		"\"Player\"": "\"Eric Gray\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"NYG\"",
		"\"PosRank\"": "80",
		"\"AVGRank\"": "262.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "285",
		"\"Patrick1.3\"": "240"
	},
	{
		"\"\"": "\"268\"",
		"\"Rank\"": "268",
		"\"Player\"": "\"DeVante Parker\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "101",
		"\"AVGRank\"": "264",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "286",
		"\"Patrick1.3\"": "242"
	},
	{
		"\"\"": "\"269\"",
		"\"Rank\"": "269",
		"\"Player\"": "\"Tyler Goodson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "81",
		"\"AVGRank\"": "264.5",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "228",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"270\"",
		"\"Rank\"": "270",
		"\"Player\"": "\"Tim Patrick\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "102",
		"\"AVGRank\"": "265",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "231",
		"\"Patrick1.3\"": "299"
	},
	{
		"\"\"": "\"271\"",
		"\"Rank\"": "271",
		"\"Player\"": "\"Greg Dortch\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "103",
		"\"AVGRank\"": "266",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "232",
		"\"Patrick1.3\"": "300"
	},
	{
		"\"\"": "\"272\"",
		"\"Rank\"": "272",
		"\"Player\"": "\"Donovan Peoples-Jones\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "104",
		"\"AVGRank\"": "267",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "288",
		"\"Patrick1.3\"": "246"
	},
	{
		"\"\"": "\"273\"",
		"\"Rank\"": "273",
		"\"Player\"": "\"Kendrick Bourne\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"NE\"",
		"\"PosRank\"": "105",
		"\"AVGRank\"": "268",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "235",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"274\"",
		"\"Rank\"": "274",
		"\"Player\"": "\"Mecole Hardman\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "106",
		"\"AVGRank\"": "268.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "277",
		"\"Patrick1.3\"": "260"
	},
	{
		"\"\"": "\"275\"",
		"\"Rank\"": "275",
		"\"Player\"": "\"Logan Thomas\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "42",
		"\"AVGRank\"": "268.5",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "236",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"276\"",
		"\"Rank\"": "276",
		"\"Player\"": "\"Tyler Huntley\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"BAL\"",
		"\"PosRank\"": "47",
		"\"AVGRank\"": "269",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "237",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"277\"",
		"\"Rank\"": "277",
		"\"Player\"": "\"Charlie Jones\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CIN\"",
		"\"PosRank\"": "107",
		"\"AVGRank\"": "269",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "281",
		"\"Patrick1.3\"": "257"
	},
	{
		"\"\"": "\"278\"",
		"\"Rank\"": "278",
		"\"Player\"": "\"Laviska Shenault\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CAR\"",
		"\"PosRank\"": "108",
		"\"AVGRank\"": "269.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "289",
		"\"Patrick1.3\"": "250"
	},
	{
		"\"\"": "\"279\"",
		"\"Rank\"": "279",
		"\"Player\"": "\"Leonard Fournette\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "82",
		"\"AVGRank\"": "271",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "290",
		"\"Patrick1.3\"": "252"
	},
	{
		"\"\"": "\"280\"",
		"\"Rank\"": "280",
		"\"Player\"": "\"Jameis Winston\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"NO\"",
		"\"PosRank\"": "48",
		"\"AVGRank\"": "271",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "248",
		"\"Patrick1.3\"": "294"
	},
	{
		"\"\"": "\"281\"",
		"\"Rank\"": "281",
		"\"Player\"": "\"Joshua Kelley\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "83",
		"\"AVGRank\"": "271.5",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "242",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"282\"",
		"\"Rank\"": "282",
		"\"Player\"": "\"Isaiah Spiller\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"LAC\"",
		"\"PosRank\"": "84",
		"\"AVGRank\"": "271.5",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "273",
		"\"Patrick1.3\"": "270"
	},
	{
		"\"\"": "\"283\"",
		"\"Rank\"": "283",
		"\"Player\"": "\"Latavius Murray\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"BUF\"",
		"\"PosRank\"": "85",
		"\"AVGRank\"": "273",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "274",
		"\"Patrick1.3\"": "272"
	},
	{
		"\"\"": "\"284\"",
		"\"Rank\"": "284",
		"\"Player\"": "\"Tyler Scott\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CHI\"",
		"\"PosRank\"": "109",
		"\"AVGRank\"": "272.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "291",
		"\"Patrick1.3\"": "254"
	},
	{
		"\"\"": "\"285\"",
		"\"Rank\"": "285",
		"\"Player\"": "\"Tre Tucker\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"LV\"",
		"\"PosRank\"": "110",
		"\"AVGRank\"": "274",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "275",
		"\"Patrick1.3\"": "273"
	},
	{
		"\"\"": "\"286\"",
		"\"Rank\"": "286",
		"\"Player\"": "\"KJ Hamler\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"IND\"",
		"\"PosRank\"": "111",
		"\"AVGRank\"": "274",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "292",
		"\"Patrick1.3\"": "256"
	},
	{
		"\"\"": "\"287\"",
		"\"Rank\"": "287",
		"\"Player\"": "\"Darrell Henderson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"FA\"",
		"\"PosRank\"": "86",
		"\"AVGRank\"": "274",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "269",
		"\"Patrick1.3\"": "279"
	},
	{
		"\"\"": "\"288\"",
		"\"Rank\"": "288",
		"\"Player\"": "\"Zack Kuntz\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"NYJ\"",
		"\"PosRank\"": "43",
		"\"AVGRank\"": "275.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "293",
		"\"Patrick1.3\"": "258"
	},
	{
		"\"\"": "\"289\"",
		"\"Rank\"": "289",
		"\"Player\"": "\"Zach Ertz\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"FA\"",
		"\"PosRank\"": "44",
		"\"AVGRank\"": "276.5",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "268",
		"\"Patrick1.3\"": "285"
	},
	{
		"\"\"": "\"290\"",
		"\"Rank\"": "290",
		"\"Player\"": "\"Deneric Prince\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"KC\"",
		"\"PosRank\"": "87",
		"\"AVGRank\"": "276.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "294",
		"\"Patrick1.3\"": "259"
	},
	{
		"\"\"": "\"291\"",
		"\"Rank\"": "291",
		"\"Player\"": "\"Dorian Thompson-Robinson\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "49",
		"\"AVGRank\"": "277",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "253",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"292\"",
		"\"Rank\"": "292",
		"\"Player\"": "\"Clayton Tune\"",
		"\"POS\"": "\"QB\"",
		"\"Team\"": "\"ARI\"",
		"\"PosRank\"": "50",
		"\"AVGRank\"": "277.5",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "254",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"293\"",
		"\"Rank\"": "293",
		"\"Player\"": "\"Lil'Jordan Humphrey\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"DEN\"",
		"\"PosRank\"": "112",
		"\"AVGRank\"": "278",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "255",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"294\"",
		"\"Rank\"": "294",
		"\"Player\"": "\"Robert Woods\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"HOU\"",
		"\"PosRank\"": "113",
		"\"AVGRank\"": "278.5",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "295",
		"\"Patrick1.3\"": "262"
	},
	{
		"\"\"": "\"295\"",
		"\"Rank\"": "295",
		"\"Player\"": "\"Cordarrelle Patterson\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "88",
		"\"AVGRank\"": "280",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "296",
		"\"Patrick1.3\"": "264"
	},
	{
		"\"\"": "\"296\"",
		"\"Rank\"": "296",
		"\"Player\"": "\"Zonovan Knight\"",
		"\"POS\"": "\"RB\"",
		"\"Team\"": "\"DET\"",
		"\"PosRank\"": "89",
		"\"AVGRank\"": "281",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "297",
		"\"Patrick1.3\"": "265"
	},
	{
		"\"\"": "\"297\"",
		"\"Rank\"": "297",
		"\"Player\"": "\"Corey Davis\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"FA\"",
		"\"PosRank\"": "114",
		"\"AVGRank\"": "281",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "301",
		"\"Patrick1.3\"": "261"
	},
	{
		"\"\"": "\"298\"",
		"\"Rank\"": "298",
		"\"Player\"": "\"Jonnu Smith\"",
		"\"POS\"": "\"TE\"",
		"\"Team\"": "\"ATL\"",
		"\"PosRank\"": "45",
		"\"AVGRank\"": "280.5",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "260",
		"\"Patrick1.3\"": "301"
	},
	{
		"\"\"": "\"299\"",
		"\"Rank\"": "299",
		"\"Player\"": "\"David Bell\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"CLE\"",
		"\"PosRank\"": "115",
		"\"AVGRank\"": "282",
		"\"AVGTier\"": "10",
		"\"Siegele1.5\"": "298",
		"\"Patrick1.3\"": "266"
	},
	{
		"\"\"": "\"300\"",
		"\"Rank\"": "300",
		"\"Player\"": "\"Dyami Brown\"",
		"\"POS\"": "\"WR\"",
		"\"Team\"": "\"WAS\"",
		"\"PosRank\"": "116",
		"\"AVGRank\"": "282.5",
		"\"AVGTier\"": "11",
		"\"Siegele1.5\"": "264",
		"\"Patrick1.3\"": "301"
	},
	
]

module.exports = rvDynastyRankingsTEP;