const rvRedraftRankingsTEP = [
  {
    '""': '"1"',
    '"Rank"': '1',
    '"Player"': '"Justin Jefferson"',
    '"POS"': '"WR"',
    '"Team"': '"MIN"',
    '"PosRank"': '1',
    '"AVGRank"': '1',
    '"AVGTier"': '1',
    '"Siegele7.11"': '1',
    '"Curtis7.9"': '1',
  },
  {
    '""': '"2"',
    '"Rank"': '2',
    '"Player"': '"Christian McCaffrey"',
    '"POS"': '"RB"',
    '"Team"': '"SF"',
    '"PosRank"': '1',
    '"AVGRank"': '3',
    '"AVGTier"': '1',
    '"Siegele7.11"': '3',
    '"Curtis7.9"': '3',
  },
  {
    '""': '"3"',
    '"Rank"': '3',
    '"Player"': '"Ja\'Marr Chase"',
    '"POS"': '"WR"',
    '"Team"': '"CIN"',
    '"PosRank"': '2',
    '"AVGRank"': '3',
    '"AVGTier"': '1',
    '"Siegele7.11"': '4',
    '"Curtis7.9"': '2',
  },
  {
    '""': '"4"',
    '"Rank"': '4',
    '"Player"': '"Travis Kelce"',
    '"POS"': '"TE"',
    '"Team"': '"KC"',
    '"PosRank"': '1',
    '"AVGRank"': '3',
    '"AVGTier"': '1',
    '"Siegele7.11"': '2',
    '"Curtis7.9"': '4',
  },
  {
    '""': '"5"',
    '"Rank"': '5',
    '"Player"': '"Cooper Kupp"',
    '"POS"': '"WR"',
    '"Team"': '"LAR"',
    '"PosRank"': '3',
    '"AVGRank"': '5',
    '"AVGTier"': '1',
    '"Siegele7.11"': '5',
    '"Curtis7.9"': '5',
  },
  {
    '""': '"6"',
    '"Rank"': '6',
    '"Player"': '"Austin Ekeler"',
    '"POS"': '"RB"',
    '"Team"': '"LAC"',
    '"PosRank"': '2',
    '"AVGRank"': '6.5',
    '"AVGTier"': '1',
    '"Siegele7.11"': '6',
    '"Curtis7.9"': '7',
  },
  {
    '""': '"7"',
    '"Rank"': '7',
    '"Player"': '"Tyreek Hill"',
    '"POS"': '"WR"',
    '"Team"': '"MIA"',
    '"PosRank"': '4',
    '"AVGRank"': '7.5',
    '"AVGTier"': '1',
    '"Siegele7.11"': '9',
    '"Curtis7.9"': '6',
  },
  {
    '""': '"8"',
    '"Rank"': '8',
    '"Player"': '"Bijan Robinson"',
    '"POS"': '"RB"',
    '"Team"': '"ATL"',
    '"PosRank"': '3',
    '"AVGRank"': '7.5',
    '"AVGTier"': '1',
    '"Siegele7.11"': '7',
    '"Curtis7.9"': '8',
  },
  {
    '""': '"9"',
    '"Rank"': '9',
    '"Player"': '"Jonathan Taylor"',
    '"POS"': '"RB"',
    '"Team"': '"IND"',
    '"PosRank"': '4',
    '"AVGRank"': '9',
    '"AVGTier"': '1',
    '"Siegele7.11"': '8',
    '"Curtis7.9"': '10',
  },
  {
    '""': '"10"',
    '"Rank"': '10',
    '"Player"': '"CeeDee Lamb"',
    '"POS"': '"WR"',
    '"Team"': '"DAL"',
    '"PosRank"': '5',
    '"AVGRank"': '11.5',
    '"AVGTier"': '2',
    '"Siegele7.11"': '11',
    '"Curtis7.9"': '12',
  },
  {
    '""': '"11"',
    '"Rank"': '11',
    '"Player"': '"Garrett Wilson"',
    '"POS"': '"WR"',
    '"Team"': '"NYJ"',
    '"PosRank"': '6',
    '"AVGRank"': '11.5',
    '"AVGTier"': '2',
    '"Siegele7.11"': '10',
    '"Curtis7.9"': '13',
  },
  {
    '""': '"12"',
    '"Rank"': '12',
    '"Player"': '"Stefon Diggs"',
    '"POS"': '"WR"',
    '"Team"': '"BUF"',
    '"PosRank"': '7',
    '"AVGRank"': '13',
    '"AVGTier"': '2',
    '"Siegele7.11"': '15',
    '"Curtis7.9"': '11',
  },
  {
    '""': '"13"',
    '"Rank"': '13',
    '"Player"': '"A.J. Brown"',
    '"POS"': '"WR"',
    '"Team"': '"PHI"',
    '"PosRank"': '8',
    '"AVGRank"': '14',
    '"AVGTier"': '2',
    '"Siegele7.11"': '14',
    '"Curtis7.9"': '14',
  },
  {
    '""': '"14"',
    '"Rank"': '14',
    '"Player"': '"Amon-Ra St. Brown"',
    '"POS"': '"WR"',
    '"Team"': '"DET"',
    '"PosRank"': '9',
    '"AVGRank"': '15',
    '"AVGTier"': '2',
    '"Siegele7.11"': '13',
    '"Curtis7.9"': '17',
  },
  {
    '""': '"15"',
    '"Rank"': '15',
    '"Player"': '"Chris Olave"',
    '"POS"': '"WR"',
    '"Team"': '"NO"',
    '"PosRank"': '10',
    '"AVGRank"': '16',
    '"AVGTier"': '2',
    '"Siegele7.11"': '17',
    '"Curtis7.9"': '15',
  },
  {
    '""': '"16"',
    '"Rank"': '16',
    '"Player"': '"Mark Andrews"',
    '"POS"': '"TE"',
    '"Team"': '"BAL"',
    '"PosRank"': '2',
    '"AVGRank"': '17',
    '"AVGTier"': '2',
    '"Siegele7.11"': '16',
    '"Curtis7.9"': '18',
  },
  {
    '""': '"17"',
    '"Rank"': '17',
    '"Player"': '"Saquon Barkley"',
    '"POS"': '"RB"',
    '"Team"': '"NYG"',
    '"PosRank"': '5',
    '"AVGRank"': '19.5',
    '"AVGTier"': '2',
    '"Siegele7.11"': '18',
    '"Curtis7.9"': '21',
  },
  {
    '""': '"18"',
    '"Rank"': '18',
    '"Player"': '"Jaylen Waddle"',
    '"POS"': '"WR"',
    '"Team"': '"MIA"',
    '"PosRank"': '11',
    '"AVGRank"': '20.5',
    '"AVGTier"': '2',
    '"Siegele7.11"': '12',
    '"Curtis7.9"': '29',
  },
  {
    '""': '"19"',
    '"Rank"': '19',
    '"Player"': '"Davante Adams"',
    '"POS"': '"WR"',
    '"Team"': '"LV"',
    '"PosRank"': '12',
    '"AVGRank"': '21',
    '"AVGTier"': '2',
    '"Siegele7.11"': '26',
    '"Curtis7.9"': '16',
  },
  {
    '""': '"20"',
    '"Rank"': '20',
    '"Player"': '"Nick Chubb"',
    '"POS"': '"RB"',
    '"Team"': '"CLE"',
    '"PosRank"': '6',
    '"AVGRank"': '21',
    '"AVGTier"': '2',
    '"Siegele7.11"': '33',
    '"Curtis7.9"': '9',
  },
  {
    '""': '"21"',
    '"Rank"': '21',
    '"Player"': '"Rhamondre Stevenson"',
    '"POS"': '"RB"',
    '"Team"': '"NE"',
    '"PosRank"': '7',
    '"AVGRank"': '22',
    '"AVGTier"': '2',
    '"Siegele7.11"': '22',
    '"Curtis7.9"': '22',
  },
  {
    '""': '"22"',
    '"Rank"': '22',
    '"Player"': '"Josh Jacobs"',
    '"POS"': '"RB"',
    '"Team"': '"LV"',
    '"PosRank"': '8',
    '"AVGRank"': '23.5',
    '"AVGTier"': '2',
    '"Siegele7.11"': '28',
    '"Curtis7.9"': '19',
  },
  {
    '""': '"23"',
    '"Rank"': '23',
    '"Player"': '"Tony Pollard"',
    '"POS"': '"RB"',
    '"Team"': '"DAL"',
    '"PosRank"': '9',
    '"AVGRank"': '23.5',
    '"AVGTier"': '2',
    '"Siegele7.11"': '24',
    '"Curtis7.9"': '23',
  },
  {
    '""': '"24"',
    '"Rank"': '24',
    '"Player"': '"Jalen Hurts"',
    '"POS"': '"QB"',
    '"Team"': '"PHI"',
    '"PosRank"': '1',
    '"AVGRank"': '24',
    '"AVGTier"': '2',
    '"Siegele7.11"': '21',
    '"Curtis7.9"': '27',
  },
  {
    '""': '"25"',
    '"Rank"': '25',
    '"Player"': '"Breece Hall"',
    '"POS"': '"RB"',
    '"Team"': '"NYJ"',
    '"PosRank"': '10',
    '"AVGRank"': '24.5',
    '"AVGTier"': '2',
    '"Siegele7.11"': '25',
    '"Curtis7.9"': '24',
  },
  {
    '""': '"26"',
    '"Rank"': '26',
    '"Player"': '"DeVonta Smith"',
    '"POS"': '"WR"',
    '"Team"': '"PHI"',
    '"PosRank"': '13',
    '"AVGRank"': '24.5',
    '"AVGTier"': '2',
    '"Siegele7.11"': '19',
    '"Curtis7.9"': '30',
  },
  {
    '""': '"27"',
    '"Rank"': '27',
    '"Player"': '"Tee Higgins"',
    '"POS"': '"WR"',
    '"Team"': '"CIN"',
    '"PosRank"': '14',
    '"AVGRank"': '25.5',
    '"AVGTier"': '2',
    '"Siegele7.11"': '20',
    '"Curtis7.9"': '31',
  },
  {
    '""': '"28"',
    '"Rank"': '28',
    '"Player"': '"T.J. Hockenson"',
    '"POS"': '"TE"',
    '"Team"': '"MIN"',
    '"PosRank"': '3',
    '"AVGRank"': '25.5',
    '"AVGTier"': '2',
    '"Siegele7.11"': '23',
    '"Curtis7.9"': '28',
  },
  {
    '""': '"29"',
    '"Rank"': '29',
    '"Player"': '"Patrick Mahomes"',
    '"POS"': '"QB"',
    '"Team"': '"KC"',
    '"PosRank"': '2',
    '"AVGRank"': '27',
    '"AVGTier"': '2',
    '"Siegele7.11"': '29',
    '"Curtis7.9"': '25',
  },
  {
    '""': '"30"',
    '"Rank"': '30',
    '"Player"': '"Derrick Henry"',
    '"POS"': '"RB"',
    '"Team"': '"TEN"',
    '"PosRank"': '11',
    '"AVGRank"': '28',
    '"AVGTier"': '2',
    '"Siegele7.11"': '36',
    '"Curtis7.9"': '20',
  },
  {
    '""': '"31"',
    '"Rank"': '31',
    '"Player"': '"Josh Allen"',
    '"POS"': '"QB"',
    '"Team"': '"BUF"',
    '"PosRank"': '3',
    '"AVGRank"': '28.5',
    '"AVGTier"': '2',
    '"Siegele7.11"': '31',
    '"Curtis7.9"': '26',
  },
  {
    '""': '"32"',
    '"Rank"': '32',
    '"Player"': '"Keenan Allen"',
    '"POS"': '"WR"',
    '"Team"': '"LAC"',
    '"PosRank"': '15',
    '"AVGRank"': '31',
    '"AVGTier"': '3',
    '"Siegele7.11"': '30',
    '"Curtis7.9"': '32',
  },
  {
    '""': '"33"',
    '"Rank"': '33',
    '"Player"': '"Jahmyr Gibbs"',
    '"POS"': '"RB"',
    '"Team"': '"DET"',
    '"PosRank"': '12',
    '"AVGRank"': '31.5',
    '"AVGTier"': '3',
    '"Siegele7.11"': '27',
    '"Curtis7.9"': '36',
  },
  {
    '""': '"34"',
    '"Rank"': '34',
    '"Player"': '"Jerry Jeudy"',
    '"POS"': '"WR"',
    '"Team"': '"DEN"',
    '"PosRank"': '16',
    '"AVGRank"': '34',
    '"AVGTier"': '3',
    '"Siegele7.11"': '35',
    '"Curtis7.9"': '33',
  },
  {
    '""': '"35"',
    '"Rank"': '35',
    '"Player"': '"Travis Etienne"',
    '"POS"': '"RB"',
    '"Team"': '"JAC"',
    '"PosRank"': '13',
    '"AVGRank"': '34.5',
    '"AVGTier"': '3',
    '"Siegele7.11"': '34',
    '"Curtis7.9"': '35',
  },
  {
    '""': '"36"',
    '"Rank"': '36',
    '"Player"': '"Deebo Samuel"',
    '"POS"': '"WR"',
    '"Team"': '"SF"',
    '"PosRank"': '17',
    '"AVGRank"': '35',
    '"AVGTier"': '3',
    '"Siegele7.11"': '32',
    '"Curtis7.9"': '38',
  },
  {
    '""': '"37"',
    '"Rank"': '37',
    '"Player"': '"Chris Godwin"',
    '"POS"': '"WR"',
    '"Team"': '"TB"',
    '"PosRank"': '18',
    '"AVGRank"': '38.5',
    '"AVGTier"': '3',
    '"Siegele7.11"': '38',
    '"Curtis7.9"': '39',
  },
  {
    '""': '"38"',
    '"Rank"': '38',
    '"Player"': '"Kyle Pitts"',
    '"POS"': '"TE"',
    '"Team"': '"ATL"',
    '"PosRank"': '4',
    '"AVGRank"': '39.5',
    '"AVGTier"': '3',
    '"Siegele7.11"': '39',
    '"Curtis7.9"': '40',
  },
  {
    '""': '"39"',
    '"Rank"': '39',
    '"Player"': '"Dallas Goedert"',
    '"POS"': '"TE"',
    '"Team"': '"PHI"',
    '"PosRank"': '5',
    '"AVGRank"': '41',
    '"AVGTier"': '3',
    '"Siegele7.11"': '40',
    '"Curtis7.9"': '42',
  },
  {
    '""': '"40"',
    '"Rank"': '40',
    '"Player"': '"DK Metcalf"',
    '"POS"': '"WR"',
    '"Team"': '"SEA"',
    '"PosRank"': '19',
    '"AVGRank"': '42',
    '"AVGTier"': '3',
    '"Siegele7.11"': '41',
    '"Curtis7.9"': '43',
  },
  {
    '""': '"41"',
    '"Rank"': '41',
    '"Player"': '"George Kittle"',
    '"POS"': '"TE"',
    '"Team"': '"SF"',
    '"PosRank"': '6',
    '"AVGRank"': '42',
    '"AVGTier"': '3',
    '"Siegele7.11"': '43',
    '"Curtis7.9"': '41',
  },
  {
    '""': '"42"',
    '"Rank"': '42',
    '"Player"': '"Justin Fields"',
    '"POS"': '"QB"',
    '"Team"': '"CHI"',
    '"PosRank"': '4',
    '"AVGRank"': '44',
    '"AVGTier"': '3',
    '"Siegele7.11"': '42',
    '"Curtis7.9"': '46',
  },
  {
    '""': '"43"',
    '"Rank"': '43',
    '"Player"': '"DeAndre Hopkins"',
    '"POS"': '"WR"',
    '"Team"': '"TEN"',
    '"PosRank"': '20',
    '"AVGRank"': '45',
    '"AVGTier"': '3',
    '"Siegele7.11"': '45',
    '"Curtis7.9"': '45',
  },
  {
    '""': '"44"',
    '"Rank"': '44',
    '"Player"': '"J.K. Dobbins"',
    '"POS"': '"RB"',
    '"Team"': '"BAL"',
    '"PosRank"': '14',
    '"AVGRank"': '45.5',
    '"AVGTier"': '3',
    '"Siegele7.11"': '44',
    '"Curtis7.9"': '47',
  },
  {
    '""': '"45"',
    '"Rank"': '45',
    '"Player"': '"Joe Burrow"',
    '"POS"': '"QB"',
    '"Team"': '"CIN"',
    '"PosRank"': '5',
    '"AVGRank"': '47.5',
    '"AVGTier"': '3',
    '"Siegele7.11"': '47',
    '"Curtis7.9"': '48',
  },
  {
    '""': '"46"',
    '"Rank"': '46',
    '"Player"': '"Lamar Jackson"',
    '"POS"': '"QB"',
    '"Team"': '"BAL"',
    '"PosRank"': '6',
    '"AVGRank"': '48.5',
    '"AVGTier"': '3',
    '"Siegele7.11"': '48',
    '"Curtis7.9"': '49',
  },
  {
    '""': '"47"',
    '"Rank"': '47',
    '"Player"': '"Kenneth Walker"',
    '"POS"': '"RB"',
    '"Team"': '"SEA"',
    '"PosRank"': '15',
    '"AVGRank"': '49',
    '"AVGTier"': '3',
    '"Siegele7.11"': '37',
    '"Curtis7.9"': '61',
  },
  {
    '""': '"48"',
    '"Rank"': '48',
    '"Player"': '"DJ Moore"',
    '"POS"': '"WR"',
    '"Team"': '"CHI"',
    '"PosRank"': '21',
    '"AVGRank"': '51',
    '"AVGTier"': '3',
    '"Siegele7.11"': '51',
    '"Curtis7.9"': '51',
  },
  {
    '""': '"49"',
    '"Rank"': '49',
    '"Player"': '"Najee Harris"',
    '"POS"': '"RB"',
    '"Team"': '"PIT"',
    '"PosRank"': '16',
    '"AVGRank"': '51.5',
    '"AVGTier"': '4',
    '"Siegele7.11"': '66',
    '"Curtis7.9"': '37',
  },
  {
    '""': '"50"',
    '"Rank"': '50',
    '"Player"': '"Jaxon Smith-Njigba"',
    '"POS"': '"WR"',
    '"Team"': '"SEA"',
    '"PosRank"': '22',
    '"AVGRank"': '51.5',
    '"AVGTier"': '3',
    '"Siegele7.11"': '46',
    '"Curtis7.9"': '57',
  },
  {
    '""': '"51"',
    '"Rank"': '51',
    '"Player"': '"Drake London"',
    '"POS"': '"WR"',
    '"Team"': '"ATL"',
    '"PosRank"': '23',
    '"AVGRank"': '52',
    '"AVGTier"': '3',
    '"Siegele7.11"': '52',
    '"Curtis7.9"': '52',
  },
  {
    '""': '"52"',
    '"Rank"': '52',
    '"Player"': '"Christian Watson"',
    '"POS"': '"WR"',
    '"Team"': '"GB"',
    '"PosRank"': '24',
    '"AVGRank"': '52.5',
    '"AVGTier"': '3',
    '"Siegele7.11"': '55',
    '"Curtis7.9"': '50',
  },
  {
    '""': '"53"',
    '"Rank"': '53',
    '"Player"': '"Treylon Burks"',
    '"POS"': '"WR"',
    '"Team"': '"TEN"',
    '"PosRank"': '25',
    '"AVGRank"': '52.5',
    '"AVGTier"': '4',
    '"Siegele7.11"': '49',
    '"Curtis7.9"': '56',
  },
  {
    '""': '"54"',
    '"Rank"': '54',
    '"Player"': '"Terry McLaurin"',
    '"POS"': '"WR"',
    '"Team"': '"WAS"',
    '"PosRank"': '26',
    '"AVGRank"': '53',
    '"AVGTier"': '3',
    '"Siegele7.11"': '53',
    '"Curtis7.9"': '53',
  },
  {
    '""': '"55"',
    '"Rank"': '55',
    '"Player"': '"Calvin Ridley"',
    '"POS"': '"WR"',
    '"Team"': '"JAC"',
    '"PosRank"': '27',
    '"AVGRank"': '55.5',
    '"AVGTier"': '3',
    '"Siegele7.11"': '56',
    '"Curtis7.9"': '55',
  },
  {
    '""': '"56"',
    '"Rank"': '56',
    '"Player"': '"Justin Herbert"',
    '"POS"': '"QB"',
    '"Team"': '"LAC"',
    '"PosRank"': '7',
    '"AVGRank"': '57.5',
    '"AVGTier"': '3',
    '"Siegele7.11"': '57',
    '"Curtis7.9"': '58',
  },
  {
    '""': '"57"',
    '"Rank"': '57',
    '"Player"': '"Joe Mixon"',
    '"POS"': '"RB"',
    '"Team"': '"CIN"',
    '"PosRank"': '17',
    '"AVGRank"': '59',
    '"AVGTier"': '4',
    '"Siegele7.11"': '84',
    '"Curtis7.9"': '34',
  },
  {
    '""': '"58"',
    '"Rank"': '58',
    '"Player"': '"D\'Andre Swift"',
    '"POS"': '"RB"',
    '"Team"': '"PHI"',
    '"PosRank"': '18',
    '"AVGRank"': '59.5',
    '"AVGTier"': '4',
    '"Siegele7.11"': '50',
    '"Curtis7.9"': '69',
  },
  {
    '""': '"59"',
    '"Rank"': '59',
    '"Player"': '"Aaron Jones"',
    '"POS"': '"RB"',
    '"Team"': '"GB"',
    '"PosRank"': '19',
    '"AVGRank"': '59.5',
    '"AVGTier"': '3',
    '"Siegele7.11"': '60',
    '"Curtis7.9"': '59',
  },
  {
    '""': '"60"',
    '"Rank"': '60',
    '"Player"': '"Amari Cooper"',
    '"POS"': '"WR"',
    '"Team"': '"CLE"',
    '"PosRank"': '28',
    '"AVGRank"': '60',
    '"AVGTier"': '4',
    '"Siegele7.11"': '76',
    '"Curtis7.9"': '44',
  },
  {
    '""': '"61"',
    '"Rank"': '61',
    '"Player"': '"Mike Evans"',
    '"POS"': '"WR"',
    '"Team"': '"TB"',
    '"PosRank"': '29',
    '"AVGRank"': '60',
    '"AVGTier"': '3',
    '"Siegele7.11"': '54',
    '"Curtis7.9"': '66',
  },
  {
    '""': '"62"',
    '"Rank"': '62',
    '"Player"': '"Brandon Aiyuk"',
    '"POS"': '"WR"',
    '"Team"': '"SF"',
    '"PosRank"': '30',
    '"AVGRank"': '61',
    '"AVGTier"': '3',
    '"Siegele7.11"': '59',
    '"Curtis7.9"': '63',
  },
  {
    '""': '"63"',
    '"Rank"': '63',
    '"Player"': '"George Pickens"',
    '"POS"': '"WR"',
    '"Team"': '"PIT"',
    '"PosRank"': '31',
    '"AVGRank"': '63',
    '"AVGTier"': '3',
    '"Siegele7.11"': '62',
    '"Curtis7.9"': '64',
  },
  {
    '""': '"64"',
    '"Rank"': '64',
    '"Player"': '"Diontae Johnson"',
    '"POS"': '"WR"',
    '"Team"': '"PIT"',
    '"PosRank"': '32',
    '"AVGRank"': '63',
    '"AVGTier"': '3',
    '"Siegele7.11"': '61',
    '"Curtis7.9"': '65',
  },
  {
    '""': '"65"',
    '"Rank"': '65',
    '"Player"': '"Mike Williams"',
    '"POS"': '"WR"',
    '"Team"': '"LAC"',
    '"PosRank"': '33',
    '"AVGRank"': '64.5',
    '"AVGTier"': '4',
    '"Siegele7.11"': '75',
    '"Curtis7.9"': '54',
  },
  {
    '""': '"66"',
    '"Rank"': '66',
    '"Player"': '"Cam Akers"',
    '"POS"': '"RB"',
    '"Team"': '"LAR"',
    '"PosRank"': '20',
    '"AVGRank"': '64.5',
    '"AVGTier"': '4',
    '"Siegele7.11"': '69',
    '"Curtis7.9"': '60',
  },
  {
    '""': '"67"',
    '"Rank"': '67',
    '"Player"': '"Jahan Dotson"',
    '"POS"': '"WR"',
    '"Team"': '"WAS"',
    '"PosRank"': '34',
    '"AVGRank"': '65',
    '"AVGTier"': '4',
    '"Siegele7.11"': '58',
    '"Curtis7.9"': '72',
  },
  {
    '""': '"68"',
    '"Rank"': '68',
    '"Player"': '"Tyler Lockett"',
    '"POS"': '"WR"',
    '"Team"': '"SEA"',
    '"PosRank"': '35',
    '"AVGRank"': '66',
    '"AVGTier"': '4',
    '"Siegele7.11"': '65',
    '"Curtis7.9"': '67',
  },
  {
    '""': '"69"',
    '"Rank"': '69',
    '"Player"': '"Marquise Brown"',
    '"POS"': '"WR"',
    '"Team"': '"ARI"',
    '"PosRank"': '36',
    '"AVGRank"': '66.5',
    '"AVGTier"': '4',
    '"Siegele7.11"': '71',
    '"Curtis7.9"': '62',
  },
  {
    '""': '"70"',
    '"Rank"': '70',
    '"Player"': '"Evan Engram"',
    '"POS"': '"TE"',
    '"Team"': '"JAC"',
    '"PosRank"': '7',
    '"AVGRank"': '68',
    '"AVGTier"': '5',
    '"Siegele7.11"': '68',
    '"Curtis7.9"': '68',
  },
  {
    '""': '"71"',
    '"Rank"': '71',
    '"Player"': '"Quentin Johnston"',
    '"POS"': '"WR"',
    '"Team"': '"LAC"',
    '"PosRank"': '37',
    '"AVGRank"': '68',
    '"AVGTier"': '4',
    '"Siegele7.11"': '63',
    '"Curtis7.9"': '73',
  },
  {
    '""': '"72"',
    '"Rank"': '72',
    '"Player"': '"Dameon Pierce"',
    '"POS"': '"RB"',
    '"Team"': '"HOU"',
    '"PosRank"': '21',
    '"AVGRank"': '69',
    '"AVGTier"': '5',
    '"Siegele7.11"': '64',
    '"Curtis7.9"': '74',
  },
  {
    '""': '"73"',
    '"Rank"': '73',
    '"Player"': '"Javonte Williams"',
    '"POS"': '"RB"',
    '"Team"': '"DEN"',
    '"PosRank"': '22',
    '"AVGRank"': '71',
    '"AVGTier"': '5',
    '"Siegele7.11"': '72',
    '"Curtis7.9"': '70',
  },
  {
    '""': '"74"',
    '"Rank"': '74',
    '"Player"': '"James Cook"',
    '"POS"': '"RB"',
    '"Team"': '"BUF"',
    '"PosRank"': '23',
    '"AVGRank"': '71',
    '"AVGTier"': '5',
    '"Siegele7.11"': '67',
    '"Curtis7.9"': '75',
  },
  {
    '""': '"75"',
    '"Rank"': '75',
    '"Player"': '"Michael Pittman"',
    '"POS"': '"WR"',
    '"Team"': '"IND"',
    '"PosRank"': '38',
    '"AVGRank"': '73',
    '"AVGTier"': '5',
    '"Siegele7.11"': '70',
    '"Curtis7.9"': '76',
  },
  {
    '""': '"76"',
    '"Rank"': '76',
    '"Player"': '"Jordan Addison"',
    '"POS"': '"WR"',
    '"Team"': '"MIN"',
    '"PosRank"': '39',
    '"AVGRank"': '75',
    '"AVGTier"': '5',
    '"Siegele7.11"': '73',
    '"Curtis7.9"': '77',
  },
  {
    '""': '"77"',
    '"Rank"': '77',
    '"Player"': '"Christian Kirk"',
    '"POS"': '"WR"',
    '"Team"': '"JAC"',
    '"PosRank"': '40',
    '"AVGRank"': '77.5',
    '"AVGTier"': '5',
    '"Siegele7.11"': '77',
    '"Curtis7.9"': '78',
  },
  {
    '""': '"78"',
    '"Rank"': '78',
    '"Player"': '"Pat Freiermuth"',
    '"POS"': '"TE"',
    '"Team"': '"PIT"',
    '"PosRank"': '8',
    '"AVGRank"': '78.5',
    '"AVGTier"': '5',
    '"Siegele7.11"': '74',
    '"Curtis7.9"': '83',
  },
  {
    '""': '"79"',
    '"Rank"': '79',
    '"Player"': '"Kadarius Toney"',
    '"POS"': '"WR"',
    '"Team"': '"KC"',
    '"PosRank"': '41',
    '"AVGRank"': '78.5',
    '"AVGTier"': '5',
    '"Siegele7.11"': '78',
    '"Curtis7.9"': '79',
  },
  {
    '""': '"80"',
    '"Rank"': '80',
    '"Player"': '"Elijah Moore"',
    '"POS"': '"WR"',
    '"Team"': '"CLE"',
    '"PosRank"': '42',
    '"AVGRank"': '80',
    '"AVGTier"': '5',
    '"Siegele7.11"': '80',
    '"Curtis7.9"': '80',
  },
  {
    '""': '"81"',
    '"Rank"': '81',
    '"Player"': '"Trevor Lawrence"',
    '"POS"': '"QB"',
    '"Team"': '"JAC"',
    '"PosRank"': '8',
    '"AVGRank"': '81.5',
    '"AVGTier"': '5',
    '"Siegele7.11"': '79',
    '"Curtis7.9"': '84',
  },
  {
    '""': '"82"',
    '"Rank"': '82',
    '"Player"': '"Brandin Cooks"',
    '"POS"': '"WR"',
    '"Team"': '"DAL"',
    '"PosRank"': '43',
    '"AVGRank"': '82',
    '"AVGTier"': '6',
    '"Siegele7.11"': '82',
    '"Curtis7.9"': '82',
  },
  {
    '""': '"83"',
    '"Rank"': '83',
    '"Player"': '"Miles Sanders"',
    '"POS"': '"RB"',
    '"Team"': '"CAR"',
    '"PosRank"': '24',
    '"AVGRank"': '85',
    '"AVGTier"': '6',
    '"Siegele7.11"': '89',
    '"Curtis7.9"': '81',
  },
  {
    '""': '"84"',
    '"Rank"': '84',
    '"Player"': '"Zay Flowers"',
    '"POS"': '"WR"',
    '"Team"': '"BAL"',
    '"PosRank"': '44',
    '"AVGRank"': '85',
    '"AVGTier"': '6',
    '"Siegele7.11"': '83',
    '"Curtis7.9"': '87',
  },
  {
    '""': '"85"',
    '"Rank"': '85',
    '"Player"': '"David Montgomery"',
    '"POS"': '"RB"',
    '"Team"': '"DET"',
    '"PosRank"': '25',
    '"AVGRank"': '86.5',
    '"AVGTier"': '6',
    '"Siegele7.11"': '88',
    '"Curtis7.9"': '85',
  },
  {
    '""': '"86"',
    '"Rank"': '86',
    '"Player"': '"James Conner"',
    '"POS"': '"RB"',
    '"Team"': '"ARI"',
    '"PosRank"': '26',
    '"AVGRank"': '87',
    '"AVGTier"': '6',
    '"Siegele7.11"': '103',
    '"Curtis7.9"': '71',
  },
  {
    '""': '"87"',
    '"Rank"': '87',
    '"Player"': '"Samaje Perine"',
    '"POS"': '"RB"',
    '"Team"': '"DEN"',
    '"PosRank"': '27',
    '"AVGRank"': '88',
    '"AVGTier"': '6',
    '"Siegele7.11"': '90',
    '"Curtis7.9"': '86',
  },
  {
    '""': '"88"',
    '"Rank"': '88',
    '"Player"': '"Rashaad Penny"',
    '"POS"': '"RB"',
    '"Team"': '"PHI"',
    '"PosRank"': '28',
    '"AVGRank"': '89',
    '"AVGTier"': '6',
    '"Siegele7.11"': '87',
    '"Curtis7.9"': '91',
  },
  {
    '""': '"89"',
    '"Rank"': '89',
    '"Player"': '"Alexander Mattison"',
    '"POS"': '"RB"',
    '"Team"': '"MIN"',
    '"PosRank"': '29',
    '"AVGRank"': '89.5',
    '"AVGTier"': '6',
    '"Siegele7.11"': '91',
    '"Curtis7.9"': '88',
  },
  {
    '""': '"90"',
    '"Rank"': '90',
    '"Player"': '"Romeo Doubs"',
    '"POS"': '"WR"',
    '"Team"': '"GB"',
    '"PosRank"': '45',
    '"AVGRank"': '89.5',
    '"AVGTier"': '6',
    '"Siegele7.11"': '85',
    '"Curtis7.9"': '94',
  },
  {
    '""': '"91"',
    '"Rank"': '91',
    '"Player"': '"Tua Tagovailoa"',
    '"POS"': '"QB"',
    '"Team"': '"MIA"',
    '"PosRank"': '9',
    '"AVGRank"': '90',
    '"AVGTier"': '6',
    '"Siegele7.11"': '81',
    '"Curtis7.9"': '99',
  },
  {
    '""': '"92"',
    '"Rank"': '92',
    '"Player"': '"David Njoku"',
    '"POS"': '"TE"',
    '"Team"': '"CLE"',
    '"PosRank"': '9',
    '"AVGRank"': '90.5',
    '"AVGTier"': '6',
    '"Siegele7.11"': '92',
    '"Curtis7.9"': '89',
  },
  {
    '""': '"93"',
    '"Rank"': '93',
    '"Player"': '"Deshaun Watson"',
    '"POS"': '"QB"',
    '"Team"': '"CLE"',
    '"PosRank"': '10',
    '"AVGRank"': '91',
    '"AVGTier"': '6',
    '"Siegele7.11"': '86',
    '"Curtis7.9"': '96',
  },
  {
    '""': '"94"',
    '"Rank"': '94',
    '"Player"': '"Dalvin Cook"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '30',
    '"AVGRank"': '92',
    '"AVGTier"': '6',
    '"Siegele7.11"': '94',
    '"Curtis7.9"': '90',
  },
  {
    '""': '"95"',
    '"Rank"': '95',
    '"Player"': '"AJ Dillon"',
    '"POS"': '"RB"',
    '"Team"': '"GB"',
    '"PosRank"': '31',
    '"AVGRank"': '94',
    '"AVGTier"': '6',
    '"Siegele7.11"': '95',
    '"Curtis7.9"': '93',
  },
  {
    '""': '"96"',
    '"Rank"': '96',
    '"Player"': '"Devon Achane"',
    '"POS"': '"RB"',
    '"Team"': '""',
    '"PosRank"': '32',
    '"AVGRank"': '95.5',
    '"AVGTier"': '6',
    '"Siegele7.11"': '96',
    '"Curtis7.9"': '95',
  },
  {
    '""': '"97"',
    '"Rank"': '97',
    '"Player"': '"Skyy Moore"',
    '"POS"': '"WR"',
    '"Team"': '"KC"',
    '"PosRank"': '46',
    '"AVGRank"': '96.5',
    '"AVGTier"': '6',
    '"Siegele7.11"': '93',
    '"Curtis7.9"': '100',
  },
  {
    '""': '"98"',
    '"Rank"': '98',
    '"Player"': '"Isiah Pacheco"',
    '"POS"': '"RB"',
    '"Team"': '"KC"',
    '"PosRank"': '33',
    '"AVGRank"': '97',
    '"AVGTier"': '6',
    '"Siegele7.11"': '102',
    '"Curtis7.9"': '92',
  },
  {
    '""': '"99"',
    '"Rank"': '99',
    '"Player"': '"Jameson Williams"',
    '"POS"': '"WR"',
    '"Team"': '"DET"',
    '"PosRank"': '47',
    '"AVGRank"': '97',
    '"AVGTier"': '6',
    '"Siegele7.11"': '97',
    '"Curtis7.9"': '97',
  },
  {
    '""': '"100"',
    '"Rank"': '100',
    '"Player"': '"Darren Waller"',
    '"POS"': '"TE"',
    '"Team"': '"NYG"',
    '"PosRank"': '10',
    '"AVGRank"': '98',
    '"AVGTier"': '6',
    '"Siegele7.11"': '98',
    '"Curtis7.9"': '98',
  },
  {
    '""': '"101"',
    '"Rank"': '101',
    '"Player"': '"Rachaad White"',
    '"POS"': '"RB"',
    '"Team"': '"TB"',
    '"PosRank"': '34',
    '"AVGRank"': '100.5',
    '"AVGTier"': '6',
    '"Siegele7.11"': '99',
    '"Curtis7.9"': '102',
  },
  {
    '""': '"102"',
    '"Rank"': '102',
    '"Player"': '"Alvin Kamara"',
    '"POS"': '"RB"',
    '"Team"': '"NO"',
    '"PosRank"': '35',
    '"AVGRank"': '101',
    '"AVGTier"': '6',
    '"Siegele7.11"': '101',
    '"Curtis7.9"': '101',
  },
  {
    '""': '"103"',
    '"Rank"': '103',
    '"Player"': '"Antonio Gibson"',
    '"POS"': '"RB"',
    '"Team"': '"WAS"',
    '"PosRank"': '36',
    '"AVGRank"': '103.5',
    '"AVGTier"': '7',
    '"Siegele7.11"': '104',
    '"Curtis7.9"': '103',
  },
  {
    '""': '"104"',
    '"Rank"': '104',
    '"Player"': '"Greg Dulcich"',
    '"POS"': '"TE"',
    '"Team"': '"DEN"',
    '"PosRank"': '11',
    '"AVGRank"': '104',
    '"AVGTier"': '6',
    '"Siegele7.11"': '100',
    '"Curtis7.9"': '108',
  },
  {
    '""': '"105"',
    '"Rank"': '105',
    '"Player"': '"Dalton Kincaid"',
    '"POS"': '"TE"',
    '"Team"': '"BUF"',
    '"PosRank"': '12',
    '"AVGRank"': '104.5',
    '"AVGTier"': '7',
    '"Siegele7.11"': '105',
    '"Curtis7.9"': '104',
  },
  {
    '""': '"106"',
    '"Rank"': '106',
    '"Player"': '"Michael Thomas"',
    '"POS"': '"WR"',
    '"Team"': '"NO"',
    '"PosRank"': '48',
    '"AVGRank"': '106.5',
    '"AVGTier"': '7',
    '"Siegele7.11"': '107',
    '"Curtis7.9"': '106',
  },
  {
    '""': '"107"',
    '"Rank"': '107',
    '"Player"': '"Dak Prescott"',
    '"POS"': '"QB"',
    '"Team"': '"DAL"',
    '"PosRank"': '11',
    '"AVGRank"': '107.5',
    '"AVGTier"': '7',
    '"Siegele7.11"': '108',
    '"Curtis7.9"': '107',
  },
  {
    '""': '"108"',
    '"Rank"': '108',
    '"Player"': '"Zach Charbonnet"',
    '"POS"': '"RB"',
    '"Team"': '"SEA"',
    '"PosRank"': '37',
    '"AVGRank"': '109',
    '"AVGTier"': '7',
    '"Siegele7.11"': '109',
    '"Curtis7.9"': '109',
  },
  {
    '""': '"109"',
    '"Rank"': '109',
    '"Player"': '"Brian Robinson"',
    '"POS"': '"RB"',
    '"Team"': '"WAS"',
    '"PosRank"': '38',
    '"AVGRank"': '109',
    '"AVGTier"': '7',
    '"Siegele7.11"': '113',
    '"Curtis7.9"': '105',
  },
  {
    '""': '"110"',
    '"Rank"': '110',
    '"Player"': '"Rashod Bateman"',
    '"POS"': '"WR"',
    '"Team"': '"BAL"',
    '"PosRank"': '49',
    '"AVGRank"': '110',
    '"AVGTier"': '7',
    '"Siegele7.11"': '106',
    '"Curtis7.9"': '114',
  },
  {
    '""': '"111"',
    '"Rank"': '111',
    '"Player"': '"Gabe Davis"',
    '"POS"': '"WR"',
    '"Team"': '"BUF"',
    '"PosRank"': '50',
    '"AVGRank"': '110',
    '"AVGTier"': '7',
    '"Siegele7.11"': '110',
    '"Curtis7.9"': '110',
  },
  {
    '""': '"112"',
    '"Rank"': '112',
    '"Player"': '"Kirk Cousins"',
    '"POS"': '"QB"',
    '"Team"': '"MIN"',
    '"PosRank"': '12',
    '"AVGRank"': '111',
    '"AVGTier"': '7',
    '"Siegele7.11"': '111',
    '"Curtis7.9"': '111',
  },
  {
    '""': '"113"',
    '"Rank"': '113',
    '"Player"': '"Khalil Herbert"',
    '"POS"': '"RB"',
    '"Team"': '"CHI"',
    '"PosRank"': '39',
    '"AVGRank"': '112',
    '"AVGTier"': '7',
    '"Siegele7.11"': '112',
    '"Curtis7.9"': '112',
  },
  {
    '""': '"114"',
    '"Rank"': '114',
    '"Player"': '"Sam LaPorta"',
    '"POS"': '"TE"',
    '"Team"': '"DET"',
    '"PosRank"': '13',
    '"AVGRank"': '114.5',
    '"AVGTier"': '7',
    '"Siegele7.11"': '114',
    '"Curtis7.9"': '115',
  },
  {
    '""': '"115"',
    '"Rank"': '115',
    '"Player"': '"Courtland Sutton"',
    '"POS"': '"WR"',
    '"Team"': '"DEN"',
    '"PosRank"': '51',
    '"AVGRank"': '115.5',
    '"AVGTier"': '7',
    '"Siegele7.11"': '115',
    '"Curtis7.9"': '116',
  },
  {
    '""': '"116"',
    '"Rank"': '116',
    '"Player"': '"Daniel Jones"',
    '"POS"': '"QB"',
    '"Team"': '"NYG"',
    '"PosRank"': '13',
    '"AVGRank"': '116.5',
    '"AVGTier"': '7',
    '"Siegele7.11"': '116',
    '"Curtis7.9"': '117',
  },
  {
    '""': '"117"',
    '"Rank"': '117',
    '"Player"': '"Cole Kmet"',
    '"POS"': '"TE"',
    '"Team"': '"CHI"',
    '"PosRank"': '14',
    '"AVGRank"': '117.5',
    '"AVGTier"': '7',
    '"Siegele7.11"': '117',
    '"Curtis7.9"': '118',
  },
  {
    '""': '"118"',
    '"Rank"': '118',
    '"Player"': '"Damien Harris"',
    '"POS"': '"RB"',
    '"Team"': '"BUF"',
    '"PosRank"': '40',
    '"AVGRank"': '118',
    '"AVGTier"': '7',
    '"Siegele7.11"': '123',
    '"Curtis7.9"': '113',
  },
  {
    '""': '"119"',
    '"Rank"': '119',
    '"Player"': '"Anthony Richardson"',
    '"POS"': '"QB"',
    '"Team"': '"IND"',
    '"PosRank"': '14',
    '"AVGRank"': '118.5',
    '"AVGTier"': '7',
    '"Siegele7.11"': '118',
    '"Curtis7.9"': '119',
  },
  {
    '""': '"120"',
    '"Rank"': '120',
    '"Player"': '"Kendre Miller"',
    '"POS"': '"RB"',
    '"Team"': '"NO"',
    '"PosRank"': '41',
    '"AVGRank"': '119.5',
    '"AVGTier"': '7',
    '"Siegele7.11"': '119',
    '"Curtis7.9"': '120',
  },
  {
    '""': '"121"',
    '"Rank"': '121',
    '"Player"': '"Jakobi Meyers"',
    '"POS"': '"WR"',
    '"Team"': '"LV"',
    '"PosRank"': '52',
    '"AVGRank"': '120.5',
    '"AVGTier"': '7',
    '"Siegele7.11"': '120',
    '"Curtis7.9"': '121',
  },
  {
    '""': '"122"',
    '"Rank"': '122',
    '"Player"': '"Dalton Schultz"',
    '"POS"': '"TE"',
    '"Team"': '"HOU"',
    '"PosRank"': '15',
    '"AVGRank"': '122',
    '"AVGTier"': '7',
    '"Siegele7.11"': '122',
    '"Curtis7.9"': '122',
  },
  {
    '""': '"123"',
    '"Rank"': '123',
    '"Player"': '"Geno Smith"',
    '"POS"': '"QB"',
    '"Team"': '"SEA"',
    '"PosRank"': '15',
    '"AVGRank"': '123.5',
    '"AVGTier"': '7',
    '"Siegele7.11"': '124',
    '"Curtis7.9"': '123',
  },
  {
    '""': '"124"',
    '"Rank"': '124',
    '"Player"': '"Elijah Mitchell"',
    '"POS"': '"RB"',
    '"Team"': '"SF"',
    '"PosRank"': '42',
    '"AVGRank"': '125',
    '"AVGTier"': '7',
    '"Siegele7.11"': '126',
    '"Curtis7.9"': '124',
  },
  {
    '""': '"125"',
    '"Rank"': '125',
    '"Player"': '"Jared Goff"',
    '"POS"': '"QB"',
    '"Team"': '"DET"',
    '"PosRank"': '16',
    '"AVGRank"': '126',
    '"AVGTier"': '7',
    '"Siegele7.11"': '127',
    '"Curtis7.9"': '125',
  },
  {
    '""': '"126"',
    '"Rank"': '126',
    '"Player"': '"Roschon Johnson"',
    '"POS"': '"RB"',
    '"Team"': '"CHI"',
    '"PosRank"': '43',
    '"AVGRank"': '127.5',
    '"AVGTier"': '7',
    '"Siegele7.11"': '129',
    '"Curtis7.9"': '126',
  },
  {
    '""': '"127"',
    '"Rank"': '127',
    '"Player"': '"Jamaal Williams"',
    '"POS"': '"RB"',
    '"Team"': '"NO"',
    '"PosRank"': '44',
    '"AVGRank"': '128',
    '"AVGTier"': '7',
    '"Siegele7.11"': '128',
    '"Curtis7.9"': '128',
  },
  {
    '""': '"128"',
    '"Rank"': '128',
    '"Player"': '"Tyler Higbee"',
    '"POS"': '"TE"',
    '"Team"': '"LAR"',
    '"PosRank"': '16',
    '"AVGRank"': '128.5',
    '"AVGTier"': '7',
    '"Siegele7.11"': '130',
    '"Curtis7.9"': '127',
  },
  {
    '""': '"129"',
    '"Rank"': '129',
    '"Player"': '"Russell Wilson"',
    '"POS"': '"QB"',
    '"Team"': '"DEN"',
    '"PosRank"': '17',
    '"AVGRank"': '130',
    '"AVGTier"': '7',
    '"Siegele7.11"': '131',
    '"Curtis7.9"': '129',
  },
  {
    '""': '"130"',
    '"Rank"': '130',
    '"Player"': '"Jaylen Warren"',
    '"POS"': '"RB"',
    '"Team"': '"PIT"',
    '"PosRank"': '45',
    '"AVGRank"': '130',
    '"AVGTier"': '7',
    '"Siegele7.11"': '125',
    '"Curtis7.9"': '135',
  },
  {
    '""': '"131"',
    '"Rank"': '131',
    '"Player"': '"Odell Beckham"',
    '"POS"': '"WR"',
    '"Team"': '"BAL"',
    '"PosRank"': '53',
    '"AVGRank"': '130.5',
    '"AVGTier"': '7',
    '"Siegele7.11"': '121',
    '"Curtis7.9"': '140',
  },
  {
    '""': '"132"',
    '"Rank"': '132',
    '"Player"': '"Zay Jones"',
    '"POS"': '"WR"',
    '"Team"': '"JAC"',
    '"PosRank"': '54',
    '"AVGRank"': '131',
    '"AVGTier"': '7',
    '"Siegele7.11"': '132',
    '"Curtis7.9"': '130',
  },
  {
    '""': '"133"',
    '"Rank"': '133',
    '"Player"': '"Mike Gesicki"',
    '"POS"': '"TE"',
    '"Team"': '"NE"',
    '"PosRank"': '17',
    '"AVGRank"': '133',
    '"AVGTier"': '7',
    '"Siegele7.11"': '133',
    '"Curtis7.9"': '133',
  },
  {
    '""': '"134"',
    '"Rank"': '134',
    '"Player"': '"Tyjae Spears"',
    '"POS"': '"RB"',
    '"Team"': '"TEN"',
    '"PosRank"': '46',
    '"AVGRank"': '134',
    '"AVGTier"': '7',
    '"Siegele7.11"': '134',
    '"Curtis7.9"': '134',
  },
  {
    '""': '"135"',
    '"Rank"': '135',
    '"Player"': '"Aaron Rodgers"',
    '"POS"': '"QB"',
    '"Team"': '"NYJ"',
    '"PosRank"': '18',
    '"AVGRank"': '136',
    '"AVGTier"': '8',
    '"Siegele7.11"': '136',
    '"Curtis7.9"': '136',
  },
  {
    '""': '"136"',
    '"Rank"': '136',
    '"Player"': '"Chigoziem Okonkwo"',
    '"POS"': '"TE"',
    '"Team"': '"TEN"',
    '"PosRank"': '18',
    '"AVGRank"': '137',
    '"AVGTier"': '8',
    '"Siegele7.11"': '137',
    '"Curtis7.9"': '137',
  },
  {
    '""': '"137"',
    '"Rank"': '137',
    '"Player"': '"Irv Smith"',
    '"POS"': '"TE"',
    '"Team"': '"CIN"',
    '"PosRank"': '19',
    '"AVGRank"': '137',
    '"AVGTier"': '7',
    '"Siegele7.11"': '143',
    '"Curtis7.9"': '131',
  },
  {
    '""': '"138"',
    '"Rank"': '138',
    '"Player"': '"Jerick McKinnon"',
    '"POS"': '"RB"',
    '"Team"': '"KC"',
    '"PosRank"': '47',
    '"AVGRank"': '138',
    '"AVGTier"': '8',
    '"Siegele7.11"': '138',
    '"Curtis7.9"': '138',
  },
  {
    '""': '"139"',
    '"Rank"': '139',
    '"Player"': '"Tyler Allgeier"',
    '"POS"': '"RB"',
    '"Team"': '"ATL"',
    '"PosRank"': '48',
    '"AVGRank"': '139',
    '"AVGTier"': '8',
    '"Siegele7.11"': '135',
    '"Curtis7.9"': '143',
  },
  {
    '""': '"140"',
    '"Rank"': '140',
    '"Player"': '"Tyquan Thornton"',
    '"POS"': '"WR"',
    '"Team"': '"NE"',
    '"PosRank"': '55',
    '"AVGRank"': '140.5',
    '"AVGTier"': '7',
    '"Siegele7.11"': '149',
    '"Curtis7.9"': '132',
  },
  {
    '""': '"141"',
    '"Rank"': '141',
    '"Player"': '"Marvin Mims"',
    '"POS"': '"WR"',
    '"Team"': '"DEN"',
    '"PosRank"': '56',
    '"AVGRank"': '141',
    '"AVGTier"': '8',
    '"Siegele7.11"': '141',
    '"Curtis7.9"': '141',
  },
  {
    '""': '"142"',
    '"Rank"': '142',
    '"Player"': '"Tank Bigsby"',
    '"POS"': '"RB"',
    '"Team"': '"JAC"',
    '"PosRank"': '49',
    '"AVGRank"': '142',
    '"AVGTier"': '8',
    '"Siegele7.11"': '142',
    '"Curtis7.9"': '142',
  },
  {
    '""': '"143"',
    '"Rank"': '143',
    '"Player"': '"Trey McBride"',
    '"POS"': '"TE"',
    '"Team"': '"ARI"',
    '"PosRank"': '20',
    '"AVGRank"': '144',
    '"AVGTier"': '8',
    '"Siegele7.11"': '144',
    '"Curtis7.9"': '144',
  },
  {
    '""': '"144"',
    '"Rank"': '144',
    '"Player"': '"Raheem Mostert"',
    '"POS"': '"RB"',
    '"Team"': '"MIA"',
    '"PosRank"': '50',
    '"AVGRank"': '144',
    '"AVGTier"': '8',
    '"Siegele7.11"': '139',
    '"Curtis7.9"': '149',
  },
  {
    '""': '"145"',
    '"Rank"': '145',
    '"Player"': '"Chuba Hubbard"',
    '"POS"': '"RB"',
    '"Team"': '"CAR"',
    '"PosRank"': '51',
    '"AVGRank"': '145',
    '"AVGTier"': '8',
    '"Siegele7.11"': '140',
    '"Curtis7.9"': '150',
  },
  {
    '""': '"146"',
    '"Rank"': '146',
    '"Player"': '"Tyler Boyd"',
    '"POS"': '"WR"',
    '"Team"': '"CIN"',
    '"PosRank"': '57',
    '"AVGRank"': '145.5',
    '"AVGTier"': '8',
    '"Siegele7.11"': '146',
    '"Curtis7.9"': '145',
  },
  {
    '""': '"147"',
    '"Rank"': '147',
    '"Player"': '"Rondale Moore"',
    '"POS"': '"WR"',
    '"Team"': '"ARI"',
    '"PosRank"': '58',
    '"AVGRank"': '146.5',
    '"AVGTier"': '8',
    '"Siegele7.11"': '147',
    '"Curtis7.9"': '146',
  },
  {
    '""': '"148"',
    '"Rank"': '148',
    '"Player"': '"Jordan Love"',
    '"POS"': '"QB"',
    '"Team"': '"GB"',
    '"PosRank"': '19',
    '"AVGRank"': '147.5',
    '"AVGTier"': '8',
    '"Siegele7.11"': '156',
    '"Curtis7.9"': '139',
  },
  {
    '""': '"149"',
    '"Rank"': '149',
    '"Player"': '"Allen Lazard"',
    '"POS"': '"WR"',
    '"Team"': '"NYJ"',
    '"PosRank"': '59',
    '"AVGRank"': '147.5',
    '"AVGTier"': '8',
    '"Siegele7.11"': '148',
    '"Curtis7.9"': '147',
  },
  {
    '""': '"150"',
    '"Rank"': '150',
    '"Player"': '"Kyler Murray"',
    '"POS"': '"QB"',
    '"Team"': '"ARI"',
    '"PosRank"': '20',
    '"AVGRank"': '149',
    '"AVGTier"': '8',
    '"Siegele7.11"': '150',
    '"Curtis7.9"': '148',
  },
  {
    '""': '"151"',
    '"Rank"': '151',
    '"Player"': '"Curtis Samuel"',
    '"POS"': '"WR"',
    '"Team"': '"WAS"',
    '"PosRank"': '60',
    '"AVGRank"': '149',
    '"AVGTier"': '8',
    '"Siegele7.11"': '145',
    '"Curtis7.9"': '153',
  },
  {
    '""': '"152"',
    '"Rank"': '152',
    '"Player"': '"Michael Mayer"',
    '"POS"': '"TE"',
    '"Team"': '"LV"',
    '"PosRank"': '21',
    '"AVGRank"': '151',
    '"AVGTier"': '8',
    '"Siegele7.11"': '151',
    '"Curtis7.9"': '151',
  },
  {
    '""': '"153"',
    '"Rank"': '153',
    '"Player"': '"Nico Collins"',
    '"POS"': '"WR"',
    '"Team"': '"HOU"',
    '"PosRank"': '61',
    '"AVGRank"': '153',
    '"AVGTier"': '8',
    '"Siegele7.11"': '152',
    '"Curtis7.9"': '154',
  },
  {
    '""': '"154"',
    '"Rank"': '154',
    '"Player"': '"Kenny Pickett"',
    '"POS"': '"QB"',
    '"Team"': '"PIT"',
    '"PosRank"': '21',
    '"AVGRank"': '154',
    '"AVGTier"': '8',
    '"Siegele7.11"': '153',
    '"Curtis7.9"': '155',
  },
  {
    '""': '"155"',
    '"Rank"': '155',
    '"Player"': '"Devin Singletary"',
    '"POS"': '"RB"',
    '"Team"': '"HOU"',
    '"PosRank"': '52',
    '"AVGRank"': '154.5',
    '"AVGTier"': '8',
    '"Siegele7.11"': '157',
    '"Curtis7.9"': '152',
  },
  {
    '""': '"156"',
    '"Rank"': '156',
    '"Player"': '"Rashid Shaheed"',
    '"POS"': '"WR"',
    '"Team"': '"NO"',
    '"PosRank"': '62',
    '"AVGRank"': '155',
    '"AVGTier"': '8',
    '"Siegele7.11"': '154',
    '"Curtis7.9"': '156',
  },
  {
    '""': '"157"',
    '"Rank"': '157',
    '"Player"': '"Van Jefferson"',
    '"POS"': '"WR"',
    '"Team"': '"LAR"',
    '"PosRank"': '63',
    '"AVGRank"': '156',
    '"AVGTier"': '8',
    '"Siegele7.11"': '155',
    '"Curtis7.9"': '157',
  },
  {
    '""': '"158"',
    '"Rank"': '158',
    '"Player"': '"Jeff Wilson"',
    '"POS"': '"RB"',
    '"Team"': '"MIA"',
    '"PosRank"': '53',
    '"AVGRank"': '160',
    '"AVGTier"': '8',
    '"Siegele7.11"': '160',
    '"Curtis7.9"': '160',
  },
  {
    '""': '"159"',
    '"Rank"': '159',
    '"Player"': '"Chase Brown"',
    '"POS"': '"RB"',
    '"Team"': '"CIN"',
    '"PosRank"': '54',
    '"AVGRank"': '160.5',
    '"AVGTier"': '8',
    '"Siegele7.11"': '162',
    '"Curtis7.9"': '159',
  },
  {
    '""': '"160"',
    '"Rank"': '160',
    '"Player"': '"Sam Howell"',
    '"POS"': '"QB"',
    '"Team"': '"WAS"',
    '"PosRank"': '22',
    '"AVGRank"': '161',
    '"AVGTier"': '8',
    '"Siegele7.11"': '164',
    '"Curtis7.9"': '158',
  },
  {
    '""': '"161"',
    '"Rank"': '161',
    '"Player"': '"Pierre Strong"',
    '"POS"': '"RB"',
    '"Team"': '"NE"',
    '"PosRank"': '55',
    '"AVGRank"': '161.5',
    '"AVGTier"': '8',
    '"Siegele7.11"': '161',
    '"Curtis7.9"': '162',
  },
  {
    '""': '"162"',
    '"Rank"': '162',
    '"Player"': '"JuJu Smith-Schuster"',
    '"POS"': '"WR"',
    '"Team"': '"NE"',
    '"PosRank"': '64',
    '"AVGRank"': '162',
    '"AVGTier"': '8',
    '"Siegele7.11"': '163',
    '"Curtis7.9"': '161',
  },
  {
    '""': '"163"',
    '"Rank"': '163',
    '"Player"': '"Rashee Rice"',
    '"POS"': '"WR"',
    '"Team"': '"KC"',
    '"PosRank"': '65',
    '"AVGRank"': '162',
    '"AVGTier"': '8',
    '"Siegele7.11"': '159',
    '"Curtis7.9"': '165',
  },
  {
    '""': '"164"',
    '"Rank"': '164',
    '"Player"': '"Bryce Young"',
    '"POS"': '"QB"',
    '"Team"': '"CAR"',
    '"PosRank"': '23',
    '"AVGRank"': '163',
    '"AVGTier"': '8',
    '"Siegele7.11"': '158',
    '"Curtis7.9"': '168',
  },
  {
    '""': '"165"',
    '"Rank"': '165',
    '"Player"': '"Darnell Mooney"',
    '"POS"': '"WR"',
    '"Team"': '"CHI"',
    '"PosRank"': '66',
    '"AVGRank"': '167.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '165',
    '"Curtis7.9"': '170',
  },
  {
    '""': '"166"',
    '"Rank"': '166',
    '"Player"': '"Mac Jones"',
    '"POS"': '"QB"',
    '"Team"': '"NE"',
    '"PosRank"': '24',
    '"AVGRank"': '168',
    '"AVGTier"': '9',
    '"Siegele7.11"': '173',
    '"Curtis7.9"': '163',
  },
  {
    '""': '"167"',
    '"Rank"': '167',
    '"Player"': '"Wan\'Dale Robinson"',
    '"POS"': '"WR"',
    '"Team"': '"NYG"',
    '"PosRank"': '67',
    '"AVGRank"': '169',
    '"AVGTier"': '9',
    '"Siegele7.11"': '171',
    '"Curtis7.9"': '167',
  },
  {
    '""': '"168"',
    '"Rank"': '168',
    '"Player"': '"Dawson Knox"',
    '"POS"': '"TE"',
    '"Team"': '"BUF"',
    '"PosRank"': '22',
    '"AVGRank"': '169.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '175',
    '"Curtis7.9"': '164',
  },
  {
    '""': '"169"',
    '"Rank"': '169',
    '"Player"': '"Matthew Stafford"',
    '"POS"': '"QB"',
    '"Team"': '"LAR"',
    '"PosRank"': '25',
    '"AVGRank"': '170.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '166',
    '"Curtis7.9"': '175',
  },
  {
    '""': '"170"',
    '"Rank"': '170',
    '"Player"': '"Hunter Henry"',
    '"POS"': '"TE"',
    '"Team"': '"NE"',
    '"PosRank"': '23',
    '"AVGRank"': '170.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '168',
    '"Curtis7.9"': '173',
  },
  {
    '""': '"171"',
    '"Rank"': '171',
    '"Player"': '"Brock Purdy"',
    '"POS"': '"QB"',
    '"Team"': '"SF"',
    '"PosRank"': '26',
    '"AVGRank"': '172',
    '"AVGTier"': '9',
    '"Siegele7.11"': '170',
    '"Curtis7.9"': '174',
  },
  {
    '""': '"172"',
    '"Rank"': '172',
    '"Player"': '"Juwan Johnson"',
    '"POS"': '"TE"',
    '"Team"': '"NO"',
    '"PosRank"': '24',
    '"AVGRank"': '172.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '176',
    '"Curtis7.9"': '169',
  },
  {
    '""': '"173"',
    '"Rank"': '173',
    '"Player"': '"Jerome Ford"',
    '"POS"': '"RB"',
    '"Team"': '"CLE"',
    '"PosRank"': '56',
    '"AVGRank"': '173',
    '"AVGTier"': '9',
    '"Siegele7.11"': '174',
    '"Curtis7.9"': '172',
  },
  {
    '""': '"174"',
    '"Rank"': '174',
    '"Player"': '"Isaiah Hodgins"',
    '"POS"': '"WR"',
    '"Team"': '"NYG"',
    '"PosRank"': '68',
    '"AVGRank"': '174',
    '"AVGTier"': '9',
    '"Siegele7.11"': '182',
    '"Curtis7.9"': '166',
  },
  {
    '""': '"175"',
    '"Rank"': '175',
    '"Player"': '"DJ Chark"',
    '"POS"': '"WR"',
    '"Team"': '"CAR"',
    '"PosRank"': '69',
    '"AVGRank"': '174',
    '"AVGTier"': '9',
    '"Siegele7.11"': '169',
    '"Curtis7.9"': '179',
  },
  {
    '""': '"176"',
    '"Rank"': '176',
    '"Player"': '"Khalil Shakir"',
    '"POS"': '"WR"',
    '"Team"': '"BUF"',
    '"PosRank"': '70',
    '"AVGRank"': '177',
    '"AVGTier"': '9',
    '"Siegele7.11"': '177',
    '"Curtis7.9"': '177',
  },
  {
    '""': '"177"',
    '"Rank"': '177',
    '"Player"': '"Jonathan Mingo"',
    '"POS"': '"WR"',
    '"Team"': '"CAR"',
    '"PosRank"': '71',
    '"AVGRank"': '175.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '167',
    '"Curtis7.9"': '184',
  },
  {
    '""': '"178"',
    '"Rank"': '178',
    '"Player"': '"Desmond Ridder"',
    '"POS"': '"QB"',
    '"Team"': '"ATL"',
    '"PosRank"': '27',
    '"AVGRank"': '179',
    '"AVGTier"': '9',
    '"Siegele7.11"': '187',
    '"Curtis7.9"': '171',
  },
  {
    '""': '"179"',
    '"Rank"': '179',
    '"Player"': '"D\'Onta Foreman"',
    '"POS"': '"RB"',
    '"Team"': '"CHI"',
    '"PosRank"': '57',
    '"AVGRank"': '180',
    '"AVGTier"': '9',
    '"Siegele7.11"': '180',
    '"Curtis7.9"': '180',
  },
  {
    '""': '"180"',
    '"Rank"': '180',
    '"Player"': '"Gerald Everett"',
    '"POS"': '"TE"',
    '"Team"': '"LAC"',
    '"PosRank"': '25',
    '"AVGRank"': '180.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '179',
    '"Curtis7.9"': '182',
  },
  {
    '""': '"181"',
    '"Rank"': '181',
    '"Player"': '"Israel Abanikanda"',
    '"POS"': '"RB"',
    '"Team"': '"NYJ"',
    '"PosRank"': '58',
    '"AVGRank"': '180.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '185',
    '"Curtis7.9"': '176',
  },
  {
    '""': '"182"',
    '"Rank"': '182',
    '"Player"': '"Ty Chandler"',
    '"POS"': '"RB"',
    '"Team"': '"MIN"',
    '"PosRank"': '59',
    '"AVGRank"': '180.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '183',
    '"Curtis7.9"': '178',
  },
  {
    '""': '"183"',
    '"Rank"': '183',
    '"Player"': '"Marquez Valdes-Scantling"',
    '"POS"': '"WR"',
    '"Team"': '"KC"',
    '"PosRank"': '72',
    '"AVGRank"': '181',
    '"AVGTier"': '9',
    '"Siegele7.11"': '172',
    '"Curtis7.9"': '190',
  },
  {
    '""': '"184"',
    '"Rank"': '184',
    '"Player"': '"Luke Musgrave"',
    '"POS"': '"TE"',
    '"Team"': '"GB"',
    '"PosRank"': '26',
    '"AVGRank"': '181.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '178',
    '"Curtis7.9"': '185',
  },
  {
    '""': '"185"',
    '"Rank"': '185',
    '"Player"': '"Jalin Hyatt"',
    '"POS"': '"WR"',
    '"Team"': '"NYG"',
    '"PosRank"': '73',
    '"AVGRank"': '182',
    '"AVGTier"': '9',
    '"Siegele7.11"': '181',
    '"Curtis7.9"': '183',
  },
  {
    '""': '"186"',
    '"Rank"': '186',
    '"Player"': '"John Metchie"',
    '"POS"': '"WR"',
    '"Team"': '"HOU"',
    '"PosRank"': '74',
    '"AVGRank"': '182.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '184',
    '"Curtis7.9"': '181',
  },
  {
    '""': '"187"',
    '"Rank"': '187',
    '"Player"': '"Derek Carr"',
    '"POS"': '"QB"',
    '"Team"': '"NO"',
    '"PosRank"': '28',
    '"AVGRank"': '187.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '188',
    '"Curtis7.9"': '187',
  },
  {
    '""': '"188"',
    '"Rank"': '188',
    '"Player"': '"C.J. Stroud"',
    '"POS"': '"QB"',
    '"Team"': '"HOU"',
    '"PosRank"': '29',
    '"AVGRank"': '188.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '186',
    '"Curtis7.9"': '191',
  },
  {
    '""': '"189"',
    '"Rank"': '189',
    '"Player"': '"Taysom Hill"',
    '"POS"': '"TE"',
    '"Team"': '"NO"',
    '"PosRank"': '27',
    '"AVGRank"': '188.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '189',
    '"Curtis7.9"': '188',
  },
  {
    '""': '"190"',
    '"Rank"': '190',
    '"Player"': '"Noah Fant"',
    '"POS"': '"TE"',
    '"Team"': '"SEA"',
    '"PosRank"': '28',
    '"AVGRank"': '189',
    '"AVGTier"': '9',
    '"Siegele7.11"': '192',
    '"Curtis7.9"': '186',
  },
  {
    '""': '"191"',
    '"Rank"': '191',
    '"Player"': '"Parris Campbell"',
    '"POS"': '"WR"',
    '"Team"': '"NYG"',
    '"PosRank"': '75',
    '"AVGRank"': '191.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '191',
    '"Curtis7.9"': '192',
  },
  {
    '""': '"192"',
    '"Rank"': '192',
    '"Player"': '"DeWayne McBride"',
    '"POS"': '"RB"',
    '"Team"': '"MIN"',
    '"PosRank"': '60',
    '"AVGRank"': '192',
    '"AVGTier"': '9',
    '"Siegele7.11"': '195',
    '"Curtis7.9"': '189',
  },
  {
    '""': '"193"',
    '"Rank"': '193',
    '"Player"': '"Logan Thomas"',
    '"POS"': '"TE"',
    '"Team"': '"WAS"',
    '"PosRank"': '29',
    '"AVGRank"': '192.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '190',
    '"Curtis7.9"': '195',
  },
  {
    '""': '"194"',
    '"Rank"': '194',
    '"Player"': '"Jelani Woods"',
    '"POS"': '"TE"',
    '"Team"': '"IND"',
    '"PosRank"': '30',
    '"AVGRank"': '193.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '193',
    '"Curtis7.9"': '194',
  },
  {
    '""': '"195"',
    '"Rank"': '195',
    '"Player"': '"Zamir White"',
    '"POS"': '"RB"',
    '"Team"': '"LV"',
    '"PosRank"': '61',
    '"AVGRank"': '195',
    '"AVGTier"': '9',
    '"Siegele7.11"': '194',
    '"Curtis7.9"': '196',
  },
  {
    '""': '"196"',
    '"Rank"': '196',
    '"Player"': '"K.J. Osborn"',
    '"POS"': '"WR"',
    '"Team"': '"MIN"',
    '"PosRank"': '76',
    '"AVGRank"': '197',
    '"AVGTier"': '9',
    '"Siegele7.11"': '197',
    '"Curtis7.9"': '197',
  },
  {
    '""': '"197"',
    '"Rank"': '197',
    '"Player"': '"Isaiah Likely"',
    '"POS"': '"TE"',
    '"Team"': '"BAL"',
    '"PosRank"': '31',
    '"AVGRank"': '200',
    '"AVGTier"': '9',
    '"Siegele7.11"': '200',
    '"Curtis7.9"': '200',
  },
  {
    '""': '"198"',
    '"Rank"': '198',
    '"Player"': '"Michael Gallup"',
    '"POS"': '"WR"',
    '"Team"': '"DAL"',
    '"PosRank"': '77',
    '"AVGRank"': '200',
    '"AVGTier"': '9',
    '"Siegele7.11"': '207',
    '"Curtis7.9"': '193',
  },
  {
    '""': '"199"',
    '"Rank"': '199',
    '"Player"': '"Jayden Reed"',
    '"POS"': '"WR"',
    '"Team"': '"GB"',
    '"PosRank"': '78',
    '"AVGRank"': '199',
    '"AVGTier"': '9',
    '"Siegele7.11"': '199',
    '"Curtis7.9"': '199',
  },
  {
    '""': '"200"',
    '"Rank"': '200',
    '"Player"': '"Leonard Fournette"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '62',
    '"AVGRank"': '201',
    '"AVGTier"': '9',
    '"Siegele7.11"': '201',
    '"Curtis7.9"': '201',
  },
  {
    '""': '"201"',
    '"Rank"': '201',
    '"Player"': '"Zach Evans"',
    '"POS"': '"RB"',
    '"Team"': '"LAR"',
    '"PosRank"': '63',
    '"AVGRank"': '201',
    '"AVGTier"': '9',
    '"Siegele7.11"': '204',
    '"Curtis7.9"': '198',
  },
  {
    '""': '"202"',
    '"Rank"': '202',
    '"Player"': '"Robert Woods"',
    '"POS"': '"WR"',
    '"Team"': '"HOU"',
    '"PosRank"': '79',
    '"AVGRank"': '202',
    '"AVGTier"': '9',
    '"Siegele7.11"': '202',
    '"Curtis7.9"': '202',
  },
  {
    '""': '"203"',
    '"Rank"': '203',
    '"Player"': '"Hayden Hurst"',
    '"POS"': '"TE"',
    '"Team"': '"CAR"',
    '"PosRank"': '32',
    '"AVGRank"': '203',
    '"AVGTier"': '10',
    '"Siegele7.11"': '203',
    '"Curtis7.9"': '203',
  },
  {
    '""': '"204"',
    '"Rank"': '204',
    '"Player"': '"Adam Thielen"',
    '"POS"': '"WR"',
    '"Team"': '"CAR"',
    '"PosRank"': '80',
    '"AVGRank"': '204.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '205',
    '"Curtis7.9"': '204',
  },
  {
    '""': '"205"',
    '"Rank"': '205',
    '"Player"': '"Nathaniel Dell"',
    '"POS"': '"WR"',
    '"Team"': '""',
    '"PosRank"': '81',
    '"AVGRank"': '205.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '198',
    '"Curtis7.9"': '213',
  },
  {
    '""': '"206"',
    '"Rank"': '206',
    '"Player"': '"Jimmy Garoppolo"',
    '"POS"': '"QB"',
    '"Team"': '"LV"',
    '"PosRank"': '30',
    '"AVGRank"': '206',
    '"AVGTier"': '10',
    '"Siegele7.11"': '206',
    '"Curtis7.9"': '206',
  },
  {
    '""': '"207"',
    '"Rank"': '207',
    '"Player"': '"Michael Wilson"',
    '"POS"': '"WR"',
    '"Team"': '"ARI"',
    '"PosRank"': '82',
    '"AVGRank"': '207.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '210',
    '"Curtis7.9"': '205',
  },
  {
    '""': '"208"',
    '"Rank"': '208',
    '"Player"': '"Kareem Hunt"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '64',
    '"AVGRank"': '208',
    '"AVGTier"': '10',
    '"Siegele7.11"': '208',
    '"Curtis7.9"': '208',
  },
  {
    '""': '"209"',
    '"Rank"': '209',
    '"Player"': '"Joshua Palmer"',
    '"POS"': '"WR"',
    '"Team"': '"LAC"',
    '"PosRank"': '83',
    '"AVGRank"': '209',
    '"AVGTier"': '10',
    '"Siegele7.11"': '209',
    '"Curtis7.9"': '209',
  },
  {
    '""': '"210"',
    '"Rank"': '210',
    '"Player"': '"Clyde Edwards-Helaire"',
    '"POS"': '"RB"',
    '"Team"': '"KC"',
    '"PosRank"': '65',
    '"AVGRank"': '211',
    '"AVGTier"': '10',
    '"Siegele7.11"': '211',
    '"Curtis7.9"': '211',
  },
  {
    '""': '"211"',
    '"Rank"': '211',
    '"Player"': '"Hunter Renfrow"',
    '"POS"': '"WR"',
    '"Team"': '"LV"',
    '"PosRank"': '84',
    '"AVGRank"': '212',
    '"AVGTier"': '10',
    '"Siegele7.11"': '212',
    '"Curtis7.9"': '212',
  },
  {
    '""': '"212"',
    '"Rank"': '212',
    '"Player"': '"Sean Tucker"',
    '"POS"': '"RB"',
    '"Team"': '"TB"',
    '"PosRank"': '66',
    '"AVGRank"': '213.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '213',
    '"Curtis7.9"': '214',
  },
  {
    '""': '"213"',
    '"Rank"': '213',
    '"Player"': '"Tim Patrick"',
    '"POS"': '"WR"',
    '"Team"': '"DEN"',
    '"PosRank"': '85',
    '"AVGRank"': '213.5',
    '"AVGTier"': '9',
    '"Siegele7.11"': '196',
    '"Curtis7.9"': '231',
  },
  {
    '""': '"214"',
    '"Rank"': '214',
    '"Player"': '"Richie James"',
    '"POS"': '"WR"',
    '"Team"': '"KC"',
    '"PosRank"': '86',
    '"AVGRank"': '214.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '214',
    '"Curtis7.9"': '215',
  },
  {
    '""': '"215"',
    '"Rank"': '215',
    '"Player"': '"Deuce Vaughn"',
    '"POS"': '"RB"',
    '"Team"': '"DAL"',
    '"PosRank"': '67',
    '"AVGRank"': '216',
    '"AVGTier"': '10',
    '"Siegele7.11"': '215',
    '"Curtis7.9"': '217',
  },
  {
    '""': '"216"',
    '"Rank"': '216',
    '"Player"': '"Chase Claypool"',
    '"POS"': '"WR"',
    '"Team"': '"CHI"',
    '"PosRank"': '87',
    '"AVGRank"': '217',
    '"AVGTier"': '10',
    '"Siegele7.11"': '216',
    '"Curtis7.9"': '218',
  },
  {
    '""': '"217"',
    '"Rank"': '217',
    '"Player"': '"Donovan Peoples-Jones"',
    '"POS"': '"WR"',
    '"Team"': '"CLE"',
    '"PosRank"': '88',
    '"AVGRank"': '218',
    '"AVGTier"': '10',
    '"Siegele7.11"': '229',
    '"Curtis7.9"': '207',
  },
  {
    '""': '"218"',
    '"Rank"': '218',
    '"Player"': '"Cordarrelle Patterson"',
    '"POS"': '"RB"',
    '"Team"': '"ATL"',
    '"PosRank"': '68',
    '"AVGRank"': '219',
    '"AVGTier"': '10',
    '"Siegele7.11"': '219',
    '"Curtis7.9"': '219',
  },
  {
    '""': '"219"',
    '"Rank"': '219',
    '"Player"': '"Jake Ferguson"',
    '"POS"': '"TE"',
    '"Team"': '"DAL"',
    '"PosRank"': '33',
    '"AVGRank"': '219.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '217',
    '"Curtis7.9"': '222',
  },
  {
    '""': '"220"',
    '"Rank"': '220',
    '"Player"': '"Ezekiel Elliott"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '69',
    '"AVGRank"': '220.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '231',
    '"Curtis7.9"': '210',
  },
  {
    '""': '"221"',
    '"Rank"': '221',
    '"Player"': '"Tyler Conklin"',
    '"POS"': '"TE"',
    '"Team"': '"NYJ"',
    '"PosRank"': '34',
    '"AVGRank"': '220.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '221',
    '"Curtis7.9"': '220',
  },
  {
    '""': '"222"',
    '"Rank"': '222',
    '"Player"': '"DeVante Parker"',
    '"POS"': '"WR"',
    '"Team"': '"NE"',
    '"PosRank"': '89',
    '"AVGRank"': '222',
    '"AVGTier"': '10',
    '"Siegele7.11"': '218',
    '"Curtis7.9"': '226',
  },
  {
    '""': '"223"',
    '"Rank"': '223',
    '"Player"': '"Terrace Marshall"',
    '"POS"': '"WR"',
    '"Team"': '"CAR"',
    '"PosRank"': '90',
    '"AVGRank"': '222.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '224',
    '"Curtis7.9"': '221',
  },
  {
    '""': '"224"',
    '"Rank"': '224',
    '"Player"': '"Zach Ertz"',
    '"POS"': '"TE"',
    '"Team"': '"ARI"',
    '"PosRank"': '35',
    '"AVGRank"': '224',
    '"AVGTier"': '10',
    '"Siegele7.11"': '225',
    '"Curtis7.9"': '223',
  },
  {
    '""': '"225"',
    '"Rank"': '225',
    '"Player"': '"Kenneth Gainwell"',
    '"POS"': '"RB"',
    '"Team"': '"PHI"',
    '"PosRank"': '70',
    '"AVGRank"': '224.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '220',
    '"Curtis7.9"': '229',
  },
  {
    '""': '"226"',
    '"Rank"': '226',
    '"Player"': '"Cedric Tillman"',
    '"POS"': '"WR"',
    '"Team"': '"CLE"',
    '"PosRank"': '91',
    '"AVGRank"': '224.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '233',
    '"Curtis7.9"': '216',
  },
  {
    '""': '"227"',
    '"Rank"': '227',
    '"Player"': '"Josh Downs"',
    '"POS"': '"WR"',
    '"Team"': '"IND"',
    '"PosRank"': '92',
    '"AVGRank"': '225',
    '"AVGTier"': '10',
    '"Siegele7.11"': '226',
    '"Curtis7.9"': '224',
  },
  {
    '""': '"228"',
    '"Rank"': '228',
    '"Player"': '"Ryan Tannehill"',
    '"POS"': '"QB"',
    '"Team"': '"TEN"',
    '"PosRank"': '31',
    '"AVGRank"': '226',
    '"AVGTier"': '10',
    '"Siegele7.11"': '227',
    '"Curtis7.9"': '225',
  },
  {
    '""': '"229"',
    '"Rank"': '229',
    '"Player"': '"Marvin Jones"',
    '"POS"': '"WR"',
    '"Team"': '"DET"',
    '"PosRank"': '93',
    '"AVGRank"': '227.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '228',
    '"Curtis7.9"': '227',
  },
  {
    '""': '"230"',
    '"Rank"': '230',
    '"Player"': '"Alec Pierce"',
    '"POS"': '"WR"',
    '"Team"': '"IND"',
    '"PosRank"': '94',
    '"AVGRank"': '230',
    '"AVGTier"': '10',
    '"Siegele7.11"': '230',
    '"Curtis7.9"': '230',
  },
  {
    '""': '"231"',
    '"Rank"': '231',
    '"Player"': '"Albert Okwuegbunam"',
    '"POS"': '"TE"',
    '"Team"': '"DEN"',
    '"PosRank"': '36',
    '"AVGRank"': '230',
    '"AVGTier"': '10',
    '"Siegele7.11"': '223',
    '"Curtis7.9"': '237',
  },
  {
    '""': '"232"',
    '"Rank"': '232',
    '"Player"': '"Baker Mayfield"',
    '"POS"': '"QB"',
    '"Team"': '"TB"',
    '"PosRank"': '32',
    '"AVGRank"': '232',
    '"AVGTier"': '10',
    '"Siegele7.11"': '222',
    '"Curtis7.9"': '242',
  },
  {
    '""': '"233"',
    '"Rank"': '233',
    '"Player"': '"Boston Scott"',
    '"POS"': '"RB"',
    '"Team"': '"PHI"',
    '"PosRank"': '71',
    '"AVGRank"': '232.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '232',
    '"Curtis7.9"': '233',
  },
  {
    '""': '"234"',
    '"Rank"': '234',
    '"Player"': '"Jeremy Ruckert"',
    '"POS"': '"TE"',
    '"Team"': '"NYJ"',
    '"PosRank"': '37',
    '"AVGRank"': '235',
    '"AVGTier"': '10',
    '"Siegele7.11"': '234',
    '"Curtis7.9"': '236',
  },
  {
    '""': '"235"',
    '"Rank"': '235',
    '"Player"': '"Cade Otton"',
    '"POS"': '"TE"',
    '"Team"': '"TB"',
    '"PosRank"': '38',
    '"AVGRank"': '236',
    '"AVGTier"': '10',
    '"Siegele7.11"': '240',
    '"Curtis7.9"': '232',
  },
  {
    '""': '"236"',
    '"Rank"': '236',
    '"Player"': '"Michael Carter"',
    '"POS"': '"RB"',
    '"Team"': '"NYJ"',
    '"PosRank"': '72',
    '"AVGRank"': '238',
    '"AVGTier"': '10',
    '"Siegele7.11"': '236',
    '"Curtis7.9"': '240',
  },
  {
    '""': '"237"',
    '"Rank"': '237',
    '"Player"': '"Mecole Hardman"',
    '"POS"': '"WR"',
    '"Team"': '"NYJ"',
    '"PosRank"': '95',
    '"AVGRank"': '239.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '238',
    '"Curtis7.9"': '241',
  },
  {
    '""': '"238"',
    '"Rank"': '238',
    '"Player"': '"Allen Robinson"',
    '"POS"': '"WR"',
    '"Team"': '"PIT"',
    '"PosRank"': '96',
    '"AVGRank"': '239.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '251',
    '"Curtis7.9"': '228',
  },
  {
    '""': '"239"',
    '"Rank"': '239',
    '"Player"': '"Laviska Shenault"',
    '"POS"': '"WR"',
    '"Team"': '"CAR"',
    '"PosRank"': '97',
    '"AVGRank"': '240',
    '"AVGTier"': '10',
    '"Siegele7.11"': '235',
    '"Curtis7.9"': '245',
  },
  {
    '""': '"240"',
    '"Rank"': '240',
    '"Player"': '"Corey Davis"',
    '"POS"': '"WR"',
    '"Team"': '"NYJ"',
    '"PosRank"': '98',
    '"AVGRank"': '241',
    '"AVGTier"': '10',
    '"Siegele7.11"': '239',
    '"Curtis7.9"': '243',
  },
  {
    '""': '"241"',
    '"Rank"': '241',
    '"Player"': '"Eric Gray"',
    '"POS"': '"RB"',
    '"Team"': '"NYG"',
    '"PosRank"': '73',
    '"AVGRank"': '241.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '244',
    '"Curtis7.9"': '239',
  },
  {
    '""': '"242"',
    '"Rank"': '242',
    '"Player"': '"Russell Gage"',
    '"POS"': '"WR"',
    '"Team"': '"TB"',
    '"PosRank"': '99',
    '"AVGRank"': '241.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '249',
    '"Curtis7.9"': '234',
  },
  {
    '""': '"243"',
    '"Rank"': '243',
    '"Player"': '"Chase Edmonds"',
    '"POS"': '"RB"',
    '"Team"': '"TB"',
    '"PosRank"': '74',
    '"AVGRank"': '242',
    '"AVGTier"': '10',
    '"Siegele7.11"': '237',
    '"Curtis7.9"': '247',
  },
  {
    '""': '"244"',
    '"Rank"': '244',
    '"Player"': '"Jordan Mason"',
    '"POS"': '"RB"',
    '"Team"': '"SF"',
    '"PosRank"': '75',
    '"AVGRank"': '243.5',
    '"AVGTier"': '11',
    '"Siegele7.11"': '241',
    '"Curtis7.9"': '246',
  },
  {
    '""': '"245"',
    '"Rank"': '245',
    '"Player"': '"Darnell Washington"',
    '"POS"': '"TE"',
    '"Team"': '"PIT"',
    '"PosRank"': '39',
    '"AVGRank"': '245',
    '"AVGTier"': '11',
    '"Siegele7.11"': '242',
    '"Curtis7.9"': '248',
  },
  {
    '""': '"246"',
    '"Rank"': '246',
    '"Player"': '"Evan Hull"',
    '"POS"': '"RB"',
    '"Team"': '"IND"',
    '"PosRank"': '76',
    '"AVGRank"': '247.5',
    '"AVGTier"': '11',
    '"Siegele7.11"': '245',
    '"Curtis7.9"': '250',
  },
  {
    '""': '"247"',
    '"Rank"': '247',
    '"Player"': '"Tucker Kraft"',
    '"POS"': '"TE"',
    '"Team"': '"GB"',
    '"PosRank"': '40',
    '"AVGRank"': '248',
    '"AVGTier"': '11',
    '"Siegele7.11"': '243',
    '"Curtis7.9"': '253',
  },
  {
    '""': '"248"',
    '"Rank"': '248',
    '"Player"': '"Will Levis"',
    '"POS"': '"QB"',
    '"Team"': '"TEN"',
    '"PosRank"': '33',
    '"AVGRank"': '248.5',
    '"AVGTier"': '10',
    '"Siegele7.11"': '259',
    '"Curtis7.9"': '238',
  },
  {
    '""': '"249"',
    '"Rank"': '249',
    '"Player"': '"Hassan Haskins"',
    '"POS"': '"RB"',
    '"Team"': '"TEN"',
    '"PosRank"': '77',
    '"AVGRank"': '248.5',
    '"AVGTier"': '11',
    '"Siegele7.11"': '246',
    '"Curtis7.9"': '251',
  },
  {
    '""': '"250"',
    '"Rank"': '250',
    '"Player"': '"Trey Palmer"',
    '"POS"': '"WR"',
    '"Team"': '"TB"',
    '"PosRank"': '100',
    '"AVGRank"': '249.5',
    '"AVGTier"': '11',
    '"Siegele7.11"': '247',
    '"Curtis7.9"': '252',
  },
];

module.exports = rvRedraftRankingsTEP;
