const rvRedraftRankingsTEP = [
  {
    '""': '"1"',
    '"Rank"': '1',
    '"Player"': '"Christian McCaffrey"',
    '"POS"': '"RB"',
    '"Team"': '"SF"',
    '"PosRank"': '1',
    '"AVGRank"': '1',
    '"AVGTier"': '1',
    '"Siegele3.2"': '1',
    '"Caban3.16"': '1',
  },
  {
    '""': '"2"',
    '"Rank"': '2',
    '"Player"': '"Tyreek Hill"',
    '"POS"': '"WR"',
    '"Team"': '"MIA"',
    '"PosRank"': '1',
    '"AVGRank"': '2.5',
    '"AVGTier"': '1',
    '"Siegele3.2"': '3',
    '"Caban3.16"': '2',
  },
  {
    '""': '"3"',
    '"Rank"': '3',
    '"Player"': '"CeeDee Lamb"',
    '"POS"': '"WR"',
    '"Team"': '"DAL"',
    '"PosRank"': '2',
    '"AVGRank"': '2.5',
    '"AVGTier"': '1',
    '"Siegele3.2"': '2',
    '"Caban3.16"': '3',
  },
  {
    '""': '"4"',
    '"Rank"': '4',
    '"Player"': '"Ja\'Marr Chase"',
    '"POS"': '"WR"',
    '"Team"': '"CIN"',
    '"PosRank"': '3',
    '"AVGRank"': '4',
    '"AVGTier"': '1',
    '"Siegele3.2"': '4',
    '"Caban3.16"': '4',
  },
  {
    '""': '"5"',
    '"Rank"': '5',
    '"Player"': '"Amon-Ra St. Brown"',
    '"POS"': '"WR"',
    '"Team"': '"DET"',
    '"PosRank"': '4',
    '"AVGRank"': '5',
    '"AVGTier"': '1',
    '"Siegele3.2"': '5',
    '"Caban3.16"': '5',
  },
  {
    '""': '"6"',
    '"Rank"': '6',
    '"Player"': '"Justin Jefferson"',
    '"POS"': '"WR"',
    '"Team"': '"MIN"',
    '"PosRank"': '5',
    '"AVGRank"': '6.5',
    '"AVGTier"': '1',
    '"Siegele3.2"': '7',
    '"Caban3.16"': '6',
  },
  {
    '""': '"7"',
    '"Rank"': '7',
    '"Player"': '"Breece Hall"',
    '"POS"': '"RB"',
    '"Team"': '"NYJ"',
    '"PosRank"': '2',
    '"AVGRank"': '6.5',
    '"AVGTier"': '1',
    '"Siegele3.2"': '6',
    '"Caban3.16"': '7',
  },
  {
    '""': '"8"',
    '"Rank"': '8',
    '"Player"': '"Bijan Robinson"',
    '"POS"': '"RB"',
    '"Team"': '"ATL"',
    '"PosRank"': '3',
    '"AVGRank"': '9',
    '"AVGTier"': '1',
    '"Siegele3.2"': '9',
    '"Caban3.16"': '9',
  },
  {
    '""': '"9"',
    '"Rank"': '9',
    '"Player"': '"Garrett Wilson"',
    '"POS"': '"WR"',
    '"Team"': '"NYJ"',
    '"PosRank"': '6',
    '"AVGRank"': '9',
    '"AVGTier"': '1',
    '"Siegele3.2"': '8',
    '"Caban3.16"': '10',
  },
  {
    '""': '"10"',
    '"Rank"': '10',
    '"Player"': '"Puka Nacua"',
    '"POS"': '"WR"',
    '"Team"': '"LAR"',
    '"PosRank"': '7',
    '"AVGRank"': '9',
    '"AVGTier"': '1',
    '"Siegele3.2"': '10',
    '"Caban3.16"': '8',
  },
  {
    '""': '"11"',
    '"Rank"': '11',
    '"Player"': '"A.J. Brown"',
    '"POS"': '"WR"',
    '"Team"': '"PHI"',
    '"PosRank"': '8',
    '"AVGRank"': '12',
    '"AVGTier"': '2',
    '"Siegele3.2"': '13',
    '"Caban3.16"': '11',
  },
  {
    '""': '"12"',
    '"Rank"': '12',
    '"Player"': '"Kyren Williams"',
    '"POS"': '"RB"',
    '"Team"': '"LAR"',
    '"PosRank"': '4',
    '"AVGRank"': '12',
    '"AVGTier"': '2',
    '"Siegele3.2"': '12',
    '"Caban3.16"': '12',
  },
  {
    '""': '"13"',
    '"Rank"': '13',
    '"Player"': '"Sam LaPorta"',
    '"POS"': '"TE"',
    '"Team"': '"DET"',
    '"PosRank"': '1',
    '"AVGRank"': '12',
    '"AVGTier"': '2',
    '"Siegele3.2"': '11',
    '"Caban3.16"': '13',
  },
  {
    '""': '"14"',
    '"Rank"': '14',
    '"Player"': '"Jonathan Taylor"',
    '"POS"': '"RB"',
    '"Team"': '"IND"',
    '"PosRank"': '5',
    '"AVGRank"': '14.5',
    '"AVGTier"': '2',
    '"Siegele3.2"': '14',
    '"Caban3.16"': '15',
  },
  {
    '""': '"15"',
    '"Rank"': '15',
    '"Player"': '"Jahmyr Gibbs"',
    '"POS"': '"RB"',
    '"Team"': '"DET"',
    '"PosRank"': '6',
    '"AVGRank"': '15.5',
    '"AVGTier"': '2',
    '"Siegele3.2"': '17',
    '"Caban3.16"': '14',
  },
  {
    '""': '"16"',
    '"Rank"': '16',
    '"Player"': '"Trey McBride"',
    '"POS"': '"TE"',
    '"Team"': '"ARI"',
    '"PosRank"': '2',
    '"AVGRank"': '17.5',
    '"AVGTier"': '2',
    '"Siegele3.2"': '15',
    '"Caban3.16"': '20',
  },
  {
    '""': '"17"',
    '"Rank"': '17',
    '"Player"': '"Nico Collins"',
    '"POS"': '"WR"',
    '"Team"': '"HOU"',
    '"PosRank"': '9',
    '"AVGRank"': '18',
    '"AVGTier"': '2',
    '"Siegele3.2"': '18',
    '"Caban3.16"': '18',
  },
  {
    '""': '"18"',
    '"Rank"': '18',
    '"Player"': '"Devon Achane"',
    '"POS"': '"RB"',
    '"Team"': '"MIA"',
    '"PosRank"': '7',
    '"AVGRank"': '18.5',
    '"AVGTier"': '2',
    '"Siegele3.2"': '20',
    '"Caban3.16"': '17',
  },
  {
    '""': '"19"',
    '"Rank"': '19',
    '"Player"': '"Rashee Rice"',
    '"POS"': '"WR"',
    '"Team"': '"KC"',
    '"PosRank"': '10',
    '"AVGRank"': '18.5',
    '"AVGTier"': '2',
    '"Siegele3.2"': '16',
    '"Caban3.16"': '21',
  },
  {
    '""': '"20"',
    '"Rank"': '20',
    '"Player"': '"Travis Kelce"',
    '"POS"': '"TE"',
    '"Team"': '"KC"',
    '"PosRank"': '3',
    '"AVGRank"': '19',
    '"AVGTier"': '2',
    '"Siegele3.2"': '22',
    '"Caban3.16"': '16',
  },
  {
    '""': '"21"',
    '"Rank"': '21',
    '"Player"': '"Chris Olave"',
    '"POS"': '"WR"',
    '"Team"': '"NO"',
    '"PosRank"': '11',
    '"AVGRank"': '21.5',
    '"AVGTier"': '2',
    '"Siegele3.2"': '21',
    '"Caban3.16"': '22',
  },
  {
    '""': '"22"',
    '"Rank"': '22',
    '"Player"': '"Jaylen Waddle"',
    '"POS"': '"WR"',
    '"Team"': '"MIA"',
    '"PosRank"': '12',
    '"AVGRank"': '23',
    '"AVGTier"': '2',
    '"Siegele3.2"': '23',
    '"Caban3.16"': '23',
  },
  {
    '""': '"23"',
    '"Rank"': '23',
    '"Player"': '"Marvin Harrison Jr."',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '13',
    '"AVGRank"': '23',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '27',
    '"Caban3.16"': '19',
  },
  {
    '""': '"24"',
    '"Rank"': '24',
    '"Player"': '"Travis Etienne"',
    '"POS"': '"RB"',
    '"Team"': '"JAC"',
    '"PosRank"': '8',
    '"AVGRank"': '24',
    '"AVGTier"': '2',
    '"Siegele3.2"': '24',
    '"Caban3.16"': '24',
  },
  {
    '""': '"25"',
    '"Rank"': '25',
    '"Player"': '"Dalton Kincaid"',
    '"POS"': '"TE"',
    '"Team"': '"BUF"',
    '"PosRank"': '4',
    '"AVGRank"': '27',
    '"AVGTier"': '2',
    '"Siegele3.2"': '28',
    '"Caban3.16"': '26',
  },
  {
    '""': '"26"',
    '"Rank"': '26',
    '"Player"': '"Josh Allen"',
    '"POS"': '"QB"',
    '"Team"': '"BUF"',
    '"PosRank"': '1',
    '"AVGRank"': '27.5',
    '"AVGTier"': '2',
    '"Siegele3.2"': '25',
    '"Caban3.16"': '30',
  },
  {
    '""': '"27"',
    '"Rank"': '27',
    '"Player"': '"Tank Dell"',
    '"POS"': '"WR"',
    '"Team"': '"HOU"',
    '"PosRank"': '14',
    '"AVGRank"': '28',
    '"AVGTier"': '2',
    '"Siegele3.2"': '19',
    '"Caban3.16"': '37',
  },
  {
    '""': '"28"',
    '"Rank"': '28',
    '"Player"': '"Mike Evans"',
    '"POS"': '"WR"',
    '"Team"': '"TB"',
    '"PosRank"': '15',
    '"AVGRank"': '28.5',
    '"AVGTier"': '2',
    '"Siegele3.2"': '29',
    '"Caban3.16"': '28',
  },
  {
    '""': '"29"',
    '"Rank"': '29',
    '"Player"': '"Brandon Aiyuk"',
    '"POS"': '"WR"',
    '"Team"': '"SF"',
    '"PosRank"': '16',
    '"AVGRank"': '29',
    '"AVGTier"': '2',
    '"Siegele3.2"': '31',
    '"Caban3.16"': '27',
  },
  {
    '""': '"30"',
    '"Rank"': '30',
    '"Player"': '"DJ Moore"',
    '"POS"': '"WR"',
    '"Team"': '"CHI"',
    '"PosRank"': '17',
    '"AVGRank"': '32',
    '"AVGTier"': '2',
    '"Siegele3.2"': '39',
    '"Caban3.16"': '25',
  },
  {
    '""': '"31"',
    '"Rank"': '31',
    '"Player"': '"Drake London"',
    '"POS"': '"WR"',
    '"Team"': '"ATL"',
    '"PosRank"': '18',
    '"AVGRank"': '32',
    '"AVGTier"': '2',
    '"Siegele3.2"': '26',
    '"Caban3.16"': '38',
  },
  {
    '""': '"32"',
    '"Rank"': '32',
    '"Player"': '"Deebo Samuel"',
    '"POS"': '"WR"',
    '"Team"': '"SF"',
    '"PosRank"': '19',
    '"AVGRank"': '32.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '32',
    '"Caban3.16"': '33',
  },
  {
    '""': '"33"',
    '"Rank"': '33',
    '"Player"': '"Zay Flowers"',
    '"POS"': '"WR"',
    '"Team"': '"BAL"',
    '"PosRank"': '20',
    '"AVGRank"': '32.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '30',
    '"Caban3.16"': '35',
  },
  {
    '""': '"34"',
    '"Rank"': '34',
    '"Player"': '"Saquon Barkley"',
    '"POS"': '"RB"',
    '"Team"': '"PHI"',
    '"PosRank"': '9',
    '"AVGRank"': '33',
    '"AVGTier"': '2',
    '"Siegele3.2"': '37',
    '"Caban3.16"': '29',
  },
  {
    '""': '"35"',
    '"Rank"': '35',
    '"Player"': '"Tee Higgins"',
    '"POS"': '"WR"',
    '"Team"': '"CIN"',
    '"PosRank"': '21',
    '"AVGRank"': '34.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '35',
    '"Caban3.16"': '34',
  },
  {
    '""': '"36"',
    '"Rank"': '36',
    '"Player"': '"Cooper Kupp"',
    '"POS"': '"WR"',
    '"Team"': '"LAR"',
    '"PosRank"': '22',
    '"AVGRank"': '37',
    '"AVGTier"': '3',
    '"Siegele3.2"': '34',
    '"Caban3.16"': '40',
  },
  {
    '""': '"37"',
    '"Rank"': '37',
    '"Player"': '"Jalen Hurts"',
    '"POS"': '"QB"',
    '"Team"': '"PHI"',
    '"PosRank"': '2',
    '"AVGRank"': '37.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '44',
    '"Caban3.16"': '31',
  },
  {
    '""': '"38"',
    '"Rank"': '38',
    '"Player"': '"DeVonta Smith"',
    '"POS"': '"WR"',
    '"Team"': '"PHI"',
    '"PosRank"': '23',
    '"AVGRank"': '38',
    '"AVGTier"': '3',
    '"Siegele3.2"': '40',
    '"Caban3.16"': '36',
  },
  {
    '""': '"39"',
    '"Rank"': '39',
    '"Player"': '"Michael Pittman"',
    '"POS"': '"WR"',
    '"Team"': '"IND"',
    '"PosRank"': '24',
    '"AVGRank"': '39.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '47',
    '"Caban3.16"': '32',
  },
  {
    '""': '"40"',
    '"Rank"': '40',
    '"Player"': '"Stefon Diggs"',
    '"POS"': '"WR"',
    '"Team"': '"BUF"',
    '"PosRank"': '25',
    '"AVGRank"': '41.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '42',
    '"Caban3.16"': '41',
  },
  {
    '""': '"41"',
    '"Rank"': '41',
    '"Player"': '"Davante Adams"',
    '"POS"': '"WR"',
    '"Team"': '"LV"',
    '"PosRank"': '26',
    '"AVGRank"': '42.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '33',
    '"Caban3.16"': '52',
  },
  {
    '""': '"42"',
    '"Rank"': '42',
    '"Player"': '"Keenan Allen"',
    '"POS"': '"WR"',
    '"Team"': '"CHI"',
    '"PosRank"': '27',
    '"AVGRank"': '42.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '41',
    '"Caban3.16"': '44',
  },
  {
    '""': '"43"',
    '"Rank"': '43',
    '"Player"': '"Mark Andrews"',
    '"POS"': '"TE"',
    '"Team"': '"BAL"',
    '"PosRank"': '5',
    '"AVGRank"': '45.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '49',
    '"Caban3.16"': '42',
  },
  {
    '""': '"44"',
    '"Rank"': '44',
    '"Player"': '"Malik Nabers"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '28',
    '"AVGRank"': '44.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '43',
    '"Caban3.16"': '46',
  },
  {
    '""': '"45"',
    '"Rank"': '45',
    '"Player"': '"DK Metcalf"',
    '"POS"': '"WR"',
    '"Team"': '"SEA"',
    '"PosRank"': '29',
    '"AVGRank"': '48',
    '"AVGTier"': '3',
    '"Siegele3.2"': '53',
    '"Caban3.16"': '43',
  },
  {
    '""': '"46"',
    '"Rank"': '46',
    '"Player"': '"Josh Jacobs"',
    '"POS"': '"RB"',
    '"Team"': '"GB"',
    '"PosRank"': '10',
    '"AVGRank"': '48.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '36',
    '"Caban3.16"': '61',
  },
  {
    '""': '"47"',
    '"Rank"': '47',
    '"Player"': '"Jordan Addison"',
    '"POS"': '"WR"',
    '"Team"': '"MIN"',
    '"PosRank"': '30',
    '"AVGRank"': '48.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '58',
    '"Caban3.16"': '39',
  },
  {
    '""': '"48"',
    '"Rank"': '48',
    '"Player"': '"Jayden Reed"',
    '"POS"': '"WR"',
    '"Team"': '"GB"',
    '"PosRank"': '31',
    '"AVGRank"': '48.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '46',
    '"Caban3.16"': '51',
  },
  {
    '""': '"49"',
    '"Rank"': '49',
    '"Player"': '"Kyle Pitts"',
    '"POS"': '"TE"',
    '"Team"': '"ATL"',
    '"PosRank"': '6',
    '"AVGRank"': '49.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '54',
    '"Caban3.16"': '45',
  },
  {
    '""': '"50"',
    '"Rank"': '50',
    '"Player"': '"Derrick Henry"',
    '"POS"': '"RB"',
    '"Team"': '"BAL"',
    '"PosRank"': '11',
    '"AVGRank"': '50',
    '"AVGTier"': '3',
    '"Siegele3.2"': '38',
    '"Caban3.16"': '62',
  },
  {
    '""': '"51"',
    '"Rank"': '51',
    '"Player"': '"Jaxon Smith-Njigba"',
    '"POS"': '"WR"',
    '"Team"': '"SEA"',
    '"PosRank"': '32',
    '"AVGRank"': '51',
    '"AVGTier"': '3',
    '"Siegele3.2"': '55',
    '"Caban3.16"': '47',
  },
  {
    '""': '"52"',
    '"Rank"': '52',
    '"Player"': '"James Cook"',
    '"POS"': '"RB"',
    '"Team"': '"BUF"',
    '"PosRank"': '12',
    '"AVGRank"': '52.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '56',
    '"Caban3.16"': '49',
  },
  {
    '""': '"53"',
    '"Rank"': '53',
    '"Player"': '"C.J. Stroud"',
    '"POS"': '"QB"',
    '"Team"': '"HOU"',
    '"PosRank"': '3',
    '"AVGRank"': '52.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '45',
    '"Caban3.16"': '60',
  },
  {
    '""': '"54"',
    '"Rank"': '54',
    '"Player"': '"Lamar Jackson"',
    '"POS"': '"QB"',
    '"Team"': '"BAL"',
    '"PosRank"': '4',
    '"AVGRank"': '53',
    '"AVGTier"': '3',
    '"Siegele3.2"': '52',
    '"Caban3.16"': '54',
  },
  {
    '""': '"55"',
    '"Rank"': '55',
    '"Player"': '"Patrick Mahomes"',
    '"POS"': '"QB"',
    '"Team"': '"KC"',
    '"PosRank"': '5',
    '"AVGRank"': '53.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '48',
    '"Caban3.16"': '59',
  },
  {
    '""': '"56"',
    '"Rank"': '56',
    '"Player"': '"Brock Bowers"',
    '"POS"': '"TE"',
    '"Team"': '"FA"',
    '"PosRank"': '7',
    '"AVGRank"': '53.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '50',
    '"Caban3.16"': '57',
  },
  {
    '""': '"57"',
    '"Rank"': '57',
    '"Player"': '"Kenneth Walker"',
    '"POS"': '"RB"',
    '"Team"': '"SEA"',
    '"PosRank"': '13',
    '"AVGRank"': '54.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '59',
    '"Caban3.16"': '50',
  },
  {
    '""': '"58"',
    '"Rank"': '58',
    '"Player"': '"Aaron Jones"',
    '"POS"': '"RB"',
    '"Team"': '"MIN"',
    '"PosRank"': '14',
    '"AVGRank"': '57.5',
    '"AVGTier"': '4',
    '"Siegele3.2"': '62',
    '"Caban3.16"': '53',
  },
  {
    '""': '"59"',
    '"Rank"': '59',
    '"Player"': '"Rachaad White"',
    '"POS"': '"RB"',
    '"Team"': '"TB"',
    '"PosRank"': '15',
    '"AVGRank"': '60',
    '"AVGTier"': '4',
    '"Siegele3.2"': '65',
    '"Caban3.16"': '55',
  },
  {
    '""': '"60"',
    '"Rank"': '60',
    '"Player"': '"Rome Odunze"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '33',
    '"AVGRank"': '58',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '60',
    '"Caban3.16"': '56',
  },
  {
    '""': '"61"',
    '"Rank"': '61',
    '"Player"': '"Amari Cooper"',
    '"POS"': '"WR"',
    '"Team"': '"CLE"',
    '"PosRank"': '34',
    '"AVGRank"': '60.5',
    '"AVGTier"': '3',
    '"Siegele3.2"': '51',
    '"Caban3.16"': '70',
  },
  {
    '""': '"62"',
    '"Rank"': '62',
    '"Player"': '"Jaylen Warren"',
    '"POS"': '"RB"',
    '"Team"': '"PIT"',
    '"PosRank"': '16',
    '"AVGRank"': '61',
    '"AVGTier"': '4',
    '"Siegele3.2"': '64',
    '"Caban3.16"': '58',
  },
  {
    '""': '"63"',
    '"Rank"': '63',
    '"Player"': '"Tyjae Spears"',
    '"POS"': '"RB"',
    '"Team"': '"TEN"',
    '"PosRank"': '17',
    '"AVGRank"': '66',
    '"AVGTier"': '3',
    '"Siegele3.2"': '84',
    '"Caban3.16"': '48',
  },
  {
    '""': '"64"',
    '"Rank"': '64',
    '"Player"': '"Rhamondre Stevenson"',
    '"POS"': '"RB"',
    '"Team"': '"NE"',
    '"PosRank"': '18',
    '"AVGRank"': '67',
    '"AVGTier"': '4',
    '"Siegele3.2"': '67',
    '"Caban3.16"': '67',
  },
  {
    '""': '"65"',
    '"Rank"': '65',
    '"Player"': '"David Njoku"',
    '"POS"': '"TE"',
    '"Team"': '"CLE"',
    '"PosRank"': '8',
    '"AVGRank"': '69',
    '"AVGTier"': '3',
    '"Siegele3.2"': '61',
    '"Caban3.16"': '77',
  },
  {
    '""': '"66"',
    '"Rank"': '66',
    '"Player"': '"Terry McLaurin"',
    '"POS"': '"WR"',
    '"Team"': '"WAS"',
    '"PosRank"': '35',
    '"AVGRank"': '69.5',
    '"AVGTier"': '4',
    '"Siegele3.2"': '75',
    '"Caban3.16"': '64',
  },
  {
    '""': '"67"',
    '"Rank"': '67',
    '"Player"': '"Christian Kirk"',
    '"POS"': '"WR"',
    '"Team"': '"JAC"',
    '"PosRank"': '36',
    '"AVGRank"': '70',
    '"AVGTier"': '4',
    '"Siegele3.2"': '68',
    '"Caban3.16"': '72',
  },
  {
    '""': '"68"',
    '"Rank"': '68',
    '"Player"': '"Diontae Johnson"',
    '"POS"': '"WR"',
    '"Team"': '"CAR"',
    '"PosRank"': '37',
    '"AVGRank"': '70',
    '"AVGTier"': '4',
    '"Siegele3.2"': '72',
    '"Caban3.16"': '68',
  },
  {
    '""': '"69"',
    '"Rank"': '69',
    '"Player"': '"Brian Thomas Jr."',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '38',
    '"AVGRank"': '70',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '66',
    '"Caban3.16"': '74',
  },
  {
    '""': '"70"',
    '"Rank"': '70',
    '"Player"': '"George Kittle"',
    '"POS"': '"TE"',
    '"Team"': '"SF"',
    '"PosRank"': '9',
    '"AVGRank"': '72',
    '"AVGTier"': '4',
    '"Siegele3.2"': '79',
    '"Caban3.16"': '65',
  },
  {
    '""': '"71"',
    '"Rank"': '71',
    '"Player"': '"Isiah Pacheco"',
    '"POS"': '"RB"',
    '"Team"': '"KC"',
    '"PosRank"': '19',
    '"AVGRank"': '72.5',
    '"AVGTier"': '4',
    '"Siegele3.2"': '74',
    '"Caban3.16"': '71',
  },
  {
    '""': '"72"',
    '"Rank"': '72',
    '"Player"': '"Alvin Kamara"',
    '"POS"': '"RB"',
    '"Team"': '"NO"',
    '"PosRank"': '20',
    '"AVGRank"': '73',
    '"AVGTier"': '4',
    '"Siegele3.2"': '70',
    '"Caban3.16"': '76',
  },
  {
    '""': '"73"',
    '"Rank"': '73',
    '"Player"': '"Evan Engram"',
    '"POS"': '"TE"',
    '"Team"': '"JAC"',
    '"PosRank"': '10',
    '"AVGRank"': '74',
    '"AVGTier"': '4',
    '"Siegele3.2"': '82',
    '"Caban3.16"': '66',
  },
  {
    '""': '"74"',
    '"Rank"': '74',
    '"Player"': '"Nick Chubb"',
    '"POS"': '"RB"',
    '"Team"': '"CLE"',
    '"PosRank"': '21',
    '"AVGRank"': '75.5',
    '"AVGTier"': '4',
    '"Siegele3.2"': '73',
    '"Caban3.16"': '78',
  },
  {
    '""': '"75"',
    '"Rank"': '75',
    '"Player"': '"Najee Harris"',
    '"POS"': '"RB"',
    '"Team"': '"PIT"',
    '"PosRank"': '22',
    '"AVGRank"': '75.5',
    '"AVGTier"': '4',
    '"Siegele3.2"': '76',
    '"Caban3.16"': '75',
  },
  {
    '""': '"76"',
    '"Rank"': '76',
    '"Player"': '"Javonte Williams"',
    '"POS"': '"RB"',
    '"Team"': '"DEN"',
    '"PosRank"': '23',
    '"AVGRank"': '76',
    '"AVGTier"': '4',
    '"Siegele3.2"': '71',
    '"Caban3.16"': '81',
  },
  {
    '""': '"77"',
    '"Rank"': '77',
    '"Player"': '"Raheem Mostert"',
    '"POS"': '"RB"',
    '"Team"': '"MIA"',
    '"PosRank"': '24',
    '"AVGRank"': '80',
    '"AVGTier"': '4',
    '"Siegele3.2"': '69',
    '"Caban3.16"': '91',
  },
  {
    '""': '"78"',
    '"Rank"': '78',
    '"Player"': '"Calvin Ridley"',
    '"POS"': '"WR"',
    '"Team"': '"TEN"',
    '"PosRank"': '39',
    '"AVGRank"': '82.5',
    '"AVGTier"': '4',
    '"Siegele3.2"': '86',
    '"Caban3.16"': '79',
  },
  {
    '""': '"79"',
    '"Rank"': '79',
    '"Player"': '"Trey Benson"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '25',
    '"AVGRank"': '81',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '89',
    '"Caban3.16"': '73',
  },
  {
    '""': '"80"',
    '"Rank"': '80',
    '"Player"': '"George Pickens"',
    '"POS"': '"WR"',
    '"Team"': '"PIT"',
    '"PosRank"': '40',
    '"AVGRank"': '83',
    '"AVGTier"': '4',
    '"Siegele3.2"': '78',
    '"Caban3.16"': '88',
  },
  {
    '""': '"81"',
    '"Rank"': '81',
    '"Player"': '"Anthony Richardson"',
    '"POS"': '"QB"',
    '"Team"': '"IND"',
    '"PosRank"': '6',
    '"AVGRank"': '83',
    '"AVGTier"': '4',
    '"Siegele3.2"': '80',
    '"Caban3.16"': '86',
  },
  {
    '""': '"82"',
    '"Rank"': '82',
    '"Player"': '"Christian Watson"',
    '"POS"': '"WR"',
    '"Team"': '"GB"',
    '"PosRank"': '41',
    '"AVGRank"': '84.5',
    '"AVGTier"': '4',
    '"Siegele3.2"': '85',
    '"Caban3.16"': '84',
  },
  {
    '""': '"83"',
    '"Rank"': '83',
    '"Player"': '"Marquise Brown"',
    '"POS"': '"WR"',
    '"Team"': '"KC"',
    '"PosRank"': '42',
    '"AVGRank"': '85',
    '"AVGTier"': '4',
    '"Siegele3.2"': '57',
    '"Caban3.16"': '113',
  },
  {
    '""': '"84"',
    '"Rank"': '84',
    '"Player"': '"T.J. Hockenson"',
    '"POS"': '"TE"',
    '"Team"': '"MIN"',
    '"PosRank"': '11',
    '"AVGRank"': '86',
    '"AVGTier"': '4',
    '"Siegele3.2"': '109',
    '"Caban3.16"': '63',
  },
  {
    '""': '"85"',
    '"Rank"': '85',
    '"Player"': '"Jordan Love"',
    '"POS"': '"QB"',
    '"Team"': '"GB"',
    '"PosRank"': '7',
    '"AVGRank"': '86.5',
    '"AVGTier"': '4',
    '"Siegele3.2"': '77',
    '"Caban3.16"': '96',
  },
  {
    '""': '"86"',
    '"Rank"': '86',
    '"Player"': '"Chase Brown"',
    '"POS"': '"RB"',
    '"Team"': '"CIN"',
    '"PosRank"': '26',
    '"AVGRank"': '88.5',
    '"AVGTier"': '4',
    '"Siegele3.2"': '95',
    '"Caban3.16"': '82',
  },
  {
    '""': '"87"',
    '"Rank"': '87',
    '"Player"': '"Jake Ferguson"',
    '"POS"': '"TE"',
    '"Team"': '"DAL"',
    '"PosRank"': '12',
    '"AVGRank"': '89.5',
    '"AVGTier"': '4',
    '"Siegele3.2"': '96',
    '"Caban3.16"': '83',
  },
  {
    '""': '"88"',
    '"Rank"': '88',
    '"Player"': '"David Montgomery"',
    '"POS"': '"RB"',
    '"Team"': '"DET"',
    '"PosRank"': '27',
    '"AVGRank"': '90.5',
    '"AVGTier"': '5',
    '"Siegele3.2"': '92',
    '"Caban3.16"': '89',
  },
  {
    '""': '"89"',
    '"Rank"': '89',
    '"Player"': '"Xavier Worthy"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '43',
    '"AVGRank"': '90.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '101',
    '"Caban3.16"': '80',
  },
  {
    '""': '"90"',
    '"Rank"': '90',
    '"Player"': '"Chris Godwin"',
    '"POS"': '"WR"',
    '"Team"': '"TB"',
    '"PosRank"': '44',
    '"AVGRank"': '91',
    '"AVGTier"': '5',
    '"Siegele3.2"': '88',
    '"Caban3.16"': '94',
  },
  {
    '""': '"91"',
    '"Rank"': '91',
    '"Player"': '"Dak Prescott"',
    '"POS"': '"QB"',
    '"Team"': '"DAL"',
    '"PosRank"': '8',
    '"AVGRank"': '91',
    '"AVGTier"': '4',
    '"Siegele3.2"': '87',
    '"Caban3.16"': '95',
  },
  {
    '""': '"92"',
    '"Rank"': '92',
    '"Player"': '"Joe Burrow"',
    '"POS"': '"QB"',
    '"Team"': '"CIN"',
    '"PosRank"': '9',
    '"AVGRank"': '92.5',
    '"AVGTier"': '5',
    '"Siegele3.2"': '98',
    '"Caban3.16"': '87',
  },
  {
    '""': '"93"',
    '"Rank"': '93',
    '"Player"': '"Tony Pollard"',
    '"POS"': '"RB"',
    '"Team"': '"TEN"',
    '"PosRank"': '28',
    '"AVGRank"': '96',
    '"AVGTier"': '5',
    '"Siegele3.2"': '102',
    '"Caban3.16"': '90',
  },
  {
    '""': '"94"',
    '"Rank"': '94',
    '"Player"': '"Caleb Williams"',
    '"POS"': '"QB"',
    '"Team"': '"FA"',
    '"PosRank"': '10',
    '"AVGRank"': '95',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '91',
    '"Caban3.16"': '99',
  },
  {
    '""': '"95"',
    '"Rank"': '95',
    '"Player"': '"Austin Ekeler"',
    '"POS"': '"RB"',
    '"Team"': '"WAS"',
    '"PosRank"': '29',
    '"AVGRank"': '96.5',
    '"AVGTier"': '4',
    '"Siegele3.2"': '108',
    '"Caban3.16"': '85',
  },
  {
    '""': '"96"',
    '"Rank"': '96',
    '"Player"': '"Joe Mixon"',
    '"POS"': '"RB"',
    '"Team"': '"HOU"',
    '"PosRank"': '30',
    '"AVGRank"': '96.5',
    '"AVGTier"': '5',
    '"Siegele3.2"': '63',
    '"Caban3.16"': '130',
  },
  {
    '""': '"97"',
    '"Rank"': '97',
    '"Player"': '"James Conner"',
    '"POS"': '"RB"',
    '"Team"': '"ARI"',
    '"PosRank"': '31',
    '"AVGRank"': '97',
    '"AVGTier"': '5',
    '"Siegele3.2"': '94',
    '"Caban3.16"': '100',
  },
  {
    '""': '"98"',
    '"Rank"': '98',
    '"Player"': '"Courtland Sutton"',
    '"POS"': '"WR"',
    '"Team"': '"DEN"',
    '"PosRank"': '45',
    '"AVGRank"': '97.5',
    '"AVGTier"': '4',
    '"Siegele3.2"': '83',
    '"Caban3.16"': '112',
  },
  {
    '""': '"99"',
    '"Rank"': '99',
    '"Player"': '"Brock Purdy"',
    '"POS"': '"QB"',
    '"Team"': '"SF"',
    '"PosRank"': '11',
    '"AVGRank"': '97.5',
    '"AVGTier"': '5',
    '"Siegele3.2"': '93',
    '"Caban3.16"': '102',
  },
  {
    '""': '"100"',
    '"Rank"': '100',
    '"Player"': '"D\'Andre Swift"',
    '"POS"': '"RB"',
    '"Team"': '"CHI"',
    '"PosRank"': '32',
    '"AVGRank"': '98.5',
    '"AVGTier"': '5',
    '"Siegele3.2"': '81',
    '"Caban3.16"': '116',
  },
  {
    '""': '"101"',
    '"Rank"': '101',
    '"Player"': '"Cole Kmet"',
    '"POS"': '"TE"',
    '"Team"': '"CHI"',
    '"PosRank"': '13',
    '"AVGRank"': '98.5',
    '"AVGTier"': '5',
    '"Siegele3.2"': '104',
    '"Caban3.16"': '93',
  },
  {
    '""': '"102"',
    '"Rank"': '102',
    '"Player"': '"Kyler Murray"',
    '"POS"': '"QB"',
    '"Team"': '"ARI"',
    '"PosRank"': '12',
    '"AVGRank"': '99.5',
    '"AVGTier"': '5',
    '"Siegele3.2"': '107',
    '"Caban3.16"': '92',
  },
  {
    '""': '"103"',
    '"Rank"': '103',
    '"Player"': '"Jameson Williams"',
    '"POS"': '"WR"',
    '"Team"': '"DET"',
    '"PosRank"': '46',
    '"AVGRank"': '105',
    '"AVGTier"': '5',
    '"Siegele3.2"': '106',
    '"Caban3.16"': '104',
  },
  {
    '""': '"104"',
    '"Rank"': '104',
    '"Player"': '"Jonathon Brooks"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '33',
    '"AVGRank"': '101',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '105',
    '"Caban3.16"': '97',
  },
  {
    '""': '"105"',
    '"Rank"': '105',
    '"Player"': '"Zamir White"',
    '"POS"': '"RB"',
    '"Team"': '"LV"',
    '"PosRank"': '34',
    '"AVGRank"': '107.5',
    '"AVGTier"': '5',
    '"Siegele3.2"': '110',
    '"Caban3.16"': '105',
  },
  {
    '""': '"106"',
    '"Rank"': '106',
    '"Player"': '"Brian Robinson"',
    '"POS"': '"RB"',
    '"Team"': '"WAS"',
    '"PosRank"': '35',
    '"AVGRank"': '108',
    '"AVGTier"': '5',
    '"Siegele3.2"': '118',
    '"Caban3.16"': '98',
  },
  {
    '""': '"107"',
    '"Rank"': '107',
    '"Player"': '"Tyler Lockett"',
    '"POS"': '"WR"',
    '"Team"': '"SEA"',
    '"PosRank"': '47',
    '"AVGRank"': '108.5',
    '"AVGTier"': '5',
    '"Siegele3.2"': '99',
    '"Caban3.16"': '118',
  },
  {
    '""': '"108"',
    '"Rank"': '108',
    '"Player"': '"Zach Charbonnet"',
    '"POS"': '"RB"',
    '"Team"': '"SEA"',
    '"PosRank"': '36',
    '"AVGRank"': '109',
    '"AVGTier"': '5',
    '"Siegele3.2"': '112',
    '"Caban3.16"': '106',
  },
  {
    '""': '"109"',
    '"Rank"': '109',
    '"Player"': '"Dallas Goedert"',
    '"POS"': '"TE"',
    '"Team"': '"PHI"',
    '"PosRank"': '14',
    '"AVGRank"': '109.5',
    '"AVGTier"': '5',
    '"Siegele3.2"': '116',
    '"Caban3.16"': '103',
  },
  {
    '""': '"110"',
    '"Rank"': '110',
    '"Player"': '"Chuba Hubbard"',
    '"POS"': '"RB"',
    '"Team"': '"CAR"',
    '"PosRank"': '37',
    '"AVGRank"': '111',
    '"AVGTier"': '5',
    '"Siegele3.2"': '113',
    '"Caban3.16"': '109',
  },
  {
    '""': '"111"',
    '"Rank"': '111',
    '"Player"': '"Luke Musgrave"',
    '"POS"': '"TE"',
    '"Team"': '"GB"',
    '"PosRank"': '15',
    '"AVGRank"': '111',
    '"AVGTier"': '5',
    '"Siegele3.2"': '111',
    '"Caban3.16"': '111',
  },
  {
    '""': '"112"',
    '"Rank"': '112',
    '"Player"': '"Jaylen Wright"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '38',
    '"AVGRank"': '111',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '121',
    '"Caban3.16"': '101',
  },
  {
    '""': '"113"',
    '"Rank"': '113',
    '"Player"': '"Kirk Cousins"',
    '"POS"': '"QB"',
    '"Team"': '"ATL"',
    '"PosRank"': '13',
    '"AVGRank"': '113',
    '"AVGTier"': '5',
    '"Siegele3.2"': '100',
    '"Caban3.16"': '126',
  },
  {
    '""': '"114"',
    '"Rank"': '114',
    '"Player"': '"Kendre Miller"',
    '"POS"': '"RB"',
    '"Team"': '"NO"',
    '"PosRank"': '39',
    '"AVGRank"': '114.5',
    '"AVGTier"': '5',
    '"Siegele3.2"': '119',
    '"Caban3.16"': '110',
  },
  {
    '""': '"115"',
    '"Rank"': '115',
    '"Player"': '"Jerry Jeudy"',
    '"POS"': '"WR"',
    '"Team"': '"CLE"',
    '"PosRank"': '48',
    '"AVGRank"': '115',
    '"AVGTier"': '5',
    '"Siegele3.2"': '97',
    '"Caban3.16"': '133',
  },
  {
    '""': '"116"',
    '"Rank"': '116',
    '"Player"': '"Marvin Mims"',
    '"POS"': '"WR"',
    '"Team"': '"DEN"',
    '"PosRank"': '49',
    '"AVGRank"': '115.5',
    '"AVGTier"': '5',
    '"Siegele3.2"': '103',
    '"Caban3.16"': '128',
  },
  {
    '""': '"117"',
    '"Rank"': '117',
    '"Player"': '"Keon Coleman"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '50',
    '"AVGRank"': '115.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '114',
    '"Caban3.16"': '117',
  },
  {
    '""': '"118"',
    '"Rank"': '118',
    '"Player"': '"Josh Downs"',
    '"POS"': '"WR"',
    '"Team"': '"IND"',
    '"PosRank"': '51',
    '"AVGRank"': '116.5',
    '"AVGTier"': '5',
    '"Siegele3.2"': '125',
    '"Caban3.16"': '108',
  },
  {
    '""': '"119"',
    '"Rank"': '119',
    '"Player"': '"Tua Tagovailoa"',
    '"POS"': '"QB"',
    '"Team"': '"MIA"',
    '"PosRank"': '14',
    '"AVGRank"': '118',
    '"AVGTier"': '6',
    '"Siegele3.2"': '122',
    '"Caban3.16"': '114',
  },
  {
    '""': '"120"',
    '"Rank"': '120',
    '"Player"': '"Troy Franklin"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '52',
    '"AVGRank"': '117.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '115',
    '"Caban3.16"': '120',
  },
  {
    '""': '"121"',
    '"Rank"': '121',
    '"Player"': '"Ladd McConkey"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '53',
    '"AVGRank"': '119',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '117',
    '"Caban3.16"': '121',
  },
  {
    '""': '"122"',
    '"Rank"': '122',
    '"Player"': '"Roschon Johnson"',
    '"POS"': '"RB"',
    '"Team"': '"CHI"',
    '"PosRank"': '40',
    '"AVGRank"': '121.5',
    '"AVGTier"': '5',
    '"Siegele3.2"': '136',
    '"Caban3.16"': '107',
  },
  {
    '""': '"123"',
    '"Rank"': '123',
    '"Player"': '"Devontez Walker"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '54',
    '"AVGRank"': '119.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '120',
    '"Caban3.16"': '119',
  },
  {
    '""': '"124"',
    '"Rank"': '124',
    '"Player"': '"DeAndre Hopkins"',
    '"POS"': '"WR"',
    '"Team"': '"TEN"',
    '"PosRank"': '55',
    '"AVGRank"': '123.5',
    '"AVGTier"': '6',
    '"Siegele3.2"': '123',
    '"Caban3.16"': '124',
  },
  {
    '""': '"125"',
    '"Rank"': '125',
    '"Player"': '"Dalton Schultz"',
    '"POS"': '"TE"',
    '"Team"': '"HOU"',
    '"PosRank"': '16',
    '"AVGRank"': '124',
    '"AVGTier"': '6',
    '"Siegele3.2"': '133',
    '"Caban3.16"': '115',
  },
  {
    '""': '"126"',
    '"Rank"': '126',
    '"Player"': '"Trevor Lawrence"',
    '"POS"': '"QB"',
    '"Team"': '"JAC"',
    '"PosRank"': '15',
    '"AVGRank"': '124.5',
    '"AVGTier"': '6',
    '"Siegele3.2"': '124',
    '"Caban3.16"': '125',
  },
  {
    '""': '"127"',
    '"Rank"': '127',
    '"Player"': '"Jaleel McLaughlin"',
    '"POS"': '"RB"',
    '"Team"': '"DEN"',
    '"PosRank"': '41',
    '"AVGRank"': '124.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '126',
    '"Caban3.16"': '123',
  },
  {
    '""': '"128"',
    '"Rank"': '128',
    '"Player"': '"Justin Herbert"',
    '"POS"': '"QB"',
    '"Team"': '"LAC"',
    '"PosRank"': '16',
    '"AVGRank"': '125.5',
    '"AVGTier"': '6',
    '"Siegele3.2"': '129',
    '"Caban3.16"': '122',
  },
  {
    '""': '"129"',
    '"Rank"': '129',
    '"Player"': '"Justin Fields"',
    '"POS"': '"QB"',
    '"Team"': '"PIT"',
    '"PosRank"': '17',
    '"AVGRank"': '126',
    '"AVGTier"': '6',
    '"Siegele3.2"': '183',
    '"Caban3.16"': '69',
  },
  {
    '""': '"130"',
    '"Rank"': '130',
    '"Player"': '"MarShawn Lloyd"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '42',
    '"AVGRank"': '129.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '130',
    '"Caban3.16"': '129',
  },
  {
    '""': '"131"',
    '"Rank"': '131',
    '"Player"': '"Michael Mayer"',
    '"POS"': '"TE"',
    '"Team"': '"LV"',
    '"PosRank"': '17',
    '"AVGRank"': '132.5',
    '"AVGTier"': '6',
    '"Siegele3.2"': '134',
    '"Caban3.16"': '131',
  },
  {
    '""': '"132"',
    '"Rank"': '132',
    '"Player"': '"Jayden Daniels"',
    '"POS"': '"QB"',
    '"Team"': '"FA"',
    '"PosRank"': '18',
    '"AVGRank"': '131.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '127',
    '"Caban3.16"': '136',
  },
  {
    '""': '"133"',
    '"Rank"': '133',
    '"Player"': '"Mike Williams"',
    '"POS"': '"WR"',
    '"Team"': '"NYJ"',
    '"PosRank"': '56',
    '"AVGRank"': '134',
    '"AVGTier"': '6',
    '"Siegele3.2"': '90',
    '"Caban3.16"': '178',
  },
  {
    '""': '"134"',
    '"Rank"': '134',
    '"Player"': '"Deshaun Watson"',
    '"POS"': '"QB"',
    '"Team"': '"CLE"',
    '"PosRank"': '19',
    '"AVGRank"': '134.5',
    '"AVGTier"': '6',
    '"Siegele3.2"': '135',
    '"Caban3.16"': '134',
  },
  {
    '""': '"135"',
    '"Rank"': '135',
    '"Player"': '"Jared Goff"',
    '"POS"': '"QB"',
    '"Team"': '"DET"',
    '"PosRank"': '20',
    '"AVGRank"': '136',
    '"AVGTier"': '6',
    '"Siegele3.2"': '137',
    '"Caban3.16"': '135',
  },
  {
    '""': '"136"',
    '"Rank"': '136',
    '"Player"': '"Rashid Shaheed"',
    '"POS"': '"WR"',
    '"Team"': '"NO"',
    '"PosRank"': '57',
    '"AVGRank"': '137.5',
    '"AVGTier"': '6',
    '"Siegele3.2"': '143',
    '"Caban3.16"': '132',
  },
  {
    '""': '"137"',
    '"Rank"': '137',
    '"Player"': '"Romeo Doubs"',
    '"POS"': '"WR"',
    '"Team"': '"GB"',
    '"PosRank"': '58',
    '"AVGRank"': '137.5',
    '"AVGTier"': '6',
    '"Siegele3.2"': '138',
    '"Caban3.16"': '137',
  },
  {
    '""': '"138"',
    '"Rank"': '138',
    '"Player"': '"Jakobi Meyers"',
    '"POS"': '"WR"',
    '"Team"': '"LV"',
    '"PosRank"': '59',
    '"AVGRank"': '138',
    '"AVGTier"': '6',
    '"Siegele3.2"': '149',
    '"Caban3.16"': '127',
  },
  {
    '""': '"139"',
    '"Rank"': '139',
    '"Player"': '"Wan\'Dale Robinson"',
    '"POS"': '"WR"',
    '"Team"': '"NYG"',
    '"PosRank"': '60',
    '"AVGRank"': '138',
    '"AVGTier"': '6',
    '"Siegele3.2"': '128',
    '"Caban3.16"': '148',
  },
  {
    '""': '"140"',
    '"Rank"': '140',
    '"Player"': '"Zack Moss"',
    '"POS"': '"RB"',
    '"Team"': '"CIN"',
    '"PosRank"': '43',
    '"AVGRank"': '138',
    '"AVGTier"': '6',
    '"Siegele3.2"': '131',
    '"Caban3.16"': '145',
  },
  {
    '""': '"141"',
    '"Rank"': '141',
    '"Player"': '"Aaron Rodgers"',
    '"POS"': '"QB"',
    '"Team"': '"NYJ"',
    '"PosRank"': '21',
    '"AVGRank"': '141',
    '"AVGTier"': '6',
    '"Siegele3.2"': '141',
    '"Caban3.16"': '141',
  },
  {
    '""': '"142"',
    '"Rank"': '142',
    '"Player"': '"Blake Corum"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '44',
    '"AVGRank"': '140',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '140',
    '"Caban3.16"': '140',
  },
  {
    '""': '"143"',
    '"Rank"': '143',
    '"Player"': '"Matthew Stafford"',
    '"POS"': '"QB"',
    '"Team"': '"LAR"',
    '"PosRank"': '22',
    '"AVGRank"': '142.5',
    '"AVGTier"': '6',
    '"Siegele3.2"': '142',
    '"Caban3.16"': '143',
  },
  {
    '""': '"144"',
    '"Rank"': '144',
    '"Player"': '"Jalin Hyatt"',
    '"POS"': '"WR"',
    '"Team"': '"NYG"',
    '"PosRank"': '61',
    '"AVGRank"': '143',
    '"AVGTier"': '6',
    '"Siegele3.2"': '139',
    '"Caban3.16"': '147',
  },
  {
    '""': '"145"',
    '"Rank"': '145',
    '"Player"': '"Quentin Johnston"',
    '"POS"': '"WR"',
    '"Team"': '"LAC"',
    '"PosRank"': '62',
    '"AVGRank"': '145',
    '"AVGTier"': '6',
    '"Siegele3.2"': '152',
    '"Caban3.16"': '138',
  },
  {
    '""': '"146"',
    '"Rank"': '146',
    '"Player"': '"Gabe Davis"',
    '"POS"': '"WR"',
    '"Team"': '"JAC"',
    '"PosRank"': '63',
    '"AVGRank"': '146.5',
    '"AVGTier"': '7',
    '"Siegele3.2"': '144',
    '"Caban3.16"': '149',
  },
  {
    '""': '"147"',
    '"Rank"': '147',
    '"Player"': '"Khalil Herbert"',
    '"POS"': '"RB"',
    '"Team"': '"CHI"',
    '"PosRank"': '45',
    '"AVGRank"': '148.5',
    '"AVGTier"': '6',
    '"Siegele3.2"': '158',
    '"Caban3.16"': '139',
  },
  {
    '""': '"148"',
    '"Rank"': '148',
    '"Player"': '"Jahan Dotson"',
    '"POS"': '"WR"',
    '"Team"': '"WAS"',
    '"PosRank"': '64',
    '"AVGRank"': '148.5',
    '"AVGTier"': '7',
    '"Siegele3.2"': '151',
    '"Caban3.16"': '146',
  },
  {
    '""': '"149"',
    '"Rank"': '149',
    '"Player"': '"Devin Singletary"',
    '"POS"': '"RB"',
    '"Team"': '"NYG"',
    '"PosRank"': '46',
    '"AVGRank"': '148.5',
    '"AVGTier"': '6',
    '"Siegele3.2"': '132',
    '"Caban3.16"': '165',
  },
  {
    '""': '"150"',
    '"Rank"': '150',
    '"Player"': '"Braelon Allen"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '47',
    '"AVGRank"': '148.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '145',
    '"Caban3.16"': '152',
  },
  {
    '""': '"151"',
    '"Rank"': '151',
    '"Player"': '"Darren Waller"',
    '"POS"': '"TE"',
    '"Team"': '"NYG"',
    '"PosRank"': '18',
    '"AVGRank"': '150',
    '"AVGTier"': '6',
    '"Siegele3.2"': '156',
    '"Caban3.16"': '144',
  },
  {
    '""': '"152"',
    '"Rank"': '152',
    '"Player"': '"Will Shipley"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '48',
    '"AVGRank"': '150',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '146',
    '"Caban3.16"': '154',
  },
  {
    '""': '"153"',
    '"Rank"': '153',
    '"Player"': '"Xavier Legette"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '65',
    '"AVGRank"': '151',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '147',
    '"Caban3.16"': '155',
  },
  {
    '""': '"154"',
    '"Rank"': '154',
    '"Player"': '"Pat Freiermuth"',
    '"POS"': '"TE"',
    '"Team"': '"PIT"',
    '"PosRank"': '19',
    '"AVGRank"': '155',
    '"AVGTier"': '7',
    '"Siegele3.2"': '154',
    '"Caban3.16"': '156',
  },
  {
    '""': '"155"',
    '"Rank"': '155',
    '"Player"': '"Adonai Mitchell"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '66',
    '"AVGRank"': '153',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '148',
    '"Caban3.16"': '158',
  },
  {
    '""': '"156"',
    '"Rank"': '156',
    '"Player"': '"Jerome Ford"',
    '"POS"': '"RB"',
    '"Team"': '"CLE"',
    '"PosRank"': '49',
    '"AVGRank"': '156',
    '"AVGTier"': '7',
    '"Siegele3.2"': '153',
    '"Caban3.16"': '159',
  },
  {
    '""': '"157"',
    '"Rank"': '157',
    '"Player"': '"Dontayvion Wicks"',
    '"POS"': '"WR"',
    '"Team"': '"GB"',
    '"PosRank"': '67',
    '"AVGRank"': '157',
    '"AVGTier"': '7',
    '"Siegele3.2"': '164',
    '"Caban3.16"': '150',
  },
  {
    '""': '"158"',
    '"Rank"': '158',
    '"Player"': "\"Mar'Keise 'Bucky' Irving\"",
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '50',
    '"AVGRank"': '159',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '165',
    '"Caban3.16"': '153',
  },
  {
    '""': '"159"',
    '"Rank"': '159',
    '"Player"': '"Ja\'Tavion Sanders"',
    '"POS"': '"TE"',
    '"Team"': '"FA"',
    '"PosRank"': '20',
    '"AVGRank"': '159.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '155',
    '"Caban3.16"': '164',
  },
  {
    '""': '"160"',
    '"Rank"': '160',
    '"Player"': '"Tucker Kraft"',
    '"POS"': '"TE"',
    '"Team"': '"GB"',
    '"PosRank"': '21',
    '"AVGRank"': '163',
    '"AVGTier"': '7',
    '"Siegele3.2"': '160',
    '"Caban3.16"': '166',
  },
  {
    '""': '"161"',
    '"Rank"': '161',
    '"Player"': '"Khalil Shakir"',
    '"POS"': '"WR"',
    '"Team"': '"BUF"',
    '"PosRank"': '68',
    '"AVGRank"': '164.5',
    '"AVGTier"': '7',
    '"Siegele3.2"': '168',
    '"Caban3.16"': '161',
  },
  {
    '""': '"162"',
    '"Rank"': '162',
    '"Player"': '"Drake Maye"',
    '"POS"': '"QB"',
    '"Team"': '"FA"',
    '"PosRank"': '23',
    '"AVGRank"': '164.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '150',
    '"Caban3.16"': '179',
  },
  {
    '""': '"163"',
    '"Rank"': '163',
    '"Player"': '"Michael Wilson"',
    '"POS"': '"WR"',
    '"Team"': '"ARI"',
    '"PosRank"': '69',
    '"AVGRank"': '165',
    '"AVGTier"': '7',
    '"Siegele3.2"': '167',
    '"Caban3.16"': '163',
  },
  {
    '""': '"164"',
    '"Rank"': '164',
    '"Player"': '"Ja\'Lynn Polk"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '70',
    '"AVGRank"': '165',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '159',
    '"Caban3.16"': '171',
  },
  {
    '""': '"165"',
    '"Rank"': '165',
    '"Player"': '"Curtis Samuel"',
    '"POS"': '"WR"',
    '"Team"': '"BUF"',
    '"PosRank"': '71',
    '"AVGRank"': '167',
    '"AVGTier"': '7',
    '"Siegele3.2"': '177',
    '"Caban3.16"': '157',
  },
  {
    '""': '"166"',
    '"Rank"': '166',
    '"Player"': '"Trey Palmer"',
    '"POS"': '"WR"',
    '"Team"': '"TB"',
    '"PosRank"': '72',
    '"AVGRank"': '167.5',
    '"AVGTier"': '7',
    '"Siegele3.2"': '173',
    '"Caban3.16"': '162',
  },
  {
    '""': '"167"',
    '"Rank"': '167',
    '"Player"': '"Roman Wilson"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '73',
    '"AVGRank"': '167.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '166',
    '"Caban3.16"': '169',
  },
  {
    '""': '"168"',
    '"Rank"': '168',
    '"Player"': '"Ty Chandler"',
    '"POS"': '"RB"',
    '"Team"': '"MIN"',
    '"PosRank"': '51',
    '"AVGRank"': '171',
    '"AVGTier"': '7',
    '"Siegele3.2"': '200',
    '"Caban3.16"': '142',
  },
  {
    '""': '"169"',
    '"Rank"': '169',
    '"Player"': '"Ben Sinnott"',
    '"POS"': '"TE"',
    '"Team"': '"FA"',
    '"PosRank"': '22',
    '"AVGRank"': '170',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '157',
    '"Caban3.16"': '183',
  },
  {
    '""': '"170"',
    '"Rank"': '170',
    '"Player"': '"Rashod Bateman"',
    '"POS"': '"WR"',
    '"Team"': '"BAL"',
    '"PosRank"': '74',
    '"AVGRank"': '172',
    '"AVGTier"': '7',
    '"Siegele3.2"': '162',
    '"Caban3.16"': '182',
  },
  {
    '""': '"171"',
    '"Rank"': '171',
    '"Player"': '"Brandin Cooks"',
    '"POS"': '"WR"',
    '"Team"': '"DAL"',
    '"PosRank"': '75',
    '"AVGRank"': '172',
    '"AVGTier"': '7',
    '"Siegele3.2"': '163',
    '"Caban3.16"': '181',
  },
  {
    '""': '"172"',
    '"Rank"': '172',
    '"Player"': '"Daniel Jones"',
    '"POS"': '"QB"',
    '"Team"': '"NYG"',
    '"PosRank"': '24',
    '"AVGRank"': '174',
    '"AVGTier"': '8',
    '"Siegele3.2"': '171',
    '"Caban3.16"': '177',
  },
  {
    '""': '"173"',
    '"Rank"': '173',
    '"Player"': '"Demario Douglas"',
    '"POS"': '"WR"',
    '"Team"': '"NE"',
    '"PosRank"': '76',
    '"AVGRank"': '175',
    '"AVGTier"': '7',
    '"Siegele3.2"': '180',
    '"Caban3.16"': '170',
  },
  {
    '""': '"174"',
    '"Rank"': '174',
    '"Player"': '"Treylon Burks"',
    '"POS"': '"WR"',
    '"Team"': '"TEN"',
    '"PosRank"': '77',
    '"AVGRank"': '176',
    '"AVGTier"': '7',
    '"Siegele3.2"': '185',
    '"Caban3.16"': '167',
  },
  {
    '""': '"175"',
    '"Rank"': '175',
    '"Player"': '"J.K. Dobbins"',
    '"POS"': '"RB"',
    '"Team"': '"BAL"',
    '"PosRank"': '52',
    '"AVGRank"': '176.5',
    '"AVGTier"': '8',
    '"Siegele3.2"': '202',
    '"Caban3.16"': '151',
  },
  {
    '""': '"176"',
    '"Rank"': '176',
    '"Player"': '"Noah Fant"',
    '"POS"': '"TE"',
    '"Team"': '"SEA"',
    '"PosRank"': '23',
    '"AVGRank"': '176.5',
    '"AVGTier"': '8',
    '"Siegele3.2"': '169',
    '"Caban3.16"': '184',
  },
  {
    '""': '"177"',
    '"Rank"': '177',
    '"Player"': '"Chigoziem Okonkwo"',
    '"POS"': '"TE"',
    '"Team"': '"TEN"',
    '"PosRank"': '24',
    '"AVGRank"': '177.5',
    '"AVGTier"': '7',
    '"Siegele3.2"': '182',
    '"Caban3.16"': '173',
  },
  {
    '""': '"178"',
    '"Rank"': '178',
    '"Player"': '"Israel Abanikanda"',
    '"POS"': '"RB"',
    '"Team"': '"NYJ"',
    '"PosRank"': '53',
    '"AVGRank"': '177.5',
    '"AVGTier"': '8',
    '"Siegele3.2"': '170',
    '"Caban3.16"': '185',
  },
  {
    '""': '"179"',
    '"Rank"': '179',
    '"Player"': '"Elijah Moore"',
    '"POS"': '"WR"',
    '"Team"': '"CLE"',
    '"PosRank"': '78',
    '"AVGRank"': '179',
    '"AVGTier"': '8',
    '"Siegele3.2"': '198',
    '"Caban3.16"': '160',
  },
  {
    '""': '"180"',
    '"Rank"': '180',
    '"Player"': '"Adam Thielen"',
    '"POS"': '"WR"',
    '"Team"': '"CAR"',
    '"PosRank"': '79',
    '"AVGRank"': '179.5',
    '"AVGTier"': '7',
    '"Siegele3.2"': '187',
    '"Caban3.16"': '172',
  },
  {
    '""': '"181"',
    '"Rank"': '181',
    '"Player"': '"Audric Estime"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '54',
    '"AVGRank"': '179.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '172',
    '"Caban3.16"': '187',
  },
  {
    '""': '"182"',
    '"Rank"': '182',
    '"Player"': '"Keaton Mitchell"',
    '"POS"': '"RB"',
    '"Team"': '"BAL"',
    '"PosRank"': '55',
    '"AVGRank"': '180.5',
    '"AVGTier"': '8',
    '"Siegele3.2"': '175',
    '"Caban3.16"': '186',
  },
  {
    '""': '"183"',
    '"Rank"': '183',
    '"Player"': '"Antonio Gibson"',
    '"POS"': '"RB"',
    '"Team"': '"NE"',
    '"PosRank"': '56',
    '"AVGRank"': '181',
    '"AVGTier"': '7',
    '"Siegele3.2"': '188',
    '"Caban3.16"': '174',
  },
  {
    '""': '"184"',
    '"Rank"': '184',
    '"Player"': '"Bryce Young"',
    '"POS"': '"QB"',
    '"Team"': '"CAR"',
    '"PosRank"': '25',
    '"AVGRank"': '181.5',
    '"AVGTier"': '8',
    '"Siegele3.2"': '174',
    '"Caban3.16"': '189',
  },
  {
    '""': '"185"',
    '"Rank"': '185',
    '"Player"': '"Ricky Pearsall"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '80',
    '"AVGRank"': '181.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '161',
    '"Caban3.16"': '202',
  },
  {
    '""': '"186"',
    '"Rank"': '186',
    '"Player"': '"Elijah Mitchell"',
    '"POS"': '"RB"',
    '"Team"': '"SF"',
    '"PosRank"': '57',
    '"AVGRank"': '183',
    '"AVGTier"': '8',
    '"Siegele3.2"': '186',
    '"Caban3.16"': '180',
  },
  {
    '""': '"187"',
    '"Rank"': '187',
    '"Player"': '"Isaiah Likely"',
    '"POS"': '"TE"',
    '"Team"': '"BAL"',
    '"PosRank"': '25',
    '"AVGRank"': '183',
    '"AVGTier"': '8',
    '"Siegele3.2"': '176',
    '"Caban3.16"': '190',
  },
  {
    '""': '"188"',
    '"Rank"': '188',
    '"Player"': '"Baker Mayfield"',
    '"POS"': '"QB"',
    '"Team"': '"TB"',
    '"PosRank"': '26',
    '"AVGRank"': '185',
    '"AVGTier"': '8',
    '"Siegele3.2"': '179',
    '"Caban3.16"': '191',
  },
  {
    '""': '"189"',
    '"Rank"': '189',
    '"Player"': '"Andrei Iosivas"',
    '"POS"': '"WR"',
    '"Team"': '"CIN"',
    '"PosRank"': '81',
    '"AVGRank"': '188',
    '"AVGTier"': '8',
    '"Siegele3.2"': '184',
    '"Caban3.16"': '192',
  },
  {
    '""': '"190"',
    '"Rank"': '190',
    '"Player"': '"Tyler Allgeier"',
    '"POS"': '"RB"',
    '"Team"': '"ATL"',
    '"PosRank"': '58',
    '"AVGRank"': '191',
    '"AVGTier"': '8',
    '"Siegele3.2"': '189',
    '"Caban3.16"': '193',
  },
  {
    '""': '"191"',
    '"Rank"': '191',
    '"Player"': '"Hunter Henry"',
    '"POS"': '"TE"',
    '"Team"': '"NE"',
    '"PosRank"': '26',
    '"AVGRank"': '191',
    '"AVGTier"': '8',
    '"Siegele3.2"': '194',
    '"Caban3.16"': '188',
  },
  {
    '""': '"192"',
    '"Rank"': '192',
    '"Player"': '"Tyrone Tracy Jr."',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '59',
    '"AVGRank"': '189.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '211',
    '"Caban3.16"': '168',
  },
  {
    '""': '"193"',
    '"Rank"': '193',
    '"Player"': '"Dylan Laube"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '60',
    '"AVGRank"': '191',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '181',
    '"Caban3.16"': '201',
  },
  {
    '""': '"194"',
    '"Rank"': '194',
    '"Player"': '"Miles Sanders"',
    '"POS"': '"RB"',
    '"Team"': '"CAR"',
    '"PosRank"': '61',
    '"AVGRank"': '192',
    '"AVGTier"': '8',
    '"Siegele3.2"': '190',
    '"Caban3.16"': '194',
  },
  {
    '""': '"195"',
    '"Rank"': '195',
    '"Player"': '"Derek Carr"',
    '"POS"': '"QB"',
    '"Team"': '"NO"',
    '"PosRank"': '27',
    '"AVGRank"': '193',
    '"AVGTier"': '8',
    '"Siegele3.2"': '191',
    '"Caban3.16"': '195',
  },
  {
    '""': '"196"',
    '"Rank"': '196',
    '"Player"': '"Cade Otton"',
    '"POS"': '"TE"',
    '"Team"': '"TB"',
    '"PosRank"': '27',
    '"AVGRank"': '194',
    '"AVGTier"': '8',
    '"Siegele3.2"': '192',
    '"Caban3.16"': '196',
  },
  {
    '""': '"197"',
    '"Rank"': '197',
    '"Player"': '"Rondale Moore"',
    '"POS"': '"WR"',
    '"Team"': '"ATL"',
    '"PosRank"': '82',
    '"AVGRank"': '195',
    '"AVGTier"': '8',
    '"Siegele3.2"': '215',
    '"Caban3.16"': '175',
  },
  {
    '""': '"198"',
    '"Rank"': '198',
    '"Player"': '"Isaac Guerendo"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '62',
    '"AVGRank"': '195',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '193',
    '"Caban3.16"': '197',
  },
  {
    '""': '"199"',
    '"Rank"': '199',
    '"Player"': '"Rico Dowdle"',
    '"POS"': '"RB"',
    '"Team"': '"DAL"',
    '"PosRank"': '63',
    '"AVGRank"': '199.5',
    '"AVGTier"': '9',
    '"Siegele3.2"': '195',
    '"Caban3.16"': '204',
  },
  {
    '""': '"200"',
    '"Rank"': '200',
    '"Player"': '"Dameon Pierce"',
    '"POS"': '"RB"',
    '"Team"': '"HOU"',
    '"PosRank"': '64',
    '"AVGRank"': '204',
    '"AVGTier"': '9',
    '"Siegele3.2"': '205',
    '"Caban3.16"': '203',
  },
  {
    '""': '"201"',
    '"Rank"': '201',
    '"Player"': '"Jonathan Mingo"',
    '"POS"': '"WR"',
    '"Team"': '"CAR"',
    '"PosRank"': '83',
    '"AVGRank"': '201.5',
    '"AVGTier"': '9',
    '"Siegele3.2"': '197',
    '"Caban3.16"': '206',
  },
  {
    '""': '"202"',
    '"Rank"': '202',
    '"Player"': '"Darnell Mooney"',
    '"POS"': '"WR"',
    '"Team"': '"ATL"',
    '"PosRank"': '84',
    '"AVGRank"': '204.5',
    '"AVGTier"': '9',
    '"Siegele3.2"': '178',
    '"Caban3.16"': '231',
  },
  {
    '""': '"203"',
    '"Rank"': '203',
    '"Player"': '"Greg Dulcich"',
    '"POS"': '"TE"',
    '"Team"': '"DEN"',
    '"PosRank"': '28',
    '"AVGRank"': '205',
    '"AVGTier"': '9',
    '"Siegele3.2"': '203',
    '"Caban3.16"': '207',
  },
  {
    '""': '"204"',
    '"Rank"': '204',
    '"Player"': '"Geno Smith"',
    '"POS"': '"QB"',
    '"Team"': '"SEA"',
    '"PosRank"': '28',
    '"AVGRank"': '206',
    '"AVGTier"': '8',
    '"Siegele3.2"': '212',
    '"Caban3.16"': '200',
  },
  {
    '""': '"205"',
    '"Rank"': '205',
    '"Player"': '"Chris Rodriguez',
    '"POS"': ' Jr."',
    '"Team"': '"RB"',
    '"PosRank"': '""',
    '"AVGRank"': '65',
    '"AVGTier"': '206',
    '"Siegele3.2"': '8',
    '"Caban3.16"': '214',
  },
  {
    '""': '"206"',
    '"Rank"': '206',
    '"Player"': '"Zay Jones"',
    '"POS"': '"WR"',
    '"Team"': '"JAC"',
    '"PosRank"': '85',
    '"AVGRank"': '209',
    '"AVGTier"': '9',
    '"Siegele3.2"': '206',
    '"Caban3.16"': '212',
  },
  {
    '""': '"207"',
    '"Rank"': '207',
    '"Player"': '"J.J. McCarthy"',
    '"POS"': '"QB"',
    '"Team"': '"FA"',
    '"PosRank"': '29',
    '"AVGRank"': '208.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '209',
    '"Caban3.16"': '208',
  },
  {
    '""': '"208"',
    '"Rank"': '208',
    '"Player"': '"Luke McCaffrey"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '86',
    '"AVGRank"': '209',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '201',
    '"Caban3.16"': '217',
  },
  {
    '""': '"209"',
    '"Rank"': '209',
    '"Player"': '"Samaje Perine"',
    '"POS"': '"RB"',
    '"Team"': '"DEN"',
    '"PosRank"': '66',
    '"AVGRank"': '211',
    '"AVGTier"': '9',
    '"Siegele3.2"': '213',
    '"Caban3.16"': '209',
  },
  {
    '""': '"210"',
    '"Rank"': '210',
    '"Player"': '"Will Levis"',
    '"POS"': '"QB"',
    '"Team"': '"TEN"',
    '"PosRank"': '30',
    '"AVGRank"': '213.5',
    '"AVGTier"': '9',
    '"Siegele3.2"': '216',
    '"Caban3.16"': '211',
  },
  {
    '""': '"211"',
    '"Rank"': '211',
    '"Player"': '"Russell Wilson"',
    '"POS"': '"QB"',
    '"Team"': '"PIT"',
    '"PosRank"': '31',
    '"AVGRank"': '215',
    '"AVGTier"': '9',
    '"Siegele3.2"': '217',
    '"Caban3.16"': '213',
  },
  {
    '""': '"212"',
    '"Rank"': '212',
    '"Player"': '"Johnny Wilson"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '87',
    '"AVGRank"': '214',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '229',
    '"Caban3.16"': '199',
  },
  {
    '""': '"213"',
    '"Rank"': '213',
    '"Player"': '"Demarcus Robinson"',
    '"POS"': '"WR"',
    '"Team"': '"LAR"',
    '"PosRank"': '88',
    '"AVGRank"': '217',
    '"AVGTier"': '9',
    '"Siegele3.2"': '196',
    '"Caban3.16"': '238',
  },
  {
    '""': '"214"',
    '"Rank"': '214',
    '"Player"': '"Tyler Boyd"',
    '"POS"': '"WR"',
    '"Team"': '"CIN"',
    '"PosRank"': '89',
    '"AVGRank"': '221',
    '"AVGTier"': '9',
    '"Siegele3.2"': '232',
    '"Caban3.16"': '210',
  },
  {
    '""': '"215"',
    '"Rank"': '215',
    '"Player"': '"Ray Davis"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '67',
    '"AVGRank"': '220',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '225',
    '"Caban3.16"': '215',
  },
  {
    '""': '"216"',
    '"Rank"': '216',
    '"Player"': '"Malachi Corley"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '90',
    '"AVGRank"': '221',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '226',
    '"Caban3.16"': '216',
  },
  {
    '""': '"217"',
    '"Rank"': '217',
    '"Player"': '"Kenneth Gainwell"',
    '"POS"': '"RB"',
    '"Team"': '"PHI"',
    '"PosRank"': '68',
    '"AVGRank"': '222.5',
    '"AVGTier"': '10',
    '"Siegele3.2"': '227',
    '"Caban3.16"': '218',
  },
  {
    '""': '"218"',
    '"Rank"': '218',
    '"Player"': '"A.T. Perry"',
    '"POS"': '"WR"',
    '"Team"': '"NO"',
    '"PosRank"': '91',
    '"AVGRank"': '222.5',
    '"AVGTier"': '9',
    '"Siegele3.2"': '240',
    '"Caban3.16"': '205',
  },
  {
    '""': '"219"',
    '"Rank"': '219',
    '"Player"': '"Dalvin Cook"',
    '"POS"': '"RB"',
    '"Team"': '"BAL"',
    '"PosRank"': '69',
    '"AVGRank"': '223.5',
    '"AVGTier"': '9',
    '"Siegele3.2"': '233',
    '"Caban3.16"': '214',
  },
  {
    '""': '"220"',
    '"Rank"': '220',
    '"Player"': '"Isaiah Davis"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '70',
    '"AVGRank"': '223',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '207',
    '"Caban3.16"': '239',
  },
  {
    '""': '"221"',
    '"Rank"': '221',
    '"Player"': '"Joshua Palmer"',
    '"POS"': '"WR"',
    '"Team"': '"LAC"',
    '"PosRank"': '92',
    '"AVGRank"': '224.5',
    '"AVGTier"': '9',
    '"Siegele3.2"': '208',
    '"Caban3.16"': '241',
  },
  {
    '""': '"222"',
    '"Rank"': '222',
    '"Player"': '"Jaheim Bell"',
    '"POS"': '"TE"',
    '"Team"': '"FA"',
    '"PosRank"': '29',
    '"AVGRank"': '225.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '223',
    '"Caban3.16"': '228',
  },
  {
    '""': '"223"',
    '"Rank"': '223',
    '"Player"': '"Bo Nix"',
    '"POS"': '"QB"',
    '"Team"': '"FA"',
    '"PosRank"': '32',
    '"AVGRank"': '226',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '218',
    '"Caban3.16"': '234',
  },
  {
    '""': '"224"',
    '"Rank"': '224',
    '"Player"': '"Tank Bigsby"',
    '"POS"': '"RB"',
    '"Team"': '"JAC"',
    '"PosRank"': '71',
    '"AVGRank"': '227.5',
    '"AVGTier"': '10',
    '"Siegele3.2"': '230',
    '"Caban3.16"': '225',
  },
  {
    '""': '"225"',
    '"Rank"': '225',
    '"Player"': '"Tyler Conklin"',
    '"POS"': '"TE"',
    '"Team"': '"NYJ"',
    '"PosRank"': '30',
    '"AVGRank"': '227.5',
    '"AVGTier"': '9',
    '"Siegele3.2"': '220',
    '"Caban3.16"': '235',
  },
  {
    '""': '"226"',
    '"Rank"': '226',
    '"Player"': '"Jaden Shirden"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '72',
    '"AVGRank"': '226.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '224',
    '"Caban3.16"': '229',
  },
  {
    '""': '"227"',
    '"Rank"': '227',
    '"Player"': '"Juwan Johnson"',
    '"POS"': '"TE"',
    '"Team"': '"NO"',
    '"PosRank"': '31',
    '"AVGRank"': '231.5',
    '"AVGTier"': '10',
    '"Siegele3.2"': '236',
    '"Caban3.16"': '227',
  },
  {
    '""': '"228"',
    '"Rank"': '228',
    '"Player"': '"Brenden Rice"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '93',
    '"AVGRank"': '232.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '235',
    '"Caban3.16"': '230',
  },
  {
    '""': '"229"',
    '"Rank"': '229',
    '"Player"': '"Malik Washington"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '94',
    '"AVGRank"': '233',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '242',
    '"Caban3.16"': '224',
  },
  {
    '""': '"230"',
    '"Rank"': '230',
    '"Player"': '"Jacob Cowing"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '95',
    '"AVGRank"': '233.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '247',
    '"Caban3.16"': '220',
  },
  {
    '""': '"231"',
    '"Rank"': '231',
    '"Player"': '"Kimani Vidal"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '73',
    '"AVGRank"': '233.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '234',
    '"Caban3.16"': '233',
  },
  {
    '""': '"232"',
    '"Rank"': '232',
    '"Player"': '"Zach Evans"',
    '"POS"': '"RB"',
    '"Team"': '"LAR"',
    '"PosRank"': '74',
    '"AVGRank"': '235',
    '"AVGTier"': '10',
    '"Siegele3.2"': '238',
    '"Caban3.16"': '232',
  },
  {
    '""': '"233"',
    '"Rank"': '233',
    '"Player"': '"K.J. Osborn"',
    '"POS"': '"WR"',
    '"Team"': '"NE"',
    '"PosRank"': '96',
    '"AVGRank"': '238',
    '"AVGTier"': '10',
    '"Siegele3.2"': '255',
    '"Caban3.16"': '221',
  },
  {
    '""': '"234"',
    '"Rank"': '234',
    '"Player"': '"Tutu Atwell"',
    '"POS"': '"WR"',
    '"Team"': '"LAR"',
    '"PosRank"': '97',
    '"AVGRank"': '238.5',
    '"AVGTier"': '9',
    '"Siegele3.2"': '301',
    '"Caban3.16"': '176',
  },
  {
    '""': '"235"',
    '"Rank"': '235',
    '"Player"': '"Davis Allen"',
    '"POS"': '"TE"',
    '"Team"': '"LAR"',
    '"PosRank"': '32',
    '"AVGRank"': '240.5',
    '"AVGTier"': '10',
    '"Siegele3.2"': '262',
    '"Caban3.16"': '219',
  },
  {
    '""': '"236"',
    '"Rank"': '236',
    '"Player"': '"Cody Schrader"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '75',
    '"AVGRank"': '240',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '243',
    '"Caban3.16"': '237',
  },
  {
    '""': '"237"',
    '"Rank"': '237',
    '"Player"': '"Alexander Mattison"',
    '"POS"': '"RB"',
    '"Team"': '"LV"',
    '"PosRank"': '76',
    '"AVGRank"': '242',
    '"AVGTier"': '10',
    '"Siegele3.2"': '228',
    '"Caban3.16"': '256',
  },
  {
    '""': '"238"',
    '"Rank"': '238',
    '"Player"': '"George Holani"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '77',
    '"AVGRank"': '242',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '244',
    '"Caban3.16"': '240',
  },
  {
    '""': '"239"',
    '"Rank"': '239',
    '"Player"': '"Sean Tucker"',
    '"POS"': '"RB"',
    '"Team"': '"TB"',
    '"PosRank"': '78',
    '"AVGRank"': '243.5',
    '"AVGTier"': '10',
    '"Siegele3.2"': '245',
    '"Caban3.16"': '242',
  },
  {
    '""': '"240"',
    '"Rank"': '240',
    '"Player"': '"Tyler Higbee"',
    '"POS"': '"TE"',
    '"Team"': '"LAR"',
    '"PosRank"': '33',
    '"AVGRank"': '245',
    '"AVGTier"': '10',
    '"Siegele3.2"': '267',
    '"Caban3.16"': '223',
  },
  {
    '""': '"241"',
    '"Rank"': '241',
    '"Player"': '"Jase McClellan"',
    '"POS"': '"RB"',
    '"Team"': '"FA"',
    '"PosRank"': '79',
    '"AVGRank"': '244',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '252',
    '"Caban3.16"': '236',
  },
  {
    '""': '"242"',
    '"Rank"': '242',
    '"Player"': '"AJ Dillon"',
    '"POS"': '"RB"',
    '"Team"': '"GB"',
    '"PosRank"': '80',
    '"AVGRank"': '246',
    '"AVGTier"': '10',
    '"Siegele3.2"': '239',
    '"Caban3.16"': '253',
  },
  {
    '""': '"243"',
    '"Rank"': '243',
    '"Player"': '"Jermaine Burton"',
    '"POS"': '"WR"',
    '"Team"': '"FA"',
    '"PosRank"': '98',
    '"AVGRank"': '246.5',
    '"AVGTier"': 'NA',
    '"Siegele3.2"': '250',
    '"Caban3.16"': '243',
  },
  {
    '""': '"244"',
    '"Rank"': '244',
    '"Player"': '"Justice Hill"',
    '"POS"': '"RB"',
    '"Team"': '"BAL"',
    '"PosRank"': '81',
    '"AVGRank"': '248.5',
    '"AVGTier"': '10',
    '"Siegele3.2"': '253',
    '"Caban3.16"': '244',
  },
  {
    '""': '"245"',
    '"Rank"': '245',
    '"Player"': '"Irv Smith"',
    '"POS"': '"TE"',
    '"Team"': '"KC"',
    '"PosRank"': '34',
    '"AVGRank"': '249',
    '"AVGTier"': '10',
    '"Siegele3.2"': '272',
    '"Caban3.16"': '226',
  },
  {
    '""': '"246"',
    '"Rank"': '246',
    '"Player"': '"Zach Ertz"',
    '"POS"': '"TE"',
    '"Team"': '"WAS"',
    '"PosRank"': '35',
    '"AVGRank"': '249.5',
    '"AVGTier"': '10',
    '"Siegele3.2"': '204',
    '"Caban3.16"': '295',
  },
  {
    '""': '"247"',
    '"Rank"': '247',
    '"Player"': '"Jerick McKinnon"',
    '"POS"': '"RB"',
    '"Team"': '"KC"',
    '"PosRank"': '82',
    '"AVGRank"': '250',
    '"AVGTier"': '10',
    '"Siegele3.2"': '278',
    '"Caban3.16"': '222',
  },
  {
    '""': '"248"',
    '"Rank"': '248',
    '"Player"': '"Gus Edwards"',
    '"POS"': '"RB"',
    '"Team"': '"LAC"',
    '"PosRank"': '83',
    '"AVGRank"': '250',
    '"AVGTier"': '10',
    '"Siegele3.2"': '199',
    '"Caban3.16"': '301',
  },
  {
    '""': '"249"',
    '"Rank"': '249',
    '"Player"': '"Justyn Ross"',
    '"POS"': '"WR"',
    '"Team"': '"KC"',
    '"PosRank"': '99',
    '"AVGRank"': '250.5',
    '"AVGTier"': '10',
    '"Siegele3.2"': '254',
    '"Caban3.16"': '247',
  },
  {
    '""': '"250"',
    '"Rank"': '250',
    '"Player"': '"Sam Howell"',
    '"POS"': '"QB"',
    '"Team"': '"SEA"',
    '"PosRank"': '33',
    '"AVGRank"': '253',
    '"AVGTier"': '10',
    '"Siegele3.2"': '249',
    '"Caban3.16"': '257',
  },
];

module.exports = rvRedraftRankingsTEP;
