const te4for4PlayerStatsAppLastFiveWeeks = [
    
        {
            "\"Player Name\"": "\"Nate Adkins\"",
            "Team": "DEN",
            "G": "2",
            "Rec": "3",
            "RecYds": "19",
            "RecTD": "0",
            "Tgts": "3",
            "YPR": "7.50",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "1.9",
            "PPR": "4.9",
            "Snaps": "12/110",
            "%": "10.91%"
        },
        {
            "\"Player Name\"": "\"Jordan Akins\"",
            "Team": "CLE",
            "G": "3",
            "Rec": "3",
            "RecYds": "20",
            "RecTD": "0",
            "Tgts": "4",
            "YPR": "6.67",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "2.0",
            "PPR": "5.0",
            "Snaps": "47/230",
            "%": "20.43%"
        },
        {
            "\"Player Name\"": "\"Mo Alie-Cox\"",
            "Team": "IND",
            "G": "3",
            "Rec": "3",
            "RecYds": "67",
            "RecTD": "1",
            "Tgts": "3",
            "YPR": "22.33",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "12.7",
            "PPR": "15.7",
            "Snaps": "52/187",
            "%": "27.81%"
        },
        {
            "\"Player Name\"": "\"Mark Andrews\"",
            "Team": "BAL",
            "G": "4",
            "Rec": "20",
            "RecYds": "225",
            "RecTD": "3",
            "Tgts": "28",
            "YPR": "11.15",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "40.5",
            "PPR": "60.5",
            "Snaps": "224/275",
            "%": "81.45%"
        },
        {
            "\"Player Name\"": "\"John Bates\"",
            "Team": "WAS",
            "G": "4",
            "Rec": "8",
            "RecYds": "83",
            "RecTD": "0",
            "Tgts": "10",
            "YPR": "9.21",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "8.3",
            "PPR": "16.3",
            "Snaps": "110/275",
            "%": "40.00%"
        },
        {
            "\"Player Name\"": "\"Blake Bell\"",
            "Team": "KC",
            "G": "1",
            "Rec": "2",
            "RecYds": "12",
            "RecTD": "1",
            "Tgts": "3",
            "YPR": "6.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "7.2",
            "PPR": "9.2",
            "Snaps": "26/65",
            "%": "40.00%"
        },
        {
            "\"Player Name\"": "\"Daniel Bellinger\"",
            "Team": "NYG",
            "G": "4",
            "Rec": "4",
            "RecYds": "22",
            "RecTD": "0",
            "Tgts": "4",
            "YPR": "5.50",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "2.2",
            "PPR": "6.2",
            "Snaps": "107/267",
            "%": "40.07%"
        },
        {
            "\"Player Name\"": "\"Pharaoh Brown\"",
            "Team": "NE",
            "G": "1",
            "Rec": "2",
            "RecYds": "71",
            "RecTD": "1",
            "Tgts": "2",
            "YPR": "35.50",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "13.1",
            "PPR": "15.1",
            "Snaps": "25/72",
            "%": "34.72%"
        },
        {
            "\"Player Name\"": "\"Harrison Bryant\"",
            "Team": "CLE",
            "G": "3",
            "Rec": "3",
            "RecYds": "7",
            "RecTD": "1",
            "Tgts": "3",
            "YPR": "1.50",
            "RuAtt": "3",
            "RuYds": "6",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "1.33",
            "STD": "7.3",
            "PPR": "10.3",
            "Snaps": "64/214",
            "%": "29.91%"
        },
        {
            "\"Player Name\"": "\"Lawrence Cager\"",
            "Team": "NYG",
            "G": "1",
            "Rec": "2",
            "RecYds": "17",
            "RecTD": "0",
            "Tgts": "2",
            "YPR": "8.50",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "1.7",
            "PPR": "3.7",
            "Snaps": "20/70",
            "%": "28.57%"
        },
        {
            "\"Player Name\"": "\"Tyler Conklin\"",
            "Team": "NYJ",
            "G": "5",
            "Rec": "17",
            "RecYds": "203",
            "RecTD": "0",
            "Tgts": "23",
            "YPR": "10.38",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "20.3",
            "PPR": "37.3",
            "Snaps": "208/288",
            "%": "72.22%"
        },
        {
            "\"Player Name\"": "\"Josiah Deguara\"",
            "Team": "GB",
            "G": "3",
            "Rec": "7",
            "RecYds": "58",
            "RecTD": "0",
            "Tgts": "7",
            "YPR": "10.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "5.8",
            "PPR": "12.8",
            "Snaps": "70/165",
            "%": "42.42%"
        },
        {
            "\"Player Name\"": "\"Will Dissly\"",
            "Team": "SEA",
            "G": "2",
            "Rec": "5",
            "RecYds": "52",
            "RecTD": "0",
            "Tgts": "5",
            "YPR": "10.09",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "5.2",
            "PPR": "10.2",
            "Snaps": "54/123",
            "%": "43.90%"
        },
        {
            "\"Player Name\"": "\"Greg Dulcich\"",
            "Team": "DEN",
            "G": "1",
            "Rec": "2",
            "RecYds": "22",
            "RecTD": "0",
            "Tgts": "2",
            "YPR": "11.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "2.2",
            "PPR": "4.2",
            "Snaps": "21/64",
            "%": "32.81%"
        },
        {
            "\"Player Name\"": "\"Evan Engram\"",
            "Team": "JAX",
            "G": "5",
            "Rec": "29",
            "RecYds": "260",
            "RecTD": "0",
            "Tgts": "37",
            "YPR": "8.86",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "26.0",
            "PPR": "55.0",
            "Snaps": "276/364",
            "%": "75.82%"
        },
        {
            "\"Player Name\"": "\"Zach Ertz\"",
            "Team": "ARI",
            "G": "5",
            "Rec": "22",
            "RecYds": "146",
            "RecTD": "1",
            "Tgts": "34",
            "YPR": "5.93",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "20.6",
            "PPR": "42.6",
            "Snaps": "225/316",
            "%": "71.20%"
        },
        {
            "\"Player Name\"": "\"Gerald Everett\"",
            "Team": "LAC",
            "G": "4",
            "Rec": "13",
            "RecYds": "107",
            "RecTD": "0",
            "Tgts": "14",
            "YPR": "8.92",
            "RuAtt": "1",
            "RuYds": "2",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.50",
            "STD": "10.9",
            "PPR": "23.9",
            "Snaps": "166/280",
            "%": "59.29%"
        },
        {
            "\"Player Name\"": "\"Noah Fant\"",
            "Team": "SEA",
            "G": "3",
            "Rec": "10",
            "RecYds": "160",
            "RecTD": "0",
            "Tgts": "11",
            "YPR": "18.58",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "16.0",
            "PPR": "26.0",
            "Snaps": "106/202",
            "%": "52.48%"
        },
        {
            "\"Player Name\"": "\"Luke Farrell\"",
            "Team": "JAX",
            "G": "3",
            "Rec": "4",
            "RecYds": "30",
            "RecTD": "0",
            "Tgts": "4",
            "YPR": "8.33",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "3.0",
            "PPR": "7.0",
            "Snaps": "84/227",
            "%": "37.00%"
        },
        {
            "\"Player Name\"": "\"Jake Ferguson\"",
            "Team": "DAL",
            "G": "5",
            "Rec": "20",
            "RecYds": "175",
            "RecTD": "1",
            "Tgts": "28",
            "YPR": "7.82",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "23.5",
            "PPR": "43.5",
            "Snaps": "223/345",
            "%": "64.64%"
        },
        {
            "\"Player Name\"": "\"Pat Freiermuth\"",
            "Team": "PIT",
            "G": "4",
            "Rec": "8",
            "RecYds": "53",
            "RecTD": "2",
            "Tgts": "13",
            "YPR": "5.25",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "17.3",
            "PPR": "25.3",
            "Snaps": "152/238",
            "%": "63.87%"
        },
        {
            "\"Player Name\"": "\"Mike Gesicki\"",
            "Team": "NE",
            "G": "5",
            "Rec": "12",
            "RecYds": "116",
            "RecTD": "0",
            "Tgts": "17",
            "YPR": "11.42",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "11.6",
            "PPR": "23.6",
            "Snaps": "169/335",
            "%": "50.45%"
        },
        {
            "\"Player Name\"": "\"Dallas Goedert\"",
            "Team": "PHI",
            "G": "4",
            "Rec": "21",
            "RecYds": "205",
            "RecTD": "1",
            "Tgts": "27",
            "YPR": "9.75",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "26.5",
            "PPR": "47.5",
            "Snaps": "294/307",
            "%": "95.77%"
        },
        {
            "\"Player Name\"": "\"Jimmy Graham\"",
            "Team": "NO",
            "G": "1",
            "Rec": "1",
            "RecYds": "8",
            "RecTD": "1",
            "Tgts": "1",
            "YPR": "8.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "6.8",
            "PPR": "7.8",
            "Snaps": "17/61",
            "%": "27.87%"
        },
        {
            "\"Player Name\"": "\"Kylen Granson\"",
            "Team": "IND",
            "G": "5",
            "Rec": "13",
            "RecYds": "103",
            "RecTD": "1",
            "Tgts": "22",
            "YPR": "7.82",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "16.3",
            "PPR": "29.3",
            "Snaps": "186/343",
            "%": "54.23%"
        },
        {
            "\"Player Name\"": "\"Noah Gray\"",
            "Team": "KC",
            "G": "5",
            "Rec": "10",
            "RecYds": "133",
            "RecTD": "1",
            "Tgts": "15",
            "YPR": "15.30",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "19.3",
            "PPR": "29.3",
            "Snaps": "222/345",
            "%": "64.35%"
        },
        {
            "\"Player Name\"": "\"Peyton Hendershot\"",
            "Team": "DAL",
            "G": "2",
            "Rec": "1",
            "RecYds": "3",
            "RecTD": "0",
            "Tgts": "1",
            "YPR": "1.50",
            "RuAtt": "1",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "0.3",
            "PPR": "1.3",
            "Snaps": "68/168",
            "%": "40.48%"
        },
        {
            "\"Player Name\"": "\"Hunter Henry\"",
            "Team": "NE",
            "G": "4",
            "Rec": "17",
            "RecYds": "176",
            "RecTD": "2",
            "Tgts": "23",
            "YPR": "10.28",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "29.6",
            "PPR": "46.6",
            "Snaps": "237/281",
            "%": "84.34%"
        },
        {
            "\"Player Name\"": "\"Connor Heyward\"",
            "Team": "PIT",
            "G": "3",
            "Rec": "5",
            "RecYds": "42",
            "RecTD": "0",
            "Tgts": "10",
            "YPR": "5.72",
            "RuAtt": "1",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "4.2",
            "PPR": "9.2",
            "Snaps": "67/191",
            "%": "35.08%"
        },
        {
            "\"Player Name\"": "\"Tyler Higbee\"",
            "Team": "LAR",
            "G": "5",
            "Rec": "18",
            "RecYds": "216",
            "RecTD": "0",
            "Tgts": "29",
            "YPR": "11.47",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "21.6",
            "PPR": "39.6",
            "Snaps": "328/354",
            "%": "92.66%"
        },
        {
            "\"Player Name\"": "\"T.J. Hockenson\"",
            "Team": "MIN",
            "G": "5",
            "Rec": "30",
            "RecYds": "254",
            "RecTD": "2",
            "Tgts": "39",
            "YPR": "9.15",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "1",
            "YPC": "0.00",
            "STD": "35.4",
            "PPR": "65.4",
            "Snaps": "270/324",
            "%": "83.33%"
        },
        {
            "\"Player Name\"": "\"Austin Hooper\"",
            "Team": "LV",
            "G": "4",
            "Rec": "6",
            "RecYds": "62",
            "RecTD": "0",
            "Tgts": "7",
            "YPR": "11.63",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "6.2",
            "PPR": "12.2",
            "Snaps": "121/236",
            "%": "51.27%"
        },
        {
            "\"Player Name\"": "\"Brycen Hopkins\"",
            "Team": "LAR",
            "G": "2",
            "Rec": "2",
            "RecYds": "26",
            "RecTD": "0",
            "Tgts": "3",
            "YPR": "13.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "2.6",
            "PPR": "4.6",
            "Snaps": "31/163",
            "%": "19.02%"
        },
        {
            "\"Player Name\"": "\"Tanner Hudson\"",
            "Team": "CIN",
            "G": "2",
            "Rec": "4",
            "RecYds": "48",
            "RecTD": "0",
            "Tgts": "6",
            "YPR": "12.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "4.8",
            "PPR": "8.8",
            "Snaps": "59/130",
            "%": "45.38%"
        },
        {
            "\"Player Name\"": "\"Hayden Hurst\"",
            "Team": "CAR",
            "G": "5",
            "Rec": "13",
            "RecYds": "100",
            "RecTD": "1",
            "Tgts": "19",
            "YPR": "7.97",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "16.0",
            "PPR": "29.0",
            "Snaps": "201/359",
            "%": "55.99%"
        },
        {
            "\"Player Name\"": "\"Juwan Johnson\"",
            "Team": "NO",
            "G": "3",
            "Rec": "7",
            "RecYds": "61",
            "RecTD": "0",
            "Tgts": "12",
            "YPR": "8.17",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "6.1",
            "PPR": "13.1",
            "Snaps": "154/203",
            "%": "75.86%"
        },
        {
            "\"Player Name\"": "\"Brevin Jordan\"",
            "Team": "HOU",
            "G": "2",
            "Rec": "4",
            "RecYds": "40",
            "RecTD": "1",
            "Tgts": "4",
            "YPR": "10.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "10.0",
            "PPR": "14.0",
            "Snaps": "25/140",
            "%": "17.86%"
        },
        {
            "\"Player Name\"": "\"Travis Kelce\"",
            "Team": "KC",
            "G": "4",
            "Rec": "27",
            "RecYds": "222",
            "RecTD": "3",
            "Tgts": "37",
            "YPR": "8.27",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "40.2",
            "PPR": "67.2",
            "Snaps": "184/280",
            "%": "65.71%"
        },
        {
            "\"Player Name\"": "\"Dalton Kincaid\"",
            "Team": "BUF",
            "G": "5",
            "Rec": "17",
            "RecYds": "118",
            "RecTD": "0",
            "Tgts": "19",
            "YPR": "6.57",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "11.8",
            "PPR": "28.8",
            "Snaps": "199/333",
            "%": "59.76%"
        },
        {
            "\"Player Name\"": "\"George Kittle\"",
            "Team": "SF",
            "G": "5",
            "Rec": "17",
            "RecYds": "215",
            "RecTD": "3",
            "Tgts": "23",
            "YPR": "12.10",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "39.5",
            "PPR": "56.5",
            "Snaps": "280/334",
            "%": "83.83%"
        },
        {
            "\"Player Name\"": "\"Cole Kmet\"",
            "Team": "CHI",
            "G": "5",
            "Rec": "23",
            "RecYds": "231",
            "RecTD": "3",
            "Tgts": "29",
            "YPR": "9.97",
            "RuAtt": "2",
            "RuYds": "1",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.20",
            "STD": "41.2",
            "PPR": "64.2",
            "Snaps": "253/314",
            "%": "80.57%"
        },
        {
            "\"Player Name\"": "\"Dawson Knox\"",
            "Team": "BUF",
            "G": "5",
            "Rec": "11",
            "RecYds": "75",
            "RecTD": "1",
            "Tgts": "19",
            "YPR": "8.07",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "13.5",
            "PPR": "24.5",
            "Snaps": "225/333",
            "%": "67.57%"
        },
        {
            "\"Player Name\"": "\"Tucker Kraft\"",
            "Team": "GB",
            "G": "1",
            "Rec": "2",
            "RecYds": "5",
            "RecTD": "0",
            "Tgts": "2",
            "YPR": "2.50",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "0.5",
            "PPR": "2.5",
            "Snaps": "13/57",
            "%": "22.81%"
        },
        {
            "\"Player Name\"": "\"Sam LaPorta\"",
            "Team": "DET",
            "G": "5",
            "Rec": "25",
            "RecYds": "289",
            "RecTD": "3",
            "Tgts": "31",
            "YPR": "12.11",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "46.9",
            "PPR": "71.9",
            "Snaps": "276/341",
            "%": "80.94%"
        },
        {
            "\"Player Name\"": "\"Marcedes Lewis\"",
            "Team": "CHI",
            "G": "1",
            "Rec": "1",
            "RecYds": "8",
            "RecTD": "0",
            "Tgts": "1",
            "YPR": "8.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "0.8",
            "PPR": "1.8",
            "Snaps": "21/72",
            "%": "29.17%"
        },
        {
            "\"Player Name\"": "\"Isaiah Likely\"",
            "Team": "BAL",
            "G": "3",
            "Rec": "3",
            "RecYds": "32",
            "RecTD": "0",
            "Tgts": "4",
            "YPR": "10.67",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "3.2",
            "PPR": "6.2",
            "Snaps": "90/211",
            "%": "42.65%"
        },
        {
            "\"Player Name\"": "\"Will Mallory\"",
            "Team": "IND",
            "G": "1",
            "Rec": "2",
            "RecYds": "49",
            "RecTD": "0",
            "Tgts": "2",
            "YPR": "24.50",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "4.9",
            "PPR": "6.9",
            "Snaps": "11/57",
            "%": "19.30%"
        },
        {
            "\"Player Name\"": "\"Chris Manhertz\"",
            "Team": "DEN",
            "G": "1",
            "Rec": "1",
            "RecYds": "10",
            "RecTD": "0",
            "Tgts": "1",
            "YPR": "10.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "1.0",
            "PPR": "2.0",
            "Snaps": "21/48",
            "%": "43.75%"
        },
        {
            "\"Player Name\"": "\"Michael Mayer\"",
            "Team": "LV",
            "G": "2",
            "Rec": "3",
            "RecYds": "41",
            "RecTD": "0",
            "Tgts": "4",
            "YPR": "10.75",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "4.1",
            "PPR": "7.1",
            "Snaps": "58/104",
            "%": "55.77%"
        },
        {
            "\"Player Name\"": "\"Trey McBride\"",
            "Team": "ARI",
            "G": "5",
            "Rec": "8",
            "RecYds": "79",
            "RecTD": "0",
            "Tgts": "10",
            "YPR": "8.60",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "7.9",
            "PPR": "15.9",
            "Snaps": "124/316",
            "%": "39.24%"
        },
        {
            "\"Player Name\"": "\"Foster Moreau\"",
            "Team": "NO",
            "G": "2",
            "Rec": "3",
            "RecYds": "26",
            "RecTD": "1",
            "Tgts": "3",
            "YPR": "8.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "8.6",
            "PPR": "11.6",
            "Snaps": "84/149",
            "%": "56.38%"
        },
        {
            "\"Player Name\"": "\"Johnny Mundt\"",
            "Team": "MIN",
            "G": "1",
            "Rec": "1",
            "RecYds": "11",
            "RecTD": "0",
            "Tgts": "1",
            "YPR": "11.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "1.1",
            "PPR": "2.1",
            "Snaps": "10/72",
            "%": "13.89%"
        },
        {
            "\"Player Name\"": "\"Luke Musgrave\"",
            "Team": "GB",
            "G": "5",
            "Rec": "18",
            "RecYds": "159",
            "RecTD": "0",
            "Tgts": "23",
            "YPR": "8.80",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "15.9",
            "PPR": "33.9",
            "Snaps": "211/304",
            "%": "69.41%"
        },
        {
            "\"Player Name\"": "\"David Njoku\"",
            "Team": "CLE",
            "G": "4",
            "Rec": "16",
            "RecYds": "138",
            "RecTD": "0",
            "Tgts": "18",
            "YPR": "9.17",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "1",
            "YPC": "0.00",
            "STD": "11.8",
            "PPR": "27.8",
            "Snaps": "228/301",
            "%": "75.75%"
        },
        {
            "\"Player Name\"": "\"Andrew Ogletree\"",
            "Team": "IND",
            "G": "4",
            "Rec": "7",
            "RecYds": "95",
            "RecTD": "1",
            "Tgts": "10",
            "YPR": "13.75",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "15.5",
            "PPR": "22.5",
            "Snaps": "111/286",
            "%": "38.81%"
        },
        {
            "\"Player Name\"": "\"Chigoziem Okonkwo\"",
            "Team": "TEN",
            "G": "4",
            "Rec": "15",
            "RecYds": "104",
            "RecTD": "0",
            "Tgts": "20",
            "YPR": "6.84",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "10.4",
            "PPR": "25.4",
            "Snaps": "162/239",
            "%": "67.78%"
        },
        {
            "\"Player Name\"": "\"Josh Oliver\"",
            "Team": "MIN",
            "G": "4",
            "Rec": "8",
            "RecYds": "64",
            "RecTD": "1",
            "Tgts": "10",
            "YPR": "8.54",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "1",
            "YPC": "0.00",
            "STD": "10.4",
            "PPR": "18.4",
            "Snaps": "102/276",
            "%": "36.96%"
        },
        {
            "\"Player Name\"": "\"Cade Otton\"",
            "Team": "TB",
            "G": "4",
            "Rec": "12",
            "RecYds": "89",
            "RecTD": "1",
            "Tgts": "15",
            "YPR": "9.17",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "14.9",
            "PPR": "26.9",
            "Snaps": "249/257",
            "%": "96.89%"
        },
        {
            "\"Player Name\"": "\"Donald Parham\"",
            "Team": "LAC",
            "G": "3",
            "Rec": "6",
            "RecYds": "33",
            "RecTD": "3",
            "Tgts": "7",
            "YPR": "5.44",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "21.3",
            "PPR": "27.3",
            "Snaps": "108/215",
            "%": "50.23%"
        },
        {
            "\"Player Name\"": "\"Colby Parkinson\"",
            "Team": "SEA",
            "G": "3",
            "Rec": "6",
            "RecYds": "87",
            "RecTD": "0",
            "Tgts": "9",
            "YPR": "13.72",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "8.7",
            "PPR": "14.7",
            "Snaps": "112/198",
            "%": "56.57%"
        },
        {
            "\"Player Name\"": "\"Kyle Pitts\"",
            "Team": "ATL",
            "G": "5",
            "Rec": "18",
            "RecYds": "208",
            "RecTD": "0",
            "Tgts": "32",
            "YPR": "12.13",
            "RuAtt": "1",
            "RuYds": "-4",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "-0.80",
            "STD": "20.4",
            "PPR": "38.4",
            "Snaps": "219/336",
            "%": "65.18%"
        },
        {
            "\"Player Name\"": "\"MyCole Pruitt\"",
            "Team": "ATL",
            "G": "2",
            "Rec": "2",
            "RecYds": "32",
            "RecTD": "0",
            "Tgts": "2",
            "YPR": "16.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "3.2",
            "PPR": "5.2",
            "Snaps": "53/144",
            "%": "36.81%"
        },
        {
            "\"Player Name\"": "\"Teagan Quitoriano\"",
            "Team": "HOU",
            "G": "2",
            "Rec": "2",
            "RecYds": "33",
            "RecTD": "0",
            "Tgts": "2",
            "YPR": "16.50",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "3.3",
            "PPR": "5.3",
            "Snaps": "45/135",
            "%": "33.33%"
        },
        {
            "\"Player Name\"": "\"Giovanni Ricci\"",
            "Team": "CAR",
            "G": "1",
            "Rec": "1",
            "RecYds": "2",
            "RecTD": "0",
            "Tgts": "1",
            "YPR": "2.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "0.2",
            "PPR": "1.2",
            "Snaps": "8/77",
            "%": "10.39%"
        },
        {
            "\"Player Name\"": "\"Jeremy Ruckert\"",
            "Team": "NYJ",
            "G": "2",
            "Rec": "3",
            "RecYds": "28",
            "RecTD": "0",
            "Tgts": "3",
            "YPR": "7.50",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "2.8",
            "PPR": "5.8",
            "Snaps": "44/124",
            "%": "35.48%"
        },
        {
            "\"Player Name\"": "\"Drew Sample\"",
            "Team": "CIN",
            "G": "2",
            "Rec": "2",
            "RecYds": "6",
            "RecTD": "0",
            "Tgts": "2",
            "YPR": "3.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "0.6",
            "PPR": "2.6",
            "Snaps": "51/130",
            "%": "39.23%"
        },
        {
            "\"Player Name\"": "\"Luke Schoonmaker\"",
            "Team": "DAL",
            "G": "1",
            "Rec": "1",
            "RecYds": "1",
            "RecTD": "1",
            "Tgts": "1",
            "YPR": "1.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "6.1",
            "PPR": "7.1",
            "Snaps": "31/87",
            "%": "35.63%"
        },
        {
            "\"Player Name\"": "\"Dalton Schultz\"",
            "Team": "HOU",
            "G": "5",
            "Rec": "17",
            "RecYds": "154",
            "RecTD": "2",
            "Tgts": "27",
            "YPR": "8.56",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "27.4",
            "PPR": "44.4",
            "Snaps": "229/346",
            "%": "66.18%"
        },
        {
            "\"Player Name\"": "\"Ben Sims\"",
            "Team": "GB",
            "G": "1",
            "Rec": "1",
            "RecYds": "12",
            "RecTD": "0",
            "Tgts": "1",
            "YPR": "12.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "1.2",
            "PPR": "2.2",
            "Snaps": "9/58",
            "%": "15.52%"
        },
        {
            "\"Player Name\"": "\"Stone Smartt\"",
            "Team": "LAC",
            "G": "1",
            "Rec": "1",
            "RecYds": "24",
            "RecTD": "0",
            "Tgts": "1",
            "YPR": "24.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "2.4",
            "PPR": "3.4",
            "Snaps": "22/68",
            "%": "32.35%"
        },
        {
            "\"Player Name\"": "\"Jonnu Smith\"",
            "Team": "ATL",
            "G": "4",
            "Rec": "21",
            "RecYds": "246",
            "RecTD": "0",
            "Tgts": "27",
            "YPR": "11.54",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "1",
            "YPC": "0.00",
            "STD": "22.6",
            "PPR": "43.6",
            "Snaps": "184/284",
            "%": "64.79%"
        },
        {
            "\"Player Name\"": "\"Irv Smith Jr.\"",
            "Team": "CIN",
            "G": "2",
            "Rec": "5",
            "RecYds": "27",
            "RecTD": "0",
            "Tgts": "9",
            "YPR": "5.34",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "2.7",
            "PPR": "7.7",
            "Snaps": "76/116",
            "%": "65.52%"
        },
        {
            "\"Player Name\"": "\"Durham Smythe\"",
            "Team": "MIA",
            "G": "4",
            "Rec": "11",
            "RecYds": "123",
            "RecTD": "0",
            "Tgts": "15",
            "YPR": "11.90",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "12.3",
            "PPR": "23.3",
            "Snaps": "209/268",
            "%": "77.99%"
        },
        {
            "\"Player Name\"": "\"Jack Stoll\"",
            "Team": "PHI",
            "G": "2",
            "Rec": "2",
            "RecYds": "10",
            "RecTD": "0",
            "Tgts": "3",
            "YPR": "5.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "1.0",
            "PPR": "3.0",
            "Snaps": "63/159",
            "%": "39.62%"
        },
        {
            "\"Player Name\"": "\"Brenton Strange\"",
            "Team": "JAX",
            "G": "1",
            "Rec": "2",
            "RecYds": "7",
            "RecTD": "0",
            "Tgts": "2",
            "YPR": "3.50",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "0.7",
            "PPR": "2.7",
            "Snaps": "21/73",
            "%": "28.77%"
        },
        {
            "\"Player Name\"": "\"Geoff Swaim\"",
            "Team": "ARI",
            "G": "1",
            "Rec": "2",
            "RecYds": "22",
            "RecTD": "0",
            "Tgts": "2",
            "YPR": "11.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "2.2",
            "PPR": "4.2",
            "Snaps": "22/57",
            "%": "38.60%"
        },
        {
            "\"Player Name\"": "\"Ian Thomas\"",
            "Team": "CAR",
            "G": "2",
            "Rec": "2",
            "RecYds": "36",
            "RecTD": "0",
            "Tgts": "3",
            "YPR": "18.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "3.6",
            "PPR": "5.6",
            "Snaps": "28/150",
            "%": "18.67%"
        },
        {
            "\"Player Name\"": "\"Logan Thomas\"",
            "Team": "WAS",
            "G": "4",
            "Rec": "18",
            "RecYds": "183",
            "RecTD": "2",
            "Tgts": "25",
            "YPR": "11.00",
            "RuAtt": "1",
            "RuYds": "2",
            "RuTD": "0",
            "Fum": "1",
            "YPC": "0.50",
            "STD": "28.5",
            "PPR": "46.5",
            "Snaps": "204/292",
            "%": "69.86%"
        },
        {
            "\"Player Name\"": "\"Robert Tonyan\"",
            "Team": "CHI",
            "G": "2",
            "Rec": "4",
            "RecYds": "28",
            "RecTD": "0",
            "Tgts": "4",
            "YPR": "7.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "2.8",
            "PPR": "6.8",
            "Snaps": "40/136",
            "%": "29.41%"
        },
        {
            "\"Player Name\"": "\"Adam Trautman\"",
            "Team": "DEN",
            "G": "2",
            "Rec": "9",
            "RecYds": "60",
            "RecTD": "1",
            "Tgts": "10",
            "YPR": "6.65",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "12.0",
            "PPR": "21.0",
            "Snaps": "103/127",
            "%": "81.10%"
        },
        {
            "\"Player Name\"": "\"Tommy Tremble\"",
            "Team": "CAR",
            "G": "2",
            "Rec": "2",
            "RecYds": "16",
            "RecTD": "1",
            "Tgts": "2",
            "YPR": "8.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "7.6",
            "PPR": "9.6",
            "Snaps": "36/150",
            "%": "24.00%"
        },
        {
            "\"Player Name\"": "\"Cole Turner\"",
            "Team": "WAS",
            "G": "4",
            "Rec": "8",
            "RecYds": "82",
            "RecTD": "0",
            "Tgts": "12",
            "YPR": "11.31",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "8.2",
            "PPR": "16.2",
            "Snaps": "75/268",
            "%": "27.99%"
        },
        {
            "\"Player Name\"": "\"C.J. Uzomah\"",
            "Team": "NYJ",
            "G": "3",
            "Rec": "4",
            "RecYds": "22",
            "RecTD": "1",
            "Tgts": "4",
            "YPR": "5.33",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "8.2",
            "PPR": "12.2",
            "Snaps": "78/187",
            "%": "41.71%"
        },
        {
            "\"Player Name\"": "\"Darren Waller\"",
            "Team": "NYG",
            "G": "5",
            "Rec": "23",
            "RecYds": "239",
            "RecTD": "0",
            "Tgts": "34",
            "YPR": "9.82",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "23.9",
            "PPR": "46.9",
            "Snaps": "275/335",
            "%": "82.09%"
        },
        {
            "\"Player Name\"": "\"Darnell Washington\"",
            "Team": "PIT",
            "G": "1",
            "Rec": "1",
            "RecYds": "10",
            "RecTD": "0",
            "Tgts": "1",
            "YPR": "10.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "1.0",
            "PPR": "2.0",
            "Snaps": "25/59",
            "%": "42.37%"
        },
        {
            "\"Player Name\"": "\"David Wells\"",
            "Team": "TB",
            "G": "1",
            "Rec": "2",
            "RecYds": "-10",
            "RecTD": "0",
            "Tgts": "2",
            "YPR": "-5.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "-1.0",
            "PPR": "1.0",
            "Snaps": "18/71",
            "%": "25.35%"
        },
        {
            "\"Player Name\"": "\"Trevon Wesco\"",
            "Team": "TEN",
            "G": "1",
            "Rec": "1",
            "RecYds": "21",
            "RecTD": "0",
            "Tgts": "1",
            "YPR": "21.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "2.1",
            "PPR": "3.1",
            "Snaps": "28/60",
            "%": "46.67%"
        },
        {
            "\"Player Name\"": "\"Josh Whyle\"",
            "Team": "TEN",
            "G": "2",
            "Rec": "3",
            "RecYds": "33",
            "RecTD": "1",
            "Tgts": "3",
            "YPR": "10.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "9.3",
            "PPR": "12.3",
            "Snaps": "41/126",
            "%": "32.54%"
        },
        {
            "\"Player Name\"": "\"Mitchell Wilcox\"",
            "Team": "CIN",
            "G": "2",
            "Rec": "3",
            "RecYds": "17",
            "RecTD": "0",
            "Tgts": "4",
            "YPR": "6.00",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "1.7",
            "PPR": "4.7",
            "Snaps": "51/130",
            "%": "39.23%"
        },
        {
            "\"Player Name\"": "\"Brock Wright\"",
            "Team": "DET",
            "G": "2",
            "Rec": "5",
            "RecYds": "33",
            "RecTD": "0",
            "Tgts": "5",
            "YPR": "6.92",
            "RuAtt": "0",
            "RuYds": "0",
            "RuTD": "0",
            "Fum": "0",
            "YPC": "0.00",
            "STD": "3.3",
            "PPR": "8.3",
            "Snaps": "64/130",
            "%": "49.23%"
        },
        
    ]

    module.exports = te4for4PlayerStatsAppLastFiveWeeks;