const te4for4FantasyPointsBrowserLastFiveWeeks = [
	{
		"Player": "\"Dallas Goedert\"",
		"Pos": "TE",
		"Team": "PHI",
		"G": "4",
		"W1": "7.1",
		"W2": "6.8",
		"W3": "27.0",
		"W4": "13.2",
		"\"PPR Pts\"": "54.1",
		"\"PPR Pts/G\"": "13.5"
	},
	{
		"Player": "\"George Kittle\"",
		"Pos": "TE",
		"Team": "SF",
		"G": "3",
		"W1": "8.0",
		"W2": "20.6",
		"W3": "-",
		"W4": "14.5",
		"\"PPR Pts\"": "43.1",
		"\"PPR Pts/G\"": "14.4"
	},
	{
		"Player": "\"Brock Bowers\"",
		"Pos": "TE",
		"Team": "LV",
		"G": "4",
		"W1": "11.8",
		"W2": "18.8",
		"W3": "7.1",
		"W4": "5.1",
		"\"PPR Pts\"": "42.8",
		"\"PPR Pts/G\"": "10.7"
	},
	{
		"Player": "\"Cole Kmet\"",
		"Pos": "TE",
		"Team": "CHI",
		"G": "4",
		"W1": "1.4",
		"W2": "6.7",
		"W3": "25.7",
		"W4": "6.4",
		"\"PPR Pts\"": "40.2",
		"\"PPR Pts/G\"": "10.1"
	},
	{
		"Player": "\"Pat Freiermuth\"",
		"Pos": "TE",
		"Team": "PIT",
		"G": "4",
		"W1": "6.7",
		"W2": "7.9",
		"W3": "7.3",
		"W4": "16.7",
		"\"PPR Pts\"": "38.6",
		"\"PPR Pts/G\"": "9.7"
	},
	{
		"Player": "\"Isaiah Likely\"",
		"Pos": "TE",
		"Team": "BAL",
		"G": "4",
		"W1": "26.1",
		"W2": "4.6",
		"W3": "1.4",
		"W4": "3.6",
		"\"PPR Pts\"": "35.7",
		"\"PPR Pts/G\"": "8.9"
	},
	{
		"Player": "\"Dalton Kincaid\"",
		"Pos": "TE",
		"Team": "BUF",
		"G": "4",
		"W1": "2.1",
		"W2": "7.3",
		"W3": "13.1",
		"W4": "9.7",
		"\"PPR Pts\"": "32.2",
		"\"PPR Pts/G\"": "8.1"
	},
	{
		"Player": "\"Trey McBride\"",
		"Pos": "TE",
		"Team": "ARI",
		"G": "3",
		"W1": "8.0",
		"W2": "18.7",
		"W3": "5.5",
		"W4": "-",
		"\"PPR Pts\"": "32.2",
		"\"PPR Pts/G\"": "10.7"
	},
	{
		"Player": "\"Zach Ertz\"",
		"Pos": "TE",
		"Team": "WAS",
		"G": "4",
		"W1": "5.8",
		"W2": "10.2",
		"W3": "8.8",
		"W4": "7.2",
		"\"PPR Pts\"": "32.0",
		"\"PPR Pts/G\"": "8.0"
	},
	{
		"Player": "\"Jake Ferguson\"",
		"Pos": "TE",
		"Team": "DAL",
		"G": "3",
		"W1": "4.5",
		"W2": "-",
		"W3": "15.5",
		"W4": "11.9",
		"\"PPR Pts\"": "31.9",
		"\"PPR Pts/G\"": "10.6"
	},
	{
		"Player": "\"Tucker Kraft\"",
		"Pos": "TE",
		"Team": "GB",
		"G": "4",
		"W1": "5.7",
		"W2": "3.6",
		"W3": "4.4",
		"W4": "17.3",
		"\"PPR Pts\"": "31.0",
		"\"PPR Pts/G\"": "7.8"
	},
	{
		"Player": "\"Travis Kelce\"",
		"Pos": "TE",
		"Team": "KC",
		"G": "4",
		"W1": "6.4",
		"W2": "1.6",
		"W3": "7.0",
		"W4": "15.9",
		"\"PPR Pts\"": "30.9",
		"\"PPR Pts/G\"": "7.7"
	},
	{
		"Player": "\"Mike Gesicki\"",
		"Pos": "TE",
		"Team": "CIN",
		"G": "4",
		"W1": "4.8",
		"W2": "16.1",
		"W3": "8.7",
		"W4": "0.1",
		"\"PPR Pts\"": "29.7",
		"\"PPR Pts/G\"": "7.4"
	},
	{
		"Player": "\"Hunter Henry\"",
		"Pos": "TE",
		"Team": "NE",
		"G": "4",
		"W1": "3.8",
		"W2": "18.9",
		"W3": "2.9",
		"W4": "3.2",
		"\"PPR Pts\"": "28.8",
		"\"PPR Pts/G\"": "7.2"
	},
	{
		"Player": "\"Sam LaPorta\"",
		"Pos": "TE",
		"Team": "DET",
		"G": "4",
		"W1": "8.5",
		"W2": "3.3",
		"W3": "5.6",
		"W4": "9.3",
		"\"PPR Pts\"": "26.7",
		"\"PPR Pts/G\"": "6.7"
	},
	{
		"Player": "\"Kyle Pitts\"",
		"Pos": "TE",
		"Team": "ATL",
		"G": "4",
		"W1": "11.6",
		"W2": "5.0",
		"W3": "7.9",
		"W4": "0.0",
		"\"PPR Pts\"": "24.5",
		"\"PPR Pts/G\"": "6.1"
	},
	{
		"Player": "\"Tyler Conklin\"",
		"Pos": "TE",
		"Team": "NYJ",
		"G": "4",
		"W1": "1.6",
		"W2": "2.0",
		"W3": "14.3",
		"W4": "5.7",
		"\"PPR Pts\"": "23.6",
		"\"PPR Pts/G\"": "5.9"
	},
	{
		"Player": "\"Brenton Strange\"",
		"Pos": "TE",
		"Team": "JAX",
		"G": "4",
		"W1": "0.0",
		"W2": "9.5",
		"W3": "9.2",
		"W4": "4.9",
		"\"PPR Pts\"": "23.6",
		"\"PPR Pts/G\"": "5.9"
	},
	{
		"Player": "\"Colby Parkinson\"",
		"Pos": "TE",
		"Team": "LAR",
		"G": "4",
		"W1": "8.7",
		"W2": "2.2",
		"W3": "5.1",
		"W4": "7.3",
		"\"PPR Pts\"": "23.3",
		"\"PPR Pts/G\"": "5.8"
	},
	{
		"Player": "\"Noah Fant\"",
		"Pos": "TE",
		"Team": "SEA",
		"G": "4",
		"W1": "3.1",
		"W2": "2.4",
		"W3": "12.0",
		"W4": "4.6",
		"\"PPR Pts\"": "22.1",
		"\"PPR Pts/G\"": "5.5"
	},
	{
		"Player": "\"Cade Otton\"",
		"Pos": "TE",
		"Team": "TB",
		"G": "4",
		"W1": "1.5",
		"W2": "-0.4",
		"W3": "9.7",
		"W4": "11.2",
		"\"PPR Pts\"": "22.0",
		"\"PPR Pts/G\"": "5.5"
	},
	{
		"Player": "\"Taysom Hill\"",
		"Pos": "TE",
		"Team": "NO",
		"G": "3",
		"W1": "4.6",
		"W2": "2.9",
		"W3": "-",
		"W4": "14.4",
		"\"PPR Pts\"": "21.9",
		"\"PPR Pts/G\"": "7.3"
	},
	{
		"Player": "\"Erick All\"",
		"Pos": "TE",
		"Team": "CIN",
		"G": "4",
		"W1": "0.0",
		"W2": "7.2",
		"W3": "6.2",
		"W4": "6.8",
		"\"PPR Pts\"": "20.2",
		"\"PPR Pts/G\"": "5.1"
	},
	{
		"Player": "\"Chigoziem Okonkwo\"",
		"Pos": "TE",
		"Team": "TEN",
		"G": "4",
		"W1": "9.5",
		"W2": "4.6",
		"W3": "3.5",
		"W4": "1.5",
		"\"PPR Pts\"": "19.1",
		"\"PPR Pts/G\"": "4.8"
	},
	{
		"Player": "\"Austin Hooper\"",
		"Pos": "TE",
		"Team": "NE",
		"G": "4",
		"W1": "5.1",
		"W2": "1.5",
		"W3": "2.9",
		"W4": "9.3",
		"\"PPR Pts\"": "18.8",
		"\"PPR Pts/G\"": "4.7"
	},
	{
		"Player": "\"Dalton Schultz\"",
		"Pos": "TE",
		"Team": "HOU",
		"G": "4",
		"W1": "4.6",
		"W2": "4.1",
		"W3": "3.1",
		"W4": "6.4",
		"\"PPR Pts\"": "18.2",
		"\"PPR Pts/G\"": "4.6"
	},
	{
		"Player": "\"Will Dissly\"",
		"Pos": "TE",
		"Team": "LAC",
		"G": "4",
		"W1": "2.3",
		"W2": "5.9",
		"W3": "4.9",
		"W4": "4.4",
		"\"PPR Pts\"": "17.5",
		"\"PPR Pts/G\"": "4.4"
	},
	{
		"Player": "\"Johnny Mundt\"",
		"Pos": "TE",
		"Team": "MIN",
		"G": "4",
		"W1": "3.5",
		"W2": "3.2",
		"W3": "7.2",
		"W4": "3.5",
		"\"PPR Pts\"": "17.4",
		"\"PPR Pts/G\"": "4.4"
	},
	{
		"Player": "\"Elijah Higgins\"",
		"Pos": "TE",
		"Team": "ARI",
		"G": "4",
		"W1": "3.2",
		"W2": "8.8",
		"W3": "2.1",
		"W4": "3.2",
		"\"PPR Pts\"": "17.3",
		"\"PPR Pts/G\"": "4.3"
	},
	{
		"Player": "\"Noah Gray\"",
		"Pos": "TE",
		"Team": "KC",
		"G": "4",
		"W1": "6.7",
		"W2": "0.0",
		"W3": "2.3",
		"W4": "8.0",
		"\"PPR Pts\"": "17.0",
		"\"PPR Pts/G\"": "4.3"
	},
	{
		"Player": "\"Jonnu Smith\"",
		"Pos": "TE",
		"Team": "MIA",
		"G": "4",
		"W1": "1.7",
		"W2": "11.3",
		"W3": "3.8",
		"W4": "0.0",
		"\"PPR Pts\"": "16.8",
		"\"PPR Pts/G\"": "4.2"
	},
	{
		"Player": "\"Jordan Akins\"",
		"Pos": "TE",
		"Team": "CLE",
		"G": "4",
		"W1": "5.7",
		"W2": "2.0",
		"W3": "6.9",
		"W4": "2.0",
		"\"PPR Pts\"": "16.6",
		"\"PPR Pts/G\"": "4.2"
	},
	{
		"Player": "\"Foster Moreau\"",
		"Pos": "TE",
		"Team": "NO",
		"G": "4",
		"W1": "14.3",
		"W2": "0.0",
		"W3": "1.2",
		"W4": "0.0",
		"\"PPR Pts\"": "15.5",
		"\"PPR Pts/G\"": "3.9"
	},
	{
		"Player": "\"AJ Barner\"",
		"Pos": "TE",
		"Team": "SEA",
		"G": "4",
		"W1": "0.0",
		"W2": "0.0",
		"W3": "4.3",
		"W4": "10.7",
		"\"PPR Pts\"": "15.0",
		"\"PPR Pts/G\"": "3.8"
	},
	{
		"Player": "\"Darnell Washington\"",
		"Pos": "TE",
		"Team": "PIT",
		"G": "4",
		"W1": "1.5",
		"W2": "7.5",
		"W3": "0.0",
		"W4": "5.1",
		"\"PPR Pts\"": "14.1",
		"\"PPR Pts/G\"": "3.5"
	},
	{
		"Player": "\"Juwan Johnson\"",
		"Pos": "TE",
		"Team": "NO",
		"G": "4",
		"W1": "10.6",
		"W2": "0.0",
		"W3": "0.0",
		"W4": "3.3",
		"\"PPR Pts\"": "13.9",
		"\"PPR Pts/G\"": "3.5"
	},
	{
		"Player": "\"Josh Oliver\"",
		"Pos": "TE",
		"Team": "MIN",
		"G": "4",
		"W1": "4.7",
		"W2": "0.0",
		"W3": "0.0",
		"W4": "9.0",
		"\"PPR Pts\"": "13.7",
		"\"PPR Pts/G\"": "3.4"
	},
	{
		"Player": "\"Josh Whyle\"",
		"Pos": "TE",
		"Team": "TEN",
		"G": "4",
		"W1": "0.0",
		"W2": "3.3",
		"W3": "8.3",
		"W4": "1.5",
		"\"PPR Pts\"": "13.1",
		"\"PPR Pts/G\"": "3.3"
	},
	{
		"Player": "\"Mark Andrews\"",
		"Pos": "TE",
		"Team": "BAL",
		"G": "4",
		"W1": "3.4",
		"W2": "9.1",
		"W3": "0.0",
		"W4": "0.0",
		"\"PPR Pts\"": "12.5",
		"\"PPR Pts/G\"": "3.1"
	},
	{
		"Player": "\"Nick Vannett\"",
		"Pos": "TE",
		"Team": "TEN",
		"G": "4",
		"W1": "3.1",
		"W2": "0.0",
		"W3": "8.9",
		"W4": "0.0",
		"\"PPR Pts\"": "12.0",
		"\"PPR Pts/G\"": "3.0"
	},
	{
		"Player": "\"Hayden Hurst\"",
		"Pos": "TE",
		"Team": "LAC",
		"G": "4",
		"W1": "5.3",
		"W2": "1.5",
		"W3": "3.5",
		"W4": "1.6",
		"\"PPR Pts\"": "11.9",
		"\"PPR Pts/G\"": "3.0"
	},
	{
		"Player": "\"Brock Wright\"",
		"Pos": "TE",
		"Team": "DET",
		"G": "4",
		"W1": "1.2",
		"W2": "0.0",
		"W3": "7.4",
		"W4": "3.3",
		"\"PPR Pts\"": "11.9",
		"\"PPR Pts/G\"": "3.0"
	},
	{
		"Player": "\"Luke Schoonmaker\"",
		"Pos": "TE",
		"Team": "DAL",
		"G": "4",
		"W1": "0.0",
		"W2": "10.3",
		"W3": "1.5",
		"W4": "0.0",
		"\"PPR Pts\"": "11.8",
		"\"PPR Pts/G\"": "3.0"
	},
	{
		"Player": "\"Tommy Tremble\"",
		"Pos": "TE",
		"Team": "CAR",
		"G": "3",
		"W1": "-",
		"W2": "5.3",
		"W3": "5.9",
		"W4": "0.0",
		"\"PPR Pts\"": "11.2",
		"\"PPR Pts/G\"": "3.7"
	},
	{
		"Player": "\"Andrew Ogletree\"",
		"Pos": "TE",
		"Team": "IND",
		"G": "4",
		"W1": "0.0",
		"W2": "2.2",
		"W3": "0.0",
		"W4": "8.5",
		"\"PPR Pts\"": "10.7",
		"\"PPR Pts/G\"": "2.7"
	},
	{
		"Player": "\"Eric Saubert\"",
		"Pos": "TE",
		"Team": "SF",
		"G": "4",
		"W1": "0.0",
		"W2": "4.6",
		"W3": "6.1",
		"W4": "0.0",
		"\"PPR Pts\"": "10.7",
		"\"PPR Pts/G\"": "2.7"
	},
	{
		"Player": "\"Grant Calcaterra\"",
		"Pos": "TE",
		"Team": "PHI",
		"G": "4",
		"W1": "2.1",
		"W2": "3.9",
		"W3": "0.0",
		"W4": "3.6",
		"\"PPR Pts\"": "9.6",
		"\"PPR Pts/G\"": "2.4"
	},
	{
		"Player": "\"David Njoku\"",
		"Pos": "TE",
		"Team": "CLE",
		"G": "1",
		"W1": "8.4",
		"W2": "-",
		"W3": "-",
		"W4": "-",
		"\"PPR Pts\"": "8.4",
		"\"PPR Pts/G\"": "8.4"
	},
	{
		"Player": "\"Greg Dulcich\"",
		"Pos": "TE",
		"Team": "DEN",
		"G": "4",
		"W1": "3.2",
		"W2": "4.6",
		"W3": "0.0",
		"W4": "0.0",
		"\"PPR Pts\"": "7.8",
		"\"PPR Pts/G\"": "2.0"
	},
	{
		"Player": "\"Ja'Tavion Sanders\"",
		"Pos": "TE",
		"Team": "CAR",
		"G": "4",
		"W1": "1.4",
		"W2": "2.8",
		"W3": "0.0",
		"W4": "3.6",
		"\"PPR Pts\"": "7.8",
		"\"PPR Pts/G\"": "2.0"
	},
	{
		"Player": "\"Luke Musgrave\"",
		"Pos": "TE",
		"Team": "GB",
		"G": "4",
		"W1": "0.0",
		"W2": "1.6",
		"W3": "1.3",
		"W4": "4.3",
		"\"PPR Pts\"": "7.2",
		"\"PPR Pts/G\"": "1.8"
	},
	{
		"Player": "\"Kylen Granson\"",
		"Pos": "TE",
		"Team": "IND",
		"G": "4",
		"W1": "0.0",
		"W2": "1.9",
		"W3": "5.0",
		"W4": "0.0",
		"\"PPR Pts\"": "6.9",
		"\"PPR Pts/G\"": "1.7"
	},
	{
		"Player": "\"Drew Sample\"",
		"Pos": "TE",
		"Team": "CIN",
		"G": "4",
		"W1": "0.0",
		"W2": "5.8",
		"W3": "0.0",
		"W4": "1.0",
		"\"PPR Pts\"": "6.8",
		"\"PPR Pts/G\"": "1.7"
	},
	{
		"Player": "\"Theo Johnson\"",
		"Pos": "TE",
		"Team": "NYG",
		"G": "4",
		"W1": "2.8",
		"W2": "0.0",
		"W3": "2.3",
		"W4": "1.6",
		"\"PPR Pts\"": "6.7",
		"\"PPR Pts/G\"": "1.7"
	},
	{
		"Player": "\"Jeremy Ruckert\"",
		"Pos": "TE",
		"Team": "NYJ",
		"G": "4",
		"W1": "0.0",
		"W2": "0.0",
		"W3": "3.5",
		"W4": "3.0",
		"\"PPR Pts\"": "6.5",
		"\"PPR Pts/G\"": "1.6"
	},
	{
		"Player": "\"Cade Stover\"",
		"Pos": "TE",
		"Team": "HOU",
		"G": "4",
		"W1": "0.0",
		"W2": "2.8",
		"W3": "0.0",
		"W4": "3.7",
		"\"PPR Pts\"": "6.5",
		"\"PPR Pts/G\"": "1.6"
	},
	{
		"Player": "\"Michael Mayer\"",
		"Pos": "TE",
		"Team": "LV",
		"G": "3",
		"W1": "2.3",
		"W2": "2.1",
		"W3": "1.7",
		"W4": "-",
		"\"PPR Pts\"": "6.1",
		"\"PPR Pts/G\"": "2.0"
	},
	{
		"Player": "\"Julian Hill\"",
		"Pos": "TE",
		"Team": "MIA",
		"G": "4",
		"W1": "1.6",
		"W2": "0.0",
		"W3": "4.4",
		"W4": "0.0",
		"\"PPR Pts\"": "6.0",
		"\"PPR Pts/G\"": "1.5"
	},
	{
		"Player": "\"Dawson Knox\"",
		"Pos": "TE",
		"Team": "BUF",
		"G": "4",
		"W1": "3.3",
		"W2": "0.0",
		"W3": "1.7",
		"W4": "1.0",
		"\"PPR Pts\"": "6.0",
		"\"PPR Pts/G\"": "1.5"
	},
	{
		"Player": "\"Charlie Kolar\"",
		"Pos": "TE",
		"Team": "BAL",
		"G": "4",
		"W1": "0.0",
		"W2": "1.4",
		"W3": "4.0",
		"W4": "0.0",
		"\"PPR Pts\"": "5.4",
		"\"PPR Pts/G\"": "1.4"
	},
	{
		"Player": "\"Tanner Conner\"",
		"Pos": "TE",
		"Team": "MIA",
		"G": "4",
		"W1": "0.0",
		"W2": "0.0",
		"W3": "1.1",
		"W4": "3.5",
		"\"PPR Pts\"": "4.6",
		"\"PPR Pts/G\"": "1.2"
	},
	{
		"Player": "\"Luke Farrell\"",
		"Pos": "TE",
		"Team": "JAX",
		"G": "4",
		"W1": "0.0",
		"W2": "3.3",
		"W3": "1.1",
		"W4": "0.0",
		"\"PPR Pts\"": "4.4",
		"\"PPR Pts/G\"": "1.1"
	},
	{
		"Player": "\"Harrison Bryant\"",
		"Pos": "TE",
		"Team": "LV",
		"G": "4",
		"W1": "0.0",
		"W2": "0.0",
		"W3": "0.0",
		"W4": "4.1",
		"\"PPR Pts\"": "4.1",
		"\"PPR Pts/G\"": "1.0"
	},
	{
		"Player": "\"Daniel Bellinger\"",
		"Pos": "TE",
		"Team": "NYG",
		"G": "4",
		"W1": "1.3",
		"W2": "0.0",
		"W3": "2.7",
		"W4": "0.0",
		"\"PPR Pts\"": "4.0",
		"\"PPR Pts/G\"": "1.0"
	},
	{
		"Player": "\"John Bates\"",
		"Pos": "TE",
		"Team": "WAS",
		"G": "4",
		"W1": "0.0",
		"W2": "1.5",
		"W3": "0.0",
		"W4": "1.9",
		"\"PPR Pts\"": "3.4",
		"\"PPR Pts/G\"": "0.9"
	},
	{
		"Player": "\"Mo Alie-Cox\"",
		"Pos": "TE",
		"Team": "IND",
		"G": "4",
		"W1": "0.0",
		"W2": "3.2",
		"W3": "0.0",
		"W4": "0.0",
		"\"PPR Pts\"": "3.2",
		"\"PPR Pts/G\"": "0.8"
	},
	{
		"Player": "\"Pharaoh Brown\"",
		"Pos": "TE",
		"Team": "SEA",
		"G": "2",
		"W1": "-",
		"W2": "-",
		"W3": "1.9",
		"W4": "1.3",
		"\"PPR Pts\"": "3.2",
		"\"PPR Pts/G\"": "1.6"
	},
	{
		"Player": "\"Durham Smythe\"",
		"Pos": "TE",
		"Team": "MIA",
		"G": "4",
		"W1": "0.0",
		"W2": "1.8",
		"W3": "1.3",
		"W4": "0.0",
		"\"PPR Pts\"": "3.1",
		"\"PPR Pts/G\"": "0.8"
	},
	{
		"Player": "\"Gerald Everett\"",
		"Pos": "TE",
		"Team": "CHI",
		"G": "4",
		"W1": "0.9",
		"W2": "2.1",
		"W3": "0.0",
		"W4": "0.0",
		"\"PPR Pts\"": "3.0",
		"\"PPR Pts/G\"": "0.8"
	},
	{
		"Player": "\"Brevin Jordan\"",
		"Pos": "TE",
		"Team": "HOU",
		"G": "2",
		"W1": "1.3",
		"W2": "1.4",
		"W3": "-",
		"W4": "-",
		"\"PPR Pts\"": "2.7",
		"\"PPR Pts/G\"": "1.4"
	},
	{
		"Player": "\"Nate Adkins\"",
		"Pos": "TE",
		"Team": "DEN",
		"G": "4",
		"W1": "0.0",
		"W2": "0.0",
		"W3": "1.6",
		"W4": "1.0",
		"\"PPR Pts\"": "2.6",
		"\"PPR Pts/G\"": "0.7"
	},
	{
		"Player": "\"Adam Trautman\"",
		"Pos": "TE",
		"Team": "DEN",
		"G": "4",
		"W1": "0.0",
		"W2": "0.0",
		"W3": "2.3",
		"W4": "0.0",
		"\"PPR Pts\"": "2.3",
		"\"PPR Pts/G\"": "0.6"
	},
	{
		"Player": "\"MyCole Pruitt\"",
		"Pos": "TE",
		"Team": "PIT",
		"G": "2",
		"W1": "1.9",
		"W2": "0.0",
		"W3": "-",
		"W4": "-",
		"\"PPR Pts\"": "1.9",
		"\"PPR Pts/G\"": "1.0"
	},
	{
		"Player": "\"Payne Durham\"",
		"Pos": "TE",
		"Team": "TB",
		"G": "4",
		"W1": "0.0",
		"W2": "0.0",
		"W3": "1.8",
		"W4": "0.0",
		"\"PPR Pts\"": "1.8",
		"\"PPR Pts/G\"": "0.5"
	},
	{
		"Player": "\"Tanner Hudson\"",
		"Pos": "TE",
		"Team": "CIN",
		"G": "1",
		"W1": "1.8",
		"W2": "-",
		"W3": "-",
		"W4": "-",
		"\"PPR Pts\"": "1.8",
		"\"PPR Pts/G\"": "1.8"
	},
	{
		"Player": "\"Jared Wiley\"",
		"Pos": "TE",
		"Team": "KC",
		"G": "4",
		"W1": "0.0",
		"W2": "1.7",
		"W3": "0.0",
		"W4": "0.0",
		"\"PPR Pts\"": "1.7",
		"\"PPR Pts/G\"": "0.4"
	},
	{
		"Player": "\"Evan Engram\"",
		"Pos": "TE",
		"Team": "JAX",
		"G": "1",
		"W1": "1.5",
		"W2": "-",
		"W3": "-",
		"W4": "-",
		"\"PPR Pts\"": "1.5",
		"\"PPR Pts/G\"": "1.5"
	},
	{
		"Player": "\"Jack Stoll\"",
		"Pos": "TE",
		"Team": "PHI",
		"G": "2",
		"W1": "-",
		"W2": "-",
		"W3": "0.0",
		"W4": "1.4",
		"\"PPR Pts\"": "1.4",
		"\"PPR Pts/G\"": "0.7"
	},
	{
		"Player": "\"Charlie Woerner\"",
		"Pos": "TE",
		"Team": "ATL",
		"G": "4",
		"W1": "1.4",
		"W2": "0.0",
		"W3": "0.0",
		"W4": "0.0",
		"\"PPR Pts\"": "1.4",
		"\"PPR Pts/G\"": "0.4"
	},
	{
		"Player": "\"Connor Heyward\"",
		"Pos": "TE",
		"Team": "PIT",
		"G": "4",
		"W1": "0.0",
		"W2": "0.0",
		"W3": "1.2",
		"W4": "0.0",
		"\"PPR Pts\"": "1.2",
		"\"PPR Pts/G\"": "0.3"
	},
	
]

module.exports = te4for4FantasyPointsBrowserLastFiveWeeks;