const teamDefStatsByRankLastFiveWeeks4for4NFLTeamStatExplorer = [
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"NO\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "392",
		"\"Pass Plays\"": "225",
		"\"Pass Yards/Game\"": "306.4",
		"\"Rush Plays\"": "123",
		"\"Rush Yards/Game\"": "131.4",
		"\"Total Yards\"": "2182",
		"\"EPA/Play\"": "0.01",
		"\"Pass EPA/Play\"": "-0.01",
		"\"Rush EPA/Play\"": "0.14",
		"\"Explosive Pass %\"": "11.56",
		"\"Explosive Rush %\"": "12.2",
		"\"PROE\"": "2.07",
		"\"Points/Game\"": "23.4",
		"\"Points/Drive\"": "4.18",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "3",
		"\"Play Success %\"": "62.76"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"JAX\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "379",
		"\"Pass Plays\"": "222",
		"\"Pass Yards/Game\"": "293.6",
		"\"Rush Plays\"": "120",
		"\"Rush Yards/Game\"": "95.4",
		"\"Total Yards\"": "1940",
		"\"EPA/Play\"": "0.18",
		"\"Pass EPA/Play\"": "0.35",
		"\"Rush EPA/Play\"": "-0.06",
		"\"Explosive Pass %\"": "16.29",
		"\"Explosive Rush %\"": "8.33",
		"\"PROE\"": "3.03",
		"\"Points/Game\"": "27.6",
		"\"Points/Drive\"": "4.93",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "66.75"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"IND\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "383",
		"\"Pass Plays\"": "188",
		"\"Pass Yards/Game\"": "252",
		"\"Rush Plays\"": "155",
		"\"Rush Yards/Game\"": "132",
		"\"Total Yards\"": "1920",
		"\"EPA/Play\"": "-0.02",
		"\"Pass EPA/Play\"": "0.09",
		"\"Rush EPA/Play\"": "-0.13",
		"\"Explosive Pass %\"": "10.64",
		"\"Explosive Rush %\"": "9.74",
		"\"PROE\"": "-9.91",
		"\"Points/Game\"": "19.8",
		"\"Points/Drive\"": "4.3",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "2.2",
		"\"Play Success %\"": "62.4"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"DAL\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "349",
		"\"Pass Plays\"": "147",
		"\"Pass Yards/Game\"": "231",
		"\"Rush Plays\"": "161",
		"\"Rush Yards/Game\"": "152.4",
		"\"Total Yards\"": "1909",
		"\"EPA/Play\"": "0.18",
		"\"Pass EPA/Play\"": "0.28",
		"\"Rush EPA/Play\"": "0.15",
		"\"Explosive Pass %\"": "17.69",
		"\"Explosive Rush %\"": "12.42",
		"\"PROE\"": "-7.68",
		"\"Points/Game\"": "27",
		"\"Points/Drive\"": "4.66",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "2.4",
		"\"Play Success %\"": "62.18"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"CAR\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "369",
		"\"Pass Plays\"": "177",
		"\"Pass Yards/Game\"": "245",
		"\"Rush Plays\"": "154",
		"\"Rush Yards/Game\"": "137.6",
		"\"Total Yards\"": "1900",
		"\"EPA/Play\"": "0.11",
		"\"Pass EPA/Play\"": "0.24",
		"\"Rush EPA/Play\"": "0.01",
		"\"Explosive Pass %\"": "11.86",
		"\"Explosive Rush %\"": "7.79",
		"\"PROE\"": "-4.13",
		"\"Points/Game\"": "27.6",
		"\"Points/Drive\"": "4.93",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "61.79"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"ARI\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "358",
		"\"Pass Plays\"": "174",
		"\"Pass Yards/Game\"": "237.2",
		"\"Rush Plays\"": "149",
		"\"Rush Yards/Game\"": "141.2",
		"\"Total Yards\"": "1888",
		"\"EPA/Play\"": "0.07",
		"\"Pass EPA/Play\"": "0.19",
		"\"Rush EPA/Play\"": "0",
		"\"Explosive Pass %\"": "12.14",
		"\"Explosive Rush %\"": "12.75",
		"\"PROE\"": "-3.44",
		"\"Points/Game\"": "21.6",
		"\"Points/Drive\"": "4.7",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "67.6"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"NE\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "380",
		"\"Pass Plays\"": "195",
		"\"Pass Yards/Game\"": "245",
		"\"Rush Plays\"": "143",
		"\"Rush Yards/Game\"": "131.2",
		"\"Total Yards\"": "1878",
		"\"EPA/Play\"": "0.05",
		"\"Pass EPA/Play\"": "0.22",
		"\"Rush EPA/Play\"": "-0.06",
		"\"Explosive Pass %\"": "12.37",
		"\"Explosive Rush %\"": "10.49",
		"\"PROE\"": "-0.88",
		"\"Points/Game\"": "22.2",
		"\"Points/Drive\"": "4.11",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "2.8",
		"\"Play Success %\"": "58.68"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"BUF\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "370",
		"\"Pass Plays\"": "201",
		"\"Pass Yards/Game\"": "233.4",
		"\"Rush Plays\"": "134",
		"\"Rush Yards/Game\"": "133.6",
		"\"Total Yards\"": "1835",
		"\"EPA/Play\"": "-0.07",
		"\"Pass EPA/Play\"": "-0.06",
		"\"Rush EPA/Play\"": "-0.02",
		"\"Explosive Pass %\"": "13.07",
		"\"Explosive Rush %\"": "14.18",
		"\"PROE\"": "-6.68",
		"\"Points/Game\"": "18.6",
		"\"Points/Drive\"": "4.43",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "56.76"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"TB\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "400",
		"\"Pass Plays\"": "252",
		"\"Pass Yards/Game\"": "270.6",
		"\"Rush Plays\"": "106",
		"\"Rush Yards/Game\"": "95",
		"\"Total Yards\"": "1825",
		"\"EPA/Play\"": "-0.06",
		"\"Pass EPA/Play\"": "-0.07",
		"\"Rush EPA/Play\"": "-0.02",
		"\"Explosive Pass %\"": "11.11",
		"\"Explosive Rush %\"": "6.6",
		"\"PROE\"": "2.41",
		"\"Points/Game\"": "20.4",
		"\"Points/Drive\"": "4.08",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "2.8",
		"\"Play Success %\"": "58.5"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"SEA\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "351",
		"\"Pass Plays\"": "169",
		"\"Pass Yards/Game\"": "213.8",
		"\"Rush Plays\"": "138",
		"\"Rush Yards/Game\"": "146.8",
		"\"Total Yards\"": "1798",
		"\"EPA/Play\"": "0.04",
		"\"Pass EPA/Play\"": "0.15",
		"\"Rush EPA/Play\"": "-0.03",
		"\"Explosive Pass %\"": "13.02",
		"\"Explosive Rush %\"": "11.59",
		"\"PROE\"": "-1.72",
		"\"Points/Game\"": "23.4",
		"\"Points/Drive\"": "4.5",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "2.2",
		"\"Play Success %\"": "52.99"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"CIN\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "365",
		"\"Pass Plays\"": "203",
		"\"Pass Yards/Game\"": "244.4",
		"\"Rush Plays\"": "132",
		"\"Rush Yards/Game\"": "109.4",
		"\"Total Yards\"": "1764",
		"\"EPA/Play\"": "0.11",
		"\"Pass EPA/Play\"": "0.14",
		"\"Rush EPA/Play\"": "0.13",
		"\"Explosive Pass %\"": "8.87",
		"\"Explosive Rush %\"": "6.82",
		"\"PROE\"": "0.4",
		"\"Points/Game\"": "22.2",
		"\"Points/Drive\"": "4.83",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "1.4",
		"\"Play Success %\"": "70.96"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"ATL\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "369",
		"\"Pass Plays\"": "196",
		"\"Pass Yards/Game\"": "234.4",
		"\"Rush Plays\"": "137",
		"\"Rush Yards/Game\"": "117.4",
		"\"Total Yards\"": "1744",
		"\"EPA/Play\"": "0.05",
		"\"Pass EPA/Play\"": "0.08",
		"\"Rush EPA/Play\"": "0.02",
		"\"Explosive Pass %\"": "10.2",
		"\"Explosive Rush %\"": "9.56",
		"\"PROE\"": "-1.08",
		"\"Points/Game\"": "22.2",
		"\"Points/Drive\"": "4.62",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "2.2",
		"\"Play Success %\"": "64.23"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"CLE\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "362",
		"\"Pass Plays\"": "173",
		"\"Pass Yards/Game\"": "227.2",
		"\"Rush Plays\"": "135",
		"\"Rush Yards/Game\"": "122.2",
		"\"Total Yards\"": "1737",
		"\"EPA/Play\"": "-0.04",
		"\"Pass EPA/Play\"": "0.09",
		"\"Rush EPA/Play\"": "-0.06",
		"\"Explosive Pass %\"": "14.45",
		"\"Explosive Rush %\"": "10.37",
		"\"PROE\"": "-4.12",
		"\"Points/Game\"": "21.6",
		"\"Points/Drive\"": "4.5",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "2.2",
		"\"Play Success %\"": "55.25"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"WAS\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "334",
		"\"Pass Plays\"": "175",
		"\"Pass Yards/Game\"": "210",
		"\"Rush Plays\"": "127",
		"\"Rush Yards/Game\"": "136.8",
		"\"Total Yards\"": "1732",
		"\"EPA/Play\"": "0.06",
		"\"Pass EPA/Play\"": "0.13",
		"\"Rush EPA/Play\"": "0.03",
		"\"Explosive Pass %\"": "14.29",
		"\"Explosive Rush %\"": "16.54",
		"\"PROE\"": "-8.04",
		"\"Points/Game\"": "19.8",
		"\"Points/Drive\"": "4.71",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "1.6",
		"\"Play Success %\"": "64.37"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"BAL\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "363",
		"\"Pass Plays\"": "234",
		"\"Pass Yards/Game\"": "283.4",
		"\"Rush Plays\"": "86",
		"\"Rush Yards/Game\"": "47.2",
		"\"Total Yards\"": "1652",
		"\"EPA/Play\"": "0.06",
		"\"Pass EPA/Play\"": "0.16",
		"\"Rush EPA/Play\"": "-0.21",
		"\"Explosive Pass %\"": "15.02",
		"\"Explosive Rush %\"": "2.33",
		"\"PROE\"": "6.44",
		"\"Points/Game\"": "21.6",
		"\"Points/Drive\"": "4.32",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "2.4",
		"\"Play Success %\"": "57.85"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"SF\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "348",
		"\"Pass Plays\"": "194",
		"\"Pass Yards/Game\"": "228.2",
		"\"Rush Plays\"": "112",
		"\"Rush Yards/Game\"": "98.4",
		"\"Total Yards\"": "1628",
		"\"EPA/Play\"": "-0.06",
		"\"Pass EPA/Play\"": "-0.04",
		"\"Rush EPA/Play\"": "-0.04",
		"\"Explosive Pass %\"": "10.82",
		"\"Explosive Rush %\"": "7.14",
		"\"PROE\"": "-4.44",
		"\"Points/Game\"": "21",
		"\"Points/Drive\"": "4.57",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "2.4",
		"\"Play Success %\"": "56.9"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"GB\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "348",
		"\"Pass Plays\"": "207",
		"\"Pass Yards/Game\"": "236.6",
		"\"Rush Plays\"": "102",
		"\"Rush Yards/Game\"": "88.4",
		"\"Total Yards\"": "1622",
		"\"EPA/Play\"": "-0.13",
		"\"Pass EPA/Play\"": "-0.09",
		"\"Rush EPA/Play\"": "-0.14",
		"\"Explosive Pass %\"": "11.59",
		"\"Explosive Rush %\"": "10.78",
		"\"PROE\"": "1.83",
		"\"Points/Game\"": "15.6",
		"\"Points/Drive\"": "4.88",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "1",
		"\"Play Success %\"": "56.61"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"LV\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "376",
		"\"Pass Plays\"": "191",
		"\"Pass Yards/Game\"": "214.6",
		"\"Rush Plays\"": "123",
		"\"Rush Yards/Game\"": "110.6",
		"\"Total Yards\"": "1618",
		"\"EPA/Play\"": "0.02",
		"\"Pass EPA/Play\"": "0.06",
		"\"Rush EPA/Play\"": "0",
		"\"Explosive Pass %\"": "12.57",
		"\"Explosive Rush %\"": "11.38",
		"\"PROE\"": "0.39",
		"\"Points/Game\"": "23.4",
		"\"Points/Drive\"": "4.33",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "2.8",
		"\"Play Success %\"": "54.79"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"NYG\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "351",
		"\"Pass Plays\"": "208",
		"\"Pass Yards/Game\"": "234.8",
		"\"Rush Plays\"": "91",
		"\"Rush Yards/Game\"": "80.8",
		"\"Total Yards\"": "1572",
		"\"EPA/Play\"": "-0.06",
		"\"Pass EPA/Play\"": "0.02",
		"\"Rush EPA/Play\"": "-0.16",
		"\"Explosive Pass %\"": "9.66",
		"\"Explosive Rush %\"": "8.79",
		"\"PROE\"": "4.94",
		"\"Points/Game\"": "16.8",
		"\"Points/Drive\"": "3.82",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "3",
		"\"Play Success %\"": "51"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"PIT\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "351",
		"\"Pass Plays\"": "194",
		"\"Pass Yards/Game\"": "225.8",
		"\"Rush Plays\"": "116",
		"\"Rush Yards/Game\"": "82.2",
		"\"Total Yards\"": "1539",
		"\"EPA/Play\"": "-0.09",
		"\"Pass EPA/Play\"": "0.04",
		"\"Rush EPA/Play\"": "-0.23",
		"\"Explosive Pass %\"": "12.5",
		"\"Explosive Rush %\"": "8.62",
		"\"PROE\"": "-4",
		"\"Points/Game\"": "13.8",
		"\"Points/Drive\"": "4.06",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "52.42"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"CHI\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "343",
		"\"Pass Plays\"": "182",
		"\"Pass Yards/Game\"": "202.6",
		"\"Rush Plays\"": "110",
		"\"Rush Yards/Game\"": "100.4",
		"\"Total Yards\"": "1508",
		"\"EPA/Play\"": "-0.09",
		"\"Pass EPA/Play\"": "-0.15",
		"\"Rush EPA/Play\"": "-0.04",
		"\"Explosive Pass %\"": "14.84",
		"\"Explosive Rush %\"": "12.73",
		"\"PROE\"": "-3.99",
		"\"Points/Game\"": "15.6",
		"\"Points/Drive\"": "3.9",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "2.4",
		"\"Play Success %\"": "49.56"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"LA\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "284",
		"\"Pass Plays\"": "132",
		"\"Pass Yards/Game\"": "243.5",
		"\"Rush Plays\"": "120",
		"\"Rush Yards/Game\"": "132.75",
		"\"Total Yards\"": "1501",
		"\"EPA/Play\"": "0.13",
		"\"Pass EPA/Play\"": "0.36",
		"\"Rush EPA/Play\"": "-0.02",
		"\"Explosive Pass %\"": "14.39",
		"\"Explosive Rush %\"": "8.33",
		"\"PROE\"": "-4.02",
		"\"Points/Game\"": "26.25",
		"\"Points/Drive\"": "5",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "1.5",
		"\"Play Success %\"": "66.2"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"MIN\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "317",
		"\"Pass Plays\"": "214",
		"\"Pass Yards/Game\"": "294.75",
		"\"Rush Plays\"": "69",
		"\"Rush Yards/Game\"": "58",
		"\"Total Yards\"": "1411",
		"\"EPA/Play\"": "-0.2",
		"\"Pass EPA/Play\"": "-0.16",
		"\"Rush EPA/Play\"": "-0.25",
		"\"Explosive Pass %\"": "12.62",
		"\"Explosive Rush %\"": "4.35",
		"\"PROE\"": "1.94",
		"\"Points/Game\"": "16.5",
		"\"Points/Drive\"": "4.4",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "1.25",
		"\"Play Success %\"": "52.37"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"DEN\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "393",
		"\"Pass Plays\"": "215",
		"\"Pass Yards/Game\"": "187",
		"\"Rush Plays\"": "126",
		"\"Rush Yards/Game\"": "94",
		"\"Total Yards\"": "1402",
		"\"EPA/Play\"": "-0.13",
		"\"Pass EPA/Play\"": "-0.15",
		"\"Rush EPA/Play\"": "-0.14",
		"\"Explosive Pass %\"": "7.01",
		"\"Explosive Rush %\"": "7.14",
		"\"PROE\"": "-0.9",
		"\"Points/Game\"": "13.8",
		"\"Points/Drive\"": "4.06",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "48.6"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"HOU\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "370",
		"\"Pass Plays\"": "202",
		"\"Pass Yards/Game\"": "184.4",
		"\"Rush Plays\"": "114",
		"\"Rush Yards/Game\"": "87.6",
		"\"Total Yards\"": "1359",
		"\"EPA/Play\"": "-0.05",
		"\"Pass EPA/Play\"": "-0.08",
		"\"Rush EPA/Play\"": "-0.11",
		"\"Explosive Pass %\"": "11.39",
		"\"Explosive Rush %\"": "8.77",
		"\"PROE\"": "-2.28",
		"\"Points/Game\"": "19.2",
		"\"Points/Drive\"": "4.8",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "1.6",
		"\"Play Success %\"": "49.46"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"PHI\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "282",
		"\"Pass Plays\"": "145",
		"\"Pass Yards/Game\"": "217",
		"\"Rush Plays\"": "100",
		"\"Rush Yards/Game\"": "107.25",
		"\"Total Yards\"": "1293",
		"\"EPA/Play\"": "0.05",
		"\"Pass EPA/Play\"": "0.19",
		"\"Rush EPA/Play\"": "-0.13",
		"\"Explosive Pass %\"": "11.03",
		"\"Explosive Rush %\"": "13",
		"\"PROE\"": "-1.72",
		"\"Points/Game\"": "18",
		"\"Points/Drive\"": "4",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "2.75",
		"\"Play Success %\"": "57.8"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"DET\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "291",
		"\"Pass Plays\"": "194",
		"\"Pass Yards/Game\"": "250",
		"\"Rush Plays\"": "69",
		"\"Rush Yards/Game\"": "65.25",
		"\"Total Yards\"": "1260",
		"\"EPA/Play\"": "-0.12",
		"\"Pass EPA/Play\"": "-0.1",
		"\"Rush EPA/Play\"": "-0.15",
		"\"Explosive Pass %\"": "11.4",
		"\"Explosive Rush %\"": "11.59",
		"\"PROE\"": "4.57",
		"\"Points/Game\"": "15.75",
		"\"Points/Drive\"": "4.2",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "53.61"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"NYJ\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "365",
		"\"Pass Plays\"": "186",
		"\"Pass Yards/Game\"": "149.8",
		"\"Rush Plays\"": "127",
		"\"Rush Yards/Game\"": "99.4",
		"\"Total Yards\"": "1237",
		"\"EPA/Play\"": "-0.1",
		"\"Pass EPA/Play\"": "-0.1",
		"\"Rush EPA/Play\"": "-0.07",
		"\"Explosive Pass %\"": "9.24",
		"\"Explosive Rush %\"": "7.14",
		"\"PROE\"": "-5.28",
		"\"Points/Game\"": "12.6",
		"\"Points/Drive\"": "3.94",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "49.86"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"MIA\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "275",
		"\"Pass Plays\"": "122",
		"\"Pass Yards/Game\"": "168.75",
		"\"Rush Plays\"": "105",
		"\"Rush Yards/Game\"": "122.5",
		"\"Total Yards\"": "1160",
		"\"EPA/Play\"": "-0.06",
		"\"Pass EPA/Play\"": "-0.04",
		"\"Rush EPA/Play\"": "-0.01",
		"\"Explosive Pass %\"": "13.11",
		"\"Explosive Rush %\"": "9.52",
		"\"PROE\"": "-4.08",
		"\"Points/Game\"": "19.5",
		"\"Points/Drive\"": "3.9",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "2.75",
		"\"Play Success %\"": "46.91"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"LAC\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "265",
		"\"Pass Plays\"": "148",
		"\"Pass Yards/Game\"": "205.25",
		"\"Rush Plays\"": "80",
		"\"Rush Yards/Game\"": "83.5",
		"\"Total Yards\"": "1150",
		"\"EPA/Play\"": "-0.14",
		"\"Pass EPA/Play\"": "-0.1",
		"\"Rush EPA/Play\"": "-0.15",
		"\"Explosive Pass %\"": "10.81",
		"\"Explosive Rush %\"": "10",
		"\"PROE\"": "-4.73",
		"\"Points/Game\"": "12.75",
		"\"Points/Drive\"": "3.92",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "1.75",
		"\"Play Success %\"": "49.81"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"TEN\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "283",
		"\"Pass Plays\"": "133",
		"\"Pass Yards/Game\"": "169.25",
		"\"Rush Plays\"": "115",
		"\"Rush Yards/Game\"": "105",
		"\"Total Yards\"": "1096",
		"\"EPA/Play\"": "-0.04",
		"\"Pass EPA/Play\"": "0.07",
		"\"Rush EPA/Play\"": "-0.21",
		"\"Explosive Pass %\"": "13.53",
		"\"Explosive Rush %\"": "7.83",
		"\"PROE\"": "-7.39",
		"\"Points/Game\"": "18",
		"\"Points/Drive\"": "4.5",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "51.94"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"KC\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "266",
		"\"Pass Plays\"": "149",
		"\"Pass Yards/Game\"": "209",
		"\"Rush Plays\"": "84",
		"\"Rush Yards/Game\"": "60",
		"\"Total Yards\"": "1075",
		"\"EPA/Play\"": "-0.07",
		"\"Pass EPA/Play\"": "0.02",
		"\"Rush EPA/Play\"": "-0.26",
		"\"Explosive Pass %\"": "8.05",
		"\"Explosive Rush %\"": "4.76",
		"\"PROE\"": "-0.41",
		"\"Points/Game\"": "16.5",
		"\"Points/Drive\"": "4.4",
		"\"TDs/Game\"": "0",
		"\"FGs/Game\"": "1.75",
		"\"Play Success %\"": "51.5"
	},
	
]

module.exports = teamDefStatsByRankLastFiveWeeks4for4NFLTeamStatExplorer;