const teamOffStatsByRankLastFiveWeeks4for4NFLTeamStatExplorer = [
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"DET\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "404",
		"\"Pass Plays\"": "212",
		"\"Pass Yards/Game\"": "333.2",
		"\"Rush Plays\"": "158",
		"\"Rush Yards/Game\"": "137.2",
		"\"Total Yards\"": "2352",
		"\"EPA/Play\"": "0.18",
		"\"Pass EPA/Play\"": "0.38",
		"\"Rush EPA/Play\"": "-0.04",
		"\"Explosive Pass %\"": "16.51",
		"\"Explosive Rush %\"": "10.76",
		"\"PROE\"": "0.43",
		"\"Points/Game\"": "30.6",
		"\"Points/Drive\"": "4.94",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "75.74"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"CLE\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "390",
		"\"Pass Plays\"": "222",
		"\"Pass Yards/Game\"": "278.8",
		"\"Rush Plays\"": "116",
		"\"Rush Yards/Game\"": "94.2",
		"\"Total Yards\"": "1865",
		"\"EPA/Play\"": "-0.17",
		"\"Pass EPA/Play\"": "-0.17",
		"\"Rush EPA/Play\"": "-0.07",
		"\"Explosive Pass %\"": "13.06",
		"\"Explosive Rush %\"": "4.31",
		"\"PROE\"": "-0.03",
		"\"Points/Game\"": "18",
		"\"Points/Drive\"": "4.29",
		"\"FGs/Game\"": "1.4",
		"\"Play Success %\"": "56.15"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"PHI\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "372",
		"\"Pass Plays\"": "134",
		"\"Pass Yards/Game\"": "167.6",
		"\"Rush Plays\"": "191",
		"\"Rush Yards/Game\"": "204.4",
		"\"Total Yards\"": "1860",
		"\"EPA/Play\"": "0.11",
		"\"Pass EPA/Play\"": "0.2",
		"\"Rush EPA/Play\"": "0.14",
		"\"Explosive Pass %\"": "16.42",
		"\"Explosive Rush %\"": "12.04",
		"\"PROE\"": "-8.85",
		"\"Points/Game\"": "24",
		"\"Points/Drive\"": "4.44",
		"\"FGs/Game\"": "2.2",
		"\"Play Success %\"": "64.52"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"LA\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "343",
		"\"Pass Plays\"": "151",
		"\"Pass Yards/Game\"": "227.8",
		"\"Rush Plays\"": "151",
		"\"Rush Yards/Game\"": "126.8",
		"\"Total Yards\"": "1773",
		"\"EPA/Play\"": "0.1",
		"\"Pass EPA/Play\"": "0.27",
		"\"Rush EPA/Play\"": "-0.01",
		"\"Explosive Pass %\"": "17.88",
		"\"Explosive Rush %\"": "8.61",
		"\"PROE\"": "-5.09",
		"\"Points/Game\"": "21",
		"\"Points/Drive\"": "4.77",
		"\"FGs/Game\"": "1.4",
		"\"Play Success %\"": "64.72"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"DAL\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "401",
		"\"Pass Plays\"": "194",
		"\"Pass Yards/Game\"": "225",
		"\"Rush Plays\"": "143",
		"\"Rush Yards/Game\"": "128.8",
		"\"Total Yards\"": "1769",
		"\"EPA/Play\"": "-0.07",
		"\"Pass EPA/Play\"": "-0.03",
		"\"Rush EPA/Play\"": "-0.14",
		"\"Explosive Pass %\"": "11.86",
		"\"Explosive Rush %\"": "11.19",
		"\"PROE\"": "-0.01",
		"\"Points/Game\"": "19.2",
		"\"Points/Drive\"": "3.84",
		"\"FGs/Game\"": "2.8",
		"\"Play Success %\"": "54.36"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"GB\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "320",
		"\"Pass Plays\"": "119",
		"\"Pass Yards/Game\"": "223.6",
		"\"Rush Plays\"": "150",
		"\"Rush Yards/Game\"": "125.6",
		"\"Total Yards\"": "1746",
		"\"EPA/Play\"": "0.17",
		"\"Pass EPA/Play\"": "0.38",
		"\"Rush EPA/Play\"": "-0.02",
		"\"Explosive Pass %\"": "20.17",
		"\"Explosive Rush %\"": "9.33",
		"\"PROE\"": "-6.31",
		"\"Points/Game\"": "26.4",
		"\"Points/Drive\"": "5.08",
		"\"FGs/Game\"": "1.6",
		"\"Play Success %\"": "62.5"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"BUF\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "282",
		"\"Pass Plays\"": "129",
		"\"Pass Yards/Game\"": "279.5",
		"\"Rush Plays\"": "120",
		"\"Rush Yards/Game\"": "156",
		"\"Total Yards\"": "1742",
		"\"EPA/Play\"": "0.25",
		"\"Pass EPA/Play\"": "0.39",
		"\"Rush EPA/Play\"": "0.23",
		"\"Explosive Pass %\"": "20.16",
		"\"Explosive Rush %\"": "10",
		"\"PROE\"": "-1.2",
		"\"Points/Game\"": "35.25",
		"\"Points/Drive\"": "5.22",
		"\"FGs/Game\"": "1.25",
		"\"Play Success %\"": "72.34"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"TB\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "294",
		"\"Pass Plays\"": "125",
		"\"Pass Yards/Game\"": "253",
		"\"Rush Plays\"": "131",
		"\"Rush Yards/Game\"": "180.5",
		"\"Total Yards\"": "1734",
		"\"EPA/Play\"": "0.12",
		"\"Pass EPA/Play\"": "0.24",
		"\"Rush EPA/Play\"": "0.02",
		"\"Explosive Pass %\"": "19.2",
		"\"Explosive Rush %\"": "10.69",
		"\"PROE\"": "-2.69",
		"\"Points/Game\"": "27",
		"\"Points/Drive\"": "4.91",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "66.67"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"MIN\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "360",
		"\"Pass Plays\"": "175",
		"\"Pass Yards/Game\"": "243.8",
		"\"Rush Plays\"": "126",
		"\"Rush Yards/Game\"": "100.6",
		"\"Total Yards\"": "1722",
		"\"EPA/Play\"": "0.1",
		"\"Pass EPA/Play\"": "0.21",
		"\"Rush EPA/Play\"": "-0.12",
		"\"Explosive Pass %\"": "16.57",
		"\"Explosive Rush %\"": "11.9",
		"\"PROE\"": "7.16",
		"\"Points/Game\"": "25.8",
		"\"Points/Drive\"": "4.61",
		"\"FGs/Game\"": "2.2",
		"\"Play Success %\"": "62.78"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"LV\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "383",
		"\"Pass Plays\"": "224",
		"\"Pass Yards/Game\"": "253",
		"\"Rush Plays\"": "104",
		"\"Rush Yards/Game\"": "80.2",
		"\"Total Yards\"": "1666",
		"\"EPA/Play\"": "-0.12",
		"\"Pass EPA/Play\"": "-0.07",
		"\"Rush EPA/Play\"": "-0.15",
		"\"Explosive Pass %\"": "9.82",
		"\"Explosive Rush %\"": "10.58",
		"\"PROE\"": "1.47",
		"\"Points/Game\"": "14.4",
		"\"Points/Drive\"": "3.6",
		"\"FGs/Game\"": "2.6",
		"\"Play Success %\"": "57.7"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"CIN\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "319",
		"\"Pass Plays\"": "179",
		"\"Pass Yards/Game\"": "313",
		"\"Rush Plays\"": "85",
		"\"Rush Yards/Game\"": "94.5",
		"\"Total Yards\"": "1630",
		"\"EPA/Play\"": "0.06",
		"\"Pass EPA/Play\"": "0.13",
		"\"Rush EPA/Play\"": "0.06",
		"\"Explosive Pass %\"": "15.64",
		"\"Explosive Rush %\"": "11.76",
		"\"PROE\"": "9.27",
		"\"Points/Game\"": "27",
		"\"Points/Drive\"": "4.7",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "64.89"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"MIA\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "373",
		"\"Pass Plays\"": "214",
		"\"Pass Yards/Game\"": "270.2",
		"\"Rush Plays\"": "101",
		"\"Rush Yards/Game\"": "55.8",
		"\"Total Yards\"": "1630",
		"\"EPA/Play\"": "0.08",
		"\"Pass EPA/Play\"": "0.26",
		"\"Rush EPA/Play\"": "-0.33",
		"\"Explosive Pass %\"": "10.28",
		"\"Explosive Rush %\"": "3.96",
		"\"PROE\"": "7",
		"\"Points/Game\"": "23.4",
		"\"Points/Drive\"": "4.68",
		"\"FGs/Game\"": "2.2",
		"\"Play Success %\"": "64.08"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"PIT\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "370",
		"\"Pass Plays\"": "164",
		"\"Pass Yards/Game\"": "218.6",
		"\"Rush Plays\"": "146",
		"\"Rush Yards/Game\"": "105.6",
		"\"Total Yards\"": "1621",
		"\"EPA/Play\"": "-0.03",
		"\"Pass EPA/Play\"": "0.03",
		"\"Rush EPA/Play\"": "-0.21",
		"\"Explosive Pass %\"": "17.68",
		"\"Explosive Rush %\"": "7.53",
		"\"PROE\"": "-2.66",
		"\"Points/Game\"": "22.2",
		"\"Points/Drive\"": "3.96",
		"\"FGs/Game\"": "3.4",
		"\"Play Success %\"": "50.81"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"KC\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "390",
		"\"Pass Plays\"": "208",
		"\"Pass Yards/Game\"": "210.8",
		"\"Rush Plays\"": "119",
		"\"Rush Yards/Game\"": "106.8",
		"\"Total Yards\"": "1588",
		"\"EPA/Play\"": "0.04",
		"\"Pass EPA/Play\"": "0.07",
		"\"Rush EPA/Play\"": "0",
		"\"Explosive Pass %\"": "7.21",
		"\"Explosive Rush %\"": "9.24",
		"\"PROE\"": "9.92",
		"\"Points/Game\"": "19.8",
		"\"Points/Drive\"": "4.12",
		"\"FGs/Game\"": "2.6",
		"\"Play Success %\"": "56.41"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"TEN\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "353",
		"\"Pass Plays\"": "181",
		"\"Pass Yards/Game\"": "229",
		"\"Rush Plays\"": "117",
		"\"Rush Yards/Game\"": "81.8",
		"\"Total Yards\"": "1554",
		"\"EPA/Play\"": "-0.09",
		"\"Pass EPA/Play\"": "-0.06",
		"\"Rush EPA/Play\"": "-0.23",
		"\"Explosive Pass %\"": "14.36",
		"\"Explosive Rush %\"": "6.84",
		"\"PROE\"": "-3.65",
		"\"Points/Game\"": "19.8",
		"\"Points/Drive\"": "4.71",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "53.26"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"CHI\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "361",
		"\"Pass Plays\"": "192",
		"\"Pass Yards/Game\"": "204.4",
		"\"Rush Plays\"": "120",
		"\"Rush Yards/Game\"": "103",
		"\"Total Yards\"": "1537",
		"\"EPA/Play\"": "-0.02",
		"\"Pass EPA/Play\"": "0",
		"\"Rush EPA/Play\"": "0.03",
		"\"Explosive Pass %\"": "11.46",
		"\"Explosive Rush %\"": "7.5",
		"\"PROE\"": "-0.5",
		"\"Points/Game\"": "16.8",
		"\"Points/Drive\"": "4.42",
		"\"FGs/Game\"": "1.6",
		"\"Play Success %\"": "57.89"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"BAL\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "283",
		"\"Pass Plays\"": "125",
		"\"Pass Yards/Game\"": "215.75",
		"\"Rush Plays\"": "119",
		"\"Rush Yards/Game\"": "168",
		"\"Total Yards\"": "1535",
		"\"EPA/Play\"": "0.07",
		"\"Pass EPA/Play\"": "0.21",
		"\"Rush EPA/Play\"": "0.08",
		"\"Explosive Pass %\"": "16.8",
		"\"Explosive Rush %\"": "13.45",
		"\"PROE\"": "-7.19",
		"\"Points/Game\"": "22.5",
		"\"Points/Drive\"": "4.29",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "62.9"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"WAS\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "324",
		"\"Pass Plays\"": "148",
		"\"Pass Yards/Game\"": "205.75",
		"\"Rush Plays\"": "133",
		"\"Rush Yards/Game\"": "160.5",
		"\"Total Yards\"": "1465",
		"\"EPA/Play\"": "0.01",
		"\"Pass EPA/Play\"": "0",
		"\"Rush EPA/Play\"": "0.08",
		"\"Explosive Pass %\"": "9.46",
		"\"Explosive Rush %\"": "10.53",
		"\"PROE\"": "-0.35",
		"\"Points/Game\"": "23.25",
		"\"Points/Drive\"": "4.23",
		"\"FGs/Game\"": "2.25",
		"\"Play Success %\"": "63.27"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"ARI\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "313",
		"\"Pass Plays\"": "160",
		"\"Pass Yards/Game\"": "242",
		"\"Rush Plays\"": "100",
		"\"Rush Yards/Game\"": "121.75",
		"\"Total Yards\"": "1455",
		"\"EPA/Play\"": "-0.04",
		"\"Pass EPA/Play\"": "0.01",
		"\"Rush EPA/Play\"": "-0.05",
		"\"Explosive Pass %\"": "8.75",
		"\"Explosive Rush %\"": "12",
		"\"PROE\"": "2.23",
		"\"Points/Game\"": "18.75",
		"\"Points/Drive\"": "3.57",
		"\"FGs/Game\"": "3.5",
		"\"Play Success %\"": "56.55"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"SEA\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "350",
		"\"Pass Plays\"": "176",
		"\"Pass Yards/Game\"": "190.2",
		"\"Rush Plays\"": "118",
		"\"Rush Yards/Game\"": "99.8",
		"\"Total Yards\"": "1450",
		"\"EPA/Play\"": "0",
		"\"Pass EPA/Play\"": "-0.08",
		"\"Rush EPA/Play\"": "0",
		"\"Explosive Pass %\"": "12.5",
		"\"Explosive Rush %\"": "11.02",
		"\"PROE\"": "-0.05",
		"\"Points/Game\"": "16.8",
		"\"Points/Drive\"": "4.42",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "54.57"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"LAC\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "333",
		"\"Pass Plays\"": "177",
		"\"Pass Yards/Game\"": "196.2",
		"\"Rush Plays\"": "97",
		"\"Rush Yards/Game\"": "84",
		"\"Total Yards\"": "1401",
		"\"EPA/Play\"": "-0.05",
		"\"Pass EPA/Play\"": "-0.09",
		"\"Rush EPA/Play\"": "-0.08",
		"\"Explosive Pass %\"": "14.12",
		"\"Explosive Rush %\"": "10.31",
		"\"PROE\"": "3",
		"\"Points/Game\"": "18",
		"\"Points/Drive\"": "4.5",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "53.75"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"SF\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "313",
		"\"Pass Plays\"": "142",
		"\"Pass Yards/Game\"": "175.6",
		"\"Rush Plays\"": "123",
		"\"Rush Yards/Game\"": "104.4",
		"\"Total Yards\"": "1400",
		"\"EPA/Play\"": "-0.09",
		"\"Pass EPA/Play\"": "-0.08",
		"\"Rush EPA/Play\"": "-0.04",
		"\"Explosive Pass %\"": "14.79",
		"\"Explosive Rush %\"": "10.57",
		"\"PROE\"": "-5.97",
		"\"Points/Game\"": "14.4",
		"\"Points/Drive\"": "4.24",
		"\"FGs/Game\"": "1.6",
		"\"Play Success %\"": "53.67"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"NE\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "296",
		"\"Pass Plays\"": "143",
		"\"Pass Yards/Game\"": "214.25",
		"\"Rush Plays\"": "106",
		"\"Rush Yards/Game\"": "131.75",
		"\"Total Yards\"": "1384",
		"\"EPA/Play\"": "-0.04",
		"\"Pass EPA/Play\"": "0.05",
		"\"Rush EPA/Play\"": "0",
		"\"Explosive Pass %\"": "13.29",
		"\"Explosive Rush %\"": "12.26",
		"\"PROE\"": "-0.96",
		"\"Points/Game\"": "15.75",
		"\"Points/Drive\"": "3.5",
		"\"FGs/Game\"": "2.75",
		"\"Play Success %\"": "57.43"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"NO\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "281",
		"\"Pass Plays\"": "135",
		"\"Pass Yards/Game\"": "204.75",
		"\"Rush Plays\"": "108",
		"\"Rush Yards/Game\"": "129.5",
		"\"Total Yards\"": "1337",
		"\"EPA/Play\"": "-0.02",
		"\"Pass EPA/Play\"": "0.04",
		"\"Rush EPA/Play\"": "-0.01",
		"\"Explosive Pass %\"": "16.3",
		"\"Explosive Rush %\"": "12.04",
		"\"PROE\"": "-5.6",
		"\"Points/Game\"": "18",
		"\"Points/Drive\"": "4.24",
		"\"FGs/Game\"": "1.75",
		"\"Play Success %\"": "57.3"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"ATL\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "308",
		"\"Pass Plays\"": "133",
		"\"Pass Yards/Game\"": "210.25",
		"\"Rush Plays\"": "127",
		"\"Rush Yards/Game\"": "123",
		"\"Total Yards\"": "1333",
		"\"EPA/Play\"": "-0.15",
		"\"Pass EPA/Play\"": "-0.18",
		"\"Rush EPA/Play\"": "-0.12",
		"\"Explosive Pass %\"": "15.04",
		"\"Explosive Rush %\"": "7.09",
		"\"PROE\"": "-12.33",
		"\"Points/Game\"": "13.5",
		"\"Points/Drive\"": "3.6",
		"\"FGs/Game\"": "2.5",
		"\"Play Success %\"": "55.84"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"DEN\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "292",
		"\"Pass Plays\"": "146",
		"\"Pass Yards/Game\"": "243",
		"\"Rush Plays\"": "101",
		"\"Rush Yards/Game\"": "86.5",
		"\"Total Yards\"": "1318",
		"\"EPA/Play\"": "0.05",
		"\"Pass EPA/Play\"": "0.13",
		"\"Rush EPA/Play\"": "-0.1",
		"\"Explosive Pass %\"": "15.07",
		"\"Explosive Rush %\"": "8.91",
		"\"PROE\"": "5.25",
		"\"Points/Game\"": "26.25",
		"\"Points/Drive\"": "4.77",
		"\"FGs/Game\"": "2.25",
		"\"Play Success %\"": "55.48"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"NYJ\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "275",
		"\"Pass Plays\"": "146",
		"\"Pass Yards/Game\"": "231.25",
		"\"Rush Plays\"": "85",
		"\"Rush Yards/Game\"": "97",
		"\"Total Yards\"": "1313",
		"\"EPA/Play\"": "0.05",
		"\"Pass EPA/Play\"": "0.09",
		"\"Rush EPA/Play\"": "-0.01",
		"\"Explosive Pass %\"": "14.38",
		"\"Explosive Rush %\"": "10.59",
		"\"PROE\"": "3.01",
		"\"Points/Game\"": "23.25",
		"\"Points/Drive\"": "4.65",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "57.45"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"JAX\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "290",
		"\"Pass Plays\"": "152",
		"\"Pass Yards/Game\"": "227.5",
		"\"Rush Plays\"": "97",
		"\"Rush Yards/Game\"": "86.25",
		"\"Total Yards\"": "1255",
		"\"EPA/Play\"": "-0.02",
		"\"Pass EPA/Play\"": "0.05",
		"\"Rush EPA/Play\"": "-0.1",
		"\"Explosive Pass %\"": "11.84",
		"\"Explosive Rush %\"": "6.19",
		"\"PROE\"": "-2.54",
		"\"Points/Game\"": "14.25",
		"\"Points/Drive\"": "3.8",
		"\"FGs/Game\"": "2.5",
		"\"Play Success %\"": "56.21"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"CAR\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "290",
		"\"Pass Plays\"": "151",
		"\"Pass Yards/Game\"": "220.25",
		"\"Rush Plays\"": "90",
		"\"Rush Yards/Game\"": "83",
		"\"Total Yards\"": "1213",
		"\"EPA/Play\"": "-0.01",
		"\"Pass EPA/Play\"": "0.01",
		"\"Rush EPA/Play\"": "-0.04",
		"\"Explosive Pass %\"": "11.92",
		"\"Explosive Rush %\"": "5.56",
		"\"PROE\"": "1.61",
		"\"Points/Game\"": "18",
		"\"Points/Drive\"": "4",
		"\"FGs/Game\"": "2.5",
		"\"Play Success %\"": "58.28"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"IND\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "287",
		"\"Pass Plays\"": "124",
		"\"Pass Yards/Game\"": "170.75",
		"\"Rush Plays\"": "122",
		"\"Rush Yards/Game\"": "120",
		"\"Total Yards\"": "1163",
		"\"EPA/Play\"": "-0.14",
		"\"Pass EPA/Play\"": "-0.12",
		"\"Rush EPA/Play\"": "-0.14",
		"\"Explosive Pass %\"": "14.52",
		"\"Explosive Rush %\"": "8.2",
		"\"PROE\"": "-11.98",
		"\"Points/Game\"": "18",
		"\"Points/Drive\"": "4.5",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "50.87"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"HOU\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "269",
		"\"Pass Plays\"": "138",
		"\"Pass Yards/Game\"": "198",
		"\"Rush Plays\"": "87",
		"\"Rush Yards/Game\"": "91.5",
		"\"Total Yards\"": "1158",
		"\"EPA/Play\"": "-0.01",
		"\"Pass EPA/Play\"": "-0.03",
		"\"Rush EPA/Play\"": "-0.04",
		"\"Explosive Pass %\"": "12.32",
		"\"Explosive Rush %\"": "9.2",
		"\"PROE\"": "9.46",
		"\"Points/Game\"": "20.25",
		"\"Points/Drive\"": "4.26",
		"\"FGs/Game\"": "2.5",
		"\"Play Success %\"": "49.07"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"NYG\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "306",
		"\"Pass Plays\"": "165",
		"\"Pass Yards/Game\"": "173.5",
		"\"Rush Plays\"": "84",
		"\"Rush Yards/Game\"": "89.75",
		"\"Total Yards\"": "1053",
		"\"EPA/Play\"": "-0.17",
		"\"Pass EPA/Play\"": "-0.29",
		"\"Rush EPA/Play\"": "-0.04",
		"\"Explosive Pass %\"": "9.7",
		"\"Explosive Rush %\"": "9.52",
		"\"PROE\"": "1.52",
		"\"Points/Game\"": "12.75",
		"\"Points/Drive\"": "4.64",
		"\"FGs/Game\"": "1",
		"\"Play Success %\"": "51.96"
	},

]

module.exports = teamOffStatsByRankLastFiveWeeks4for4NFLTeamStatExplorer;