const teamDefStatsByRankLastFiveWeeks4for4NFLTeamStatExplorer = [
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"LAC\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "401",
		"\"Pass Plays\"": "184",
		"\"Pass Yards/Game\"": "247.6",
		"\"Rush Plays\"": "163",
		"\"Rush Yards/Game\"": "151.4",
		"\"Total Yards\"": "1995",
		"\"EPA/Play\"": "0.05",
		"\"Pass EPA/Play\"": "0.12",
		"\"Rush EPA/Play\"": "0",
		"\"Explosive Pass %\"": "13.04",
		"\"Explosive Rush %\"": "8.59",
		"\"PROE\"": "-2.68",
		"\"Points/Game\"": "24.6",
		"\"Points/Drive\"": "4.1",
		"\"FGs/Game\"": "3.2",
		"\"Play Success %\"": "63.59"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"CHI\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "345",
		"\"Pass Plays\"": "154",
		"\"Pass Yards/Game\"": "250.4",
		"\"Rush Plays\"": "146",
		"\"Rush Yards/Game\"": "133.8",
		"\"Total Yards\"": "1921",
		"\"EPA/Play\"": "0.15",
		"\"Pass EPA/Play\"": "0.29",
		"\"Rush EPA/Play\"": "0",
		"\"Explosive Pass %\"": "20.13",
		"\"Explosive Rush %\"": "11.64",
		"\"PROE\"": "-1.78",
		"\"Points/Game\"": "24.6",
		"\"Points/Drive\"": "4.73",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "64.64"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"MIN\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "397",
		"\"Pass Plays\"": "203",
		"\"Pass Yards/Game\"": "268.8",
		"\"Rush Plays\"": "132",
		"\"Rush Yards/Game\"": "107",
		"\"Total Yards\"": "1879",
		"\"EPA/Play\"": "-0.05",
		"\"Pass EPA/Play\"": "0.03",
		"\"Rush EPA/Play\"": "-0.07",
		"\"Explosive Pass %\"": "13.79",
		"\"Explosive Rush %\"": "7.58",
		"\"PROE\"": "-3.52",
		"\"Points/Game\"": "17.4",
		"\"Points/Drive\"": "3.78",
		"\"FGs/Game\"": "3",
		"\"Play Success %\"": "55.16"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"LA\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "368",
		"\"Pass Plays\"": "173",
		"\"Pass Yards/Game\"": "215.6",
		"\"Rush Plays\"": "142",
		"\"Rush Yards/Game\"": "149.6",
		"\"Total Yards\"": "1826",
		"\"EPA/Play\"": "0.1",
		"\"Pass EPA/Play\"": "0.13",
		"\"Rush EPA/Play\"": "0.08",
		"\"Explosive Pass %\"": "15.61",
		"\"Explosive Rush %\"": "9.86",
		"\"PROE\"": "-4.91",
		"\"Points/Game\"": "22.8",
		"\"Points/Drive\"": "4.56",
		"\"FGs/Game\"": "2.2",
		"\"Play Success %\"": "62.23"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"CLE\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "376",
		"\"Pass Plays\"": "165",
		"\"Pass Yards/Game\"": "225.4",
		"\"Rush Plays\"": "158",
		"\"Rush Yards/Game\"": "138.4",
		"\"Total Yards\"": "1819",
		"\"EPA/Play\"": "0.01",
		"\"Pass EPA/Play\"": "0.08",
		"\"Rush EPA/Play\"": "-0.09",
		"\"Explosive Pass %\"": "15.76",
		"\"Explosive Rush %\"": "11.39",
		"\"PROE\"": "-1.58",
		"\"Points/Game\"": "22.8",
		"\"Points/Drive\"": "4.75",
		"\"FGs/Game\"": "1.6",
		"\"Play Success %\"": "52.93"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"DAL\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "370",
		"\"Pass Plays\"": "195",
		"\"Pass Yards/Game\"": "236.4",
		"\"Rush Plays\"": "106",
		"\"Rush Yards/Game\"": "107.2",
		"\"Total Yards\"": "1718",
		"\"EPA/Play\"": "-0.04",
		"\"Pass EPA/Play\"": "-0.13",
		"\"Rush EPA/Play\"": "0.11",
		"\"Explosive Pass %\"": "10.77",
		"\"Explosive Rush %\"": "11.32",
		"\"PROE\"": "2.61",
		"\"Points/Game\"": "21.6",
		"\"Points/Drive\"": "4.7",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "54.86"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"PIT\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "370",
		"\"Pass Plays\"": "184",
		"\"Pass Yards/Game\"": "234.4",
		"\"Rush Plays\"": "128",
		"\"Rush Yards/Game\"": "107.4",
		"\"Total Yards\"": "1709",
		"\"EPA/Play\"": "-0.07",
		"\"Pass EPA/Play\"": "-0.01",
		"\"Rush EPA/Play\"": "-0.03",
		"\"Explosive Pass %\"": "16.3",
		"\"Explosive Rush %\"": "7.81",
		"\"PROE\"": "0.69",
		"\"Points/Game\"": "21",
		"\"Points/Drive\"": "4.38",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "61.89"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"TEN\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "379",
		"\"Pass Plays\"": "173",
		"\"Pass Yards/Game\"": "228.2",
		"\"Rush Plays\"": "147",
		"\"Rush Yards/Game\"": "112.2",
		"\"Total Yards\"": "1702",
		"\"EPA/Play\"": "0.04",
		"\"Pass EPA/Play\"": "0.14",
		"\"Rush EPA/Play\"": "-0.06",
		"\"Explosive Pass %\"": "15.61",
		"\"Explosive Rush %\"": "8.16",
		"\"PROE\"": "4.65",
		"\"Points/Game\"": "22.2",
		"\"Points/Drive\"": "4.62",
		"\"FGs/Game\"": "1.6",
		"\"Play Success %\"": "63.06"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"KC\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "359",
		"\"Pass Plays\"": "187",
		"\"Pass Yards/Game\"": "230",
		"\"Rush Plays\"": "122",
		"\"Rush Yards/Game\"": "107.6",
		"\"Total Yards\"": "1688",
		"\"EPA/Play\"": "-0.01",
		"\"Pass EPA/Play\"": "0.01",
		"\"Rush EPA/Play\"": "-0.05",
		"\"Explosive Pass %\"": "13.37",
		"\"Explosive Rush %\"": "7.38",
		"\"PROE\"": "0.23",
		"\"Points/Game\"": "17.4",
		"\"Points/Drive\"": "4.14",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "57.66"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"LV\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "373",
		"\"Pass Plays\"": "185",
		"\"Pass Yards/Game\"": "232",
		"\"Rush Plays\"": "127",
		"\"Rush Yards/Game\"": "105.6",
		"\"Total Yards\"": "1688",
		"\"EPA/Play\"": "0.04",
		"\"Pass EPA/Play\"": "0.17",
		"\"Rush EPA/Play\"": "-0.13",
		"\"Explosive Pass %\"": "15.14",
		"\"Explosive Rush %\"": "9.45",
		"\"PROE\"": "3.33",
		"\"Points/Game\"": "22.2",
		"\"Points/Drive\"": "4.11",
		"\"FGs/Game\"": "3",
		"\"Play Success %\"": "59.52"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"CIN\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "294",
		"\"Pass Plays\"": "151",
		"\"Pass Yards/Game\"": "286.75",
		"\"Rush Plays\"": "102",
		"\"Rush Yards/Game\"": "126",
		"\"Total Yards\"": "1651",
		"\"EPA/Play\"": "0.05",
		"\"Pass EPA/Play\"": "0.06",
		"\"Rush EPA/Play\"": "0.01",
		"\"Explosive Pass %\"": "19.87",
		"\"Explosive Rush %\"": "13.73",
		"\"PROE\"": "2.27",
		"\"Points/Game\"": "29.25",
		"\"Points/Drive\"": "4.88",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "64.97"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"JAX\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "286",
		"\"Pass Plays\"": "134",
		"\"Pass Yards/Game\"": "272",
		"\"Rush Plays\"": "119",
		"\"Rush Yards/Game\"": "138.75",
		"\"Total Yards\"": "1643",
		"\"EPA/Play\"": "0.21",
		"\"Pass EPA/Play\"": "0.31",
		"\"Rush EPA/Play\"": "0.08",
		"\"Explosive Pass %\"": "19.4",
		"\"Explosive Rush %\"": "11.76",
		"\"PROE\"": "2.74",
		"\"Points/Game\"": "24.75",
		"\"Points/Drive\"": "4.71",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "66.08"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"GB\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "365",
		"\"Pass Plays\"": "198",
		"\"Pass Yards/Game\"": "230.6",
		"\"Rush Plays\"": "114",
		"\"Rush Yards/Game\"": "90.6",
		"\"Total Yards\"": "1606",
		"\"EPA/Play\"": "-0.04",
		"\"Pass EPA/Play\"": "-0.04",
		"\"Rush EPA/Play\"": "-0.04",
		"\"Explosive Pass %\"": "11.62",
		"\"Explosive Rush %\"": "10.53",
		"\"PROE\"": "0.26",
		"\"Points/Game\"": "16.8",
		"\"Points/Drive\"": "4.42",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "60.27"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"DET\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "325",
		"\"Pass Plays\"": "157",
		"\"Pass Yards/Game\"": "217",
		"\"Rush Plays\"": "111",
		"\"Rush Yards/Game\"": "102.2",
		"\"Total Yards\"": "1596",
		"\"EPA/Play\"": "0.01",
		"\"Pass EPA/Play\"": "0.04",
		"\"Rush EPA/Play\"": "0.05",
		"\"Explosive Pass %\"": "17.2",
		"\"Explosive Rush %\"": "9.91",
		"\"PROE\"": "0.78",
		"\"Points/Game\"": "19.8",
		"\"Points/Drive\"": "4.71",
		"\"FGs/Game\"": "1.6",
		"\"Play Success %\"": "53.85"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"MIA\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "349",
		"\"Pass Plays\"": "188",
		"\"Pass Yards/Game\"": "229.6",
		"\"Rush Plays\"": "103",
		"\"Rush Yards/Game\"": "84",
		"\"Total Yards\"": "1568",
		"\"EPA/Play\"": "0.03",
		"\"Pass EPA/Play\"": "0.06",
		"\"Rush EPA/Play\"": "-0.03",
		"\"Explosive Pass %\"": "10.11",
		"\"Explosive Rush %\"": "9.71",
		"\"PROE\"": "5.36",
		"\"Points/Game\"": "18.6",
		"\"Points/Drive\"": "4.23",
		"\"FGs/Game\"": "2.4",
		"\"Play Success %\"": "59.6"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"SEA\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "359",
		"\"Pass Plays\"": "180",
		"\"Pass Yards/Game\"": "205.6",
		"\"Rush Plays\"": "119",
		"\"Rush Yards/Game\"": "106",
		"\"Total Yards\"": "1558",
		"\"EPA/Play\"": "-0.12",
		"\"Pass EPA/Play\"": "-0.07",
		"\"Rush EPA/Play\"": "-0.09",
		"\"Explosive Pass %\"": "8.89",
		"\"Explosive Rush %\"": "10.92",
		"\"PROE\"": "0.64",
		"\"Points/Game\"": "17.4",
		"\"Points/Drive\"": "4.35",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "53.76"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"NYG\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "297",
		"\"Pass Plays\"": "127",
		"\"Pass Yards/Game\"": "241",
		"\"Rush Plays\"": "128",
		"\"Rush Yards/Game\"": "135.25",
		"\"Total Yards\"": "1505",
		"\"EPA/Play\"": "0.06",
		"\"Pass EPA/Play\"": "0.32",
		"\"Rush EPA/Play\"": "-0.13",
		"\"Explosive Pass %\"": "17.32",
		"\"Explosive Rush %\"": "8.59",
		"\"PROE\"": "-2.85",
		"\"Points/Game\"": "21.75",
		"\"Points/Drive\"": "4.83",
		"\"FGs/Game\"": "1.25",
		"\"Play Success %\"": "63.3"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"BUF\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "280",
		"\"Pass Plays\"": "147",
		"\"Pass Yards/Game\"": "265",
		"\"Rush Plays\"": "101",
		"\"Rush Yards/Game\"": "104",
		"\"Total Yards\"": "1476",
		"\"EPA/Play\"": "0.08",
		"\"Pass EPA/Play\"": "0.3",
		"\"Rush EPA/Play\"": "-0.11",
		"\"Explosive Pass %\"": "15.65",
		"\"Explosive Rush %\"": "10.89",
		"\"PROE\"": "-2.8",
		"\"Points/Game\"": "24",
		"\"Points/Drive\"": "4.8",
		"\"FGs/Game\"": "1.25",
		"\"Play Success %\"": "70"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"DEN\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "333",
		"\"Pass Plays\"": "194",
		"\"Pass Yards/Game\"": "278",
		"\"Rush Plays\"": "92",
		"\"Rush Yards/Game\"": "86.25",
		"\"Total Yards\"": "1457",
		"\"EPA/Play\"": "-0.21",
		"\"Pass EPA/Play\"": "-0.22",
		"\"Rush EPA/Play\"": "-0.28",
		"\"Explosive Pass %\"": "14.43",
		"\"Explosive Rush %\"": "7.61",
		"\"PROE\"": "-0.42",
		"\"Points/Game\"": "20.25",
		"\"Points/Drive\"": "4.26",
		"\"FGs/Game\"": "2.5",
		"\"Play Success %\"": "52.85"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"CAR\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "307",
		"\"Pass Plays\"": "131",
		"\"Pass Yards/Game\"": "168.75",
		"\"Rush Plays\"": "131",
		"\"Rush Yards/Game\"": "193.75",
		"\"Total Yards\"": "1450",
		"\"EPA/Play\"": "0.1",
		"\"Pass EPA/Play\"": "0.08",
		"\"Rush EPA/Play\"": "0.17",
		"\"Explosive Pass %\"": "11.45",
		"\"Explosive Rush %\"": "17.56",
		"\"PROE\"": "-4.02",
		"\"Points/Game\"": "23.25",
		"\"Points/Drive\"": "4.23",
		"\"FGs/Game\"": "2.75",
		"\"Play Success %\"": "62.54"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"SF\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "342",
		"\"Pass Plays\"": "137",
		"\"Pass Yards/Game\"": "151.4",
		"\"Rush Plays\"": "162",
		"\"Rush Yards/Game\"": "138.6",
		"\"Total Yards\"": "1450",
		"\"EPA/Play\"": "0.04",
		"\"Pass EPA/Play\"": "0.01",
		"\"Rush EPA/Play\"": "0.06",
		"\"Explosive Pass %\"": "7.3",
		"\"Explosive Rush %\"": "6.79",
		"\"PROE\"": "-10.51",
		"\"Points/Game\"": "21",
		"\"Points/Drive\"": "4.77",
		"\"FGs/Game\"": "1.6",
		"\"Play Success %\"": "58.19"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"NE\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "273",
		"\"Pass Plays\"": "125",
		"\"Pass Yards/Game\"": "236",
		"\"Rush Plays\"": "114",
		"\"Rush Yards/Game\"": "119.75",
		"\"Total Yards\"": "1423",
		"\"EPA/Play\"": "0.12",
		"\"Pass EPA/Play\"": "0.3",
		"\"Rush EPA/Play\"": "-0.05",
		"\"Explosive Pass %\"": "14.4",
		"\"Explosive Rush %\"": "7.02",
		"\"PROE\"": "-1.32",
		"\"Points/Game\"": "27",
		"\"Points/Drive\"": "4.91",
		"\"FGs/Game\"": "1.75",
		"\"Play Success %\"": "65.2"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"NO\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "320",
		"\"Pass Plays\"": "166",
		"\"Pass Yards/Game\"": "236.25",
		"\"Rush Plays\"": "107",
		"\"Rush Yards/Game\"": "117.75",
		"\"Total Yards\"": "1416",
		"\"EPA/Play\"": "-0.06",
		"\"Pass EPA/Play\"": "-0.01",
		"\"Rush EPA/Play\"": "0.04",
		"\"Explosive Pass %\"": "13.25",
		"\"Explosive Rush %\"": "9.35",
		"\"PROE\"": "-0.03",
		"\"Points/Game\"": "14.25",
		"\"Points/Drive\"": "3.8",
		"\"FGs/Game\"": "1.75",
		"\"Play Success %\"": "56.88"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"PHI\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "349",
		"\"Pass Plays\"": "174",
		"\"Pass Yards/Game\"": "173.2",
		"\"Rush Plays\"": "129",
		"\"Rush Yards/Game\"": "105",
		"\"Total Yards\"": "1391",
		"\"EPA/Play\"": "-0.06",
		"\"Pass EPA/Play\"": "0.01",
		"\"Rush EPA/Play\"": "-0.16",
		"\"Explosive Pass %\"": "10.34",
		"\"Explosive Rush %\"": "8.53",
		"\"PROE\"": "-3.64",
		"\"Points/Game\"": "15.6",
		"\"Points/Drive\"": "4.11",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "56.73"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"HOU\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "321",
		"\"Pass Plays\"": "179",
		"\"Pass Yards/Game\"": "252.25",
		"\"Rush Plays\"": "95",
		"\"Rush Yards/Game\"": "86.25",
		"\"Total Yards\"": "1354",
		"\"EPA/Play\"": "-0.13",
		"\"Pass EPA/Play\"": "-0.1",
		"\"Rush EPA/Play\"": "-0.23",
		"\"Explosive Pass %\"": "10.06",
		"\"Explosive Rush %\"": "5.26",
		"\"PROE\"": "-0.16",
		"\"Points/Game\"": "19.5",
		"\"Points/Drive\"": "4.11",
		"\"FGs/Game\"": "2.5",
		"\"Play Success %\"": "53.89"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"NYJ\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "306",
		"\"Pass Plays\"": "154",
		"\"Pass Yards/Game\"": "241.25",
		"\"Rush Plays\"": "105",
		"\"Rush Yards/Game\"": "88",
		"\"Total Yards\"": "1317",
		"\"EPA/Play\"": "0.13",
		"\"Pass EPA/Play\"": "0.18",
		"\"Rush EPA/Play\"": "-0.06",
		"\"Explosive Pass %\"": "13.64",
		"\"Explosive Rush %\"": "3.81",
		"\"PROE\"": "-1.77",
		"\"Points/Game\"": "23.25",
		"\"Points/Drive\"": "4.23",
		"\"FGs/Game\"": "3.25",
		"\"Play Success %\"": "60.78"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"ARI\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "260",
		"\"Pass Plays\"": "127",
		"\"Pass Yards/Game\"": "213.25",
		"\"Rush Plays\"": "95",
		"\"Rush Yards/Game\"": "106.25",
		"\"Total Yards\"": "1278",
		"\"EPA/Play\"": "0.01",
		"\"Pass EPA/Play\"": "0.07",
		"\"Rush EPA/Play\"": "-0.04",
		"\"Explosive Pass %\"": "18.11",
		"\"Explosive Rush %\"": "11.58",
		"\"PROE\"": "1.91",
		"\"Points/Game\"": "18",
		"\"Points/Drive\"": "4",
		"\"FGs/Game\"": "2.5",
		"\"Play Success %\"": "54.23"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"ATL\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "267",
		"\"Pass Plays\"": "138",
		"\"Pass Yards/Game\"": "232",
		"\"Rush Plays\"": "89",
		"\"Rush Yards/Game\"": "85.25",
		"\"Total Yards\"": "1269",
		"\"EPA/Play\"": "0.03",
		"\"Pass EPA/Play\"": "0.2",
		"\"Rush EPA/Play\"": "-0.14",
		"\"Explosive Pass %\"": "13.04",
		"\"Explosive Rush %\"": "12.36",
		"\"PROE\"": "2.28",
		"\"Points/Game\"": "21.75",
		"\"Points/Drive\"": "4.83",
		"\"FGs/Game\"": "1.5",
		"\"Play Success %\"": "59.93"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"IND\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "290",
		"\"Pass Plays\"": "139",
		"\"Pass Yards/Game\"": "189.5",
		"\"Rush Plays\"": "111",
		"\"Rush Yards/Game\"": "125",
		"\"Total Yards\"": "1258",
		"\"EPA/Play\"": "-0.01",
		"\"Pass EPA/Play\"": "0.01",
		"\"Rush EPA/Play\"": "-0.05",
		"\"Explosive Pass %\"": "10.79",
		"\"Explosive Rush %\"": "12.61",
		"\"PROE\"": "0.98",
		"\"Points/Game\"": "21.75",
		"\"Points/Drive\"": "4.35",
		"\"FGs/Game\"": "2.25",
		"\"Play Success %\"": "56.21"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"WAS\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "281",
		"\"Pass Plays\"": "137",
		"\"Pass Yards/Game\"": "208.25",
		"\"Rush Plays\"": "95",
		"\"Rush Yards/Game\"": "105.75",
		"\"Total Yards\"": "1256",
		"\"EPA/Play\"": "-0.04",
		"\"Pass EPA/Play\"": "0.09",
		"\"Rush EPA/Play\"": "-0.12",
		"\"Explosive Pass %\"": "15.33",
		"\"Explosive Rush %\"": "7.37",
		"\"PROE\"": "-3.22",
		"\"Points/Game\"": "19.5",
		"\"Points/Drive\"": "3.71",
		"\"FGs/Game\"": "3",
		"\"Play Success %\"": "52.67"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"TB\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "273",
		"\"Pass Plays\"": "157",
		"\"Pass Yards/Game\"": "202.75",
		"\"Rush Plays\"": "75",
		"\"Rush Yards/Game\"": "67",
		"\"Total Yards\"": "1079",
		"\"EPA/Play\"": "-0.18",
		"\"Pass EPA/Play\"": "-0.16",
		"\"Rush EPA/Play\"": "-0.17",
		"\"Explosive Pass %\"": "8.92",
		"\"Explosive Rush %\"": "5.33",
		"\"PROE\"": "5.27",
		"\"Points/Game\"": "13.5",
		"\"Points/Drive\"": "3.86",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "50.92"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"BAL\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "310",
		"\"Pass Plays\"": "141",
		"\"Pass Yards/Game\"": "169",
		"\"Rush Plays\"": "107",
		"\"Rush Yards/Game\"": "100",
		"\"Total Yards\"": "1076",
		"\"EPA/Play\"": "-0.02",
		"\"Pass EPA/Play\"": "-0.17",
		"\"Rush EPA/Play\"": "-0.05",
		"\"Explosive Pass %\"": "12.06",
		"\"Explosive Rush %\"": "10.28",
		"\"PROE\"": "-0.36",
		"\"Points/Game\"": "18",
		"\"Points/Drive\"": "4.24",
		"\"FGs/Game\"": "2.5",
		"\"Play Success %\"": "55.81"
	},
	
]

module.exports = teamDefStatsByRankLastFiveWeeks4for4NFLTeamStatExplorer;