const teamDefStatsByRankLastFiveWeeks4for4NFLTeamStatExplorer = [
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"NO\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "389",
		"\"Pass Plays\"": "212",
		"\"Pass Yards/Game\"": "287.2",
		"\"Rush Plays\"": "130",
		"\"Rush Yards/Game\"": "158.2",
		"\"Total Yards\"": "2218",
		"\"EPA/Play\"": "0.04",
		"\"Pass EPA/Play\"": "0.03",
		"\"Rush EPA/Play\"": "0.19",
		"\"Explosive Pass %\"": "12.26",
		"\"Explosive Rush %\"": "15.38",
		"\"PROE\"": "3.29",
		"\"Points/Game\"": "24.6",
		"\"Points/Drive\"": "4.24",
		"\"FGs/Game\"": "3",
		"\"Play Success %\"": "60.93"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"ARI\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "375",
		"\"Pass Plays\"": "187",
		"\"Pass Yards/Game\"": "267.6",
		"\"Rush Plays\"": "149",
		"\"Rush Yards/Game\"": "140.8",
		"\"Total Yards\"": "2038",
		"\"EPA/Play\"": "0.12",
		"\"Pass EPA/Play\"": "0.27",
		"\"Rush EPA/Play\"": "-0.01",
		"\"Explosive Pass %\"": "12.37",
		"\"Explosive Rush %\"": "13.42",
		"\"PROE\"": "-0.91",
		"\"Points/Game\"": "22.8",
		"\"Points/Drive\"": "4.38",
		"\"FGs/Game\"": "2.6",
		"\"Play Success %\"": "69.6"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"CAR\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "373",
		"\"Pass Plays\"": "185",
		"\"Pass Yards/Game\"": "262.2",
		"\"Rush Plays\"": "147",
		"\"Rush Yards/Game\"": "134.6",
		"\"Total Yards\"": "1972",
		"\"EPA/Play\"": "0.14",
		"\"Pass EPA/Play\"": "0.29",
		"\"Rush EPA/Play\"": "0",
		"\"Explosive Pass %\"": "14.05",
		"\"Explosive Rush %\"": "6.12",
		"\"PROE\"": "-3",
		"\"Points/Game\"": "28.8",
		"\"Points/Drive\"": "4.8",
		"\"FGs/Game\"": "2.2",
		"\"Play Success %\"": "63.27"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"JAX\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "367",
		"\"Pass Plays\"": "225",
		"\"Pass Yards/Game\"": "312.6",
		"\"Rush Plays\"": "104",
		"\"Rush Yards/Game\"": "76",
		"\"Total Yards\"": "1938",
		"\"EPA/Play\"": "0.17",
		"\"Pass EPA/Play\"": "0.38",
		"\"Rush EPA/Play\"": "-0.08",
		"\"Explosive Pass %\"": "16.96",
		"\"Explosive Rush %\"": "8.65",
		"\"PROE\"": "2.72",
		"\"Points/Game\"": "28.8",
		"\"Points/Drive\"": "5.14",
		"\"FGs/Game\"": "1.4",
		"\"Play Success %\"": "67.85"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"NE\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "372",
		"\"Pass Plays\"": "173",
		"\"Pass Yards/Game\"": "230.8",
		"\"Rush Plays\"": "165",
		"\"Rush Yards/Game\"": "156.6",
		"\"Total Yards\"": "1935",
		"\"EPA/Play\"": "0.09",
		"\"Pass EPA/Play\"": "0.28",
		"\"Rush EPA/Play\"": "-0.01",
		"\"Explosive Pass %\"": "13.29",
		"\"Explosive Rush %\"": "10.91",
		"\"PROE\"": "-4.76",
		"\"Points/Game\"": "22.8",
		"\"Points/Drive\"": "4.22",
		"\"FGs/Game\"": "2.6",
		"\"Play Success %\"": "62.9"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"SEA\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "359",
		"\"Pass Plays\"": "178",
		"\"Pass Yards/Game\"": "235",
		"\"Rush Plays\"": "136",
		"\"Rush Yards/Game\"": "142.6",
		"\"Total Yards\"": "1882",
		"\"EPA/Play\"": "0",
		"\"Pass EPA/Play\"": "0.09",
		"\"Rush EPA/Play\"": "-0.05",
		"\"Explosive Pass %\"": "12.92",
		"\"Explosive Rush %\"": "10.29",
		"\"PROE\"": "-1.55",
		"\"Points/Game\"": "23.4",
		"\"Points/Drive\"": "4.68",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "55.71"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"IND\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "384",
		"\"Pass Plays\"": "200",
		"\"Pass Yards/Game\"": "254.2",
		"\"Rush Plays\"": "141",
		"\"Rush Yards/Game\"": "120.6",
		"\"Total Yards\"": "1874",
		"\"EPA/Play\"": "-0.06",
		"\"Pass EPA/Play\"": "0.04",
		"\"Rush EPA/Play\"": "-0.17",
		"\"Explosive Pass %\"": "10",
		"\"Explosive Rush %\"": "9.29",
		"\"PROE\"": "-8.06",
		"\"Points/Game\"": "18.6",
		"\"Points/Drive\"": "4.43",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "59.9"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"BAL\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "380",
		"\"Pass Plays\"": "242",
		"\"Pass Yards/Game\"": "312.6",
		"\"Rush Plays\"": "95",
		"\"Rush Yards/Game\"": "62.2",
		"\"Total Yards\"": "1873",
		"\"EPA/Play\"": "0.07",
		"\"Pass EPA/Play\"": "0.17",
		"\"Rush EPA/Play\"": "-0.1",
		"\"Explosive Pass %\"": "15.77",
		"\"Explosive Rush %\"": "4.21",
		"\"PROE\"": "3.72",
		"\"Points/Game\"": "22.2",
		"\"Points/Drive\"": "4.44",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "62.37"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"TB\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "371",
		"\"Pass Plays\"": "223",
		"\"Pass Yards/Game\"": "264.4",
		"\"Rush Plays\"": "110",
		"\"Rush Yards/Game\"": "110.2",
		"\"Total Yards\"": "1870",
		"\"EPA/Play\"": "0.02",
		"\"Pass EPA/Play\"": "0.09",
		"\"Rush EPA/Play\"": "-0.11",
		"\"Explosive Pass %\"": "13",
		"\"Explosive Rush %\"": "7.27",
		"\"PROE\"": "1.81",
		"\"Points/Game\"": "24.6",
		"\"Points/Drive\"": "4.39",
		"\"FGs/Game\"": "2.6",
		"\"Play Success %\"": "58.76"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"CIN\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "389",
		"\"Pass Plays\"": "227",
		"\"Pass Yards/Game\"": "263",
		"\"Rush Plays\"": "126",
		"\"Rush Yards/Game\"": "101.2",
		"\"Total Yards\"": "1814",
		"\"EPA/Play\"": "0.06",
		"\"Pass EPA/Play\"": "0.1",
		"\"Rush EPA/Play\"": "0.1",
		"\"Explosive Pass %\"": "8.81",
		"\"Explosive Rush %\"": "7.94",
		"\"PROE\"": "2.66",
		"\"Points/Game\"": "21",
		"\"Points/Drive\"": "4.77",
		"\"FGs/Game\"": "1.2",
		"\"Play Success %\"": "66.84"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"BUF\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "370",
		"\"Pass Plays\"": "203",
		"\"Pass Yards/Game\"": "228.4",
		"\"Rush Plays\"": "128",
		"\"Rush Yards/Game\"": "126.2",
		"\"Total Yards\"": "1773",
		"\"EPA/Play\"": "-0.05",
		"\"Pass EPA/Play\"": "0.01",
		"\"Rush EPA/Play\"": "-0.08",
		"\"Explosive Pass %\"": "11.94",
		"\"Explosive Rush %\"": "13.28",
		"\"PROE\"": "-2.98",
		"\"Points/Game\"": "17.4",
		"\"Points/Drive\"": "4.35",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "54.86"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"ATL\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "362",
		"\"Pass Plays\"": "194",
		"\"Pass Yards/Game\"": "238.8",
		"\"Rush Plays\"": "129",
		"\"Rush Yards/Game\"": "107.6",
		"\"Total Yards\"": "1718",
		"\"EPA/Play\"": "0.07",
		"\"Pass EPA/Play\"": "0.12",
		"\"Rush EPA/Play\"": "0",
		"\"Explosive Pass %\"": "11.86",
		"\"Explosive Rush %\"": "8.59",
		"\"PROE\"": "-0.27",
		"\"Points/Game\"": "23.4",
		"\"Points/Drive\"": "4.68",
		"\"FGs/Game\"": "2.2",
		"\"Play Success %\"": "62.71"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"CLE\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "360",
		"\"Pass Plays\"": "162",
		"\"Pass Yards/Game\"": "211.8",
		"\"Rush Plays\"": "138",
		"\"Rush Yards/Game\"": "118.2",
		"\"Total Yards\"": "1637",
		"\"EPA/Play\"": "-0.07",
		"\"Pass EPA/Play\"": "0.1",
		"\"Rush EPA/Play\"": "-0.12",
		"\"Explosive Pass %\"": "16.05",
		"\"Explosive Rush %\"": "10.87",
		"\"PROE\"": "-4.76",
		"\"Points/Game\"": "21.6",
		"\"Points/Drive\"": "4.7",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "50.56"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"WAS\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "327",
		"\"Pass Plays\"": "165",
		"\"Pass Yards/Game\"": "191.6",
		"\"Rush Plays\"": "125",
		"\"Rush Yards/Game\"": "130.6",
		"\"Total Yards\"": "1608",
		"\"EPA/Play\"": "-0.02",
		"\"Pass EPA/Play\"": "-0.03",
		"\"Rush EPA/Play\"": "0.03",
		"\"Explosive Pass %\"": "14.55",
		"\"Explosive Rush %\"": "14.4",
		"\"PROE\"": "-7.8",
		"\"Points/Game\"": "18.6",
		"\"Points/Drive\"": "4.65",
		"\"FGs/Game\"": "1.6",
		"\"Play Success %\"": "59.02"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"PIT\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "344",
		"\"Pass Plays\"": "190",
		"\"Pass Yards/Game\"": "232",
		"\"Rush Plays\"": "115",
		"\"Rush Yards/Game\"": "81.6",
		"\"Total Yards\"": "1567",
		"\"EPA/Play\"": "-0.09",
		"\"Pass EPA/Play\"": "0.09",
		"\"Rush EPA/Play\"": "-0.22",
		"\"Explosive Pass %\"": "13.68",
		"\"Explosive Rush %\"": "9.57",
		"\"PROE\"": "-2.42",
		"\"Points/Game\"": "15",
		"\"Points/Drive\"": "4.17",
		"\"FGs/Game\"": "1.6",
		"\"Play Success %\"": "55.23"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"SF\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "360",
		"\"Pass Plays\"": "195",
		"\"Pass Yards/Game\"": "207",
		"\"Rush Plays\"": "128",
		"\"Rush Yards/Game\"": "104.8",
		"\"Total Yards\"": "1554",
		"\"EPA/Play\"": "-0.04",
		"\"Pass EPA/Play\"": "-0.02",
		"\"Rush EPA/Play\"": "-0.02",
		"\"Explosive Pass %\"": "9.23",
		"\"Explosive Rush %\"": "6.25",
		"\"PROE\"": "-5.72",
		"\"Points/Game\"": "21.6",
		"\"Points/Drive\"": "4.91",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "59.17"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"LV\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "362",
		"\"Pass Plays\"": "179",
		"\"Pass Yards/Game\"": "193.6",
		"\"Rush Plays\"": "125",
		"\"Rush Yards/Game\"": "112.2",
		"\"Total Yards\"": "1519",
		"\"EPA/Play\"": "-0.04",
		"\"Pass EPA/Play\"": "0.03",
		"\"Rush EPA/Play\"": "-0.04",
		"\"Explosive Pass %\"": "11.73",
		"\"Explosive Rush %\"": "11.2",
		"\"PROE\"": "1.16",
		"\"Points/Game\"": "21.6",
		"\"Points/Drive\"": "4.5",
		"\"FGs/Game\"": "2.2",
		"\"Play Success %\"": "52.49"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"NYG\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "343",
		"\"Pass Plays\"": "190",
		"\"Pass Yards/Game\"": "204.4",
		"\"Rush Plays\"": "104",
		"\"Rush Yards/Game\"": "93.8",
		"\"Total Yards\"": "1486",
		"\"EPA/Play\"": "-0.06",
		"\"Pass EPA/Play\"": "-0.03",
		"\"Rush EPA/Play\"": "-0.09",
		"\"Explosive Pass %\"": "8.99",
		"\"Explosive Rush %\"": "7.69",
		"\"PROE\"": "2.77",
		"\"Points/Game\"": "17.4",
		"\"Points/Drive\"": "4.58",
		"\"FGs/Game\"": "1.6",
		"\"Play Success %\"": "49.56"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"GB\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "358",
		"\"Pass Plays\"": "200",
		"\"Pass Yards/Game\"": "205.6",
		"\"Rush Plays\"": "115",
		"\"Rush Yards/Game\"": "91.4",
		"\"Total Yards\"": "1481",
		"\"EPA/Play\"": "-0.1",
		"\"Pass EPA/Play\"": "-0.12",
		"\"Rush EPA/Play\"": "-0.11",
		"\"Explosive Pass %\"": "10.5",
		"\"Explosive Rush %\"": "7.83",
		"\"PROE\"": "0.27",
		"\"Points/Game\"": "18",
		"\"Points/Drive\"": "5",
		"\"FGs/Game\"": "1.2",
		"\"Play Success %\"": "55.31"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"DAL\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "288",
		"\"Pass Plays\"": "128",
		"\"Pass Yards/Game\"": "228.25",
		"\"Rush Plays\"": "124",
		"\"Rush Yards/Game\"": "142.25",
		"\"Total Yards\"": "1477",
		"\"EPA/Play\"": "0.14",
		"\"Pass EPA/Play\"": "0.2",
		"\"Rush EPA/Play\"": "0.12",
		"\"Explosive Pass %\"": "16.41",
		"\"Explosive Rush %\"": "12.9",
		"\"PROE\"": "-6.83",
		"\"Points/Game\"": "24",
		"\"Points/Drive\"": "4.36",
		"\"FGs/Game\"": "2.75",
		"\"Play Success %\"": "58.68"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"HOU\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "351",
		"\"Pass Plays\"": "188",
		"\"Pass Yards/Game\"": "187.8",
		"\"Rush Plays\"": "116",
		"\"Rush Yards/Game\"": "98.6",
		"\"Total Yards\"": "1431",
		"\"EPA/Play\"": "-0.01",
		"\"Pass EPA/Play\"": "-0.02",
		"\"Rush EPA/Play\"": "-0.12",
		"\"Explosive Pass %\"": "11.17",
		"\"Explosive Rush %\"": "10.34",
		"\"PROE\"": "-2.73",
		"\"Points/Game\"": "21",
		"\"Points/Drive\"": "5",
		"\"FGs/Game\"": "1.4",
		"\"Play Success %\"": "51.85"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"DET\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "301",
		"\"Pass Plays\"": "207",
		"\"Pass Yards/Game\"": "279",
		"\"Rush Plays\"": "67",
		"\"Rush Yards/Game\"": "77.75",
		"\"Total Yards\"": "1427",
		"\"EPA/Play\"": "-0.1",
		"\"Pass EPA/Play\"": "-0.1",
		"\"Rush EPA/Play\"": "-0.11",
		"\"Explosive Pass %\"": "11.22",
		"\"Explosive Rush %\"": "13.43",
		"\"PROE\"": "4.85",
		"\"Points/Game\"": "16.5",
		"\"Points/Drive\"": "4.12",
		"\"FGs/Game\"": "2.25",
		"\"Play Success %\"": "55.48"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"DEN\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "394",
		"\"Pass Plays\"": "234",
		"\"Pass Yards/Game\"": "201.2",
		"\"Rush Plays\"": "110",
		"\"Rush Yards/Game\"": "84",
		"\"Total Yards\"": "1422",
		"\"EPA/Play\"": "-0.2",
		"\"Pass EPA/Play\"": "-0.26",
		"\"Rush EPA/Play\"": "-0.07",
		"\"Explosive Pass %\"": "6.87",
		"\"Explosive Rush %\"": "7.27",
		"\"PROE\"": "1.78",
		"\"Points/Game\"": "14.4",
		"\"Points/Drive\"": "4.24",
		"\"FGs/Game\"": "1.8",
		"\"Play Success %\"": "49.49"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"MIN\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "307",
		"\"Pass Plays\"": "199",
		"\"Pass Yards/Game\"": "280",
		"\"Rush Plays\"": "70",
		"\"Rush Yards/Game\"": "72.5",
		"\"Total Yards\"": "1406",
		"\"EPA/Play\"": "-0.16",
		"\"Pass EPA/Play\"": "-0.09",
		"\"Rush EPA/Play\"": "-0.34",
		"\"Explosive Pass %\"": "14.57",
		"\"Explosive Rush %\"": "5.71",
		"\"PROE\"": "1.57",
		"\"Points/Game\"": "21",
		"\"Points/Drive\"": "4.67",
		"\"FGs/Game\"": "1.25",
		"\"Play Success %\"": "51.79"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"NYJ\"",
		"\"Games\"": "5",
		"\"Total Plays\"": "367",
		"\"Pass Plays\"": "181",
		"\"Pass Yards/Game\"": "160.8",
		"\"Rush Plays\"": "134",
		"\"Rush Yards/Game\"": "110.2",
		"\"Total Yards\"": "1346",
		"\"EPA/Play\"": "-0.04",
		"\"Pass EPA/Play\"": "-0.04",
		"\"Rush EPA/Play\"": "-0.04",
		"\"Explosive Pass %\"": "10.06",
		"\"Explosive Rush %\"": "7.46",
		"\"PROE\"": "-4.62",
		"\"Points/Game\"": "16.2",
		"\"Points/Drive\"": "4.05",
		"\"FGs/Game\"": "2.2",
		"\"Play Success %\"": "51.23"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"LA\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "305",
		"\"Pass Plays\"": "153",
		"\"Pass Yards/Game\"": "215.5",
		"\"Rush Plays\"": "112",
		"\"Rush Yards/Game\"": "117.75",
		"\"Total Yards\"": "1329",
		"\"EPA/Play\"": "-0.05",
		"\"Pass EPA/Play\"": "0.02",
		"\"Rush EPA/Play\"": "-0.04",
		"\"Explosive Pass %\"": "8.5",
		"\"Explosive Rush %\"": "8.04",
		"\"PROE\"": "-5.29",
		"\"Points/Game\"": "22.5",
		"\"Points/Drive\"": "4.5",
		"\"FGs/Game\"": "2.25",
		"\"Play Success %\"": "57.05"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"LAC\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "272",
		"\"Pass Plays\"": "148",
		"\"Pass Yards/Game\"": "239",
		"\"Rush Plays\"": "87",
		"\"Rush Yards/Game\"": "92.25",
		"\"Total Yards\"": "1317",
		"\"EPA/Play\"": "-0.02",
		"\"Pass EPA/Play\"": "0.11",
		"\"Rush EPA/Play\"": "-0.16",
		"\"Explosive Pass %\"": "13.51",
		"\"Explosive Rush %\"": "12.64",
		"\"PROE\"": "-2.38",
		"\"Points/Game\"": "15.75",
		"\"Points/Drive\"": "4.2",
		"\"FGs/Game\"": "1.75",
		"\"Play Success %\"": "58.09"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"TEN\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "280",
		"\"Pass Plays\"": "134",
		"\"Pass Yards/Game\"": "208.25",
		"\"Rush Plays\"": "113",
		"\"Rush Yards/Game\"": "96.75",
		"\"Total Yards\"": "1220",
		"\"EPA/Play\"": "-0.02",
		"\"Pass EPA/Play\"": "0.13",
		"\"Rush EPA/Play\"": "-0.22",
		"\"Explosive Pass %\"": "16.42",
		"\"Explosive Rush %\"": "8.85",
		"\"PROE\"": "-5.61",
		"\"Points/Game\"": "20.25",
		"\"Points/Drive\"": "4.5",
		"\"FGs/Game\"": "2.25",
		"\"Play Success %\"": "51.79"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"CHI\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "268",
		"\"Pass Plays\"": "142",
		"\"Pass Yards/Game\"": "194.5",
		"\"Rush Plays\"": "89",
		"\"Rush Yards/Game\"": "106.5",
		"\"Total Yards\"": "1198",
		"\"EPA/Play\"": "-0.09",
		"\"Pass EPA/Play\"": "-0.2",
		"\"Rush EPA/Play\"": "0.07",
		"\"Explosive Pass %\"": "12.68",
		"\"Explosive Rush %\"": "12.36",
		"\"PROE\"": "-5.54",
		"\"Points/Game\"": "15",
		"\"Points/Drive\"": "4",
		"\"FGs/Game\"": "2",
		"\"Play Success %\"": "51.87"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"MIA\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "299",
		"\"Pass Plays\"": "132",
		"\"Pass Yards/Game\"": "174",
		"\"Rush Plays\"": "114",
		"\"Rush Yards/Game\"": "126",
		"\"Total Yards\"": "1197",
		"\"EPA/Play\"": "-0.12",
		"\"Pass EPA/Play\"": "-0.16",
		"\"Rush EPA/Play\"": "-0.06",
		"\"Explosive Pass %\"": "12.98",
		"\"Explosive Rush %\"": "11.4",
		"\"PROE\"": "-6",
		"\"Points/Game\"": "18",
		"\"Points/Drive\"": "3.79",
		"\"FGs/Game\"": "3",
		"\"Play Success %\"": "44.82"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"KC\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "262",
		"\"Pass Plays\"": "146",
		"\"Pass Yards/Game\"": "204",
		"\"Rush Plays\"": "85",
		"\"Rush Yards/Game\"": "62.5",
		"\"Total Yards\"": "1065",
		"\"EPA/Play\"": "-0.12",
		"\"Pass EPA/Play\"": "-0.04",
		"\"Rush EPA/Play\"": "-0.28",
		"\"Explosive Pass %\"": "8.28",
		"\"Explosive Rush %\"": "5.88",
		"\"PROE\"": "-4",
		"\"Points/Game\"": "13.5",
		"\"Points/Drive\"": "4.5",
		"\"FGs/Game\"": "1.25",
		"\"Play Success %\"": "50.76"
	},
	{
		"\"Rank\"": "NA",
		"\"Team\"": "\"PHI\"",
		"\"Games\"": "4",
		"\"Total Plays\"": "289",
		"\"Pass Plays\"": "154",
		"\"Pass Yards/Game\"": "175.25",
		"\"Rush Plays\"": "90",
		"\"Rush Yards/Game\"": "82",
		"\"Total Yards\"": "1027",
		"\"EPA/Play\"": "-0.06",
		"\"Pass EPA/Play\"": "-0.03",
		"\"Rush EPA/Play\"": "-0.17",
		"\"Explosive Pass %\"": "7.14",
		"\"Explosive Rush %\"": "7.78",
		"\"PROE\"": "0.3",
		"\"Points/Game\"": "13.5",
		"\"Points/Drive\"": "3.86",
		"\"FGs/Game\"": "2.25",
		"\"Play Success %\"": "49.83"
	},
	
]

module.exports = teamDefStatsByRankLastFiveWeeks4for4NFLTeamStatExplorer;