const teamOffStatsByRankLastFiveWeeks4for4NFLTeamStatExplorer = [
	{
		"Player": "\"Ja'Marr Chase\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "5",
		"W4": "17.5",
		"W5": "41.3",
		"W6": "12.2",
		"W7": "17.6",
		"W8": "20.4",
		"\"PPR Pts\"": "109.0",
		"\"PPR Pts/G\"": "21.8"
	},
	{
		"Player": "\"Drake London\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "5",
		"W4": "12.4",
		"W5": "33.4",
		"W6": "19.4",
		"W7": "18.3",
		"W8": "7.4",
		"\"PPR Pts\"": "90.9",
		"\"PPR Pts/G\"": "18.2"
	},
	{
		"Player": "\"CeeDee Lamb\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "4",
		"W4": "23.6",
		"W5": "11.4",
		"W6": "16.1",
		"W7": "-",
		"W8": "39.6",
		"\"PPR Pts\"": "90.7",
		"\"PPR Pts/G\"": "22.7"
	},
	{
		"Player": "\"Garrett Wilson\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "5",
		"W4": "7.1",
		"W5": "29.1",
		"W6": "24.7",
		"W7": "13.1",
		"W8": "16.3",
		"\"PPR Pts\"": "90.3",
		"\"PPR Pts/G\"": "18.1"
	},
	{
		"Player": "\"Terry McLaurin\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "5",
		"W4": "18.2",
		"W5": "13.4",
		"W6": "23.3",
		"W7": "15.8",
		"W8": "17.5",
		"\"PPR Pts\"": "88.2",
		"\"PPR Pts/G\"": "17.6"
	},
	{
		"Player": "\"Brian Thomas Jr.\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "5",
		"W4": "21.9",
		"W5": "23.2",
		"W6": "5.7",
		"W7": "22.1",
		"W8": "15.0",
		"\"PPR Pts\"": "87.9",
		"\"PPR Pts/G\"": "17.6"
	},
	{
		"Player": "\"Josh Downs\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "5",
		"W4": "22.2",
		"W5": "15.9",
		"W6": "19.5",
		"W7": "1.3",
		"W8": "22.2",
		"\"PPR Pts\"": "81.1",
		"\"PPR Pts/G\"": "16.2"
	},
	{
		"Player": "\"Justin Jefferson\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "4",
		"W4": "20.5",
		"W5": "15.2",
		"W6": "-",
		"W7": "21.4",
		"W8": "19.5",
		"\"PPR Pts\"": "76.6",
		"\"PPR Pts/G\"": "19.2"
	},
	{
		"Player": "\"Darnell Mooney\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "5",
		"W4": "8.6",
		"W5": "31.5",
		"W6": "6.8",
		"W7": "9.6",
		"W8": "18.6",
		"\"PPR Pts\"": "75.1",
		"\"PPR Pts/G\"": "15.0"
	},
	{
		"Player": "\"Tee Higgins\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "4",
		"W4": "12.0",
		"W5": "29.3",
		"W6": "14.7",
		"W7": "18.2",
		"W8": "-",
		"\"PPR Pts\"": "74.2",
		"\"PPR Pts/G\"": "18.6"
	},
	{
		"Player": "\"Chris Godwin\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "4",
		"W4": "12.9",
		"W5": "11.6",
		"W6": "35.5",
		"W7": "13.5",
		"W8": "-",
		"\"PPR Pts\"": "73.5",
		"\"PPR Pts/G\"": "18.4"
	},
	{
		"Player": "\"Stefon Diggs\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "5",
		"W4": "18.5",
		"W5": "14.2",
		"W6": "19.7",
		"W7": "7.3",
		"W8": "12.7",
		"\"PPR Pts\"": "72.4",
		"\"PPR Pts/G\"": "14.5"
	},
	{
		"Player": "\"Amon-Ra St. Brown\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "4",
		"W4": "20.8",
		"W5": "-",
		"W6": "13.7",
		"W7": "25.2",
		"W8": "8.7",
		"\"PPR Pts\"": "68.4",
		"\"PPR Pts/G\"": "17.1"
	},
	{
		"Player": "\"Jayden Reed\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "5",
		"W4": "27.1",
		"W5": "13.7",
		"W6": "14.8",
		"W7": "3.0",
		"W8": "7.5",
		"\"PPR Pts\"": "66.1",
		"\"PPR Pts/G\"": "13.2"
	},
	{
		"Player": "\"Zay Flowers\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "5",
		"W4": "2.0",
		"W5": "19.0",
		"W6": "22.4",
		"W7": "4.0",
		"W8": "18.5",
		"\"PPR Pts\"": "65.9",
		"\"PPR Pts/G\"": "13.2"
	},
	{
		"Player": "\"Ladd McConkey\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "4",
		"W4": "17.7",
		"W5": "-",
		"W6": "8.3",
		"W7": "9.6",
		"W8": "29.1",
		"\"PPR Pts\"": "64.7",
		"\"PPR Pts/G\"": "16.2"
	},
	{
		"Player": "\"George Pickens\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "5",
		"W4": "16.3",
		"W5": "5.6",
		"W6": "8.3",
		"W7": "22.1",
		"W8": "11.4",
		"\"PPR Pts\"": "63.7",
		"\"PPR Pts/G\"": "12.7"
	},
	{
		"Player": "\"Darius Slayton\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "5",
		"W4": "8.6",
		"W5": "26.2",
		"W6": "11.7",
		"W7": "2.1",
		"W8": "14.8",
		"\"PPR Pts\"": "63.4",
		"\"PPR Pts/G\"": "12.7"
	},
	{
		"Player": "\"Mike Evans\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "4",
		"W4": "23.4",
		"W5": "23.2",
		"W6": "5.4",
		"W7": "9.5",
		"W8": "-",
		"\"PPR Pts\"": "61.5",
		"\"PPR Pts/G\"": "15.4"
	},
	{
		"Player": "\"Wan'Dale Robinson\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "5",
		"W4": "18.1",
		"W5": "16.0",
		"W6": "10.0",
		"W7": "8.3",
		"W8": "8.0",
		"\"PPR Pts\"": "60.4",
		"\"PPR Pts/G\"": "12.1"
	},
	{
		"Player": "\"Keon Coleman\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "5",
		"W4": "8.1",
		"W5": "11.9",
		"W6": "5.6",
		"W7": "16.5",
		"W8": "18.0",
		"\"PPR Pts\"": "60.1",
		"\"PPR Pts/G\"": "12.0"
	},
	{
		"Player": "\"Allen Lazard\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "4",
		"W4": "10.8",
		"W5": "13.4",
		"W6": "23.4",
		"W7": "9.8",
		"W8": "-",
		"\"PPR Pts\"": "57.4",
		"\"PPR Pts/G\"": "14.4"
	},
	{
		"Player": "\"A.J. Brown\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "3",
		"W4": "-",
		"W5": "-",
		"W6": "23.6",
		"W7": "19.9",
		"W8": "13.4",
		"\"PPR Pts\"": "56.9",
		"\"PPR Pts/G\"": "19.0"
	},
	{
		"Player": "\"Michael Pittman Jr.\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "5",
		"W4": "17.3",
		"W5": "14.7",
		"W6": "12.5",
		"W7": "9.3",
		"W8": "2.6",
		"\"PPR Pts\"": "56.4",
		"\"PPR Pts/G\"": "11.3"
	},
	{
		"Player": "\"Rashod Bateman\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "5",
		"W4": "3.3",
		"W5": "15.8",
		"W6": "11.1",
		"W7": "22.1",
		"W8": "3.8",
		"\"PPR Pts\"": "56.1",
		"\"PPR Pts/G\"": "11.2"
	},
	{
		"Player": "\"Romeo Doubs\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "4",
		"W4": "7.9",
		"W5": "-",
		"W6": "19.9",
		"W7": "17.4",
		"W8": "10.2",
		"\"PPR Pts\"": "55.4",
		"\"PPR Pts/G\"": "13.9"
	},
	{
		"Player": "\"Jaxon Smith-Njigba\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "5",
		"W4": "13.1",
		"W5": "13.1",
		"W6": "10.3",
		"W7": "5.3",
		"W8": "12.9",
		"\"PPR Pts\"": "54.7",
		"\"PPR Pts/G\"": "10.9"
	},
	{
		"Player": "\"Courtland Sutton\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "5",
		"W4": "15.0",
		"W5": "5.2",
		"W6": "15.3",
		"W7": "0.0",
		"W8": "17.1",
		"\"PPR Pts\"": "52.6",
		"\"PPR Pts/G\"": "10.5"
	},
	{
		"Player": "\"DK Metcalf\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "4",
		"W4": "15.4",
		"W5": "7.5",
		"W6": "7.8",
		"W7": "19.9",
		"W8": "-",
		"\"PPR Pts\"": "50.6",
		"\"PPR Pts/G\"": "12.7"
	},
	{
		"Player": "\"Christian Kirk\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "5",
		"W4": "19.1",
		"W5": "12.8",
		"W6": "6.9",
		"W7": "3.4",
		"W8": "7.9",
		"\"PPR Pts\"": "50.1",
		"\"PPR Pts/G\"": "10.0"
	},
	{
		"Player": "\"D.J. Moore\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "4",
		"W4": "11.2",
		"W5": "27.5",
		"W6": "6.0",
		"W7": "-",
		"W8": "5.4",
		"\"PPR Pts\"": "50.1",
		"\"PPR Pts/G\"": "12.5"
	},
	{
		"Player": "\"Diontae Johnson\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "4",
		"W4": "21.3",
		"W5": "5.9",
		"W6": "19.8",
		"W7": "2.7",
		"W8": "-",
		"\"PPR Pts\"": "49.7",
		"\"PPR Pts/G\"": "12.4"
	},
	{
		"Player": "\"Tyler Lockett\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "5",
		"W4": "11.1",
		"W5": "11.5",
		"W6": "16.5",
		"W7": "8.5",
		"W8": "1.9",
		"\"PPR Pts\"": "49.5",
		"\"PPR Pts/G\"": "9.9"
	},
	{
		"Player": "\"Marvin Harrison Jr.\"",
		"Pos": "WR",
		"Team": "ARI",
		"G": "5",
		"W4": "15.5",
		"W5": "5.6",
		"W6": "0.0",
		"W7": "5.1",
		"W8": "23.1",
		"\"PPR Pts\"": "49.3",
		"\"PPR Pts/G\"": "9.9"
	},
	{
		"Player": "\"Xavier Legette\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "5",
		"W4": "19.6",
		"W5": "1.8",
		"W6": "11.3",
		"W7": "2.9",
		"W8": "13.4",
		"\"PPR Pts\"": "49.0",
		"\"PPR Pts/G\"": "9.8"
	},
	{
		"Player": "\"Nico Collins\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "2",
		"W4": "33.1",
		"W5": "15.8",
		"W6": "-",
		"W7": "-",
		"W8": "-",
		"\"PPR Pts\"": "48.9",
		"\"PPR Pts/G\"": "24.5"
	},
	{
		"Player": "\"Dontayvion Wicks\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "5",
		"W4": "24.8",
		"W5": "4.0",
		"W6": "1.9",
		"W7": "13.8",
		"W8": "3.1",
		"\"PPR Pts\"": "47.6",
		"\"PPR Pts/G\"": "9.5"
	},
	{
		"Player": "\"Khalil Shakir\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "4",
		"W4": "10.2",
		"W5": "-",
		"W6": "3.9",
		"W7": "13.5",
		"W8": "19.9",
		"\"PPR Pts\"": "47.5",
		"\"PPR Pts/G\"": "11.9"
	},
	{
		"Player": "\"Xavier Worthy\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "4",
		"W4": "16.3",
		"W5": "11.8",
		"W6": "-",
		"W7": "5.4",
		"W8": "13.7",
		"\"PPR Pts\"": "47.2",
		"\"PPR Pts/G\"": "11.8"
	},
	{
		"Player": "\"Deebo Samuel\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "5",
		"W4": "10.2",
		"W5": "3.0",
		"W6": "20.7",
		"W7": "0.0",
		"W8": "12.6",
		"\"PPR Pts\"": "46.5",
		"\"PPR Pts/G\"": "9.3"
	},
	{
		"Player": "\"Cedric Tillman\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "5",
		"W4": "0.0",
		"W5": "0.0",
		"W6": "-0.5",
		"W7": "18.1",
		"W8": "28.9",
		"\"PPR Pts\"": "46.5",
		"\"PPR Pts/G\"": "9.3"
	},
	{
		"Player": "\"Malik Nabers\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "3",
		"W4": "23.1",
		"W5": "-",
		"W6": "-",
		"W7": "8.1",
		"W8": "14.1",
		"\"PPR Pts\"": "45.3",
		"\"PPR Pts/G\"": "15.1"
	},
	{
		"Player": "\"Michael Wilson\"",
		"Pos": "WR",
		"Team": "ARI",
		"G": "5",
		"W4": "4.8",
		"W5": "12.8",
		"W6": "10.1",
		"W7": "2.5",
		"W8": "14.1",
		"\"PPR Pts\"": "44.3",
		"\"PPR Pts/G\"": "8.9"
	},
	{
		"Player": "\"Demario Douglas\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "5",
		"W4": "4.3",
		"W5": "11.9",
		"W6": "21.2",
		"W7": "3.4",
		"W8": "3.2",
		"\"PPR Pts\"": "44.0",
		"\"PPR Pts/G\"": "8.8"
	},
	{
		"Player": "\"Amari Cooper\"",
		"Pos": "WR",
		"Team": "\"BUF",
		"G": " CLE\"",
		"W4": "5",
		"W5": "7.5",
		"W6": "10.0",
		"W7": "8.2",
		"W8": "16.6",
		"\"PPR Pts\"": "1.3",
		"\"PPR Pts/G\"": "43.6"
	},
	{
		"Player": "\"Jordan Addison\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "4",
		"W4": "22.9",
		"W5": "6.6",
		"W6": "-",
		"W7": "9.6",
		"W8": "4.2",
		"\"PPR Pts\"": "43.3",
		"\"PPR Pts/G\"": "10.8"
	},
	{
		"Player": "\"Jalen Tolbert\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "4",
		"W4": "5.4",
		"W5": "21.7",
		"W6": "8.3",
		"W7": "-",
		"W8": "7.4",
		"\"PPR Pts\"": "42.8",
		"\"PPR Pts/G\"": "10.7"
	},
	{
		"Player": "\"Jakobi Meyers\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "3",
		"W4": "9.9",
		"W5": "13.2",
		"W6": "-",
		"W7": "-",
		"W8": "17.2",
		"\"PPR Pts\"": "40.3",
		"\"PPR Pts/G\"": "13.4"
	},
	{
		"Player": "\"Brandon Aiyuk\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "4",
		"W4": "6.8",
		"W5": "22.7",
		"W6": "5.7",
		"W7": "4.3",
		"W8": "-",
		"\"PPR Pts\"": "39.5",
		"\"PPR Pts/G\"": "9.9"
	},
	{
		"Player": "\"Tank Dell\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "4",
		"W4": "-",
		"W5": "7.3",
		"W6": "18.7",
		"W7": "0.0",
		"W8": "13.5",
		"\"PPR Pts\"": "39.5",
		"\"PPR Pts/G\"": "9.9"
	},
	{
		"Player": "\"Rashid Shaheed\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "3",
		"W4": "17.7",
		"W5": "18.6",
		"W6": "2.3",
		"W7": "-",
		"W8": "-",
		"\"PPR Pts\"": "38.6",
		"\"PPR Pts/G\"": "12.9"
	},
	{
		"Player": "\"Tutu Atwell\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "4",
		"W4": "12.2",
		"W5": "12.5",
		"W6": "-",
		"W7": "11.1",
		"W8": "2.8",
		"\"PPR Pts\"": "38.6",
		"\"PPR Pts/G\"": "9.7"
	},
	{
		"Player": "\"Keenan Allen\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "4",
		"W4": "4.9",
		"W5": "6.3",
		"W6": "21.1",
		"W7": "-",
		"W8": "5.9",
		"\"PPR Pts\"": "38.2",
		"\"PPR Pts/G\"": "9.6"
	},
	{
		"Player": "\"Chris Olave\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "4",
		"W4": "16.7",
		"W5": "3.0",
		"W6": "-0.5",
		"W7": "-",
		"W8": "18.7",
		"\"PPR Pts\"": "37.9",
		"\"PPR Pts/G\"": "9.5"
	},
	{
		"Player": "\"Demarcus Robinson\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "4",
		"W4": "5.7",
		"W5": "11.8",
		"W6": "-",
		"W7": "1.9",
		"W8": "17.5",
		"\"PPR Pts\"": "36.9",
		"\"PPR Pts/G\"": "9.2"
	},
	{
		"Player": "\"DeVonta Smith\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "3",
		"W4": "-",
		"W5": "-",
		"W6": "15.4",
		"W7": "0.8",
		"W8": "20.5",
		"\"PPR Pts\"": "36.7",
		"\"PPR Pts/G\"": "12.2"
	},
	{
		"Player": "\"Jalen Coker\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "5",
		"W4": "0.0",
		"W5": "10.8",
		"W6": "6.0",
		"W7": "2.0",
		"W8": "17.8",
		"\"PPR Pts\"": "36.6",
		"\"PPR Pts/G\"": "7.3"
	},
	{
		"Player": "\"Tyreek Hill\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "4",
		"W4": "8.2",
		"W5": "12.9",
		"W6": "-",
		"W7": "2.3",
		"W8": "13.2",
		"\"PPR Pts\"": "36.6",
		"\"PPR Pts/G\"": "9.2"
	},
	{
		"Player": "\"Ray-Ray McCloud\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "5",
		"W4": "11.2",
		"W5": "12.6",
		"W6": "4.3",
		"W7": "2.9",
		"W8": "5.6",
		"\"PPR Pts\"": "36.6",
		"\"PPR Pts/G\"": "7.3"
	},
	{
		"Player": "\"Jerry Jeudy\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "5",
		"W4": "13.2",
		"W5": "2.6",
		"W6": "4.5",
		"W7": "2.8",
		"W8": "12.9",
		"\"PPR Pts\"": "36.0",
		"\"PPR Pts/G\"": "7.2"
	},
	{
		"Player": "\"Kalif Raymond\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "4",
		"W4": "1.9",
		"W5": "-",
		"W6": "11.3",
		"W7": "12.9",
		"W8": "9.4",
		"\"PPR Pts\"": "35.5",
		"\"PPR Pts/G\"": "8.9"
	},
	{
		"Player": "\"Jameson Williams\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "3",
		"W4": "16.0",
		"W5": "-",
		"W6": "17.7",
		"W7": "0.6",
		"W8": "-",
		"\"PPR Pts\"": "34.3",
		"\"PPR Pts/G\"": "11.4"
	},
	{
		"Player": "\"Kayshon Boutte\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "5",
		"W4": "2.1",
		"W5": "5.4",
		"W6": "14.9",
		"W7": "4.3",
		"W8": "7.6",
		"\"PPR Pts\"": "34.3",
		"\"PPR Pts/G\"": "6.9"
	},
	{
		"Player": "\"Noah Brown\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "4",
		"W4": "5.6",
		"W5": "-",
		"W6": "9.8",
		"W7": "2.6",
		"W8": "16.3",
		"\"PPR Pts\"": "34.3",
		"\"PPR Pts/G\"": "8.6"
	},
	{
		"Player": "\"Elijah Moore\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "5",
		"W4": "2.1",
		"W5": "4.1",
		"W6": "1.3",
		"W7": "10.1",
		"W8": "16.5",
		"\"PPR Pts\"": "34.1",
		"\"PPR Pts/G\"": "6.8"
	},
	{
		"Player": "\"Calvin Ridley\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "4",
		"W4": "2.5",
		"W5": "-",
		"W6": "0.9",
		"W7": "7.2",
		"W8": "22.6",
		"\"PPR Pts\"": "33.2",
		"\"PPR Pts/G\"": "8.3"
	},
	{
		"Player": "\"Sterling Shepard\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "5",
		"W4": "8.1",
		"W5": "7.4",
		"W6": "8.4",
		"W7": "4.5",
		"W8": "4.8",
		"\"PPR Pts\"": "33.2",
		"\"PPR Pts/G\"": "6.6"
	},
	{
		"Player": "\"DJ Turner\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "5",
		"W4": "7.8",
		"W5": "2.7",
		"W6": "5.7",
		"W7": "3.7",
		"W8": "13.2",
		"\"PPR Pts\"": "33.1",
		"\"PPR Pts/G\"": "6.6"
	},
	{
		"Player": "\"Tre Tucker\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "5",
		"W4": "15.4",
		"W5": "4.6",
		"W6": "0.0",
		"W7": "7.7",
		"W8": "5.3",
		"\"PPR Pts\"": "33.0",
		"\"PPR Pts/G\"": "6.6"
	},
	{
		"Player": "\"Joshua Palmer\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "4",
		"W4": "6.6",
		"W5": "-",
		"W6": "5.8",
		"W7": "10.3",
		"W8": "9.2",
		"\"PPR Pts\"": "31.9",
		"\"PPR Pts/G\"": "8.0"
	},
	{
		"Player": "\"Alec Pierce\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "5",
		"W4": "1.9",
		"W5": "22.4",
		"W6": "0.0",
		"W7": "3.5",
		"W8": "2.1",
		"\"PPR Pts\"": "29.9",
		"\"PPR Pts/G\"": "6.0"
	},
	{
		"Player": "\"Olamide Zaccheaus\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "5",
		"W4": "14.5",
		"W5": "2.0",
		"W6": "6.7",
		"W7": "6.5",
		"W8": "0.0",
		"\"PPR Pts\"": "29.7",
		"\"PPR Pts/G\"": "5.9"
	},
	{
		"Player": "\"Gabe Davis\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "5",
		"W4": "0.8",
		"W5": "4.8",
		"W6": "21.5",
		"W7": "2.3",
		"W8": "0.0",
		"\"PPR Pts\"": "29.4",
		"\"PPR Pts/G\"": "5.9"
	},
	{
		"Player": "\"Van Jefferson\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "5",
		"W4": "4.1",
		"W5": "5.6",
		"W6": "0.0",
		"W7": "9.5",
		"W8": "10.2",
		"\"PPR Pts\"": "29.4",
		"\"PPR Pts/G\"": "5.9"
	},
	{
		"Player": "\"Calvin Austin III\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "5",
		"W4": "2.7",
		"W5": "1.6",
		"W6": "5.6",
		"W7": "4.6",
		"W8": "14.4",
		"\"PPR Pts\"": "28.9",
		"\"PPR Pts/G\"": "5.8"
	},
	{
		"Player": "\"Nick Westbrook-Ikhine\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "4",
		"W4": "0.0",
		"W5": "-",
		"W6": "7.9",
		"W7": "9.0",
		"W8": "11.9",
		"\"PPR Pts\"": "28.8",
		"\"PPR Pts/G\"": "7.2"
	},
	{
		"Player": "\"Troy Franklin\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "5",
		"W4": "1.8",
		"W5": "3.0",
		"W6": "11.6",
		"W7": "10.0",
		"W8": "1.9",
		"\"PPR Pts\"": "28.3",
		"\"PPR Pts/G\"": "5.7"
	},
	{
		"Player": "\"Jordan Whittington\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "3",
		"W4": "12.2",
		"W5": "15.9",
		"W6": "-",
		"W7": "0.0",
		"W8": "-",
		"\"PPR Pts\"": "28.1",
		"\"PPR Pts/G\"": "9.4"
	},
	{
		"Player": "\"Jaylen Waddle\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "4",
		"W4": "7.6",
		"W5": "8.6",
		"W6": "-",
		"W7": "2.1",
		"W8": "8.5",
		"\"PPR Pts\"": "26.8",
		"\"PPR Pts/G\"": "6.7"
	},
	{
		"Player": "\"Bub Means\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "5",
		"W4": "0.0",
		"W5": "0.0",
		"W6": "15.5",
		"W7": "6.7",
		"W8": "4.6",
		"\"PPR Pts\"": "26.8",
		"\"PPR Pts/G\"": "5.4"
	},
	{
		"Player": "\"Rome Odunze\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "4",
		"W4": "2.0",
		"W5": "9.0",
		"W6": "6.0",
		"W7": "-",
		"W8": "8.4",
		"\"PPR Pts\"": "25.4",
		"\"PPR Pts/G\"": "6.4"
	},
	{
		"Player": "\"Christian Watson\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "4",
		"W4": "0.0",
		"W5": "-",
		"W6": "15.8",
		"W7": "1.5",
		"W8": "7.9",
		"\"PPR Pts\"": "25.2",
		"\"PPR Pts/G\"": "6.3"
	},
	{
		"Player": "\"Tyler Boyd\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "4",
		"W4": "5.1",
		"W5": "-",
		"W6": "4.9",
		"W7": "9.3",
		"W8": "4.4",
		"\"PPR Pts\"": "23.7",
		"\"PPR Pts/G\"": "5.9"
	},
	{
		"Player": "\"Nelson Agholor\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "5",
		"W4": "3.0",
		"W5": "1.4",
		"W6": "3.5",
		"W7": "3.0",
		"W8": "12.6",
		"\"PPR Pts\"": "23.5",
		"\"PPR Pts/G\"": "4.7"
	},
	{
		"Player": "\"Greg Dortch\"",
		"Pos": "WR",
		"Team": "ARI",
		"G": "5",
		"W4": "7.8",
		"W5": "1.7",
		"W6": "4.6",
		"W7": "7.5",
		"W8": "1.9",
		"\"PPR Pts\"": "23.5",
		"\"PPR Pts/G\"": "4.7"
	},
	{
		"Player": "\"Cedrick Wilson\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "4",
		"W4": "0.0",
		"W5": "0.0",
		"W6": "4.8",
		"W7": "17.7",
		"W8": "-",
		"\"PPR Pts\"": "22.5",
		"\"PPR Pts/G\"": "5.6"
	},
	{
		"Player": "\"Dyami Brown\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "5",
		"W4": "1.4",
		"W5": "13.7",
		"W6": "2.1",
		"W7": "3.3",
		"W8": "1.6",
		"\"PPR Pts\"": "22.1",
		"\"PPR Pts/G\"": "4.4"
	},
	{
		"Player": "\"Mecole Hardman\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "4",
		"W4": "0.0",
		"W5": "7.3",
		"W6": "-",
		"W7": "12.5",
		"W8": "1.8",
		"\"PPR Pts\"": "21.6",
		"\"PPR Pts/G\"": "5.4"
	},
	{
		"Player": "\"Tim Patrick\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "4",
		"W4": "7.2",
		"W5": "-",
		"W6": "9.8",
		"W7": "4.5",
		"W8": "0.0",
		"\"PPR Pts\"": "21.5",
		"\"PPR Pts/G\"": "5.4"
	},
	{
		"Player": "\"Devaughn Vele\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "3",
		"W4": "-",
		"W5": "-",
		"W6": "11.8",
		"W7": "3.0",
		"W8": "5.8",
		"\"PPR Pts\"": "20.6",
		"\"PPR Pts/G\"": "6.9"
	},
	{
		"Player": "\"DeAndre Hopkins\"",
		"Pos": "WR",
		"Team": "\"KC",
		"G": " TEN\"",
		"W4": "4",
		"W5": "5.1",
		"W6": "-",
		"W7": "9.4",
		"W8": "0.8",
		"\"PPR Pts\"": "4.9",
		"\"PPR Pts/G\"": "20.2"
	},
	{
		"Player": "\"JuJu Smith-Schuster\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "3",
		"W4": "0.0",
		"W5": "20.0",
		"W6": "-",
		"W7": "0.0",
		"W8": "-",
		"\"PPR Pts\"": "20.0",
		"\"PPR Pts/G\"": "6.7"
	},
	{
		"Player": "\"Adonai Mitchell\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "5",
		"W4": "1.0",
		"W5": "9.2",
		"W6": "2.9",
		"W7": "5.0",
		"W8": "1.9",
		"\"PPR Pts\"": "20.0",
		"\"PPR Pts/G\"": "4.0"
	},
	{
		"Player": "\"Jauan Jennings\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "3",
		"W4": "11.8",
		"W5": "2.3",
		"W6": "5.7",
		"W7": "-",
		"W8": "-",
		"\"PPR Pts\"": "19.8",
		"\"PPR Pts/G\"": "6.6"
	},
	{
		"Player": "\"Jalen Nailor\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "4",
		"W4": "4.1",
		"W5": "0.0",
		"W6": "-",
		"W7": "11.6",
		"W8": "3.6",
		"\"PPR Pts\"": "19.3",
		"\"PPR Pts/G\"": "4.8"
	},
	{
		"Player": "\"Mason Tipton\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "5",
		"W4": "1.6",
		"W5": "1.2",
		"W6": "2.5",
		"W7": "10.5",
		"W8": "3.4",
		"\"PPR Pts\"": "19.2",
		"\"PPR Pts/G\"": "3.8"
	},
	{
		"Player": "\"Trey Palmer\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "3",
		"W4": "11.6",
		"W5": "-",
		"W6": "-",
		"W7": "2.6",
		"W8": "4.9",
		"\"PPR Pts\"": "19.1",
		"\"PPR Pts/G\"": "6.4"
	},
	{
		"Player": "\"Puka Nacua\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "1",
		"W4": "-",
		"W5": "-",
		"W6": "-",
		"W7": "-",
		"W8": "18.1",
		"\"PPR Pts\"": "18.1",
		"\"PPR Pts/G\"": "18.1"
	},
	{
		"Player": "\"Mike Williams\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "5",
		"W4": "10.7",
		"W5": "4.5",
		"W6": "0.0",
		"W7": "2.5",
		"W8": "0.0",
		"\"PPR Pts\"": "17.7",
		"\"PPR Pts/G\"": "3.5"
	},
	{
		"Player": "\"KaVontae Turpin\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "4",
		"W4": "0.0",
		"W5": "8.4",
		"W6": "5.0",
		"W7": "-",
		"W8": "3.7",
		"\"PPR Pts\"": "17.1",
		"\"PPR Pts/G\"": "4.3"
	},
	{
		"Player": "\"Ricky Pearsall\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "2",
		"W4": "-",
		"W5": "-",
		"W6": "-",
		"W7": "5.1",
		"W8": "11.7",
		"\"PPR Pts\"": "16.8",
		"\"PPR Pts/G\"": "8.4"
	},
	{
		"Player": "\"Cooper Kupp\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "1",
		"W4": "-",
		"W5": "-",
		"W6": "-",
		"W7": "-",
		"W8": "16.1",
		"\"PPR Pts\"": "16.1",
		"\"PPR Pts/G\"": "16.1"
	},
	{
		"Player": "\"Lil'Jordan Humphrey\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "5",
		"W4": "0.0",
		"W5": "6.8",
		"W6": "1.8",
		"W7": "3.2",
		"W8": "4.2",
		"\"PPR Pts\"": "16.0",
		"\"PPR Pts/G\"": "3.2"
	},
	{
		"Player": "\"Davante Adams\"",
		"Pos": "WR",
		"Team": "\"LV",
		"G": " NYJ\"",
		"W4": "2",
		"W5": "-",
		"W6": "-",
		"W7": "-",
		"W8": "6.0",
		"\"PPR Pts\"": "9.4",
		"\"PPR Pts/G\"": "15.4"
	},
	{
		"Player": "\"David Moore\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "5",
		"W4": "0.0",
		"W5": "3.3",
		"W6": "3.7",
		"W7": "0.0",
		"W8": "7.9",
		"\"PPR Pts\"": "14.9",
		"\"PPR Pts/G\"": "3.0"
	},
	{
		"Player": "\"Jalen McMillan\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "3",
		"W4": "-",
		"W5": "-",
		"W6": "0.0",
		"W7": "5.6",
		"W8": "9.2",
		"\"PPR Pts\"": "14.8",
		"\"PPR Pts/G\"": "4.9"
	},
	{
		"Player": "\"KhaDarel Hodge\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "5",
		"W4": "0.0",
		"W5": "14.7",
		"W6": "0.0",
		"W7": "0.0",
		"W8": "0.0",
		"\"PPR Pts\"": "14.7",
		"\"PPR Pts/G\"": "2.9"
	},
	{
		"Player": "\"Andrei Iosivas\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "5",
		"W4": "3.9",
		"W5": "4.9",
		"W6": "5.6",
		"W7": "0.0",
		"W8": "0.0",
		"\"PPR Pts\"": "14.4",
		"\"PPR Pts/G\"": "2.9"
	},
	{
		"Player": "\"Mack Hollins\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "5",
		"W4": "1.5",
		"W5": "4.7",
		"W6": "7.8",
		"W7": "0.0",
		"W8": "0.0",
		"\"PPR Pts\"": "14.0",
		"\"PPR Pts/G\"": "2.8"
	},
	{
		"Player": "\"Simi Fehoko\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "4",
		"W4": "0.0",
		"W5": "-",
		"W6": "6.4",
		"W7": "7.5",
		"W8": "0.0",
		"\"PPR Pts\"": "13.9",
		"\"PPR Pts/G\"": "3.5"
	},
	{
		"Player": "\"Jake Bobo\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "5",
		"W4": "6.0",
		"W5": "1.3",
		"W6": "3.8",
		"W7": "0.0",
		"W8": "2.5",
		"\"PPR Pts\"": "13.6",
		"\"PPR Pts/G\"": "2.7"
	},
	{
		"Player": "\"Justin Watson\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "4",
		"W4": "4.7",
		"W5": "0.0",
		"W6": "-",
		"W7": "1.8",
		"W8": "6.3",
		"\"PPR Pts\"": "12.8",
		"\"PPR Pts/G\"": "3.2"
	},
	{
		"Player": "\"Jonathan Mingo\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "5",
		"W4": "5.4",
		"W5": "5.7",
		"W6": "1.1",
		"W7": "0.0",
		"W8": "0.0",
		"\"PPR Pts\"": "12.2",
		"\"PPR Pts/G\"": "2.4"
	},
	{
		"Player": "\"Bo Melton\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "5",
		"W4": "3.8",
		"W5": "2.2",
		"W6": "4.3",
		"W7": "1.7",
		"W8": "0.0",
		"\"PPR Pts\"": "12.0",
		"\"PPR Pts/G\"": "2.4"
	},
	{
		"Player": "\"K.J. Osborn\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "3",
		"W4": "1.3",
		"W5": "-",
		"W6": "-",
		"W7": "10.6",
		"W8": "0.0",
		"\"PPR Pts\"": "11.9",
		"\"PPR Pts/G\"": "4.0"
	},
	{
		"Player": "\"Curtis Samuel\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "4",
		"W4": "3.5",
		"W5": "0.9",
		"W6": "7.4",
		"W7": "0.0",
		"W8": "-",
		"\"PPR Pts\"": "11.8",
		"\"PPR Pts/G\"": "3.0"
	},
	{
		"Player": "\"Parris Campbell\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "2",
		"W4": "11.7",
		"W5": "-",
		"W6": "-",
		"W7": "0.0",
		"W8": "-",
		"\"PPR Pts\"": "11.7",
		"\"PPR Pts/G\"": "5.9"
	},
	{
		"Player": "\"Tyler Johnson\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "4",
		"W4": "0.0",
		"W5": "0.0",
		"W6": "-",
		"W7": "9.7",
		"W8": "1.6",
		"\"PPR Pts\"": "11.3",
		"\"PPR Pts/G\"": "2.8"
	},
	{
		"Player": "\"Luke McCaffrey\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "5",
		"W4": "2.7",
		"W5": "4.9",
		"W6": "1.5",
		"W7": "0.0",
		"W8": "1.8",
		"\"PPR Pts\"": "10.9",
		"\"PPR Pts/G\"": "2.2"
	},
	{
		"Player": "\"Xavier Hutchinson\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "5",
		"W4": "0.0",
		"W5": "5.1",
		"W6": "0.0",
		"W7": "2.1",
		"W8": "2.9",
		"\"PPR Pts\"": "10.1",
		"\"PPR Pts/G\"": "2.0"
	},
	{
		"Player": "\"Ryan Miller\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "2",
		"W4": "-",
		"W5": "-",
		"W6": "4.9",
		"W7": "-",
		"W8": "4.9",
		"\"PPR Pts\"": "9.8",
		"\"PPR Pts/G\"": "4.9"
	},
	{
		"Player": "\"Trent Sherfield\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "4",
		"W4": "1.8",
		"W5": "0.0",
		"W6": "-",
		"W7": "0.0",
		"W8": "8.0",
		"\"PPR Pts\"": "9.8",
		"\"PPR Pts/G\"": "2.5"
	},
	{
		"Player": "\"Kristian Wilkerson\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "2",
		"W4": "-",
		"W5": "-",
		"W6": "9.8",
		"W7": "0.0",
		"W8": "-",
		"\"PPR Pts\"": "9.8",
		"\"PPR Pts/G\"": "4.9"
	},
	{
		"Player": "\"Ja'Lynn Polk\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "4",
		"W4": "6.0",
		"W5": "2.3",
		"W6": "1.4",
		"W7": "0.0",
		"W8": "-",
		"\"PPR Pts\"": "9.7",
		"\"PPR Pts/G\"": "2.4"
	},
	{
		"Player": "\"Marvin Mims\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "5",
		"W4": "0.0",
		"W5": "3.4",
		"W6": "0.0",
		"W7": "3.8",
		"W8": "1.8",
		"\"PPR Pts\"": "9.0",
		"\"PPR Pts/G\"": "1.8"
	},
	{
		"Player": "\"Rakim Jarrett\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "1",
		"W4": "-",
		"W5": "-",
		"W6": "-",
		"W7": "-",
		"W8": "8.8",
		"\"PPR Pts\"": "8.8",
		"\"PPR Pts/G\"": "8.8"
	},
	{
		"Player": "\"Xavier Gipson\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "5",
		"W4": "1.6",
		"W5": "0.0",
		"W6": "0.0",
		"W7": "0.0",
		"W8": "7.1",
		"\"PPR Pts\"": "8.7",
		"\"PPR Pts/G\"": "1.7"
	},
	{
		"Player": "\"Josh Reynolds\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "2",
		"W4": "0.0",
		"W5": "7.9",
		"W6": "-",
		"W7": "-",
		"W8": "-",
		"\"PPR Pts\"": "7.9",
		"\"PPR Pts/G\"": "4.0"
	},
	{
		"Player": "\"John Metchie\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "5",
		"W4": "1.7",
		"W5": "0.0",
		"W6": "0.0",
		"W7": "0.0",
		"W8": "5.9",
		"\"PPR Pts\"": "7.6",
		"\"PPR Pts/G\"": "1.5"
	},
	{
		"Player": "\"Parker Washington\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "5",
		"W4": "0.0",
		"W5": "0.0",
		"W6": "0.0",
		"W7": "0.0",
		"W8": "7.6",
		"\"PPR Pts\"": "7.6",
		"\"PPR Pts/G\"": "1.5"
	},
	{
		"Player": "\"Quentin Johnston\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "2",
		"W4": "2.3",
		"W5": "-",
		"W6": "5.2",
		"W7": "-",
		"W8": "-",
		"\"PPR Pts\"": "7.5",
		"\"PPR Pts/G\"": "3.8"
	},
	{
		"Player": "\"Jacob Cowing\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "4",
		"W4": "0.0",
		"W5": "-",
		"W6": "0.0",
		"W7": "7.0",
		"W8": "0.0",
		"\"PPR Pts\"": "7.0",
		"\"PPR Pts/G\"": "1.8"
	},
	{
		"Player": "\"Kendrick Bourne\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "4",
		"W4": "-",
		"W5": "1.6",
		"W6": "2.9",
		"W7": "2.4",
		"W8": "0.0",
		"\"PPR Pts\"": "6.9",
		"\"PPR Pts/G\"": "1.7"
	},
	{
		"Player": "\"Malik Heath\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "5",
		"W4": "3.2",
		"W5": "3.4",
		"W6": "0.0",
		"W7": "0.0",
		"W8": "0.0",
		"\"PPR Pts\"": "6.6",
		"\"PPR Pts/G\"": "1.3"
	},
	{
		"Player": "\"Jahan Dotson\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "4",
		"W4": "3.1",
		"W5": "-",
		"W6": "3.3",
		"W7": "0.0",
		"W8": "0.0",
		"\"PPR Pts\"": "6.4",
		"\"PPR Pts/G\"": "1.6"
	},
	{
		"Player": "\"Alex Bachman\"",
		"Pos": "WR",
		"Team": "\"HOU",
		"G": " LV\"",
		"W4": "5",
		"W5": "0.0",
		"W6": "0.0",
		"W7": "6.1",
		"W8": "0.0",
		"\"PPR Pts\"": "0.0",
		"\"PPR Pts/G\"": "6.1"
	},
	{
		"Player": "\"Robert Woods\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "3",
		"W4": "2.0",
		"W5": "0.0",
		"W6": "-",
		"W7": "-",
		"W8": "3.8",
		"\"PPR Pts\"": "5.8",
		"\"PPR Pts/G\"": "1.9"
	},
	{
		"Player": "\"Xavier Smith\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "4",
		"W4": "0.0",
		"W5": "2.6",
		"W6": "-",
		"W7": "3.0",
		"W8": "0.0",
		"\"PPR Pts\"": "5.6",
		"\"PPR Pts/G\"": "1.4"
	},
	{
		"Player": "\"Jalen Reagor\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "1",
		"W4": "-",
		"W5": "-",
		"W6": "-",
		"W7": "-",
		"W8": "5.5",
		"\"PPR Pts\"": "5.5",
		"\"PPR Pts/G\"": "5.5"
	},
	{
		"Player": "\"Jermaine Burton\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "4",
		"W4": "0.0",
		"W5": "0.0",
		"W6": "-",
		"W7": "0.0",
		"W8": "5.1",
		"\"PPR Pts\"": "5.1",
		"\"PPR Pts/G\"": "1.3"
	},
	{
		"Player": "\"Tylan Wallace\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "5",
		"W4": "0.0",
		"W5": "5.1",
		"W6": "0.0",
		"W7": "0.0",
		"W8": "0.0",
		"\"PPR Pts\"": "5.1",
		"\"PPR Pts/G\"": "1.0"
	},
	{
		"Player": "\"Malik Washington\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "4",
		"W4": "1.8",
		"W5": "0.0",
		"W6": "-",
		"W7": "2.9",
		"W8": "0.0",
		"\"PPR Pts\"": "4.7",
		"\"PPR Pts/G\"": "1.2"
	},
	{
		"Player": "\"Jalen Brooks\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "4",
		"W4": "0.0",
		"W5": "2.0",
		"W6": "2.5",
		"W7": "-",
		"W8": "0.0",
		"\"PPR Pts\"": "4.5",
		"\"PPR Pts/G\"": "1.1"
	},
	{
		"Player": "\"Treylon Burks\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "2",
		"W4": "2.3",
		"W5": "-",
		"W6": "2.0",
		"W7": "-",
		"W8": "-",
		"\"PPR Pts\"": "4.3",
		"\"PPR Pts/G\"": "2.2"
	},
	{
		"Player": "\"Tyquan Thornton\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "3",
		"W4": "0.0",
		"W5": "0.0",
		"W6": "-",
		"W7": "-",
		"W8": "4.0",
		"\"PPR Pts\"": "4.0",
		"\"PPR Pts/G\"": "1.3"
	},
	{
		"Player": "\"Derius Davis\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "1",
		"W4": "0.0",
		"W5": "-",
		"W6": "3.2",
		"W7": "-",
		"W8": "-",
		"\"PPR Pts\"": "3.2",
		"\"PPR Pts/G\"": "3.2"
	},
	{
		"Player": "\"Tim Jones\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "5",
		"W4": "0.0",
		"W5": "0.0",
		"W6": "0.0",
		"W7": "0.0",
		"W8": "3.0",
		"\"PPR Pts\"": "3.0",
		"\"PPR Pts/G\"": "0.6"
	},
	{
		"Player": "\"Laviska Shenault\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "4",
		"W4": "2.8",
		"W5": "0.0",
		"W6": "-2.0",
		"W7": "0.0",
		"W8": "2.0",
		"\"PPR Pts\"": "2.8",
		"\"PPR Pts/G\"": "0.7"
	},
	{
		"Player": "\"Brandin Cooks\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "1",
		"W4": "2.6",
		"W5": "-",
		"W6": "-",
		"W7": "-",
		"W8": "-",
		"\"PPR Pts\"": "2.6",
		"\"PPR Pts/G\"": "2.6"
	},
	{
		"Player": "\"Isaiah Williams\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "1",
		"W4": "-",
		"W5": "-",
		"W6": "-",
		"W7": "-",
		"W8": "2.6",
		"\"PPR Pts\"": "2.6",
		"\"PPR Pts/G\"": "2.6"
	},
	{
		"Player": "\"Casey Washington\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "1",
		"W4": "-",
		"W5": "0.0",
		"W6": "-",
		"W7": "2.4",
		"W8": "0.0",
		"\"PPR Pts\"": "2.4",
		"\"PPR Pts/G\"": "2.4"
	},
	{
		"Player": "\"Ashton Dulin\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "5",
		"W4": "0.0",
		"W5": "0.9",
		"W6": "0.0",
		"W7": "1.2",
		"W8": "0.0",
		"\"PPR Pts\"": "2.1",
		"\"PPR Pts/G\"": "0.4"
	},
	{
		"Player": "\"Ronnie Bell\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "3",
		"W4": "-",
		"W5": "0.0",
		"W6": "0.0",
		"W7": "2.0",
		"W8": "0.0",
		"\"PPR Pts\"": "2.0",
		"\"PPR Pts/G\"": "0.7"
	},
	{
		"Player": "\"Brandon Johnson\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "3",
		"W4": "-",
		"W5": "1.9",
		"W6": "-",
		"W7": "0.0",
		"W8": "0.0",
		"\"PPR Pts\"": "1.9",
		"\"PPR Pts/G\"": "0.6"
	},
	{
		"Player": "\"DeAndre Carter\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "2",
		"W4": "0.0",
		"W5": "0.0",
		"W6": "0.0",
		"W7": "-",
		"W8": "1.7",
		"\"PPR Pts\"": "1.7",
		"\"PPR Pts/G\"": "0.9"
	},
	{
		"Player": "\"Jaelon Darden\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "3",
		"W4": "-",
		"W5": "-",
		"W6": "1.6",
		"W7": "0.0",
		"W8": "0.0",
		"\"PPR Pts\"": "1.6",
		"\"PPR Pts/G\"": "0.5"
	},
	{
		"Player": "\"D'Wayne Eskridge\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "2",
		"W4": "0.0",
		"W5": "-",
		"W6": "-",
		"W7": "-",
		"W8": "1.6",
		"\"PPR Pts\"": "1.6",
		"\"PPR Pts/G\"": "0.8"
	},
	{
		"Player": "\"Jalin Hyatt\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "4",
		"W4": "0.0",
		"W5": "0.0",
		"W6": "1.6",
		"W7": "0.0",
		"W8": "-",
		"\"PPR Pts\"": "1.6",
		"\"PPR Pts/G\"": "0.4"
	},
	{
		"Player": "\"John Ross\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "1",
		"W4": "1.6",
		"W5": "-",
		"W6": "-",
		"W7": "-",
		"W8": "-",
		"\"PPR Pts\"": "1.6",
		"\"PPR Pts/G\"": "1.6"
	},
	{
		"Player": "\"Isaiah Hodgins\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "2",
		"W4": "-",
		"W5": "0.0",
		"W6": "1.5",
		"W7": "-",
		"W8": "-",
		"\"PPR Pts\"": "1.5",
		"\"PPR Pts/G\"": "0.8"
	},
	{
		"Player": "\"Trenton Irwin\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "2",
		"W4": "-",
		"W5": "-",
		"W6": "0.0",
		"W7": "-",
		"W8": "1.4",
		"\"PPR Pts\"": "1.4",
		"\"PPR Pts/G\"": "0.7"
	},
	{
		"Player": "\"Zay Jones\"",
		"Pos": "WR",
		"Team": "ARI",
		"G": "2",
		"W4": "-",
		"W5": "-",
		"W6": "-",
		"W7": "0.0",
		"W8": "1.3",
		"\"PPR Pts\"": "1.3",
		"\"PPR Pts/G\"": "0.7"
	},
	{
		"Player": "\"James Proche\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "2",
		"W4": "1.3",
		"W5": "0.0",
		"W6": "-",
		"W7": "-",
		"W8": "-",
		"\"PPR Pts\"": "1.3",
		"\"PPR Pts/G\"": "0.7"
	},
	{
		"Player": "\"Tyreik McAllister\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "1",
		"W4": "1.1",
		"W5": "-",
		"W6": "-",
		"W7": "0.0",
		"W8": "-",
		"\"PPR Pts\"": "1.1",
		"\"PPR Pts/G\"": "1.1"
	},
	{
		"Player": "\"Devin Duvernay\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "2",
		"W4": "0.0",
		"W5": "0.3",
		"W6": "-",
		"W7": "-",
		"W8": "-",
		"\"PPR Pts\"": "0.3",
		"\"PPR Pts/G\"": "0.2"
	},
	{
		"Player": "\"Ryan Flournoy\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "3",
		"W4": "-",
		"W5": "0.0",
		"W6": "0.2",
		"W7": "-",
		"W8": "0.0",
		"\"PPR Pts\"": "0.2",
		"\"PPR Pts/G\"": "0.1"
	},
	
]

module.exports = teamOffStatsByRankLastFiveWeeks4for4NFLTeamStatExplorer;