const wr4for4PlayerTargetsAppLastFiveWeeks = [
	{
		"Player": "\"CeeDee Lamb\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "5",
		"W9": "12",
		"W10": "10",
		"W11": "12",
		"W12": "12",
		"W13": "6",
		"TGTs": "52",
		"TGTs/G": "10.4",
		"Array": "17.7%"
	},
	{
		"Player": "\"Ja'Marr Chase\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "4",
		"W9": "11",
		"W10": "17",
		"W11": "13",
		"W12": "-",
		"W13": "9",
		"TGTs": "50",
		"TGTs/G": "12.5",
		"Array": "17.7%"
	},
	{
		"Player": "\"Cooper Kupp\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "5",
		"W9": "14",
		"W10": "7",
		"W11": "10",
		"W12": "11",
		"W13": "6",
		"TGTs": "48",
		"TGTs/G": "9.6",
		"Array": "17.0%"
	},
	{
		"Player": "\"Puka Nacua\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "5",
		"W9": "4",
		"W10": "14",
		"W11": "9",
		"W12": "13",
		"W13": "8",
		"TGTs": "48",
		"TGTs/G": "9.6",
		"Array": "22.2%"
	},
	{
		"Player": "\"Keenan Allen\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "5",
		"W9": "10",
		"W10": "6",
		"W11": "8",
		"W12": "15",
		"W13": "8",
		"TGTs": "47",
		"TGTs/G": "9.4",
		"Array": "14.6%"
	},
	{
		"Player": "\"Courtland Sutton\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "5",
		"W9": "10",
		"W10": "9",
		"W11": "8",
		"W12": "10",
		"W13": "9",
		"TGTs": "46",
		"TGTs/G": "9.2",
		"Array": "16.0%"
	},
	{
		"Player": "\"D.J. Moore\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "5",
		"W9": "9",
		"W10": "6",
		"W11": "7",
		"W12": "7",
		"W13": "16",
		"TGTs": "45",
		"TGTs/G": "9.0",
		"Array": "13.3%"
	},
	{
		"Player": "\"Davante Adams\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "4",
		"W9": "11",
		"W10": "13",
		"W11": "7",
		"W12": "-",
		"W13": "12",
		"TGTs": "43",
		"TGTs/G": "10.8",
		"Array": "20.0%"
	},
	{
		"Player": "\"Jakobi Meyers\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "4",
		"W9": "11",
		"W10": "-",
		"W11": "6",
		"W12": "15",
		"W13": "11",
		"TGTs": "43",
		"TGTs/G": "10.8",
		"Array": "16.9%"
	},
	{
		"Player": "\"Malik Nabers\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "4",
		"W9": "11",
		"W10": "10",
		"W11": "-",
		"W12": "9",
		"W13": "13",
		"TGTs": "43",
		"TGTs/G": "10.8",
		"Array": "17.7%"
	},
	{
		"Player": "\"Jerry Jeudy\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "4",
		"W9": "11",
		"W10": "-",
		"W11": "11",
		"W12": "6",
		"W13": "13",
		"TGTs": "41",
		"TGTs/G": "10.3",
		"Array": "15.4%"
	},
	{
		"Player": "\"Justin Jefferson\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "5",
		"W9": "9",
		"W10": "9",
		"W11": "8",
		"W12": "5",
		"W13": "9",
		"TGTs": "40",
		"TGTs/G": "8.0",
		"Array": "11.7%"
	},
	{
		"Player": "\"Amon-Ra St. Brown\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "5",
		"W9": "7",
		"W10": "8",
		"W11": "11",
		"W12": "7",
		"W13": "7",
		"TGTs": "40",
		"TGTs/G": "8.0",
		"Array": "12.7%"
	},
	{
		"Player": "\"Rome Odunze\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "5",
		"W9": "7",
		"W10": "6",
		"W11": "10",
		"W12": "10",
		"W13": "6",
		"TGTs": "39",
		"TGTs/G": "7.8",
		"Array": "13.8%"
	},
	{
		"Player": "\"Drake London\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "4",
		"W9": "2",
		"W10": "13",
		"W11": "7",
		"W12": "-",
		"W13": "16",
		"TGTs": "38",
		"TGTs/G": "9.5",
		"Array": "17.8%"
	},
	{
		"Player": "\"Ladd McConkey\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "5",
		"W9": "7",
		"W10": "2",
		"W11": "9",
		"W12": "6",
		"W13": "12",
		"TGTs": "36",
		"TGTs/G": "7.2",
		"Array": "15.6%"
	},
	{
		"Player": "\"Elijah Moore\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "4",
		"W9": "9",
		"W10": "-",
		"W11": "8",
		"W12": "5",
		"W13": "14",
		"TGTs": "36",
		"TGTs/G": "9.0",
		"Array": "16.6%"
	},
	{
		"Player": "\"Calvin Ridley\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "5",
		"W9": "8",
		"W10": "9",
		"W11": "6",
		"W12": "6",
		"W13": "7",
		"TGTs": "36",
		"TGTs/G": "7.2",
		"Array": "12.8%"
	},
	{
		"Player": "\"Khalil Shakir\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "4",
		"W9": "7",
		"W10": "9",
		"W11": "12",
		"W12": "-",
		"W13": "7",
		"TGTs": "35",
		"TGTs/G": "8.8",
		"Array": "20.7%"
	},
	{
		"Player": "\"Jaxon Smith-Njigba\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "4",
		"W9": "13",
		"W10": "-",
		"W11": "11",
		"W12": "7",
		"W13": "4",
		"TGTs": "35",
		"TGTs/G": "8.8",
		"Array": "16.5%"
	},
	{
		"Player": "\"Tank Dell\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "5",
		"W9": "9",
		"W10": "9",
		"W11": "7",
		"W12": "5",
		"W13": "4",
		"TGTs": "34",
		"TGTs/G": "6.8",
		"Array": "14.2%"
	},
	{
		"Player": "\"Jauan Jennings\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "4",
		"W9": "-",
		"W10": "11",
		"W11": "11",
		"W12": "7",
		"W13": "5",
		"TGTs": "34",
		"TGTs/G": "8.5",
		"Array": "16.3%"
	},
	{
		"Player": "\"Garrett Wilson\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "4",
		"W9": "10",
		"W10": "6",
		"W11": "8",
		"W12": "-",
		"W13": "10",
		"TGTs": "34",
		"TGTs/G": "8.5",
		"Array": "14.8%"
	},
	{
		"Player": "\"Jordan Addison\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "5",
		"W9": "5",
		"W10": "5",
		"W11": "8",
		"W12": "9",
		"W13": "6",
		"TGTs": "33",
		"TGTs/G": "6.6",
		"Array": "11.4%"
	},
	{
		"Player": "\"Zay Flowers\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "5",
		"W9": "6",
		"W10": "6",
		"W11": "6",
		"W12": "8",
		"W13": "7",
		"TGTs": "33",
		"TGTs/G": "6.6",
		"Array": "13.1%"
	},
	{
		"Player": "\"DeAndre Hopkins\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "5",
		"W9": "9",
		"W10": "5",
		"W11": "4",
		"W12": "6",
		"W13": "9",
		"TGTs": "33",
		"TGTs/G": "6.6",
		"Array": "16.8%"
	},
	{
		"Player": "\"A.J. Brown\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "5",
		"W9": "4",
		"W10": "7",
		"W11": "8",
		"W12": "7",
		"W13": "6",
		"TGTs": "32",
		"TGTs/G": "6.4",
		"Array": "11.6%"
	},
	{
		"Player": "\"Tyreek Hill\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "5",
		"W9": "5",
		"W10": "4",
		"W11": "8",
		"W12": "6",
		"W13": "9",
		"TGTs": "32",
		"TGTs/G": "6.4",
		"Array": "12.1%"
	},
	{
		"Player": "\"George Pickens\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "4",
		"W9": "-",
		"W10": "7",
		"W11": "12",
		"W12": "7",
		"W13": "6",
		"TGTs": "32",
		"TGTs/G": "8.0",
		"Array": "12.5%"
	},
	{
		"Player": "\"Noah Brown\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "5",
		"W9": "6",
		"W10": "7",
		"W11": "4",
		"W12": "10",
		"W13": "4",
		"TGTs": "31",
		"TGTs/G": "6.2",
		"Array": "13.6%"
	},
	{
		"Player": "\"Demario Douglas\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "5",
		"W9": "9",
		"W10": "5",
		"W11": "6",
		"W12": "7",
		"W13": "4",
		"TGTs": "31",
		"TGTs/G": "6.2",
		"Array": "14.7%"
	},
	{
		"Player": "\"Josh Downs\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "4",
		"W9": "9",
		"W10": "10",
		"W11": "5",
		"W12": "7",
		"W13": "-",
		"TGTs": "31",
		"TGTs/G": "7.8",
		"Array": "20.9%"
	},
	{
		"Player": "\"Kayshon Boutte\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "5",
		"W9": "6",
		"W10": "6",
		"W11": "6",
		"W12": "4",
		"W13": "6",
		"TGTs": "28",
		"TGTs/G": "5.6",
		"Array": "8.4%"
	},
	{
		"Player": "\"Marvin Harrison Jr.\"",
		"Pos": "WR",
		"Team": "ARI",
		"G": "4",
		"W9": "5",
		"W10": "5",
		"W11": "-",
		"W12": "6",
		"W13": "12",
		"TGTs": "28",
		"TGTs/G": "7.0",
		"Array": "13.1%"
	},
	{
		"Player": "\"Darnell Mooney\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "4",
		"W9": "9",
		"W10": "9",
		"W11": "4",
		"W12": "-",
		"W13": "6",
		"TGTs": "28",
		"TGTs/G": "7.0",
		"Array": "11.5%"
	},
	{
		"Player": "\"Nick Westbrook-Ikhine\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "5",
		"W9": "6",
		"W10": "3",
		"W11": "6",
		"W12": "5",
		"W13": "8",
		"TGTs": "28",
		"TGTs/G": "5.6",
		"Array": "9.5%"
	},
	{
		"Player": "\"Nico Collins\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "3",
		"W9": "-",
		"W10": "-",
		"W11": "7",
		"W12": "9",
		"W13": "11",
		"TGTs": "27",
		"TGTs/G": "9.0",
		"Array": "22.9%"
	},
	{
		"Player": "\"David Moore\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "4",
		"W9": "4",
		"W10": "4",
		"W11": "-",
		"W12": "10",
		"W13": "9",
		"TGTs": "27",
		"TGTs/G": "6.8",
		"Array": "12.4%"
	},
	{
		"Player": "\"Michael Pittman Jr.\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "4",
		"W9": "4",
		"W10": "-",
		"W11": "8",
		"W12": "7",
		"W13": "7",
		"TGTs": "26",
		"TGTs/G": "6.5",
		"Array": "13.0%"
	},
	{
		"Player": "\"Terry McLaurin\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "5",
		"W9": "3",
		"W10": "6",
		"W11": "2",
		"W12": "6",
		"W13": "8",
		"TGTs": "25",
		"TGTs/G": "5.0",
		"Array": "9.2%"
	},
	{
		"Player": "\"Devaughn Vele\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "5",
		"W9": "3",
		"W10": "4",
		"W11": "5",
		"W12": "9",
		"W13": "4",
		"TGTs": "25",
		"TGTs/G": "5.0",
		"Array": "13.6%"
	},
	{
		"Player": "\"Jameson Williams\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "4",
		"W9": "-",
		"W10": "5",
		"W11": "6",
		"W12": "7",
		"W13": "7",
		"TGTs": "25",
		"TGTs/G": "6.3",
		"Array": "11.7%"
	},
	{
		"Player": "\"Quentin Johnston\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "5",
		"W9": "5",
		"W10": "2",
		"W11": "8",
		"W12": "5",
		"W13": "4",
		"TGTs": "24",
		"TGTs/G": "4.8",
		"Array": "11.0%"
	},
	{
		"Player": "\"Xavier Legette\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "4",
		"W9": "6",
		"W10": "4",
		"W11": "-",
		"W12": "6",
		"W13": "8",
		"TGTs": "24",
		"TGTs/G": "6.0",
		"Array": "10.5%"
	},
	{
		"Player": "\"Alec Pierce\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "5",
		"W9": "3",
		"W10": "7",
		"W11": "4",
		"W12": "4",
		"W13": "6",
		"TGTs": "24",
		"TGTs/G": "4.8",
		"Array": "9.9%"
	},
	{
		"Player": "\"Demarcus Robinson\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "5",
		"W9": "9",
		"W10": "5",
		"W11": "4",
		"W12": "3",
		"W13": "3",
		"TGTs": "24",
		"TGTs/G": "4.8",
		"Array": "10.2%"
	},
	{
		"Player": "\"Brian Thomas Jr.\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "4",
		"W9": "4",
		"W10": "3",
		"W11": "7",
		"W12": "-",
		"W13": "10",
		"TGTs": "24",
		"TGTs/G": "6.0",
		"Array": "12.4%"
	},
	{
		"Player": "\"Jalen Tolbert\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "5",
		"W9": "6",
		"W10": "5",
		"W11": "5",
		"W12": "4",
		"W13": "4",
		"TGTs": "24",
		"TGTs/G": "4.8",
		"Array": "7.6%"
	},
	{
		"Player": "\"Jaylen Waddle\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "5",
		"W9": "2",
		"W10": "6",
		"W11": "3",
		"W12": "9",
		"W13": "4",
		"TGTs": "24",
		"TGTs/G": "4.8",
		"Array": "8.9%"
	},
	{
		"Player": "\"Xavier Worthy\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "5",
		"W9": "2",
		"W10": "4",
		"W11": "5",
		"W12": "6",
		"W13": "7",
		"TGTs": "24",
		"TGTs/G": "4.8",
		"Array": "10.4%"
	},
	{
		"Player": "\"Tee Higgins\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "2",
		"W9": "-",
		"W10": "-",
		"W11": "13",
		"W12": "-",
		"W13": "10",
		"TGTs": "23",
		"TGTs/G": "11.5",
		"Array": "18.4%"
	},
	{
		"Player": "\"DK Metcalf\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "3",
		"W9": "-",
		"W10": "-",
		"W11": "9",
		"W12": "5",
		"W13": "9",
		"TGTs": "23",
		"TGTs/G": "7.7",
		"Array": "15.1%"
	},
	{
		"Player": "\"Cedric Tillman\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "3",
		"W9": "11",
		"W10": "-",
		"W11": "8",
		"W12": "4",
		"W13": "-",
		"TGTs": "23",
		"TGTs/G": "7.7",
		"Array": "13.0%"
	},
	{
		"Player": "\"Deebo Samuel\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "4",
		"W9": "-",
		"W10": "6",
		"W11": "7",
		"W12": "4",
		"W13": "5",
		"TGTs": "22",
		"TGTs/G": "5.5",
		"Array": "12.6%"
	},
	{
		"Player": "\"Sterling Shepard\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "4",
		"W9": "5",
		"W10": "3",
		"W11": "-",
		"W12": "7",
		"W13": "7",
		"TGTs": "22",
		"TGTs/G": "5.5",
		"Array": "15.0%"
	},
	{
		"Player": "\"Parker Washington\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "4",
		"W9": "6",
		"W10": "0",
		"W11": "3",
		"W12": "-",
		"W13": "12",
		"TGTs": "21",
		"TGTs/G": "5.3",
		"Array": "13.7%"
	},
	{
		"Player": "\"Rashod Bateman\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "5",
		"W9": "4",
		"W10": "8",
		"W11": "5",
		"W12": "3",
		"W13": "0",
		"TGTs": "20",
		"TGTs/G": "4.0",
		"Array": "10.1%"
	},
	{
		"Player": "\"Kendrick Bourne\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "4",
		"W9": "6",
		"W10": "-",
		"W11": "5",
		"W12": "5",
		"W13": "3",
		"TGTs": "19",
		"TGTs/G": "4.8",
		"Array": "10.7%"
	},
	{
		"Player": "\"Ray-Ray McCloud\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "4",
		"W9": "3",
		"W10": "4",
		"W11": "6",
		"W12": "-",
		"W13": "6",
		"TGTs": "19",
		"TGTs/G": "4.8",
		"Array": "7.2%"
	},
	{
		"Player": "\"Joshua Palmer\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "5",
		"W9": "4",
		"W10": "2",
		"W11": "4",
		"W12": "8",
		"W13": "1",
		"TGTs": "19",
		"TGTs/G": "3.8",
		"Array": "9.4%"
	},
	{
		"Player": "\"Wan'Dale Robinson\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "4",
		"W9": "4",
		"W10": "8",
		"W11": "-",
		"W12": "5",
		"W13": "2",
		"TGTs": "19",
		"TGTs/G": "4.8",
		"Array": "9.8%"
	},
	{
		"Player": "\"Tre Tucker\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "4",
		"W9": "6",
		"W10": "-",
		"W11": "4",
		"W12": "8",
		"W13": "1",
		"TGTs": "19",
		"TGTs/G": "4.8",
		"Array": "7.6%"
	},
	{
		"Player": "\"Mike Evans\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "2",
		"W9": "-",
		"W10": "-",
		"W11": "-",
		"W12": "6",
		"W13": "12",
		"TGTs": "18",
		"TGTs/G": "9.0",
		"Array": "17.0%"
	},
	{
		"Player": "\"Troy Franklin\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "5",
		"W9": "4",
		"W10": "3",
		"W11": "2",
		"W12": "4",
		"W13": "5",
		"TGTs": "18",
		"TGTs/G": "3.6",
		"Array": "13.8%"
	},
	{
		"Player": "\"Christian Watson\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "4",
		"W9": "7",
		"W10": "-",
		"W11": "4",
		"W12": "3",
		"W13": "4",
		"TGTs": "18",
		"TGTs/G": "4.5",
		"Array": "10.8%"
	},
	{
		"Player": "\"Marvin Mims\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "5",
		"W9": "2",
		"W10": "4",
		"W11": "2",
		"W12": "5",
		"W13": "4",
		"TGTs": "17",
		"TGTs/G": "3.4",
		"Array": "18.7%"
	},
	{
		"Player": "\"Jayden Reed\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "4",
		"W9": "6",
		"W10": "-",
		"W11": "2",
		"W12": "3",
		"W13": "6",
		"TGTs": "17",
		"TGTs/G": "4.3",
		"Array": "12.0%"
	},
	{
		"Player": "\"John Metchie\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "5",
		"W9": "2",
		"W10": "6",
		"W11": "3",
		"W12": "3",
		"W13": "2",
		"TGTs": "16",
		"TGTs/G": "3.2",
		"Array": "7.8%"
	},
	{
		"Player": "\"Michael Wilson\"",
		"Pos": "WR",
		"Team": "ARI",
		"G": "4",
		"W9": "1",
		"W10": "4",
		"W11": "-",
		"W12": "4",
		"W13": "7",
		"TGTs": "16",
		"TGTs/G": "4.0",
		"Array": "8.2%"
	},
	{
		"Player": "\"Lil'Jordan Humphrey\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "5",
		"W9": "5",
		"W10": "3",
		"W11": "4",
		"W12": "3",
		"W13": "0",
		"TGTs": "15",
		"TGTs/G": "3.0",
		"Array": "9.7%"
	},
	{
		"Player": "\"Andrei Iosivas\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "4",
		"W9": "4",
		"W10": "4",
		"W11": "3",
		"W12": "-",
		"W13": "4",
		"TGTs": "15",
		"TGTs/G": "3.8",
		"Array": "6.4%"
	},
	{
		"Player": "\"Curtis Samuel\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "4",
		"W9": "1",
		"W10": "8",
		"W11": "6",
		"W12": "-",
		"W13": "0",
		"TGTs": "15",
		"TGTs/G": "3.8",
		"Array": "10.1%"
	},
	{
		"Player": "\"DeVonta Smith\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "3",
		"W9": "6",
		"W10": "3",
		"W11": "6",
		"W12": "-",
		"W13": "-",
		"TGTs": "15",
		"TGTs/G": "5.0",
		"Array": "8.0%"
	},
	{
		"Player": "\"Odell Beckham\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "5",
		"W9": "3",
		"W10": "2",
		"W11": "4",
		"W12": "3",
		"W13": "2",
		"TGTs": "14",
		"TGTs/G": "2.8",
		"Array": "18.4%"
	},
	{
		"Player": "\"Adonai Mitchell\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "5",
		"W9": "1",
		"W10": "6",
		"W11": "2",
		"W12": "3",
		"W13": "2",
		"TGTs": "14",
		"TGTs/G": "2.8",
		"Array": "11.2%"
	},
	{
		"Player": "\"Adam Thielen\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "2",
		"W9": "-",
		"W10": "-",
		"W11": "-",
		"W12": "4",
		"W13": "10",
		"TGTs": "14",
		"TGTs/G": "7.0",
		"Array": "15.7%"
	},
	{
		"Player": "\"Calvin Austin III\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "4",
		"W9": "-",
		"W10": "6",
		"W11": "2",
		"W12": "3",
		"W13": "2",
		"TGTs": "13",
		"TGTs/G": "3.3",
		"Array": "11.1%"
	},
	{
		"Player": "\"Tyler Boyd\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "5",
		"W9": "0",
		"W10": "0",
		"W11": "3",
		"W12": "6",
		"W13": "4",
		"TGTs": "13",
		"TGTs/G": "2.6",
		"Array": "7.4%"
	},
	{
		"Player": "\"Jalen Brooks\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "4",
		"W9": "5",
		"W10": "4",
		"W11": "-",
		"W12": "3",
		"W13": "1",
		"TGTs": "13",
		"TGTs/G": "3.3",
		"Array": "9.8%"
	},
	{
		"Player": "\"Dyami Brown\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "5",
		"W9": "1",
		"W10": "3",
		"W11": "2",
		"W12": "2",
		"W13": "5",
		"TGTs": "13",
		"TGTs/G": "2.6",
		"Array": "10.2%"
	},
	{
		"Player": "\"Romeo Doubs\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "3",
		"W9": "5",
		"W10": "-",
		"W11": "2",
		"W12": "6",
		"W13": "-",
		"TGTs": "13",
		"TGTs/G": "4.3",
		"Array": "10.2%"
	},
	{
		"Player": "\"Tyler Lockett\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "4",
		"W9": "4",
		"W10": "-",
		"W11": "3",
		"W12": "3",
		"W13": "3",
		"TGTs": "13",
		"TGTs/G": "3.3",
		"Array": "6.9%"
	},
	{
		"Player": "\"Tim Patrick\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "5",
		"W9": "2",
		"W10": "0",
		"W11": "4",
		"W12": "4",
		"W13": "3",
		"TGTs": "13",
		"TGTs/G": "2.6",
		"Array": "6.0%"
	},
	{
		"Player": "\"KaVontae Turpin\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "5",
		"W9": "4",
		"W10": "0",
		"W11": "3",
		"W12": "1",
		"W13": "5",
		"TGTs": "13",
		"TGTs/G": "2.6",
		"Array": "17.1%"
	},
	{
		"Player": "\"Justin Watson\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "5",
		"W9": "4",
		"W10": "2",
		"W11": "2",
		"W12": "2",
		"W13": "3",
		"TGTs": "13",
		"TGTs/G": "2.6",
		"Array": "5.9%"
	},
	{
		"Player": "\"Mack Hollins\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "4",
		"W9": "5",
		"W10": "4",
		"W11": "2",
		"W12": "-",
		"W13": "1",
		"TGTs": "12",
		"TGTs/G": "3.0",
		"Array": "6.3%"
	},
	{
		"Player": "\"Tutu Atwell\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "5",
		"W9": "3",
		"W10": "1",
		"W11": "2",
		"W12": "3",
		"W13": "2",
		"TGTs": "11",
		"TGTs/G": "2.2",
		"Array": "12.9%"
	},
	{
		"Player": "\"Jalen Coker\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "2",
		"W9": "3",
		"W10": "8",
		"W11": "-",
		"W12": "-",
		"W13": "-",
		"TGTs": "11",
		"TGTs/G": "5.5",
		"Array": "14.3%"
	},
	{
		"Player": "\"Tyler Johnson\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "5",
		"W9": "5",
		"W10": "4",
		"W11": "0",
		"W12": "1",
		"W13": "1",
		"TGTs": "11",
		"TGTs/G": "2.2",
		"Array": "16.4%"
	},
	{
		"Player": "\"Jonathan Mingo\"",
		"Pos": "WR",
		"Team": "\"CAR",
		"G": " DAL\"",
		"W9": "4",
		"W10": "1",
		"W11": "-",
		"W12": "4",
		"W13": "2",
		"TGTs": "4",
		"TGTs/G": "11",
		"Array": "2.8"
	},
	{
		"Player": "\"Darius Slayton\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "3",
		"W9": "3",
		"W10": "-",
		"W11": "-",
		"W12": "2",
		"W13": "6",
		"TGTs": "11",
		"TGTs/G": "3.7",
		"Array": "8.0%"
	},
	{
		"Player": "\"Marquez Valdes-Scantling\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "4",
		"W9": "1",
		"W10": "3",
		"W11": "4",
		"W12": "-",
		"W13": "3",
		"TGTs": "11",
		"TGTs/G": "2.8",
		"Array": "7.2%"
	},
	{
		"Player": "\"Malik Washington\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "5",
		"W9": "0",
		"W10": "2",
		"W11": "3",
		"W12": "2",
		"W13": "4",
		"TGTs": "11",
		"TGTs/G": "2.2",
		"Array": "9.5%"
	},
	{
		"Player": "\"Dontayvion Wicks\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "4",
		"W9": "3",
		"W10": "-",
		"W11": "1",
		"W12": "2",
		"W13": "5",
		"TGTs": "11",
		"TGTs/G": "2.8",
		"Array": "8.7%"
	},
	{
		"Player": "\"Olamide Zaccheaus\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "5",
		"W9": "2",
		"W10": "3",
		"W11": "2",
		"W12": "1",
		"W13": "3",
		"TGTs": "11",
		"TGTs/G": "2.2",
		"Array": "9.1%"
	},
	{
		"Player": "\"Jalen Nailor\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "5",
		"W9": "1",
		"W10": "3",
		"W11": "2",
		"W12": "2",
		"W13": "2",
		"TGTs": "10",
		"TGTs/G": "2.0",
		"Array": "6.5%"
	},
	{
		"Player": "\"Robert Woods\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "5",
		"W9": "3",
		"W10": "3",
		"W11": "2",
		"W12": "1",
		"W13": "1",
		"TGTs": "10",
		"TGTs/G": "2.0",
		"Array": "8.5%"
	},
	{
		"Player": "\"Jermaine Burton\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "3",
		"W9": "-",
		"W10": "5",
		"W11": "4",
		"W12": "-",
		"W13": "0",
		"TGTs": "9",
		"TGTs/G": "3.0",
		"Array": "15.3%"
	},
	{
		"Player": "\"Ricky Pearsall\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "4",
		"W9": "-",
		"W10": "6",
		"W11": "2",
		"W12": "0",
		"W13": "1",
		"TGTs": "9",
		"TGTs/G": "2.3",
		"Array": "6.2%"
	},
	{
		"Player": "\"Xavier Hutchinson\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "4",
		"W9": "3",
		"W10": "4",
		"W11": "0",
		"W12": "1",
		"W13": "-",
		"TGTs": "8",
		"TGTs/G": "2.0",
		"Array": "5.3%"
	},
	{
		"Player": "\"Van Jefferson\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "4",
		"W9": "-",
		"W10": "2",
		"W11": "1",
		"W12": "2",
		"W13": "3",
		"TGTs": "8",
		"TGTs/G": "2.0",
		"Array": "5.0%"
	},
	{
		"Player": "\"Jalen Reagor\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "5",
		"W9": "2",
		"W10": "1",
		"W11": "1",
		"W12": "4",
		"W13": "0",
		"TGTs": "8",
		"TGTs/G": "1.6",
		"Array": "9.5%"
	},
	{
		"Player": "\"DJ Turner\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "4",
		"W9": "0",
		"W10": "-",
		"W11": "3",
		"W12": "4",
		"W13": "1",
		"TGTs": "8",
		"TGTs/G": "2.0",
		"Array": "7.1%"
	},
	{
		"Player": "\"Brandin Cooks\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "1",
		"W9": "-",
		"W10": "-",
		"W11": "-",
		"W12": "-",
		"W13": "7",
		"TGTs": "7",
		"TGTs/G": "7.0",
		"Array": "23.3%"
	},
	{
		"Player": "\"Gabe Davis\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "2",
		"W9": "-",
		"W10": "4",
		"W11": "3",
		"W12": "-",
		"W13": "-",
		"TGTs": "7",
		"TGTs/G": "3.5",
		"Array": "10.9%"
	},
	{
		"Player": "\"Greg Dortch\"",
		"Pos": "WR",
		"Team": "ARI",
		"G": "4",
		"W9": "1",
		"W10": "1",
		"W11": "-",
		"W12": "2",
		"W13": "3",
		"TGTs": "7",
		"TGTs/G": "1.8",
		"Array": "10.3%"
	},
	{
		"Player": "\"Mecole Hardman\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "5",
		"W9": "3",
		"W10": "1",
		"W11": "3",
		"W12": "0",
		"W13": "0",
		"TGTs": "7",
		"TGTs/G": "1.4",
		"Array": "13.7%"
	},
	{
		"Player": "\"Luke McCaffrey\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "5",
		"W9": "0",
		"W10": "3",
		"W11": "1",
		"W12": "1",
		"W13": "2",
		"TGTs": "7",
		"TGTs/G": "1.4",
		"Array": "6.3%"
	},
	{
		"Player": "\"Ryan Miller\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "4",
		"W9": "3",
		"W10": "3",
		"W11": "-",
		"W12": "1",
		"W13": "0",
		"TGTs": "7",
		"TGTs/G": "1.8",
		"Array": "6.4%"
	},
	{
		"Player": "\"Trey Palmer\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "4",
		"W9": "4",
		"W10": "1",
		"W11": "-",
		"W12": "1",
		"W13": "1",
		"TGTs": "7",
		"TGTs/G": "1.8",
		"Array": "9.5%"
	},
	{
		"Player": "\"Tylan Wallace\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "5",
		"W9": "0",
		"W10": "3",
		"W11": "1",
		"W12": "1",
		"W13": "2",
		"TGTs": "7",
		"TGTs/G": "1.4",
		"Array": "8.0%"
	},
	{
		"Player": "\"Nelson Agholor\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "5",
		"W9": "1",
		"W10": "2",
		"W11": "1",
		"W12": "0",
		"W13": "2",
		"TGTs": "6",
		"TGTs/G": "1.2",
		"Array": "4.2%"
	},
	{
		"Player": "\"Amari Cooper\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "2",
		"W9": "-",
		"W10": "-",
		"W11": "3",
		"W12": "-",
		"W13": "3",
		"TGTs": "6",
		"TGTs/G": "3.0",
		"Array": "9.4%"
	},
	{
		"Player": "\"Derius Davis\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "5",
		"W9": "0",
		"W10": "1",
		"W11": "2",
		"W12": "2",
		"W13": "1",
		"TGTs": "6",
		"TGTs/G": "1.2",
		"Array": "20.0%"
	},
	{
		"Player": "\"Jahan Dotson\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "5",
		"W9": "1",
		"W10": "1",
		"W11": "2",
		"W12": "1",
		"W13": "1",
		"TGTs": "6",
		"TGTs/G": "1.2",
		"Array": "3.2%"
	},
	{
		"Player": "\"Devin Duvernay\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "2",
		"W9": "-",
		"W10": "0",
		"W11": "2",
		"W12": "-",
		"W13": "4",
		"TGTs": "6",
		"TGTs/G": "3.0",
		"Array": "11.1%"
	},
	{
		"Player": "\"Jalin Hyatt\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "4",
		"W9": "0",
		"W10": "4",
		"W11": "-",
		"W12": "0",
		"W13": "2",
		"TGTs": "6",
		"TGTs/G": "1.5",
		"Array": "5.9%"
	},
	{
		"Player": "\"Rakim Jarrett\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "4",
		"W9": "1",
		"W10": "4",
		"W11": "-",
		"W12": "1",
		"W13": "0",
		"TGTs": "6",
		"TGTs/G": "1.5",
		"Array": "4.7%"
	},
	{
		"Player": "\"Kevin Austin\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "2",
		"W9": "-",
		"W10": "-",
		"W11": "2",
		"W12": "-",
		"W13": "3",
		"TGTs": "5",
		"TGTs/G": "2.5",
		"Array": "6.0%"
	},
	{
		"Player": "\"Malachi Corley\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "4",
		"W9": "0",
		"W10": "2",
		"W11": "1",
		"W12": "-",
		"W13": "2",
		"TGTs": "5",
		"TGTs/G": "1.3",
		"Array": "6.7%"
	},
	{
		"Player": "\"Ryan Flournoy\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "4",
		"W9": "2",
		"W10": "0",
		"W11": "3",
		"W12": "0",
		"W13": "-",
		"TGTs": "5",
		"TGTs/G": "1.3",
		"Array": "5.2%"
	},
	{
		"Player": "\"Diontae Johnson\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "4",
		"W9": "0",
		"W10": "2",
		"W11": "2",
		"W12": "1",
		"W13": "-",
		"TGTs": "5",
		"TGTs/G": "1.3",
		"Array": "12.8%"
	},
	{
		"Player": "\"Jalen McMillan\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "2",
		"W9": "-",
		"W10": "-",
		"W11": "-",
		"W12": "2",
		"W13": "3",
		"TGTs": "5",
		"TGTs/G": "2.5",
		"Array": "4.9%"
	},
	{
		"Player": "\"Ja'Lynn Polk\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "5",
		"W9": "1",
		"W10": "1",
		"W11": "0",
		"W12": "2",
		"W13": "1",
		"TGTs": "5",
		"TGTs/G": "1.0",
		"Array": "4.6%"
	},
	{
		"Player": "\"KhaDarel Hodge\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "4",
		"W9": "2",
		"W10": "0",
		"W11": "2",
		"W12": "-",
		"W13": "0",
		"TGTs": "4",
		"TGTs/G": "1.0",
		"Array": "5.1%"
	},
	{
		"Player": "\"Dante Pettis\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "3",
		"W9": "-",
		"W10": "1",
		"W11": "1",
		"W12": "-",
		"W13": "2",
		"TGTs": "4",
		"TGTs/G": "1.3",
		"Array": "14.3%"
	},
	{
		"Player": "\"Kalif Raymond\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "4",
		"W9": "1",
		"W10": "0",
		"W11": "2",
		"W12": "1",
		"W13": "-",
		"TGTs": "4",
		"TGTs/G": "1.0",
		"Array": "5.5%"
	},
	{
		"Player": "\"JuJu Smith-Schuster\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "3",
		"W9": "-",
		"W10": "-",
		"W11": "1",
		"W12": "2",
		"W13": "1",
		"TGTs": "4",
		"TGTs/G": "1.3",
		"Array": "4.0%"
	},
	{
		"Player": "\"Cedrick Wilson\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "3",
		"W9": "3",
		"W10": "-",
		"W11": "0",
		"W12": "-",
		"W13": "1",
		"TGTs": "4",
		"TGTs/G": "1.3",
		"Array": "5.7%"
	},
	{
		"Player": "\"Ashton Dulin\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "4",
		"W9": "2",
		"W10": "0",
		"W11": "0",
		"W12": "1",
		"W13": "-",
		"TGTs": "3",
		"TGTs/G": "0.8",
		"Array": "6.3%"
	},
	{
		"Player": "\"Xavier Gipson\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "4",
		"W9": "0",
		"W10": "1",
		"W11": "1",
		"W12": "-",
		"W13": "1",
		"TGTs": "3",
		"TGTs/G": "0.8",
		"Array": "3.8%"
	},
	{
		"Player": "\"Ramel Keyton\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "3",
		"W9": "2",
		"W10": "-",
		"W11": "1",
		"W12": "0",
		"W13": "-",
		"TGTs": "3",
		"TGTs/G": "1.0",
		"Array": "8.6%"
	},
	{
		"Player": "\"Bo Melton\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "4",
		"W9": "2",
		"W10": "-",
		"W11": "0",
		"W12": "1",
		"W13": "0",
		"TGTs": "3",
		"TGTs/G": "0.8",
		"Array": "6.3%"
	},
	{
		"Player": "\"Bryce Oliver\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "4",
		"W9": "0",
		"W10": "2",
		"W11": "1",
		"W12": "0",
		"W13": "0",
		"TGTs": "3",
		"TGTs/G": "0.8",
		"Array": "15.0%"
	},
	{
		"Player": "\"Brandon Powell\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "5",
		"W9": "1",
		"W10": "0",
		"W11": "1",
		"W12": "0",
		"W13": "1",
		"TGTs": "3",
		"TGTs/G": "0.6",
		"Array": "5.4%"
	},
	{
		"Player": "\"Allen Robinson\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "5",
		"W9": "1",
		"W10": "0",
		"W11": "2",
		"W12": "0",
		"W13": "0",
		"TGTs": "3",
		"TGTs/G": "0.6",
		"Array": "8.1%"
	},
	{
		"Player": "\"Trent Sherfield\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "5",
		"W9": "1",
		"W10": "1",
		"W11": "1",
		"W12": "0",
		"W13": "0",
		"TGTs": "3",
		"TGTs/G": "0.6",
		"Array": "5.9%"
	},
	{
		"Player": "\"Ainias Smith\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "4",
		"W9": "1",
		"W10": "2",
		"W11": "0",
		"W12": "0",
		"W13": "-",
		"TGTs": "3",
		"TGTs/G": "0.8",
		"Array": "8.3%"
	},
	{
		"Player": "\"Deven Thompkins\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "4",
		"W9": "0",
		"W10": "0",
		"W11": "-",
		"W12": "3",
		"W13": "0",
		"TGTs": "3",
		"TGTs/G": "0.8",
		"Array": "10.7%"
	},
	{
		"Player": "\"Jamari Thrash\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "4",
		"W9": "0",
		"W10": "-",
		"W11": "1",
		"W12": "0",
		"W13": "2",
		"TGTs": "3",
		"TGTs/G": "0.8",
		"Array": "6.7%"
	},
	{
		"Player": "\"Mason Tipton\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "2",
		"W9": "3",
		"W10": "0",
		"W11": "-",
		"W12": "-",
		"W13": "-",
		"TGTs": "3",
		"TGTs/G": "1.5",
		"Array": "3.4%"
	},
	{
		"Player": "\"Austin Trammell\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "1",
		"W9": "3",
		"W10": "-",
		"W11": "-",
		"W12": "-",
		"W13": "-",
		"TGTs": "3",
		"TGTs/G": "3.0",
		"Array": "9.1%"
	},
	{
		"Player": "\"Cody White\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "4",
		"W9": "3",
		"W10": "-",
		"W11": "0",
		"W12": "0",
		"W13": "0",
		"TGTs": "3",
		"TGTs/G": "0.8",
		"Array": "4.8%"
	},
	{
		"Player": "\"Mike Williams\"",
		"Pos": "WR",
		"Team": "\"NYJ",
		"G": " PIT\"",
		"W9": "5",
		"W10": "2",
		"W11": "1",
		"W12": "0",
		"W13": "0",
		"TGTs": "0",
		"TGTs/G": "3",
		"Array": "0.6"
	},
	{
		"Player": "\"Jake Bobo\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "4",
		"W9": "1",
		"W10": "-",
		"W11": "0",
		"W12": "1",
		"W13": "0",
		"TGTs": "2",
		"TGTs/G": "0.5",
		"Array": "2.4%"
	},
	{
		"Player": "\"Keon Coleman\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "1",
		"W9": "2",
		"W10": "-",
		"W11": "-",
		"W12": "-",
		"W13": "-",
		"TGTs": "2",
		"TGTs/G": "2.0",
		"Array": "3.8%"
	},
	{
		"Player": "\"Malik Heath\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "3",
		"W9": "-",
		"W10": "-",
		"W11": "0",
		"W12": "2",
		"W13": "0",
		"TGTs": "2",
		"TGTs/G": "0.7",
		"Array": "10.5%"
	},
	{
		"Player": "\"Jha'Quan Jackson\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "5",
		"W9": "2",
		"W10": "0",
		"W11": "0",
		"W12": "0",
		"W13": "0",
		"TGTs": "2",
		"TGTs/G": "0.4",
		"Array": "5.1%"
	},
	{
		"Player": "\"Tim Jones\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "4",
		"W9": "2",
		"W10": "0",
		"W11": "0",
		"W12": "-",
		"W13": "0",
		"TGTs": "2",
		"TGTs/G": "0.5",
		"Array": "4.8%"
	},
	{
		"Player": "\"Ben Skowronek\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "4",
		"W9": "-",
		"W10": "0",
		"W11": "1",
		"W12": "0",
		"W13": "1",
		"TGTs": "2",
		"TGTs/G": "0.5",
		"Array": "4.0%"
	},
	{
		"Player": "\"Johnny Wilson\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "4",
		"W9": "0",
		"W10": "1",
		"W11": "0",
		"W12": "1",
		"W13": "-",
		"TGTs": "2",
		"TGTs/G": "0.5",
		"Array": "1.7%"
	},
	{
		"Player": "\"Javon Baker\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "5",
		"W9": "0",
		"W10": "0",
		"W11": "0",
		"W12": "1",
		"W13": "0",
		"TGTs": "1",
		"TGTs/G": "0.2",
		"Array": "3.8%"
	},
	{
		"Player": "\"DeAndre Carter\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "4",
		"W9": "0",
		"W10": "1",
		"W11": "0",
		"W12": "0",
		"W13": "0",
		"TGTs": "1",
		"TGTs/G": "0.3",
		"Array": "10.0%"
	},
	{
		"Player": "\"Dan Chisena\"",
		"Pos": "WR",
		"Team": "ARI",
		"G": "2",
		"W9": "-",
		"W10": "-",
		"W11": "-",
		"W12": "0",
		"W13": "1",
		"TGTs": "1",
		"TGTs/G": "0.5",
		"Array": "33.3%"
	},
	{
		"Player": "\"Chris Conley\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "3",
		"W9": "-",
		"W10": "-",
		"W11": "0",
		"W12": "1",
		"W13": "0",
		"TGTs": "1",
		"TGTs/G": "0.3",
		"Array": "10.0%"
	},
	{
		"Player": "\"Britain Covey\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "2",
		"W9": "-",
		"W10": "-",
		"W11": "-",
		"W12": "0",
		"W13": "1",
		"TGTs": "1",
		"TGTs/G": "0.5",
		"Array": "9.1%"
	},
	{
		"Player": "\"Simi Fehoko\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "1",
		"W9": "1",
		"W10": "-",
		"W11": "-",
		"W12": "-",
		"W13": "-",
		"TGTs": "1",
		"TGTs/G": "1.0",
		"Array": "11.1%"
	},
	{
		"Player": "\"Isaiah Hodgins\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "1",
		"W9": "-",
		"W10": "1",
		"W11": "-",
		"W12": "-",
		"W13": "-",
		"TGTs": "1",
		"TGTs/G": "1.0",
		"Array": "4.3%"
	},
	{
		"Player": "\"Trenton Irwin\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "3",
		"W9": "1",
		"W10": "0",
		"W11": "0",
		"W12": "-",
		"W13": "-",
		"TGTs": "1",
		"TGTs/G": "0.3",
		"Array": "2.6%"
	},
	{
		"Player": "\"Terrace Marshall\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "2",
		"W9": "-",
		"W10": "-",
		"W11": "0",
		"W12": "-",
		"W13": "1",
		"TGTs": "1",
		"TGTs/G": "0.5",
		"Array": "4.3%"
	},
	{
		"Player": "\"Chris Olave\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "1",
		"W9": "1",
		"W10": "-",
		"W11": "-",
		"W12": "-",
		"W13": "-",
		"TGTs": "1",
		"TGTs/G": "1.0",
		"Array": "12.5%"
	},
	{
		"Player": "\"K.J. Osborn\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "1",
		"W9": "-",
		"W10": "1",
		"W11": "-",
		"W12": "-",
		"W13": "-",
		"TGTs": "1",
		"TGTs/G": "1.0",
		"Array": "3.4%"
	},
	{
		"Player": "\"Kendric Pryor\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "1",
		"W9": "1",
		"W10": "-",
		"W11": "-",
		"W12": "-",
		"W13": "-",
		"TGTs": "1",
		"TGTs/G": "1.0",
		"Array": "5.6%"
	},
	{
		"Player": "\"Justyn Ross\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "1",
		"W9": "-",
		"W10": "1",
		"W11": "-",
		"W12": "-",
		"W13": "-",
		"TGTs": "1",
		"TGTs/G": "1.0",
		"Array": "14.3%"
	},
	{
		"Player": "\"Kadarius Toney\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "2",
		"W9": "-",
		"W10": "-",
		"W11": "0",
		"W12": "-",
		"W13": "1",
		"TGTs": "1",
		"TGTs/G": "0.5",
		"Array": "8.3%"
	},
	{
		"Player": "\"Casey Washington\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "1",
		"W9": "0",
		"W10": "0",
		"W11": "1",
		"W12": "-",
		"W13": "0",
		"TGTs": "1",
		"TGTs/G": "1.0",
		"Array": "50.0%"
	},
	
]

module.exports = wr4for4PlayerTargetsAppLastFiveWeeks