const wr4for4FantasyPointsBrowserLastFiveWeeks = [
	{
		"Player": "\"Malik Nabers\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "3",
		"W1": "11.6",
		"W2": "28.7",
		"W3": "28.2",
		"\"PPR Pts\"": "68.5",
		"\"PPR Pts/G\"": "22.8"
	},
	{
		"Player": "\"Rashee Rice\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "3",
		"W1": "17.3",
		"W2": "18.5",
		"W3": "29.1",
		"\"PPR Pts\"": "64.9",
		"\"PPR Pts/G\"": "21.6"
	},
	{
		"Player": "\"Chris Godwin\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "3",
		"W1": "22.3",
		"W2": "24.7",
		"W3": "17.3",
		"\"PPR Pts\"": "64.3",
		"\"PPR Pts/G\"": "21.4"
	},
	{
		"Player": "\"Jauan Jennings\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "3",
		"W1": "11.4",
		"W2": "5.7",
		"W3": "46.5",
		"\"PPR Pts\"": "63.6",
		"\"PPR Pts/G\"": "21.2"
	},
	{
		"Player": "\"Justin Jefferson\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "3",
		"W1": "15.9",
		"W2": "23.3",
		"W3": "20.1",
		"\"PPR Pts\"": "59.3",
		"\"PPR Pts/G\"": "19.8"
	},
	{
		"Player": "\"Nico Collins\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "3",
		"W1": "17.7",
		"W2": "27.5",
		"W3": "12.6",
		"\"PPR Pts\"": "57.8",
		"\"PPR Pts/G\"": "19.3"
	},
	{
		"Player": "\"DK Metcalf\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "3",
		"W1": "5.9",
		"W2": "28.9",
		"W3": "20.4",
		"\"PPR Pts\"": "55.2",
		"\"PPR Pts/G\"": "18.4"
	},
	{
		"Player": "\"DeVonta Smith\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "3",
		"W1": "15.4",
		"W2": "20.6",
		"W3": "14.9",
		"\"PPR Pts\"": "50.9",
		"\"PPR Pts/G\"": "17.0"
	},
	{
		"Player": "\"Jayden Reed\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "3",
		"W1": "33.1",
		"W2": "6.6",
		"W3": "10.9",
		"\"PPR Pts\"": "50.6",
		"\"PPR Pts/G\"": "16.9"
	},
	{
		"Player": "\"Stefon Diggs\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "3",
		"W1": "21.9",
		"W2": "7.7",
		"W3": "19.9",
		"\"PPR Pts\"": "49.5",
		"\"PPR Pts/G\"": "16.5"
	},
	{
		"Player": "\"Ja'Marr Chase\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "3",
		"W1": "12.2",
		"W2": "7.5",
		"W3": "29.8",
		"\"PPR Pts\"": "49.5",
		"\"PPR Pts/G\"": "16.5"
	},
	{
		"Player": "\"Marvin Harrison Jr.\"",
		"Pos": "WR",
		"Team": "ARI",
		"G": "3",
		"W1": "1.4",
		"W2": "29.0",
		"W3": "17.4",
		"\"PPR Pts\"": "47.8",
		"\"PPR Pts/G\"": "15.9"
	},
	{
		"Player": "\"Amon-Ra St. Brown\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "3",
		"W1": "4.3",
		"W2": "22.9",
		"W3": "20.5",
		"\"PPR Pts\"": "47.7",
		"\"PPR Pts/G\"": "15.9"
	},
	{
		"Player": "\"Davante Adams\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "3",
		"W1": "10.9",
		"W2": "26.0",
		"W3": "8.0",
		"\"PPR Pts\"": "44.9",
		"\"PPR Pts/G\"": "15.0"
	},
	{
		"Player": "\"Allen Lazard\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "3",
		"W1": "26.9",
		"W2": "3.1",
		"W3": "13.8",
		"\"PPR Pts\"": "43.8",
		"\"PPR Pts/G\"": "14.6"
	},
	{
		"Player": "\"Alec Pierce\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "3",
		"W1": "21.5",
		"W2": "16.6",
		"W3": "5.4",
		"\"PPR Pts\"": "43.5",
		"\"PPR Pts/G\"": "14.5"
	},
	{
		"Player": "\"Khalil Shakir\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "3",
		"W1": "13.2",
		"W2": "10.6",
		"W3": "19.2",
		"\"PPR Pts\"": "43.0",
		"\"PPR Pts/G\"": "14.3"
	},
	{
		"Player": "\"Quentin Johnston\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "3",
		"W1": "6.8",
		"W2": "22.1",
		"W3": "12.4",
		"\"PPR Pts\"": "41.3",
		"\"PPR Pts/G\"": "13.8"
	},
	{
		"Player": "\"CeeDee Lamb\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "3",
		"W1": "13.6",
		"W2": "19.0",
		"W3": "8.7",
		"\"PPR Pts\"": "41.3",
		"\"PPR Pts/G\"": "13.8"
	},
	{
		"Player": "\"Jameson Williams\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "3",
		"W1": "24.4",
		"W2": "14.4",
		"W3": "1.2",
		"\"PPR Pts\"": "40.0",
		"\"PPR Pts/G\"": "13.3"
	},
	{
		"Player": "\"Cooper Kupp\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "2",
		"W1": "32.0",
		"W2": "7.7",
		"W3": "-",
		"\"PPR Pts\"": "39.7",
		"\"PPR Pts/G\"": "19.9"
	},
	{
		"Player": "\"Tyreek Hill\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "3",
		"W1": "26.0",
		"W2": "6.6",
		"W3": "7.0",
		"\"PPR Pts\"": "39.6",
		"\"PPR Pts/G\"": "13.2"
	},
	{
		"Player": "\"Drake London\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "3",
		"W1": "3.5",
		"W2": "17.4",
		"W3": "18.7",
		"\"PPR Pts\"": "39.6",
		"\"PPR Pts/G\"": "13.2"
	},
	{
		"Player": "\"Zay Flowers\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "3",
		"W1": "11.1",
		"W2": "22.1",
		"W3": "5.3",
		"\"PPR Pts\"": "38.5",
		"\"PPR Pts/G\"": "12.8"
	},
	{
		"Player": "\"Jakobi Meyers\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "3",
		"W1": "9.4",
		"W2": "6.9",
		"W3": "21.2",
		"\"PPR Pts\"": "37.5",
		"\"PPR Pts/G\"": "12.5"
	},
	{
		"Player": "\"Rashid Shaheed\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "3",
		"W1": "16.3",
		"W2": "20.9",
		"W3": "0.0",
		"\"PPR Pts\"": "37.2",
		"\"PPR Pts/G\"": "12.4"
	},
	{
		"Player": "\"Deebo Samuel\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "2",
		"W1": "18.7",
		"W2": "18.0",
		"W3": "-",
		"\"PPR Pts\"": "36.7",
		"\"PPR Pts/G\"": "18.4"
	},
	{
		"Player": "\"Andrei Iosivas\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "3",
		"W1": "5.6",
		"W2": "14.7",
		"W3": "16.2",
		"\"PPR Pts\"": "36.5",
		"\"PPR Pts/G\"": "12.2"
	},
	{
		"Player": "\"D.J. Moore\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "3",
		"W1": "10.0",
		"W2": "11.3",
		"W3": "15.2",
		"\"PPR Pts\"": "36.5",
		"\"PPR Pts/G\"": "12.2"
	},
	{
		"Player": "\"Chris Olave\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "3",
		"W1": "3.1",
		"W2": "12.8",
		"W3": "20.6",
		"\"PPR Pts\"": "36.5",
		"\"PPR Pts/G\"": "12.2"
	},
	{
		"Player": "\"Garrett Wilson\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "3",
		"W1": "12.0",
		"W2": "10.2",
		"W3": "14.3",
		"\"PPR Pts\"": "36.5",
		"\"PPR Pts/G\"": "12.2"
	},
	{
		"Player": "\"Brian Thomas Jr.\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "3",
		"W1": "14.7",
		"W2": "11.4",
		"W3": "9.8",
		"\"PPR Pts\"": "35.9",
		"\"PPR Pts/G\"": "12.0"
	},
	{
		"Player": "\"Jalen Nailor\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "3",
		"W1": "9.1",
		"W2": "14.4",
		"W3": "12.4",
		"\"PPR Pts\"": "35.9",
		"\"PPR Pts/G\"": "12.0"
	},
	{
		"Player": "\"Amari Cooper\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "3",
		"W1": "3.6",
		"W2": "4.1",
		"W3": "27.6",
		"\"PPR Pts\"": "35.3",
		"\"PPR Pts/G\"": "11.8"
	},
	{
		"Player": "\"Darnell Mooney\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "3",
		"W1": "2.5",
		"W2": "17.8",
		"W3": "14.6",
		"\"PPR Pts\"": "34.9",
		"\"PPR Pts/G\"": "11.6"
	},
	{
		"Player": "\"Wan'Dale Robinson\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "3",
		"W1": "11.8",
		"W2": "9.8",
		"W3": "13.1",
		"\"PPR Pts\"": "34.7",
		"\"PPR Pts/G\"": "11.6"
	},
	{
		"Player": "\"Diontae Johnson\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "3",
		"W1": "3.9",
		"W2": "4.5",
		"W3": "26.2",
		"\"PPR Pts\"": "34.6",
		"\"PPR Pts/G\"": "11.5"
	},
	{
		"Player": "\"Calvin Ridley\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "3",
		"W1": "8.0",
		"W2": "24.7",
		"W3": "1.9",
		"\"PPR Pts\"": "34.6",
		"\"PPR Pts/G\"": "11.5"
	},
	{
		"Player": "\"Jaxon Smith-Njigba\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "3",
		"W1": "3.9",
		"W2": "23.7",
		"W3": "6.9",
		"\"PPR Pts\"": "34.5",
		"\"PPR Pts/G\"": "11.5"
	},
	{
		"Player": "\"Mike Evans\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "3",
		"W1": "23.1",
		"W2": "7.2",
		"W3": "3.7",
		"\"PPR Pts\"": "34.0",
		"\"PPR Pts/G\"": "11.3"
	},
	{
		"Player": "\"Jerry Jeudy\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "3",
		"W1": "11.5",
		"W2": "12.3",
		"W3": "8.7",
		"\"PPR Pts\"": "32.5",
		"\"PPR Pts/G\"": "10.8"
	},
	{
		"Player": "\"Terry McLaurin\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "3",
		"W1": "3.7",
		"W2": "8.2",
		"W3": "20.0",
		"\"PPR Pts\"": "31.9",
		"\"PPR Pts/G\"": "10.6"
	},
	{
		"Player": "\"Jaylen Waddle\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "3",
		"W1": "16.2",
		"W2": "8.5",
		"W3": "6.6",
		"\"PPR Pts\"": "31.3",
		"\"PPR Pts/G\"": "10.4"
	},
	{
		"Player": "\"Rome Odunze\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "3",
		"W1": "2.1",
		"W2": "5.3",
		"W3": "23.4",
		"\"PPR Pts\"": "30.8",
		"\"PPR Pts/G\"": "10.3"
	},
	{
		"Player": "\"Tre Tucker\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "3",
		"W1": "4.2",
		"W2": "3.3",
		"W3": "22.6",
		"\"PPR Pts\"": "30.1",
		"\"PPR Pts/G\"": "10.0"
	},
	{
		"Player": "\"Xavier Worthy\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "3",
		"W1": "20.8",
		"W2": "4.2",
		"W3": "5.0",
		"\"PPR Pts\"": "30.0",
		"\"PPR Pts/G\"": "10.0"
	},
	{
		"Player": "\"Jalen Tolbert\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "3",
		"W1": "2.2",
		"W2": "14.2",
		"W3": "13.2",
		"\"PPR Pts\"": "29.6",
		"\"PPR Pts/G\"": "9.9"
	},
	{
		"Player": "\"George Pickens\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "3",
		"W1": "13.5",
		"W2": "4.9",
		"W3": "10.7",
		"\"PPR Pts\"": "29.1",
		"\"PPR Pts/G\"": "9.7"
	},
	{
		"Player": "\"Josh Reynolds\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "3",
		"W1": "9.5",
		"W2": "13.3",
		"W3": "5.6",
		"\"PPR Pts\"": "28.4",
		"\"PPR Pts/G\"": "9.5"
	},
	{
		"Player": "\"Michael Wilson\"",
		"Pos": "WR",
		"Team": "ARI",
		"G": "3",
		"W1": "7.5",
		"W2": "5.1",
		"W3": "14.4",
		"\"PPR Pts\"": "27.0",
		"\"PPR Pts/G\"": "9.0"
	},
	{
		"Player": "\"Ladd McConkey\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "3",
		"W1": "14.9",
		"W2": "4.6",
		"W3": "7.4",
		"\"PPR Pts\"": "26.9",
		"\"PPR Pts/G\"": "9.0"
	},
	{
		"Player": "\"Tyler Lockett\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "3",
		"W1": "13.7",
		"W2": "3.5",
		"W3": "9.6",
		"\"PPR Pts\"": "26.8",
		"\"PPR Pts/G\"": "8.9"
	},
	{
		"Player": "\"Rashod Bateman\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "3",
		"W1": "7.3",
		"W2": "7.0",
		"W3": "11.8",
		"\"PPR Pts\"": "26.1",
		"\"PPR Pts/G\"": "8.7"
	},
	{
		"Player": "\"Courtland Sutton\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "3",
		"W1": "7.8",
		"W2": "3.6",
		"W3": "13.8",
		"\"PPR Pts\"": "25.2",
		"\"PPR Pts/G\"": "8.4"
	},
	{
		"Player": "\"Adam Thielen\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "3",
		"W1": "7.9",
		"W2": "4.0",
		"W3": "13.0",
		"\"PPR Pts\"": "24.9",
		"\"PPR Pts/G\"": "8.3"
	},
	{
		"Player": "\"DeAndre Hopkins\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "3",
		"W1": "1.8",
		"W2": "1.9",
		"W3": "19.3",
		"\"PPR Pts\"": "23.0",
		"\"PPR Pts/G\"": "7.7"
	},
	{
		"Player": "\"Brandon Aiyuk\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "3",
		"W1": "4.8",
		"W2": "8.3",
		"W3": "9.8",
		"\"PPR Pts\"": "22.9",
		"\"PPR Pts/G\"": "7.6"
	},
	{
		"Player": "\"A.J. Brown\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "1",
		"W1": "22.9",
		"W2": "-",
		"W3": "-",
		"\"PPR Pts\"": "22.9",
		"\"PPR Pts/G\"": "22.9"
	},
	{
		"Player": "\"Calvin Austin III\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "3",
		"W1": "1.7",
		"W2": "1.6",
		"W3": "19.5",
		"\"PPR Pts\"": "22.8",
		"\"PPR Pts/G\"": "7.6"
	},
	{
		"Player": "\"Tank Dell\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "3",
		"W1": "8.9",
		"W2": "2.3",
		"W3": "11.2",
		"\"PPR Pts\"": "22.4",
		"\"PPR Pts/G\"": "7.5"
	},
	{
		"Player": "\"Ray-Ray McCloud\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "3",
		"W1": "9.2",
		"W2": "7.5",
		"W3": "5.7",
		"\"PPR Pts\"": "22.4",
		"\"PPR Pts/G\"": "7.5"
	},
	{
		"Player": "\"Tyler Johnson\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "3",
		"W1": "12.9",
		"W2": "4.0",
		"W3": "5.0",
		"\"PPR Pts\"": "21.9",
		"\"PPR Pts/G\"": "7.3"
	},
	{
		"Player": "\"Brandin Cooks\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "3",
		"W1": "14.5",
		"W2": "3.6",
		"W3": "3.6",
		"\"PPR Pts\"": "21.7",
		"\"PPR Pts/G\"": "7.2"
	},
	{
		"Player": "\"Tutu Atwell\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "3",
		"W1": "0.0",
		"W2": "7.8",
		"W3": "13.3",
		"\"PPR Pts\"": "21.1",
		"\"PPR Pts/G\"": "7.0"
	},
	{
		"Player": "\"Romeo Doubs\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "3",
		"W1": "9.0",
		"W2": "9.2",
		"W3": "2.8",
		"\"PPR Pts\"": "21.0",
		"\"PPR Pts/G\"": "7.0"
	},
	{
		"Player": "\"Christian Kirk\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "3",
		"W1": "4.0",
		"W2": "0.9",
		"W3": "15.9",
		"\"PPR Pts\"": "20.8",
		"\"PPR Pts/G\"": "6.9"
	},
	{
		"Player": "\"Greg Dortch\"",
		"Pos": "WR",
		"Team": "ARI",
		"G": "3",
		"W1": "11.1",
		"W2": "3.1",
		"W3": "6.5",
		"\"PPR Pts\"": "20.7",
		"\"PPR Pts/G\"": "6.9"
	},
	{
		"Player": "\"Gabe Davis\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "3",
		"W1": "9.2",
		"W2": "7.3",
		"W3": "3.8",
		"\"PPR Pts\"": "20.3",
		"\"PPR Pts/G\"": "6.8"
	},
	{
		"Player": "\"Michael Pittman Jr.\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "3",
		"W1": "7.1",
		"W2": "5.1",
		"W3": "7.6",
		"\"PPR Pts\"": "19.8",
		"\"PPR Pts/G\"": "6.6"
	},
	{
		"Player": "\"Demarcus Robinson\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "3",
		"W1": "8.2",
		"W2": "7.0",
		"W3": "4.2",
		"\"PPR Pts\"": "19.4",
		"\"PPR Pts/G\"": "6.5"
	},
	{
		"Player": "\"Christian Watson\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "3",
		"W1": "10.3",
		"W2": "0.0",
		"W3": "8.7",
		"\"PPR Pts\"": "19.0",
		"\"PPR Pts/G\"": "6.3"
	},
	{
		"Player": "\"Lil'Jordan Humphrey\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "3",
		"W1": "0.0",
		"W2": "9.0",
		"W3": "9.7",
		"\"PPR Pts\"": "18.7",
		"\"PPR Pts/G\"": "6.2"
	},
	{
		"Player": "\"Keon Coleman\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "3",
		"W1": "9.1",
		"W2": "0.0",
		"W3": "9.4",
		"\"PPR Pts\"": "18.5",
		"\"PPR Pts/G\"": "6.2"
	},
	{
		"Player": "\"Demario Douglas\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "3",
		"W1": "3.2",
		"W2": "0.0",
		"W3": "14.8",
		"\"PPR Pts\"": "18.0",
		"\"PPR Pts/G\"": "6.0"
	},
	{
		"Player": "\"Elijah Moore\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "3",
		"W1": "3.9",
		"W2": "10.4",
		"W3": "3.7",
		"\"PPR Pts\"": "18.0",
		"\"PPR Pts/G\"": "6.0"
	},
	{
		"Player": "\"KaVontae Turpin\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "3",
		"W1": "0.0",
		"W2": "2.6",
		"W3": "14.2",
		"\"PPR Pts\"": "16.8",
		"\"PPR Pts/G\"": "5.6"
	},
	{
		"Player": "\"Tyler Boyd\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "3",
		"W1": "4.8",
		"W2": "4.6",
		"W3": "6.3",
		"\"PPR Pts\"": "15.7",
		"\"PPR Pts/G\"": "5.2"
	},
	{
		"Player": "\"Jalen McMillan\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "3",
		"W1": "10.2",
		"W2": "3.1",
		"W3": "1.6",
		"\"PPR Pts\"": "14.9",
		"\"PPR Pts/G\"": "5.0"
	},
	{
		"Player": "\"Ashton Dulin\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "3",
		"W1": "12.4",
		"W2": "2.3",
		"W3": "0.0",
		"\"PPR Pts\"": "14.7",
		"\"PPR Pts/G\"": "4.9"
	},
	{
		"Player": "\"Noah Brown\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "2",
		"W1": "-",
		"W2": "8.6",
		"W3": "5.9",
		"\"PPR Pts\"": "14.5",
		"\"PPR Pts/G\"": "7.3"
	},
	{
		"Player": "\"Ja'Lynn Polk\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "3",
		"W1": "1.6",
		"W2": "9.2",
		"W3": "3.3",
		"\"PPR Pts\"": "14.1",
		"\"PPR Pts/G\"": "4.7"
	},
	{
		"Player": "\"Xavier Legette\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "3",
		"W1": "7.5",
		"W2": "0.0",
		"W3": "6.2",
		"\"PPR Pts\"": "13.7",
		"\"PPR Pts/G\"": "4.6"
	},
	{
		"Player": "\"Darius Slayton\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "3",
		"W1": "5.6",
		"W2": "6.3",
		"W3": "1.7",
		"\"PPR Pts\"": "13.6",
		"\"PPR Pts/G\"": "4.5"
	},
	{
		"Player": "\"Mack Hollins\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "3",
		"W1": "10.5",
		"W2": "0.0",
		"W3": "2.6",
		"\"PPR Pts\"": "13.1",
		"\"PPR Pts/G\"": "4.4"
	},
	{
		"Player": "\"DeAndre Carter\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "3",
		"W1": "1.6",
		"W2": "6.2",
		"W3": "5.2",
		"\"PPR Pts\"": "13.0",
		"\"PPR Pts/G\"": "4.3"
	},
	{
		"Player": "\"Luke McCaffrey\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "3",
		"W1": "4.8",
		"W2": "0.0",
		"W3": "7.4",
		"\"PPR Pts\"": "12.2",
		"\"PPR Pts/G\"": "4.1"
	},
	{
		"Player": "\"Devaughn Vele\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "1",
		"W1": "11.9",
		"W2": "-",
		"W3": "-",
		"\"PPR Pts\"": "11.9",
		"\"PPR Pts/G\"": "11.9"
	},
	{
		"Player": "\"Dontayvion Wicks\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "3",
		"W1": "0.0",
		"W2": "11.6",
		"W3": "0.0",
		"\"PPR Pts\"": "11.6",
		"\"PPR Pts/G\"": "3.9"
	},
	{
		"Player": "\"Nelson Agholor\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "3",
		"W1": "1.6",
		"W2": "2.3",
		"W3": "6.6",
		"\"PPR Pts\"": "10.5",
		"\"PPR Pts/G\"": "3.5"
	},
	{
		"Player": "\"Britain Covey\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "3",
		"W1": "0.0",
		"W2": "8.3",
		"W3": "2.1",
		"\"PPR Pts\"": "10.4",
		"\"PPR Pts/G\"": "3.5"
	},
	{
		"Player": "\"Jonathan Mingo\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "3",
		"W1": "4.3",
		"W2": "1.1",
		"W3": "5.0",
		"\"PPR Pts\"": "10.4",
		"\"PPR Pts/G\"": "3.5"
	},
	{
		"Player": "\"Curtis Samuel\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "3",
		"W1": "3.5",
		"W2": "1.3",
		"W3": "5.2",
		"\"PPR Pts\"": "10.0",
		"\"PPR Pts/G\"": "3.3"
	},
	{
		"Player": "\"Justin Watson\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "3",
		"W1": "3.5",
		"W2": "4.2",
		"W3": "2.3",
		"\"PPR Pts\"": "10.0",
		"\"PPR Pts/G\"": "3.3"
	},
	{
		"Player": "\"Jordan Whittington\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "3",
		"W1": "0.0",
		"W2": "4.2",
		"W3": "5.8",
		"\"PPR Pts\"": "10.0",
		"\"PPR Pts/G\"": "3.3"
	},
	{
		"Player": "\"JuJu Smith-Schuster\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "3",
		"W1": "0.0",
		"W2": "0.0",
		"W3": "9.7",
		"\"PPR Pts\"": "9.7",
		"\"PPR Pts/G\"": "3.2"
	},
	{
		"Player": "\"Mike Williams\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "3",
		"W1": "0.0",
		"W2": "2.9",
		"W3": "6.4",
		"\"PPR Pts\"": "9.3",
		"\"PPR Pts/G\"": "3.1"
	},
	{
		"Player": "\"Jalen Brooks\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "3",
		"W1": "2.8",
		"W2": "2.0",
		"W3": "3.4",
		"\"PPR Pts\"": "8.2",
		"\"PPR Pts/G\"": "2.7"
	},
	{
		"Player": "\"Puka Nacua\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "1",
		"W1": "8.2",
		"W2": "-",
		"W3": "-",
		"\"PPR Pts\"": "8.2",
		"\"PPR Pts/G\"": "8.2"
	},
	{
		"Player": "\"Joshua Palmer\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "2",
		"W1": "3.5",
		"W2": "3.9",
		"W3": "-",
		"\"PPR Pts\"": "7.4",
		"\"PPR Pts/G\"": "3.7"
	},
	{
		"Player": "\"Dyami Brown\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "3",
		"W1": "0.0",
		"W2": "3.7",
		"W3": "3.6",
		"\"PPR Pts\"": "7.3",
		"\"PPR Pts/G\"": "2.4"
	},
	{
		"Player": "\"Keenan Allen\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "1",
		"W1": "6.9",
		"W2": "-",
		"W3": "-",
		"\"PPR Pts\"": "6.9",
		"\"PPR Pts/G\"": "6.9"
	},
	{
		"Player": "\"Tee Higgins\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "1",
		"W1": "-",
		"W2": "-",
		"W3": "6.9",
		"\"PPR Pts\"": "6.9",
		"\"PPR Pts/G\"": "6.9"
	},
	{
		"Player": "\"Kalif Raymond\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "3",
		"W1": "1.2",
		"W2": "5.7",
		"W3": "0.0",
		"\"PPR Pts\"": "6.9",
		"\"PPR Pts/G\"": "2.3"
	},
	{
		"Player": "\"Olamide Zaccheaus\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "3",
		"W1": "2.5",
		"W2": "4.4",
		"W3": "0.0",
		"\"PPR Pts\"": "6.9",
		"\"PPR Pts/G\"": "2.3"
	},
	{
		"Player": "\"K.J. Osborn\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "3",
		"W1": "5.1",
		"W2": "1.7",
		"W3": "0.0",
		"\"PPR Pts\"": "6.8",
		"\"PPR Pts/G\"": "2.3"
	},
	{
		"Player": "\"Jordan Addison\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "1",
		"W1": "6.5",
		"W2": "-",
		"W3": "-",
		"\"PPR Pts\"": "6.5",
		"\"PPR Pts/G\"": "6.5"
	},
	{
		"Player": "\"Brandon Powell\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "3",
		"W1": "0.0",
		"W2": "3.6",
		"W3": "2.3",
		"\"PPR Pts\"": "5.9",
		"\"PPR Pts/G\"": "2.0"
	},
	{
		"Player": "\"David Bell\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "1",
		"W1": "-",
		"W2": "5.7",
		"W3": "-",
		"\"PPR Pts\"": "5.7",
		"\"PPR Pts/G\"": "5.7"
	},
	{
		"Player": "\"Jermaine Burton\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "3",
		"W1": "0.0",
		"W2": "5.7",
		"W3": "0.0",
		"\"PPR Pts\"": "5.7",
		"\"PPR Pts/G\"": "1.9"
	},
	{
		"Player": "\"Josh Downs\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "1",
		"W1": "-",
		"W2": "-",
		"W3": "5.2",
		"\"PPR Pts\"": "5.2",
		"\"PPR Pts/G\"": "5.2"
	},
	{
		"Player": "\"Adonai Mitchell\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "3",
		"W1": "1.2",
		"W2": "4.0",
		"W3": "0.0",
		"\"PPR Pts\"": "5.2",
		"\"PPR Pts/G\"": "1.7"
	},
	{
		"Player": "\"Scott Miller\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "3",
		"W1": "0.0",
		"W2": "0.0",
		"W3": "5.1",
		"\"PPR Pts\"": "5.1",
		"\"PPR Pts/G\"": "1.7"
	},
	{
		"Player": "\"Parker Washington\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "3",
		"W1": "1.3",
		"W2": "0.0",
		"W3": "3.8",
		"\"PPR Pts\"": "5.1",
		"\"PPR Pts/G\"": "1.7"
	},
	{
		"Player": "\"Tim Patrick\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "2",
		"W1": "-",
		"W2": "3.2",
		"W3": "1.8",
		"\"PPR Pts\"": "5.0",
		"\"PPR Pts/G\"": "2.5"
	},
	{
		"Player": "\"Tyquan Thornton\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "3",
		"W1": "4.7",
		"W2": "0.0",
		"W3": "0.0",
		"\"PPR Pts\"": "4.7",
		"\"PPR Pts/G\"": "1.6"
	},
	{
		"Player": "\"Mason Tipton\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "3",
		"W1": "1.6",
		"W2": "0.0",
		"W3": "3.1",
		"\"PPR Pts\"": "4.7",
		"\"PPR Pts/G\"": "1.6"
	},
	{
		"Player": "\"Marquez Valdes-Scantling\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "3",
		"W1": "2.9",
		"W2": "0.0",
		"W3": "1.7",
		"\"PPR Pts\"": "4.6",
		"\"PPR Pts/G\"": "1.5"
	},
	{
		"Player": "\"Van Jefferson\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "3",
		"W1": "1.1",
		"W2": "3.4",
		"W3": "0.0",
		"\"PPR Pts\"": "4.5",
		"\"PPR Pts/G\"": "1.5"
	},
	{
		"Player": "\"Trent Sherfield\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "3",
		"W1": "0.0",
		"W2": "2.7",
		"W3": "1.8",
		"\"PPR Pts\"": "4.5",
		"\"PPR Pts/G\"": "1.5"
	},
	{
		"Player": "\"Jahan Dotson\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "3",
		"W1": "0.0",
		"W2": "1.6",
		"W3": "2.8",
		"\"PPR Pts\"": "4.4",
		"\"PPR Pts/G\"": "1.5"
	},
	{
		"Player": "\"D'Wayne Eskridge\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "1",
		"W1": "-",
		"W2": "-",
		"W3": "4.0",
		"\"PPR Pts\"": "4.0",
		"\"PPR Pts/G\"": "4.0"
	},
	{
		"Player": "\"Laviska Shenault\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "3",
		"W1": "1.1",
		"W2": "1.6",
		"W3": "1.2",
		"\"PPR Pts\"": "3.9",
		"\"PPR Pts/G\"": "1.3"
	},
	{
		"Player": "\"Marvin Mims\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "3",
		"W1": "0.0",
		"W2": "2.0",
		"W3": "1.9",
		"\"PPR Pts\"": "3.9",
		"\"PPR Pts/G\"": "1.3"
	},
	{
		"Player": "\"Cedric Tillman\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "3",
		"W1": "1.3",
		"W2": "1.2",
		"W3": "1.4",
		"\"PPR Pts\"": "3.9",
		"\"PPR Pts/G\"": "1.3"
	},
	{
		"Player": "\"Robert Woods\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "3",
		"W1": "0.0",
		"W2": "0.0",
		"W3": "3.8",
		"\"PPR Pts\"": "3.8",
		"\"PPR Pts/G\"": "1.3"
	},
	{
		"Player": "\"Xavier Gipson\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "3",
		"W1": "0.0",
		"W2": "0.0",
		"W3": "3.6",
		"\"PPR Pts\"": "3.6",
		"\"PPR Pts/G\"": "1.2"
	},
	{
		"Player": "\"Jake Bobo\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "3",
		"W1": "0.0",
		"W2": "3.5",
		"W3": "0.0",
		"\"PPR Pts\"": "3.5",
		"\"PPR Pts/G\"": "1.2"
	},
	{
		"Player": "\"Parris Campbell\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "1",
		"W1": "-",
		"W2": "-",
		"W3": "3.3",
		"\"PPR Pts\"": "3.3",
		"\"PPR Pts/G\"": "3.3"
	},
	{
		"Player": "\"Treylon Burks\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "3",
		"W1": "1.3",
		"W2": "0.0",
		"W3": "1.9",
		"\"PPR Pts\"": "3.2",
		"\"PPR Pts/G\"": "1.1"
	},
	{
		"Player": "\"Troy Franklin\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "2",
		"W1": "-",
		"W2": "0.0",
		"W3": "3.1",
		"\"PPR Pts\"": "3.1",
		"\"PPR Pts/G\"": "1.6"
	},
	{
		"Player": "\"Trenton Irwin\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "2",
		"W1": "1.6",
		"W2": "1.5",
		"W3": "-",
		"\"PPR Pts\"": "3.1",
		"\"PPR Pts/G\"": "1.6"
	},
	{
		"Player": "\"Velus Jones\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "1",
		"W1": "2.9",
		"W2": "-",
		"W3": "-",
		"\"PPR Pts\"": "2.9",
		"\"PPR Pts/G\"": "2.9"
	},
	{
		"Player": "\"Trey Palmer\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "3",
		"W1": "2.9",
		"W2": "0.0",
		"W3": "0.0",
		"\"PPR Pts\"": "2.9",
		"\"PPR Pts/G\"": "1.0"
	},
	{
		"Player": "\"Simi Fehoko\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "3",
		"W1": "0.0",
		"W2": "0.0",
		"W3": "2.7",
		"\"PPR Pts\"": "2.7",
		"\"PPR Pts/G\"": "0.9"
	},
	{
		"Player": "\"David Moore\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "3",
		"W1": "2.4",
		"W2": "0.0",
		"W3": "0.0",
		"\"PPR Pts\"": "2.4",
		"\"PPR Pts/G\"": "0.8"
	},
	{
		"Player": "\"Ronnie Bell\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "3",
		"W1": "0.0",
		"W2": "0.0",
		"W3": "2.2",
		"\"PPR Pts\"": "2.2",
		"\"PPR Pts/G\"": "0.7"
	},
	{
		"Player": "\"DJ Turner\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "3",
		"W1": "1.9",
		"W2": "0.2",
		"W3": "0.0",
		"\"PPR Pts\"": "2.1",
		"\"PPR Pts/G\"": "0.7"
	},
	{
		"Player": "\"Johnny Wilson\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "3",
		"W1": "0.0",
		"W2": "0.0",
		"W3": "1.9",
		"\"PPR Pts\"": "1.9",
		"\"PPR Pts/G\"": "0.6"
	},
	{
		"Player": "\"Derius Davis\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "3",
		"W1": "0.9",
		"W2": "0.0",
		"W3": "0.8",
		"\"PPR Pts\"": "1.7",
		"\"PPR Pts/G\"": "0.6"
	},
	{
		"Player": "\"Devin Duvernay\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "3",
		"W1": "0.3",
		"W2": "0.4",
		"W3": "0.9",
		"\"PPR Pts\"": "1.6",
		"\"PPR Pts/G\"": "0.5"
	},
	{
		"Player": "\"Robbie Chosen\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "2",
		"W1": "0.0",
		"W2": "1.5",
		"W3": "-",
		"\"PPR Pts\"": "1.5",
		"\"PPR Pts/G\"": "0.8"
	},
	{
		"Player": "\"Jamison Crowder\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "2",
		"W1": "1.5",
		"W2": "-",
		"W3": "0.0",
		"\"PPR Pts\"": "1.5",
		"\"PPR Pts/G\"": "0.8"
	},
	{
		"Player": "\"Chris Conley\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "3",
		"W1": "0.0",
		"W2": "1.4",
		"W3": "0.0",
		"\"PPR Pts\"": "1.4",
		"\"PPR Pts/G\"": "0.5"
	},
	{
		"Player": "\"Malachi Corley\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "2",
		"W1": "0.0",
		"W2": "1.4",
		"W3": "0.0",
		"\"PPR Pts\"": "1.4",
		"\"PPR Pts/G\"": "0.7"
	},
	{
		"Player": "\"Xavier Hutchinson\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "3",
		"W1": "1.3",
		"W2": "0.0",
		"W3": "0.0",
		"\"PPR Pts\"": "1.3",
		"\"PPR Pts/G\"": "0.4"
	},
	{
		"Player": "\"Cedrick Wilson\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "3",
		"W1": "0.0",
		"W2": "0.0",
		"W3": "1.3",
		"\"PPR Pts\"": "1.3",
		"\"PPR Pts/G\"": "0.4"
	},
	{
		"Player": "\"Kayshon Boutte\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "1",
		"W1": "-",
		"W2": "-",
		"W3": "1.2",
		"\"PPR Pts\"": "1.2",
		"\"PPR Pts/G\"": "1.2"
	},
	{
		"Player": "\"Bo Melton\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "3",
		"W1": "0.0",
		"W2": "0.8",
		"W3": "0.0",
		"\"PPR Pts\"": "0.8",
		"\"PPR Pts/G\"": "0.3"
	},
	
]

module.exports = wr4for4FantasyPointsBrowserLastFiveWeeks;