const wr4for4PlayerTargetsAppLastFiveWeeks = 
[
	{
		"Player": "\"Puka Nacua\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "5",
		"W1": "15",
		"W2": "20",
		"W3": "7",
		"W4": "10",
		"W5": "11",
		"TGTs": "63",
		"TGTs/G": "12.6",
		"Array": "19.7%"
	},
	{
		"Player": "\"Ja'Marr Chase\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "5",
		"W1": "9",
		"W2": "8",
		"W3": "15",
		"W4": "9",
		"W5": "19",
		"TGTs": "60",
		"TGTs/G": "12.0",
		"Array": "19.2%"
	},
	{
		"Player": "\"Davante Adams\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "5",
		"W1": "9",
		"W2": "8",
		"W3": "20",
		"W4": "13",
		"W5": "4",
		"TGTs": "54",
		"TGTs/G": "10.8",
		"Array": "19.1%"
	},
	{
		"Player": "\"Justin Jefferson\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "5",
		"W1": "12",
		"W2": "13",
		"W3": "13",
		"W4": "9",
		"W5": "6",
		"TGTs": "53",
		"TGTs/G": "10.6",
		"Array": "17.8%"
	},
	{
		"Player": "\"A.J. Brown\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "5",
		"W1": "10",
		"W2": "6",
		"W3": "14",
		"W4": "13",
		"W5": "8",
		"TGTs": "51",
		"TGTs/G": "10.2",
		"Array": "14.7%"
	},
	{
		"Player": "\"Stefon Diggs\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "5",
		"W1": "13",
		"W2": "7",
		"W3": "12",
		"W4": "7",
		"W5": "11",
		"TGTs": "50",
		"TGTs/G": "10.0",
		"Array": "18.7%"
	},
	{
		"Player": "\"Tyreek Hill\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "5",
		"W1": "15",
		"W2": "9",
		"W3": "11",
		"W4": "5",
		"W5": "9",
		"TGTs": "49",
		"TGTs/G": "9.8",
		"Array": "23.4%"
	},
	{
		"Player": "\"Michael Pittman Jr.\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "5",
		"W1": "11",
		"W2": "12",
		"W3": "11",
		"W4": "5",
		"W5": "7",
		"TGTs": "46",
		"TGTs/G": "9.2",
		"Array": "13.6%"
	},
	{
		"Player": "\"Adam Thielen\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "5",
		"W1": "2",
		"W2": "9",
		"W3": "14",
		"W4": "8",
		"W5": "13",
		"TGTs": "46",
		"TGTs/G": "9.2",
		"Array": "14.1%"
	},
	{
		"Player": "\"Keenan Allen\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "4",
		"W1": "9",
		"W2": "10",
		"W3": "20",
		"W4": "5",
		"W5": "-",
		"TGTs": "44",
		"TGTs/G": "11.0",
		"Array": "17.9%"
	},
	{
		"Player": "\"Christian Kirk\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "5",
		"W1": "3",
		"W2": "14",
		"W3": "6",
		"W4": "12",
		"W5": "8",
		"TGTs": "43",
		"TGTs/G": "8.6",
		"Array": "15.1%"
	},
	{
		"Player": "\"Chris Olave\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "5",
		"W1": "10",
		"W2": "11",
		"W3": "11",
		"W4": "6",
		"W5": "5",
		"TGTs": "43",
		"TGTs/G": "8.6",
		"Array": "15.9%"
	},
	{
		"Player": "\"Garrett Wilson\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "5",
		"W1": "5",
		"W2": "8",
		"W3": "9",
		"W4": "14",
		"W5": "7",
		"TGTs": "43",
		"TGTs/G": "8.6",
		"Array": "16.3%"
	},
	{
		"Player": "\"Marquise Brown\"",
		"Pos": "WR",
		"Team": "ARI",
		"G": "5",
		"W1": "5",
		"W2": "10",
		"W3": "7",
		"W4": "10",
		"W5": "10",
		"TGTs": "42",
		"TGTs/G": "8.4",
		"Array": "14.5%"
	},
	{
		"Player": "\"DeAndre Hopkins\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "5",
		"W1": "13",
		"W2": "5",
		"W3": "7",
		"W4": "6",
		"W5": "11",
		"TGTs": "42",
		"TGTs/G": "8.4",
		"Array": "20.2%"
	},
	{
		"Player": "\"Tutu Atwell\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "5",
		"W1": "8",
		"W2": "9",
		"W3": "9",
		"W4": "9",
		"W5": "5",
		"TGTs": "40",
		"TGTs/G": "8.0",
		"Array": "13.3%"
	},
	{
		"Player": "\"Zay Flowers\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "5",
		"W1": "10",
		"W2": "5",
		"W3": "10",
		"W4": "4",
		"W5": "11",
		"TGTs": "40",
		"TGTs/G": "8.0",
		"Array": "13.1%"
	},
	{
		"Player": "\"George Pickens\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "5",
		"W1": "7",
		"W2": "10",
		"W3": "6",
		"W4": "7",
		"W5": "10",
		"TGTs": "40",
		"TGTs/G": "8.0",
		"Array": "14.7%"
	},
	{
		"Player": "\"Robert Woods\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "5",
		"W1": "10",
		"W2": "9",
		"W3": "6",
		"W4": "6",
		"W5": "9",
		"TGTs": "40",
		"TGTs/G": "8.0",
		"Array": "15.2%"
	},
	{
		"Player": "\"Michael Thomas\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "5",
		"W1": "8",
		"W2": "9",
		"W3": "9",
		"W4": "6",
		"W5": "7",
		"TGTs": "39",
		"TGTs/G": "7.8",
		"Array": "14.9%"
	},
	{
		"Player": "\"Romeo Doubs\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "5",
		"W1": "5",
		"W2": "3",
		"W3": "12",
		"W4": "13",
		"W5": "4",
		"TGTs": "37",
		"TGTs/G": "7.4",
		"Array": "15.7%"
	},
	{
		"Player": "\"Nico Collins\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "5",
		"W1": "11",
		"W2": "9",
		"W3": "3",
		"W4": "9",
		"W5": "4",
		"TGTs": "36",
		"TGTs/G": "7.2",
		"Array": "14.5%"
	},
	{
		"Player": "\"Jakobi Meyers\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "4",
		"W1": "10",
		"W2": "-",
		"W3": "12",
		"W4": "4",
		"W5": "10",
		"TGTs": "36",
		"TGTs/G": "9.0",
		"Array": "15.0%"
	},
	{
		"Player": "\"Calvin Ridley\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "5",
		"W1": "11",
		"W2": "8",
		"W3": "7",
		"W4": "2",
		"W5": "8",
		"TGTs": "36",
		"TGTs/G": "7.2",
		"Array": "12.1%"
	},
	{
		"Player": "\"CeeDee Lamb\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "5",
		"W1": "4",
		"W2": "13",
		"W3": "7",
		"W4": "6",
		"W5": "5",
		"TGTs": "35",
		"TGTs/G": "7.0",
		"Array": "13.8%"
	},
	{
		"Player": "\"Amon-Ra St. Brown\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "4",
		"W1": "9",
		"W2": "7",
		"W3": "12",
		"W4": "7",
		"W5": "-",
		"TGTs": "35",
		"TGTs/G": "8.8",
		"Array": "14.2%"
	},
	{
		"Player": "\"Tyler Boyd\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "5",
		"W1": "3",
		"W2": "8",
		"W3": "9",
		"W4": "7",
		"W5": "7",
		"TGTs": "34",
		"TGTs/G": "6.8",
		"Array": "12.6%"
	},
	{
		"Player": "\"D.J. Moore\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "5",
		"W1": "2",
		"W2": "7",
		"W3": "6",
		"W4": "9",
		"W5": "10",
		"TGTs": "34",
		"TGTs/G": "6.8",
		"Array": "11.7%"
	},
	{
		"Player": "\"DeVonta Smith\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "5",
		"W1": "10",
		"W2": "5",
		"W3": "5",
		"W4": "9",
		"W5": "5",
		"TGTs": "34",
		"TGTs/G": "6.8",
		"Array": "9.3%"
	},
	{
		"Player": "\"Kendrick Bourne\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "5",
		"W1": "11",
		"W2": "9",
		"W3": "5",
		"W4": "3",
		"W5": "5",
		"TGTs": "33",
		"TGTs/G": "6.6",
		"Array": "14.5%"
	},
	{
		"Player": "\"Josh Downs\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "5",
		"W1": "7",
		"W2": "5",
		"W3": "12",
		"W4": "3",
		"W5": "6",
		"TGTs": "33",
		"TGTs/G": "6.6",
		"Array": "12.6%"
	},
	{
		"Player": "\"Tee Higgins\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "4",
		"W1": "8",
		"W2": "12",
		"W3": "8",
		"W4": "4",
		"W5": "-",
		"TGTs": "32",
		"TGTs/G": "8.0",
		"Array": "16.1%"
	},
	{
		"Player": "\"Amari Cooper\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "4",
		"W1": "7",
		"W2": "10",
		"W3": "8",
		"W4": "6",
		"W5": "-",
		"TGTs": "31",
		"TGTs/G": "7.8",
		"Array": "14.0%"
	},
	{
		"Player": "\"Mike Evans\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "4",
		"W1": "10",
		"W2": "8",
		"W3": "10",
		"W4": "3",
		"W5": "-",
		"TGTs": "31",
		"TGTs/G": "7.8",
		"Array": "18.9%"
	},
	{
		"Player": "\"Drake London\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "5",
		"W1": "1",
		"W2": "8",
		"W3": "6",
		"W4": "7",
		"W5": "9",
		"TGTs": "31",
		"TGTs/G": "6.2",
		"Array": "10.6%"
	},
	{
		"Player": "\"Terry McLaurin\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "5",
		"W1": "4",
		"W2": "6",
		"W3": "6",
		"W4": "10",
		"W5": "5",
		"TGTs": "31",
		"TGTs/G": "6.2",
		"Array": "11.0%"
	},
	{
		"Player": "\"Deebo Samuel\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "5",
		"W1": "7",
		"W2": "9",
		"W3": "12",
		"W4": "0",
		"W5": "3",
		"TGTs": "31",
		"TGTs/G": "6.2",
		"Array": "11.2%"
	},
	{
		"Player": "\"Courtland Sutton\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "5",
		"W1": "5",
		"W2": "7",
		"W3": "11",
		"W4": "5",
		"W5": "3",
		"TGTs": "31",
		"TGTs/G": "6.2",
		"Array": "11.6%"
	},
	{
		"Player": "\"Jahan Dotson\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "5",
		"W1": "7",
		"W2": "5",
		"W3": "4",
		"W4": "9",
		"W5": "5",
		"TGTs": "30",
		"TGTs/G": "6.0",
		"Array": "10.5%"
	},
	{
		"Player": "\"Chris Godwin\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "4",
		"W1": "6",
		"W2": "8",
		"W3": "5",
		"W4": "11",
		"W5": "-",
		"TGTs": "30",
		"TGTs/G": "7.5",
		"Array": "14.6%"
	},
	{
		"Player": "\"Jordan Addison\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "5",
		"W1": "6",
		"W2": "5",
		"W3": "8",
		"W4": "1",
		"W5": "9",
		"TGTs": "29",
		"TGTs/G": "5.8",
		"Array": "13.4%"
	},
	{
		"Player": "\"Elijah Moore\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "4",
		"W1": "7",
		"W2": "9",
		"W3": "9",
		"W4": "4",
		"W5": "-",
		"TGTs": "29",
		"TGTs/G": "7.3",
		"Array": "12.7%"
	},
	{
		"Player": "\"Tank Dell\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "5",
		"W1": "4",
		"W2": "10",
		"W3": "7",
		"W4": "3",
		"W5": "4",
		"TGTs": "28",
		"TGTs/G": "5.6",
		"Array": "13.5%"
	},
	{
		"Player": "\"Brandon Aiyuk\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "4",
		"W1": "8",
		"W2": "6",
		"W3": "-",
		"W4": "6",
		"W5": "7",
		"TGTs": "27",
		"TGTs/G": "6.8",
		"Array": "14.5%"
	},
	{
		"Player": "\"Tyler Lockett\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "4",
		"W1": "4",
		"W2": "10",
		"W3": "7",
		"W4": "6",
		"W5": "-",
		"TGTs": "27",
		"TGTs/G": "6.8",
		"Array": "13.2%"
	},
	{
		"Player": "\"Jayden Reed\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "5",
		"W1": "5",
		"W2": "8",
		"W3": "7",
		"W4": "5",
		"W5": "2",
		"TGTs": "27",
		"TGTs/G": "5.4",
		"Array": "15.1%"
	},
	{
		"Player": "\"Curtis Samuel\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "5",
		"W1": "5",
		"W2": "3",
		"W3": "4",
		"W4": "8",
		"W5": "7",
		"TGTs": "27",
		"TGTs/G": "5.4",
		"Array": "11.5%"
	},
	{
		"Player": "\"Gabe Davis\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "5",
		"W1": "4",
		"W2": "7",
		"W3": "4",
		"W4": "3",
		"W5": "8",
		"TGTs": "26",
		"TGTs/G": "5.2",
		"Array": "9.6%"
	},
	{
		"Player": "\"Jonathan Mingo\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "4",
		"W1": "5",
		"W2": "8",
		"W3": "6",
		"W4": "-",
		"W5": "7",
		"TGTs": "26",
		"TGTs/G": "6.5",
		"Array": "12.2%"
	},
	{
		"Player": "\"K.J. Osborn\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "5",
		"W1": "6",
		"W2": "6",
		"W3": "3",
		"W4": "2",
		"W5": "9",
		"TGTs": "26",
		"TGTs/G": "5.2",
		"Array": "8.8%"
	},
	{
		"Player": "\"Allen Robinson\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "5",
		"W1": "8",
		"W2": "3",
		"W3": "4",
		"W4": "2",
		"W5": "9",
		"TGTs": "26",
		"TGTs/G": "5.2",
		"Array": "10.0%"
	},
	{
		"Player": "\"Jaylen Waddle\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "4",
		"W1": "5",
		"W2": "6",
		"W3": "-",
		"W4": "5",
		"W5": "10",
		"TGTs": "26",
		"TGTs/G": "6.5",
		"Array": "14.3%"
	},
	{
		"Player": "\"Mike Williams\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "3",
		"W1": "5",
		"W2": "13",
		"W3": "8",
		"W4": "-",
		"W5": "-",
		"TGTs": "26",
		"TGTs/G": "8.7",
		"Array": "15.6%"
	},
	{
		"Player": "\"JuJu Smith-Schuster\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "5",
		"W1": "7",
		"W2": "6",
		"W3": "3",
		"W4": "5",
		"W5": "4",
		"TGTs": "25",
		"TGTs/G": "5.0",
		"Array": "13.0%"
	},
	{
		"Player": "\"Jerry Jeudy\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "4",
		"W1": "-",
		"W2": "5",
		"W3": "7",
		"W4": "5",
		"W5": "7",
		"TGTs": "24",
		"TGTs/G": "6.0",
		"Array": "13.6%"
	},
	{
		"Player": "\"Terrace Marshall\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "4",
		"W1": "6",
		"W2": "0",
		"W3": "8",
		"W4": "10",
		"W5": "-",
		"TGTs": "24",
		"TGTs/G": "6.0",
		"Array": "13.1%"
	},
	{
		"Player": "\"Josh Reynolds\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "5",
		"W1": "7",
		"W2": "6",
		"W3": "0",
		"W4": "6",
		"W5": "5",
		"TGTs": "24",
		"TGTs/G": "4.8",
		"Array": "10.0%"
	},
	{
		"Player": "\"Rashee Rice\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "5",
		"W1": "5",
		"W2": "2",
		"W3": "7",
		"W4": "5",
		"W5": "5",
		"TGTs": "24",
		"TGTs/G": "4.8",
		"Array": "19.5%"
	},
	{
		"Player": "\"Darius Slayton\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "5",
		"W1": "5",
		"W2": "6",
		"W3": "6",
		"W4": "3",
		"W5": "4",
		"TGTs": "24",
		"TGTs/G": "4.8",
		"Array": "9.2%"
	},
	{
		"Player": "\"Parris Campbell\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "5",
		"W1": "4",
		"W2": "6",
		"W3": "6",
		"W4": "5",
		"W5": "2",
		"TGTs": "23",
		"TGTs/G": "4.6",
		"Array": "15.1%"
	},
	{
		"Player": "\"DK Metcalf\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "4",
		"W1": "5",
		"W2": "6",
		"W3": "8",
		"W4": "4",
		"W5": "-",
		"TGTs": "23",
		"TGTs/G": "5.8",
		"Array": "11.4%"
	},
	{
		"Player": "\"Calvin Austin III\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "5",
		"W1": "6",
		"W2": "4",
		"W3": "6",
		"W4": "5",
		"W5": "1",
		"TGTs": "22",
		"TGTs/G": "4.4",
		"Array": "10.4%"
	},
	{
		"Player": "\"Michael Gallup\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "5",
		"W1": "2",
		"W2": "2",
		"W3": "7",
		"W4": "6",
		"W5": "5",
		"TGTs": "22",
		"TGTs/G": "4.4",
		"Array": "9.4%"
	},
	{
		"Player": "\"D.J. Chark\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "4",
		"W1": "-",
		"W2": "1",
		"W3": "11",
		"W4": "3",
		"W5": "6",
		"TGTs": "21",
		"TGTs/G": "5.3",
		"Array": "8.5%"
	},
	{
		"Player": "\"Joshua Palmer\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "4",
		"W1": "1",
		"W2": "5",
		"W3": "7",
		"W4": "8",
		"W5": "-",
		"TGTs": "21",
		"TGTs/G": "5.3",
		"Array": "11.4%"
	},
	{
		"Player": "\"Rashid Shaheed\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "5",
		"W1": "6",
		"W2": "4",
		"W3": "2",
		"W4": "7",
		"W5": "2",
		"TGTs": "21",
		"TGTs/G": "4.2",
		"Array": "10.7%"
	},
	{
		"Player": "\"Allen Lazard\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "5",
		"W1": "4",
		"W2": "4",
		"W3": "5",
		"W4": "3",
		"W5": "4",
		"TGTs": "20",
		"TGTs/G": "4.0",
		"Array": "7.8%"
	},
	{
		"Player": "\"Jaxon Smith-Njigba\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "4",
		"W1": "5",
		"W2": "6",
		"W3": "3",
		"W4": "6",
		"W5": "-",
		"TGTs": "20",
		"TGTs/G": "5.0",
		"Array": "15.2%"
	},
	{
		"Player": "\"Brandin Cooks\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "4",
		"W1": "4",
		"W2": "-",
		"W3": "7",
		"W4": "4",
		"W5": "4",
		"TGTs": "19",
		"TGTs/G": "4.8",
		"Array": "10.6%"
	},
	{
		"Player": "\"Mack Hollins\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "5",
		"W1": "4",
		"W2": "6",
		"W3": "4",
		"W4": "3",
		"W5": "2",
		"TGTs": "19",
		"TGTs/G": "3.8",
		"Array": "8.8%"
	},
	{
		"Player": "\"DeVante Parker\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "4",
		"W1": "-",
		"W2": "8",
		"W3": "3",
		"W4": "4",
		"W5": "4",
		"TGTs": "19",
		"TGTs/G": "4.8",
		"Array": "8.4%"
	},
	{
		"Player": "\"Kadarius Toney\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "5",
		"W1": "5",
		"W2": "5",
		"W3": "1",
		"W4": "2",
		"W5": "6",
		"TGTs": "19",
		"TGTs/G": "3.8",
		"Array": "24.1%"
	},
	{
		"Player": "\"Nick Westbrook-Ikhine\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "5",
		"W1": "7",
		"W2": "3",
		"W3": "0",
		"W4": "6",
		"W5": "3",
		"TGTs": "19",
		"TGTs/G": "3.8",
		"Array": "8.2%"
	},
	{
		"Player": "\"Braxton Berrios\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "5",
		"W1": "5",
		"W2": "3",
		"W3": "2",
		"W4": "6",
		"W5": "2",
		"TGTs": "18",
		"TGTs/G": "3.6",
		"Array": "12.4%"
	},
	{
		"Player": "\"Zay Jones\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "3",
		"W1": "7",
		"W2": "6",
		"W3": "-",
		"W4": "-",
		"W5": "5",
		"TGTs": "18",
		"TGTs/G": "6.0",
		"Array": "12.5%"
	},
	{
		"Player": "\"Michael Wilson\"",
		"Pos": "WR",
		"Team": "ARI",
		"G": "5",
		"W1": "4",
		"W2": "3",
		"W3": "2",
		"W4": "7",
		"W5": "2",
		"TGTs": "18",
		"TGTs/G": "3.6",
		"Array": "8.3%"
	},
	{
		"Player": "\"Nelson Agholor\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "5",
		"W1": "0",
		"W2": "6",
		"W3": "4",
		"W4": "2",
		"W5": "5",
		"TGTs": "17",
		"TGTs/G": "3.4",
		"Array": "9.2%"
	},
	{
		"Player": "\"Demario Douglas\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "5",
		"W1": "7",
		"W2": "2",
		"W3": "3",
		"W4": "3",
		"W5": "2",
		"TGTs": "17",
		"TGTs/G": "3.4",
		"Array": "21.0%"
	},
	{
		"Player": "\"Rondale Moore\"",
		"Pos": "WR",
		"Team": "ARI",
		"G": "5",
		"W1": "3",
		"W2": "1",
		"W3": "6",
		"W4": "2",
		"W5": "5",
		"TGTs": "17",
		"TGTs/G": "3.4",
		"Array": "8.1%"
	},
	{
		"Player": "\"Skyy Moore\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "5",
		"W1": "3",
		"W2": "4",
		"W3": "6",
		"W4": "2",
		"W5": "2",
		"TGTs": "17",
		"TGTs/G": "3.4",
		"Array": "8.0%"
	},
	{
		"Player": "\"Wan'Dale Robinson\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "3",
		"W1": "-",
		"W2": "-",
		"W3": "5",
		"W4": "6",
		"W5": "6",
		"TGTs": "17",
		"TGTs/G": "5.7",
		"Array": "15.9%"
	},
	{
		"Player": "\"Darnell Mooney\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "5",
		"W1": "7",
		"W2": "0",
		"W3": "1",
		"W4": "4",
		"W5": "4",
		"TGTs": "16",
		"TGTs/G": "3.2",
		"Array": "7.4%"
	},
	{
		"Player": "\"Alec Pierce\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "5",
		"W1": "3",
		"W2": "2",
		"W3": "7",
		"W4": "2",
		"W5": "2",
		"TGTs": "16",
		"TGTs/G": "3.2",
		"Array": "4.9%"
	},
	{
		"Player": "\"Justin Watson\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "5",
		"W1": "4",
		"W2": "5",
		"W3": "3",
		"W4": "1",
		"W5": "3",
		"TGTs": "16",
		"TGTs/G": "3.2",
		"Array": "10.5%"
	},
	{
		"Player": "\"Van Jefferson\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "5",
		"W1": "5",
		"W2": "4",
		"W3": "3",
		"W4": "3",
		"W5": "0",
		"TGTs": "15",
		"TGTs/G": "3.0",
		"Array": "5.7%"
	},
	{
		"Player": "\"Chase Claypool\"",
		"Pos": "WR",
		"Team": "\"CHI",
		"G": " MIA\"",
		"W1": "3",
		"W2": "2",
		"W3": "8",
		"W4": "4",
		"W5": "-",
		"TGTs": "-",
		"TGTs/G": "14",
		"Array": "4.7"
	},
	{
		"Player": "\"Deonte Harty\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "5",
		"W1": "4",
		"W2": "3",
		"W3": "3",
		"W4": "2",
		"W5": "2",
		"TGTs": "14",
		"TGTs/G": "2.8",
		"Array": "19.2%"
	},
	{
		"Player": "\"Isaiah Hodgins\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "5",
		"W1": "3",
		"W2": "5",
		"W3": "1",
		"W4": "3",
		"W5": "2",
		"TGTs": "14",
		"TGTs/G": "2.8",
		"Array": "7.7%"
	},
	{
		"Player": "\"Donovan Peoples-Jones\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "4",
		"W1": "2",
		"W2": "4",
		"W3": "4",
		"W4": "4",
		"W5": "-",
		"TGTs": "14",
		"TGTs/G": "3.5",
		"Array": "5.2%"
	},
	{
		"Player": "\"Kalif Raymond\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "5",
		"W1": "1",
		"W2": "3",
		"W3": "6",
		"W4": "1",
		"W5": "3",
		"TGTs": "14",
		"TGTs/G": "2.8",
		"Array": "11.9%"
	},
	{
		"Player": "\"Dontayvion Wicks\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "5",
		"W1": "2",
		"W2": "4",
		"W3": "6",
		"W4": "1",
		"W5": "1",
		"TGTs": "14",
		"TGTs/G": "2.8",
		"Array": "8.8%"
	},
	{
		"Player": "\"Treylon Burks\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "3",
		"W1": "3",
		"W2": "4",
		"W3": "6",
		"W4": "-",
		"W5": "-",
		"TGTs": "13",
		"TGTs/G": "4.3",
		"Array": "9.6%"
	},
	{
		"Player": "\"Rashod Bateman\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "4",
		"W1": "3",
		"W2": "3",
		"W3": "3",
		"W4": "-",
		"W5": "3",
		"TGTs": "12",
		"TGTs/G": "3.0",
		"Array": "8.2%"
	},
	{
		"Player": "\"Cooper Kupp\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "1",
		"W1": "-",
		"W2": "-",
		"W3": "-",
		"W4": "-",
		"W5": "12",
		"TGTs": "12",
		"TGTs/G": "12.0",
		"Array": "22.6%"
	},
	{
		"Player": "\"Marvin Mims\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "5",
		"W1": "2",
		"W2": "2",
		"W3": "5",
		"W4": "2",
		"W5": "1",
		"TGTs": "12",
		"TGTs/G": "2.4",
		"Array": "14.1%"
	},
	{
		"Player": "\"Odell Beckham\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "3",
		"W1": "3",
		"W2": "4",
		"W3": "-",
		"W4": "-",
		"W5": "4",
		"TGTs": "11",
		"TGTs/G": "3.7",
		"Array": "8.1%"
	},
	{
		"Player": "\"Trenton Irwin\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "4",
		"W1": "0",
		"W2": "0",
		"W3": "-",
		"W4": "1",
		"W5": "10",
		"TGTs": "11",
		"TGTs/G": "2.8",
		"Array": "10.3%"
	},
	{
		"Player": "\"Brandon Johnson\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "5",
		"W1": "3",
		"W2": "3",
		"W3": "3",
		"W4": "1",
		"W5": "1",
		"TGTs": "11",
		"TGTs/G": "2.2",
		"Array": "7.4%"
	},
	{
		"Player": "\"Quentin Johnston\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "4",
		"W1": "3",
		"W2": "2",
		"W3": "3",
		"W4": "3",
		"W5": "-",
		"TGTs": "11",
		"TGTs/G": "2.8",
		"Array": "13.6%"
	},
	{
		"Player": "\"Deven Thompkins\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "4",
		"W1": "3",
		"W2": "0",
		"W3": "4",
		"W4": "4",
		"W5": "-",
		"TGTs": "11",
		"TGTs/G": "2.8",
		"Array": "10.5%"
	},
	{
		"Player": "\"Marquez Valdes-Scantling\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "5",
		"W1": "2",
		"W2": "3",
		"W3": "2",
		"W4": "2",
		"W5": "2",
		"TGTs": "11",
		"TGTs/G": "2.2",
		"Array": "5.0%"
	},
	{
		"Player": "\"Christian Watson\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "2",
		"W1": "-",
		"W2": "-",
		"W3": "-",
		"W4": "4",
		"W5": "7",
		"TGTs": "11",
		"TGTs/G": "5.5",
		"Array": "14.7%"
	},
	{
		"Player": "\"Dyami Brown\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "5",
		"W1": "0",
		"W2": "3",
		"W3": "1",
		"W4": "3",
		"W5": "3",
		"TGTs": "10",
		"TGTs/G": "2.0",
		"Array": "10.4%"
	},
	{
		"Player": "\"Randall Cobb\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "5",
		"W1": "1",
		"W2": "1",
		"W3": "2",
		"W4": "4",
		"W5": "1",
		"TGTs": "9",
		"TGTs/G": "1.8",
		"Array": "6.6%"
	},
	{
		"Player": "\"Marvin Jones\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "5",
		"W1": "6",
		"W2": "0",
		"W3": "0",
		"W4": "1",
		"W5": "2",
		"TGTs": "9",
		"TGTs/G": "1.8",
		"Array": "5.7%"
	},
	{
		"Player": "\"Trey Palmer\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "4",
		"W1": "3",
		"W2": "2",
		"W3": "1",
		"W4": "3",
		"W5": "-",
		"TGTs": "9",
		"TGTs/G": "2.3",
		"Array": "6.2%"
	},
	{
		"Player": "\"Hunter Renfrow\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "5",
		"W1": "0",
		"W2": "1",
		"W3": "2",
		"W4": "4",
		"W5": "2",
		"TGTs": "9",
		"TGTs/G": "1.8",
		"Array": "7.0%"
	},
	{
		"Player": "\"Jalen Tolbert\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "5",
		"W1": "1",
		"W2": "4",
		"W3": "0",
		"W4": "4",
		"W5": "0",
		"TGTs": "9",
		"TGTs/G": "1.8",
		"Array": "6.7%"
	},
	{
		"Player": "\"Samori Toure\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "5",
		"W1": "3",
		"W2": "2",
		"W3": "3",
		"W4": "1",
		"W5": "0",
		"TGTs": "9",
		"TGTs/G": "1.8",
		"Array": "9.9%"
	},
	{
		"Player": "\"River Cracraft\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "3",
		"W1": "5",
		"W2": "2",
		"W3": "1",
		"W4": "-",
		"W5": "-",
		"TGTs": "8",
		"TGTs/G": "2.7",
		"Array": "11.4%"
	},
	{
		"Player": "\"Jauan Jennings\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "4",
		"W1": "1",
		"W2": "3",
		"W3": "3",
		"W4": "-",
		"W5": "1",
		"TGTs": "8",
		"TGTs/G": "2.0",
		"Array": "7.5%"
	},
	{
		"Player": "\"Chris Moore\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "5",
		"W1": "1",
		"W2": "1",
		"W3": "3",
		"W4": "3",
		"W5": "0",
		"TGTs": "8",
		"TGTs/G": "1.6",
		"Array": "5.5%"
	},
	{
		"Player": "\"Devin Duvernay\"",
		"Pos": "WR",
		"Team": "BAL",
		"G": "5",
		"W1": "0",
		"W2": "3",
		"W3": "1",
		"W4": "2",
		"W5": "1",
		"TGTs": "7",
		"TGTs/G": "1.4",
		"Array": "8.0%"
	},
	{
		"Player": "\"John Metchie\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "4",
		"W1": "-",
		"W2": "1",
		"W3": "2",
		"W4": "2",
		"W5": "2",
		"TGTs": "7",
		"TGTs/G": "1.8",
		"Array": "10.0%"
	},
	{
		"Player": "\"Zach Pascal\"",
		"Pos": "WR",
		"Team": "ARI",
		"G": "5",
		"W1": "1",
		"W2": "1",
		"W3": "0",
		"W4": "4",
		"W5": "1",
		"TGTs": "7",
		"TGTs/G": "1.4",
		"Array": "9.6%"
	},
	{
		"Player": "\"Brandon Powell\"",
		"Pos": "WR",
		"Team": "MIN",
		"G": "3",
		"W1": "0",
		"W2": "0",
		"W3": "1",
		"W4": "0",
		"W5": "6",
		"TGTs": "7",
		"TGTs/G": "2.3",
		"Array": "25.9%"
	},
	{
		"Player": "\"Trent Sherfield\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "5",
		"W1": "0",
		"W2": "0",
		"W3": "3",
		"W4": "3",
		"W5": "1",
		"TGTs": "7",
		"TGTs/G": "1.4",
		"Array": "6.3%"
	},
	{
		"Player": "\"Jamal Agnew\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "4",
		"W1": "0",
		"W2": "1",
		"W3": "5",
		"W4": "-",
		"W5": "0",
		"TGTs": "6",
		"TGTs/G": "1.5",
		"Array": "7.6%"
	},
	{
		"Player": "\"Diontae Johnson\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "1",
		"W1": "6",
		"W2": "-",
		"W3": "-",
		"W4": "-",
		"W5": "-",
		"TGTs": "6",
		"TGTs/G": "6.0",
		"Array": "22.2%"
	},
	{
		"Player": "\"Justyn Ross\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "5",
		"W1": "1",
		"W2": "0",
		"W3": "1",
		"W4": "0",
		"W5": "4",
		"TGTs": "6",
		"TGTs/G": "1.2",
		"Array": "11.1%"
	},
	{
		"Player": "\"KaVontae Turpin\"",
		"Pos": "WR",
		"Team": "DAL",
		"G": "5",
		"W1": "3",
		"W2": "1",
		"W3": "0",
		"W4": "1",
		"W5": "1",
		"TGTs": "6",
		"TGTs/G": "1.2",
		"Array": "11.5%"
	},
	{
		"Player": "\"Cedrick Wilson\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "3",
		"W1": "-",
		"W2": "-",
		"W3": "0",
		"W4": "2",
		"W5": "4",
		"TGTs": "6",
		"TGTs/G": "2.0",
		"Array": "7.0%"
	},
	{
		"Player": "\"Marquise Goodwin\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "4",
		"W1": "2",
		"W2": "2",
		"W3": "0",
		"W4": "1",
		"W5": "-",
		"TGTs": "5",
		"TGTs/G": "1.3",
		"Array": "14.7%"
	},
	{
		"Player": "\"Lil'Jordan Humphrey\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "5",
		"W1": "2",
		"W2": "2",
		"W3": "0",
		"W4": "1",
		"W5": "0",
		"TGTs": "5",
		"TGTs/G": "1.0",
		"Array": "5.2%"
	},
	{
		"Player": "\"Jalin Hyatt\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "5",
		"W1": "1",
		"W2": "2",
		"W3": "0",
		"W4": "2",
		"W5": "0",
		"TGTs": "5",
		"TGTs/G": "1.0",
		"Array": "3.8%"
	},
	{
		"Player": "\"Tim Jones\"",
		"Pos": "WR",
		"Team": "JAX",
		"G": "5",
		"W1": "0",
		"W2": "0",
		"W3": "3",
		"W4": "1",
		"W5": "1",
		"TGTs": "5",
		"TGTs/G": "1.0",
		"Array": "5.3%"
	},
	{
		"Player": "\"Isaiah McKenzie\"",
		"Pos": "WR",
		"Team": "IND",
		"G": "5",
		"W1": "0",
		"W2": "1",
		"W3": "1",
		"W4": "3",
		"W5": "0",
		"TGTs": "5",
		"TGTs/G": "1.0",
		"Array": "19.2%"
	},
	{
		"Player": "\"Byron Pringle\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "4",
		"W1": "0",
		"W2": "1",
		"W3": "0",
		"W4": "2",
		"W5": "2",
		"TGTs": "5",
		"TGTs/G": "1.3",
		"Array": "10.4%"
	},
	{
		"Player": "\"Tyler Scott\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "5",
		"W1": "2",
		"W2": "0",
		"W3": "3",
		"W4": "0",
		"W5": "0",
		"TGTs": "5",
		"TGTs/G": "1.0",
		"Array": "7.8%"
	},
	{
		"Player": "\"Sterling Shepard\"",
		"Pos": "WR",
		"Team": "NYG",
		"G": "5",
		"W1": "1",
		"W2": "1",
		"W3": "0",
		"W4": "1",
		"W5": "2",
		"TGTs": "5",
		"TGTs/G": "1.0",
		"Array": "9.8%"
	},
	{
		"Player": "\"Ben Skowronek\"",
		"Pos": "WR",
		"Team": "LAR",
		"G": "5",
		"W1": "2",
		"W2": "1",
		"W3": "1",
		"W4": "0",
		"W5": "1",
		"TGTs": "5",
		"TGTs/G": "1.0",
		"Array": "6.2%"
	},
	{
		"Player": "\"Quez Watkins\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "3",
		"W1": "2",
		"W2": "0",
		"W3": "-",
		"W4": "-",
		"W5": "3",
		"TGTs": "5",
		"TGTs/G": "1.7",
		"Array": "4.3%"
	},
	{
		"Player": "\"Olamide Zaccheaus\"",
		"Pos": "WR",
		"Team": "PHI",
		"G": "5",
		"W1": "0",
		"W2": "0",
		"W3": "3",
		"W4": "2",
		"W5": "0",
		"TGTs": "5",
		"TGTs/G": "1.0",
		"Array": "3.2%"
	},
	{
		"Player": "\"David Bell\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "4",
		"W1": "1",
		"W2": "3",
		"W3": "0",
		"W4": "0",
		"W5": "-",
		"TGTs": "4",
		"TGTs/G": "1.0",
		"Array": "10.3%"
	},
	{
		"Player": "\"Ronnie Bell\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "5",
		"W1": "0",
		"W2": "0",
		"W3": "2",
		"W4": "1",
		"W5": "1",
		"TGTs": "4",
		"TGTs/G": "0.8",
		"Array": "4.5%"
	},
	{
		"Player": "\"Jake Bobo\"",
		"Pos": "WR",
		"Team": "SEA",
		"G": "4",
		"W1": "0",
		"W2": "1",
		"W3": "2",
		"W4": "1",
		"W5": "-",
		"TGTs": "4",
		"TGTs/G": "1.0",
		"Array": "4.9%"
	},
	{
		"Player": "\"Kayshon Boutte\"",
		"Pos": "WR",
		"Team": "NE",
		"G": "1",
		"W1": "4",
		"W2": "-",
		"W3": "-",
		"W4": "-",
		"W5": "-",
		"TGTs": "4",
		"TGTs/G": "4.0",
		"Array": "7.3%"
	},
	{
		"Player": "\"Noah Brown\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "1",
		"W1": "4",
		"W2": "-",
		"W3": "-",
		"W4": "-",
		"W5": "-",
		"TGTs": "4",
		"TGTs/G": "4.0",
		"Array": "7.7%"
	},
	{
		"Player": "\"DeAndre Carter\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "5",
		"W1": "1",
		"W2": "1",
		"W3": "1",
		"W4": "0",
		"W5": "1",
		"TGTs": "4",
		"TGTs/G": "0.8",
		"Array": "7.5%"
	},
	{
		"Player": "\"Derius Davis\"",
		"Pos": "WR",
		"Team": "LAC",
		"G": "4",
		"W1": "1",
		"W2": "0",
		"W3": "1",
		"W4": "2",
		"W5": "-",
		"TGTs": "4",
		"TGTs/G": "1.0",
		"Array": "12.5%"
	},
	{
		"Player": "\"Malik Heath\"",
		"Pos": "WR",
		"Team": "GB",
		"G": "3",
		"W1": "1",
		"W2": "1",
		"W3": "2",
		"W4": "-",
		"W5": "-",
		"TGTs": "4",
		"TGTs/G": "1.3",
		"Array": "8.0%"
	},
	{
		"Player": "\"KhaDarel Hodge\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "5",
		"W1": "0",
		"W2": "0",
		"W3": "1",
		"W4": "2",
		"W5": "1",
		"TGTs": "4",
		"TGTs/G": "0.8",
		"Array": "4.9%"
	},
	{
		"Player": "\"Keith Kirkwood\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "5",
		"W1": "1",
		"W2": "1",
		"W3": "1",
		"W4": "0",
		"W5": "1",
		"TGTs": "4",
		"TGTs/G": "0.8",
		"Array": "4.3%"
	},
	{
		"Player": "\"Khalil Shakir\"",
		"Pos": "WR",
		"Team": "BUF",
		"G": "5",
		"W1": "0",
		"W2": "1",
		"W3": "1",
		"W4": "1",
		"W5": "1",
		"TGTs": "4",
		"TGTs/G": "0.8",
		"Array": "5.7%"
	},
	{
		"Player": "\"Laviska Shenault\"",
		"Pos": "WR",
		"Team": "CAR",
		"G": "5",
		"W1": "2",
		"W2": "0",
		"W3": "1",
		"W4": "1",
		"W5": "0",
		"TGTs": "4",
		"TGTs/G": "0.8",
		"Array": "5.3%"
	},
	{
		"Player": "\"Richie James\"",
		"Pos": "WR",
		"Team": "KC",
		"G": "2",
		"W1": "2",
		"W2": "1",
		"W3": "-",
		"W4": "-",
		"W5": "-",
		"TGTs": "3",
		"TGTs/G": "1.5",
		"Array": "11.5%"
	},
	{
		"Player": "\"Ray-Ray McCloud\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "5",
		"W1": "0",
		"W2": "0",
		"W3": "0",
		"W4": "2",
		"W5": "1",
		"TGTs": "3",
		"TGTs/G": "0.6",
		"Array": "4.2%"
	},
	{
		"Player": "\"Cedric Tillman\"",
		"Pos": "WR",
		"Team": "CLE",
		"G": "4",
		"W1": "0",
		"W2": "0",
		"W3": "0",
		"W4": "3",
		"W5": "-",
		"TGTs": "3",
		"TGTs/G": "0.8",
		"Array": "6.7%"
	},
	{
		"Player": "\"Jameson Williams\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "1",
		"W1": "-",
		"W2": "-",
		"W3": "-",
		"W4": "-",
		"W5": "3",
		"TGTs": "3",
		"TGTs/G": "3.0",
		"Array": "10.7%"
	},
	{
		"Player": "\"Miles Boykin\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "5",
		"W1": "0",
		"W2": "1",
		"W3": "0",
		"W4": "0",
		"W5": "1",
		"TGTs": "2",
		"TGTs/G": "0.4",
		"Array": "5.7%"
	},
	{
		"Player": "\"Robbie Chosen\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "3",
		"W1": "-",
		"W2": "-",
		"W3": "1",
		"W4": "1",
		"W5": "0",
		"TGTs": "2",
		"TGTs/G": "0.7",
		"Array": "2.9%"
	},
	{
		"Player": "\"Jamison Crowder\"",
		"Pos": "WR",
		"Team": "WAS",
		"G": "2",
		"W1": "0",
		"W2": "0",
		"W3": "0",
		"W4": "0",
		"W5": "2",
		"TGTs": "2",
		"TGTs/G": "1.0",
		"Array": "22.2%"
	},
	{
		"Player": "\"Xavier Hutchinson\"",
		"Pos": "WR",
		"Team": "HOU",
		"G": "3",
		"W1": "1",
		"W2": "1",
		"W3": "0",
		"W4": "0",
		"W5": "0",
		"TGTs": "2",
		"TGTs/G": "0.7",
		"Array": "6.1%"
	},
	{
		"Player": "\"Andrei Iosivas\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "5",
		"W1": "0",
		"W2": "0",
		"W3": "0",
		"W4": "0",
		"W5": "2",
		"TGTs": "2",
		"TGTs/G": "0.4",
		"Array": "4.3%"
	},
	{
		"Player": "\"Rakim Jarrett\"",
		"Pos": "WR",
		"Team": "TB",
		"G": "4",
		"W1": "0",
		"W2": "1",
		"W3": "0",
		"W4": "1",
		"W5": "-",
		"TGTs": "2",
		"TGTs/G": "0.5",
		"Array": "4.9%"
	},
	{
		"Player": "\"Charlie Jones\"",
		"Pos": "WR",
		"Team": "CIN",
		"G": "1",
		"W1": "0",
		"W2": "0",
		"W3": "2",
		"W4": "-",
		"W5": "-",
		"TGTs": "2",
		"TGTs/G": "2.0",
		"Array": "66.7%"
	},
	{
		"Player": "\"Scott Miller\"",
		"Pos": "WR",
		"Team": "ATL",
		"G": "5",
		"W1": "0",
		"W2": "0",
		"W3": "0",
		"W4": "0",
		"W5": "2",
		"TGTs": "2",
		"TGTs/G": "0.4",
		"Array": "3.2%"
	},
	{
		"Player": "\"Equanimeous St. Brown\"",
		"Pos": "WR",
		"Team": "CHI",
		"G": "2",
		"W1": "-",
		"W2": "-",
		"W3": "-",
		"W4": "1",
		"W5": "1",
		"TGTs": "2",
		"TGTs/G": "1.0",
		"Array": "3.0%"
	},
	{
		"Player": "\"Tre Tucker\"",
		"Pos": "WR",
		"Team": "LV",
		"G": "4",
		"W1": "-",
		"W2": "1",
		"W3": "0",
		"W4": "0",
		"W5": "1",
		"TGTs": "2",
		"TGTs/G": "0.5",
		"Array": "4.3%"
	},
	{
		"Player": "\"Lynn Bowden\"",
		"Pos": "WR",
		"Team": "NO",
		"G": "3",
		"W1": "-",
		"W2": "-",
		"W3": "0",
		"W4": "1",
		"W5": "0",
		"TGTs": "1",
		"TGTs/G": "0.3",
		"Array": "4.0%"
	},
	{
		"Player": "\"Phillip Dorsett\"",
		"Pos": "WR",
		"Team": "DEN",
		"G": "1",
		"W1": "1",
		"W2": "-",
		"W3": "-",
		"W4": "-",
		"W5": "-",
		"TGTs": "1",
		"TGTs/G": "1.0",
		"Array": "16.7%"
	},
	{
		"Player": "\"Colton Dowell\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "1",
		"W1": "-",
		"W2": "-",
		"W3": "-",
		"W4": "1",
		"W5": "0",
		"TGTs": "1",
		"TGTs/G": "1.0",
		"Array": "6.7%"
	},
	{
		"Player": "\"Erik Ezukanma\"",
		"Pos": "WR",
		"Team": "MIA",
		"G": "2",
		"W1": "0",
		"W2": "1",
		"W3": "-",
		"W4": "-",
		"W5": "-",
		"TGTs": "1",
		"TGTs/G": "0.5",
		"Array": "3.4%"
	},
	{
		"Player": "\"Xavier Gipson\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "3",
		"W1": "0",
		"W2": "0",
		"W3": "0",
		"W4": "1",
		"W5": "0",
		"TGTs": "1",
		"TGTs/G": "0.3",
		"Array": "3.1%"
	},
	{
		"Player": "\"Antoine Green\"",
		"Pos": "WR",
		"Team": "DET",
		"G": "4",
		"W1": "-",
		"W2": "1",
		"W3": "0",
		"W4": "0",
		"W5": "0",
		"TGTs": "1",
		"TGTs/G": "0.3",
		"Array": "2.1%"
	},
	{
		"Player": "\"Mecole Hardman\"",
		"Pos": "WR",
		"Team": "NYJ",
		"G": "3",
		"W1": "0",
		"W2": "1",
		"W3": "0",
		"W4": "0",
		"W5": "-",
		"TGTs": "1",
		"TGTs/G": "0.3",
		"Array": "4.5%"
	},
	{
		"Player": "\"Gunner Olszewski\"",
		"Pos": "WR",
		"Team": "PIT",
		"G": "2",
		"W1": "-",
		"W2": "1",
		"W3": "-",
		"W4": "-",
		"W5": "0",
		"TGTs": "1",
		"TGTs/G": "0.5",
		"Array": "20.0%"
	},
	{
		"Player": "\"Kyle Philips\"",
		"Pos": "WR",
		"Team": "TEN",
		"G": "1",
		"W1": "-",
		"W2": "-",
		"W3": "-",
		"W4": "-",
		"W5": "1",
		"TGTs": "1",
		"TGTs/G": "1.0",
		"Array": "7.7%"
	},
	{
		"Player": "\"Willie Snead\"",
		"Pos": "WR",
		"Team": "SF",
		"G": "1",
		"W1": "-",
		"W2": "-",
		"W3": "-",
		"W4": "1",
		"W5": "-",
		"TGTs": "1",
		"TGTs/G": "1.0",
		"Array": "14.3%"
	},
	
]


module.exports = wr4for4PlayerTargetsAppLastFiveWeeks