const gppLeverageScoresAndProjOwnershipFanduel = [
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Lamar Jackson\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"WAS\"",
		"\"FD Sal $\"": "\"9500\"",
		"\"Projected Own%\"": "\"16.5%\"",
		"\"Cash Odds\"": "\"57%\"",
		"\"GPP Odds\"": "\"27%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"FD LEV\"": "\"0.77\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Ja'Marr Chase\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@NYG\"",
		"\"FD Sal $\"": "\"9500\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"18%\"",
		"\"Implied Own%\"": "\"15%\"",
		"\"FD LEV\"": "\"3.69\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"CeeDee Lamb\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"DET\"",
		"\"FD Sal $\"": "\"9300\"",
		"\"Projected Own%\"": "\"8.5%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"1.30\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Saquon Barkley\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"CLE\"",
		"\"FD Sal $\"": "\"9200\"",
		"\"Projected Own%\"": "\"11.5%\"",
		"\"Cash Odds\"": "\"59%\"",
		"\"GPP Odds\"": "\"24%\"",
		"\"Implied Own%\"": "\"22%\"",
		"\"FD LEV\"": "\"1.94\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Derrick Henry\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"WAS\"",
		"\"FD Sal $\"": "\"9100\"",
		"\"Projected Own%\"": "\"14.0%\"",
		"\"Cash Odds\"": "\"53%\"",
		"\"GPP Odds\"": "\"22%\"",
		"\"Implied Own%\"": "\"20%\"",
		"\"FD LEV\"": "\"1.45\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Amon-Ra St. Brown\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@DAL\"",
		"\"FD Sal $\"": "\"9000\"",
		"\"Projected Own%\"": "\"9.5%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"FD LEV\"": "\"1.33\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Alvin Kamara\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"TB\"",
		"\"FD Sal $\"": "\"8800\"",
		"\"Projected Own%\"": "\"17.0%\"",
		"\"Cash Odds\"": "\"56%\"",
		"\"GPP Odds\"": "\"21%\"",
		"\"Implied Own%\"": "\"19%\"",
		"\"FD LEV\"": "\"1.13\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jayden Daniels\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"8700\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"17%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"1.13\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jordan Love\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"8500\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"1.68\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Bijan Robinson\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"8500\"",
		"\"Projected Own%\"": "\"17.0%\"",
		"\"Cash Odds\"": "\"54%\"",
		"\"GPP Odds\"": "\"18%\"",
		"\"Implied Own%\"": "\"16%\"",
		"\"FD LEV\"": "\"0.95\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jalen Hurts\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"CLE\"",
		"\"FD Sal $\"": "\"8300\"",
		"\"Projected Own%\"": "\"24.0%\"",
		"\"Cash Odds\"": "\"55%\"",
		"\"GPP Odds\"": "\"24%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"0.46\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"C.J. Stroud\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@NE\"",
		"\"FD Sal $\"": "\"8200\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"38%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"2.57\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Mike Evans\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"@NO\"",
		"\"FD Sal $\"": "\"8200\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"3.74\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Joe Burrow\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@NYG\"",
		"\"FD Sal $\"": "\"8100\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"1.00\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"A.J. Brown\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"CLE\"",
		"\"FD Sal $\"": "\"8100\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"2.20\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Dak Prescott\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"DET\"",
		"\"FD Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"8.5%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.67\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"James Conner\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"9.0%\"",
		"\"Cash Odds\"": "\"50%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"FD LEV\"": "\"1.43\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Stefon Diggs\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@NE\"",
		"\"FD Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"6.0%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"1.51\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Baker Mayfield\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"@NO\"",
		"\"FD Sal $\"": "\"7900\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"38%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"2.24\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"David Montgomery\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@DAL\"",
		"\"FD Sal $\"": "\"7900\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"10%\"",
		"\"FD LEV\"": "\"2.54\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Kyler Murray\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"7800\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"1.32\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jahmyr Gibbs\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@DAL\"",
		"\"FD Sal $\"": "\"7800\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"FD LEV\"": "\"1.56\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jared Goff\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@DAL\"",
		"\"FD Sal $\"": "\"7700\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.77\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Brian Robinson\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"7700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"5.23\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jayden Reed\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"7700\"",
		"\"Projected Own%\"": "\"15.5%\"",
		"\"Cash Odds\"": "\"51%\"",
		"\"GPP Odds\"": "\"16%\"",
		"\"Implied Own%\"": "\"14%\"",
		"\"FD LEV\"": "\"0.87\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Justin Fields\"",
		"\"Tm\"": "\"PIT\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"7600\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"1.20\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Josh Jacobs\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"7600\"",
		"\"Projected Own%\"": "\"14.0%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"16%\"",
		"\"Implied Own%\"": "\"15%\"",
		"\"FD LEV\"": "\"1.05\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tee Higgins\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@NYG\"",
		"\"FD Sal $\"": "\"7600\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"1.32\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Chris Godwin\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"@NO\"",
		"\"FD Sal $\"": "\"7500\"",
		"\"Projected Own%\"": "\"14.0%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"0.67\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Kirk Cousins\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"7400\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.87\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Chuba Hubbard\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"7400\"",
		"\"Projected Own%\"": "\"17.5%\"",
		"\"Cash Odds\"": "\"55%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"FD LEV\"": "\"0.74\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Drake London\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"7400\"",
		"\"Projected Own%\"": "\"16.0%\"",
		"\"Cash Odds\"": "\"50%\"",
		"\"GPP Odds\"": "\"17%\"",
		"\"Implied Own%\"": "\"14%\"",
		"\"FD LEV\"": "\"0.90\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DeVonta Smith\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"CLE\"",
		"\"FD Sal $\"": "\"7300\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"3.78\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Justin Herbert\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@DEN\"",
		"\"FD Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"24%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.38\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Najee Harris\"",
		"\"Tm\"": "\"PIT\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"10.0%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"0.83\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Zay Flowers\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"WAS\"",
		"\"FD Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.96\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Andy Dalton\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"7100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"5.84\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Chris Olave\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"TB\"",
		"\"FD Sal $\"": "\"7100\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.72\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tony Pollard\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"19.5%\"",
		"\"Cash Odds\"": "\"53%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"FD LEV\"": "\"0.65\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Marvin Harrison Jr.\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"8.5%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"1.30\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Dallas Goedert\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"CLE\"",
		"\"FD Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"9.34\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Diontae Johnson\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"11.5%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"0.65\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Daniel Jones\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"CIN\"",
		"\"FD Sal $\"": "\"6800\"",
		"\"Projected Own%\"": "\"11.0%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.37\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Rhamondre Stevenson\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"HOU\"",
		"\"FD Sal $\"": "\"6800\"",
		"\"Projected Own%\"": "\"6.0%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.54\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Terry McLaurin\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"6800\"",
		"\"Projected Own%\"": "\"11.0%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"0.67\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Bo Nix\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"LAC\"",
		"\"FD Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"4.16\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"J.K. Dobbins\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@DEN\"",
		"\"FD Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"13.5%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"0.70\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tank Dell\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@NE\"",
		"\"FD Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.70\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Brock Bowers\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"PIT\"",
		"\"FD Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"8.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"FD LEV\"": "\"1.53\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Will Levis\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.91\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Deshaun Watson\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"@PHI\"",
		"\"FD Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"2.56\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Aidan O'Connell\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"PIT\"",
		"\"FD Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.17\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Darnell Mooney\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"8.5%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.70\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Trey McBride\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"0.72\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Rashid Shaheed\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"TB\"",
		"\"FD Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"9.5%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.39\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Rachaad White\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"@NO\"",
		"\"FD Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.60\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jameson Williams\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@DAL\"",
		"\"FD Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"2.78\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Wan'Dale Robinson\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"CIN\"",
		"\"FD Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"8.5%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.57\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Sam LaPorta\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@DAL\"",
		"\"FD Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"10.5%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"10%\"",
		"\"FD LEV\"": "\"0.96\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jerome Ford\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"@PHI\"",
		"\"FD Sal $\"": "\"6200\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"1.59\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"George Pickens\"",
		"\"Tm\"": "\"PIT\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"6200\"",
		"\"Projected Own%\"": "\"14.0%\"",
		"\"Cash Odds\"": "\"38%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.27\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Amari Cooper\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"@PHI\"",
		"\"FD Sal $\"": "\"6200\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.97\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Rico Dowdle\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"DET\"",
		"\"FD Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.41\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jalen Tolbert\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"DET\"",
		"\"FD Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"2.82\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Josh Downs\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@TEN\"",
		"\"FD Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.61\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Jake Ferguson\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"DET\"",
		"\"FD Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"30.0%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"16%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"FD LEV\"": "\"0.43\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Drake Maye\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"HOU\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"23%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.90\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Trey Sermon\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@TEN\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"6.0%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.80\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Dontayvion Wicks\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.55\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Calvin Ridley\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"2.42\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Tucker Kraft\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"22%\"",
		"\"Implied Own%\"": "\"17%\"",
		"\"FD LEV\"": "\"1.39\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Javonte Williams\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"LAC\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.47\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Ezekiel Elliott\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"DET\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"10%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.08\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Darius Slayton\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"CIN\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"3.69\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Michael Wilson\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.43\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Xavier Legette\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"24%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"1.79\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Kyle Pitts\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"6.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"1.08\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tyrone Tracy\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"CIN\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"10.5%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"0.88\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Cam Akers\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@NE\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"5.17\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Alec Pierce\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@TEN\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"9.07\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Ladd McConkey\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@DEN\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.58\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Quentin Johnston\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@DEN\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"4.77\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DeAndre Hopkins\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.68\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Isaiah Likely\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"WAS\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.91\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Bucky Irving\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"@NO\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.75\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tyjae Spears\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"2.20\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Austin Ekeler\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.22\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jakobi Meyers\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"PIT\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"10.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.34\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jerry Jeudy\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"@PHI\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.87\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Pat Freiermuth\"",
		"\"Tm\"": "\"PIT\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.88\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Alexander Mattison\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"PIT\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"10.0%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.48\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Courtland Sutton\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"LAC\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"9.0%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.19\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Ray-Ray McCloud\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.30\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Antonio Gibson\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"HOU\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.92\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Justice Hill\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"WAS\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.30\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Rashod Bateman\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"WAS\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.69\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Mark Andrews\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"WAS\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"8.55\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Chase Brown\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@NYG\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"18.0%\"",
		"\"Cash Odds\"": "\"59%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"14%\"",
		"\"FD LEV\"": "\"0.78\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tyler Allgeier\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"3.38\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Dare Ogunbowale\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@NE\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.46\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tre Tucker\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"PIT\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.14\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Andrei Iosivas\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@NYG\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.99\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jonathan Mingo\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"17%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.11\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Dalton Schultz\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@NE\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.04\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jaleel McLaughlin\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"LAC\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.56\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Miles Sanders\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.82\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Emanuel Wilson\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"15%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.38\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Cade Otton\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"@NO\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.68\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"D'Onta Foreman\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"@PHI\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.76\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Gus Edwards\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@DEN\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"6%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"KaVontae Turpin\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"DET\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.57\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Joshua Palmer\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@DEN\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.33\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Olamide Zaccheaus\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"13%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.33\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Mike Gesicki\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@NYG\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"1.40\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Juwan Johnson\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"TB\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"11%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.35\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Adonai Mitchell\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@TEN\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"2.69\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Demario Douglas\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"HOU\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.51\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tyler Boyd\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"16%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.50\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Hunter Henry\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"HOU\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"1.26\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Zach Ertz\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.29\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Houston Texans\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@NE\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"54%\"",
		"\"GPP Odds\"": "\"21%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"2.68\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Greg Dortch\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"18%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.76\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Lil'Jordan Humphrey\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"LAC\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"16%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.61\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Nelson Agholor\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"WAS\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"8%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.07\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Theo Johnson\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"CIN\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"4.32\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Chigoziem Okonkwo\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"10%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.20\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Pittsburgh Steelers\"",
		"\"Tm\"": "\"PIT\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"11.40\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Ameer Abdullah\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"PIT\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"24%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.51\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Van Jefferson\"",
		"\"Tm\"": "\"PIT\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"6%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.05\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Ja'Tavion Sanders\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.46\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Philadelphia Eagles\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"CLE\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"8.0%\"",
		"\"Cash Odds\"": "\"53%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.64\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tyler Goodson\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@TEN\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"2.32\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Elijah Moore\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"@PHI\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"12%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.18\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Denver Broncos\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"LAC\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"7.21\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tim Patrick\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@DAL\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"2%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Hayden Hurst\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@DEN\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"17%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.22\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Cincinnati Bengals\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@NYG\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"6.92\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Luke McCaffrey\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"15%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.61\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Green Bay Packers\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"9.00\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Los Angeles Chargers\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@DEN\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.65\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Tennessee Titans\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.34\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Trayveon Williams\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@NYG\"",
		"\"FD Sal $\"": "\"4200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.65\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Baltimore Ravens\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"WAS\"",
		"\"FD Sal $\"": "\"4200\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.69\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"New Orleans Saints\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"TB\"",
		"\"FD Sal $\"": "\"4100\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"1.45\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Indianapolis Colts\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@TEN\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.33\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Las Vegas Raiders\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"PIT\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.63\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Detroit Lions\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@DAL\"",
		"\"FD Sal $\"": "\"3900\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"1.90\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Atlanta Falcons\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"3800\"",
		"\"Projected Own%\"": "\"8.0%\"",
		"\"Cash Odds\"": "\"50%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.64\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Tampa Bay Buccaneers\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"@NO\"",
		"\"FD Sal $\"": "\"3700\"",
		"\"Projected Own%\"": "\"8.5%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.54\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Cleveland Browns\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"@PHI\"",
		"\"FD Sal $\"": "\"3600\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.08\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Washington Commanders\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"3500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.38\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Arizona Cardinals\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"3400\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"2.89\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Dallas Cowboys\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"DET\"",
		"\"FD Sal $\"": "\"3300\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"51%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"1.56\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"New England Patriots\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"HOU\"",
		"\"FD Sal $\"": "\"3200\"",
		"\"Projected Own%\"": "\"6.5%\"",
		"\"Cash Odds\"": "\"51%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.56\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"New York Giants\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"CIN\"",
		"\"FD Sal $\"": "\"3100\"",
		"\"Projected Own%\"": "\"10.0%\"",
		"\"Cash Odds\"": "\"55%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.25\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Carolina Panthers\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"3000\"",
		"\"Projected Own%\"": "\"6.5%\"",
		"\"Cash Odds\"": "\"53%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.50\""
	}
]

module.exports = gppLeverageScoresAndProjOwnershipFanduel;