const gppLeverageScoresAndProjOwnershipFanduel = [
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Josh Allen\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"9400\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"17%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"2.55\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Derrick Henry\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"@CLE\"",
		"\"FD Sal $\"": "\"9200\"",
		"\"Projected Own%\"": "\"11.0%\"",
		"\"Cash Odds\"": "\"55%\"",
		"\"GPP Odds\"": "\"25%\"",
		"\"Implied Own%\"": "\"20%\"",
		"\"FD LEV\"": "\"1.83\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Ja'Marr Chase\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"PHI\"",
		"\"FD Sal $\"": "\"9200\"",
		"\"Projected Own%\"": "\"9.5%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"17%\"",
		"\"Implied Own%\"": "\"14%\"",
		"\"FD LEV\"": "\"1.51\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Saquon Barkley\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@CIN\"",
		"\"FD Sal $\"": "\"9100\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"20%\"",
		"\"Implied Own%\"": "\"16%\"",
		"\"FD LEV\"": "\"2.31\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"CeeDee Lamb\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@SF\"",
		"\"FD Sal $\"": "\"9100\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"2.37\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Joe Mixon\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"9000\"",
		"\"Projected Own%\"": "\"21.0%\"",
		"\"Cash Odds\"": "\"59%\"",
		"\"GPP Odds\"": "\"23%\"",
		"\"Implied Own%\"": "\"18%\"",
		"\"FD LEV\"": "\"0.87\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"A.J. Brown\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@CIN\"",
		"\"FD Sal $\"": "\"9000\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"1.61\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jordan Love\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"8900\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"17%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"0.95\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jordan Mason\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"8900\"",
		"\"Projected Own%\"": "\"6.5%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"10%\"",
		"\"FD LEV\"": "\"1.51\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Amon-Ra St. Brown\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"8900\"",
		"\"Projected Own%\"": "\"11.0%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"10%\"",
		"\"FD LEV\"": "\"0.95\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Lamar Jackson\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"@CLE\"",
		"\"FD Sal $\"": "\"8800\"",
		"\"Projected Own%\"": "\"14.0%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"21%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"0.56\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jalen Hurts\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@CIN\"",
		"\"FD Sal $\"": "\"8600\"",
		"\"Projected Own%\"": "\"6.0%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"16%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"1.00\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Bijan Robinson\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@TB\"",
		"\"FD Sal $\"": "\"8600\"",
		"\"Projected Own%\"": "\"8.5%\"",
		"\"Cash Odds\"": "\"50%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"FD LEV\"": "\"1.41\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"C.J. Stroud\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"8500\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"1.90\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Stefon Diggs\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"8500\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"1.05\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jahmyr Gibbs\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"8400\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"FD LEV\"": "\"0.94\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"James Conner\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"8300\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"FD LEV\"": "\"3.83\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Alvin Kamara\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@LAC\"",
		"\"FD Sal $\"": "\"8200\"",
		"\"Projected Own%\"": "\"6.0%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.74\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Kareem Hunt\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"8100\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"1.80\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jayden Reed\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"8100\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"2.01\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Patrick Mahomes\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.07\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Baker Mayfield\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"3.74\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"David Montgomery\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"6.01\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jonathan Taylor\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@HOU\"",
		"\"FD Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.36\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Deebo Samuel\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"10.00\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jared Goff\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"7900\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"38%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.81\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Breece Hall\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"@NE\"",
		"\"FD Sal $\"": "\"7900\"",
		"\"Projected Own%\"": "\"29.0%\"",
		"\"Cash Odds\"": "\"67%\"",
		"\"GPP Odds\"": "\"31%\"",
		"\"Implied Own%\"": "\"25%\"",
		"\"FD LEV\"": "\"0.87\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Drake London\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@TB\"",
		"\"FD Sal $\"": "\"7900\"",
		"\"Projected Own%\"": "\"11.5%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"1.00\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Kyler Murray\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"7800\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"16%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"1.49\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Kenneth Walker\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"7800\"",
		"\"Projected Own%\"": "\"17.5%\"",
		"\"Cash Odds\"": "\"59%\"",
		"\"GPP Odds\"": "\"20%\"",
		"\"Implied Own%\"": "\"16%\"",
		"\"FD LEV\"": "\"0.94\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Davante Adams\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"@NE\"",
		"\"FD Sal $\"": "\"7800\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"2.69\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"George Kittle\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"7800\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"22%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"FD LEV\"": "\"1.57\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Joe Burrow\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"PHI\"",
		"\"FD Sal $\"": "\"7700\"",
		"\"Projected Own%\"": "\"10.0%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.58\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Brock Purdy\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"7700\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.96\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"James Cook\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"7700\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"2.28\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Dak Prescott\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@SF\"",
		"\"FD Sal $\"": "\"7600\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"2.14\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Brian Robinson\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"7600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"13.17\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tyreek Hill\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"7600\"",
		"\"Projected Own%\"": "\"20.5%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"0.54\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Geno Smith\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"7500\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"1.38\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Josh Jacobs\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"7500\"",
		"\"Projected Own%\"": "\"11.5%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"0.75\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tee Higgins\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"PHI\"",
		"\"FD Sal $\"": "\"7500\"",
		"\"Projected Own%\"": "\"16.0%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"10%\"",
		"\"FD LEV\"": "\"0.62\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Caleb Williams\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"7400\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.60\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"J.K. Dobbins\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"7400\"",
		"\"Projected Own%\"": "\"19.5%\"",
		"\"Cash Odds\"": "\"53%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"0.58\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Garrett Wilson\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"@NE\"",
		"\"FD Sal $\"": "\"7400\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"2.38\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Brock Bowers\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"KC\"",
		"\"FD Sal $\"": "\"7400\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"21%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"1.57\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Anthony Richardson\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@HOU\"",
		"\"FD Sal $\"": "\"7300\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"1.26\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Justin Herbert\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"7300\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"1.66\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Chuba Hubbard\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@DEN\"",
		"\"FD Sal $\"": "\"7300\"",
		"\"Projected Own%\"": "\"11.0%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"0.62\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DeVonta Smith\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@CIN\"",
		"\"FD Sal $\"": "\"7300\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"3.68\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Aaron Rodgers\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"@NE\"",
		"\"FD Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"1.29\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Trevor Lawrence\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"GB\"",
		"\"FD Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"1.38\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Xavier Worthy\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"8.52\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Marvin Harrison Jr.\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"10.02\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Kirk Cousins\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@TB\"",
		"\"FD Sal $\"": "\"7100\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.10\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Drake Maye\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"NYJ\"",
		"\"FD Sal $\"": "\"7100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.22\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tank Bigsby\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"GB\"",
		"\"FD Sal $\"": "\"7100\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"2.40\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Amari Cooper\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"7100\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"3.22\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Tua Tagovailoa\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.68\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Spencer Rattler\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@LAC\"",
		"\"FD Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.38\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tony Pollard\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@DET\"",
		"\"FD Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"13.0%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"0.66\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Terry McLaurin\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.30\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Bo Nix\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"13.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.32\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Nick Chubb\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"BAL\"",
		"\"FD Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.33\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tank Dell\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"8.0%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"1.10\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Travis Kelce\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"9.0%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.70\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Marcus Mariota\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"6800\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"1.37\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"De'Von Achane\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"6800\"",
		"\"Projected Own%\"": "\"15.5%\"",
		"\"Cash Odds\"": "\"53%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"0.70\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Diontae Johnson\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@DEN\"",
		"\"FD Sal $\"": "\"6800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.57\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Rhamondre Stevenson\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"NYJ\"",
		"\"FD Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"38%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"2.26\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Chris Olave\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@LAC\"",
		"\"FD Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"24%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.33\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Trey McBride\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"17%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"2.52\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Gardner Minshew\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"KC\"",
		"\"FD Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.60\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Chase Brown\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"PHI\"",
		"\"FD Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.53\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"D.J. Moore\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"13.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"0.57\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jameis Winston\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"BAL\"",
		"\"FD Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"38%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"1.42\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"D'Andre Swift\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"17.0%\"",
		"\"Cash Odds\"": "\"53%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"0.46\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Brian Thomas Jr.\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"GB\"",
		"\"FD Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"14.0%\"",
		"\"Cash Odds\"": "\"50%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"FD LEV\"": "\"0.86\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Rachaad White\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.95\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jaxon Smith-Njigba\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.68\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Keenan Allen\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"4.11\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Zack Moss\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"PHI\"",
		"\"FD Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.50\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Darnell Mooney\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@TB\"",
		"\"FD Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"38%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.69\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Josh Downs\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@HOU\"",
		"\"FD Sal $\"": "\"6200\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.71\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Evan Engram\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"GB\"",
		"\"FD Sal $\"": "\"6200\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.87\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Alexander Mattison\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"KC\"",
		"\"FD Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.80\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Braelon Allen\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"@NE\"",
		"\"FD Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"2%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tyler Lockett\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"9.5%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.62\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Romeo Doubs\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.71\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Michael Pittman Jr.\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@HOU\"",
		"\"FD Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"2.80\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Jake Ferguson\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@SF\"",
		"\"FD Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.25\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Mason Rudolph\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@DET\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.98\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Bryce Young\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@DEN\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.46\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Javonte Williams\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"25.0%\"",
		"\"Cash Odds\"": "\"56%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"10%\"",
		"\"FD LEV\"": "\"0.39\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Rico Dowdle\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@SF\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"2.58\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Justice Hill\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"@CLE\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"12%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.12\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jerry Jeudy\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"BAL\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"6.69\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Ladd McConkey\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"11.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.27\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jalen Tolbert\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@SF\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"4.60\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Sam LaPorta\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"6.84\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Raheem Mostert\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"4.33\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Austin Ekeler\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.92\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Ray Davis\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"11%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.13\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jaylen Waddle\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"14.5%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"0.75\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Dontayvion Wicks\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"5.66\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Christian Kirk\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"GB\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.40\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Tucker Kraft\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"6.16\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Ezekiel Elliott\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@SF\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"10%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.07\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Alec Pierce\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@HOU\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"6.40\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Khalil Shakir\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"1.31\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Christian Watson\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"24%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.92\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Joshua Palmer\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.50\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Gabe Davis\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"GB\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.04\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Xavier Legette\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@DEN\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"14%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.56\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Isaiah Likely\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"@CLE\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.78\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tyler Allgeier\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@TB\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.54\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Roschon Johnson\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"17%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.62\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Rashod Bateman\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"@CLE\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"2.65\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Kyle Pitts\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@TB\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.28\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"D'Ernest Johnson\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"GB\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.88\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Emanuel Wilson\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"2%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Courtland Sutton\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.93\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Calvin Ridley\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@DET\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"8.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.48\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Keon Coleman\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"23%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.91\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Michael Wilson\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"17%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.43\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tre Tucker\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"KC\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"13%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.41\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Mason Tipton\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@LAC\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"2%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Mark Andrews\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"@CLE\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"2.68\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Sean Tucker\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"3%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Rome Odunze\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.03\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Justin Watson\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"1%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"David Njoku\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"BAL\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"16.0%\"",
		"\"Cash Odds\"": "\"57%\"",
		"\"GPP Odds\"": "\"25%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"FD LEV\"": "\"0.84\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Antonio Gibson\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"NYJ\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"3%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DeAndre Hopkins\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"1.83\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Ray-Ray McCloud\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@TB\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"14%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.30\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Cole Kmet\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.85\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Troy Franklin\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.74\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Hunter Henry\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"NYJ\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"2.43\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Juwan Johnson\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@LAC\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"5%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Zach Charbonnet\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"12%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.06\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Ricky Pearsall\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.50\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Andrei Iosivas\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"PHI\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"14%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.32\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"KaVontae Turpin\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@SF\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"12%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.08\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Cade Otton\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"12.0%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.45\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Jonnu Smith\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"7.11\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Zach Ertz\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.12\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Baltimore Ravens\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"@CLE\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"51%\"",
		"\"GPP Odds\"": "\"20%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"1.72\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Miles Sanders\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@DEN\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"11%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.03\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Cedric Tillman\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"BAL\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"1.34\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Elijah Moore\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"BAL\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.84\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Sterling Shepard\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"24%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.68\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Demario Douglas\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"NYJ\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.41\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Allen Lazard\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"@NE\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"15%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.34\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DJ Turner\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"KC\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"3%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Dalton Schultz\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.72\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Tyler Conklin\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"@NE\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.31\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Adonai Mitchell\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@HOU\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"5%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Noah Fant\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.18\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Noah Gray\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.57\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Ja'Tavion Sanders\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@DEN\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.50\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Denver Broncos\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"19%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"2.28\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jaleel McLaughlin\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"23%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.06\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jalen McMillan\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"9.0%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.25\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tyler Boyd\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@DET\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.74\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Nick Westbrook-Ikhine\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@DET\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"14%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.15\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Will Dissly\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.40\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Grant Calcaterra\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@CIN\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"23%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.64\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Chigoziem Okonkwo\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@DET\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"23%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.59\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"New York Jets\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"@NE\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"50%\"",
		"\"GPP Odds\"": "\"17%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.95\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Kalif Raymond\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.28\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Simi Fehoko\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.76\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Noah Brown\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"13%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.16\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Kendrick Bourne\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"NYJ\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"1%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Erick All\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"PHI\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"10%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.16\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tim Patrick\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.45\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Kansas City Chiefs\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"53%\"",
		"\"GPP Odds\"": "\"20%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"1.21\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Green Bay Packers\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"4.92\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Pierre Strong Jr.\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"BAL\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"4%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Chris Conley\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"0%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Los Angeles Chargers\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"8.5%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"17%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.62\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Chicago Bears\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"2.44\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jake Bobo\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"14%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.09\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Buffalo Bills\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"5.63\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Philadelphia Eagles\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@CIN\"",
		"\"FD Sal $\"": "\"4200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.67\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Houston Texans\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"4100\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"51%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.92\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Kimani Vidal\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.16\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Trey Palmer\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.06\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Devaughn Vele\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"24%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.12\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Dalton Kincaid\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"23.5%\"",
		"\"Cash Odds\"": "\"50%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.23\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Detroit Lions\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"17.0%\"",
		"\"Cash Odds\"": "\"57%\"",
		"\"GPP Odds\"": "\"21%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.38\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"San Francisco 49ers\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.93\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Seattle Seahawks\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"3900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"4.20\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Washington Commanders\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"3900\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.78\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Arizona Cardinals\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"3800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"6.24\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"New Orleans Saints\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@LAC\"",
		"\"FD Sal $\"": "\"3800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"7.07\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Cincinnati Bengals\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"PHI\"",
		"\"FD Sal $\"": "\"3700\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"1.39\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Tampa Bay Buccaneers\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"3700\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"1.12\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Atlanta Falcons\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@TB\"",
		"\"FD Sal $\"": "\"3600\"",
		"\"Projected Own%\"": "\"6.5%\"",
		"\"Cash Odds\"": "\"51%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.38\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Dallas Cowboys\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@SF\"",
		"\"FD Sal $\"": "\"3600\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"1.09\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Jacksonville Jaguars\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"GB\"",
		"\"FD Sal $\"": "\"3500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"4.09\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Miami Dolphins\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"3400\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"54%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.40\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Indianapolis Colts\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@HOU\"",
		"\"FD Sal $\"": "\"3300\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"51%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.89\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"New England Patriots\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"NYJ\"",
		"\"FD Sal $\"": "\"3300\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.76\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Carolina Panthers\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@DEN\"",
		"\"FD Sal $\"": "\"3200\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"1.41\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Cleveland Browns\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"BAL\"",
		"\"FD Sal $\"": "\"3100\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.68\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Las Vegas Raiders\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"KC\"",
		"\"FD Sal $\"": "\"3000\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"50%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.70\""
	}
]

module.exports = gppLeverageScoresAndProjOwnershipFanduel;