const gppLeverageScoresAndProjOwnershipFanduel = [
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Saquon Barkley\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@LAR\"",
		"\"FD Sal $\"": "\"10000\"",
		"\"Projected Own%\"": "\"6.5%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"21%\"",
		"\"Implied Own%\"": "\"21%\"",
		"\"FD LEV\"": "\"3.19\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Christian McCaffrey\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"9500\"",
		"\"Projected Own%\"": "\"14.0%\"",
		"\"Cash Odds\"": "\"57%\"",
		"\"GPP Odds\"": "\"23%\"",
		"\"Implied Own%\"": "\"23%\"",
		"\"FD LEV\"": "\"1.66\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Amon-Ra St. Brown\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@IND\"",
		"\"FD Sal $\"": "\"9500\"",
		"\"Projected Own%\"": "\"8.5%\"",
		"\"Cash Odds\"": "\"50%\"",
		"\"GPP Odds\"": "\"21%\"",
		"\"Implied Own%\"": "\"21%\"",
		"\"FD LEV\"": "\"2.41\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jalen Hurts\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@LAR\"",
		"\"FD Sal $\"": "\"9300\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"22%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"2.00\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Joe Mixon\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"9300\"",
		"\"Projected Own%\"": "\"16.0%\"",
		"\"Cash Odds\"": "\"56%\"",
		"\"GPP Odds\"": "\"21%\"",
		"\"Implied Own%\"": "\"21%\"",
		"\"FD LEV\"": "\"1.30\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Cooper Kupp\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"PHI\"",
		"\"FD Sal $\"": "\"9200\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"FD LEV\"": "\"6.72\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"De'Von Achane\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"9100\"",
		"\"Projected Own%\"": "\"21.0%\"",
		"\"Cash Odds\"": "\"63%\"",
		"\"GPP Odds\"": "\"30%\"",
		"\"Implied Own%\"": "\"29%\"",
		"\"FD LEV\"": "\"1.40\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jayden Daniels\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"9000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"50%\"",
		"\"GPP Odds\"": "\"21%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"2.50\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Justin Jefferson\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"@CHI\"",
		"\"FD Sal $\"": "\"9000\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"18%\"",
		"\"Implied Own%\"": "\"18%\"",
		"\"FD LEV\"": "\"4.52\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Nico Collins\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"8900\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"4.53\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jahmyr Gibbs\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@IND\"",
		"\"FD Sal $\"": "\"8600\"",
		"\"Projected Own%\"": "\"14.5%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"17%\"",
		"\"Implied Own%\"": "\"17%\"",
		"\"FD LEV\"": "\"1.17\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Puka Nacua\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"PHI\"",
		"\"FD Sal $\"": "\"8600\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"2.17\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jared Goff\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@IND\"",
		"\"FD Sal $\"": "\"8500\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"4.82\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"A.J. Brown\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@LAR\"",
		"\"FD Sal $\"": "\"8500\"",
		"\"Projected Own%\"": "\"9.5%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"16%\"",
		"\"Implied Own%\"": "\"16%\"",
		"\"FD LEV\"": "\"1.72\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Patrick Mahomes\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"8400\"",
		"\"Projected Own%\"": "\"6.5%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"17%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.95\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"David Montgomery\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@IND\"",
		"\"FD Sal $\"": "\"8400\"",
		"\"Projected Own%\"": "\"6.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"1.30\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"CeeDee Lamb\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"8400\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"2.89\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Kyren Williams\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"PHI\"",
		"\"FD Sal $\"": "\"8300\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"50%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"14%\"",
		"\"FD LEV\"": "\"1.11\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tyreek Hill\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"8300\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"2.10\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Isiah Pacheco\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"8200\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"5.69\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Malik Nabers\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"TB\"",
		"\"FD Sal $\"": "\"8200\"",
		"\"Projected Own%\"": "\"10.0%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"FD LEV\"": "\"1.32\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Brock Purdy\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"8100\"",
		"\"Projected Own%\"": "\"6.0%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"16%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.97\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Kenneth Walker\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"8100\"",
		"\"Projected Own%\"": "\"16.5%\"",
		"\"Cash Odds\"": "\"53%\"",
		"\"GPP Odds\"": "\"16%\"",
		"\"Implied Own%\"": "\"16%\"",
		"\"FD LEV\"": "\"0.95\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Bo Nix\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"19%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"0.91\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jonathan Taylor\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"DET\"",
		"\"FD Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"6.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.64\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Mike Evans\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"@NYG\"",
		"\"FD Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"15%\"",
		"\"FD LEV\"": "\"2.19\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Baker Mayfield\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"@NYG\"",
		"\"FD Sal $\"": "\"7900\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.60\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Brian Robinson\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"7900\"",
		"\"Projected Own%\"": "\"13.5%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"FD LEV\"": "\"0.86\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DK Metcalf\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"7900\"",
		"\"Projected Own%\"": "\"8.5%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"10%\"",
		"\"FD LEV\"": "\"1.15\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Kyler Murray\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"7800\"",
		"\"Projected Own%\"": "\"10.0%\"",
		"\"Cash Odds\"": "\"51%\"",
		"\"GPP Odds\"": "\"20%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"0.72\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Terry McLaurin\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"7800\"",
		"\"Projected Own%\"": "\"9.5%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"0.98\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Tua Tagovailoa\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"7700\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"18%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.86\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"James Conner\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"7700\"",
		"\"Projected Own%\"": "\"14.0%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"FD LEV\"": "\"0.89\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DeVonta Smith\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@LAR\"",
		"\"FD Sal $\"": "\"7700\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.26\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"C.J. Stroud\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"7600\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.98\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Josh Jacobs\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"SF\"",
		"\"FD Sal $\"": "\"7600\"",
		"\"Projected Own%\"": "\"17.0%\"",
		"\"Cash Odds\"": "\"55%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"FD LEV\"": "\"0.79\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Deebo Samuel\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"7600\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"1.46\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Anthony Richardson\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"DET\"",
		"\"FD Sal $\"": "\"7500\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.98\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jaxon Smith-Njigba\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"7500\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"1.45\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Brock Bowers\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"7500\"",
		"\"Projected Own%\"": "\"10.0%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"23%\"",
		"\"Implied Own%\"": "\"15%\"",
		"\"FD LEV\"": "\"1.55\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Geno Smith\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"7400\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.06\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jordan Love\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"SF\"",
		"\"FD Sal $\"": "\"7300\"",
		"\"Projected Own%\"": "\"10.0%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"16%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.57\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Aaron Jones\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"@CHI\"",
		"\"FD Sal $\"": "\"7300\"",
		"\"Projected Own%\"": "\"6.5%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"1.13\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jayden Reed\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"SF\"",
		"\"FD Sal $\"": "\"7300\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"1.08\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Matthew Stafford\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"PHI\"",
		"\"FD Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.21\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Marvin Harrison Jr.\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"10.5%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"0.70\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Travis Kelce\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"19%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"FD LEV\"": "\"1.82\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Sam Darnold\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"@CHI\"",
		"\"FD Sal $\"": "\"7100\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.79\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Chuba Hubbard\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"KC\"",
		"\"FD Sal $\"": "\"7100\"",
		"\"Projected Own%\"": "\"6.5%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"1.21\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Courtland Sutton\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"7100\"",
		"\"Projected Own%\"": "\"10.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"0.88\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Caleb Williams\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"MIN\"",
		"\"FD Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.58\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"D'Andre Swift\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"MIN\"",
		"\"FD Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"11.0%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"0.72\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tank Dell\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"9.0%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"0.96\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Drake Maye\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.36\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Rachaad White\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"@NYG\"",
		"\"FD Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.74\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Josh Downs\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"DET\"",
		"\"FD Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.75\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Bucky Irving\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"@NYG\"",
		"\"FD Sal $\"": "\"6800\"",
		"\"Projected Own%\"": "\"9.0%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.69\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jameson Williams\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@IND\"",
		"\"FD Sal $\"": "\"6800\"",
		"\"Projected Own%\"": "\"11.5%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"FD LEV\"": "\"1.04\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Will Levis\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@HOU\"",
		"\"FD Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.76\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tyrone Tracy\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"TB\"",
		"\"FD Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"13.0%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"10%\"",
		"\"FD LEV\"": "\"0.78\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jauan Jennings\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"0.89\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Trey McBride\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"12.0%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"19%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"FD LEV\"": "\"1.07\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Austin Ekeler\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.22\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Xavier Worthy\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.75\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Cade Otton\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"@NYG\"",
		"\"FD Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"2.16\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Gardner Minshew\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.61\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tony Pollard\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@HOU\"",
		"\"FD Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"12.0%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"0.63\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DeAndre Hopkins\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"9.5%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.48\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Cooper Rush\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.16\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Rhamondre Stevenson\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"0.59\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jakobi Meyers\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.52\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Rico Dowdle\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"10.5%\"",
		"\"Cash Odds\"": "\"38%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.29\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Calvin Ridley\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@HOU\"",
		"\"FD Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"13.0%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"FD LEV\"": "\"0.91\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Javonte Williams\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"6200\"",
		"\"Projected Own%\"": "\"9.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.40\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jordan Addison\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"@CHI\"",
		"\"FD Sal $\"": "\"6200\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.77\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Christian Watson\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"SF\"",
		"\"FD Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.31\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Dallas Goedert\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@LAR\"",
		"\"FD Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"6.5%\"",
		"\"Cash Odds\"": "\"38%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"1.00\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Tommy DeVito\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"TB\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"6.5%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.53\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Raheem Mostert\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.07\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"D.J. Moore\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"MIN\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"8.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.70\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"T.J. Hockenson\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"@CHI\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.92\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Cam Akers\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"@CHI\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"2%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jaylen Waddle\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"8.5%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.31\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Keenan Allen\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"MIN\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.52\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tyler Lockett\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.63\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Xavier Legette\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"KC\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"16%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.78\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Alec Pierce\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"DET\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"6.0%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.50\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Wan'Dale Robinson\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"TB\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.55\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Michael Pittman Jr.\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"DET\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.58\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Romeo Doubs\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"SF\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.45\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Ricky Pearsall\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.65\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Demarcus Robinson\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"PHI\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.38\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Jonnu Smith\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"10.0%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"16%\"",
		"\"Implied Own%\"": "\"10%\"",
		"\"FD LEV\"": "\"1.05\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Nick Westbrook-Ikhine\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@HOU\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"6.0%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.37\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Devaughn Vele\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.92\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"John Metchie\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"17%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.65\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Dalton Schultz\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.25\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Rome Odunze\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"MIN\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"8.0%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.53\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Noah Brown\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.48\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Demario Douglas\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.43\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Troy Franklin\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"9%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.19\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Tucker Kraft\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"SF\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"9.0%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"0.86\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Zach Charbonnet\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.26\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Darius Slayton\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"TB\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.32\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jalen Tolbert\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"18%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.16\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jalen Coker\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"KC\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"15%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.09\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Zach Ertz\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.40\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Devin Singletary\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"TB\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"14%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.47\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Michael Wilson\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.15\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tre Tucker\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.35\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Kendrick Bourne\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"15%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.21\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Hunter Henry\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"8.0%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.78\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Kayshon Boutte\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"17%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.15\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Cole Kmet\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"MIN\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.91\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Denver Broncos\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"1.70\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Ameer Abdullah\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"6.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.50\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Antonio Gibson\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"4%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DJ Turner\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"1.16\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Lil'Jordan Humphrey\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"14%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.31\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"JuJu Smith-Schuster\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"9%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.19\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Noah Gray\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.32\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Washington Commanders\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.43\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Adam Thielen\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"KC\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.16\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Justin Watson\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"7%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.06\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Ja'Tavion Sanders\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"KC\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.50\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"AJ Barner\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.53\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Austin Hooper\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"15%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.65\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Kansas City Chiefs\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@CAR\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"6.0%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"19%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"FD LEV\"": "\"1.95\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Dontayvion Wicks\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"SF\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"17%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.11\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tyler Boyd\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@HOU\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"12%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.07\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Theo Johnson\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"TB\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.98\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Josh Oliver\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"@CHI\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"17%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.63\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Minnesota Vikings\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"@CHI\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"6.0%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.88\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jaylen Wright\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"8%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.02\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"KaVontae Turpin\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"13%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.06\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Kalif Raymond\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@IND\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"13%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.11\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Chigoziem Okonkwo\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@HOU\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.62\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Houston Texans\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"1.06\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Luke McCaffrey\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"9%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.20\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Adam Trautman\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@LV\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"14%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.56\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Elijah Higgins\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"12%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.47\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Detroit Lions\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@IND\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.41\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Luke Schoonmaker\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.65\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Eric Saubert\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.18\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Shane Zylstra\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@IND\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"10%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.23\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Miami Dolphins\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"1.59\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jalen Brooks\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"11%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.26\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Davis Allen\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"PHI\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.36\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Tampa Bay Buccaneers\"",
		"\"Tm\"": "\"TB\"",
		"\"Opp\"": "\"@NYG\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"6.0%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"1.11\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Kyle Juszczyk\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"12%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.12\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"San Francisco 49ers\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.53\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Julius Chestnut\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@HOU\"",
		"\"FD Sal $\"": "\"4200\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"12%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.05\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Philadelphia Eagles\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@LAR\"",
		"\"FD Sal $\"": "\"4200\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"1.60\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Brevyn Spann-Ford\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"4100\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"18%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.22\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Los Angeles Rams\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"PHI\"",
		"\"FD Sal $\"": "\"4100\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.32\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Dylan Laube\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.06\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Sincere McCormick\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"15%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.09\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Tommy Tremble\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"KC\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"5%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Green Bay Packers\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"SF\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.10\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Chicago Bears\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"MIN\"",
		"\"FD Sal $\"": "\"3900\"",
		"\"Projected Own%\"": "\"6.0%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.88\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Seattle Seahawks\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"ARI\"",
		"\"FD Sal $\"": "\"3800\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.96\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"New England Patriots\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"3700\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.53\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Arizona Cardinals\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"3600\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.65\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Tennessee Titans\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@HOU\"",
		"\"FD Sal $\"": "\"3500\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.65\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Dallas Cowboys\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"3400\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.58\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"New York Giants\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"TB\"",
		"\"FD Sal $\"": "\"3300\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.89\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Las Vegas Raiders\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"3200\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.63\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Indianapolis Colts\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"DET\"",
		"\"FD Sal $\"": "\"3100\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.38\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Carolina Panthers\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"KC\"",
		"\"FD Sal $\"": "\"3000\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.52\""
	}
]

module.exports = gppLeverageScoresAndProjOwnershipFanduel;