const gppLeverageScoresAndProjOwnershipDraftkings = [
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Justin Jefferson\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"DET\"",
		"\"DK Sal $\"": "\"8500\"",
		"\"Projected Own%\"": "\"22.5%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"21%\"",
		"\"Implied Own%\"": "\"25%\"",
		"\"DK LEV\"": "\"1.13\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Ja'Marr Chase\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"DK Sal $\"": "\"8400\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"16%\"",
		"\"Implied Own%\"": "\"19%\"",
		"\"DK LEV\"": "\"7.67\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Amon-Ra St. Brown\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@MIN\"",
		"\"DK Sal $\"": "\"8300\"",
		"\"Projected Own%\"": "\"8.0%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"DK LEV\"": "\"1.37\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Saquon Barkley\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@NYG\"",
		"\"DK Sal $\"": "\"8200\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"17%\"",
		"\"DK LEV\"": "\"3.74\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Kyren Williams\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"LV\"",
		"\"DK Sal $\"": "\"8100\"",
		"\"Projected Own%\"": "\"23.5%\"",
		"\"Cash Odds\"": "\"50%\"",
		"\"GPP Odds\"": "\"21%\"",
		"\"Implied Own%\"": "\"24%\"",
		"\"DK LEV\"": "\"1.04\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"A.J. Brown\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@NYG\"",
		"\"DK Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"DK LEV\"": "\"2.29\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Stefon Diggs\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@GB\"",
		"\"DK Sal $\"": "\"7700\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"DK LEV\"": "\"2.49\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jayden Daniels\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"CAR\"",
		"\"DK Sal $\"": "\"7600\"",
		"\"Projected Own%\"": "\"23.0%\"",
		"\"Cash Odds\"": "\"51%\"",
		"\"GPP Odds\"": "\"19%\"",
		"\"Implied Own%\"": "\"16%\"",
		"\"DK LEV\"": "\"0.68\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jordan Mason\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"KC\"",
		"\"DK Sal $\"": "\"7600\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"15%\"",
		"\"DK LEV\"": "\"7.68\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Josh Allen\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"TEN\"",
		"\"DK Sal $\"": "\"7500\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"DK LEV\"": "\"3.07\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jalen Hurts\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@NYG\"",
		"\"DK Sal $\"": "\"7300\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"10%\"",
		"\"DK LEV\"": "\"1.30\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Kenneth Walker\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"@ATL\"",
		"\"DK Sal $\"": "\"7300\"",
		"\"Projected Own%\"": "\"34.5%\"",
		"\"Cash Odds\"": "\"51%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"15%\"",
		"\"DK LEV\"": "\"0.43\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tyreek Hill\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"@IND\"",
		"\"DK Sal $\"": "\"7300\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"DK LEV\"": "\"4.47\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Joe Mixon\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@GB\"",
		"\"DK Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"10.0%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"14%\"",
		"\"DK LEV\"": "\"1.40\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jayden Reed\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"HOU\"",
		"\"DK Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"11.5%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"18%\"",
		"\"DK LEV\"": "\"1.56\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"C.J. Stroud\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@GB\"",
		"\"DK Sal $\"": "\"7100\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"6.19\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Bijan Robinson\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"SEA\"",
		"\"DK Sal $\"": "\"7100\"",
		"\"Projected Own%\"": "\"27.5%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"17%\"",
		"\"Implied Own%\"": "\"19%\"",
		"\"DK LEV\"": "\"0.70\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Davante Adams\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"@PIT\"",
		"\"DK Sal $\"": "\"7100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"8.00\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Patrick Mahomes\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@SF\"",
		"\"DK Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"3.04\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Deebo Samuel\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"KC\"",
		"\"DK Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"DK LEV\"": "\"1.65\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jordan Love\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"HOU\"",
		"\"DK Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"DK LEV\"": "\"1.83\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jahmyr Gibbs\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@MIN\"",
		"\"DK Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"2.09\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Drake London\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"SEA\"",
		"\"DK Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"28.5%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"18%\"",
		"\"Implied Own%\"": "\"22%\"",
		"\"DK LEV\"": "\"0.75\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DeVonta Smith\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@NYG\"",
		"\"DK Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"DK LEV\"": "\"2.40\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Joe Burrow\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"DK Sal $\"": "\"6800\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"1.91\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Terry McLaurin\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"CAR\"",
		"\"DK Sal $\"": "\"6800\"",
		"\"Projected Own%\"": "\"12.0%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"16%\"",
		"\"DK LEV\"": "\"1.35\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DK Metcalf\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"@ATL\"",
		"\"DK Sal $\"": "\"6800\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"DK LEV\"": "\"1.67\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"De'Von Achane\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"@IND\"",
		"\"DK Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"DK LEV\"": "\"3.28\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"David Montgomery\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@MIN\"",
		"\"DK Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"11.57\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Diontae Johnson\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@WAS\"",
		"\"DK Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"15.5%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"15%\"",
		"\"DK LEV\"": "\"0.98\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jared Goff\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@MIN\"",
		"\"DK Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"2.60\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Chuba Hubbard\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@WAS\"",
		"\"DK Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"31.5%\"",
		"\"Cash Odds\"": "\"53%\"",
		"\"GPP Odds\"": "\"21%\"",
		"\"Implied Own%\"": "\"24%\"",
		"\"DK LEV\"": "\"0.75\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Aaron Jones\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"DET\"",
		"\"DK Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"16.5%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"10%\"",
		"\"DK LEV\"": "\"0.61\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tank Dell\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@GB\"",
		"\"DK Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"1.28\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Brock Purdy\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"KC\"",
		"\"DK Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"1.39\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Josh Jacobs\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"HOU\"",
		"\"DK Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"DK LEV\"": "\"1.10\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tee Higgins\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"DK Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"DK LEV\"": "\"0.93\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Xavier Worthy\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@SF\"",
		"\"DK Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"6.74\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Kirk Cousins\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"SEA\"",
		"\"DK Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"1.19\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tony Pollard\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@BUF\"",
		"\"DK Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"27.5%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"17%\"",
		"\"DK LEV\"": "\"0.61\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Brandon Aiyuk\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"KC\"",
		"\"DK Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"6.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"DK LEV\"": "\"1.29\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Travis Kelce\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@SF\"",
		"\"DK Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"10.5%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"20%\"",
		"\"DK LEV\"": "\"1.91\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Sam Darnold\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"DET\"",
		"\"DK Sal $\"": "\"6200\"",
		"\"Projected Own%\"": "\"9.0%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"0.44\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tyrone Tracy\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"PHI\"",
		"\"DK Sal $\"": "\"6200\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"DK LEV\"": "\"2.31\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Raheem Mostert\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"@IND\"",
		"\"DK Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"8%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.35\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Wan'Dale Robinson\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"PHI\"",
		"\"DK Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"4.64\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Anthony Richardson\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"MIA\"",
		"\"DK Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"6.0%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"0.82\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Kareem Hunt\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@SF\"",
		"\"DK Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"10.0%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"0.34\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Nick Chubb\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"CIN\"",
		"\"DK Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"7%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.19\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"George Kittle\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"KC\"",
		"\"DK Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"19%\"",
		"\"DK LEV\"": "\"6.43\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Austin Ekeler\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"CAR\"",
		"\"DK Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"DK LEV\"": "\"2.45\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Chase Brown\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"DK Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"1.54\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jaxon Smith-Njigba\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"@ATL\"",
		"\"DK Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"2.50\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Geno Smith\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"@ATL\"",
		"\"DK Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"11.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"0.46\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Zack Moss\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"DK Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"DK LEV\"": "\"2.46\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Amari Cooper\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"TEN\"",
		"\"DK Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"14%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"DK LEV\"": "\"2.46\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Brock Bowers\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"@LAR\"",
		"\"DK Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"19.0%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"23%\"",
		"\"DK LEV\"": "\"1.21\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Ty Johnson\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"TEN\"",
		"\"DK Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"3%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.02\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Josh Downs\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"MIA\"",
		"\"DK Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"12.0%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"0.43\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Matthew Stafford\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"LV\"",
		"\"DK Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"1.81\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Ty Chandler\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"DET\"",
		"\"DK Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"7%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.32\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Darnell Mooney\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"SEA\"",
		"\"DK Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"11.0%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"0.49\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jordan Addison\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"DET\"",
		"\"DK Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"1.98\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Trey Sermon\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"MIA\"",
		"\"DK Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"0.80\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Alexander Mattison\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"@LAR\"",
		"\"DK Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"9.5%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"0.19\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Romeo Doubs\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"HOU\"",
		"\"DK Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"1.80\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Calvin Ridley\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@BUF\"",
		"\"DK Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"16%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"DK LEV\"": "\"1.89\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Daniel Jones\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"PHI\"",
		"\"DK Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"24%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"0.34\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Keon Coleman\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"TEN\"",
		"\"DK Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"17%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"3.48\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"D'Onta Foreman\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"CIN\"",
		"\"DK Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"12%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.68\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Zach Charbonnet\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"@ATL\"",
		"\"DK Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"8%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.30\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tyler Lockett\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"@ATL\"",
		"\"DK Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"5.05\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jaylen Waddle\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"@IND\"",
		"\"DK Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"23%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"1.15\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Sam LaPorta\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@MIN\"",
		"\"DK Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"9.23\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Andy Dalton\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@WAS\"",
		"\"DK Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"1.26\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Ray Davis\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"TEN\"",
		"\"DK Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"13.0%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"16%\"",
		"\"Implied Own%\"": "\"18%\"",
		"\"DK LEV\"": "\"1.38\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Alec Pierce\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"MIA\"",
		"\"DK Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"15%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"DK LEV\"": "\"2.49\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Tyler Huntley\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"@IND\"",
		"\"DK Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"0.26\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tyler Allgeier\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"SEA\"",
		"\"DK Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"18%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"DK LEV\"": "\"2.49\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Darius Slayton\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"PHI\"",
		"\"DK Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"8.49\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Xavier Legette\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@WAS\"",
		"\"DK Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"18%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"DK LEV\"": "\"2.71\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DeAndre Hopkins\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@BUF\"",
		"\"DK Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"3.99\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tutu Atwell\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"LV\"",
		"\"DK Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"8.0%\"",
		"\"Cash Odds\"": "\"14%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.05\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Dalton Kincaid\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"TEN\"",
		"\"DK Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"10.10\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Deshaun Watson\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"CIN\"",
		"\"DK Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"0.40\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Christian Watson\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"HOU\"",
		"\"DK Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"2.91\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Aidan O'Connell\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"@LAR\"",
		"\"DK Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"0.87\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Pierre Strong Jr.\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"CIN\"",
		"\"DK Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"4%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jerry Jeudy\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"CIN\"",
		"\"DK Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"9.5%\"",
		"\"Cash Odds\"": "\"24%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"0.22\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jordan Whittington\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"LV\"",
		"\"DK Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"19.0%\"",
		"\"Cash Odds\"": "\"13%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.03\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Will Levis\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@BUF\"",
		"\"DK Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"3.07\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Demarcus Robinson\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"LV\"",
		"\"DK Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"DK LEV\"": "\"2.75\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jauan Jennings\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"KC\"",
		"\"DK Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"13%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.88\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Tucker Kraft\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"HOU\"",
		"\"DK Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"1.80\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Miles Sanders\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@WAS\"",
		"\"DK Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"15%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.90\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Emanuel Wilson\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"HOU\"",
		"\"DK Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"2%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jalen Nailor\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"DET\"",
		"\"DK Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"6%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.16\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Kyle Pitts\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"SEA\"",
		"\"DK Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"6.5%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"DK LEV\"": "\"1.04\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Ray-Ray McCloud\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"SEA\"",
		"\"DK Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"15.5%\"",
		"\"Cash Odds\"": "\"16%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.03\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Curtis Samuel\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"TEN\"",
		"\"DK Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"1%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tre Tucker\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"@LAR\"",
		"\"DK Sal $\"": "\"4200\"",
		"\"Projected Own%\"": "\"10.0%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"DK LEV\"": "\"0.12\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Dalton Schultz\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@GB\"",
		"\"DK Sal $\"": "\"4200\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"1.02\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"David Njoku\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"CIN\"",
		"\"DK Sal $\"": "\"4100\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"0.26\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"JuJu Smith-Schuster\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@SF\"",
		"\"DK Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"17.0%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"DK LEV\"": "\"0.44\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Noah Brown\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"CAR\"",
		"\"DK Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"DK LEV\"": "\"0.25\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tyler Boyd\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@BUF\"",
		"\"DK Sal $\"": "\"3900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"10%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.34\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Zach Ertz\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"CAR\"",
		"\"DK Sal $\"": "\"3900\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"DK LEV\"": "\"1.67\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Andrei Iosivas\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"DK Sal $\"": "\"3800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"10%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.24\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Colby Parkinson\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"LV\"",
		"\"DK Sal $\"": "\"3800\"",
		"\"Projected Own%\"": "\"27.0%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"0.09\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Adonai Mitchell\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"MIA\"",
		"\"DK Sal $\"": "\"3700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"11%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.31\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Justin Watson\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@SF\"",
		"\"DK Sal $\"": "\"3700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"5%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.07\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Olamide Zaccheaus\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"CAR\"",
		"\"DK Sal $\"": "\"3600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"13%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"DK LEV\"": "\"1.15\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Philadelphia Eagles\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@NYG\"",
		"\"DK Sal $\"": "\"3600\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"18%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"2.09\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tim Patrick\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@MIN\"",
		"\"DK Sal $\"": "\"3500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"1%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Noah Fant\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"@ATL\"",
		"\"DK Sal $\"": "\"3500\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"DK LEV\"": "\"1.44\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Buffalo Bills\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"TEN\"",
		"\"DK Sal $\"": "\"3500\"",
		"\"Projected Own%\"": "\"15.5%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"25%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"DK LEV\"": "\"0.48\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Xavier Hutchinson\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@GB\"",
		"\"DK Sal $\"": "\"3400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"17%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"DK LEV\"": "\"1.81\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DJ Turner\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"@LAR\"",
		"\"DK Sal $\"": "\"3400\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"11%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.04\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Jonnu Smith\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"@IND\"",
		"\"DK Sal $\"": "\"3400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"14%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.20\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Washington Commanders\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"CAR\"",
		"\"DK Sal $\"": "\"3400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"6.38\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Cincinnati Bengals\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"DK Sal $\"": "\"3300\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"18%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"0.44\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Elijah Moore\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"CIN\"",
		"\"DK Sal $\"": "\"3200\"",
		"\"Projected Own%\"": "\"20.0%\"",
		"\"Cash Odds\"": "\"9%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Grant Calcaterra\"",
		"\"Tm\"": "\"PHI\"",
		"\"Opp\"": "\"@NYG\"",
		"\"DK Sal $\"": "\"3200\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"DK LEV\"": "\"0.35\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Indianapolis Colts\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"MIA\"",
		"\"DK Sal $\"": "\"3200\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"18%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"2.13\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Chigoziem Okonkwo\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@BUF\"",
		"\"DK Sal $\"": "\"3100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"9%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.13\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Atlanta Falcons\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"SEA\"",
		"\"DK Sal $\"": "\"3100\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"2.52\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Kansas City Chiefs\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@SF\"",
		"\"DK Sal $\"": "\"3100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"4.77\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jalen Coker\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@WAS\"",
		"\"DK Sal $\"": "\"3000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"14%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.13\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Cedric Tillman\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"CIN\"",
		"\"DK Sal $\"": "\"3000\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"2%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Mike Gesicki\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"DK Sal $\"": "\"3000\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.30\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Los Angeles Rams\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"LV\"",
		"\"DK Sal $\"": "\"3000\"",
		"\"Projected Own%\"": "\"9.0%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"22%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"0.71\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"San Francisco 49ers\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"KC\"",
		"\"DK Sal $\"": "\"3000\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"3.47\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Ja'Tavion Sanders\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@WAS\"",
		"\"DK Sal $\"": "\"2900\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.16\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Green Bay Packers\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"HOU\"",
		"\"DK Sal $\"": "\"2900\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"1.71\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Minnesota Vikings\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"DET\"",
		"\"DK Sal $\"": "\"2900\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"16%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"4.84\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Theo Johnson\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"PHI\"",
		"\"DK Sal $\"": "\"2800\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"24%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"DK LEV\"": "\"0.38\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Noah Gray\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@SF\"",
		"\"DK Sal $\"": "\"2800\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"16%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.12\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Johnny Mundt\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"DET\"",
		"\"DK Sal $\"": "\"2800\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"0%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Detroit Lions\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"@MIN\"",
		"\"DK Sal $\"": "\"2800\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"0.62\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Miami Dolphins\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"@IND\"",
		"\"DK Sal $\"": "\"2800\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"16%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"0.94\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Erick All\"",
		"\"Tm\"": "\"CIN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"DK Sal $\"": "\"2700\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"10%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"DK LEV\"": "\"0.02\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Las Vegas Raiders\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"@LAR\"",
		"\"DK Sal $\"": "\"2700\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"2.40\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Houston Texans\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@GB\"",
		"\"DK Sal $\"": "\"2600\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"1.43\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Seattle Seahawks\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"@ATL\"",
		"\"DK Sal $\"": "\"2600\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"1.07\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Cleveland Browns\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"CIN\"",
		"\"DK Sal $\"": "\"2500\"",
		"\"Projected Own%\"": "\"8.0%\"",
		"\"Cash Odds\"": "\"38%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"0.57\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"New York Giants\"",
		"\"Tm\"": "\"NYG\"",
		"\"Opp\"": "\"PHI\"",
		"\"DK Sal $\"": "\"2500\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"17%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"0.72\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Carolina Panthers\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@WAS\"",
		"\"DK Sal $\"": "\"2400\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"1.06\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Tennessee Titans\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@BUF\"",
		"\"DK Sal $\"": "\"2300\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"17%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"1.40\""
	}
]

module.exports = gppLeverageScoresAndProjOwnershipDraftkings;