const gppLeverageScoresAndProjOwnershipDraftkings = [
  {
    '"Pos"': '"WR"',
    '"Player"': '"Justin Jefferson"',
    '"Tm"': '"MIN"',
    '"Opp"': '"@GB"',
    '"DK Sal $"': '"9500"',
    '"Projected Own%"': '"12.5%"',
    '"Cash Odds"': '"58%"',
    '"GPP Odds"': '"23%"',
    '"Implied Own%"': '"26%"',
    '"DK LEV"': '"2.08"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Christian McCaffrey"',
    '"Tm"': '"SF"',
    '"Opp"': '"@LV"',
    '"DK Sal $"': '"9000"',
    '"Projected Own%"': '"22.5%"',
    '"Cash Odds"': '"61%"',
    '"GPP Odds"': '"28%"',
    '"Implied Own%"': '"32%"',
    '"DK LEV"': '"1.41"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Tyreek Hill"',
    '"Tm"': '"MIA"',
    '"Opp"': '"@NE"',
    '"DK Sal $"': '"8900"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"46%"',
    '"GPP Odds"': '"14%"',
    '"Implied Own%"': '"15%"',
    '"DK LEV"': '"2.06"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Austin Ekeler"',
    '"Tm"': '"LAC"',
    '"Opp"': '"LAR"',
    '"DK Sal $"': '"8500"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"43%"',
    '"GPP Odds"': '"13%"',
    '"Implied Own%"': '"15%"',
    '"DK LEV"': '"2.05"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Davante Adams"',
    '"Tm"': '"LV"',
    '"Opp"': '"SF"',
    '"DK Sal $"': '"8500"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"35%"',
    '"GPP Odds"': '"8%"',
    '"Implied Own%"': '"9%"',
    '"DK LEV"': '"3.13"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Patrick Mahomes"',
    '"Tm"': '"KC"',
    '"Opp"': '"DEN"',
    '"DK Sal $"': '"8500"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"50%"',
    '"GPP Odds"': '"22%"',
    '"Implied Own%"': '"9%"',
    '"DK LEV"': '"1.16"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Travis Kelce"',
    '"Tm"': '"KC"',
    '"Opp"': '"DEN"',
    '"DK Sal $"': '"8100"',
    '"Projected Own%"': '"12.5%"',
    '"Cash Odds"': '"49%"',
    '"GPP Odds"': '"10%"',
    '"Implied Own%"': '"19%"',
    '"DK LEV"': '"1.50"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Saquon Barkley"',
    '"Tm"': '"NYG"',
    '"Opp"': '"IND"',
    '"DK Sal $"': '"8000"',
    '"Projected Own%"': '"17.5%"',
    '"Cash Odds"': '"47%"',
    '"GPP Odds"': '"15%"',
    '"Implied Own%"': '"17%"',
    '"DK LEV"': '"0.98"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"A.J. Brown"',
    '"Tm"': '"PHI"',
    '"Opp"': '"NO"',
    '"DK Sal $"': '"7900"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"43%"',
    '"GPP Odds"': '"13%"',
    '"Implied Own%"': '"14%"',
    '"DK LEV"': '"1.88"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Justin Fields"',
    '"Tm"': '"CHI"',
    '"Opp"': '"@DET"',
    '"DK Sal $"': '"7900"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"47%"',
    '"GPP Odds"': '"20%"',
    '"Implied Own%"': '"8%"',
    '"DK LEV"': '"1.05"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Amon-Ra St. Brown"',
    '"Tm"': '"DET"',
    '"Opp"': '"CHI"',
    '"DK Sal $"': '"7800"',
    '"Projected Own%"': '"37.5%"',
    '"Cash Odds"': '"50%"',
    '"GPP Odds"': '"16%"',
    '"Implied Own%"': '"18%"',
    '"DK LEV"': '"0.48"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"DeAndre Hopkins"',
    '"Tm"': '"ARI"',
    '"Opp"': '"@ATL"',
    '"DK Sal $"': '"7700"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"36%"',
    '"GPP Odds"': '"8%"',
    '"Implied Own%"': '"9%"',
    '"DK LEV"': '"2.91"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Jaylen Waddle"',
    '"Tm"': '"MIA"',
    '"Opp"': '"@NE"',
    '"DK Sal $"': '"7500"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"33%"',
    '"GPP Odds"': '"7%"',
    '"Implied Own%"': '"8%"',
    '"DK LEV"': '"2.60"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Josh Jacobs"',
    '"Tm"': '"LV"',
    '"Opp"': '"SF"',
    '"DK Sal $"': '"7400"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"30%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"2.12"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Nick Chubb"',
    '"Tm"': '"CLE"',
    '"Opp"': '"@WAS"',
    '"DK Sal $"': '"7300"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"36%"',
    '"GPP Odds"': '"8%"',
    '"Implied Own%"': '"9%"',
    '"DK LEV"': '"3.09"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"James Conner"',
    '"Tm"': '"ARI"',
    '"Opp"': '"@ATL"',
    '"DK Sal $"': '"7200"',
    '"Projected Own%"': '"12.5%"',
    '"Cash Odds"': '"43%"',
    '"GPP Odds"': '"11%"',
    '"Implied Own%"': '"13%"',
    '"DK LEV"': '"1.00"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"DeVonta Smith"',
    '"Tm"': '"PHI"',
    '"Opp"': '"NO"',
    '"DK Sal $"': '"7100"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"32%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"7%"',
    '"DK LEV"': '"2.24"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Aaron Jones"',
    '"Tm"': '"GB"',
    '"Opp"': '"MIN"',
    '"DK Sal $"': '"7100"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"30%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"1.91"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Justin Herbert"',
    '"Tm"': '"LAC"',
    '"Opp"': '"LAR"',
    '"DK Sal $"': '"7100"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"41%"',
    '"GPP Odds"': '"13%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"1.79"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Dalvin Cook"',
    '"Tm"': '"MIN"',
    '"Opp"': '"@GB"',
    '"DK Sal $"': '"7000"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"42%"',
    '"GPP Odds"': '"10%"',
    '"Implied Own%"': '"12%"',
    '"DK LEV"': '"1.55"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Keenan Allen"',
    '"Tm"': '"LAC"',
    '"Opp"': '"LAR"',
    '"DK Sal $"': '"7000"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"41%"',
    '"GPP Odds"': '"9%"',
    '"Implied Own%"': '"10%"',
    '"DK LEV"': '"1.40"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Alvin Kamara"',
    '"Tm"': '"NO"',
    '"Opp"': '"@PHI"',
    '"DK Sal $"': '"6900"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"42%"',
    '"GPP Odds"': '"9%"',
    '"Implied Own%"': '"10%"',
    '"DK LEV"': '"3.44"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"David Montgomery"',
    '"Tm"': '"CHI"',
    '"Opp"': '"@DET"',
    '"DK Sal $"': '"6900"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"33%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"7%"',
    '"DK LEV"': '"2.35"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"DK Metcalf"',
    '"Tm"': '"SEA"',
    '"Opp"': '"NYJ"',
    '"DK Sal $"': '"6900"',
    '"Projected Own%"': '"12.5%"',
    '"Cash Odds"': '"31%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"0.50"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Chris Godwin"',
    '"Tm"': '"TB"',
    '"Opp"': '"CAR"',
    '"DK Sal $"': '"6800"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"36%"',
    '"GPP Odds"': '"7%"',
    '"Implied Own%"': '"8%"',
    '"DK LEV"': '"1.05"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Rhamondre Stevenson"',
    '"Tm"': '"NE"',
    '"Opp"': '"MIA"',
    '"DK Sal $"': '"6800"',
    '"Projected Own%"': '"22.5%"',
    '"Cash Odds"': '"49%"',
    '"GPP Odds"': '"13%"',
    '"Implied Own%"': '"15%"',
    '"DK LEV"': '"0.68"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Mike Williams"',
    '"Tm"': '"LAC"',
    '"Opp"': '"LAR"',
    '"DK Sal $"': '"6700"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"35%"',
    '"GPP Odds"': '"7%"',
    '"Implied Own%"': '"8%"',
    '"DK LEV"': '"2.66"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Tyler Lockett"',
    '"Tm"': '"SEA"',
    '"Opp"': '"NYJ"',
    '"DK Sal $"': '"6600"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"31%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"1.98"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Mike Evans"',
    '"Tm"': '"TB"',
    '"Opp"': '"CAR"',
    '"DK Sal $"': '"6500"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"30%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"1.83"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Jerry Jeudy"',
    '"Tm"': '"DEN"',
    '"Opp"': '"@KC"',
    '"DK Sal $"': '"6400"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"38%"',
    '"GPP Odds"': '"8%"',
    '"Implied Own%"': '"9%"',
    '"DK LEV"': '"2.88"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Kirk Cousins"',
    '"Tm"': '"MIN"',
    '"Opp"': '"@GB"',
    '"DK Sal $"': '"6400"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"39%"',
    '"GPP Odds"': '"12%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"1.56"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Travis Etienne"',
    '"Tm"': '"JAX"',
    '"Opp"': '"@HOU"',
    '"DK Sal $"': '"6400"',
    '"Projected Own%"': '"22.5%"',
    '"Cash Odds"': '"42%"',
    '"GPP Odds"': '"9%"',
    '"Implied Own%"': '"11%"',
    '"DK LEV"': '"0.47"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Brandon Aiyuk"',
    '"Tm"': '"SF"',
    '"Opp"': '"@LV"',
    '"DK Sal $"': '"6300"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"34%"',
    '"GPP Odds"': '"7%"',
    '"Implied Own%"': '"8%"',
    '"DK LEV"': '"1.00"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Michael Pittman Jr."',
    '"Tm"': '"IND"',
    '"Opp"': '"@NYG"',
    '"DK Sal $"': '"6200"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"28%"',
    '"GPP Odds"': '"4%"',
    '"Implied Own%"': '"4%"',
    '"DK LEV"': '"1.49"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Ken Walker"',
    '"Tm"': '"SEA"',
    '"Opp"': '"NYJ"',
    '"DK Sal $"': '"6200"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"36%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"7%"',
    '"DK LEV"': '"0.97"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Trevor Lawrence"',
    '"Tm"': '"JAX"',
    '"Opp"': '"@HOU"',
    '"DK Sal $"': '"6200"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"44%"',
    '"GPP Odds"': '"17%"',
    '"Implied Own%"': '"7%"',
    '"DK LEV"': '"0.88"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Cam Akers"',
    '"Tm"': '"LAR"',
    '"Opp"': '"@LAC"',
    '"DK Sal $"': '"6100"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"38%"',
    '"GPP Odds"': '"7%"',
    '"Implied Own%"': '"8%"',
    '"DK LEV"': '"2.56"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Terry McLaurin"',
    '"Tm"': '"WAS"',
    '"Opp"': '"CLE"',
    '"DK Sal $"': '"6100"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"33%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"2.04"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Chris Olave"',
    '"Tm"': '"NO"',
    '"Opp"': '"@PHI"',
    '"DK Sal $"': '"6100"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"31%"',
    '"GPP Odds"': '"4%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"1.68"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Tom Brady"',
    '"Tm"': '"TB"',
    '"Opp"': '"CAR"',
    '"DK Sal $"': '"6100"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"37%"',
    '"GPP Odds"': '"10%"',
    '"Implied Own%"': '"4%"',
    '"DK LEV"': '"1.32"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Christian Kirk"',
    '"Tm"': '"JAX"',
    '"Opp"': '"@HOU"',
    '"DK Sal $"': '"6000"',
    '"Projected Own%"': '"12.5%"',
    '"Cash Odds"': '"34%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"7%"',
    '"DK LEV"': '"0.56"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Jerick McKinnon"',
    '"Tm"': '"KC"',
    '"Opp"': '"DEN"',
    '"DK Sal $"': '"6000"',
    '"Projected Own%"': '"12.5%"',
    '"Cash Odds"': '"39%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"7%"',
    '"DK LEV"': '"0.57"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Aaron Rodgers"',
    '"Tm"': '"GB"',
    '"Opp"': '"MIN"',
    '"DK Sal $"': '"6000"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"37%"',
    '"GPP Odds"': '"10%"',
    '"Implied Own%"': '"4%"',
    '"DK LEV"': '"0.53"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Christian Watson"',
    '"Tm"': '"GB"',
    '"Opp"': '"MIN"',
    '"DK Sal $"': '"5900"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"31%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"2.16"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"George Kittle"',
    '"Tm"': '"SF"',
    '"Opp"': '"@LV"',
    '"DK Sal $"': '"5900"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"45%"',
    '"GPP Odds"': '"7%"',
    '"Implied Own%"': '"13%"',
    '"DK LEV"': '"1.72"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Geno Smith"',
    '"Tm"': '"SEA"',
    '"Opp"': '"NYJ"',
    '"DK Sal $"': '"5900"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"33%"',
    '"GPP Odds"': '"9%"',
    '"Implied Own%"': '"4%"',
    '"DK LEV"': '"1.23"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Miles Sanders"',
    '"Tm"': '"PHI"',
    '"Opp"': '"NO"',
    '"DK Sal $"': '"5900"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"31%"',
    '"GPP Odds"': '"4%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"0.66"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Amari Cooper"',
    '"Tm"': '"CLE"',
    '"Opp"': '"@WAS"',
    '"DK Sal $"': '"5800"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"33%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"1.99"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"A.J. Dillon"',
    '"Tm"': '"GB"',
    '"Opp"': '"MIN"',
    '"DK Sal $"': '"5800"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"25%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"1.05"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Deshaun Watson"',
    '"Tm"': '"CLE"',
    '"Opp"': '"@WAS"',
    '"DK Sal $"': '"5800"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"27%"',
    '"GPP Odds"': '"7%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"0.87"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"D.J. Moore"',
    '"Tm"': '"CAR"',
    '"Opp"': '"@TB"',
    '"DK Sal $"': '"5700"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"34%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"7%"',
    '"DK LEV"': '"2.36"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Daniel Jones"',
    '"Tm"': '"NYG"',
    '"Opp"': '"IND"',
    '"DK Sal $"': '"5700"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"43%"',
    '"GPP Odds"': '"15%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"0.78"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"D\'Onta Foreman"',
    '"Tm"': '"CAR"',
    '"Opp"': '"@TB"',
    '"DK Sal $"': '"5700"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"23%"',
    '"GPP Odds"': '"2%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"0.72"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Leonard Fournette"',
    '"Tm"': '"TB"',
    '"Opp"': '"CAR"',
    '"DK Sal $"': '"5600"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"39%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"7%"',
    '"DK LEV"': '"2.24"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Isiah Pacheco"',
    '"Tm"': '"KC"',
    '"Opp"': '"DEN"',
    '"DK Sal $"': '"5600"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"33%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"1.79"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"JuJu Smith-Schuster"',
    '"Tm"': '"KC"',
    '"Opp"': '"DEN"',
    '"DK Sal $"': '"5600"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"34%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"0.82"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Jared Goff"',
    '"Tm"': '"DET"',
    '"Opp"': '"CHI"',
    '"DK Sal $"': '"5600"',
    '"Projected Own%"': '"17.5%"',
    '"Cash Odds"': '"45%"',
    '"GPP Odds"': '"14%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"0.31"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Raheem Mostert"',
    '"Tm"': '"MIA"',
    '"Opp"': '"@NE"',
    '"DK Sal $"': '"5500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"17%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"2.67"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Latavius Murray"',
    '"Tm"': '"DEN"',
    '"Opp"': '"@KC"',
    '"DK Sal $"': '"5500"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"16%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"0.36"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Marquise Brown"',
    '"Tm"': '"ARI"',
    '"Opp"': '"@ATL"',
    '"DK Sal $"': '"5500"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"33%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"1.88"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Deon Jackson"',
    '"Tm"': '"IND"',
    '"Opp"': '"@NYG"',
    '"DK Sal $"': '"5500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"11%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.91"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Gardner Minshew"',
    '"Tm"': '"PHI"',
    '"Opp"': '"NO"',
    '"DK Sal $"': '"5500"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"42%"',
    '"GPP Odds"': '"14%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"0.74"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Brock Purdy"',
    '"Tm"': '"SF"',
    '"Opp"': '"@LV"',
    '"DK Sal $"': '"5500"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"40%"',
    '"GPP Odds"': '"13%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"0.68"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Rachaad White"',
    '"Tm"': '"TB"',
    '"Opp"': '"CAR"',
    '"DK Sal $"': '"5500"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"23%"',
    '"GPP Odds"': '"2%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"0.70"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Garrett Wilson"',
    '"Tm"': '"NYJ"',
    '"Opp"': '"@SEA"',
    '"DK Sal $"': '"5500"',
    '"Projected Own%"': '"17.5%"',
    '"Cash Odds"': '"41%"',
    '"GPP Odds"': '"8%"',
    '"Implied Own%"': '"9%"',
    '"DK LEV"': '"0.53"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Russell Wilson"',
    '"Tm"': '"DEN"',
    '"Opp"': '"@KC"',
    '"DK Sal $"': '"5400"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"29%"',
    '"GPP Odds"': '"7%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"5.60"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Cordarrelle Patterson"',
    '"Tm"': '"ATL"',
    '"Opp"': '"ARI"',
    '"DK Sal $"': '"5400"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"18%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"3.00"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Jeff Wilson"',
    '"Tm"': '"MIA"',
    '"Opp"': '"@NE"',
    '"DK Sal $"': '"5400"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"15%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.80"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Zack Moss"',
    '"Tm"': '"IND"',
    '"Opp"': '"@NYG"',
    '"DK Sal $"': '"5400"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"27%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"4%"',
    '"DK LEV"': '"1.22"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"T.J. Hockenson"',
    '"Tm"': '"MIN"',
    '"Opp"': '"@GB"',
    '"DK Sal $"': '"5400"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"41%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"9%"',
    '"DK LEV"': '"1.19"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Mike White"',
    '"Tm"': '"NYJ"',
    '"Opp"': '"@SEA"',
    '"DK Sal $"': '"5400"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"32%"',
    '"GPP Odds"': '"8%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"1.06"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Allen Lazard"',
    '"Tm"': '"GB"',
    '"Opp"': '"MIN"',
    '"DK Sal $"': '"5400"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"33%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"0.84"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Josh Palmer"',
    '"Tm"': '"LAC"',
    '"Opp"': '"LAR"',
    '"DK Sal $"': '"5300"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"23%"',
    '"GPP Odds"': '"2%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"5.29"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Baker Mayfield"',
    '"Tm"': '"LAR"',
    '"Opp"': '"@LAC"',
    '"DK Sal $"': '"5300"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"27%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"4.97"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Tyler Allgeier"',
    '"Tm"': '"ATL"',
    '"Opp"': '"ARI"',
    '"DK Sal $"': '"5300"',
    '"Projected Own%"': '"17.5%"',
    '"Cash Odds"': '"41%"',
    '"GPP Odds"': '"7%"',
    '"Implied Own%"': '"8%"',
    '"DK LEV"': '"0.47"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"D\'Andre Swift"',
    '"Tm"': '"DET"',
    '"Opp"': '"CHI"',
    '"DK Sal $"': '"5300"',
    '"Projected Own%"': '"12.5%"',
    '"Cash Odds"': '"36%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"0.45"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Joshua Kelley"',
    '"Tm"': '"LAC"',
    '"Opp"': '"LAR"',
    '"DK Sal $"': '"5300"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"6%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.22"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Colt McCoy"',
    '"Tm"': '"ARI"',
    '"Opp"': '"@ATL"',
    '"DK Sal $"': '"5200"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"29%"',
    '"GPP Odds"': '"7%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"5.55"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Nick Foles"',
    '"Tm"': '"IND"',
    '"Opp"': '"@NYG"',
    '"DK Sal $"': '"5200"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"24%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"3.96"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Adam Thielen"',
    '"Tm"': '"MIN"',
    '"Opp"': '"@GB"',
    '"DK Sal $"': '"5200"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"23%"',
    '"GPP Odds"': '"2%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"0.92"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Brian Robinson"',
    '"Tm"': '"WAS"',
    '"Opp"': '"CLE"',
    '"DK Sal $"': '"5200"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"36%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"0.69"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Carson Wentz"',
    '"Tm"': '"WAS"',
    '"Opp"': '"CLE"',
    '"DK Sal $"': '"5100"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"28%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"4.89"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Michael Carter"',
    '"Tm"': '"NYJ"',
    '"Opp"': '"@SEA"',
    '"DK Sal $"': '"5100"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"19%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"2.95"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Courtland Sutton"',
    '"Tm"': '"DEN"',
    '"Opp"': '"@KC"',
    '"DK Sal $"': '"5100"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"27%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"1.09"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Zonovan Knight"',
    '"Tm"': '"NYJ"',
    '"Opp"': '"@SEA"',
    '"DK Sal $"': '"5100"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"38%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"0.85"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Davis Mills"',
    '"Tm"': '"HOU"',
    '"Opp"': '"JAX"',
    '"DK Sal $"': '"5000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"26%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"4.58"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Desmond Ridder"',
    '"Tm"': '"ATL"',
    '"Opp"': '"ARI"',
    '"DK Sal $"': '"5000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"25%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"4.50"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Jakobi Meyers"',
    '"Tm"': '"NE"',
    '"Opp"': '"MIA"',
    '"DK Sal $"': '"5000"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"34%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"2.01"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Antonio Gibson"',
    '"Tm"': '"WAS"',
    '"Opp"': '"CLE"',
    '"DK Sal $"': '"5000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"14%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.52"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Teddy Bridgewater"',
    '"Tm"': '"MIA"',
    '"Opp"': '"@NE"',
    '"DK Sal $"': '"5000"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"32%"',
    '"GPP Odds"': '"8%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"1.10"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Mac Jones"',
    '"Tm"': '"NE"',
    '"Opp"': '"MIA"',
    '"DK Sal $"': '"5000"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"31%"',
    '"GPP Odds"': '"7%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"0.99"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Jamaal Williams"',
    '"Tm"': '"DET"',
    '"Opp"': '"CHI"',
    '"DK Sal $"': '"5000"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"25%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"0.96"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Sam Darnold"',
    '"Tm"': '"CAR"',
    '"Opp"': '"@TB"',
    '"DK Sal $"': '"5000"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"27%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"0.86"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Zay Jones"',
    '"Tm"': '"JAX"',
    '"Opp"': '"@HOU"',
    '"DK Sal $"': '"5000"',
    '"Projected Own%"': '"17.5%"',
    '"Cash Odds"': '"36%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"7%"',
    '"DK LEV"': '"0.39"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Jeff Driskel"',
    '"Tm"': '"HOU"',
    '"Opp"': '"JAX"',
    '"DK Sal $"': '"5000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"5%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.27"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Chuba Hubbard"',
    '"Tm"': '"CAR"',
    '"Opp"': '"@TB"',
    '"DK Sal $"': '"4900"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"28%"',
    '"GPP Odds"': '"2%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"5.70"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Darius Slayton"',
    '"Tm"': '"NYG"',
    '"Opp"': '"IND"',
    '"DK Sal $"': '"4900"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"31%"',
    '"GPP Odds"': '"4%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"1.63"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Taysom Hill"',
    '"Tm"': '"NO"',
    '"Opp"': '"@PHI"',
    '"DK Sal $"': '"4900"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"17%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.08"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Drake London"',
    '"Tm"': '"ATL"',
    '"Opp"': '"ARI"',
    '"DK Sal $"': '"4900"',
    '"Projected Own%"': '"22.5%"',
    '"Cash Odds"': '"38%"',
    '"GPP Odds"': '"7%"',
    '"Implied Own%"': '"7%"',
    '"DK LEV"': '"0.33"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Andy Dalton"',
    '"Tm"': '"NO"',
    '"Opp"': '"@PHI"',
    '"DK Sal $"': '"4800"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"25%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"3.77"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Brandin Cooks"',
    '"Tm"': '"HOU"',
    '"Opp"': '"JAX"',
    '"DK Sal $"': '"4800"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"34%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"0.73"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Rex Burkhead"',
    '"Tm"': '"HOU"',
    '"Opp"': '"JAX"',
    '"DK Sal $"': '"4800"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"7%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.26"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Donovan Peoples-Jones"',
    '"Tm"': '"CLE"',
    '"Opp"': '"@WAS"',
    '"DK Sal $"': '"4700"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"28%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"4%"',
    '"DK LEV"': '"1.24"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Romeo Doubs"',
    '"Tm"': '"GB"',
    '"Opp"': '"MIN"',
    '"DK Sal $"': '"4700"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"26%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"4%"',
    '"DK LEV"': '"1.19"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Dallas Goedert"',
    '"Tm"': '"PHI"',
    '"Opp"': '"NO"',
    '"DK Sal $"': '"4700"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"41%"',
    '"GPP Odds"': '"4%"',
    '"Implied Own%"': '"8%"',
    '"DK LEV"': '"1.11"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"K.J. Osborn"',
    '"Tm"': '"MIN"',
    '"Opp"': '"@GB"',
    '"DK Sal $"': '"4600"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"27%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"6.84"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Parris Campbell"',
    '"Tm"': '"IND"',
    '"Opp"': '"@NYG"',
    '"DK Sal $"': '"4600"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"20%"',
    '"GPP Odds"': '"2%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"3.60"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Tyler Higbee"',
    '"Tm"': '"LAR"',
    '"Opp"': '"@LAC"',
    '"DK Sal $"': '"4600"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"37%"',
    '"GPP Odds"': '"4%"',
    '"Implied Own%"': '"7%"',
    '"DK LEV"': '"2.31"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Royce Freeman"',
    '"Tm"': '"HOU"',
    '"Opp"': '"JAX"',
    '"DK Sal $"': '"4600"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"18%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"2.01"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Jahan Dotson"',
    '"Tm"': '"WAS"',
    '"Opp"': '"CLE"',
    '"DK Sal $"': '"4600"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"32%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"1.85"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Cole Kmet"',
    '"Tm"': '"CHI"',
    '"Opp"': '"@DET"',
    '"DK Sal $"': '"4500"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"31%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"1.69"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Isaiah Hodgins"',
    '"Tm"': '"NYG"',
    '"Opp"': '"IND"',
    '"DK Sal $"': '"4500"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"31%"',
    '"GPP Odds"': '"4%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"1.58"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Kareem Hunt"',
    '"Tm"': '"CLE"',
    '"Opp"': '"@WAS"',
    '"DK Sal $"': '"4500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"14%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.31"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Alexander Mattison"',
    '"Tm"': '"MIN"',
    '"Opp"': '"@GB"',
    '"DK Sal $"': '"4500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"4%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.07"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"JaMycal Hasty"',
    '"Tm"': '"JAX"',
    '"Opp"': '"@HOU"',
    '"DK Sal $"': '"4500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"2%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.01"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Matt Breida"',
    '"Tm"': '"NYG"',
    '"Opp"': '"IND"',
    '"DK Sal $"': '"4500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"2%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.01"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Keaontay Ingram"',
    '"Tm"': '"ARI"',
    '"Opp"': '"@ATL"',
    '"DK Sal $"': '"4500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"1%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.00"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Chase Edmonds"',
    '"Tm"': '"DEN"',
    '"Opp"': '"@KC"',
    '"DK Sal $"': '"4400"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"17%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.86"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Kenneth Gainwell"',
    '"Tm"': '"PHI"',
    '"Opp"': '"NO"',
    '"DK Sal $"': '"4400"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"13%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.02"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Curtis Samuel"',
    '"Tm"': '"WAS"',
    '"Opp"': '"CLE"',
    '"DK Sal $"': '"4400"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"33%"',
    '"GPP Odds"': '"4%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"0.67"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Evan Engram"',
    '"Tm"': '"JAX"',
    '"Opp"': '"@HOU"',
    '"DK Sal $"': '"4400"',
    '"Projected Own%"': '"22.5%"',
    '"Cash Odds"': '"43%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"10%"',
    '"DK LEV"': '"0.44"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Kyren Williams"',
    '"Tm"': '"LAR"',
    '"Opp"': '"@LAC"',
    '"DK Sal $"': '"4400"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"5%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.11"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Marquise Goodwin"',
    '"Tm"': '"SEA"',
    '"Opp"': '"NYJ"',
    '"DK Sal $"': '"4400"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"2%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.02"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Darren Waller"',
    '"Tm"': '"LV"',
    '"Opp"': '"SF"',
    '"DK Sal $"': '"4300"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"29%"',
    '"GPP Odds"': '"2%"',
    '"Implied Own%"': '"4%"',
    '"DK LEV"': '"1.23"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Richie James"',
    '"Tm"': '"NYG"',
    '"Opp"': '"IND"',
    '"DK Sal $"': '"4300"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"33%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"0.68"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"D.J. Chark"',
    '"Tm"': '"DET"',
    '"Opp"': '"CHI"',
    '"DK Sal $"': '"4300"',
    '"Projected Own%"': '"12.5%"',
    '"Cash Odds"': '"37%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"7%"',
    '"DK LEV"': '"0.53"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Pierre Strong Jr."',
    '"Tm"': '"NE"',
    '"Opp"': '"MIA"',
    '"DK Sal $"': '"4300"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"9%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.39"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Marlon Mack"',
    '"Tm"': '"DEN"',
    '"Opp"': '"@KC"',
    '"DK Sal $"': '"4300"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"3%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.02"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Mack Hollins"',
    '"Tm"': '"LV"',
    '"Opp"': '"SF"',
    '"DK Sal $"': '"4200"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"20%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"3.35"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Gerald Everett"',
    '"Tm"': '"LAC"',
    '"Opp"': '"LAR"',
    '"DK Sal $"': '"4200"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"23%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"0.79"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Chris Moore"',
    '"Tm"': '"HOU"',
    '"Opp"': '"JAX"',
    '"DK Sal $"': '"4200"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"27%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"0.43"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Kadarius Toney"',
    '"Tm"': '"KC"',
    '"Opp"': '"DEN"',
    '"DK Sal $"': '"4200"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"8%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.32"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Dare Ogunbowale"',
    '"Tm"': '"HOU"',
    '"Opp"': '"JAX"',
    '"DK Sal $"': '"4200"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"8%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.22"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Jordan Mason"',
    '"Tm"': '"SF"',
    '"Opp"': '"@LV"',
    '"DK Sal $"': '"4200"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"6%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.11"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Raheem Blackshear"',
    '"Tm"': '"CAR"',
    '"Opp"': '"@TB"',
    '"DK Sal $"': '"4200"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"2%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.00"',
  },
  {
    '"Pos"': '"QB"',
    '"Player"': '"Jarrett Stidham"',
    '"Tm"': '"LV"',
    '"Opp"': '"SF"',
    '"DK Sal $"': '"4100"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"23%"',
    '"GPP Odds"': '"4%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"2.96"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"David Njoku"',
    '"Tm"': '"CLE"',
    '"Opp"': '"@WAS"',
    '"DK Sal $"': '"4100"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"34%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"1.79"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Marquez Valdes-Scantling"',
    '"Tm"': '"KC"',
    '"Opp"': '"DEN"',
    '"DK Sal $"': '"4100"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"20%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"0.52"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"DeeJay Dallas"',
    '"Tm"': '"SEA"',
    '"Opp"': '"NYJ"',
    '"DK Sal $"': '"4100"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"11%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.52"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"David Johnson"',
    '"Tm"': '"NO"',
    '"Opp"': '"@PHI"',
    '"DK Sal $"': '"4100"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"7%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.20"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Ameer Abdullah"',
    '"Tm"': '"LV"',
    '"Opp"': '"SF"',
    '"DK Sal $"': '"4100"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"2%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.01"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Van Jefferson"',
    '"Tm"': '"LAR"',
    '"Opp"': '"@LAC"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"25%"',
    '"GPP Odds"': '"2%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"5.48"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Khalil Herbert"',
    '"Tm"': '"CHI"',
    '"Opp"': '"@DET"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"21%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"2.83"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Philadelphia Eagles"',
    '"Tm"': '"PHI"',
    '"Opp"': '"NO"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"22%"',
    '"GPP Odds"': '"5%"',
    '"Implied Own%"': '"6%"',
    '"DK LEV"': '"1.91"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Greg Dulcich"',
    '"Tm"': '"DEN"',
    '"Opp"': '"@KC"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"32%"',
    '"GPP Odds"': '"2%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"1.50"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Hunter Renfrow"',
    '"Tm"': '"LV"',
    '"Opp"': '"SF"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"13%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.01"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Rashid Shaheed"',
    '"Tm"': '"NO"',
    '"Opp"': '"@PHI"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"27%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"0.42"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Justin Jackson"',
    '"Tm"': '"DET"',
    '"Opp"': '"CHI"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"7%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.17"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Avery Williams"',
    '"Tm"': '"ATL"',
    '"Opp"': '"ARI"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"5%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.06"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Jonathan Williams"',
    '"Tm"': '"WAS"',
    '"Opp"': '"CLE"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"4%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.05"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Kyle Juszczyk"',
    '"Tm"': '"SF"',
    '"Opp"': '"@LV"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"4%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.04"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Jordan Wilkins"',
    '"Tm"': '"IND"',
    '"Opp"': '"@NYG"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"3%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.03"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Boston Scott"',
    '"Tm"': '"PHI"',
    '"Opp"': '"NO"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"3%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.02"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Ty Johnson"',
    '"Tm"': '"NYJ"',
    '"Opp"': '"@SEA"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"3%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.02"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Malcolm Brown"',
    '"Tm"': '"LAR"',
    '"Opp"': '"@LAC"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"2%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.01"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Kevin Harris"',
    '"Tm"': '"NE"',
    '"Opp"': '"MIA"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"2%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.00"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"C.J. Ham"',
    '"Tm"': '"MIN"',
    '"Opp"': '"@GB"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"1%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.00"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Brandon Bolden"',
    '"Tm"': '"LV"',
    '"Opp"': '"SF"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"1%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.00"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Gary Brightwell"',
    '"Tm"': '"NYG"',
    '"Opp"': '"IND"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"1%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.00"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Patrick Taylor"',
    '"Tm"': '"GB"',
    '"Opp"': '"MIN"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"1%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.00"',
  },
  {
    '"Pos"': '"RB"',
    '"Player"': '"Ke\'Shawn Vaughn"',
    '"Tm"': '"TB"',
    '"Opp"': '"CAR"',
    '"DK Sal $"': '"4000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"0%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.00"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Alec Pierce"',
    '"Tm"': '"IND"',
    '"Opp"': '"@NYG"',
    '"DK Sal $"': '"3900"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"19%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"2.81"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"New York Giants"',
    '"Tm"': '"NYG"',
    '"Opp"': '"IND"',
    '"DK Sal $"': '"3900"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"26%"',
    '"GPP Odds"': '"7%"',
    '"Implied Own%"': '"7%"',
    '"DK LEV"': '"2.44"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Julio Jones"',
    '"Tm"': '"TB"',
    '"Opp"': '"CAR"',
    '"DK Sal $"': '"3900"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"14%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.28"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Russell Gage"',
    '"Tm"': '"TB"',
    '"Opp"': '"CAR"',
    '"DK Sal $"': '"3800"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"29%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"6.89"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Kansas City Chiefs"',
    '"Tm"': '"KC"',
    '"Opp"': '"DEN"',
    '"DK Sal $"': '"3800"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"39%"',
    '"GPP Odds"': '"16%"',
    '"Implied Own%"': '"18%"',
    '"DK LEV"': '"2.36"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Randall Cobb"',
    '"Tm"': '"GB"',
    '"Opp"': '"MIN"',
    '"DK Sal $"': '"3800"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"12%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.84"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Corey Davis"',
    '"Tm"': '"NYJ"',
    '"Opp"': '"@SEA"',
    '"DK Sal $"': '"3700"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"26%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"6.03"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Dante Pettis"',
    '"Tm"': '"CHI"',
    '"Opp"': '"@DET"',
    '"DK Sal $"': '"3700"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"14%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.20"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Josh Reynolds"',
    '"Tm"': '"DET"',
    '"Opp"': '"CHI"',
    '"DK Sal $"': '"3700"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"14%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.14"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Los Angeles Chargers"',
    '"Tm"': '"LAC"',
    '"Opp"': '"LAR"',
    '"DK Sal $"': '"3700"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"22%"',
    '"GPP Odds"': '"4%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"0.62"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Marvin Jones"',
    '"Tm"': '"JAX"',
    '"Opp"': '"@HOU"',
    '"DK Sal $"': '"3600"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"18%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"2.02"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Jauan Jennings"',
    '"Tm"': '"SF"',
    '"Opp"': '"@LV"',
    '"DK Sal $"': '"3600"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"16%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.52"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Terrace Marshall"',
    '"Tm"': '"CAR"',
    '"Opp"': '"@TB"',
    '"DK Sal $"': '"3600"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"15%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.42"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Jacksonville Jaguars"',
    '"Tm"': '"JAX"',
    '"Opp"': '"@HOU"',
    '"DK Sal $"': '"3600"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"20%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"4%"',
    '"DK LEV"': '"1.22"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Robert Tonyan"',
    '"Tm"': '"GB"',
    '"Opp"': '"MIN"',
    '"DK Sal $"': '"3600"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"19%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"0.47"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Tutu Atwell"',
    '"Tm"': '"LAR"',
    '"Opp"': '"@LAC"',
    '"DK Sal $"': '"3600"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"25%"',
    '"GPP Odds"': '"2%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"0.34"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Miami Dolphins"',
    '"Tm"': '"MIA"',
    '"Opp"': '"@NE"',
    '"DK Sal $"': '"3500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"11%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.57"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Byron Pringle"',
    '"Tm"': '"CHI"',
    '"Opp"': '"@DET"',
    '"DK Sal $"': '"3500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"16%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.51"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Juwan Johnson"',
    '"Tm"': '"NO"',
    '"Opp"': '"@PHI"',
    '"DK Sal $"': '"3500"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"27%"',
    '"GPP Odds"': '"2%"',
    '"Implied Own%"': '"4%"',
    '"DK LEV"': '"1.25"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Kendrick Bourne"',
    '"Tm"': '"NE"',
    '"Opp"': '"MIA"',
    '"DK Sal $"': '"3500"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"28%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"1.04"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Elijah Moore"',
    '"Tm"': '"NYJ"',
    '"Opp"': '"@SEA"',
    '"DK Sal $"': '"3500"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"23%"',
    '"GPP Odds"': '"2%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"0.27"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"DeAndre Carter"',
    '"Tm"': '"LAC"',
    '"Opp"': '"LAR"',
    '"DK Sal $"': '"3500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"3%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.02"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Cleveland Browns"',
    '"Tm"': '"CLE"',
    '"Opp"': '"@WAS"',
    '"DK Sal $"': '"3400"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"13%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"2.18"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Noah Fant"',
    '"Tm"': '"SEA"',
    '"Opp"': '"NYJ"',
    '"DK Sal $"': '"3400"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"28%"',
    '"GPP Odds"': '"2%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"1.14"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Olamide Zaccheaus"',
    '"Tm"': '"ATL"',
    '"Opp"': '"ARI"',
    '"DK Sal $"': '"3400"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"13%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.85"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Jameson Williams"',
    '"Tm"': '"DET"',
    '"Opp"': '"CHI"',
    '"DK Sal $"': '"3400"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"10%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.43"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Ray-Ray McCloud"',
    '"Tm"': '"SF"',
    '"Opp"': '"@LV"',
    '"DK Sal $"': '"3400"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"10%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.39"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Ashton Dulin"',
    '"Tm"': '"IND"',
    '"Opp"': '"@NYG"',
    '"DK Sal $"': '"3400"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"7%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.19"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Amari Rodgers"',
    '"Tm"': '"HOU"',
    '"Opp"': '"JAX"',
    '"DK Sal $"': '"3400"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"3%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.03"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Mike Gesicki"',
    '"Tm"': '"MIA"',
    '"Opp"': '"@NE"',
    '"DK Sal $"': '"3300"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"21%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"3.44"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Trey McBride"',
    '"Tm"': '"ARI"',
    '"Opp"': '"@ATL"',
    '"DK Sal $"': '"3300"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"20%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"3.07"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Indianapolis Colts"',
    '"Tm"': '"IND"',
    '"Opp"': '"@NYG"',
    '"DK Sal $"': '"3300"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"11%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.24"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Quez Watkins"',
    '"Tm"': '"PHI"',
    '"Opp"': '"NO"',
    '"DK Sal $"': '"3300"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"12%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.67"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Nelson Agholor"',
    '"Tm"': '"NE"',
    '"Opp"': '"MIA"',
    '"DK Sal $"': '"3300"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"9%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.36"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Laviska Shenault"',
    '"Tm"': '"CAR"',
    '"Opp"': '"@TB"',
    '"DK Sal $"': '"3200"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"13%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.80"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Cade Otton"',
    '"Tm"': '"TB"',
    '"Opp"': '"CAR"',
    '"DK Sal $"': '"3200"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"23%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"0.67"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Phillip Dorsett"',
    '"Tm"': '"HOU"',
    '"Opp"': '"JAX"',
    '"DK Sal $"': '"3200"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"12%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.60"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Daniel Bellinger"',
    '"Tm"': '"NYG"',
    '"Opp"': '"IND"',
    '"DK Sal $"': '"3200"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"20%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"0.51"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Seattle Seahawks"',
    '"Tm"': '"SEA"',
    '"Opp"': '"NYJ"',
    '"DK Sal $"': '"3200"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"15%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"0.42"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Trent Sherfield"',
    '"Tm"': '"MIA"',
    '"Opp"': '"@NE"',
    '"DK Sal $"': '"3200"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"8%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.25"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"A.J. Green"',
    '"Tm"': '"ARI"',
    '"Opp"': '"@ATL"',
    '"DK Sal $"': '"3200"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"4%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.04"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Washington Commanders"',
    '"Tm"': '"WAS"',
    '"Opp"': '"CLE"',
    '"DK Sal $"': '"3100"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"24%"',
    '"GPP Odds"': '"4%"',
    '"Implied Own%"': '"4%"',
    '"DK LEV"': '"1.29"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Jordan Akins"',
    '"Tm"': '"HOU"',
    '"Opp"': '"JAX"',
    '"DK Sal $"': '"3100"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"24%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"0.81"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Kalif Raymond"',
    '"Tm"': '"DET"',
    '"Opp"': '"CHI"',
    '"DK Sal $"': '"3100"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"11%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.49"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Logan Thomas"',
    '"Tm"': '"WAS"',
    '"Opp"': '"CLE"',
    '"DK Sal $"': '"3100"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"18%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"0.37"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Hunter Henry"',
    '"Tm"': '"NE"',
    '"Opp"': '"MIA"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"23%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"4.08"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Tampa Bay Buccaneers"',
    '"Tm"': '"TB"',
    '"Opp"': '"CAR"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"30%"',
    '"GPP Odds"': '"6%"',
    '"Implied Own%"': '"7%"',
    '"DK LEV"': '"2.26"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Arizona Cardinals"',
    '"Tm"': '"ARI"',
    '"Opp"': '"@ATL"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"14%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.82"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Jonnu Smith"',
    '"Tm"': '"NE"',
    '"Opp"': '"MIA"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"14%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.22"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Brandon Powell"',
    '"Tm"': '"LAR"',
    '"Opp"': '"@LAC"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"14%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.94"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Greg Dortch"',
    '"Tm"': '"ARI"',
    '"Opp"': '"@ATL"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"28%"',
    '"GPP Odds"': '"2%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"0.93"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Velus Jones"',
    '"Tm"': '"CHI"',
    '"Opp"': '"@DET"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"14%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.90"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Tyquan Thornton"',
    '"Tm"': '"NE"',
    '"Opp"': '"MIA"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"11%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.53"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Jamal Agnew"',
    '"Tm"': '"JAX"',
    '"Opp"': '"@HOU"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"12%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.45"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Damiere Byrd"',
    '"Tm"': '"ATL"',
    '"Opp"': '"ARI"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"9%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.24"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"N\'Keal Harry"',
    '"Tm"': '"CHI"',
    '"Opp"': '"@DET"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"8%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.21"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Lance McCutcheon"',
    '"Tm"': '"LAR"',
    '"Opp"': '"@LAC"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"8%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.18"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"KhaDarel Hodge"',
    '"Tm"': '"ATL"',
    '"Opp"': '"ARI"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"6%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.10"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Skyy Moore"',
    '"Tm"': '"KC"',
    '"Opp"': '"DEN"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"6%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.10"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"David Bell"',
    '"Tm"': '"CLE"',
    '"Opp"': '"@WAS"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"5%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.07"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Laquon Treadwell"',
    '"Tm"': '"SEA"',
    '"Opp"': '"NYJ"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"5%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.06"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Shi Smith"',
    '"Tm"': '"CAR"',
    '"Opp"': '"@TB"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"5%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.05"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Braxton Berrios"',
    '"Tm"': '"NYJ"',
    '"Opp"': '"@SEA"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"5%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.05"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Freddie Swain"',
    '"Tm"': '"DEN"',
    '"Opp"': '"@KC"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"4%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.04"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Tre\'Quan Smith"',
    '"Tm"': '"NO"',
    '"Opp"': '"@PHI"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"3%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.02"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Danny Gray"',
    '"Tm"': '"SF"',
    '"Opp"': '"@LV"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"3%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.02"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Zach Pascal"',
    '"Tm"': '"PHI"',
    '"Opp"': '"NO"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"3%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.01"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Justin Watson"',
    '"Tm"': '"KC"',
    '"Opp"': '"DEN"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"3%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.01"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Robbie Anderson"',
    '"Tm"': '"ARI"',
    '"Opp"': '"@ATL"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"2%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.01"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Mike Strachan"',
    '"Tm"': '"IND"',
    '"Opp"': '"@NYG"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"2%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.01"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Jalen Reagor"',
    '"Tm"': '"MIN"',
    '"Opp"': '"@GB"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"1%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.00"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Montrell Washington"',
    '"Tm"': '"DEN"',
    '"Opp"': '"@KC"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"1%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.00"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Cedrick Wilson"',
    '"Tm"': '"MIA"',
    '"Opp"': '"@NE"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"1%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.00"',
  },
  {
    '"Pos"': '"WR"',
    '"Player"': '"Scott Miller"',
    '"Tm"': '"TB"',
    '"Opp"': '"CAR"',
    '"DK Sal $"': '"3000"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"1%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.00"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Detroit Lions"',
    '"Tm"': '"DET"',
    '"Opp"': '"CHI"',
    '"DK Sal $"': '"2900"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"20%"',
    '"GPP Odds"': '"2%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"4.67"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Tyler Conklin"',
    '"Tm"': '"NYJ"',
    '"Opp"': '"@SEA"',
    '"DK Sal $"': '"2900"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"33%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"0.67"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"San Francisco 49ers"',
    '"Tm"': '"SF"',
    '"Opp"': '"@LV"',
    '"DK Sal $"': '"2900"',
    '"Projected Own%"': '"17.5%"',
    '"Cash Odds"': '"50%"',
    '"GPP Odds"': '"22%"',
    '"Implied Own%"': '"24%"',
    '"DK LEV"': '"1.40"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Donald Parham"',
    '"Tm"': '"LAC"',
    '"Opp"': '"LAR"',
    '"DK Sal $"': '"2900"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"9%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.32"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Jelani Woods"',
    '"Tm"': '"IND"',
    '"Opp"': '"@NYG"',
    '"DK Sal $"': '"2800"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"24%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"2%"',
    '"DK LEV"': '"4.38"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Shane Zylstra"',
    '"Tm"': '"DET"',
    '"Opp"': '"CHI"',
    '"DK Sal $"': '"2800"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"14%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.06"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"New York Jets"',
    '"Tm"': '"NYJ"',
    '"Opp"': '"@SEA"',
    '"DK Sal $"': '"2800"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"27%"',
    '"GPP Odds"': '"4%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"0.63"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Chicago Bears"',
    '"Tm"': '"CHI"',
    '"Opp"': '"@DET"',
    '"DK Sal $"': '"2800"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"9%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.45"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Foster Moreau"',
    '"Tm"': '"LV"',
    '"Opp"': '"SF"',
    '"DK Sal $"': '"2800"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"9%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.30"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Cameron Brate"',
    '"Tm"': '"TB"',
    '"Opp"': '"CAR"',
    '"DK Sal $"': '"2800"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"4%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.05"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Marcedes Lewis"',
    '"Tm"': '"GB"',
    '"Opp"': '"MIN"',
    '"DK Sal $"': '"2800"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"4%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.05"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Brock Wright"',
    '"Tm"': '"DET"',
    '"Opp"': '"CHI"',
    '"DK Sal $"': '"2700"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"12%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.61"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Atlanta Falcons"',
    '"Tm"': '"ATL"',
    '"Opp"': '"ARI"',
    '"DK Sal $"': '"2700"',
    '"Projected Own%"': '"12.5%"',
    '"Cash Odds"': '"28%"',
    '"GPP Odds"': '"4%"',
    '"Implied Own%"': '"5%"',
    '"DK LEV"': '"0.38"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Minnesota Vikings"',
    '"Tm"': '"MIN"',
    '"Opp"': '"@GB"',
    '"DK Sal $"': '"2700"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"8%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.25"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Brycen Hopkins"',
    '"Tm"': '"LAR"',
    '"Opp"': '"@LAC"',
    '"DK Sal $"': '"2600"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"16%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.40"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Ian Thomas"',
    '"Tm"': '"CAR"',
    '"Opp"': '"@TB"',
    '"DK Sal $"': '"2600"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"13%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.91"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"New England Patriots"',
    '"Tm"': '"NE"',
    '"Opp"': '"MIA"',
    '"DK Sal $"': '"2600"',
    '"Projected Own%"': '"12.5%"',
    '"Cash Odds"': '"28%"',
    '"GPP Odds"': '"4%"',
    '"Implied Own%"': '"4%"',
    '"DK LEV"': '"0.34"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Harrison Bryant"',
    '"Tm"': '"CLE"',
    '"Opp"': '"@WAS"',
    '"DK Sal $"': '"2600"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"8%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.20"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Josiah Deguara"',
    '"Tm"': '"GB"',
    '"Opp"': '"MIN"',
    '"DK Sal $"': '"2600"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"5%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.07"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Colby Parkinson"',
    '"Tm"': '"SEA"',
    '"Opp"': '"NYJ"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"20%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"2.84"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Houston Texans"',
    '"Tm"': '"HOU"',
    '"Opp"': '"JAX"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"17%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.94"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Noah Gray"',
    '"Tm"': '"KC"',
    '"Opp"': '"DEN"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"16%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"1.41"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"C.J. Uzomah"',
    '"Tm"': '"NYJ"',
    '"Opp"': '"@SEA"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"14%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"1.00"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Anthony Firkser"',
    '"Tm"': '"ATL"',
    '"Opp"': '"ARI"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"12%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.68"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Brevin Jordan"',
    '"Tm"': '"HOU"',
    '"Opp"': '"JAX"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"12%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.65"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Tommy Tremble"',
    '"Tm"': '"CAR"',
    '"Opp"': '"@TB"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"12%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.65"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Mo Alie-Cox"',
    '"Tm"': '"IND"',
    '"Opp"': '"@NYG"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"12%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.58"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Adam Trautman"',
    '"Tm"': '"NO"',
    '"Opp"': '"@PHI"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"11%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.49"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Eric Saubert"',
    '"Tm"': '"DEN"',
    '"Opp"': '"@KC"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"10%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.43"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"MyCole Pruitt"',
    '"Tm"': '"ATL"',
    '"Opp"': '"ARI"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"10%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.41"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Teagan Quitoriano"',
    '"Tm"': '"HOU"',
    '"Opp"': '"JAX"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"9%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.34"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Eric Tomlinson"',
    '"Tm"': '"DEN"',
    '"Opp"': '"@KC"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"9%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.26"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Durham Smythe"',
    '"Tm"': '"MIA"',
    '"Opp"': '"@NE"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"8%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.22"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"James Mitchell"',
    '"Tm"': '"DET"',
    '"Opp"': '"CHI"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"6%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.11"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Johnny Mundt"',
    '"Tm"': '"MIN"',
    '"Opp"': '"@GB"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"6%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.11"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Ryan Griffin"',
    '"Tm"': '"CHI"',
    '"Opp"': '"@DET"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"6%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.11"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"John Bates"',
    '"Tm"': '"WAS"',
    '"Opp"': '"CLE"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"5%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.08"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Parker Hesse"',
    '"Tm"': '"ATL"',
    '"Opp"': '"ARI"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"5%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.06"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Chris Myarick"',
    '"Tm"': '"NYG"',
    '"Opp"': '"IND"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"5%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.06"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Dan Arnold"',
    '"Tm"': '"JAX"',
    '"Opp"': '"@HOU"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"4%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.04"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Nick Vannett"',
    '"Tm"': '"NYG"',
    '"Opp"': '"IND"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"4%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.04"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Stephen Sullivan"',
    '"Tm"': '"CAR"',
    '"Opp"': '"@TB"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"4%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.03"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Ross Dwelley"',
    '"Tm"': '"SF"',
    '"Opp"': '"@LV"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"3%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.02"',
  },
  {
    '"Pos"': '"TE"',
    '"Player"': '"Stephen Anderson"',
    '"Tm"': '"ARI"',
    '"Opp"': '"@ATL"',
    '"DK Sal $"': '"2500"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"3%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.02"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Carolina Panthers"',
    '"Tm"': '"CAR"',
    '"Opp"': '"@TB"',
    '"DK Sal $"': '"2400"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"26%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"0.96"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Los Angeles Rams"',
    '"Tm"': '"LAR"',
    '"Opp"': '"@LAC"',
    '"DK Sal $"': '"2400"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"20%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"0.46"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Las Vegas Raiders"',
    '"Tm"': '"LV"',
    '"Opp"': '"SF"',
    '"DK Sal $"': '"2300"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"12%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.50"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Green Bay Packers"',
    '"Tm"': '"GB"',
    '"Opp"': '"MIN"',
    '"DK Sal $"': '"2300"',
    '"Projected Own%"': '"7.5%"',
    '"Cash Odds"': '"26%"',
    '"GPP Odds"': '"3%"',
    '"Implied Own%"': '"3%"',
    '"DK LEV"': '"0.38"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"New Orleans Saints"',
    '"Tm"': '"NO"',
    '"Opp"': '"@PHI"',
    '"DK Sal $"': '"2200"',
    '"Projected Own%"': '"3.0%"',
    '"Cash Odds"': '"19%"',
    '"GPP Odds"': '"1%"',
    '"Implied Own%"': '"1%"',
    '"DK LEV"': '"0.30"',
  },
  {
    '"Pos"': '"DEF"',
    '"Player"': '"Denver Broncos"',
    '"Tm"': '"DEN"',
    '"Opp"': '"@KC"',
    '"DK Sal $"': '"2200"',
    '"Projected Own%"': '"0.5%"',
    '"Cash Odds"': '"6%"',
    '"GPP Odds"': '"0%"',
    '"Implied Own%"': '"0%"',
    '"DK LEV"': '"0.05"',
  },
];

module.exports = gppLeverageScoresAndProjOwnershipDraftkings;
