const gppLeverageScoresAndProjOwnershipDraftkings = [
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Justin Jefferson\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"@TEN\"",
		"\"DK Sal $\"": "\"8600\"",
		"\"Projected Own%\"": "\"25.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"15%\"",
		"\"DK LEV\"": "\"0.58\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Christian McCaffrey\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"SEA\"",
		"\"DK Sal $\"": "\"8300\"",
		"\"Projected Own%\"": "\"38.5%\"",
		"\"Cash Odds\"": "\"60%\"",
		"\"GPP Odds\"": "\"31%\"",
		"\"Implied Own%\"": "\"30%\"",
		"\"DK LEV\"": "\"0.79\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Alvin Kamara\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"CLE\"",
		"\"DK Sal $\"": "\"8200\"",
		"\"Projected Own%\"": "\"37.5%\"",
		"\"Cash Odds\"": "\"57%\"",
		"\"GPP Odds\"": "\"25%\"",
		"\"Implied Own%\"": "\"24%\"",
		"\"DK LEV\"": "\"0.63\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Derrick Henry\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"@PIT\"",
		"\"DK Sal $\"": "\"8100\"",
		"\"Projected Own%\"": "\"19.5%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"19%\"",
		"\"Implied Own%\"": "\"18%\"",
		"\"DK LEV\"": "\"0.93\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Lamar Jackson\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"@PIT\"",
		"\"DK Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"12.0%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"DK LEV\"": "\"0.63\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Amon-Ra St. Brown\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"JAX\"",
		"\"DK Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"35.5%\"",
		"\"Cash Odds\"": "\"48%\"",
		"\"GPP Odds\"": "\"20%\"",
		"\"Implied Own%\"": "\"25%\"",
		"\"DK LEV\"": "\"0.71\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Kyren Williams\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"@NE\"",
		"\"DK Sal $\"": "\"7900\"",
		"\"Projected Own%\"": "\"26.0%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"19%\"",
		"\"Implied Own%\"": "\"18%\"",
		"\"DK LEV\"": "\"0.69\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Josh Allen\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"KC\"",
		"\"DK Sal $\"": "\"7800\"",
		"\"Projected Own%\"": "\"17.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"DK LEV\"": "\"0.45\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Bijan Robinson\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@DEN\"",
		"\"DK Sal $\"": "\"7800\"",
		"\"Projected Own%\"": "\"13.0%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"DK LEV\"": "\"0.87\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jonathan Taylor\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@NYJ\"",
		"\"DK Sal $\"": "\"7600\"",
		"\"Projected Own%\"": "\"17.0%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"15%\"",
		"\"DK LEV\"": "\"0.86\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Breece Hall\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"IND\"",
		"\"DK Sal $\"": "\"7500\"",
		"\"Projected Own%\"": "\"17.5%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"14%\"",
		"\"DK LEV\"": "\"0.82\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Cooper Kupp\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"@NE\"",
		"\"DK Sal $\"": "\"7500\"",
		"\"Projected Own%\"": "\"31.0%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"DK LEV\"": "\"0.43\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tyreek Hill\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"LV\"",
		"\"DK Sal $\"": "\"7400\"",
		"\"Projected Own%\"": "\"13.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"DK LEV\"": "\"0.80\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jahmyr Gibbs\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"JAX\"",
		"\"DK Sal $\"": "\"7300\"",
		"\"Projected Own%\"": "\"10.5%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"DK LEV\"": "\"1.22\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Puka Nacua\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"@NE\"",
		"\"DK Sal $\"": "\"7300\"",
		"\"Projected Own%\"": "\"19.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"DK LEV\"": "\"0.68\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"De'Von Achane\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"LV\"",
		"\"DK Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"41.0%\"",
		"\"Cash Odds\"": "\"60%\"",
		"\"GPP Odds\"": "\"19%\"",
		"\"Implied Own%\"": "\"19%\"",
		"\"DK LEV\"": "\"0.46\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Davante Adams\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"IND\"",
		"\"DK Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"5.91\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Josh Jacobs\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"@CHI\"",
		"\"DK Sal $\"": "\"7100\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"38%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"DK LEV\"": "\"1.35\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Garrett Wilson\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"IND\"",
		"\"DK Sal $\"": "\"7100\"",
		"\"Projected Own%\"": "\"21.5%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"DK LEV\"": "\"0.57\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jordan Love\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"@CHI\"",
		"\"DK Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"1.34\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Kenneth Walker\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"@SF\"",
		"\"DK Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"8.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"10%\"",
		"\"DK LEV\"": "\"1.21\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"George Pickens\"",
		"\"Tm\"": "\"PIT\"",
		"\"Opp\"": "\"BAL\"",
		"\"DK Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"20.0%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"17%\"",
		"\"DK LEV\"": "\"0.84\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Aaron Jones\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"@TEN\"",
		"\"DK Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"5.69\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Zay Flowers\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"@PIT\"",
		"\"DK Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"DK LEV\"": "\"1.40\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Patrick Mahomes\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@BUF\"",
		"\"DK Sal $\"": "\"6800\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"1.18\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"James Cook\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"KC\"",
		"\"DK Sal $\"": "\"6800\"",
		"\"Projected Own%\"": "\"9.0%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"DK LEV\"": "\"1.29\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Deebo Samuel\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"SEA\"",
		"\"DK Sal $\"": "\"6800\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"DK LEV\"": "\"0.92\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Kareem Hunt\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@BUF\"",
		"\"DK Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"DK LEV\"": "\"2.27\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Drake London\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@DEN\"",
		"\"DK Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"10.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"DK LEV\"": "\"0.82\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Brock Purdy\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"SEA\"",
		"\"DK Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"18.5%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"DK LEV\"": "\"0.51\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"D'Andre Swift\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"GB\"",
		"\"DK Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"4.73\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Darnell Mooney\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@DEN\"",
		"\"DK Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"DK LEV\"": "\"2.23\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Kirk Cousins\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@DEN\"",
		"\"DK Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"2.90\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"David Montgomery\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"JAX\"",
		"\"DK Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"DK LEV\"": "\"3.62\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DK Metcalf\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"@SF\"",
		"\"DK Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"8.5%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"DK LEV\"": "\"0.86\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jaxon Smith-Njigba\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"@SF\"",
		"\"DK Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"1.80\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jayden Reed\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"@CHI\"",
		"\"DK Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"10%\"",
		"\"DK LEV\"": "\"0.83\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Josh Downs\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@NYJ\"",
		"\"DK Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"11.0%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"0.56\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jared Goff\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"JAX\"",
		"\"DK Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"8.0%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"0.79\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Travis Etienne\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"@DET\"",
		"\"DK Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"9.52\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Khalil Shakir\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"KC\"",
		"\"DK Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"DK LEV\"": "\"1.42\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Travis Kelce\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@BUF\"",
		"\"DK Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"25.0%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"14%\"",
		"\"DK LEV\"": "\"0.57\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Bo Nix\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"ATL\"",
		"\"DK Sal $\"": "\"6200\"",
		"\"Projected Own%\"": "\"11.0%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"DK LEV\"": "\"0.82\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Najee Harris\"",
		"\"Tm\"": "\"PIT\"",
		"\"Opp\"": "\"BAL\"",
		"\"DK Sal $\"": "\"6200\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"3.34\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Calvin Ridley\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"MIN\"",
		"\"DK Sal $\"": "\"6200\"",
		"\"Projected Own%\"": "\"12.0%\"",
		"\"Cash Odds\"": "\"38%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"DK LEV\"": "\"0.92\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Sam Darnold\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"@TEN\"",
		"\"DK Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"0.97\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Rhamondre Stevenson\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"LAR\"",
		"\"DK Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"DK LEV\"": "\"3.49\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Brian Thomas Jr.\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"@DET\"",
		"\"DK Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"2.81\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Tua Tagovailoa\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"LV\"",
		"\"DK Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"4.0%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"1.12\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Nick Chubb\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"@NO\"",
		"\"DK Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"DK LEV\"": "\"2.54\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"D.J. Moore\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"GB\"",
		"\"DK Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"1.74\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"George Kittle\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"SEA\"",
		"\"DK Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"16.5%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"DK LEV\"": "\"0.75\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Russell Wilson\"",
		"\"Tm\"": "\"PIT\"",
		"\"Opp\"": "\"BAL\"",
		"\"DK Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"4.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"DK LEV\"": "\"1.52\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Courtland Sutton\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"ATL\"",
		"\"DK Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"DK LEV\"": "\"1.15\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Matthew Stafford\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"@NE\"",
		"\"DK Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"1.16\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jameson Williams\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"JAX\"",
		"\"DK Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"1.89\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tyler Lockett\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"@SF\"",
		"\"DK Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"17%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"3.32\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Brock Bowers\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"@MIA\"",
		"\"DK Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"27.0%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"15%\"",
		"\"DK LEV\"": "\"0.55\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DeAndre Hopkins\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@BUF\"",
		"\"DK Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"DK LEV\"": "\"2.00\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Drake Maye\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"LAR\"",
		"\"DK Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"1.84\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jakobi Meyers\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"@MIA\"",
		"\"DK Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"1.20\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jameis Winston\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"@NO\"",
		"\"DK Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"1.08\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Aaron Rodgers\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"IND\"",
		"\"DK Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"3.73\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Alexander Mattison\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"@MIA\"",
		"\"DK Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"6.97\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Romeo Doubs\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"@CHI\"",
		"\"DK Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"4.61\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"David Njoku\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"@NO\"",
		"\"DK Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"13.0%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"DK LEV\"": "\"0.95\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Caleb Williams\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"GB\"",
		"\"DK Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"2.99\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Cedric Tillman\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"@NO\"",
		"\"DK Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"DK LEV\"": "\"1.84\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jauan Jennings\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"SEA\"",
		"\"DK Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"7.0%\"",
		"\"Cash Odds\"": "\"38%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"DK LEV\"": "\"1.27\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Derek Carr\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"CLE\"",
		"\"DK Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"2.67\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Evan Engram\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"@DET\"",
		"\"DK Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"1.91\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Will Levis\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"MIN\"",
		"\"DK Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"24%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"2.34\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Gardner Minshew\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"@MIA\"",
		"\"DK Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"1.61\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Mac Jones\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"@DET\"",
		"\"DK Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"23%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"5.52\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Kyle Pitts\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@DEN\"",
		"\"DK Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"1.18\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"T.J. Hockenson\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"@TEN\"",
		"\"DK Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"5.5%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"DK LEV\"": "\"1.28\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Rashod Bateman\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"@PIT\"",
		"\"DK Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"3.47\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Mark Andrews\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"@PIT\"",
		"\"DK Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"3.31\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Audric Estime\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"ATL\"",
		"\"DK Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"7.31\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Taysom Hill\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"CLE\"",
		"\"DK Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"DK LEV\"": "\"2.78\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Tucker Kraft\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"@CHI\"",
		"\"DK Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"2.19\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Sam LaPorta\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"JAX\"",
		"\"DK Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"2.24\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Hunter Henry\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"LAR\"",
		"\"DK Sal $\"": "\"3900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"4.48\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Mack Hollins\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"KC\"",
		"\"DK Sal $\"": "\"3800\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"4.78\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Jonnu Smith\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"LV\"",
		"\"DK Sal $\"": "\"3800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"6.43\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Detroit Lions\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"JAX\"",
		"\"DK Sal $\"": "\"3800\"",
		"\"Projected Own%\"": "\"19.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"18%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"DK LEV\"": "\"0.36\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"San Francisco 49ers\"",
		"\"Tm\"": "\"SF\"",
		"\"Opp\"": "\"SEA\"",
		"\"DK Sal $\"": "\"3600\"",
		"\"Projected Own%\"": "\"5.0%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"0.70\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Dawson Knox\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"KC\"",
		"\"DK Sal $\"": "\"3500\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"2.41\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Green Bay Packers\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"@CHI\"",
		"\"DK Sal $\"": "\"3500\"",
		"\"Projected Own%\"": "\"12.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"18%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"DK LEV\"": "\"0.57\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Baltimore Ravens\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"@PIT\"",
		"\"DK Sal $\"": "\"3400\"",
		"\"Projected Own%\"": "\"1.0%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"2.64\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"New Orleans Saints\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"CLE\"",
		"\"DK Sal $\"": "\"3300\"",
		"\"Projected Own%\"": "\"8.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"0.64\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Los Angeles Rams\"",
		"\"Tm\"": "\"LAR\"",
		"\"Opp\"": "\"@NE\"",
		"\"DK Sal $\"": "\"3200\"",
		"\"Projected Own%\"": "\"10.5%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"16%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"0.59\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Kansas City Chiefs\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"@BUF\"",
		"\"DK Sal $\"": "\"3100\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"24%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"1.77\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Miami Dolphins\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"LV\"",
		"\"DK Sal $\"": "\"3000\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"19%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"DK LEV\"": "\"0.60\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"New York Jets\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"IND\"",
		"\"DK Sal $\"": "\"2800\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"1.41\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Atlanta Falcons\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@DEN\"",
		"\"DK Sal $\"": "\"2700\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"1.54\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Buffalo Bills\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"KC\"",
		"\"DK Sal $\"": "\"2700\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"1.42\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Cleveland Browns\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"@NO\"",
		"\"DK Sal $\"": "\"2600\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"DK LEV\"": "\"2.30\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Indianapolis Colts\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@NYJ\"",
		"\"DK Sal $\"": "\"2600\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"1.93\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"New England Patriots\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"LAR\"",
		"\"DK Sal $\"": "\"2500\"",
		"\"Projected Own%\"": "\"1.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"DK LEV\"": "\"3.03\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Pittsburgh Steelers\"",
		"\"Tm\"": "\"PIT\"",
		"\"Opp\"": "\"BAL\"",
		"\"DK Sal $\"": "\"2500\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"1.07\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Chicago Bears\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"GB\"",
		"\"DK Sal $\"": "\"2400\"",
		"\"Projected Own%\"": "\"3.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"1.06\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Las Vegas Raiders\"",
		"\"Tm\"": "\"LV\"",
		"\"Opp\"": "\"@MIA\"",
		"\"DK Sal $\"": "\"2400\"",
		"\"Projected Own%\"": "\"2.0%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"DK LEV\"": "\"1.65\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Seattle Seahawks\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"@SF\"",
		"\"DK Sal $\"": "\"2300\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"0.78\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Tennessee Titans\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"MIN\"",
		"\"DK Sal $\"": "\"2300\"",
		"\"Projected Own%\"": "\"2.5%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"DK LEV\"": "\"1.80\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Jacksonville Jaguars\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"@DET\"",
		"\"DK Sal $\"": "\"2200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"DK LEV\"": "\"3.99\""
	}
]

module.exports = gppLeverageScoresAndProjOwnershipDraftkings;