const allNFLTeamPace = [
  {
    '"Home"': '"HOU"',
    '"Away"': '"PHI"',
    '"Time"': '"THU 8:15 AM"',
    '"Sec_ALL_nt_h"': '26.6',
    '"Sec_ALL_nt_v"': '26.8',
    '"Sec_ALL_nt_avg"': '26.7',
    '"Plays_ALL_nt_h"': '60',
    '"Plays_ALL_nt_v"': '84',
    '"Plays_ALL_nt_avg"': '72',
    '"Sec_ALL_h"': '25.1',
    '"Sec_ALL_v"': '24.9',
    '"Sec_ALL_avg"': '25',
    '"Plays_ALL_h"': '65',
    '"Plays_ALL_v"': '77',
    '"PLays_ALL_avg"': '71',
  },
  {
    '"Home"': '"JAC"',
    '"Away"': '"LV"',
    '"Time"': '"SUN 1:00 AM"',
    '"Sec_ALL_nt_h"': '24.9',
    '"Sec_ALL_nt_v"': '27.7',
    '"Sec_ALL_nt_avg"': '26.3',
    '"Plays_ALL_nt_h"': '75',
    '"Plays_ALL_nt_v"': '62',
    '"Plays_ALL_nt_avg"': '68.5',
    '"Sec_ALL_h"': '23.9',
    '"Sec_ALL_v"': '24.7',
    '"Sec_ALL_avg"': '24.3',
    '"Plays_ALL_h"': '74',
    '"Plays_ALL_v"': '69',
    '"PLays_ALL_avg"': '71.5',
  },
  {
    '"Home"': '"ATL"',
    '"Away"': '"LAC"',
    '"Time"': '"SUN 1:00 AM"',
    '"Sec_ALL_nt_h"': '28.1',
    '"Sec_ALL_nt_v"': '24.9',
    '"Sec_ALL_nt_avg"': '26.5',
    '"Plays_ALL_nt_h"': '67',
    '"Plays_ALL_nt_v"': '71',
    '"Plays_ALL_nt_avg"': '69',
    '"Sec_ALL_h"': '27',
    '"Sec_ALL_v"': '23.1',
    '"Sec_ALL_avg"': '25.1',
    '"Plays_ALL_h"': '64',
    '"Plays_ALL_v"': '75',
    '"PLays_ALL_avg"': '69.5',
  },
  {
    '"Home"': '"CHI"',
    '"Away"': '"MIA"',
    '"Time"': '"SUN 1:00 AM"',
    '"Sec_ALL_nt_h"': '27.5',
    '"Sec_ALL_nt_v"': '26.5',
    '"Sec_ALL_nt_avg"': '27',
    '"Plays_ALL_nt_h"': '58',
    '"Plays_ALL_nt_v"': '59',
    '"Plays_ALL_nt_avg"': '58.5',
    '"Sec_ALL_h"': '25',
    '"Sec_ALL_v"': '25.2',
    '"Sec_ALL_avg"': '25.1',
    '"Plays_ALL_h"': '69',
    '"Plays_ALL_v"': '70',
    '"PLays_ALL_avg"': '69.5',
  },
  {
    '"Home"': '"CIN"',
    '"Away"': '"CAR"',
    '"Time"': '"SUN 1:00 AM"',
    '"Sec_ALL_nt_h"': '25.4',
    '"Sec_ALL_nt_v"': '24.4',
    '"Sec_ALL_nt_avg"': '24.9',
    '"Plays_ALL_nt_h"': '68',
    '"Plays_ALL_nt_v"': '54',
    '"Plays_ALL_nt_avg"': '61',
    '"Sec_ALL_h"': '24.9',
    '"Sec_ALL_v"': '24.1',
    '"Sec_ALL_avg"': '24.5',
    '"Plays_ALL_h"': '74',
    '"Plays_ALL_v"': '62',
    '"PLays_ALL_avg"': '68',
  },
  {
    '"Home"': '"DET"',
    '"Away"': '"GB"',
    '"Time"': '"SUN 1:00 AM"',
    '"Sec_ALL_nt_h"': '26.6',
    '"Sec_ALL_nt_v"': '28',
    '"Sec_ALL_nt_avg"': '27.3',
    '"Plays_ALL_nt_h"': '67',
    '"Plays_ALL_nt_v"': '65',
    '"Plays_ALL_nt_avg"': '66',
    '"Sec_ALL_h"': '23.5',
    '"Sec_ALL_v"': '25.7',
    '"Sec_ALL_avg"': '24.6',
    '"Plays_ALL_h"': '72',
    '"Plays_ALL_v"': '70',
    '"PLays_ALL_avg"': '71',
  },
  {
    '"Home"': '"NE"',
    '"Away"': '"IND"',
    '"Time"': '"SUN 1:00 AM"',
    '"Sec_ALL_nt_h"': '27.7',
    '"Sec_ALL_nt_v"': '25.7',
    '"Sec_ALL_nt_avg"': '26.7',
    '"Plays_ALL_nt_h"': '64',
    '"Plays_ALL_nt_v"': '65',
    '"Plays_ALL_nt_avg"': '64.5',
    '"Sec_ALL_h"': '25.7',
    '"Sec_ALL_v"': '24.2',
    '"Sec_ALL_avg"': '24.9',
    '"Plays_ALL_h"': '69',
    '"Plays_ALL_v"': '72',
    '"PLays_ALL_avg"': '70.5',
  },
  {
    '"Home"': '"NYJ"',
    '"Away"': '"BUF"',
    '"Time"': '"SUN 1:00 AM"',
    '"Sec_ALL_nt_h"': '25.7',
    '"Sec_ALL_nt_v"': '25.9',
    '"Sec_ALL_nt_avg"': '25.8',
    '"Plays_ALL_nt_h"': '62',
    '"Plays_ALL_nt_v"': '77',
    '"Plays_ALL_nt_avg"': '69.5',
    '"Sec_ALL_h"': '23.1',
    '"Sec_ALL_v"': '23.7',
    '"Sec_ALL_avg"': '23.4',
    '"Plays_ALL_h"': '72',
    '"Plays_ALL_v"': '73',
    '"PLays_ALL_avg"': '72.5',
  },
  {
    '"Home"': '"WAS"',
    '"Away"': '"MIN"',
    '"Time"': '"SUN 1:00 AM"',
    '"Sec_ALL_nt_h"': '26.9',
    '"Sec_ALL_nt_v"': '26.2',
    '"Sec_ALL_nt_avg"': '26.5',
    '"Plays_ALL_nt_h"': '64',
    '"Plays_ALL_nt_v"': '65',
    '"Plays_ALL_nt_avg"': '64.5',
    '"Sec_ALL_h"': '24.7',
    '"Sec_ALL_v"': '23.2',
    '"Sec_ALL_avg"': '23.9',
    '"Plays_ALL_h"': '74',
    '"Plays_ALL_v"': '73',
    '"PLays_ALL_avg"': '73.5',
  },
  {
    '"Home"': '"ARI"',
    '"Away"': '"SEA"',
    '"Time"': '"SUN 4:05 AM"',
    '"Sec_ALL_nt_h"': '26.7',
    '"Sec_ALL_nt_v"': '26',
    '"Sec_ALL_nt_avg"': '26.4',
    '"Plays_ALL_nt_h"': '57',
    '"Plays_ALL_nt_v"': '67',
    '"Plays_ALL_nt_avg"': '62',
    '"Sec_ALL_h"': '23',
    '"Sec_ALL_v"': '24',
    '"Sec_ALL_avg"': '23.5',
    '"Plays_ALL_h"': '79',
    '"Plays_ALL_v"': '68',
    '"PLays_ALL_avg"': '73.5',
  },
  {
    '"Home"': '"TB"',
    '"Away"': '"LAR"',
    '"Time"': '"SUN 4:25 AM"',
    '"Sec_ALL_nt_h"': '26.4',
    '"Sec_ALL_nt_v"': '31',
    '"Sec_ALL_nt_avg"': '28.7',
    '"Plays_ALL_nt_h"': '64',
    '"Plays_ALL_nt_v"': '56',
    '"Plays_ALL_nt_avg"': '60',
    '"Sec_ALL_h"': '22.2',
    '"Sec_ALL_v"': '26.9',
    '"Sec_ALL_avg"': '24.5',
    '"Plays_ALL_h"': '72',
    '"Plays_ALL_v"': '67',
    '"PLays_ALL_avg"': '69.5',
  },
  {
    '"Home"': '"KC"',
    '"Away"': '"TEN"',
    '"Time"': '"SUN 8:20 AM"',
    '"Sec_ALL_nt_h"': '26.4',
    '"Sec_ALL_nt_v"': '29.5',
    '"Sec_ALL_nt_avg"': '27.9',
    '"Plays_ALL_nt_h"': '64',
    '"Plays_ALL_nt_v"': '66',
    '"Plays_ALL_nt_avg"': '65',
    '"Sec_ALL_h"': '24.5',
    '"Sec_ALL_v"': '27.1',
    '"Sec_ALL_avg"': '25.8',
    '"Plays_ALL_h"': '72',
    '"Plays_ALL_v"': '65',
    '"PLays_ALL_avg"': '68.5',
  },
  {
    '"Home"': '"NO"',
    '"Away"': '"BAL"',
    '"Time"': '"MON 8:15 AM"',
    '"Sec_ALL_nt_h"': '27.3',
    '"Sec_ALL_nt_v"': '28.7',
    '"Sec_ALL_nt_avg"': '28',
    '"Plays_ALL_nt_h"': '67',
    '"Plays_ALL_nt_v"': '72',
    '"Plays_ALL_nt_avg"': '69.5',
    '"Sec_ALL_h"': '24.6',
    '"Sec_ALL_v"': '26.7',
    '"Sec_ALL_avg"': '25.6',
    '"Plays_ALL_h"': '73',
    '"Plays_ALL_v"': '69',
    '"PLays_ALL_avg"': '71',
  },
];

module.exports = allNFLTeamPace;
