const qbRushingLastFiveGamesFromWeeklyStatExplorer = [
  {
    '"Player"': '"Aaron Rodgers"',
    '"Team"': '"GB"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '3',
    '"Yards"': '12',
    '"TD"': '0',
    '"YPC"': '4',
    '"% Tm Att"': '"3%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Andy Dalton"',
    '"Team"': '"NO"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '12',
    '"Yards"': '28',
    '"TD"': '0',
    '"YPC"': '2.3',
    '"% Tm Att"': '"8%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Bailey Zappe"',
    '"Team"': '"NE"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '10',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': '0',
    '"% Tm Att"': '"9%"',
    '"FumL"': '2',
  },
  {
    '"Player"': '"Baker Mayfield"',
    '"Team"': '"CAR"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '2',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': '0',
    '"% Tm Att"': '"25%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Brett Rypien"',
    '"Team"': '"DEN"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '3',
    '"Yards"': '9',
    '"TD"': '0',
    '"YPC"': '3',
    '"% Tm Att"': '"9%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Brian Hoyer"',
    '"Team"': '"NE"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '0',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': 'NA',
    '"% Tm Att"': '"0%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Brock Purdy"',
    '"Team"': '"SF"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '2',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': '0',
    '"% Tm Att"': '"5%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Carson Wentz"',
    '"Team"': '"WAS"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Att"': '8',
    '"Yards"': '22',
    '"TD"': '0',
    '"YPC"': '2.8',
    '"% Tm Att"': '"11%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Case Keenum"',
    '"Team"': '"BUF"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '2',
    '"Yards"': '-2',
    '"TD"': '0',
    '"YPC"': '-1',
    '"% Tm Att"': '"11%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Chad Henne"',
    '"Team"': '"KC"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '3',
    '"Yards"': '-3',
    '"TD"': '0',
    '"YPC"': '-1',
    '"% Tm Att"': '"14%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Cooper Rush"',
    '"Team"': '"DAL"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Att"': '6',
    '"Yards"': '6',
    '"TD"': '0',
    '"YPC"': '1',
    '"% Tm Att"': '"7%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Dak Prescott"',
    '"Team"': '"DAL"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '8',
    '"Yards"': '34',
    '"TD"': '1',
    '"YPC"': '4.2',
    '"% Tm Att"': '"13%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Daniel Jones"',
    '"Team"': '"NYG"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '39',
    '"Yards"': '238',
    '"TD"': '3',
    '"YPC"': '6.1',
    '"% Tm Att"': '"23%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Davis Mills"',
    '"Team"': '"HOU"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '5',
    '"Yards"': '10',
    '"TD"': '0',
    '"YPC"': '2',
    '"% Tm Att"': '"6%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Derek Carr"',
    '"Team"': '"LV"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '12',
    '"Yards"': '41',
    '"TD"': '0',
    '"YPC"': '3.4',
    '"% Tm Att"': '"12%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Gardner Minshew"',
    '"Team"': '"PHI"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '1',
    '"Yards"': '-1',
    '"TD"': '0',
    '"YPC"': '-1',
    '"% Tm Att"': '"5%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Geno Smith"',
    '"Team"': '"SEA"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '25',
    '"Yards"': '143',
    '"TD"': '1',
    '"YPC"': '5.7',
    '"% Tm Att"': '"18%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Jacob Eason"',
    '"Team"': '"CAR"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '0',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': 'NA',
    '"% Tm Att"': '"0%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Jacoby Brissett"',
    '"Team"': '"CLE"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '18',
    '"Yards"': '78',
    '"TD"': '2',
    '"YPC"': '4.3',
    '"% Tm Att"': '"12%"',
    '"FumL"': '4',
  },
  {
    '"Player"': '"Jalen Hurts"',
    '"Team"': '"PHI"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '42',
    '"Yards"': '136',
    '"TD"': '3',
    '"YPC"': '3.2',
    '"% Tm Att"': '"30%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Jared Goff"',
    '"Team"': '"DET"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '6',
    '"Yards"': '15',
    '"TD"': '0',
    '"YPC"': '2.5',
    '"% Tm Att"': '"6%"',
    '"FumL"': '3',
  },
  {
    '"Player"': '"Jarrett Stidham"',
    '"Team"': '"LV"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '0',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': 'NA',
    '"% Tm Att"': '"0%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Jimmy Garoppolo"',
    '"Team"': '"SF"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '8',
    '"Yards"': '18',
    '"TD"': '0',
    '"YPC"': '2.2',
    '"% Tm Att"': '"9%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Joe Burrow"',
    '"Team"': '"CIN"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '16',
    '"Yards"': '59',
    '"TD"': '3',
    '"YPC"': '3.7',
    '"% Tm Att"': '"17%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Jordan Love"',
    '"Team"': '"GB"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '0',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': 'NA',
    '"% Tm Att"': '"0%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Josh Allen"',
    '"Team"': '"BUF"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '34',
    '"Yards"': '193',
    '"TD"': '1',
    '"YPC"': '5.7',
    '"% Tm Att"': '"33%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Justin Fields"',
    '"Team"': '"CHI"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '49',
    '"Yards"': '329',
    '"TD"': '2',
    '"YPC"': '6.7',
    '"% Tm Att"': '"27%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Justin Herbert"',
    '"Team"': '"LAC"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '14',
    '"Yards"': '39',
    '"TD"': '0',
    '"YPC"': '2.8',
    '"% Tm Att"': '"14%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Kenny Pickett"',
    '"Team"': '"PIT"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '19',
    '"Yards"': '98',
    '"TD"': '2',
    '"YPC"': '5.2',
    '"% Tm Att"': '"16%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Kirk Cousins"',
    '"Team"': '"MIN"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '10',
    '"Yards"': '21',
    '"TD"': '2',
    '"YPC"': '2.1',
    '"% Tm Att"': '"10%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Kyler Murray"',
    '"Team"': '"ARI"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '39',
    '"Yards"': '234',
    '"TD"': '1',
    '"YPC"': '6',
    '"% Tm Att"': '"27%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Lamar Jackson"',
    '"Team"': '"BAL"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '49',
    '"Yards"': '310',
    '"TD"': '0',
    '"YPC"': '6.3',
    '"% Tm Att"': '"31%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Mac Jones"',
    '"Team"': '"NE"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '10',
    '"Yards"': '43',
    '"TD"': '0',
    '"YPC"': '4.3',
    '"% Tm Att"': '"19%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Malik Willis"',
    '"Team"': '"TEN"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '5',
    '"Yards"': '12',
    '"TD"': '0',
    '"YPC"': '2.4',
    '"% Tm Att"': '"6%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Marcus Mariota"',
    '"Team"': '"ATL"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '30',
    '"Yards"': '188',
    '"TD"': '1',
    '"YPC"': '6.3',
    '"% Tm Att"': '"18%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Matt Ryan"',
    '"Team"': '"IND"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '5',
    '"Yards"': '-5',
    '"TD"': '0',
    '"YPC"': '-1',
    '"% Tm Att"': '"6%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Matthew Stafford"',
    '"Team"': '"LAR"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '6',
    '"Yards"': '2',
    '"TD"': '1',
    '"YPC"': '0.3',
    '"% Tm Att"': '"7%"',
    '"FumL"': '3',
  },
  {
    '"Player"': '"Mitchell Trubisky"',
    '"Team"': '"PIT"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '7',
    '"Yards"': '6',
    '"TD"': '0',
    '"YPC"': '0.9',
    '"% Tm Att"': '"12%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Patrick Mahomes"',
    '"Team"': '"KC"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '12',
    '"Yards"': '83',
    '"TD"': '0',
    '"YPC"': '6.9',
    '"% Tm Att"': '"12%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Phillip Walker"',
    '"Team"': '"CAR"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '2',
    '"Yards"': '19',
    '"TD"': '0',
    '"YPC"': '9.5',
    '"% Tm Att"': '"3%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Russell Wilson"',
    '"Team"': '"DEN"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '16',
    '"Yards"': '91',
    '"TD"': '1',
    '"YPC"': '5.7',
    '"% Tm Att"': '"13%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Ryan Tannehill"',
    '"Team"': '"TEN"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Att"': '12',
    '"Yards"': '18',
    '"TD"': '0',
    '"YPC"': '1.5',
    '"% Tm Att"': '"13%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Sam Ehlinger"',
    '"Team"': '"IND"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '6',
    '"Yards"': '15',
    '"TD"': '0',
    '"YPC"': '2.5',
    '"% Tm Att"': '"25%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Skylar Thompson"',
    '"Team"': '"MIA"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '1',
    '"Yards"': '9',
    '"TD"': '0',
    '"YPC"': '9',
    '"% Tm Att"': '"2%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Taylor Heinicke"',
    '"Team"': '"WAS"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '8',
    '"Yards"': '33',
    '"TD"': '1',
    '"YPC"': '4.1',
    '"% Tm Att"': '"12%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Teddy Bridgewater"',
    '"Team"': '"MIA"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Att"': '2',
    '"Yards"': '21',
    '"TD"': '0',
    '"YPC"': '10.5',
    '"% Tm Att"': '"2%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Tom Brady"',
    '"Team"': '"TB"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '6',
    '"Yards"': '-1',
    '"TD"': '0',
    '"YPC"': '-0.2',
    '"% Tm Att"': '"7%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Trevor Lawrence"',
    '"Team"': '"JAC"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '19',
    '"Yards"': '77',
    '"TD"': '3',
    '"YPC"': '4.1',
    '"% Tm Att"': '"19%"',
    '"FumL"': '2',
  },
  {
    '"Player"': '"Trevor Siemian"',
    '"Team"': '"CHI"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '0',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': 'NA',
    '"% Tm Att"': '"0%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Tua Tagovailoa"',
    '"Team"': '"MIA"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Att"': '9',
    '"Yards"': '34',
    '"TD"': '0',
    '"YPC"': '3.8',
    '"% Tm Att"': '"10%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Tyrod Taylor"',
    '"Team"': '"NYG"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '3',
    '"Yards"': '30',
    '"TD"': '0',
    '"YPC"': '10',
    '"% Tm Att"': '"7%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Zach Wilson"',
    '"Team"': '"NYJ"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '16',
    '"Yards"': '44',
    '"TD"': '1',
    '"YPC"': '2.8',
    '"% Tm Att"': '"10%"',
    '"FumL"': '0',
  },
];

module.exports = qbRushingLastFiveGamesFromWeeklyStatExplorer;
