const rotovizNeutralScriptOffensivePaceAndRunPassReportLastFiveWeeks = [
  {
    '"Team"': '"BAL"',
    '"GMs"': '4',
    '"Plays"': '72',
    '"Sec/Snap"': '30.9',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"54%"',
    '"Rush%"': '"46%"',
    '"Pass"': '39',
    '"Rush"': '33',
    '"No Play (Penalty)"': '43',
  },
  {
    '"Team"': '"TB"',
    '"GMs"': '4',
    '"Plays"': '64',
    '"Sec/Snap"': '25.2',
    '"No-Huddle"': '"12%"',
    '"Pass%"': '"63%"',
    '"Rush%"': '"37%"',
    '"Pass"': '40',
    '"Rush"': '23',
    '"No Play (Penalty)"': '38',
  },
  {
    '"Team"': '"DEN"',
    '"GMs"': '4',
    '"Plays"': '57',
    '"Sec/Snap"': '25.5',
    '"No-Huddle"': '"6%"',
    '"Pass%"': '"57%"',
    '"Rush%"': '"43%"',
    '"Pass"': '33',
    '"Rush"': '25',
    '"No Play (Penalty)"': '37',
  },
  {
    '"Team"': '"JAC"',
    '"GMs"': '4',
    '"Plays"': '62',
    '"Sec/Snap"': '27.7',
    '"No-Huddle"': '"5%"',
    '"Pass%"': '"54%"',
    '"Rush%"': '"46%"',
    '"Pass"': '34',
    '"Rush"': '28',
    '"No Play (Penalty)"': '48',
  },
  {
    '"Team"': '"ATL"',
    '"GMs"': '5',
    '"Plays"': '57',
    '"Sec/Snap"': '30',
    '"No-Huddle"': '"20%"',
    '"Pass%"': '"41%"',
    '"Rush%"': '"59%"',
    '"Pass"': '23',
    '"Rush"': '33',
    '"No Play (Penalty)"': '30',
  },
  {
    '"Team"': '"CAR"',
    '"GMs"': '5',
    '"Plays"': '58',
    '"Sec/Snap"': '29.3',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"45%"',
    '"Rush%"': '"55%"',
    '"Pass"': '26',
    '"Rush"': '32',
    '"No Play (Penalty)"': '40',
  },
  {
    '"Team"': '"DAL"',
    '"GMs"': '4',
    '"Plays"': '79',
    '"Sec/Snap"': '26.2',
    '"No-Huddle"': '"19%"',
    '"Pass%"': '"52%"',
    '"Rush%"': '"48%"',
    '"Pass"': '41',
    '"Rush"': '38',
    '"No Play (Penalty)"': '54',
  },
  {
    '"Team"': '"CHI"',
    '"GMs"': '5',
    '"Plays"': '58',
    '"Sec/Snap"': '29.3',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"44%"',
    '"Rush%"': '"56%"',
    '"Pass"': '25',
    '"Rush"': '33',
    '"No Play (Penalty)"': '39',
  },
  {
    '"Team"': '"DET"',
    '"GMs"': '5',
    '"Plays"': '67',
    '"Sec/Snap"': '26.4',
    '"No-Huddle"': '"5%"',
    '"Pass%"': '"54%"',
    '"Rush%"': '"46%"',
    '"Pass"': '36',
    '"Rush"': '31',
    '"No Play (Penalty)"': '36',
  },
  {
    '"Team"': '"MIA"',
    '"GMs"': '4',
    '"Plays"': '57',
    '"Sec/Snap"': '29.8',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"53%"',
    '"Rush%"': '"47%"',
    '"Pass"': '31',
    '"Rush"': '27',
    '"No Play (Penalty)"': '65',
  },
  {
    '"Team"': '"MIN"',
    '"GMs"': '5',
    '"Plays"': '64',
    '"Sec/Snap"': '27.6',
    '"No-Huddle"': '"7%"',
    '"Pass%"': '"60%"',
    '"Rush%"': '"40%"',
    '"Pass"': '38',
    '"Rush"': '25',
    '"No Play (Penalty)"': '37',
  },
  {
    '"Team"': '"ARI"',
    '"GMs"': '5',
    '"Plays"': '57',
    '"Sec/Snap"': '28.7',
    '"No-Huddle"': '"22%"',
    '"Pass%"': '"57%"',
    '"Rush%"': '"43%"',
    '"Pass"': '33',
    '"Rush"': '24',
    '"No Play (Penalty)"': '37',
  },
  {
    '"Team"': '"LV"',
    '"GMs"': '5',
    '"Plays"': '62',
    '"Sec/Snap"': '29.4',
    '"No-Huddle"': '"4%"',
    '"Pass%"': '"60%"',
    '"Rush%"': '"40%"',
    '"Pass"': '37',
    '"Rush"': '25',
    '"No Play (Penalty)"': '33',
  },
  {
    '"Team"': '"NO"',
    '"GMs"': '5',
    '"Plays"': '47',
    '"Sec/Snap"': '30.7',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"60%"',
    '"Rush%"': '"40%"',
    '"Pass"': '28',
    '"Rush"': '19',
    '"No Play (Penalty)"': '50',
  },
  {
    '"Team"': '"NYJ"',
    '"GMs"': '4',
    '"Plays"': '52',
    '"Sec/Snap"': '28.5',
    '"No-Huddle"': '"3%"',
    '"Pass%"': '"52%"',
    '"Rush%"': '"48%"',
    '"Pass"': '27',
    '"Rush"': '25',
    '"No Play (Penalty)"': '41',
  },
  {
    '"Team"': '"NE"',
    '"GMs"': '4',
    '"Plays"': '62',
    '"Sec/Snap"': '30.2',
    '"No-Huddle"': '"7%"',
    '"Pass%"': '"59%"',
    '"Rush%"': '"41%"',
    '"Pass"': '36',
    '"Rush"': '26',
    '"No Play (Penalty)"': '43',
  },
  {
    '"Team"': '"PIT"',
    '"GMs"': '4',
    '"Plays"': '71',
    '"Sec/Snap"': '28.2',
    '"No-Huddle"': '"7%"',
    '"Pass%"': '"55%"',
    '"Rush%"': '"45%"',
    '"Pass"': '39',
    '"Rush"': '32',
    '"No Play (Penalty)"': '46',
  },
  {
    '"Team"': '"PHI"',
    '"GMs"': '5',
    '"Plays"': '62',
    '"Sec/Snap"': '26.2',
    '"No-Huddle"': '"21%"',
    '"Pass%"': '"50%"',
    '"Rush%"': '"50%"',
    '"Pass"': '31',
    '"Rush"': '31',
    '"No Play (Penalty)"': '38',
  },
  {
    '"Team"': '"TEN"',
    '"GMs"': '5',
    '"Plays"': '53',
    '"Sec/Snap"': '30.9',
    '"No-Huddle"': '"1%"',
    '"Pass%"': '"50%"',
    '"Rush%"': '"50%"',
    '"Pass"': '26',
    '"Rush"': '27',
    '"No Play (Penalty)"': '34',
  },
  {
    '"Team"': '"HOU"',
    '"GMs"': '5',
    '"Plays"': '46',
    '"Sec/Snap"': '31.1',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"49%"',
    '"Rush%"': '"51%"',
    '"Pass"': '22',
    '"Rush"': '23',
    '"No Play (Penalty)"': '52',
  },
  {
    '"Team"': '"IND"',
    '"GMs"': '5',
    '"Plays"': '61',
    '"Sec/Snap"': '27.9',
    '"No-Huddle"': '"7%"',
    '"Pass%"': '"52%"',
    '"Rush%"': '"48%"',
    '"Pass"': '32',
    '"Rush"': '30',
    '"No Play (Penalty)"': '36',
  },
  {
    '"Team"': '"WAS"',
    '"GMs"': '5',
    '"Plays"': '65',
    '"Sec/Snap"': '30.7',
    '"No-Huddle"': '"5%"',
    '"Pass%"': '"43%"',
    '"Rush%"': '"57%"',
    '"Pass"': '28',
    '"Rush"': '37',
    '"No Play (Penalty)"': '33',
  },
  {
    '"Team"': '"LAR"',
    '"GMs"': '5',
    '"Plays"': '50',
    '"Sec/Snap"': '30.5',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"54%"',
    '"Rush%"': '"46%"',
    '"Pass"': '27',
    '"Rush"': '23',
    '"No Play (Penalty)"': '36',
  },
  {
    '"Team"': '"SF"',
    '"GMs"': '4',
    '"Plays"': '65',
    '"Sec/Snap"': '31.3',
    '"No-Huddle"': '"3%"',
    '"Pass%"': '"52%"',
    '"Rush%"': '"48%"',
    '"Pass"': '33',
    '"Rush"': '31',
    '"No Play (Penalty)"': '50',
  },
  {
    '"Team"': '"SEA"',
    '"GMs"': '4',
    '"Plays"': '57',
    '"Sec/Snap"': '27',
    '"No-Huddle"': '"17%"',
    '"Pass%"': '"61%"',
    '"Rush%"': '"39%"',
    '"Pass"': '35',
    '"Rush"': '23',
    '"No Play (Penalty)"': '39',
  },
  {
    '"Team"': '"NYG"',
    '"GMs"': '4',
    '"Plays"': '59',
    '"Sec/Snap"': '30.2',
    '"No-Huddle"': '"21%"',
    '"Pass%"': '"44%"',
    '"Rush%"': '"56%"',
    '"Pass"': '26',
    '"Rush"': '33',
    '"No Play (Penalty)"': '50',
  },
  {
    '"Team"': '"BUF"',
    '"GMs"': '5',
    '"Plays"': '64',
    '"Sec/Snap"': '27.6',
    '"No-Huddle"': '"12%"',
    '"Pass%"': '"58%"',
    '"Rush%"': '"42%"',
    '"Pass"': '37',
    '"Rush"': '27',
    '"No Play (Penalty)"': '38',
  },
  {
    '"Team"': '"GB"',
    '"GMs"': '5',
    '"Plays"': '46',
    '"Sec/Snap"': '31.2',
    '"No-Huddle"': '"3%"',
    '"Pass%"': '"54%"',
    '"Rush%"': '"46%"',
    '"Pass"': '25',
    '"Rush"': '21',
    '"No Play (Penalty)"': '40',
  },
  {
    '"Team"': '"CIN"',
    '"GMs"': '4',
    '"Plays"': '66',
    '"Sec/Snap"': '29.1',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"62%"',
    '"Rush%"': '"38%"',
    '"Pass"': '41',
    '"Rush"': '25',
    '"No Play (Penalty)"': '51',
  },
  {
    '"Team"': '"CLE"',
    '"GMs"': '4',
    '"Plays"': '64',
    '"Sec/Snap"': '30.5',
    '"No-Huddle"': '"10%"',
    '"Pass%"': '"53%"',
    '"Rush%"': '"47%"',
    '"Pass"': '34',
    '"Rush"': '30',
    '"No Play (Penalty)"': '49',
  },
  {
    '"Team"': '"LAC"',
    '"GMs"': '4',
    '"Plays"': '58',
    '"Sec/Snap"': '26.4',
    '"No-Huddle"': '"8%"',
    '"Pass%"': '"67%"',
    '"Rush%"': '"33%"',
    '"Pass"': '39',
    '"Rush"': '19',
    '"No Play (Penalty)"': '37',
  },
  {
    '"Team"': '"KC"',
    '"GMs"': '4',
    '"Plays"': '71',
    '"Sec/Snap"': '25.1',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"65%"',
    '"Rush%"': '"35%"',
    '"Pass"': '46',
    '"Rush"': '25',
    '"No Play (Penalty)"': '53',
  },
];

module.exports = rotovizNeutralScriptOffensivePaceAndRunPassReportLastFiveWeeks;
