const gppLeverageScoresAndProjOwnershipFanduel = [
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Justin Jefferson\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"LAC\"",
		"\"FD Sal $\"": "\"9700\"",
		"\"Projected Own%\"": "\"27.5%\"",
		"\"Cash Odds\"": "\"58%\"",
		"\"GPP Odds\"": "\"20%\"",
		"\"Implied Own%\"": "\"27%\"",
		"\"FD LEV\"": "\"0.98\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tyreek Hill\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"9600\"",
		"\"Projected Own%\"": "\"17.5%\"",
		"\"Cash Odds\"": "\"60%\"",
		"\"GPP Odds\"": "\"23%\"",
		"\"Implied Own%\"": "\"31%\"",
		"\"FD LEV\"": "\"1.79\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tony Pollard\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@ARI\"",
		"\"FD Sal $\"": "\"9400\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"60%\"",
		"\"GPP Odds\"": "\"20%\"",
		"\"Implied Own%\"": "\"25%\"",
		"\"FD LEV\"": "\"2.01\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Patrick Mahomes\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"9200\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"61%\"",
		"\"GPP Odds\"": "\"33%\"",
		"\"Implied Own%\"": "\"10%\"",
		"\"FD LEV\"": "\"0.78\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Bijan Robinson\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@DET\"",
		"\"FD Sal $\"": "\"9000\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"18%\"",
		"\"FD LEV\"": "\"2.34\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Keenan Allen\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@MIN\"",
		"\"FD Sal $\"": "\"8800\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"0.92\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Josh Allen\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"8800\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"50%\"",
		"\"GPP Odds\"": "\"22%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"0.89\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"CeeDee Lamb\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@ARI\"",
		"\"FD Sal $\"": "\"8500\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"46%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"15%\"",
		"\"FD LEV\"": "\"1.20\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Derrick Henry\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"FD Sal $\"": "\"8400\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"51%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"16%\"",
		"\"FD LEV\"": "\"2.11\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Justin Herbert\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@MIN\"",
		"\"FD Sal $\"": "\"8400\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"49%\"",
		"\"GPP Odds\"": "\"20%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.81\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Lamar Jackson\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"8200\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"23%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"0.92\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Tua Tagovailoa\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"8100\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.60\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Travis Etienne\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"HOU\"",
		"\"FD Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"17.5%\"",
		"\"Cash Odds\"": "\"56%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"17%\"",
		"\"FD LEV\"": "\"0.98\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Stefon Diggs\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"17.5%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"14%\"",
		"\"FD LEV\"": "\"0.78\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Travis Kelce\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"8000\"",
		"\"Projected Own%\"": "\"17.5%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"13%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"0.64\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Amon-Ra St. Brown\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"7900\"",
		"\"Projected Own%\"": "\"17.5%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"FD LEV\"": "\"0.75\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Chris Olave\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"7800\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"FD LEV\"": "\"0.93\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Kirk Cousins\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"LAC\"",
		"\"FD Sal $\"": "\"7800\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"51%\"",
		"\"GPP Odds\"": "\"20%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.49\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Justin Fields\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@KC\"",
		"\"FD Sal $\"": "\"7700\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"16%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.64\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Kenneth Walker\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"7600\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"55%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"17%\"",
		"\"FD LEV\"": "\"2.29\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Dak Prescott\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@ARI\"",
		"\"FD Sal $\"": "\"7600\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.50\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Trevor Lawrence\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"HOU\"",
		"\"FD Sal $\"": "\"7600\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"50%\"",
		"\"GPP Odds\"": "\"21%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.84\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Brian Robinson\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"7500\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"2.89\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Deshaun Watson\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"7500\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"17%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.72\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jared Goff\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"7500\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"14%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.40\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Calvin Ridley\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"HOU\"",
		"\"FD Sal $\"": "\"7500\"",
		"\"Projected Own%\"": "\"17.5%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"0.65\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"T.J. Hockenson\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"LAC\"",
		"\"FD Sal $\"": "\"7500\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"0.59\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Russell Wilson\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"7400\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.21\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DK Metcalf\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"7400\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"1.13\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Mark Andrews\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"7400\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.82\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Jordan Love\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"7300\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"12%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.23\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tyler Lockett\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"7300\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"38%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"1.20\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Garrett Wilson\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"1.94\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Geno Smith\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.49\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Mike Williams\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@MIN\"",
		"\"FD Sal $\"": "\"7200\"",
		"\"Projected Own%\"": "\"22.5%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"0.48\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Terry McLaurin\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"7100\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.54\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Gardner Minshew\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"7100\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.98\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Josh Reynolds\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"7.78\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Desmond Ridder\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@DET\"",
		"\"FD Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"4.62\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jahmyr Gibbs\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"52%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"13%\"",
		"\"FD LEV\"": "\"1.03\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Sam Howell\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"7000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.96\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Nico Collins\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"1.87\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"James Cook\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"1.02\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Derek Carr\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"6900\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.90\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jordan Addison\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"LAC\"",
		"\"FD Sal $\"": "\"6800\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"2.29\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Mac Jones\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@NYJ\"",
		"\"FD Sal $\"": "\"6800\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.73\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Ryan Tannehill\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"FD Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.32\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Gabe Davis\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.53\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Michael Pittman Jr.\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"0.71\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Miles Sanders\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"6700\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"0.64\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tyler Allgeier\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@DET\"",
		"\"FD Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"8.76\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Raheem Mostert\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"17.5%\"",
		"\"Cash Odds\"": "\"59%\"",
		"\"GPP Odds\"": "\"15%\"",
		"\"Implied Own%\"": "\"19%\"",
		"\"FD LEV\"": "\"1.06\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"C.J. Stroud\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.88\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DeAndre Hopkins\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"FD Sal $\"": "\"6600\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.72\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Joshua Dobbs\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.36\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Drake London\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@DET\"",
		"\"FD Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.67\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Christian Kirk\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"HOU\"",
		"\"FD Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.80\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Rhamondre Stevenson\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@NYJ\"",
		"\"FD Sal $\"": "\"6500\"",
		"\"Projected Own%\"": "\"17.5%\"",
		"\"Cash Odds\"": "\"54%\"",
		"\"GPP Odds\"": "\"11%\"",
		"\"Implied Own%\"": "\"14%\"",
		"\"FD LEV\"": "\"0.78\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Bryce Young\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"5.42\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"D.J. Moore\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@KC\"",
		"\"FD Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"2.14\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Breece Hall\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.37\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Zack Moss\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"6400\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"51%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"11%\"",
		"\"FD LEV\"": "\"0.91\""
	},
	{
		"\"Pos\"": "\"QB\"",
		"\"Player\"": "\"Zach Wilson\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"4.84\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Courtland Sutton\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"1.05\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Zay Flowers\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"1.05\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"A.J. Dillon\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.70\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Alexander Mattison\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"LAC\"",
		"\"FD Sal $\"": "\"6300\"",
		"\"Projected Own%\"": "\"17.5%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"10%\"",
		"\"FD LEV\"": "\"0.55\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Marquise Brown\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"6200\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.60\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Gus Edwards\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"6200\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.46\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Amari Cooper\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"6200\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"47%\"",
		"\"GPP Odds\"": "\"9%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"FD LEV\"": "\"0.98\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"James Conner\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"6200\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.49\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Elijah Moore\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.42\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Joshua Kelley\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@MIN\"",
		"\"FD Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"50%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"FD LEV\"": "\"0.97\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Javonte Williams\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"0.89\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jerry Jeudy\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"6100\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.38\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Rashid Shaheed\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.71\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Zay Jones\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"HOU\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.63\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Justice Hill\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"6000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"10%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.37\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Dalvin Cook\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"4.82\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Kendrick Bourne\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@NYJ\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"4.12\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jayden Reed\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.79\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Romeo Doubs\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.75\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Chuba Hubbard\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.71\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Donovan Peoples-Jones\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"13%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.12\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Evan Engram\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"HOU\"",
		"\"FD Sal $\"": "\"5900\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.85\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Allen Lazard\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.58\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Dameon Pierce\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.76\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Ezekiel Elliott\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@NYJ\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.68\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jahan Dotson\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.82\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Robert Woods\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.55\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Michael Thomas\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"5800\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.40\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Hunter Henry\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@NYJ\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"9.22\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Curtis Samuel\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.78\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Adam Thielen\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.99\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Craig Reynolds\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.94\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Treylon Burks\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"23%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.75\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Isiah Pacheco\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"17.5%\"",
		"\"Cash Odds\"": "\"53%\"",
		"\"GPP Odds\"": "\"10%\"",
		"\"Implied Own%\"": "\"12%\"",
		"\"FD LEV\"": "\"0.69\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Marvin Jones\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"5700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"8%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.29\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Darnell Mooney\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@KC\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.65\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Rashod Bateman\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.83\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Nick Westbrook-Ikhine\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"14%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.12\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"JuJu Smith-Schuster\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@NYJ\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"13%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.92\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"K.J. Osborn\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"LAC\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"23%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.76\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Skyy Moore\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"23%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.74\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"D.J. Chark\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"11%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.71\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Khalil Herbert\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@KC\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.60\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jerome Ford\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"17.5%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"0.41\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Devin Singletary\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"5600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"7%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.10\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Hayden Hurst\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"5.68\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Nelson Agholor\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.02\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Taysom Hill\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.06\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Mack Hollins\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@DET\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"15%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.52\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Samaje Perine\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.34\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Kadarius Toney\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.56\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Chase Claypool\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@KC\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"9%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.35\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Mecole Hardman\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"5%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.09\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Damien Harris\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"5500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"6%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.08\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"David Njoku\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"38%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"2.11\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Kyle Pitts\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@DET\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.39\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Tank Dell\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"24%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.80\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"DeVante Parker\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@NYJ\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.68\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Marquez Valdes-Scantling\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.54\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Terrace Marshall\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"5400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"6%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.10\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Gerald Everett\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@MIN\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"7.11\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Michael Gallup\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@ARI\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"5.27\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Marvin Mims\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.08\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Odell Beckham\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.93\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jaxon Smith-Njigba\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.85\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Kalif Raymond\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"12%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.76\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Brandon Johnson\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"10%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.45\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Dawson Knox\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"14%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.26\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Laviska Shenault\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"8%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.23\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Antonio Gibson\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"5300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"4%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.02\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"River Cracraft\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"5.73\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Dallas Cowboys\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@ARI\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"32%\"",
		"\"FD LEV\"": "\"4.20\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Alec Pierce\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"15%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.41\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Rondale Moore\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"13%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.96\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Sam LaPorta\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"40%\"",
		"\"GPP Odds\"": "\"8%\"",
		"\"Implied Own%\"": "\"7%\"",
		"\"FD LEV\"": "\"0.93\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Latavius Murray\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"14%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.63\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Melvin Gordon\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"5200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"11%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.36\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Cole Kmet\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@KC\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"8.84\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Braxton Berrios\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"7.19\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Justin Watson\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"5.03\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jonathan Mingo\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"18%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.22\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tank Bigsby\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"HOU\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"17%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.96\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Zach Ertz\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.60\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Randall Cobb\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"6%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.11\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Keaontay Ingram\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"5100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"2%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"New England Patriots\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@NYJ\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"2.80\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Rashee Rice\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.37\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Jake Ferguson\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@ARI\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"7%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"1.98\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Dalton Kincaid\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"1.62\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Jerick McKinnon\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.45\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Juwan Johnson\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.22\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Josh Downs\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"24%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.75\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Devon Achane\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"9%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.13\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Deon Jackson\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"4%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.02\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Demario Douglas\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@NYJ\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"3%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Ty Montgomery\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@NYJ\"",
		"\"FD Sal $\"": "\"5000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"3%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Noah Fant\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"18%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.45\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Tyler Conklin\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"18%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.23\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Josh Palmer\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@MIN\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.17\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Dontayvion Wicks\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"14%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.01\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Luke Musgrave\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"6%\"",
		"\"Implied Own%\"": "\"5%\"",
		"\"FD LEV\"": "\"0.65\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Clyde Edwards-Helaire\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"10%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.19\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"David Bell\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"5%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.05\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Khalil Shakir\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"4900\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"3%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Logan Thomas\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"29%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"6.23\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Michael Wilson\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"22%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.28\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Kansas City Chiefs\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"45%\"",
		"\"GPP Odds\"": "\"5%\"",
		"\"Implied Own%\"": "\"22%\"",
		"\"FD LEV\"": "\"2.91\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Durham Smythe\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"1.28\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Chigoziem Okonkwo\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"30%\"",
		"\"GPP Odds\"": "\"4%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"1.13\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Kylen Granson\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"28%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"1.00\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tyjae Spears\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"18%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.93\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Dalton Schultz\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.93\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Quentin Johnston\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@MIN\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"11%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.49\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jamal Agnew\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"HOU\"",
		"\"FD Sal $\"": "\"4800\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"3%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Jacksonville Jaguars\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"HOU\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"15%\"",
		"\"FD LEV\"": "\"4.90\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Mike Gesicki\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@NYJ\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"21%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"3.13\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Will Dissly\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"18%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.25\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Harrison Bryant\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"16%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.48\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Jalen Tolbert\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@ARI\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"15%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.02\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Roschon Johnson\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@KC\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"2%\"",
		"\"FD LEV\"": "\"0.80\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Erik Ezukanma\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"13%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.68\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Jonnu Smith\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@DET\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"8%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.28\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Rico Dowdle\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@ARI\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"10%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.19\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"John Metchie\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"8%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.18\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Patrick Taylor\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"8%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.10\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Cedric Tillman\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"4%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.03\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Chris Moore\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"3%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Emari Demercado\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"4700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"2%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Foster Moreau\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"12%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.78\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Noah Gray\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"10%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.51\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Colby Parkinson\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"10%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.48\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Josh Oliver\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"LAC\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"9%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.37\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Ty Chandler\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"LAC\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"12%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.30\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Zach Charbonnet\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"12%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.29\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Elijah Dotson\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@MIN\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"12%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.25\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Kendre Miller\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"18%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.15\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Cole Turner\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"5%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.09\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Dyami Brown\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"5%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.04\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Richie James\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"4%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.02\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Isaiah McKenzie\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"3%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Lil'Jordan Humphrey\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"2%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"D'Ernest Johnson\"",
		"\"Tm\"": "\"JAX\"",
		"\"Opp\"": "\"HOU\"",
		"\"FD Sal $\"": "\"4600\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"2%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Trey McBride\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.56\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Samori Toure\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"2.25\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Tony Jones\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.08\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Donald Parham\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@MIN\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"27%\"",
		"\"GPP Odds\"": "\"3%\"",
		"\"Implied Own%\"": "\"3%\"",
		"\"FD LEV\"": "\"0.85\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Baltimore Ravens\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"37%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.74\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Emanuel Wilson\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"16%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.66\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Luke Schoonmaker\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@ARI\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"9%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.39\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"KhaDarel Hodge\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@DET\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"7%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.11\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Zach Pascal\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"3%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.02\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Isaiah Spiller\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@MIN\"",
		"\"FD Sal $\"": "\"4500\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"4%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Brock Wright\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.96\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Mo Alie-Cox\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"15%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"1.14\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Buffalo Bills\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"41%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"8%\"",
		"\"FD LEV\"": "\"1.04\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"C.J. Uzomah\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"12%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.65\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Deuce Vaughn\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@ARI\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"16%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.59\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Isaiah Likely\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"9%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.32\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Brevin Jordan\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"9%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.30\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"KaVontae Turpin\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@ARI\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"8%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.20\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Michael Carter\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"10%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.13\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Ian Thomas\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"5%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.09\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Scott Miller\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@DET\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"4%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.02\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Greg Dortch\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"4400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"2%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Cleveland Browns\"",
		"\"Tm\"": "\"CLE\"",
		"\"Opp\"": "\"TEN\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"43%\"",
		"\"GPP Odds\"": "\"2%\"",
		"\"Implied Own%\"": "\"9%\"",
		"\"FD LEV\"": "\"1.16\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Deonte Harty\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"12%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.52\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Adam Trautman\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"19%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.34\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Josiah Deguara\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"9%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.31\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Peyton Hendershot\"",
		"\"Tm\"": "\"DAL\"",
		"\"Opp\"": "\"@ARI\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"9%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.31\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Robert Tonyan\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@KC\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"7%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.15\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Teagan Quitoriano\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"6%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.10\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Alec Ingold\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"8%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.06\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Justyn Ross\"",
		"\"Tm\"": "\"KC\"",
		"\"Opp\"": "\"CHI\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"6%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.06\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Derius Davis\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@MIN\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"5%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.03\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"DeeJay Dallas\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"6%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.02\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Reggie Gilliam\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"4300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"2%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Seattle Seahawks\"",
		"\"Tm\"": "\"SEA\"",
		"\"Opp\"": "\"CAR\"",
		"\"FD Sal $\"": "\"4200\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"42%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"6%\"",
		"\"FD LEV\"": "\"0.79\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Quintin Morris\"",
		"\"Tm\"": "\"BUF\"",
		"\"Opp\"": "\"@WAS\"",
		"\"FD Sal $\"": "\"4200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"6%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.10\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Pharaoh Brown\"",
		"\"Tm\"": "\"NE\"",
		"\"Opp\"": "\"@NYJ\"",
		"\"FD Sal $\"": "\"4200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"5%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.09\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"C.J. Ham\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"LAC\"",
		"\"FD Sal $\"": "\"4200\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"4%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"New Orleans Saints\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"4100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"26%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.35\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Tommy Tremble\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"4100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"9%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.25\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Green Bay Packers\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"4100\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.19\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Chris Manhertz\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"4100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"7%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.16\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"James Mitchell\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"4100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"7%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.13\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Malik Heath\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"4100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"4%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.02\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Patrick Ricard\"",
		"\"Tm\"": "\"BAL\"",
		"\"Opp\"": "\"IND\"",
		"\"FD Sal $\"": "\"4100\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"3%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Detroit Lions\"",
		"\"Tm\"": "\"DET\"",
		"\"Opp\"": "\"ATL\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.32\""
	},
	{
		"\"Pos\"": "\"TE\"",
		"\"Player\"": "\"Tucker Kraft\"",
		"\"Tm\"": "\"GB\"",
		"\"Opp\"": "\"NO\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"8%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.18\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Chris Brooks\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"8%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.05\""
	},
	{
		"\"Pos\"": "\"WR\"",
		"\"Player\"": "\"Juwann Winfree\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"5%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.03\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Washington Commanders\"",
		"\"Tm\"": "\"WAS\"",
		"\"Opp\"": "\"BUF\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Michael Burton\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"4%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"RB\"",
		"\"Player\"": "\"Adam Prentice\"",
		"\"Tm\"": "\"NO\"",
		"\"Opp\"": "\"@GB\"",
		"\"FD Sal $\"": "\"4000\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"3%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Miami Dolphins\"",
		"\"Tm\"": "\"MIA\"",
		"\"Opp\"": "\"DEN\"",
		"\"FD Sal $\"": "\"3900\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"44%\"",
		"\"GPP Odds\"": "\"1%\"",
		"\"Implied Own%\"": "\"4%\"",
		"\"FD LEV\"": "\"0.53\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"New York Jets\"",
		"\"Tm\"": "\"NYJ\"",
		"\"Opp\"": "\"NE\"",
		"\"FD Sal $\"": "\"3900\"",
		"\"Projected Own%\"": "\"12.5%\"",
		"\"Cash Odds\"": "\"36%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"1%\"",
		"\"FD LEV\"": "\"0.08\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Tennessee Titans\"",
		"\"Tm\"": "\"TEN\"",
		"\"Opp\"": "\"@CLE\"",
		"\"FD Sal $\"": "\"3800\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"31%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.03\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Indianapolis Colts\"",
		"\"Tm\"": "\"IND\"",
		"\"Opp\"": "\"@BAL\"",
		"\"FD Sal $\"": "\"3800\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"25%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Atlanta Falcons\"",
		"\"Tm\"": "\"ATL\"",
		"\"Opp\"": "\"@DET\"",
		"\"FD Sal $\"": "\"3700\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"20%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.01\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Los Angeles Chargers\"",
		"\"Tm\"": "\"LAC\"",
		"\"Opp\"": "\"@MIN\"",
		"\"FD Sal $\"": "\"3600\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.07\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Carolina Panthers\"",
		"\"Tm\"": "\"CAR\"",
		"\"Opp\"": "\"@SEA\"",
		"\"FD Sal $\"": "\"3500\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"35%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.04\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Denver Broncos\"",
		"\"Tm\"": "\"DEN\"",
		"\"Opp\"": "\"@MIA\"",
		"\"FD Sal $\"": "\"3400\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"34%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.13\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Minnesota Vikings\"",
		"\"Tm\"": "\"MIN\"",
		"\"Opp\"": "\"LAC\"",
		"\"FD Sal $\"": "\"3300\"",
		"\"Projected Own%\"": "\"0.5%\"",
		"\"Cash Odds\"": "\"39%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.28\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Houston Texans\"",
		"\"Tm\"": "\"HOU\"",
		"\"Opp\"": "\"@JAX\"",
		"\"FD Sal $\"": "\"3200\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Arizona Cardinals\"",
		"\"Tm\"": "\"ARI\"",
		"\"Opp\"": "\"DAL\"",
		"\"FD Sal $\"": "\"3100\"",
		"\"Projected Own%\"": "\"7.5%\"",
		"\"Cash Odds\"": "\"32%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	},
	{
		"\"Pos\"": "\"DEF\"",
		"\"Player\"": "\"Chicago Bears\"",
		"\"Tm\"": "\"CHI\"",
		"\"Opp\"": "\"@KC\"",
		"\"FD Sal $\"": "\"3000\"",
		"\"Projected Own%\"": "\"3.0%\"",
		"\"Cash Odds\"": "\"33%\"",
		"\"GPP Odds\"": "\"0%\"",
		"\"Implied Own%\"": "\"0%\"",
		"\"FD LEV\"": "\"0.00\""
	}
]

module.exports = gppLeverageScoresAndProjOwnershipFanduel;