const rotovizNeutralScriptOffensivePaceAndRunPassReportLastFiveWeeks = [
  {
    '"Team"': '"IND"',
    '"GMs"': '5',
    '"Plays"': '58',
    '"Sec/Snap"': '26.1',
    '"No-Huddle"': '"21%"',
    '"Pass%"': '"62%"',
    '"Rush%"': '"38%"',
    '"Pass"': '36',
    '"Rush"': '22',
    '"No Play (Penalty)"': '45',
  },
  {
    '"Team"': '"DEN"',
    '"GMs"': '4',
    '"Plays"': '61',
    '"Sec/Snap"': '26.6',
    '"No-Huddle"': '"5%"',
    '"Pass%"': '"57%"',
    '"Rush%"': '"43%"',
    '"Pass"': '35',
    '"Rush"': '26',
    '"No Play (Penalty)"': '41',
  },
  {
    '"Team"': '"GB"',
    '"GMs"': '5',
    '"Plays"': '60',
    '"Sec/Snap"': '28.2',
    '"No-Huddle"': '"3%"',
    '"Pass%"': '"67%"',
    '"Rush%"': '"33%"',
    '"Pass"': '40',
    '"Rush"': '20',
    '"No Play (Penalty)"': '52',
  },
  {
    '"Team"': '"NYG"',
    '"GMs"': '4',
    '"Plays"': '57',
    '"Sec/Snap"': '29.6',
    '"No-Huddle"': '"22%"',
    '"Pass%"': '"48%"',
    '"Rush%"': '"52%"',
    '"Pass"': '28',
    '"Rush"': '30',
    '"No Play (Penalty)"': '48',
  },
  {
    '"Team"': '"BUF"',
    '"GMs"': '4',
    '"Plays"': '66',
    '"Sec/Snap"': '28.2',
    '"No-Huddle"': '"8%"',
    '"Pass%"': '"58%"',
    '"Rush%"': '"42%"',
    '"Pass"': '38',
    '"Rush"': '28',
    '"No Play (Penalty)"': '65',
  },
  {
    '"Team"': '"PIT"',
    '"GMs"': '4',
    '"Plays"': '67',
    '"Sec/Snap"': '26.6',
    '"No-Huddle"': '"16%"',
    '"Pass%"': '"63%"',
    '"Rush%"': '"37%"',
    '"Pass"': '42',
    '"Rush"': '25',
    '"No Play (Penalty)"': '72',
  },
  {
    '"Team"': '"CLE"',
    '"GMs"': '4',
    '"Plays"': '52',
    '"Sec/Snap"': '28.9',
    '"No-Huddle"': '"10%"',
    '"Pass%"': '"53%"',
    '"Rush%"': '"47%"',
    '"Pass"': '28',
    '"Rush"': '25',
    '"No Play (Penalty)"': '61',
  },
  {
    '"Team"': '"LAC"',
    '"GMs"': '4',
    '"Plays"': '65',
    '"Sec/Snap"': '23.7',
    '"No-Huddle"': '"7%"',
    '"Pass%"': '"61%"',
    '"Rush%"': '"39%"',
    '"Pass"': '40',
    '"Rush"': '25',
    '"No Play (Penalty)"': '55',
  },
  {
    '"Team"': '"HOU"',
    '"GMs"': '4',
    '"Plays"': '53',
    '"Sec/Snap"': '31.7',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"48%"',
    '"Rush%"': '"52%"',
    '"Pass"': '25',
    '"Rush"': '27',
    '"No Play (Penalty)"': '51',
  },
  {
    '"Team"': '"JAC"',
    '"GMs"': '5',
    '"Plays"': '70',
    '"Sec/Snap"': '26.1',
    '"No-Huddle"': '"17%"',
    '"Pass%"': '"54%"',
    '"Rush%"': '"46%"',
    '"Pass"': '38',
    '"Rush"': '32',
    '"No Play (Penalty)"': '39',
  },
  {
    '"Team"': '"MIN"',
    '"GMs"': '4',
    '"Plays"': '63',
    '"Sec/Snap"': '28.7',
    '"No-Huddle"': '"9%"',
    '"Pass%"': '"59%"',
    '"Rush%"': '"41%"',
    '"Pass"': '38',
    '"Rush"': '26',
    '"No Play (Penalty)"': '53',
  },
  {
    '"Team"': '"CHI"',
    '"GMs"': '5',
    '"Plays"': '60',
    '"Sec/Snap"': '28.1',
    '"No-Huddle"': '"6%"',
    '"Pass%"': '"48%"',
    '"Rush%"': '"52%"',
    '"Pass"': '29',
    '"Rush"': '31',
    '"No Play (Penalty)"': '55',
  },
  {
    '"Team"': '"DET"',
    '"GMs"': '4',
    '"Plays"': '64',
    '"Sec/Snap"': '29',
    '"No-Huddle"': '"5%"',
    '"Pass%"': '"49%"',
    '"Rush%"': '"51%"',
    '"Pass"': '32',
    '"Rush"': '33',
    '"No Play (Penalty)"': '61',
  },
  {
    '"Team"': '"NE"',
    '"GMs"': '5',
    '"Plays"': '60',
    '"Sec/Snap"': '29.4',
    '"No-Huddle"': '"9%"',
    '"Pass%"': '"54%"',
    '"Rush%"': '"46%"',
    '"Pass"': '33',
    '"Rush"': '28',
    '"No Play (Penalty)"': '65',
  },
  {
    '"Team"': '"NO"',
    '"GMs"': '5',
    '"Plays"': '67',
    '"Sec/Snap"': '29.3',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"45%"',
    '"Rush%"': '"55%"',
    '"Pass"': '30',
    '"Rush"': '37',
    '"No Play (Penalty)"': '57',
  },
  {
    '"Team"': '"SEA"',
    '"GMs"': '5',
    '"Plays"': '64',
    '"Sec/Snap"': '27.3',
    '"No-Huddle"': '"11%"',
    '"Pass%"': '"59%"',
    '"Rush%"': '"41%"',
    '"Pass"': '38',
    '"Rush"': '26',
    '"No Play (Penalty)"': '45',
  },
  {
    '"Team"': '"NYJ"',
    '"GMs"': '5',
    '"Plays"': '55',
    '"Sec/Snap"': '29.5',
    '"No-Huddle"': '"4%"',
    '"Pass%"': '"52%"',
    '"Rush%"': '"48%"',
    '"Pass"': '28',
    '"Rush"': '27',
    '"No Play (Penalty)"': '41',
  },
  {
    '"Team"': '"MIA"',
    '"GMs"': '5',
    '"Plays"': '59',
    '"Sec/Snap"': '28.4',
    '"No-Huddle"': '"6%"',
    '"Pass%"': '"57%"',
    '"Rush%"': '"43%"',
    '"Pass"': '34',
    '"Rush"': '26',
    '"No Play (Penalty)"': '46',
  },
  {
    '"Team"': '"TB"',
    '"GMs"': '5',
    '"Plays"': '66',
    '"Sec/Snap"': '24.9',
    '"No-Huddle"': '"13%"',
    '"Pass%"': '"66%"',
    '"Rush%"': '"34%"',
    '"Pass"': '44',
    '"Rush"': '23',
    '"No Play (Penalty)"': '42',
  },
  {
    '"Team"': '"ATL"',
    '"GMs"': '5',
    '"Plays"': '62',
    '"Sec/Snap"': '31.8',
    '"No-Huddle"': '"18%"',
    '"Pass%"': '"41%"',
    '"Rush%"': '"59%"',
    '"Pass"': '26',
    '"Rush"': '36',
    '"No Play (Penalty)"': '54',
  },
  {
    '"Team"': '"TEN"',
    '"GMs"': '4',
    '"Plays"': '58',
    '"Sec/Snap"': '31.4',
    '"No-Huddle"': '"1%"',
    '"Pass%"': '"44%"',
    '"Rush%"': '"56%"',
    '"Pass"': '26',
    '"Rush"': '32',
    '"No Play (Penalty)"': '59',
  },
  {
    '"Team"': '"WAS"',
    '"GMs"': '5',
    '"Plays"': '59',
    '"Sec/Snap"': '29.2',
    '"No-Huddle"': '"6%"',
    '"Pass%"': '"53%"',
    '"Rush%"': '"47%"',
    '"Pass"': '31',
    '"Rush"': '28',
    '"No Play (Penalty)"': '36',
  },
  {
    '"Team"': '"SF"',
    '"GMs"': '4',
    '"Plays"': '52',
    '"Sec/Snap"': '31.2',
    '"No-Huddle"': '"1%"',
    '"Pass%"': '"61%"',
    '"Rush%"': '"39%"',
    '"Pass"': '32',
    '"Rush"': '20',
    '"No Play (Penalty)"': '75',
  },
  {
    '"Team"': '"CAR"',
    '"GMs"': '5',
    '"Plays"': '46',
    '"Sec/Snap"': '28.1',
    '"No-Huddle"': '"3%"',
    '"Pass%"': '"51%"',
    '"Rush%"': '"49%"',
    '"Pass"': '23',
    '"Rush"': '23',
    '"No Play (Penalty)"': '51',
  },
  {
    '"Team"': '"ARI"',
    '"GMs"': '5',
    '"Plays"': '51',
    '"Sec/Snap"': '26.8',
    '"No-Huddle"': '"33%"',
    '"Pass%"': '"56%"',
    '"Rush%"': '"44%"',
    '"Pass"': '28',
    '"Rush"': '22',
    '"No Play (Penalty)"': '48',
  },
  {
    '"Team"': '"PHI"',
    '"GMs"': '4',
    '"Plays"': '72',
    '"Sec/Snap"': '28.7',
    '"No-Huddle"': '"25%"',
    '"Pass%"': '"53%"',
    '"Rush%"': '"47%"',
    '"Pass"': '39',
    '"Rush"': '34',
    '"No Play (Penalty)"': '65',
  },
  {
    '"Team"': '"LAR"',
    '"GMs"': '4',
    '"Plays"': '58',
    '"Sec/Snap"': '30.7',
    '"No-Huddle"': '"3%"',
    '"Pass%"': '"63%"',
    '"Rush%"': '"37%"',
    '"Pass"': '36',
    '"Rush"': '21',
    '"No Play (Penalty)"': '53',
  },
  {
    '"Team"': '"DAL"',
    '"GMs"': '4',
    '"Plays"': '60',
    '"Sec/Snap"': '28.8',
    '"No-Huddle"': '"17%"',
    '"Pass%"': '"51%"',
    '"Rush%"': '"49%"',
    '"Pass"': '30',
    '"Rush"': '29',
    '"No Play (Penalty)"': '76',
  },
  {
    '"Team"': '"CIN"',
    '"GMs"': '5',
    '"Plays"': '56',
    '"Sec/Snap"': '29.5',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"70%"',
    '"Rush%"': '"30%"',
    '"Pass"': '40',
    '"Rush"': '17',
    '"No Play (Penalty)"': '66',
  },
  {
    '"Team"': '"BAL"',
    '"GMs"': '5',
    '"Plays"': '71',
    '"Sec/Snap"': '30.6',
    '"No-Huddle"': '"3%"',
    '"Pass%"': '"50%"',
    '"Rush%"': '"50%"',
    '"Pass"': '36',
    '"Rush"': '35',
    '"No Play (Penalty)"': '43',
  },
  {
    '"Team"': '"LV"',
    '"GMs"': '4',
    '"Plays"': '64',
    '"Sec/Snap"': '28.3',
    '"No-Huddle"': '"5%"',
    '"Pass%"': '"61%"',
    '"Rush%"': '"39%"',
    '"Pass"': '39',
    '"Rush"': '25',
    '"No Play (Penalty)"': '66',
  },
  {
    '"Team"': '"KC"',
    '"GMs"': '4',
    '"Plays"': '68',
    '"Sec/Snap"': '26',
    '"No-Huddle"': '"1%"',
    '"Pass%"': '"69%"',
    '"Rush%"': '"31%"',
    '"Pass"': '47',
    '"Rush"': '21',
    '"No Play (Penalty)"': '57',
  },
];

module.exports = rotovizNeutralScriptOffensivePaceAndRunPassReportLastFiveWeeks;
