const rotovizNegativeScriptOffensivePaceAndRunPassReportLastFiveWeeks = [
  {
    '"Team"': '"NYG"',
    '"GMs"': '3',
    '"Plays"': '73',
    '"Sec/Snap"': '30.6',
    '"No-Huddle"': '"4%"',
    '"Pass%"': '"55%"',
    '"Rush%"': '"45%"',
    '"Pass"': '40',
    '"Rush"': '33',
    '"No Play (Penalty)"': '44',
  },
  {
    '"Team"': '"GB"',
    '"GMs"': '5',
    '"Plays"': '57',
    '"Sec/Snap"': '26.4',
    '"No-Huddle"': '"7%"',
    '"Pass%"': '"64%"',
    '"Rush%"': '"36%"',
    '"Pass"': '37',
    '"Rush"': '21',
    '"No Play (Penalty)"': '23',
  },
  {
    '"Team"': '"PIT"',
    '"GMs"': '3',
    '"Plays"': '76',
    '"Sec/Snap"': '27.7',
    '"No-Huddle"': '"16%"',
    '"Pass%"': '"69%"',
    '"Rush%"': '"31%"',
    '"Pass"': '53',
    '"Rush"': '23',
    '"No Play (Penalty)"': '24',
  },
  {
    '"Team"': '"LAC"',
    '"GMs"': '4',
    '"Plays"': '80',
    '"Sec/Snap"': '24.1',
    '"No-Huddle"': '"9%"',
    '"Pass%"': '"75%"',
    '"Rush%"': '"25%"',
    '"Pass"': '60',
    '"Rush"': '20',
    '"No Play (Penalty)"': '39',
  },
  {
    '"Team"': '"JAC"',
    '"GMs"': '4',
    '"Plays"': '46',
    '"Sec/Snap"': '21.3',
    '"No-Huddle"': '"11%"',
    '"Pass%"': '"65%"',
    '"Rush%"': '"35%"',
    '"Pass"': '30',
    '"Rush"': '16',
    '"No Play (Penalty)"': '47',
  },
  {
    '"Team"': '"CHI"',
    '"GMs"': '3',
    '"Plays"': '64',
    '"Sec/Snap"': '27.7',
    '"No-Huddle"': '"6%"',
    '"Pass%"': '"45%"',
    '"Rush%"': '"55%"',
    '"Pass"': '29',
    '"Rush"': '35',
    '"No Play (Penalty)"': '27',
  },
  {
    '"Team"': '"DET"',
    '"GMs"': '2',
    '"Plays"': '31',
    '"Sec/Snap"': '19',
    '"No-Huddle"': '"11%"',
    '"Pass%"': '"83%"',
    '"Rush%"': '"17%"',
    '"Pass"': '26',
    '"Rush"': '5',
    '"No Play (Penalty)"': '38',
  },
  {
    '"Team"': '"NO"',
    '"GMs"': '3',
    '"Plays"': '33',
    '"Sec/Snap"': '22.4',
    '"No-Huddle"': '"24%"',
    '"Pass%"': '"73%"',
    '"Rush%"': '"27%"',
    '"Pass"': '25',
    '"Rush"': '9',
    '"No Play (Penalty)"': '20',
  },
  {
    '"Team"': '"SEA"',
    '"GMs"': '1',
    '"Plays"': '9',
    '"Sec/Snap"': '21.6',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"64%"',
    '"Rush%"': '"36%"',
    '"Pass"': '6',
    '"Rush"': '3',
    '"No Play (Penalty)"': '35',
  },
  {
    '"Team"': '"MIA"',
    '"GMs"': '3',
    '"Plays"': '55',
    '"Sec/Snap"': '26.7',
    '"No-Huddle"': '"3%"',
    '"Pass%"': '"72%"',
    '"Rush%"': '"28%"',
    '"Pass"': '40',
    '"Rush"': '15',
    '"No Play (Penalty)"': '29',
  },
  {
    '"Team"': '"ATL"',
    '"GMs"': '2',
    '"Plays"': '35',
    '"Sec/Snap"': '29.7',
    '"No-Huddle"': '"16%"',
    '"Pass%"': '"44%"',
    '"Rush%"': '"56%"',
    '"Pass"': '15',
    '"Rush"': '19',
    '"No Play (Penalty)"': '20',
  },
  {
    '"Team"': '"WAS"',
    '"GMs"': '4',
    '"Plays"': '75',
    '"Sec/Snap"': '29.5',
    '"No-Huddle"': '"6%"',
    '"Pass%"': '"55%"',
    '"Rush%"': '"45%"',
    '"Pass"': '41',
    '"Rush"': '33',
    '"No Play (Penalty)"': '63',
  },
  {
    '"Team"': '"CAR"',
    '"GMs"': '4',
    '"Plays"': '52',
    '"Sec/Snap"': '24.4',
    '"No-Huddle"': '"8%"',
    '"Pass%"': '"68%"',
    '"Rush%"': '"32%"',
    '"Pass"': '35',
    '"Rush"': '17',
    '"No Play (Penalty)"': '21',
  },
  {
    '"Team"': '"ARI"',
    '"GMs"': '5',
    '"Plays"': '82',
    '"Sec/Snap"': '22',
    '"No-Huddle"': '"38%"',
    '"Pass%"': '"68%"',
    '"Rush%"': '"32%"',
    '"Pass"': '56',
    '"Rush"': '26',
    '"No Play (Penalty)"': '27',
  },
  {
    '"Team"': '"LAR"',
    '"GMs"': '2',
    '"Plays"': '41',
    '"Sec/Snap"': '26.3',
    '"No-Huddle"': '"17%"',
    '"Pass%"': '"74%"',
    '"Rush%"': '"26%"',
    '"Pass"': '30',
    '"Rush"': '10',
    '"No Play (Penalty)"': '48',
  },
  {
    '"Team"': '"CIN"',
    '"GMs"': '3',
    '"Plays"': '26',
    '"Sec/Snap"': '27.3',
    '"No-Huddle"': '"5%"',
    '"Pass%"': '"74%"',
    '"Rush%"': '"26%"',
    '"Pass"': '19',
    '"Rush"': '7',
    '"No Play (Penalty)"': '19',
  },
  {
    '"Team"': '"KC"',
    '"GMs"': '4',
    '"Plays"': '57',
    '"Sec/Snap"': '28',
    '"No-Huddle"': '"1%"',
    '"Pass%"': '"75%"',
    '"Rush%"': '"25%"',
    '"Pass"': '43',
    '"Rush"': '14',
    '"No Play (Penalty)"': '38',
  },
  {
    '"Team"': '"LV"',
    '"GMs"': '4',
    '"Plays"': '34',
    '"Sec/Snap"': '25',
    '"No-Huddle"': '"8%"',
    '"Pass%"': '"71%"',
    '"Rush%"': '"29%"',
    '"Pass"': '24',
    '"Rush"': '10',
    '"No Play (Penalty)"': '29',
  },
  {
    '"Team"': '"SF"',
    '"GMs"': '3',
    '"Plays"': '47',
    '"Sec/Snap"': '25.2',
    '"No-Huddle"': '"13%"',
    '"Pass%"': '"73%"',
    '"Rush%"': '"27%"',
    '"Pass"': '34',
    '"Rush"': '13',
    '"No Play (Penalty)"': '22',
  },
  {
    '"Team"': '"CLE"',
    '"GMs"': '2',
    '"Plays"': '37',
    '"Sec/Snap"': '19.6',
    '"No-Huddle"': '"29%"',
    '"Pass%"': '"73%"',
    '"Rush%"': '"27%"',
    '"Pass"': '27',
    '"Rush"': '10',
    '"No Play (Penalty)"': '33',
  },
  {
    '"Team"': '"IND"',
    '"GMs"': '3',
    '"Plays"': '82',
    '"Sec/Snap"': '25.5',
    '"No-Huddle"': '"31%"',
    '"Pass%"': '"73%"',
    '"Rush%"': '"27%"',
    '"Pass"': '60',
    '"Rush"': '22',
    '"No Play (Penalty)"': '36',
  },
  {
    '"Team"': '"TB"',
    '"GMs"': '4',
    '"Plays"': '57',
    '"Sec/Snap"': '19.8',
    '"No-Huddle"': '"28%"',
    '"Pass%"': '"82%"',
    '"Rush%"': '"18%"',
    '"Pass"': '46',
    '"Rush"': '10',
    '"No Play (Penalty)"': '30',
  },
  {
    '"Team"': '"DAL"',
    '"GMs"': '1',
    '"Plays"': '29',
    '"Sec/Snap"': '21',
    '"No-Huddle"': '"25%"',
    '"Pass%"': '"63%"',
    '"Rush%"': '"37%"',
    '"Pass"': '18',
    '"Rush"': '11',
    '"No Play (Penalty)"': '28',
  },
  {
    '"Team"': '"BAL"',
    '"GMs"': '2',
    '"Plays"': '26',
    '"Sec/Snap"': '26.8',
    '"No-Huddle"': '"6%"',
    '"Pass%"': '"62%"',
    '"Rush%"': '"38%"',
    '"Pass"': '16',
    '"Rush"': '10',
    '"No Play (Penalty)"': '28',
  },
  {
    '"Team"': '"DEN"',
    '"GMs"': '2',
    '"Plays"': '74',
    '"Sec/Snap"': '24.3',
    '"No-Huddle"': '"15%"',
    '"Pass%"': '"60%"',
    '"Rush%"': '"40%"',
    '"Pass"': '44',
    '"Rush"': '30',
    '"No Play (Penalty)"': '88',
  },
  {
    '"Team"': '"HOU"',
    '"GMs"': '3',
    '"Plays"': '71',
    '"Sec/Snap"': '24.6',
    '"No-Huddle"': '"19%"',
    '"Pass%"': '"65%"',
    '"Rush%"': '"35%"',
    '"Pass"': '46',
    '"Rush"': '25',
    '"No Play (Penalty)"': '51',
  },
  {
    '"Team"': '"NE"',
    '"GMs"': '2',
    '"Plays"': '23',
    '"Sec/Snap"': '23.5',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"61%"',
    '"Rush%"': '"39%"',
    '"Pass"': '14',
    '"Rush"': '9',
    '"No Play (Penalty)"': '21',
  },
  {
    '"Team"': '"NYJ"',
    '"GMs"': '2',
    '"Plays"': '27',
    '"Sec/Snap"': '28',
    '"No-Huddle"': '"12%"',
    '"Pass%"': '"70%"',
    '"Rush%"': '"30%"',
    '"Pass"': '19',
    '"Rush"': '8',
    '"No Play (Penalty)"': '38',
  },
  {
    '"Team"': '"PHI"',
    '"GMs"': '1',
    '"Plays"': '7',
    '"Sec/Snap"': '26.5',
    '"No-Huddle"': '"28%"',
    '"Pass%"': '"72%"',
    '"Rush%"': '"28%"',
    '"Pass"': '5',
    '"Rush"': '2',
    '"No Play (Penalty)"': '22',
  },
  {
    '"Team"': '"MIN"',
    '"GMs"': '1',
    '"Plays"': '6',
    '"Sec/Snap"': '20.9',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"90%"',
    '"Rush%"': '"10%"',
    '"Pass"': '5',
    '"Rush"': '1',
    '"No Play (Penalty)"': '33',
  },
  {
    '"Team"': '"TEN"',
    '"GMs"': '1',
    '"Plays"': '5',
    '"Sec/Snap"': '34.3',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"29%"',
    '"Rush%"': '"71%"',
    '"Pass"': '1',
    '"Rush"': '4',
    '"No Play (Penalty)"': '41',
  },
];

module.exports =
  rotovizNegativeScriptOffensivePaceAndRunPassReportLastFiveWeeks;
