const allNFLTeamPace = [
  {
    '"Home"': '"GB"',
    '"Away"': '"TEN"',
    '"Time"': '"THU 8:15 AM"',
    '"Sec_ALL_nt_h"': '27.9',
    '"Sec_ALL_nt_v"': '28.7',
    '"Sec_ALL_nt_avg"': '28.3',
    '"Plays_ALL_nt_h"': '64',
    '"Plays_ALL_nt_v"': '62',
    '"Plays_ALL_nt_avg"': '63',
    '"Sec_ALL_h"': '26',
    '"Sec_ALL_v"': '26.6',
    '"Sec_ALL_avg"': '26.3',
    '"Plays_ALL_h"': '70',
    '"Plays_ALL_v"': '63',
    '"PLays_ALL_avg"': '66.5',
  },
  {
    '"Home"': '"ATL"',
    '"Away"': '"CHI"',
    '"Time"': '"SUN 1:00 AM"',
    '"Sec_ALL_nt_h"': '28.1',
    '"Sec_ALL_nt_v"': '27.7',
    '"Sec_ALL_nt_avg"': '27.9',
    '"Plays_ALL_nt_h"': '66',
    '"Plays_ALL_nt_v"': '59',
    '"Plays_ALL_nt_avg"': '62.5',
    '"Sec_ALL_h"': '26.6',
    '"Sec_ALL_v"': '25.6',
    '"Sec_ALL_avg"': '26.1',
    '"Plays_ALL_h"': '65',
    '"Plays_ALL_v"': '69',
    '"PLays_ALL_avg"': '67',
  },
  {
    '"Home"': '"BAL"',
    '"Away"': '"CAR"',
    '"Time"': '"SUN 1:00 AM"',
    '"Sec_ALL_nt_h"': '29.1',
    '"Sec_ALL_nt_v"': '25.2',
    '"Sec_ALL_nt_avg"': '27.1',
    '"Plays_ALL_nt_h"': '72',
    '"Plays_ALL_nt_v"': '55',
    '"Plays_ALL_nt_avg"': '63.5',
    '"Sec_ALL_h"': '27',
    '"Sec_ALL_v"': '24.3',
    '"Sec_ALL_avg"': '25.6',
    '"Plays_ALL_h"': '70',
    '"Plays_ALL_v"': '62',
    '"PLays_ALL_avg"': '66',
  },
  {
    '"Home"': '"BUF"',
    '"Away"': '"CLE"',
    '"Time"': '"SUN 1:00 AM"',
    '"Sec_ALL_nt_h"': '25.9',
    '"Sec_ALL_nt_v"': '27.1',
    '"Sec_ALL_nt_avg"': '26.5',
    '"Plays_ALL_nt_h"': '76',
    '"Plays_ALL_nt_v"': '68',
    '"Plays_ALL_nt_avg"': '72',
    '"Sec_ALL_h"': '23.8',
    '"Sec_ALL_v"': '24.7',
    '"Sec_ALL_avg"': '24.2',
    '"Plays_ALL_h"': '72',
    '"Plays_ALL_v"': '76',
    '"PLays_ALL_avg"': '74',
  },
  {
    '"Home"': '"HOU"',
    '"Away"': '"WAS"',
    '"Time"': '"SUN 1:00 AM"',
    '"Sec_ALL_nt_h"': '27.5',
    '"Sec_ALL_nt_v"': '27.6',
    '"Sec_ALL_nt_avg"': '27.6',
    '"Plays_ALL_nt_h"': '57',
    '"Plays_ALL_nt_v"': '67',
    '"Plays_ALL_nt_avg"': '62',
    '"Sec_ALL_h"': '25.1',
    '"Sec_ALL_v"': '25.1',
    '"Sec_ALL_avg"': '25.1',
    '"Plays_ALL_h"': '65',
    '"Plays_ALL_v"': '75',
    '"PLays_ALL_avg"': '70',
  },
  {
    '"Home"': '"IND"',
    '"Away"': '"PHI"',
    '"Time"': '"SUN 1:00 AM"',
    '"Sec_ALL_nt_h"': '26.1',
    '"Sec_ALL_nt_v"': '26.5',
    '"Sec_ALL_nt_avg"': '26.3',
    '"Plays_ALL_nt_h"': '65',
    '"Plays_ALL_nt_v"': '73',
    '"Plays_ALL_nt_avg"': '69',
    '"Sec_ALL_h"': '23.9',
    '"Sec_ALL_v"': '24.5',
    '"Sec_ALL_avg"': '24.2',
    '"Plays_ALL_h"': '72',
    '"Plays_ALL_v"': '73',
    '"PLays_ALL_avg"': '72.5',
  },
  {
    '"Home"': '"NE"',
    '"Away"': '"NYJ"',
    '"Time"': '"SUN 1:00 AM"',
    '"Sec_ALL_nt_h"': '27.9',
    '"Sec_ALL_nt_v"': '26.4',
    '"Sec_ALL_nt_avg"': '27.1',
    '"Plays_ALL_nt_h"': '64',
    '"Plays_ALL_nt_v"': '61',
    '"Plays_ALL_nt_avg"': '62.5',
    '"Sec_ALL_h"': '25.9',
    '"Sec_ALL_v"': '23.9',
    '"Sec_ALL_avg"': '24.9',
    '"Plays_ALL_h"': '69',
    '"Plays_ALL_v"': '71',
    '"PLays_ALL_avg"': '70',
  },
  {
    '"Home"': '"NO"',
    '"Away"': '"LAR"',
    '"Time"': '"SUN 1:00 AM"',
    '"Sec_ALL_nt_h"': '26.9',
    '"Sec_ALL_nt_v"': '29.4',
    '"Sec_ALL_nt_avg"': '28.1',
    '"Plays_ALL_nt_h"': '62',
    '"Plays_ALL_nt_v"': '56',
    '"Plays_ALL_nt_avg"': '59',
    '"Sec_ALL_h"': '24.1',
    '"Sec_ALL_v"': '26.3',
    '"Sec_ALL_avg"': '25.2',
    '"Plays_ALL_h"': '70',
    '"Plays_ALL_v"': '67',
    '"PLays_ALL_avg"': '68.5',
  },
  {
    '"Home"': '"NYG"',
    '"Away"': '"DET"',
    '"Time"': '"SUN 1:00 AM"',
    '"Sec_ALL_nt_h"': '27.1',
    '"Sec_ALL_nt_v"': '26.5',
    '"Sec_ALL_nt_avg"': '26.8',
    '"Plays_ALL_nt_h"': '67',
    '"Plays_ALL_nt_v"': '67',
    '"Plays_ALL_nt_avg"': '67',
    '"Sec_ALL_h"': '25.3',
    '"Sec_ALL_v"': '23.8',
    '"Sec_ALL_avg"': '24.6',
    '"Plays_ALL_h"': '73',
    '"Plays_ALL_v"': '71',
    '"PLays_ALL_avg"': '72',
  },
  {
    '"Home"': '"DEN"',
    '"Away"': '"LV"',
    '"Time"': '"SUN 4:05 AM"',
    '"Sec_ALL_nt_h"': '25.5',
    '"Sec_ALL_nt_v"': '26.4',
    '"Sec_ALL_nt_avg"': '25.9',
    '"Plays_ALL_nt_h"': '69',
    '"Plays_ALL_nt_v"': '64',
    '"Plays_ALL_nt_avg"': '66.5',
    '"Sec_ALL_h"': '23.8',
    '"Sec_ALL_v"': '24.5',
    '"Sec_ALL_avg"': '24.1',
    '"Plays_ALL_h"': '73',
    '"Plays_ALL_v"': '69',
    '"PLays_ALL_avg"': '71',
  },
  {
    '"Home"': '"MIN"',
    '"Away"': '"DAL"',
    '"Time"': '"SUN 4:25 AM"',
    '"Sec_ALL_nt_h"': '25.2',
    '"Sec_ALL_nt_v"': '25.7',
    '"Sec_ALL_nt_avg"': '25.4',
    '"Plays_ALL_nt_h"': '66',
    '"Plays_ALL_nt_v"': '69',
    '"Plays_ALL_nt_avg"': '67.5',
    '"Sec_ALL_h"': '22.9',
    '"Sec_ALL_v"': '23.4',
    '"Sec_ALL_avg"': '23.1',
    '"Plays_ALL_h"': '74',
    '"Plays_ALL_v"': '68',
    '"PLays_ALL_avg"': '71',
  },
  {
    '"Home"': '"PIT"',
    '"Away"': '"CIN"',
    '"Time"': '"SUN 4:25 AM"',
    '"Sec_ALL_nt_h"': '25.6',
    '"Sec_ALL_nt_v"': '25.9',
    '"Sec_ALL_nt_avg"': '25.8',
    '"Plays_ALL_nt_h"': '68',
    '"Plays_ALL_nt_v"': '69',
    '"Plays_ALL_nt_avg"': '68.5',
    '"Sec_ALL_h"': '24',
    '"Sec_ALL_v"': '25.5',
    '"Sec_ALL_avg"': '24.8',
    '"Plays_ALL_h"': '74',
    '"Plays_ALL_v"': '74',
    '"PLays_ALL_avg"': '74',
  },
  {
    '"Home"': '"LAC"',
    '"Away"': '"KC"',
    '"Time"': '"SUN 8:20 AM"',
    '"Sec_ALL_nt_h"': '24.1',
    '"Sec_ALL_nt_v"': '26',
    '"Sec_ALL_nt_avg"': '25.1',
    '"Plays_ALL_nt_h"': '68',
    '"Plays_ALL_nt_v"': '67',
    '"Plays_ALL_nt_avg"': '67.5',
    '"Sec_ALL_h"': '22.5',
    '"Sec_ALL_v"': '24.7',
    '"Sec_ALL_avg"': '23.6',
    '"Plays_ALL_h"': '75',
    '"Plays_ALL_v"': '73',
    '"PLays_ALL_avg"': '74',
  },
  {
    '"Home"': '"ARI"',
    '"Away"': '"SF"',
    '"Time"': '"MON 8:15 AM"',
    '"Sec_ALL_nt_h"': '26.9',
    '"Sec_ALL_nt_v"': '29',
    '"Sec_ALL_nt_avg"': '27.9',
    '"Plays_ALL_nt_h"': '58',
    '"Plays_ALL_nt_v"': '62',
    '"Plays_ALL_nt_avg"': '60',
    '"Sec_ALL_h"': '22.9',
    '"Sec_ALL_v"': '25.5',
    '"Sec_ALL_avg"': '24.2',
    '"Plays_ALL_h"': '78',
    '"Plays_ALL_v"': '71',
    '"PLays_ALL_avg"': '74.5',
  },
];

module.exports = allNFLTeamPace;
