const qbRushingLastFiveGamesFromWeeklyStatExplorer = [
  {
    '"Player"': '"Aaron Rodgers"',
    '"Team"': '"GB"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '6',
    '"Yards"': '7',
    '"TD"': '0',
    '"YPC"': '1.2',
    '"% Tm Att"': '"5%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Andy Dalton"',
    '"Team"': '"NO"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '10',
    '"Yards"': '21',
    '"TD"': '0',
    '"YPC"': '2.1',
    '"% Tm Att"': '"12%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Anthony Brown"',
    '"Team"': '"BAL"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '3',
    '"Yards"': '-5',
    '"TD"': '0',
    '"YPC"': '-1.7',
    '"% Tm Att"': '"7%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Baker Mayfield"',
    '"Team"': '"LAR"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '6',
    '"Yards"': '22',
    '"TD"': '0',
    '"YPC"': '3.7',
    '"% Tm Att"': '"15%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Brett Rypien"',
    '"Team"': '"DEN"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '1',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': '0',
    '"% Tm Att"': '"5%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Brock Purdy"',
    '"Team"': '"SF"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Att"': '9',
    '"Yards"': '5',
    '"TD"': '1',
    '"YPC"': '0.6',
    '"% Tm Att"': '"9%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Bryce Perkins"',
    '"Team"': '"LAR"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '18',
    '"Yards"': '92',
    '"TD"': '0',
    '"YPC"': '5.1',
    '"% Tm Att"': '"16%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"CJ Beathard"',
    '"Team"': '"JAC"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '0',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': 'NA',
    '"% Tm Att"': '"0%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Chase Daniel"',
    '"Team"': '"LAC"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '0',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': 'NA',
    '"% Tm Att"': '"0%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Colt McCoy"',
    '"Team"': '"ARI"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Att"': '12',
    '"Yards"': '34',
    '"TD"': '0',
    '"YPC"': '2.8',
    '"% Tm Att"': '"17%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Cooper Rush"',
    '"Team"': '"DAL"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '0',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': 'NA',
    '"% Tm Att"': '"0%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Dak Prescott"',
    '"Team"': '"DAL"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '14',
    '"Yards"': '48',
    '"TD"': '0',
    '"YPC"': '3.4',
    '"% Tm Att"': '"8%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Daniel Jones"',
    '"Team"': '"NYG"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '31',
    '"Yards"': '185',
    '"TD"': '2',
    '"YPC"': '6',
    '"% Tm Att"': '"21%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Davis Mills"',
    '"Team"': '"HOU"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Att"': '6',
    '"Yards"': '12',
    '"TD"': '1',
    '"YPC"': '2',
    '"% Tm Att"': '"8%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Derek Carr"',
    '"Team"': '"LV"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '6',
    '"Yards"': '21',
    '"TD"': '0',
    '"YPC"': '3.5',
    '"% Tm Att"': '"4%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Deshaun Watson"',
    '"Team"': '"CLE"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '13',
    '"Yards"': '54',
    '"TD"': '0',
    '"YPC"': '4.2',
    '"% Tm Att"': '"21%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Gardner Minshew"',
    '"Team"': '"PHI"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '1',
    '"Yards"': '-1',
    '"TD"': '0',
    '"YPC"': '-1',
    '"% Tm Att"': '"2%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Geno Smith"',
    '"Team"': '"SEA"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '14',
    '"Yards"': '67',
    '"TD"': '0',
    '"YPC"': '4.8',
    '"% Tm Att"': '"19%"',
    '"FumL"': '3',
  },
  {
    '"Player"': '"Jacoby Brissett"',
    '"Team"': '"CLE"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '16',
    '"Yards"': '96',
    '"TD"': '0',
    '"YPC"': '6',
    '"% Tm Att"': '"11%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Jalen Hurts"',
    '"Team"': '"PHI"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '51',
    '"Yards"': '360',
    '"TD"': '4',
    '"YPC"': '7.1',
    '"% Tm Att"': '"32%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Jared Goff"',
    '"Team"': '"DET"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '10',
    '"Yards"': '22',
    '"TD"': '0',
    '"YPC"': '2.2',
    '"% Tm Att"': '"6%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Jarrett Stidham"',
    '"Team"': '"LV"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '0',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': 'NA',
    '"% Tm Att"': '"0%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Jeff Driskel"',
    '"Team"': '"HOU"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '7',
    '"Yards"': '36',
    '"TD"': '0',
    '"YPC"': '5.1',
    '"% Tm Att"': '"19%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Jimmy Garoppolo"',
    '"Team"': '"SF"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '10',
    '"Yards"': '10',
    '"TD"': '1',
    '"YPC"': '1',
    '"% Tm Att"': '"8%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Joe Burrow"',
    '"Team"': '"CIN"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '30',
    '"Yards"': '93',
    '"TD"': '1',
    '"YPC"': '3.1',
    '"% Tm Att"': '"27%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Joe Flacco"',
    '"Team"': '"NYJ"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '0',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': 'NA',
    '"% Tm Att"': '"0%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"John Wolford"',
    '"Team"': '"LAR"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Att"': '8',
    '"Yards"': '32',
    '"TD"': '0',
    '"YPC"': '4',
    '"% Tm Att"': '"11%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Jordan Love"',
    '"Team"': '"GB"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '0',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': 'NA',
    '"% Tm Att"': '"0%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Josh Allen"',
    '"Team"': '"BUF"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '37',
    '"Yards"': '236',
    '"TD"': '2',
    '"YPC"': '6.4',
    '"% Tm Att"': '"25%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Josh Johnson"',
    '"Team"': '"SF"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '2',
    '"Yards"': '3',
    '"TD"': '0',
    '"YPC"': '1.5',
    '"% Tm Att"': '"6%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Justin Fields"',
    '"Team"': '"CHI"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Att"': '37',
    '"Yards"': '303',
    '"TD"': '4',
    '"YPC"': '8.2',
    '"% Tm Att"': '"37%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Justin Herbert"',
    '"Team"': '"LAC"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '23',
    '"Yards"': '92',
    '"TD"': '0',
    '"YPC"': '4',
    '"% Tm Att"': '"22%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Kenny Pickett"',
    '"Team"': '"PIT"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '25',
    '"Yards"': '127',
    '"TD"': '1',
    '"YPC"': '5.1',
    '"% Tm Att"': '"16%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Kirk Cousins"',
    '"Team"': '"MIN"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '10',
    '"Yards"': '20',
    '"TD"': '0',
    '"YPC"': '2',
    '"% Tm Att"': '"9%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Kyle Allen"',
    '"Team"': '"HOU"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '6',
    '"Yards"': '13',
    '"TD"': '0',
    '"YPC"': '2.2',
    '"% Tm Att"': '"17%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Kyler Murray"',
    '"Team"': '"ARI"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '8',
    '"Yards"': '59',
    '"TD"': '1',
    '"YPC"': '7.4',
    '"% Tm Att"': '"14%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Lamar Jackson"',
    '"Team"': '"BAL"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Att"': '26',
    '"Yards"': '129',
    '"TD"': '1',
    '"YPC"': '5',
    '"% Tm Att"': '"28%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Mac Jones"',
    '"Team"': '"NE"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '10',
    '"Yards"': '9',
    '"TD"': '0',
    '"YPC"': '0.9',
    '"% Tm Att"': '"14%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Malik Willis"',
    '"Team"': '"TEN"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '2',
    '"Yards"': '4',
    '"TD"': '0',
    '"YPC"': '2',
    '"% Tm Att"': '"5%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Marcus Mariota"',
    '"Team"': '"ATL"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '25',
    '"Yards"': '134',
    '"TD"': '1',
    '"YPC"': '5.4',
    '"% Tm Att"': '"22%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Matt Ryan"',
    '"Team"': '"IND"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '12',
    '"Yards"': '59',
    '"TD"': '1',
    '"YPC"': '4.9',
    '"% Tm Att"': '"11%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Matthew Stafford"',
    '"Team"': '"LAR"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '1',
    '"Yards"': '4',
    '"TD"': '0',
    '"YPC"': '4',
    '"% Tm Att"': '"3%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Mike White"',
    '"Team"': '"NYJ"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Att"': '6',
    '"Yards"': '9',
    '"TD"': '1',
    '"YPC"': '1.5',
    '"% Tm Att"': '"8%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Mitchell Trubisky"',
    '"Team"': '"PIT"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '0',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': 'NA',
    '"% Tm Att"': '"0%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Nate Sudfeld"',
    '"Team"': '"DET"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '2',
    '"Yards"': '-1',
    '"TD"': '0',
    '"YPC"': '-0.5',
    '"% Tm Att"': '"7%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Nick Mullens"',
    '"Team"': '"MIN"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '0',
    '"Yards"': '0',
    '"TD"': '0',
    '"YPC"': 'NA',
    '"% Tm Att"': '"0%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Patrick Mahomes"',
    '"Team"': '"KC"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '20',
    '"Yards"': '104',
    '"TD"': '1',
    '"YPC"': '5.2',
    '"% Tm Att"': '"15%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Phillip Walker"',
    '"Team"': '"CAR"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '3',
    '"Yards"': '14',
    '"TD"': '0',
    '"YPC"': '4.7',
    '"% Tm Att"': '"6%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Russell Wilson"',
    '"Team"': '"DEN"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '16',
    '"Yards"': '102',
    '"TD"': '0',
    '"YPC"': '6.4',
    '"% Tm Att"': '"13%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Ryan Tannehill"',
    '"Team"': '"TEN"',
    '"Pos"': '"QB"',
    '"GMs"': '5',
    '"Att"': '12',
    '"Yards"': '68',
    '"TD"': '0',
    '"YPC"': '5.7',
    '"% Tm Att"': '"10%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Sam Darnold"',
    '"Team"': '"CAR"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '7',
    '"Yards"': '33',
    '"TD"': '1',
    '"YPC"': '4.7',
    '"% Tm Att"': '"8%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Skylar Thompson"',
    '"Team"': '"MIA"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Att"': '9',
    '"Yards"': '5',
    '"TD"': '0',
    '"YPC"': '0.6',
    '"% Tm Att"': '"13%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Taylor Heinicke"',
    '"Team"': '"WAS"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '11',
    '"Yards"': '17',
    '"TD"': '0',
    '"YPC"': '1.5',
    '"% Tm Att"': '"7%"',
    '"FumL"': '2',
  },
  {
    '"Player"': '"Tom Brady"',
    '"Team"': '"TB"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '10',
    '"Yards"': '-2',
    '"TD"': '0',
    '"YPC"': '-0.2',
    '"% Tm Att"': '"10%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Trace McSorley"',
    '"Team"': '"ARI"',
    '"Pos"': '"QB"',
    '"GMs"': '2',
    '"Att"': '1',
    '"Yards"': '6',
    '"TD"': '0',
    '"YPC"': '6',
    '"% Tm Att"': '"2%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Trevor Lawrence"',
    '"Team"': '"JAC"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '13',
    '"Yards"': '66',
    '"TD"': '1',
    '"YPC"': '5.1',
    '"% Tm Att"': '"16%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Trevor Siemian"',
    '"Team"': '"CHI"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '4',
    '"Yards"': '8',
    '"TD"': '0',
    '"YPC"': '2',
    '"% Tm Att"': '"14%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Tua Tagovailoa"',
    '"Team"': '"MIA"',
    '"Pos"': '"QB"',
    '"GMs"': '4',
    '"Att"': '4',
    '"Yards"': '28',
    '"TD"': '0',
    '"YPC"': '7',
    '"% Tm Att"': '"5%"',
    '"FumL"': '1',
  },
  {
    '"Player"': '"Tyler Huntley"',
    '"Team"': '"BAL"',
    '"Pos"': '"QB"',
    '"GMs"': '3',
    '"Att"': '19',
    '"Yards"': '72',
    '"TD"': '1',
    '"YPC"': '3.8',
    '"% Tm Att"': '"18%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Tyrod Taylor"',
    '"Team"': '"NYG"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '2',
    '"Yards"': '40',
    '"TD"': '0',
    '"YPC"': '20',
    '"% Tm Att"': '"9%"',
    '"FumL"': '0',
  },
  {
    '"Player"': '"Zach Wilson"',
    '"Team"': '"NYJ"',
    '"Pos"': '"QB"',
    '"GMs"': '1',
    '"Att"': '3',
    '"Yards"': '26',
    '"TD"': '0',
    '"YPC"': '8.7',
    '"% Tm Att"': '"13%"',
    '"FumL"': '0',
  },
];

module.exports = qbRushingLastFiveGamesFromWeeklyStatExplorer;
