const rotovizPositiveScriptOffensivePaceAndRunPassReportLastFiveWeeks = [
  {
    '"Team"': '"CAR"',
    '"GMs"': '3',
    '"Plays"': '60',
    '"Sec/Snap"': '29.9',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"24%"',
    '"Rush%"': '"76%"',
    '"Pass"': '14',
    '"Rush"': '46',
    '"No Play (Penalty)"': '20',
  },
  {
    '"Team"': '"TB"',
    '"GMs"': '2',
    '"Plays"': '23',
    '"Sec/Snap"': '29.5',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"50%"',
    '"Rush%"': '"50%"',
    '"Pass"': '12',
    '"Rush"': '12',
    '"No Play (Penalty)"': '13',
  },
  {
    '"Team"': '"BUF"',
    '"GMs"': '4',
    '"Plays"': '47',
    '"Sec/Snap"': '29.5',
    '"No-Huddle"': '"6%"',
    '"Pass%"': '"44%"',
    '"Rush%"': '"56%"',
    '"Pass"': '21',
    '"Rush"': '26',
    '"No Play (Penalty)"': '13',
  },
  {
    '"Team"': '"CHI"',
    '"GMs"': '3',
    '"Plays"': '11',
    '"Sec/Snap"': '23.8',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"44%"',
    '"Rush%"': '"56%"',
    '"Pass"': '5',
    '"Rush"': '6',
    '"No Play (Penalty)"': '23',
  },
  {
    '"Team"': '"KC"',
    '"GMs"': '3',
    '"Plays"': '43',
    '"Sec/Snap"': '27.3',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"52%"',
    '"Rush%"': '"48%"',
    '"Pass"': '23',
    '"Rush"': '21',
    '"No Play (Penalty)"': '14',
  },
  {
    '"Team"': '"MIA"',
    '"GMs"': '2',
    '"Plays"': '45',
    '"Sec/Snap"': '28.1',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"52%"',
    '"Rush%"': '"48%"',
    '"Pass"': '24',
    '"Rush"': '21',
    '"No Play (Penalty)"': '17',
  },
  {
    '"Team"': '"NYG"',
    '"GMs"': '2',
    '"Plays"': '14',
    '"Sec/Snap"': '30.5',
    '"No-Huddle"': '"16%"',
    '"Pass%"': '"32%"',
    '"Rush%"': '"68%"',
    '"Pass"': '4',
    '"Rush"': '9',
    '"No Play (Penalty)"': '12',
  },
  {
    '"Team"': '"PIT"',
    '"GMs"': '3',
    '"Plays"': '50',
    '"Sec/Snap"': '29.3',
    '"No-Huddle"': '"4%"',
    '"Pass%"': '"37%"',
    '"Rush%"': '"63%"',
    '"Pass"': '19',
    '"Rush"': '32',
    '"No Play (Penalty)"': '25',
  },
  {
    '"Team"': '"DEN"',
    '"GMs"': '2',
    '"Plays"': '13',
    '"Sec/Snap"': '22.9',
    '"No-Huddle"': '"11%"',
    '"Pass%"': '"50%"',
    '"Rush%"': '"50%"',
    '"Pass"': '7',
    '"Rush"': '7',
    '"No Play (Penalty)"': '24',
  },
  {
    '"Team"': '"TEN"',
    '"GMs"': '4',
    '"Plays"': '13',
    '"Sec/Snap"': '27.9',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"44%"',
    '"Rush%"': '"56%"',
    '"Pass"': '6',
    '"Rush"': '7',
    '"No Play (Penalty)"': '14',
  },
  {
    '"Team"': '"IND"',
    '"GMs"': '2',
    '"Plays"': '24',
    '"Sec/Snap"': '28.8',
    '"No-Huddle"': '"3%"',
    '"Pass%"': '"61%"',
    '"Rush%"': '"39%"',
    '"Pass"': '14',
    '"Rush"': '9',
    '"No Play (Penalty)"': '21',
  },
  {
    '"Team"': '"DAL"',
    '"GMs"': '4',
    '"Plays"': '53',
    '"Sec/Snap"': '29.5',
    '"No-Huddle"': '"5%"',
    '"Pass%"': '"39%"',
    '"Rush%"': '"61%"',
    '"Pass"': '21',
    '"Rush"': '32',
    '"No Play (Penalty)"': '17',
  },
  {
    '"Team"': '"ARI"',
    '"GMs"': '2',
    '"Plays"': '26',
    '"Sec/Snap"': '27.3',
    '"No-Huddle"': '"11%"',
    '"Pass%"': '"46%"',
    '"Rush%"': '"54%"',
    '"Pass"': '12',
    '"Rush"': '14',
    '"No Play (Penalty)"': '19',
  },
  {
    '"Team"': '"LAC"',
    '"GMs"': '4',
    '"Plays"': '23',
    '"Sec/Snap"': '30',
    '"No-Huddle"': '"3%"',
    '"Pass%"': '"74%"',
    '"Rush%"': '"26%"',
    '"Pass"': '17',
    '"Rush"': '6',
    '"No Play (Penalty)"': '20',
  },
  {
    '"Team"': '"BAL"',
    '"GMs"': '3',
    '"Plays"': '34',
    '"Sec/Snap"': '17.7',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"18%"',
    '"Rush%"': '"82%"',
    '"Pass"': '6',
    '"Rush"': '28',
    '"No Play (Penalty)"': '102',
  },
  {
    '"Team"': '"CLE"',
    '"GMs"': '2',
    '"Plays"': '9',
    '"Sec/Snap"': '29.5',
    '"No-Huddle"': '"23%"',
    '"Pass%"': '"27%"',
    '"Rush%"': '"73%"',
    '"Pass"': '2',
    '"Rush"': '6',
    '"No Play (Penalty)"': '13',
  },
  {
    '"Team"': '"WAS"',
    '"GMs"': '2',
    '"Plays"': '34',
    '"Sec/Snap"': '32.3',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"37%"',
    '"Rush%"': '"63%"',
    '"Pass"': '13',
    '"Rush"': '22',
    '"No Play (Penalty)"': '18',
  },
  {
    '"Team"': '"NO"',
    '"GMs"': '2',
    '"Plays"': '26',
    '"Sec/Snap"': '33.7',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"52%"',
    '"Rush%"': '"48%"',
    '"Pass"': '14',
    '"Rush"': '13',
    '"No Play (Penalty)"': '19',
  },
  {
    '"Team"': '"DET"',
    '"GMs"': '3',
    '"Plays"': '53',
    '"Sec/Snap"': '29.9',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"48%"',
    '"Rush%"': '"52%"',
    '"Pass"': '25',
    '"Rush"': '27',
    '"No Play (Penalty)"': '13',
  },
  {
    '"Team"': '"CIN"',
    '"GMs"': '3',
    '"Plays"': '28',
    '"Sec/Snap"': '25.1',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"48%"',
    '"Rush%"': '"52%"',
    '"Pass"': '13',
    '"Rush"': '15',
    '"No Play (Penalty)"': '23',
  },
  {
    '"Team"': '"SF"',
    '"GMs"': '4',
    '"Plays"': '49',
    '"Sec/Snap"': '32.9',
    '"No-Huddle"': '"1%"',
    '"Pass%"': '"36%"',
    '"Rush%"': '"64%"',
    '"Pass"': '18',
    '"Rush"': '31',
    '"No Play (Penalty)"': '12',
  },
  {
    '"Team"': '"MIN"',
    '"GMs"': '2',
    '"Plays"': '12',
    '"Sec/Snap"': '28.5',
    '"No-Huddle"': '"6%"',
    '"Pass%"': '"55%"',
    '"Rush%"': '"45%"',
    '"Pass"': '6',
    '"Rush"': '5',
    '"No Play (Penalty)"': '12',
  },
  {
    '"Team"': '"NYJ"',
    '"GMs"': '1',
    '"Plays"': '18',
    '"Sec/Snap"': '31.2',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"29%"',
    '"Rush%"': '"71%"',
    '"Pass"': '5',
    '"Rush"': '13',
    '"No Play (Penalty)"': '22',
  },
  {
    '"Team"': '"LV"',
    '"GMs"': '3',
    '"Plays"': '30',
    '"Sec/Snap"': '32.6',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"36%"',
    '"Rush%"': '"64%"',
    '"Pass"': '11',
    '"Rush"': '19',
    '"No Play (Penalty)"': '15',
  },
  {
    '"Team"': '"PHI"',
    '"GMs"': '3',
    '"Plays"': '43',
    '"Sec/Snap"': '28.9',
    '"No-Huddle"': '"10%"',
    '"Pass%"': '"44%"',
    '"Rush%"': '"56%"',
    '"Pass"': '19',
    '"Rush"': '24',
    '"No Play (Penalty)"': '11',
  },
  {
    '"Team"': '"GB"',
    '"GMs"': '1',
    '"Plays"': '2',
    '"Sec/Snap"': '17.7',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"0%"',
    '"Rush%"': '"100%"',
    '"Pass"': '0',
    '"Rush"': '2',
    '"No Play (Penalty)"': '17',
  },
  {
    '"Team"': '"JAC"',
    '"GMs"': '1',
    '"Plays"': '11',
    '"Sec/Snap"': '26.5',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"48%"',
    '"Rush%"': '"52%"',
    '"Pass"': '5',
    '"Rush"': '6',
    '"No Play (Penalty)"': '14',
  },
  {
    '"Team"': '"NE"',
    '"GMs"': '1',
    '"Plays"': '15',
    '"Sec/Snap"': '29.1',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"56%"',
    '"Rush%"': '"44%"',
    '"Pass"': '8',
    '"Rush"': '6',
    '"No Play (Penalty)"': '30',
  },
];

module.exports =
  rotovizPositiveScriptOffensivePaceAndRunPassReportLastFiveWeeks;
