const rotovizNeutralScriptOffensivePaceAndRunPassReportLastFiveWeeks = [
  {
    '"Team"': '"ATL"',
    '"GMs"': '4',
    '"Plays"': '48',
    '"Sec/Snap"': '29.1',
    '"No-Huddle"': '"16%"',
    '"Pass%"': '"42%"',
    '"Rush%"': '"58%"',
    '"Pass"': '20',
    '"Rush"': '28',
    '"No Play (Penalty)"': '42',
  },
  {
    '"Team"': '"CAR"',
    '"GMs"': '4',
    '"Plays"': '64',
    '"Sec/Snap"': '32.4',
    '"No-Huddle"': '"1%"',
    '"Pass%"': '"41%"',
    '"Rush%"': '"59%"',
    '"Pass"': '26',
    '"Rush"': '38',
    '"No Play (Penalty)"': '54',
  },
  {
    '"Team"': '"TB"',
    '"GMs"': '4',
    '"Plays"': '67',
    '"Sec/Snap"': '26.4',
    '"No-Huddle"': '"7%"',
    '"Pass%"': '"62%"',
    '"Rush%"': '"38%"',
    '"Pass"': '41',
    '"Rush"': '26',
    '"No Play (Penalty)"': '52',
  },
  {
    '"Team"': '"SEA"',
    '"GMs"': '4',
    '"Plays"': '51',
    '"Sec/Snap"': '26.7',
    '"No-Huddle"': '"19%"',
    '"Pass%"': '"67%"',
    '"Rush%"': '"33%"',
    '"Pass"': '34',
    '"Rush"': '17',
    '"No Play (Penalty)"': '44',
  },
  {
    '"Team"': '"BUF"',
    '"GMs"': '5',
    '"Plays"': '65',
    '"Sec/Snap"': '27.1',
    '"No-Huddle"': '"9%"',
    '"Pass%"': '"57%"',
    '"Rush%"': '"43%"',
    '"Pass"': '37',
    '"Rush"': '28',
    '"No Play (Penalty)"': '40',
  },
  {
    '"Team"': '"MIN"',
    '"GMs"': '5',
    '"Plays"': '65',
    '"Sec/Snap"': '27.8',
    '"No-Huddle"': '"8%"',
    '"Pass%"': '"61%"',
    '"Rush%"': '"39%"',
    '"Pass"': '40',
    '"Rush"': '25',
    '"No Play (Penalty)"': '42',
  },
  {
    '"Team"': '"CHI"',
    '"GMs"': '4',
    '"Plays"': '60',
    '"Sec/Snap"': '31.4',
    '"No-Huddle"': '"1%"',
    '"Pass%"': '"43%"',
    '"Rush%"': '"57%"',
    '"Pass"': '26',
    '"Rush"': '35',
    '"No Play (Penalty)"': '43',
  },
  {
    '"Team"': '"DET"',
    '"GMs"': '5',
    '"Plays"': '63',
    '"Sec/Snap"': '27.1',
    '"No-Huddle"': '"5%"',
    '"Pass%"': '"55%"',
    '"Rush%"': '"45%"',
    '"Pass"': '35',
    '"Rush"': '29',
    '"No Play (Penalty)"': '43',
  },
  {
    '"Team"': '"JAC"',
    '"GMs"': '4',
    '"Plays"': '58',
    '"Sec/Snap"': '26.7',
    '"No-Huddle"': '"11%"',
    '"Pass%"': '"66%"',
    '"Rush%"': '"34%"',
    '"Pass"': '38',
    '"Rush"': '20',
    '"No Play (Penalty)"': '69',
  },
  {
    '"Team"': '"KC"',
    '"GMs"': '5',
    '"Plays"': '61',
    '"Sec/Snap"': '27',
    '"No-Huddle"': '"1%"',
    '"Pass%"': '"60%"',
    '"Rush%"': '"40%"',
    '"Pass"': '37',
    '"Rush"': '24',
    '"No Play (Penalty)"': '42',
  },
  {
    '"Team"': '"CLE"',
    '"GMs"': '5',
    '"Plays"': '64',
    '"Sec/Snap"': '30.5',
    '"No-Huddle"': '"6%"',
    '"Pass%"': '"49%"',
    '"Rush%"': '"51%"',
    '"Pass"': '31',
    '"Rush"': '33',
    '"No Play (Penalty)"': '39',
  },
  {
    '"Team"': '"MIA"',
    '"GMs"': '4',
    '"Plays"': '48',
    '"Sec/Snap"': '26.4',
    '"No-Huddle"': '"3%"',
    '"Pass%"': '"65%"',
    '"Rush%"': '"35%"',
    '"Pass"': '31',
    '"Rush"': '17',
    '"No Play (Penalty)"': '57',
  },
  {
    '"Team"': '"HOU"',
    '"GMs"': '5',
    '"Plays"': '51',
    '"Sec/Snap"': '29.3',
    '"No-Huddle"': '"4%"',
    '"Pass%"': '"49%"',
    '"Rush%"': '"51%"',
    '"Pass"': '25',
    '"Rush"': '26',
    '"No Play (Penalty)"': '48',
  },
  {
    '"Team"': '"NYG"',
    '"GMs"': '5',
    '"Plays"': '53',
    '"Sec/Snap"': '28.4',
    '"No-Huddle"': '"20%"',
    '"Pass%"': '"49%"',
    '"Rush%"': '"51%"',
    '"Pass"': '26',
    '"Rush"': '27',
    '"No Play (Penalty)"': '43',
  },
  {
    '"Team"': '"PIT"',
    '"GMs"': '5',
    '"Plays"': '65',
    '"Sec/Snap"': '29.2',
    '"No-Huddle"': '"4%"',
    '"Pass%"': '"51%"',
    '"Rush%"': '"49%"',
    '"Pass"': '33',
    '"Rush"': '32',
    '"No Play (Penalty)"': '33',
  },
  {
    '"Team"': '"NO"',
    '"GMs"': '4',
    '"Plays"': '49',
    '"Sec/Snap"': '30.3',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"58%"',
    '"Rush%"': '"42%"',
    '"Pass"': '29',
    '"Rush"': '21',
    '"No Play (Penalty)"': '52',
  },
  {
    '"Team"': '"TEN"',
    '"GMs"': '5',
    '"Plays"': '56',
    '"Sec/Snap"': '30',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"56%"',
    '"Rush%"': '"44%"',
    '"Pass"': '31',
    '"Rush"': '25',
    '"No Play (Penalty)"': '38',
  },
  {
    '"Team"': '"DEN"',
    '"GMs"': '5',
    '"Plays"': '56',
    '"Sec/Snap"': '27.1',
    '"No-Huddle"': '"6%"',
    '"Pass%"': '"58%"',
    '"Rush%"': '"42%"',
    '"Pass"': '33',
    '"Rush"': '23',
    '"No Play (Penalty)"': '32',
  },
  {
    '"Team"': '"LV"',
    '"GMs"': '5',
    '"Plays"': '63',
    '"Sec/Snap"': '29.9',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"54%"',
    '"Rush%"': '"46%"',
    '"Pass"': '34',
    '"Rush"': '29',
    '"No Play (Penalty)"': '34',
  },
  {
    '"Team"': '"IND"',
    '"GMs"': '4',
    '"Plays"': '59',
    '"Sec/Snap"': '27.3',
    '"No-Huddle"': '"13%"',
    '"Pass%"': '"52%"',
    '"Rush%"': '"48%"',
    '"Pass"': '31',
    '"Rush"': '28',
    '"No Play (Penalty)"': '47',
  },
  {
    '"Team"': '"DAL"',
    '"GMs"': '5',
    '"Plays"': '73',
    '"Sec/Snap"': '25.6',
    '"No-Huddle"': '"15%"',
    '"Pass%"': '"51%"',
    '"Rush%"': '"49%"',
    '"Pass"': '37',
    '"Rush"': '36',
    '"No Play (Penalty)"': '37',
  },
  {
    '"Team"': '"GB"',
    '"GMs"': '4',
    '"Plays"': '43',
    '"Sec/Snap"': '31.5',
    '"No-Huddle"': '"1%"',
    '"Pass%"': '"47%"',
    '"Rush%"': '"53%"',
    '"Pass"': '20',
    '"Rush"': '23',
    '"No Play (Penalty)"': '45',
  },
  {
    '"Team"': '"LAR"',
    '"GMs"': '5',
    '"Plays"': '49',
    '"Sec/Snap"': '28.3',
    '"No-Huddle"': '"4%"',
    '"Pass%"': '"48%"',
    '"Rush%"': '"52%"',
    '"Pass"': '24',
    '"Rush"': '26',
    '"No Play (Penalty)"': '43',
  },
  {
    '"Team"': '"ARI"',
    '"GMs"': '4',
    '"Plays"': '66',
    '"Sec/Snap"': '29.1',
    '"No-Huddle"': '"28%"',
    '"Pass%"': '"59%"',
    '"Rush%"': '"41%"',
    '"Pass"': '39',
    '"Rush"': '27',
    '"No Play (Penalty)"': '49',
  },
  {
    '"Team"': '"LAC"',
    '"GMs"': '5',
    '"Plays"': '65',
    '"Sec/Snap"': '27.8',
    '"No-Huddle"': '"6%"',
    '"Pass%"': '"67%"',
    '"Rush%"': '"33%"',
    '"Pass"': '44',
    '"Rush"': '21',
    '"No Play (Penalty)"': '32',
  },
  {
    '"Team"': '"SF"',
    '"GMs"': '5',
    '"Plays"': '72',
    '"Sec/Snap"': '30.3',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"51%"',
    '"Rush%"': '"49%"',
    '"Pass"': '37',
    '"Rush"': '35',
    '"No Play (Penalty)"': '46',
  },
  {
    '"Team"': '"WAS"',
    '"GMs"': '4',
    '"Plays"': '74',
    '"Sec/Snap"': '30',
    '"No-Huddle"': '"6%"',
    '"Pass%"': '"45%"',
    '"Rush%"': '"55%"',
    '"Pass"': '33',
    '"Rush"': '41',
    '"No Play (Penalty)"': '42',
  },
  {
    '"Team"': '"PHI"',
    '"GMs"': '5',
    '"Plays"': '65',
    '"Sec/Snap"': '25.9',
    '"No-Huddle"': '"21%"',
    '"Pass%"': '"54%"',
    '"Rush%"': '"46%"',
    '"Pass"': '35',
    '"Rush"': '30',
    '"No Play (Penalty)"': '44',
  },
  {
    '"Team"': '"BAL"',
    '"GMs"': '4',
    '"Plays"': '67',
    '"Sec/Snap"': '30',
    '"No-Huddle"': '"4%"',
    '"Pass%"': '"49%"',
    '"Rush%"': '"51%"',
    '"Pass"': '33',
    '"Rush"': '34',
    '"No Play (Penalty)"': '37',
  },
  {
    '"Team"': '"NE"',
    '"GMs"': '4',
    '"Plays"': '52',
    '"Sec/Snap"': '30.1',
    '"No-Huddle"': '"2%"',
    '"Pass%"': '"63%"',
    '"Rush%"': '"37%"',
    '"Pass"': '33',
    '"Rush"': '19',
    '"No Play (Penalty)"': '44',
  },
  {
    '"Team"': '"NYJ"',
    '"GMs"': '4',
    '"Plays"': '61',
    '"Sec/Snap"': '26.4',
    '"No-Huddle"': '"6%"',
    '"Pass%"': '"59%"',
    '"Rush%"': '"41%"',
    '"Pass"': '36',
    '"Rush"': '25',
    '"No Play (Penalty)"': '47',
  },
  {
    '"Team"': '"CIN"',
    '"GMs"': '4',
    '"Plays"': '69',
    '"Sec/Snap"': '27.6',
    '"No-Huddle"': '"0%"',
    '"Pass%"': '"59%"',
    '"Rush%"': '"41%"',
    '"Pass"': '41',
    '"Rush"': '28',
    '"No Play (Penalty)"': '43',
  },
];

module.exports = rotovizNeutralScriptOffensivePaceAndRunPassReportLastFiveWeeks;
